### ISSUE TITLE
Cancelling certain promise results in internal error

### ISSUE THREAD

**Issue by trkjgrdg** [petkaantonov/bluebird#1006]
new Promise(function() {
    }).tap(function() {
    }).cancel();

    Unhandled rejection TypeError: Cannot read property 'apply' of undefined

Looking through the stack trace, it looks like `this._rejectionHandler0` is `undefined`.

Bluebird 3.3.0 on Chromium 45.0.2454.101

**Comment by petkaantonov** [comment]
Fixed in 3.3.1
