### ISSUE TITLE
promisify the "request" module works in an unexpected way

### ISSUE THREAD

**Issue by danoctavian** [petkaantonov/bluebird#1007]
```
npm install bluebird request 
```
and then run this code.
```
var Promise = require("bluebird")
var request = Promise.promisify(require("request"));
Promise.promisifyAll(request);

request.getAsync("http://summessedupurlthatdoesntexist.com").then(page => {console.log(page.body)});
```

This places an error message in the page.body and does not through an exception catchable with .catch(...). UNLIKE the next snippet which does.
```
request.get("http://summessedupurlthatdoesntexist.com", (err, page) => {
  console.log(err)
})
```

The following library works as expected. 

https://github.com/request/request-promise

Did i use promisify wrong or is misbehaving?

**Comment by petkaantonov** [comment]
request-promise does far more than just promisifying. Id think the module would not even have a purpose if it was just promisifying.

**Comment by benjamingr** [comment]
@petkaantonov why it doesn't work is still a legitimate question IMO.

**Comment by petkaantonov** [comment]
because http errors are not errors in request. they callback successfully

**Comment by benjamingr** [comment]
Oh, I just read the OP code - that's expected behavior. My bad.

**Comment by danoctavian** [comment]
@petkaantonov from my experience they don't callback successfully. they throw an error (the error parameter is not null).

Hence my question of why the promisify does not follow that behavior.

i am fine with using request-promise for this use case but that still doesn't answer the question as to why a promisify call does not work.

you closed the issue but you did not address it.

**Comment by petkaantonov** [comment]
`request-promisify` has  a ton of additional logic rather than simply just promisifying (if it simply just promisified, the module would have no reason to exist). Among this additional logic is what turns non-successful HTTP error code responses into rejections.

In HTTP error cases  the vanilla `request` module doesn't callback with `err` rather it reports it as success. As promisify is just an API translation, it cannot automagically convert this success case into error without additional logic.

**Comment by danoctavian** [comment]
i understand you're argument but i did not see this behavior when running the following specific example, hence i was questioning what is the reason for which promisify doesn't deal with this.

```
var = require("request")
request.get("http://summessedupurlthatdoesntexist.com", (err, page) => {
  console.log(err)
})
```

this logs a non-null error.

**Comment by petkaantonov** [comment]
That's not a HTTP error but a DNS error, HTTP is not be involved at all in this case. 

Try to cause a HTTP error by doing e.g.:

```js
request.get("https://github.com/foo/bar/quz", (err, page) => {
  console.log(err)
})
```

**Comment by danoctavian** [comment]
alright i see what you're saying, thanks for taking the time to clear that up for me
