### ISSUE TITLE
False performance claims?

### ISSUE THREAD

**Issue by JoshuaWise** [petkaantonov/bluebird#1008]
I decided to [make a promise performance test](https://github.com/JoshuaWise/promise-comparison), and my test is showing me that bluebird is the absolute slowest of every library I tested (including native Promises).

I tested these implementations:

- [bluebird](https://github.com/petkaantonov/bluebird)
- [when](https://github.com/cujojs/when)
- [then/promise](https://github.com/then/promise)
- [native](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

Here's what the test does:

1. Wait 500 milliseconds before starting the test, because node needs time to stabilize its CPU/memory usage.
2. Create 10,000 pending promises that each resolve at `process.nextTick`.
3. Wait until all promises are resolved, and measure how long it took.
4. Repeat steps (2) and (3) 100 times, for more data points.

Here are the results I got:
![image](https://cloud.githubusercontent.com/assets/8255757/13067933/01c3ef28-d444-11e5-9745-d0d922743761.png)

**Comment by spion** [comment]
What results do you get for 100K promises and 10 datapoints?

**Comment by petkaantonov** [comment]
This comes up every now and then and the reason has so far always been that you have enabled long stack traces without knowing it

Check that:

- The environment variable `NODE_ENV` is not set to `development`
- The various `BLUEBIRD_` environment variables are not enabled
- You are not calling `Promise.config` or `Promise.longStackTraces()`
- `Promise.hasLongStackTraces()` returns `false` (it might be haveLongStackTraces I forgot)

**Comment by petkaantonov** [comment]
Also what version you are using? I could have messed up something with the monitoring PR which has potential to make really bad perf regression

**Comment by lextiz** [comment]
I have ran this benchmark on both 3.3.1 and 3.2.2 and the results are the same.

**Comment by lextiz** [comment]
BTW, this benchmark gives different results on my machine, the mean is:
bluebird.js: 1824801 promises/s
native.js: 545893 promises/s
promise.js: 2710532 promises/s
when.js: 1088571 promises/s

**Comment by spion** [comment]
I ran it for 100K promises, 10 datapoints and bluebird was faster than everything else but the number of promises/s was significantly smaller overall. Thats why I asked - it seems to me like the benchmark isn't quite stable.

**Comment by spion** [comment]
bluebird.js
Rate of raw promise lifecycles:	716767 promises/s

native.js
Rate of raw promise lifecycles:	193564 promises/s

promise.js
Rate of raw promise lifecycles:	581570 promises/s

when.js
Rate of raw promise lifecycles:	557073 promises/s

**Comment by JoshuaWise** [comment]
> This comes up every now and then and the reason has so far always been that you have enabled long stack traces without knowing it

Ah yes, I did have `NODE_ENV=development`.

After fixing that, I get these results:
```
bluebird.js
Rate of raw promise lifecycles:	1905698 promises/s

native.js
Rate of raw promise lifecycles:	387428 promises/s

promise.js
Rate of raw promise lifecycles:	3578438 promises/s

when.js
Rate of raw promise lifecycles:	1077647 promises/s
```

`then/promise` still seems to be outperforming bluebird, which comes in second place.

However, then I took @spion's recommendation and bumped the test up to 100k promises, and I got these results:

```
bluebird.js
Rate of raw promise lifecycles:	879554 promises/s

native.js
Rate of raw promise lifecycles:	260321 promises/s

promise.js
Rate of raw promise lifecycles:	793255 promises/s

when.js
Rate of raw promise lifecycles:	658497 promises/s
```

Finally `bluebird` is the fastest. I then tried with even more promises (more than 100k), and I got similar results.

Without actually measuring memory usage, this leads me to believe that `then/promise` has better raw performance than `bluebird`, but that it uses more memory, and thus when there were a very large number of promises, its memory allocation caused it to become slower than `bluebird`.

Is that a logical hypothesis? What else could have caused the difference in results when running the test at 10k promises and 100k promises?

**Comment by benjamingr** [comment]
@JoshuaWise these tests typically aren't very meaningful in isolation, that's why bluebird is benchmark against a suite simulating a real workload.

**Comment by JoshuaWise** [comment]
So, I just added fake data for the promises to pass around, and now `then/promise` is performing about as well as `when`, and `bluebird` is twice as fast as both.

After further investigation, it appears that `then/promise` performs 3x faster when you don't pass any arguments to the `resolve()` callback. Even if you just pass `undefined`, it's 3x slower suddenly.

**Comment by JoshuaWise** [comment]
After adding fake data to the stress test, and making sure bluebird's long stack traces are off, here are the new results (10k promises, 100 tests)
![image](https://cloud.githubusercontent.com/assets/8255757/13089272/e52019e4-d4bd-11e5-806f-585b2e0789f8.png)

**Comment by petkaantonov** [comment]
@JoshuaWise ok so I take it you are satisfied? Can we close this or?

**Comment by JoshuaWise** [comment]
Yes, we can close this :)

**Comment by benjamingr** [comment]
I just want to point out now that we "win" this benchmark that I still find it mostly meaningless in determining the performance characteristics of code using promises.
