### ISSUE TITLE
Possible leak with recursive `finally`s

### ISSUE THREAD

**Issue by jbourassa** [petkaantonov/bluebird#1009]
Hey,

I'm using bluebird latest (version 3.3.1) and there appears to be a leak when using `finally` to recurse. For example, this keeps leaking promises:

```javascript
var P = require('bluebird');
function tick() { return P.delay(100).finally(tick); };
tick();
```
![leaking-finally](https://cloud.githubusercontent.com/assets/224311/13079922/7ff45df6-d494-11e5-86ee-168c36671b4b.png)

Doing the same recursion with `then` does not leak promises:

```javascript
var P = require('bluebird');
function tick() { return P.delay(100).then(tick, tick); };
tick();
```

![not-leaking-then](https://cloud.githubusercontent.com/assets/224311/13080081/30bd1f88-d495-11e5-9a53-2d9063376b79.png)

------

Is this a leak, or am I missing something?

**Comment by jbourassa** [comment]
For what it's worth, this also happens on `2.10.2` (the version I originally noticed the leak with)

**Comment by petkaantonov** [comment]
This is actually unfixable given how finally works (not like `.then(fn, fn)`). Finally has to save the fulfillment value/rejection reason until the promise returned by the finally body is settled.

So you have the equivalent of:

```js
// F1
Promise.delay(100).finally(function() {
    // F2
    return Promise.delay(100).finally(function() {
        // F3
        return Promise.delay(100).finally(function() {
            // F4
            return Promise.delay(100).finally(function() {
                // F5
                return Promise.delay(100).finally(function() {
                    // ...
                }) // Only now can get rid of F5's value/reason
            }) // Only now can get rid of F4's value/reason
        }) // Only now can get rid of F3's value/reason
    }) // Only now can get rid of F2's value/reason
}); // Only now can get rid of F1's value/reason
```

Each iteration of the loop adds one more value/reason to save while not one of them could be get rid of. So I don't see how it's possible to implement without leaking in this case.

**Comment by jbourassa** [comment]
Thanks for looking into it. After a bit more investigating, I understand which property of `finally` makes this behaviour "by design". Your comment vas very helpful.
