### ISSUE TITLE
Possible reflection issue in .each() and .filter() ?

### ISSUE THREAD

**Issue by iaean** [petkaantonov/bluebird#1011]
Running the following snippet ([see the full gist](https://gist.github.com/iaean/cbc00c5e7e9834db8626)) via node
```javascript
p0.then(function() {
  var p1 = delayResolve(500);
  var p2 = delayReject(300);
  var p3 = delayResolve(400);
  return Promise.all([p1,p2,p3].map(function(p) { return p.reflect(); })) })
.each(function(p) {
  return p.isFulfilled() ? p.value() : null; })
.then(function(r) {
  console.log(JSON.stringify(r)); });
```
results in
```javascript
[{"_bitField":268435457,"_settledValue":500},
 {"_bitField":135266305,"_settledValue":300},
 {"_bitField":268435457,"_settledValue":400}]
```
other than the expected ```[500,null,400]``` produced by ```.map()```.

Is this a bug in bluebird's node branch or do I something wrong in composition?

I'm always excited to hear from you.
Best regards

**Comment by benjamingr** [comment]
`each` does not mutate the value of a promise resolution. It iterates your array and then returns the original input. Did you want to use another `map`?

**Comment by benjamingr** [comment]
Or `mapSeries` if you want "sequential" behavior.

**Comment by iaean** [comment]
@benjamingr, thanks a lot for your reply. The sequential pattern via ```.mapSeries()``` is exactly what I need, but unfortunately replacing ```.each()``` with ```.mapSeries()``` in the block above throws: ```TypeError: p0.then(...).mapSeries is not a function```. See the stack trace at the end of this [gist](https://gist.github.com/iaean/cbc00c5e7e9834db8626)...

**Comment by benjamingr** [comment]
Make sure you're using a recent version of bluebird it's relatively new.

Here is a working example http://bluebirdjs.com/docs/api/promise.mapseries.html

I can't read your code your placement of `})` is very strange :P

**Comment by iaean** [comment]
@benjamingr, hoping it's better now...
bluebird@**3.3.1** and node@**4.2.6** resulting in ```TypeError: p0.then(...).mapSeries is not a function```.

```javascript
p0.then(function() {
  var p1 = delayResolve(500);
  var p2 = delayReject(300);
  var p3 = delayResolve(400);
  // resolved on settleAll (http://bluebirdjs.com/docs/api/reflect.html)
  return Promise.all([p1,p2,p3].map(function(p) {
    return p.reflect(); }));
})
.mapSeries(function(p) {
  return p.isFulfilled() ? p.value() : null;
})
.then(function(r) {
  console.log(JSON.stringify(r));
});
```

**Comment by petkaantonov** [comment]
`p0` is probably a native promise.

**Comment by iaean** [comment]
No. It's a bluebird promise instanced as
```javascript
var p0 = delayResolve(200);
```
or
```javascript
var p0 = Promise.resolve(delayResolve(200));
```
with
```javascript
var Promise = require('bluebird');

function delayResolve(t) {
  return new Promise(function(resolve, reject) {
    setTimeout(function() { resolve(t); }, t); }); }

function delayReject(t) {
  return new Promise(function(resolve, reject) {
    setTimeout(function() { reject(t); }, t); }); }
```
I could provide a small gist to reproduce that issue...

**Comment by petkaantonov** [comment]
right after you require Promise, can you log what `Promise.prototype.mapSeries` is?

**Comment by iaean** [comment]
@petkaantonov: ```ùndefined``` Here is a new [gist](https://gist.github.com/iaean/8bb010727c6ec576e38e)...

**Comment by petkaantonov** [comment]
In that case you are requiring different bluebird version than you think you are

**Comment by iaean** [comment]
Oh, damn stupid... You are so right!
Sorry for confusion and thanks a lot for your guidance and investigation.
Best regards
