### ISSUE TITLE
[Feature request] Support react-native

### ISSUE THREAD

**Issue by vespakoen** [petkaantonov/bluebird#1013]
1) What version of bluebird is the issue happening on?
3.3.1 (latest)
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
React Native 0.20 (using react-native packager), node 5.4.1, npm 3.3.12
3) Did this issue happen with earlier version of bluebird?
Probably, yes

When bluebird is required inside of a react-native project, it crashes because it assumes when it is not running on node.js that it is running in a browser.

In react-native the document is not present and it throws an error.

**Comment by benjamingr** [comment]
@vespakoen can you please share the error and stack trace? 

I think it's a platform we generally want to support.

**Comment by vespakoen** [comment]
Ah, I had "Pause On Caught Exceptions" enabled, it seems to catch / handle it fine when I play through the error.

My mistake (btw, it did seem to be an actual problem in the past: https://github.com/petkaantonov/bluebird/issues/550)
