### ISSUE TITLE
Ten Thousand Stars 

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#1021]
Bluebird just passed 10,000 stars on GitHub :bird: :balloon: :balloon: :balloon: :bird: 

We'd like to thank all the support and great work from everyone. This has been a fun ride and we'd like to thank you all. The project has over 6 million monthly downloads and is one of the most popular NodeJS packages.

We'd like to celebrate this occasion (inspired by [Ramda](https://github.com/ramda/ramda/issues/1593)) by giving away a few bluebird coffee* mugs. 

Below are everyone who pushed code minus @petkaantonov @spion and myself. This can be a small fix like a typo in the docs or a large fix. 

We will be giving two mugs at random to two bluebird contributors.

If you would like to be _excluded_ from consideration, please let me know in the comments below. 

(List ordered alphabetically)

@Artazor
@Dashron
@JonAbrams
@Joris-van-der-Wel
@L8D
@MadaraUchiha
@Matthew-Davey
@MetaMemoryT
@Page-
@alexanderkjeldaas
@alubbe
@andyfischer
@anvaka
@askhogan
@azu
@bcaudesaygues
@bergus
@bjouhier
@bryanburgers
@calvinmetcalf
@chetbox
@codeNgJon
@cscott
@cspotcode
@d6u
@dantman
@demmer
@designeng
@dotnil
@dungsaga
@evanlucas
@fasterthanlime
@floatdrop
@gabrielf
@gdi2290
@gordonwoodhull
@grncdr
@hawkrives
@hvrauhal
@iarna
@jamesmanning
@jasonmerino
@jimlloyd
@jmm
@jonasi
@jordangray
@kevinburke

(Next comment with more people as GH excludes more than 50 pings per comment)
(* tea has been tested to work, but is not an officially supported platform)

**Comment by benjamingr** [comment]
@kevinoid
@kimmobrunfeldt
@lextiz
@lvivski
@m-lautenbach
@madarche
@marchant
@markstos
@matiaszanolli
@mbezjak
@mgenware
@mhamann
@mhelvens
@mk-pmb
@nickclaw
@nikolas
@nizhu
@noahadams
@noseglid
@nubs
@odziem
@oliversalzburg
@parkerault
@petehunt
@phillipalexander
@pilwon
@pjeby
@pon
@richguan
@samccone
@samcday
@shinnn
@southpolesteve
@srguiwiz
@stites
@suguru03
@sukima
@teppeis
@tgriesser
@thataustin
@timeimp
@vitaly-t
@wavded
@wcp1231
@xaka
@yonjah
@yotamofek
@yourcelf
@ysagal
@yzarubin

**Comment by vitaly-t** [comment]
Ask people to remove a few, and then you can celebrate it more than once! :) :) :)

**Comment by oliversalzburg** [comment]
:+1: :coffee:

**Comment by noseglid** [comment]
woho :dancer:

**Comment by d6u** [comment]
🐦🎉

**Comment by m-lautenbach** [comment]
Feeling honored, great library!

**Comment by satazor** [comment]
Congrats!

**Comment by wavded** [comment]
Woohoo!  Great job!

**Comment by teppeis** [comment]
wow! :smile_cat:

**Comment by odziem** [comment]
Congratulations, well deserved! :shipit:

**Comment by jasonmerino** [comment]
Very cool! Congrats. :)

**Comment by azu** [comment]
Congratulations :congratulations:

**Comment by Artazor** [comment]
Congrats! -)

**Comment by L8D** [comment]
Is there anywhere where I can buy a bluebird mug if I don't win one?

**Comment by tyscorp** [comment]
:+1: on buying bluebird mugs

**Comment by martin-williams** [comment]
:+1: for mugs

**Comment by gdi2290** [comment]
:+1: congrats on 10k

**Comment by Joris-van-der-Wel** [comment]
haha nice idea, congrats.

**Comment by yzarubin** [comment]
Congrats!! :bird:

**Comment by gordonwoodhull** [comment]
It is no wonder. Bluebird saved our project from callback hell, and I'm sure many others.

Congratulations!

**Comment by lextiz** [comment]
Congratulations!

**Comment by MetaMemoryT** [comment]
Congrats!!

**Comment by ruimarinho** [comment]
A well deserved recognition of your work. Congrats!

**Comment by jmm** [comment]
Congrats!

**Comment by yonjah** [comment]
Congrats! this is an awesome project

**Comment by ericmdantas** [comment]
Congrats!

**Comment by dungsaga** [comment]
Congrats on first 10 thousand stars! I hope you will add tea as an officially supported platform :)

**Comment by phpnode** [comment]
Congratulations!

**Comment by timeimp** [comment]
Without a doubt, one of the best communities.

Congratulations!

**Comment by benjamingr** [comment]
Just updating with a timeline - I'm flying on a work holiday this Wednesday - I'l coming back on Sunday and I'll go to the store to make the mugs. I'll then run the random and post the winners here. Cheers.

**Comment by benjamingr** [comment]
Also, public thank you to @phpnode who has always been a big help with bluebird and related issues :)

**Comment by benjamingr** [comment]
Sorry, mugs are on their way - finally shipping to me where I'll send them on.

**Comment by benjamingr** [comment]
Congratulations @lextiz @tgriesser :tada: :tada: :tada:

You have been blessed by the mystic random number picker.

Please send me a shipping address to benji [at] tipranks [dot] com for your free complimentary mug :) 

(If either participant does not respond in 48 hours, a new winner will be chosen).

**Comment by m-lautenbach** [comment]
Can these mugs be bought somewhere?
