### ISSUE TITLE
no promise returned warning for a constructor

### ISSUE THREAD

**Issue by mfrost66** [petkaantonov/bluebird#1028]
I have a scenario where I'm creating a promise in a constructor.  This is by design (all the methods in the class gate on the promise).  The issue is that I can't find a way to suppress the warning other than disabling all warnings.  That said, I think it's bad form to do a return at the bottom of the constructor.

Possible solutions?  

* allow error suppression comment (standard in many compilers) so its not all or nothing
* don't generate warning inside constructors

Example

```javascript

function FileWrapper() {
  if( !(this instanceof FileWrapper())
    return new FileWrapper();  // causes warning if even null returned below 
  this.ready = loadFileAsync();

  return null; //this doesn't suppress
}
function otherMethod() {
  return this.ready.then(...);
}
```

**Comment by benjamingr** [comment]
What's the code of loadFileAsync?

**Comment by benjamingr** [comment]
Also note, that you need to suppress possibly unhandled rejections most likely by calling `loadFileAsync.suppressUnhandledRejection()`.

**Comment by petkaantonov** [comment]
Look at the stack trace of the warning

**Comment by mfrost66** [comment]
@benjamingr @petkaantonov I'm not having trouble understanding the warning or reason for it - at least, I don't think I am.  I'm highlighting that the warning is not meaningful or suppressible when a promise is created inside of a constructor, as you couldn't return the promise even if you wanted to.  I believe this to be a valid and useful pattern; starting a background process on creation of an object/class.

**Comment by benjamingr** [comment]
That's not the warning means. Post the stack trace and the function we asked for here so we can help you.

**Comment by mfrost66** [comment]
I'm not looking for help, was trying to be helpful.  Since that doesn't seem to be working, I'll go ahead and close the issue.

**Comment by spion** [comment]
@mfrost66 bluebird only reports this error for promises created in `then` handlers. So only for things like:

```js
somePromise.then(function(val) {
  otherAction() // no return in this handler
  new FileWrapper() // great but still no return
  return new FileWrapper() // okay, this will clear the warning.
});
```

Can you post a minimal runnable example that reproduces your error?

**Comment by benjamingr** [comment]
@mfrost66 to clarify - the code you have shown is _not_ where the error is coming from. You most likely have a bug in your code somewhere _else_. This is why Petka asked for the stack trace.

I understand you came here because you wanted to help - we appreciate that, honest. I just want to make sure we're on the same page here - you are not getting the error for the code you've shared.

**Comment by mfrost66** [comment]
@benjamingr thanks for the clarification.  
@spion thanks for the pointers on what causes warnings

Removing uses of Promise.method wrappers gave me a much better (deeper) stack trace.  I still haven't found the issue, but agree it has nothing to do with constructors.
