### ISSUE TITLE
This in executor is bound to window

### ISSUE THREAD

**Issue by AndreLouisCaron** [petkaantonov/bluebird#1031]
I'm currently using bluebird v3.3.3 in Chrome 48 on Windows.  I have not tried other versions.

I would like to capture a reference to the promise in the revealing constructor.  Here is an example:

```
return new Promise(function(resolve, reject) {
    var promise = this;  // is Window, was expecting Promise.
});
```

---

The use case is a notification queue that returns a promise that will be fulfilled when a notification matching a predicate arrives.

I really want this API to handle requesting a notification after it has already arrived to work around a natural race condition (the server may push information faster than I can consume the events).

Currently, my queue has the following prototype:

```
var NotificationQueue = function() {

  // Fulfill immediately if a notification matching the predicate
  // is already queued, else queue the promise for a future
  // `.dispatch()` that matches the predicate.
  self.wait = function(predicate, resolve, reject) {
  };

  // Dispatch immediately if a the notification matches the predicate
  // for a queued promise, else queue the notification to satisfy a
  // future `.wait()` for which the predicate accepts the notification.
  self.dispatch = function(notification) {
  };
};
```

The caller will do something like this:

```
function nextNotification(predicate) {
  var q = ...;
  return new Promise(function(resolve, reject) {
     q.wait(predicate, resolve, reject);
  });
}
```

If the promise is cancelled before  `.dispatch()` is called, the `resolve`,  `reject` pair for the promise will still be in queue.

The thing is that `.dispatch()` must not satisfy multiple waiters, so I need to skip cancelled promises.  I'd like to call `Promise.isCancelled()` in `.dispatch()`, but I can't get a hold of the promise from there.

I'd like to change my prototype to `NotificationQueue.wait(predicate, promise, resolve, reject)`, so that I can change the caller to do this:

```
function nextNotification(predicate) {
  var q = ...;
  return new Promise(function(resolve, reject) {
     q.wait(pred, this, resolve, reject);
  });
}
```

However, `this` in that context resolves to the `Window` object rather than the promise.

**Comment by AndreLouisCaron** [comment]
BTW, I'm an absolute beginner in JS, so if you have any advice I'm all ears.

However, taking a look at the code, it seems to me like this could be fixed by adding this line in the `Promise` constructor:

```
    if (executor !== INTERNAL) {
        check(this, executor);
        executor = executor.bind(this);  // adding this resolves my issue.
        this._resolveFromExecutor(executor);
    }
```

See [promise.js, line #78](https://github.com/petkaantonov/bluebird/blob/master/src/promise.js#L78).

If I send in a patch for this, any chance that you will accept this?

Thanks!

**Comment by petkaantonov** [comment]
It is supposd to be global or undefined as per the ES6 specification, however I don't recall any practical reason for not passing the promise as `this` and we are not fully compliant to that spec anyway. @benjamingr @spion

**Comment by benjamingr** [comment]
No - let's not deviate any further from the spec. It should be as easy as possible for people to migrate from native ES6 promises to bluebird.

**Comment by AndreLouisCaron** [comment]
I'm having trouble following you guys.  Assuming "the spec" refers to the [Promises/A+](https://promisesaplus.com/), the only part of the spec that mentions the value of `this` is this footnote:

> 3.2 That is, in strict mode this will be undefined inside of them; in sloppy mode, it will be the global object.

However, this is only referred to from section 2.2.5:

> 2.2.5 `onFulfilled` and `onRejected`;  must be called as functions (i.e. with no `this` value). [3.2]

I have no problem obtaining a reference to the promise by my own means in that context.

I was referring to the accessing the promise as `this` inside the constructor, which is before I have any possibility to gain a reference to the promise (because the constructor hasn't completed yet).

**Comment by spion** [comment]
@AndreLouisCaron if we do this, it could break currently valid sloppy-mode code that uses ES6 promises as well as libraries where `Promise` is injectable. I suppose its a fairly minor thing, but personally I'd rather avoid any sort of breakage for this use case.

@petkaantonov are there examples except for inheritance where replacing ES6 `Promise` with bluebird will cause breakage?

**Comment by petkaantonov** [comment]
there is no breakage in that direction.

**Comment by benjamingr** [comment]
@petkaantonov what about the native promises memory leak?

**Comment by petkaantonov** [comment]
i mean there is no breakage when migrating from es6 to bluebird regardless of this value inside executor

**Comment by spion** [comment]
btw, I would solve the original problem like so:

```js
function nextNotification(predicate) {
  var q = ...;
  var promise;
  return promise = new Promise(function(resolve, reject) {
     q.wait(pred, promise, resolve, reject);
  });
}
```

**Comment by AndreLouisCaron** [comment]
After thinking about his, I guess I can solve my problem using an indirect reference like so:

```
var ref = {p: null};
var p = new Promise(function(resolve, reject) {
    // queue `ref` here instead of `this` (`ref.p` will be used later).
});
ref.p = p;

// starting from here, `ref.p` can be used inside promise.
```

While this is ugly and only works in a limited case (can't refer to the promise inside the constructor), I guess it's portable to all implementations and it solves my problem.

Ouf of curiosity (bacause I'm somewhat new to all of this), does anybody know why the spec says the callbacks *must* be called as functions without a `this` value?

**Comment by petkaantonov** [comment]
I don't know, I mostly use the surrounding `this` anyway
