### ISSUE TITLE
Error thrown from a within a returned promise does not get caught in main promise chain

### ISSUE THREAD

**Issue by adambuczynski** [petkaantonov/bluebird#1032]
1) What version of bluebird is the issue happening on?
3.2.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 5.5.0, Mac OS X 10.10.5

3) Did this issue happen with earlier version of bluebird?
Haven't tried.

The problem is as follows. For an old piece of hardware which communicates via serial port, I have to send a buffer of data which may or may not get acknowledged by the hardware (depends on if it's busy doing other stuff). If it doesn't get acknowledged, it just silently fails (there is no callback or feedback), so I have to let it timeout and try again. For this reason, I am using the deferred pattern, because I need to store the deferred and resolve the promise later if an acknowledgement from the hardware does come back. This happens completely independent of the data being sent to the hardware, so there are no callbacks to rely on.

(I was a bit disappointed to find out deferred could not be created more easily in Bluebird anymore, because there are valid use cases in my opinion. But that's not the point of this issue.)

Anyway, I've created a mock setup with the same pattern as is used with the real software in the following JSbin: https://jsbin.com/lozeyo/1/edit?js,console

The function `sendBuffer` gets called which will attempt to send data and then wait for a response. If it times out, it will retry for a specified amount of times.

If you set `NUM_RETRIES` in the JSbin to `2`, you can see that on the 3rd attempt the `mockResponse` function will send back some fake data and resolve the deferred. When this happens, the resolution is propagated to the main promise chain which initiated the command, and all works well.

However, setting `NUM_RETIRES` to `1` illustrates the failure case, which I think is not working properly. In this case, the deferred gets rejected with a timeout error, but this error is *not* caught in the main promise chain. Instead, Bluebird complains about an `Unhandled rejection Error`.

Is this a bug in Bluebird? Shouldn't the error be handled in the main promise rejection handler (since `sendBuffer` is returning a promise which throws an error)? Or am I missing something here?

**Comment by petkaantonov** [comment]
You are not returning the promise chain, but the original `promise`.

Try `var ret = promise.catch(....); ... return ret`

**Comment by adambuczynski** [comment]
That shouldn't matter though, should it? Is this Bluebird specific behaviour?

**Comment by petkaantonov** [comment]
Promises don't mutate. When you chain a promise it always returns a *new* promise. If you return the original promise, it doesn't work at all. Watch:

```js
function doSomething() {
    var promise = Promise.resolve(1);

    promise.then(function(value) {
        return value + 2;
    }).then(function(value) {
        return value + 3;
    });

    return promise;
}

doSomething().then(function(result) {
    // Logs 1 instead of 6
    console.log(result);
})
```

**Comment by adambuczynski** [comment]
Right. Interesting that in 2 years of working with promises this has never come up for me. Thanks for clarifying.

So in my example, it was resolving because I was always resolving the original promise, but the rejection was happening further down the chain, hence why it didn't bubble.
