### ISSUE TITLE
Promise.map synchronously called

### ISSUE THREAD

**Issue by robinjoseph08** [petkaantonov/bluebird#1039]
1) What version of bluebird is the issue happening on?

**Bluebird v3.3.4**

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

**Node v5.1.1**

3) Did this issue happen with earlier version of bluebird?

**Not after Bluebird v2.9.13 for Bluebird v2.x**

When `.map` is called after a `Promise.resolve` with a synchronous value, it looks like the mapper function is called synchronously:

```js
// Actual: 1 3 4 5 2
// Expected: 1 2 3 4 5
console.log(1);

Promise.resolve([3, 4, 5]).map((i) => console.log(i));

console.log(2);
```

It looks like [this issue](https://github.com/petkaantonov/bluebird/issues/513) was fixed for a a patch release of v2.x, but it wasn't included in v3.x.

**Comment by petkaantonov** [comment]
That issue is about `.each`. It is unrelated to `.map` which is concurrent and out of order by design. To avoid it being accidentally in-order with immediate values it artificially processes items out of order so that devs realize this fact without having to read documentation.
