### ISSUE TITLE
"For library authors" doesn't exist anymore

### ISSUE THREAD

**Issue by naugtur** [petkaantonov/bluebird#1040]
In version 3+ extending bluebird via `var Promise = require("bluebird/js/main/promise")();` is not possible anymore and the documentation section "For library authors" referenced in multiple discussions doesn't exist anymore.

Please bring back "For library authors" in the docs or document that bluebird cannot be extended anymore.

**Comment by benjamingr** [comment]
Extending bluebird is still possible - this is a docs glitch, apologies.

**Comment by petkaantonov** [comment]
Did you try `release` instead of `main`?

**Comment by overlookmotel** [comment]
v3.4.0 also introduced a method `Promise.getNewLibraryCopy()` for this.

http://bluebirdjs.com/docs/api/promise.getnewlibrarycopy.html

**Comment by overlookmotel** [comment]
I think this issue can be closed now.
