### ISSUE TITLE
Problematic delay in calling onCancel function

### ISSUE THREAD

**Issue by kevinoid** [petkaantonov/bluebird#1041]
I really like the design of the cancellation support in 3.x, but ran into some difficulty using it due to the [delay invoking the `onCancel` function](https://github.com/petkaantonov/bluebird/blob/v3.3.4/src/cancel.js#L118).  To demonstrate the issue, consider the following Node.js example:

```js
var Promise = require('bluebird');
var stream = require('stream');

Promise.config({cancellation: true});

function read(readable) {
  return new Promise(function(resolve, reject, onCancel) {
    function doRead() {
      resolve(readable.read());
    }

    readable.once('readable', doRead);

    onCancel(function() {
      readable.removeListener('readable', doRead);
    });
  });
}

var passthrough = new stream.PassThrough();

var result1 = read(passthrough);
result1.cancel();

var result2 = read(passthrough);
result2.then(function(data) {
  console.log('Got data: ' + data);
});

passthrough.write('Hello');
```

This prints `Got data: null` since the `onCancel` function of `result1` is not invoked until after the `'readable'` event has been emitted which allows `result1` to grab the data before `result2`.

It looks like the delay invoking `onCancel` has been in place since 89af8102.  I assume the delay is intentional, but the reason is not obvious to me (and I couldn't find one in the issue tracker).  Is the delay necessary, or could it be removed or relaxed in order to avoid cases like the above example?

Thanks,
Kevin

**Comment by petkaantonov** [comment]
Resource management should be done with [`using`](http://bluebirdjs.com/docs/api/promise.using.html) or [`coroutine.defer` (not available yet)](https://github.com/petkaantonov/bluebird/issues/1014) or even[ `.finally`](http://bluebirdjs.com/docs/api/finally.html). Cancellation is not appropriate for this at all (which just has disinterest semantics) and if you need to rely on the `onCancel` function to be called, then it doesn't look like just a disinterest scenario.
