### ISSUE TITLE
Library version

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#1042]
Considering the following facts about this library:

* Huge user base
* Used on both server-side and client-side
* Frequent update schedule

It is asking to extend the library's root with a `version` object, similar to that of Angular JS:

```js
require('bluebird').version = {
    name: 'false-positives-slayer',
    full: '3.3.4',
    major: 3,
    minor: 3,
    build: 4
};
```

It will help with the diagnostics in libraries built on extensive use of bluebird.

**Comment by benjamingr** [comment]
Any example where this kind of detection is necessary?

**Comment by vitaly-t** [comment]
We are logging library versions whenever an error occurs, and sometimes they occur as a result of a package update, which one can easily see then. It's much easier to log things this way when your major library provides the version information.

**Comment by petkaantonov** [comment]
I presume `.version = "3.3.4";` is enough as that other info can be derived from it as needed

**Comment by vitaly-t** [comment]
@petkaantonov probably, but I showed how it is used in Angular.js ;) something for the lazies ;)

**Comment by vitaly-t** [comment]
@petkaantonov on the second thought though, no. You should include the version properties, because those make it possible to easily code around new library features, without having to parse the version every time.

**Comment by vitaly-t** [comment]
@petkaantonov also, it would be a good idea to extend every error thrown by the library with this property `version` ;)

**Comment by vitaly-t** [comment]
Something simple, like this:
```js
function Version() {
    this.name = 'false-positives-slayer';
    this.major = 3;
    this.minor = 3;
    this.build = 4;
    this.full = this.major + '.' + this.minor + '.' + this.build;
}

// returns the full version as the default console output;
Version.prototype.inspect = function () {
    return this.full;
};
```

**Comment by petkaantonov** [comment]
Yeah I think it's unreasonable to expect all that to be implemented in bluebird. The users who really need more than a string can parse the string easily into such object using the semver module.

**Comment by overlookmotel** [comment]
For my purposes, just the full version string would be easily sufficient. But it *would* be really useful to have a `.version` property available. Some libraries allow a Promise implementation to be injected (i.e. "please return promises of this type") and it'd be useful to be able to know inside the library the version of bluebird you're dealing with e.g. to work around the different syntax of `Promise.promisify()` in v2.x and v3.x.

I'm not sure if the `.version` property is best added by something like this in the main codebase: `Promise.version = require('../package.json').version` or by adding it in the build step.

Please let me know your preference, and I'll submit a PR.

**Comment by vitaly-t** [comment]
@overlookmotel the property should definitely be available from the root:

```js
var ver = require('bluebird').version;
```

**Comment by overlookmotel** [comment]
@vitaly-t Yeah, I agree. But my question was what's the best way to implement it internally. i.e. how to set the value within bluebird, not access the value *from* bluebird.
