### ISSUE TITLE
Throw not calling catch method

### ISSUE THREAD

**Issue by andyrichardson** [petkaantonov/bluebird#1043]
**Version:**  3.3.4
**Node.js:** 5.60

`throw new Exception(Exception.database);`

results in following error:
**_Unhandled rejection (<{"id":1,"msg":"Database Exception"}>, no stack trace)_**

On the contrary
`reject(new Exception(Exception.database);`

causes no issues.

Conclusion: Throw catching is inconsistent

**Comment by benjamingr** [comment]
Can you please post a _self contained_ code example? It's not clear what you're talking about here.

**Comment by petkaantonov** [comment]
`throw` and `return` only affect the containing function, using promises doesn't change how the language works. `reject(..)` is just a plain function call that can reject arbitrary promise, not just the promise whose handler function the throw is contained in.

**Comment by andyrichardson** [comment]
Apologies for the lack of detail. Please see the amended post and re-open the case if you consider the bug to be a valid issue.

**Comment by benjamingr** [comment]
You're using the explicit construction anti-pattern twice which is causing faulty error handling in your code @andyrichardson - see http://bluebirdjs.com/docs/anti-patterns.html#the-explicit-construction-anti-pattern

**Comment by petkaantonov** [comment]
`new Promise` is not needed when you are delaing with APIs that already return a promise. You can write this equivalent code (for more, see [explicit construction anti-pattern](https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it)):

```js
class Database {
    static cypher(query, params){
        return db.cypher({
            query: query,
            params: params
        }).catch(function() {
            throw new Exception(Exception.database);
        });
    }
}
```

Your throw statement is indeed inside a different function, that's why it's not affecting the upper function:

```js
.catch(function onlyThisFunctionIsAffectedByThrowsAndReturnsInsideThisFunction() {
    throw new Exception(Exception.database);
});
```

**Comment by andyrichardson** [comment]
Thank you all for the feedback, apologies for any wasted time.
