### ISSUE TITLE
call props method  after then would not be applied

### ISSUE THREAD

**Issue by ChitaGideon** [petkaantonov/bluebird#1047]
```
promise.resolve({a:1:b:2}).props(console.log)//nothing print out and no error throw out
```
the doc never give an example 

http://bluebirdjs.com/docs/api/props.html

1) What version of bluebird is the issue happening on?
v3.3.4
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
 `node v5.4.1`
3) Did this issue happen with earlier version of bluebird?
I'm not sure.

**Comment by benjamingr** [comment]
You either need to use the static invocation version: `Promise.props({a:1, b:2}).then(...)` or you use the no argument version: `Promise.resolve({..}).props().then(...`. 

Nowhere in the documentation it is implied that `props` takes a fulfillment handler - this is like how `.all` behaves.
