### ISSUE TITLE
Feature request for Promise.loop()

### ISSUE THREAD

**Issue by jfriend00** [petkaantonov/bluebird#1053]
This is a feature request for the ability to call some async operation N times in sequence.  The idea is like Bluebird's existing `Promise.reduce()`, but there is no source array to iterate over.  

I see this requested pretty regularly on StackOverflow when people are trying to call an API with some sequence of requests where each request increases an index value.  There is no underlying iterable they are iterating, just a `for` loop with an index.

I think of this as `Promise.loop()`, but it could certainly have any appropriate name.  Here's the general idea:

```javascript
    // Create a sequenced loop from startLoop to endLoop (inclusive)
    // The iterator is called with whatever the previous promise returned and 
    //    must return a promise when it is done.
    // The iterator is called like this: iterator(result, index); where:
    //     result is the fulfilled value of the prior promise in the chain
    //     index is the current loop index
    Promise.loop = function(startLoop, endLoop, increment, iterator, initialVal) {
        var p = Promise.resolve(initialVal);
        for (var i = startLoop; i <= endLoop; i+= increment) {
            (function(index) {
                p = p.then(function(result) {
                    return iterator(result, index);
                });
            })(i);
        }
        return p;
    };
```

Sample usage example here: https://jsfiddle.net/jfriend00/rodrz6o3/

**Comment by benjamingr** [comment]
Hey, nice to see you here @jfriend00 , any particular reason this should not be a separate module? 

Alternatively, mind linking to some of those questions?

**Comment by jfriend00** [comment]
Obviously it works as a separate module.  It just seemed to be of similar or more utility as some of the other utilities you had built in and I thought it was one of the sequential iteration structures you had not yet included.  

I can look around for some of the links.  The one I came across today which triggered my thought that this should be a prewritten iteration structure because I've seen it a bunch of times is this one: http://stackoverflow.com/questions/36191637/returning-looped-get-requests-sequentially-using-q-js/36193971#36193971.  I've even seen people make up a dummy array just so they could use something like `Promise.mapSeries()` on it.

**Comment by Rush** [comment]
Also a point about using a library, I trust more in code that's commited to petkaantonov/bluebird rather than to some unknown repo, If I see some utility function in bluebird I'm more likely to use it.

**Comment by benjamingr** [comment]
Let's sum this up, I'm -1 on it. 

@petkaantonov @spion ?

**Comment by spion** [comment]
I think this should be handled by bluebird streams, once they become real.

Example crawler that finds the first bluebird link from reddit (with imaginary API):

```js
iterate(page => getNextPage(page), getFirstPage('/r/programming'))
.flatMap(page => page.links)
.skipUntil(link => link.innerText.contains("bluebird"))
.first()
.then(link => console.log("Article about bluebird", link.innerText, link.href));
```

**Comment by petkaantonov** [comment]
I'm sort of +0, this gets asked pretty often, but the ease at which you can do loops simply using recursion is why I'm not entirely +1.

**Comment by jfriend00** [comment]
Here's a slight different variation of need.  Whereas the original proposal was to sequence async items in a loop, this is a situation where you want to iterate with a for loop, but you want to know when all the async ops in the for loop are done and they can all be run in parallel.  Yes, you can manually collect the promises in an array and use Promise.all, but it could be useful to have a utility that does that for you.  Here's the example.  http://stackoverflow.com/questions/38572767/for-loop-in-promise-then.   Maybe one utility could be made to let you manage the async for loop results in either sequence or parallel.

**Comment by bergus** [comment]
I believe all you need is
```
function* loop(start, end, increment=1) {
    for (var i=start; i<end; i+=increment) yield i;
}
```
that you can use with `Promise.map` and `Promise.mapSeries`. No need for dummy arrays when we have iterators :-) I don't think we need an extra utility function for this.

**Comment by benjamingr** [comment]
Yeah, after playing with it a little I think I'm -1 on this. Given spion is -1 on this and petka is +0 I'm going to close at this point - but feel free to reopen or to publish this as a utility lib.
