### ISSUE TITLE
Possible memory leak with Promise.each

### ISSUE THREAD

**Issue by tdzienniak** [petkaantonov/bluebird#1057]
I'm using bluebird v3.3.4 running on node v4.4.0. Leaky code:
```javascript
const Promise = require('bluebird');

Promise.each(new Array(3000), () => {
	const longString = (new Array(1000000)).join('1');

	return Promise.resolve(longString);
});
```
Not leaky code:
```javascript
const Promise = require('bluebird');

Promise.each(new Array(3000), () => {
	const longString = (new Array(1000000)).join('1');

	return Promise.resolve(longString).then(() => void 0);
});
```

It seems that the results of the promises are stored somewhere, but they shouldn't be, at least this is what I understand reading the docs of `Promise.each`:

> Resolves to the original array unmodified, this method is meant to be used for side effects.

Issue is happening on earlier versions of bluebird too.

**Comment by tdzienniak** [comment]
I've noticed, that second snippet is also leaking memory when long stack traces are enabled. Is this desired behaviour?

**Comment by benjamingr** [comment]
@tdzienniak this is because each is currently implemented through mapSeries https://github.com/petkaantonov/bluebird/blob/master/src/each.js#L14-L17 - the behavior of `each` was modified in 3.0 and then reverted when people complained.

Note that this is _not_ a memory leak - it is merely wasteful behavior.

**Comment by benjamingr** [comment]
We can implement directly with `_iterate` and overriding shouldCopyValues https://github.com/petkaantonov/bluebird/blob/283412e2ab2cd45f4c513e9a16b361b348a527d5/src/promise_array.js#L164-L166 - petka, I can take a shot at it but it's probably faster for you to fix it than to me to fix it and you to verify.

**Comment by tdzienniak** [comment]
@benjamingr yes, I've noticed that it is implemented through mapSeries, which is why with conjunction with long stack traces is wasting a lot of memory. I spent a lot of time trying to figure out why my node process is running out of memory. Maybe a note in the docs describing this behaviour will be helpful for others?

**Comment by benjamingr** [comment]
Ping @petkaantonov

**Comment by petkaantonov** [comment]
@benjamingr feel free to give a shot at fixing it

**Comment by benjamingr** [comment]
@tdzienniak if you feel like it - I would appreciate it if you take a look at the code with the fix and see if it fixes the issue for you.

**Comment by tdzienniak** [comment]
@benjamingr ok, I can test the examples form my initial post.
