### ISSUE TITLE
Documentation bug for MySQL transaction example?

### ISSUE THREAD

**Issue by dlong500** [petkaantonov/bluebird#1062]
On the "Working with Callbacks" guide page (http://bluebirdjs.com/docs/working-with-callbacks.html) in the section on disposers in MySQL there is an example for working with transactions that calls a `db.getTransactionAsync` function, yet I see basically no reference anywhere (on the internet) to such a `getTransaction` function related to MySQL.

Can someone clarify what is going on here or is this example just not right?  I thought with the node-mysql library that transactions were started with the `beginTransaction` function on the connection object.

**Comment by petkaantonov** [comment]
In the example db is just any database handle object with that method, it's not MySQL handle

**Comment by dlong500** [comment]
Ok, it just seemed confusing because the section appeared to indicated a MySQL specific example.
