### ISSUE TITLE
Bluebird Promises and Domains

### ISSUE THREAD

**Issue by kineticfaction** [petkaantonov/bluebird#1065]
1) What version of bluebird is the issue happening on?
3.3.4

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
NodeJS 4.x

3) Did this issue happen with earlier version of bluebird?
Unknown	

I have a issue with throwing an error inside of a bluebird promise. Take the following code:

    var Promise = require('bluebird');
    var domain = require('domain');

    var problem = function() {
        return new Promise(function(resolve, reject){
            reject(new Error('Oops!'));
        });
    };

    domain.create()
        .on('error', function(e){
            console.log("Caught Error " + e.message)
            process.exit(1);
        })
        .run(function() {
            problem().done();
        });

I would expect to see Caught Error Oops! in the console. However it seems that the error is not caught inside of the domain and I'm seeing a fatal error and stack trace in the console.

**Comment by petkaantonov** [comment]
`.done` doesn't throw error, it exits the process. Instead of using done + domains, don't use anything and handle unhandled rejection in the `"unhandledRejection"` event

**Comment by kineticfaction** [comment]
The following solves my issue:

    var domain = require('domain');
    var Promise = require('bluebird');

    var problem = function() {
        return new Promise(function(resolve, reject){
            process.nextTick(function() {
                throw new Error('Oops!');
            });
        });
    };

    domain.create()
        .on('error', function(e){
            console.log("Caught Error " + e.message);
            process.exit(1);
        })
        .run(function() {
            problem().done(function(test) {
                console.log('Success');
            });
        });

While probably not the best solution it solves my specific problem.

**Comment by benjamingr** [comment]
Sorry this might sound harsh. That's a terrible solution that shows lack of fundamental understand of the promise exception handling model. Your code can do the same thing without domains and be rewritten as:

```js
  problem().then(function(test) {
            console.log('Success');
  }).catch(function(err) { 
      console.log("Caught Error", e.message);
      process.exit(1);
  });
```

Or better, as Petka suggested:

```js
process.on("unhandledRejection", e => logAndHandle(e));
```

Which would do it automatically for all promises created.

**Comment by kineticfaction** [comment]
As always with node it seems that when handling *programmer* errors there is much disagreement. 

This isn't something I am attempting out of choice, the code I provided above is mearly to illustrate an issue I have with bluebird. 

In an ideal world you would use a .catch() for every promise chain. However we dont live in an ideal world and I think using catches for every single chain isnt a practical solution. No one ever writes perfect code.

The problem with using one global catch for all uncaught exceptions/rejections such as both yourself and petka suggested, is that you lose the ability for subsystems to recover independently from the rest of the application.

**Comment by benjamingr** [comment]
@kimmobrunfeldt there are local events for different instances of bluebird, have a copy per system and recover that way. Or better, turn on warnings and make sure you "close" all your chains (returning promises) which would let you perform better fine grained error handling.

This isn't about error handling since for the very _least_ you should log unhandled rejections which bluebird does by default.

**Comment by spion** [comment]
Wouldn't the fix only involve not autodetecting node here?

https://github.com/petkaantonov/bluebird/blob/master/src/async.js#L37

**Comment by petkaantonov** [comment]
@spion no because that fixes something else. There is conflicting requirements. .done is meant to be never reached and is like an UNREACHABLE assertion. If you just want to report unhandled rejections there is no need to use done in bluebird and we already discourage that in .done documentation.
