### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by onury** [petkaantonov/bluebird#1073]
I dropped Q and started to use Bluebird in my Titanium app. But when I build for iOS, I get the following error described.

```
function Promise(executor) {
    this._bitField = 0; // <---- this line throws
```
Appcelerator does not output a trace for this error but app crashes and error dialog shown in the app reads: `Attempted to assign to readonly property at bluebird.js line 2697`.

Bluebird version 3.3.5 (latest) (development and production tested both)
Titanium SDK version 5.2.2.GA (latest)
Node version 4.3.0

**Comment by petkaantonov** [comment]
Doesn't seem to be specific to bluebird, there is nothing that would make it readonly
