### ISSUE TITLE
Using .reflect() gives Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by Clan-Utility** [petkaantonov/bluebird#1078]
While using reflect(), it gives Warning: a promise was created in a handler but was not returned from it

    Promise
          .all(promises.map(function (promise) {
            return Promise.resolve(promise).reflect();  // the original promise doesn't have a reflect method
          }))
          .each( ...

This warns is thrown at the line of 'return Promise.resolve(promise).reflect();'

**Comment by petkaantonov** [comment]
what version? Doesn't reproduce for me:

```js
var Promise = require("./js/debug/bluebird");

Promise.config({warnings: true})

var promises = [
    {then: function() {arguments[0](new Error("lol"))}}
];

Promise
      .all(promises.map(function (promise) {
        return Promise.resolve(promise).reflect();  // the original promise doesn't have a reflect method
      }))
      .each(function() {})
```

**Comment by benjamingr** [comment]
Not reproducing for me either with the above code. Going to close, feel free to comment with an example and we'll reopen.
