### ISSUE TITLE
Skip node packages for forgotten return warnings

### ISSUE THREAD

**Issue by jovinbm** [petkaantonov/bluebird#1082]
Is there a way to filter these stack traces to only specific path/scripts? It would be much more useful to narrow down the stack traces so that one can see the errors in their own code while preventing pollution from other external node packages.

For reference see `https://github.com/AriaMinaei/pretty-error#skipping-packages`

**Comment by petkaantonov** [comment]
You can attach a `"warning"` event listener and apply arbitrary filters etc in the listener function.

```js
process.on("warning", function(warning) {
     console.warn(warning);
});
```
