### ISSUE TITLE
Bluebird not playing nice inside heroku.

### ISSUE THREAD

**Issue by puneethnarayana** [petkaantonov/bluebird#1083]
I have built an app which has a bunch of endpoints doing a bunch of stuff.
I promisified a few modules using bluebird.

But when I deploy the project to heroku and try hitting it. Get the error that cannot find module bluebird.
Whereas it works perfectly fine in local and dependency has been clearly mentioned in package.json as well.

**Comment by petkaantonov** [comment]
I don't really know anything about heroku, sorry. It looks like a problem that could happen with any module, not just bluebird, so it isn't relaly on-topic her.e
