### ISSUE TITLE
bluebird with async causes warnings

### ISSUE THREAD

**Issue by gpresland** [petkaantonov/bluebird#1084]
bluebird@3.3.5
Node 5.11.0

When using a bluebird promise inside an async function with NODE_ENV=development, you receive `Warning: a promise was created in a handler but was not returned from it`. This gets to be extremely spammy. Is there a solution to this other than rewriting everything into promises and chaining them?

Here is a simple example:

```
const async = require('async');
const Promise = require('bluebird');

function promiseFunction() {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(), 1000);
  });
}

async.series([
  (callback) => {

    // Example
    // Do stuff here

    promiseFunction()
      .then(() => callback(null))
      .catch((err) => callback(err));
  },
  (callback) => {

    // Example
    // Do stuff here

    promiseFunction()
      .then(() => {

        // Example
        // Do stuff here

        callback(null);
      })
      .catch((err) => callback(err));
  }
], (err) => {
  (err) ? console.error(err) : console.log('done');
});
```

**Comment by spion** [comment]
If you are transitioning your project from callbacks to promises (or vice-versa), I'd recommend turning off the warning.

Otherwise, I'd recommend not mixing callbacks and promises:

```js
// do stuff here (1)
promiseFunction()
.then(_ => promiseFunction())
.then(_ => { /* do stuff here (2) */ })
.then(result => console.log('done'),
      error  => console.log(error))

```

**Comment by gpresland** [comment]
I'm leaning towards replacing `npm async` with `npm co` rather than rewriting everything to use promise chains. `bluebird` doesn't seem to throw warnings inside generators. This method will result in less code to change, and I get to keep a similar code layout.

Example for anyone who comes across this ticket in the future:
```
const co = require('co');
const Promise = require('bluebird');

function promiseFunction() {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(), 1000);
  });
}

(function () {
  co(function* () {
    // Exmaple
    // Do stuff here
    yield promiseFunction();
    // Example
    // Do stuff here
    yield promiseFunction();
    console.log('done');
  }).catch((err) => console.error(err));
}());

```

**Comment by tyscorp** [comment]
Bluebird has similar functionality to co with [Promise.coroutine](http://bluebirdjs.com/docs/api/promise.coroutine.html).

You can also just:
```js
const co = require('bluebird').coroutine;
```

**Comment by gpresland** [comment]
With @tyscorp's suggestion of using Bluebird's coroutines, I can do the following:

```
const Promise = require('bluebird');

function promiseFunction() {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(), 1000);
  });
}

(function () {
  Promise.coroutine(function* () {
    // Exmaple
    // Do stuff here
    yield promiseFunction();
    // Example
    // Do stuff here
    yield promiseFunction();
    console.log('done');
  })().catch((err) => console.error(err));
}());
```

**Comment by petkaantonov** [comment]
The warning has been improved in 3.4.3
