### ISSUE TITLE
Leave Disqus or find a way to disable the ads

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#1085]
We should migrate from disqus or disable it. Either is better than that crap.

![13148006_10153875283267013_1654730192_o](https://cloud.githubusercontent.com/assets/1315533/14943855/e584ab38-0fec-11e6-8a37-502a21c7b7bd.png)

**Comment by petkaantonov** [comment]
They should be disabled now... that's insane that they got suddenly enabled out of nowhere

**Comment by Phezit** [comment]
They seem to be back.

**Comment by petkaantonov** [comment]
ads are again removed

they updated their ad system which came with default enabled...
