### ISSUE TITLE
Feature request: Concurrent Promise#reduce

### ISSUE THREAD

**Issue by tejasmanohar** [petkaantonov/bluebird#1086]
`Promise#map` is concurrent, but it seems `Promise#reduce` is not.

**Comment by benjamingr** [comment]
`Promise#reduce` is intentionally not concurrent, I don't see how a concurrent `reduce` would even work. Of course, no one is stopping you from doing:

```js
var arr = arr.map(somePromiseReturningFn); // all promises generated here
arr.reduce((prev, curPromise) => {

});
```

Essentially, you can use the native `Array#reduce` for this.

**Comment by petkaantonov** [comment]
you cannot have order with concurrency

**Comment by tejasmanohar** [comment]
Is order a must for "reduce" though? For example, if I'm just summing a set of values (common use case for "reduce") resolved by Promises, order is not really relevant.

**Comment by benjamingr** [comment]
Right, use Array#reduce then

**Comment by dmethvin** [comment]
To your point about summing values, order can make a difference: http://jsbin.com/yokezutuka/1/edit?js,console

**Comment by spion** [comment]
Formally, if the operation is associative it can be made concurrent, otherwise it cannot.

**Comment by dmethvin** [comment]
Yes, exactly. Unfortunately computer addition isn't associative for many cases (loss of precision, integer overflow) but people often think so since math addition is associative and the notation looks similar.
