### ISSUE TITLE
Feature request: Concurrent Promise#each

### ISSUE THREAD

**Issue by tejasmanohar** [petkaantonov/bluebird#1087]
`Promise#map` is concurrent, and `Promise#each` is not. It would be nice to see a `Promise#eachConcurrent` (or similar) method that is the same as "map" except it does not transform anything but instead, simply returns `undefined` like "each" does.

**Comment by benjamingr** [comment]
```js
Promise.map(arr, fn).return(undefined);
```

**Comment by benjamingr** [comment]
The fact `each` doesn't have a return value is most likely a mistake and we didn't want to break peoples' code in 3.0 so we kept it this way and added `mapSeries`.

**Comment by petkaantonov** [comment]
you cannot have order with concurrency

**Comment by tejasmanohar** [comment]
@petehunt I realize :) - I was suggesting a `map` w/o return value. @benjamingr's solution works, but I think a convenience method would be worthwhile.
