### ISSUE TITLE
Locks up IE unless longStackTraces is turned off (even though it's the default)

### ISSUE THREAD

**Issue by adam-lynch** [petkaantonov/bluebird#1089]
>1) What version of bluebird is the issue happening on?

3.3.5

>2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

IE11 (and 10 I think too but not Edge I'm told by a team member)

>3) Did this issue happen with earlier version of bluebird?

No idea.

----

We switched from Q to bluebird and noticed that it crippled IE. It was very very slow and locked up for awhile as well. It was very hard to debug so I don't have that much info (sorry). I had a hunch that it was something to do with stack traces but then ruled it out because the default is to have `longStackTraces` turned off. Later though, I noticed that it was taking very long to call a function which immediately called `return Promise.resolve()`. I noticed that 96% of scripting was spent in a bluebird function to capture long stack traces and randomly hitting pause a few times in the debugger always stopped in that function (capturing the stack trace of the function that immediately resolved). Surprisingly, passing `longStackTraces: false` to `Promise.config` fixed everything. It's now way faster and doesn't lock up.

**Comment by petkaantonov** [comment]
It's not the default unless you used the development download

**Comment by adam-lynch** [comment]
Ah ok... then this doc is wrong: http://bluebirdjs.com/docs/api/promise.config.html. (We use bluebird via npm)

**Comment by adam-lynch** [comment]
Just saw this:

>Note that even though false is the default here, a development environment might be detected which automatically enables long stack traces and warnings.

Maybe that's the case. Not sure.

**Comment by petkaantonov** [comment]
do you have NODE_ENV=development?
On May 4, 2016 16:45, Adam Lynch <notifications@github.com> wrote:Just saw this:


Note that even though false is the default here, a development environment might be detected which automatically enables long stack traces and warnings.


Maybe that's the case. Not sure.

**Comment by adam-lynch** [comment]
No. We're using browserify btw.

**Comment by benjamingr** [comment]
I don't understand - bluebird should _not_ lock IE with long stack traces enabled.

If this happens it's a regression or a bug you found with your particular code (are you using rejections a lot?). We run bluebird 3.3.5 in production in IE9-10-11 with long stack traces and it works fine all the times and helps us find bugs. 

To be fair, we have a very low amount of rejections in our code - only for exceptional cases.

**Comment by adam-lynch** [comment]
>are you using rejections a lot?

Emmm maybe? Not sure what is a lot. 

So the function in question was somewhat deep... we map an array of promises to `eachPromise.reflect()`, pass that to `Promise.all` and then we loop over the results, checking which worked and which didn't, then call a function which calls a function which calls the function in question. Roughly.

**Comment by benjamingr** [comment]
I'm not able to reproduce this in IE11 IE10 or IE9 using latest bluebird. I'm sorry but I'm not sure what we can do without a test case - I just tried nesting a lot.

It might be a good idea to add a tool that warns if long stack traces are enabled and bluebird is slow in the future.

**Comment by eugene1g** [comment]
FWIW, I noticed a significant drop in performance when building with webpack vs using the minified file directly. As a rough guess, for me it ran at maybe 50% of the speed of core-js polyfill, and we use promises/async *a lot*.  Unfortunately, I haven't setup a test/benchmark harness and just switched to using the .min version directly.

I used ENV=production and the rest of the codebase (including React/Relay/our code) pretends to run at full speed/production mode.

**Comment by adam-lynch** [comment]
For the record: I was using Browserify.

**Comment by christophmegusta** [comment]
We have similiar issue. When we were upgrading our app from BB2 to 3, it locks and freezes in IE10-11. Sometimes even F12 Developer Tools dont open. It works when disabling the Long Stack Traces or when going back to BB2 (even with LST enabled).

We are building with gulp and uglify plugin using non-minified bluebird.js from bower as source (and do minification via gulp ourselves).

**Comment by haight6716** [comment]
I'm encountering this problem with BB 3.4.6.  I'm also using webpack to build.  IE11 on Windows 7 is slow, with the profiler showing a lot of time being spent in captureStackTrace.  Promise.config({longStackTraces: false}); seems to solve the problem.

**Comment by Lavoaster** [comment]
I have it reproducible in this repo: https://github.com/Lavoaster/bluebird-ie-issue

In `src/redux.js` the `submit` function has high chain of `.then`, which seems to block the UI whilst its being ran in IE.

I couldn't get it reproducible in a smaller build in the time I had to prepare this. I hope this helps.

**Comment by Lavoaster** [comment]
@benjamingr Would you prefer a new issue for this?
