### ISSUE TITLE
Report Errors After Resolve

### ISSUE THREAD

**Issue by NatalieWolfe** [petkaantonov/bluebird#1091]
1) What version of bluebird is the issue happening on?
Tested on 3.3.5 and 3.0.0.

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Probably all, tested on Node 4.4.3 and 6.0.0.

3) Did this issue happen with earlier version of bluebird?
Yes.

---------------

## Situation

Currently, if you throw an exception _after_ calling `resolve` in the promise's executor that exception is swallowed by bluebird with no notice of the problem. This silent suppression of errors can cause lingering bugs in the code that are hard to detect without exhaustive testing.

For example, take this commit niftylettuce/node-email-templates@80589c8fb7656111eefe94c11b77c78dd36be2f1 which resolves the promise and then causes the error "Cannot call method 'then' of undefined." This error is suppressed by bluebird, and it was allowed to linger in the code base for 2 months before it was noticed only because a different module that was instrumenting bluebird broke.

## Request

Rather than silently dropping this error on the floor, bluebird should report the exception, possibly as an `uncaughtException` on the process.

### bb-swallowing.js
```js
var Promise = require('bluebird')

process.on('unhandledRejection', () => {
  console.log('Unhandled rejection!');
});

process.on('uncaughtException', () => {
  console.log('Uncaught exception!');
});

(new Promise((resolve, reject) => {
  resolve(1)
    .undefinedMethod();
})).then((res) => {
  console.log('resolved', res);
}, (err) => {
  console.log('rejected', err);
});
```

### Current Output
```
$ node bb-swallowing.js
resolved 1
```

### Desired Output
```
$ node bb-swallowing.js
Uncaught exception!
```

**Comment by petkaantonov** [comment]
I don't think the proposed solution is feasible because it can crash the process. It's also odd to run code after resolving or rejecting the promise, the entire purpose of the executor function is just to resolve or reject the promise.

**Comment by NatalieWolfe** [comment]
Yeah, it is definitely bad to continue performing logic after calling `resolve`, but in the case of the commit I linked to it was an accident caused by reformatting the code. I believe what they intended to do was this:

```js
resolve(
  renderFile(this.files.style, locals)
    .then((style) => {
      this.style = style
      debug('Finished rendering stylesheet')
      return style
    })
)
```

The `.then` statement was supposed to chain off the return value from `renderFile` and then resolve with the promise from `.then`. But they mistakenly left the `.then` call outside of `resolve`'s parenthesis.

I believe emitting the `uncaughtException` event (and crashing the application) in this scenario is the correct behavior, if the code was _not_ within a promise then the process would have crashed and the mistake would have been immediately found.

**Comment by NatalieWolfe** [comment]
I understand not adding this within v3 since it could break existing code that "works," but it could go into v4.

**Comment by benjamingr** [comment]
-1 this breaks compatibility with native promises. This is as strange as resolving/rejecting multiple times. 

I definitely see the merit in an opt-in warning for this though.

**Comment by NatalieWolfe** [comment]
This breaks compatibility with native _less_ than the `.spread` method. Bluebird already adds several new methods at both the class and instance levels meaning developers have to be aware of what promise library each of their dependencies use meaning perfectly good code can break because a dependency changed a dependency (e.g. from bluebird to native).

Only code that is actually broken is affected by reporting these errors as uncaught exceptions.

**Comment by benjamingr** [comment]
That's not true - the rule of thumb is that bluebird can be a drop in replacement for native promises - this breaks that for a quirk.

**Comment by NatalieWolfe** [comment]
This breaks that for telling people when their code is broken. :)
