### ISSUE TITLE
Feature request: suppressUnhandledRejections return promise instance

### ISSUE THREAD

**Issue by focusaurus** [petkaantonov/bluebird#1101]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

3.x

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

all

3) Did this issue happen with earlier version of bluebird?

N/A (feature request)

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I would like to suggest an API change (semver major) to have `.suppressUnhandledRejections()` return the existing promise instance, allowing chained calls such as:

`return Bluebird.reject(new Error('ouch')).suppressUnhandledRejections()`

This is a pattern I use a lot in my unit tests where I want to prepare a rejection, then run the code under test, inject the rejected promise into the code path via mock/stub (sinon, testdouble, etc), then the code under test attaches its rejection handlers, and finally the test code path completes. Currently I need a separate helper method to avoid bluebird printing errors about potentially unhandled rejections.

**Comment by spion** [comment]
Why not create a new promise on demand instead?

**Comment by focusaurus** [comment]
Due to the design of the `testdouble` mocking library I'm using (which is common to most of them AFAIK), the results are specified ahead of time, then the code under test is executed, then assertions are made on the result.

**Comment by spion** [comment]
Afaik, `thenDo` can be used to return a new rejection.

**Comment by focusaurus** [comment]
I don't believe `.thenDo` can alter or affect what is returned from the testdouble function, which is controlled by `.thenReturn`. My understanding is `.thenDo` is for side affects only. If I want to pre-suppress the promise, I can just do:

```
  const down = new Error('DB is down')
  const downPromise = Bluebird.reject(down)
  downPromise.suppressUnhandledRejections()
  td.replace(User, 'findAll')
  td.when(User.findAll({where: {score: {$gt: '1'}}}))
    .thenReturn(downPromise)
```

But I think what I'm getting at here is that `.suppressUnhandledRejections()` returns undefined which is not useful. I think there's a small but useful case if it returned the promise and supported chaining. So far I haven't heard any reason this change could not be made.

**Comment by spion** [comment]
The testdouble documentation is awful, but I looked at the source and thenDo will infact work.

You should however open an issue on their tracker - they should update the documentation to be more specific about whether you can or cannot rely on this behaviour.

**Comment by focusaurus** [comment]
Great! I verified `.thenDo(() => Bluebird.reject(down))` seems to work with no warnings. Thanks! Leave this open for discussion as this fact seems unrelated to the feature request here, but my immediate needs are solved so feel free to close this if no one else thinks it would be useful.

**Comment by spion** [comment]
The problem with this suggestion is that you might get warnings in dev/prod that you did not get in tests. If you actually do have an error in the function which causes a warning to be generated, using the suppression feature this way in the test doubles will turn that warning off during testing - which is probably not what you want.
