### ISSUE TITLE
catch(MyException, ex => { ... }) can cause some trouble

### ISSUE THREAD

**Issue by philippevk** [petkaantonov/bluebird#1103]
I'm reporting a design issue/gotcha, that you might want to address (or not). It's reaaaally edge-case but I'm telling you just in case. Consider the following code

``` JavaScript
doSomethingAsync()
  .catch(MyError, ex => console.log(ex.message));
```

doSomethingAsync() is supposed to return a bluebird Promise but let's say someone (me) introduces a bug that makes it return a vanilla Promise instead.

The behavior will be that the vanilla promise will call MyError as an error callback. The call will fail silently and the promise will stay pending forever.

Obviously it's the programmer's own fault for introducing the bug, but if we could think of an alternative api that achieves the same behaviour AND has the added benefit of causing an error in this scenario it would make bluebird more user-friendly.

Like I said it's more a design gotcha than an actual bug/problem. And I can't think of a fix that doesn't make the API more clunky. But at least now the problem is reported!

**Comment by jcready** [comment]
Seems like you could resolve this by putting the predicate as the second argument. Feels more clucky, but at least it wouldn't silently fail.

**Comment by petkaantonov** [comment]
Thanks for the report but I don't think there is any solution, changing the argument order would make the next major really hard to adopt and the api kinda clunky like you say.
