### ISSUE TITLE
Resolvable value definition

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#1105]
@petkaantonov 

Some of your method API-s mention what they can accept as resolvable values, and some don't. I don't know if it is a limitation or a documentation omission.

I wanted to share some thoughts on this subject, as I once wrote a few generic promise methods, and I was trying to define a generic resolvable value.

This was the definition that I came up with at the time: [Mixed Values](https://github.com/vitaly-t/spex/wiki/Mixed-Values).

I'm not sure how much of it would be applicable to your API, but I suspect that most of it, as your API is also very flexible when it comes to resolvable values.

I was thinking it would benefit everyone to come up with a unified definition for a resolvable value that other projects could reference. And I believe that your project would be the perfect place to host such a definition. I am offering my definition of it as an initial draft, if you want, which ideally will be replaced with a reference to your page in the future, if you decide to go ahead with this.

**Comment by petkaantonov** [comment]
What is a "resolvable value"?

**Comment by vitaly-t** [comment]
- anything that can be transformed / resolved into a simple value.

Example:

```js
promise.all([
   123, // simple value
   Promise.resolve(value), // a resolved value
   Promise.reject(value), // a rejected value
   ()=>456, // a function that returns a simple value
   ()=>()=>111, // a function that returns another function, etc...
   ()=>Promise.resolve(), // a function that returns a promise
   ...
   and so on
]);
```
- all the combinations of values, functions, promises, with recursion support, i.e. functions that return promises or functions, promises that resolve with a function or another promise, etc.

**Comment by petkaantonov** [comment]
Whenever the API accepts promise it will always accept thenable too. There is no intention to expand this to support functions as well.

**Comment by vitaly-t** [comment]
I found functions to be very useful, because:

* unlike regular `.then`, `.catch`  and other methods, the promise spec doesn't allows any `this` context. When working with functions we can pass in the initial `this` context, which helps in many situations;
* ES6 generators can make useful parameters also. In fact, I can see people use `promise.all`, passing it an array of functions - ES6 generators as values.
