### ISSUE TITLE
eval in toFastProperties optimized away in minified build?

### ISSUE THREAD

**Issue by MattiasBuelens** [petkaantonov/bluebird#1108]
I noticed that Bluebird uses `eval` after a `return` in the `toFastProperties` utility function. [As explained in the comments](https://github.com/petkaantonov/bluebird/blob/8fac946a231a18d5ae61a1632f265d0a3c0ffb01/src/util.js#L209), this is done to prevent the function from being optimized through dead code elimination:
```js
function toFastProperties(obj) {
    /*jshint -W027,-W055,-W031*/
    function FakeConstructor() {}
    FakeConstructor.prototype = obj;
    var l = 8;
    while (l--) new FakeConstructor();
    ASSERT("%HasFastProperties", true, obj);
    return obj;
    // Prevent the function from being optimized through dead code elimination
    // or further optimizations. This code is never reached but even using eval
    // in unreachable code causes v8 to not optimize functions.
    eval(obj);
}
````

However, it appears that this `eval` call is **removed in the minified browser builds**. For example, in the [generated `js/browser/bluebird.min.js` for v3.4.0](https://github.com/petkaantonov/bluebird/blob/v3.4.0/js/browser/bluebird.min.js), the resulting code for `toFastProperties` is as followed:
```js
function f(t){function e(){}e.prototype=t;for(var n=8;n--;)new e;return t}
```

As you can see, the `eval` call is gone. Is this intentional, i.e. is this trick not needed in browsers? Or is this a bug?

**Comment by petkaantonov** [comment]
iirc it requires like 80 invocations before such a function is optimized, so it's not currently strictly necessary as it's only called like 2 times.

**Comment by MattiasBuelens** [comment]
Okay, so the `eval` trick isn't really needed. Thanks for the explanation!

I just noticed because we bundle `bluebird` along with our other dependencies using [`rollup`](https://github.com/rollup/rollup), which logs a warning when it finds an `eval` call in the code. I guess we'll just keep ignoring those warnings. :stuck_out_tongue:

**Comment by subtext916** [comment]
You can also suppress this warning: https://github.com/rollup/rollup/issues/408
