### ISSUE TITLE
Assumes 'stack' property exists on trace in debuggability.js, not always true

### ISSUE THREAD

**Issue by mattbarton** [petkaantonov/bluebird#1109]
Error discovered when using request-promise which depends on bluebird

1) What version of bluebird is the issue happening on?
v2 to current

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node v4

3) Did this issue happen with earlier version of bluebird?
yes

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Error message:
node_modules/bluebird/js/release/debuggability.js:721
        stacks.push(cleanStack(trace.stack.split("\n")));
                                          ^
TypeError: Cannot read property 'split' of undefined

Just above the line "while (trace !== undefined) {", I added "console.log({error, parsed, trace})" and got this output:
{ error: 
   { [StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>xx</RequestId><HostId>xx</HostId></Error>"]
     name: 'StatusCodeError',
     statusCode: 403,
     message: '403 - "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>\\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>xx</RequestId><HostId>xx</HostId></Error>"',
     error: '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9C86550DB8C12062</RequestId><HostId>xx</HostId></Error>',
     options: 
      { uri: 'https://host/ndeen.txt',
        callback: undefined,
        transform: undefined,
        simple: true,
        resolveWithFullResponse: false },
     response: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 403,
        statusMessage: 'Forbidden',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        request: [Object],
        toJSON: [Function: responseToJSON],
        caseless: [Object],
        read: [Function],
        body: '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>xx</RequestId><HostId>xx</HostId></Error>' } },
  parsed: 
   { message: 'StatusCodeError: 403 - "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>\\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>xx</RequestId><HostId>xx</HostId></Error>"',
     stack: [ '    (No stack trace)' ] },
  trace: 
   { [Error]
     _parent: undefined,
     _promisesCreated: 0,
     _length: 1,
     _promiseCreated: null } }

**Comment by mattbarton** [comment]
Something like this perhaps could remedy it:

    while (trace !== undefined && trace.stack && trace.stack.split) {

**Comment by benjamingr** [comment]
Proper `Error` objects in Node always have a stack. Also, the code in your example _does_ have a stack property.
