### ISSUE TITLE
Promise.map() got TypeError: Cannot match against 'undefined' or 'null'

### ISSUE THREAD

**Issue by chrischjh** [petkaantonov/bluebird#1110]
It works at version 3.3.5 but doesn't work at version 3.4.0
Node version 6.0

`
Promise.map(httpCalls, (http, id) => {
    const httpExp = preProcess(http, testData);
    return request(id, httpExp).then(result => logResult(result));
}, 20);
`

**Comment by petkaantonov** [comment]
The parameter `20` is incorrect, but it should give a more helpful error message

**Comment by petkaantonov** [comment]
Cannot repro, I get: `TypeError: options argument must be an object but it is [object Number]`
