### ISSUE TITLE
Beginner's guide not properly showing

### ISSUE THREAD

**Issue by simondiep** [petkaantonov/bluebird#1111]
I was looking for the beginner's guide for BlueBird, but ran into either blank pages or broken links.
The two places I looked were: 
http://bluebirdjs.com/docs/beginners-guide.html https://github.com/petkaantonov/bluebird/blob/master/docs/docs/beginners-guide.md

I was using Chrome 49.

**Comment by aaarichter** [comment]
👍 there are multiple broken links in the docs section

**Comment by petkaantonov** [comment]
It's a blank page because it's not written yet
