### ISSUE TITLE
Why was `Promise.try` with an additional argument deprecated?

### ISSUE THREAD

**Issue by spion** [petkaantonov/bluebird#1112]
Why is `Promise.try(fn, arg)` deprecated?

It was super useful for functions that take function arguments. Made it easy to keep the promise non-throwing contract without a whole new closure just to pass the argument...

**Comment by petkaantonov** [comment]
Because the intended usage is with a closure as to emulate a try block and the arguments were confusing (if it's array it's spread, if it's not array it's just a single arg)

**Comment by spion** [comment]
Well, whoever deprecated it forgot to update the documentation :) e.g. see the examples at:

http://bluebirdjs.com/docs/api/disposer.html

**Comment by ricardograca** [comment]
And the alternative to using the second argument is what exactly?
