### ISSUE TITLE
Bluebird 4 and modern NodeJS

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#1116]
Just to get some discussion going:

Hey, a lot of things have happened since 0.x and while the API got more refined a lot of things changed in Node. I presume a lot of people will use async/await or at least generators (with Promise.coroutine) which makes some of the convenience methods less useful. 

I think 4.x should focus on two things: 

 - Making it even easier to wrap libraries with a promise-based interface and small performance penalty. 
 - Making it easier to create libraries with a promise-based interface with a small performance penalty (i.e. - faster than the promise constructor if possible).
 - Making it easier to debug bluebird code.

I think a lot of the utility methods don't really make sense in a generator/async-await centric Node:

### Join, Try and Method
`Promise.join` -
```
Promise.join(p1,p2,p3, (r1,r2,r3) => {
  // ...
});
const [r1,r2,r3] = await all([p1, p2, p3]); // or yield
// ...
```
`Pormise.try`
```
Promise.try(() => {
    // maybe return promise here
});
(async () => {
     // maybe return promise here
}());
co(function*() {
   // maybe return promise here
});
```
`Promise.method` -> `Promise.coroutine` or `async function`

###Synchronous inspection

I don't really see why I'd need this API in an async/await or generator setting - but I think it's worth keeping but we can simplify it - remove `.settle` completely but keep the rest.

### Collections

`each` and `mapSeries` are basically for loops. Map/Filter with concurrency are still useful - `map` and `filter` without them are less useful since there is no chaining benefit but are still worth keeping. 
 
### Utilities

`.call` `.return` `catchReturn` `catchThrow` aren't really useful with generators or async functions.

**Comment by spion** [comment]
Join is there because its easy to write the types for it.

Also, not everyone is happy with async/await. I for one find the lack of filtered catch too limiting and arrow functions a good enough improvement over regular functions to keep the non-generators approach very much alive.

**Comment by Rush** [comment]
> I for one find the lack of filtered catch too limiting

Here here. I really like `async`/`await` but now I have to evaluate if my functions benefit more from better error handling or from better `async`/`await` clarity. And sometimes I simply do `await foo().catch(ErrorClass, err => null)`. 

Sorry for off topic but do y'all have any news from core ES on solving the problems of catching errors in synchronous (or `async`/`await`) code the bluebird style?

**Comment by benjamingr** [comment]
@Rush the latest proposal on nodejs/promises before everyone got too busy and tired was something like:

```js
await fs.readFile("/a.txt", {
    ErrorClass :e => ...
    OtherErrorClass: e => ...
 });
```

**Comment by spion** [comment]
That proposal sucks because it removes the ability to delegate error handling up the stack :(

**Comment by vitaly-t** [comment]
>Making it easier to create libraries with a promise-based interface

I've done a lot of it, in a generic way, with such libraries as [pg-promise] and [spex], supporting all promise libraries in a generic way, and I don't see any need for simplification. If the library's promise signature is generic (as it is), it is good enough.

**Comment by benjamingr** [comment]
@vitaly-t I'd like to see how bluebird could automatically create something like pg-promise automatically without user intervention or the need for more libraries.

**Comment by vitaly-t** [comment]
>how bluebird could automatically create something like pg-promise

I'm not sure what that means :)

**Comment by vitaly-t** [comment]
@benjamingr re-reading a few more times, I've started to think you were talking about improved promisification?

If that's the case, then it is not a good example, because promises in `pg-promises` make up for about 1% of what the library does, it is very far from some sort of a simple merge of an existing protocol with promises.

There are two types of libraries:
* ones that try to merge an existing non-promise protocol with promises, while repeating the existing protocol accurately. This is where promisification is helpful
* Libraries that extend existing libraries beyond promisification. For example, `pg-promise` is an extreme case, which leave almost nothing of the original protocol.

In my experience, automatic promisification is a good quick hack at solving the callback hell. All good solutions are custom-written, to allow for specifics of the library, as most usually have.

**Comment by jcready** [comment]
There are a number of times when promisifying a function results in a loss of information about the actual call. For example, lets say you wanted to promisify a [WriteStream](https://nodejs.org/api/stream.html#stream_class_stream_writable) instance's `write()` method:

> The return value indicates if you should continue writing right now. If the data had to be buffered internally, then it will return false. Otherwise, it will return true.
> 
> This return value is strictly advisory. You MAY continue to write, even if it returns false. However, writes will be buffered in memory, so it is best not to do this excessively. Instead, wait for the 'drain' event before writing more data.

If there were a way for you to access this return value somehow as a property on the Promise instance then you could act on that information by maybe waiting on the WriteStream's drain event before calling it again.

Additionally, promisifying a function means that you cannot handle the `onCancel` event like you could if using a Promise constructor. For instance if you wanted to promifiy the request library (just the exported function, none of the sugar methods). With request you can abort the whole thing by calling `.abort()` on the returned value. Here's a dumbed down version using the Promise constructor:

```js
var request = require('request')
var Promise = require('bluebird')
Promise.config({ cancellation: true })
var requestAsync = function (options) {
  return new Promise(function (resolve, reject, onCancel) {
    var req = request(options, function (err, resp) {
      if (err) reject(err)
      else resolve(resp)
    })
    onCancel(req.abort.bind(req)) // Abort the request on cancellation
  })
}
```

I propose that you would pass a `onCancel` function along in the promisify options:

```js
var request = require('request')
var Promise = require('bluebird')
Promise.config({ cancellation: true })
var requestAsync = Promise.promisify(request, {
  onCancel: function (req) {
    // ret is the return value from bluebird's invocation of the request function
    req.abort()
  }
})
```

**Comment by benjamingr** [comment]
@jcready interesting, how would onCancel know what `req` is in your last snippet?

**Comment by jcready** [comment]
@benjamingr I would imagine, you would modify the [makeNodePromisifiedClosure](https://github.com/petkaantonov/bluebird/blob/afd4494f11555d159eff438fe64b19562452269f/src/promisify.js#L217-L242) (as well as the exec version) to hold onto a reference to the invocation. So on [line 233](https://github.com/petkaantonov/bluebird/blob/afd4494f11555d159eff438fe64b19562452269f/src/promisify.js#L233) you would just change it to:

```js
promise._promisifiedInvocationValue = cb.apply(_receiver, withAppended(arguments, fn));
```

Then when/if a promise is cancelled, it would do something like:

```js
if (this.__isPromisified__) {
  promiseifyOptions.onCancel.call(this, this._promisifiedInvocationValue)
}
```

Another possibility is to, by default, not hold onto a reference to the invocation's return value, but make it another option you can pass to promisify.

```js
var request = require('request')
var Promise = require('bluebird')
Promise.config({ cancellation: true })
var requestAsync = Promise.promisify(request, {
  storeInvocationValue: true,
  onCancel: function (ret) { // ret would be undefined if storeInvocationValue was false (default)
    // the value of ret can also be undefined if the invocation threw an error
    // any errors that may occur while inside the onCancel callback are not caught and turned into rejections
    ret.abort()
  }
})
```

**Comment by benjamingr** [comment]
Doesn't sound like much discussion is happening here. Feel free to reopen if anyone wants to.

**Comment by jcready** [comment]
@benjamingr do you have any thoughts on my proposal? Would you accept a PR with said functionality?
