### ISSUE TITLE
Promisify vs PromisifyAll

### ISSUE THREAD

**Issue by cnojima-ra** [petkaantonov/bluebird#112]
Hi,

I'm trying to promisify the request library and I need to use it as a function and sub methods. I'm doing the code below but I'm hoping there's a cleaner way to achieve this.

var Promise = require('bluebird');
var request = require('request');
var requestAsync = Promise.promisify(request);
var jarAsync = Promise.promisifyAll(request.jar());

return requestAsync(options).spread(function (response, body) {});

return jarAsync.getCookiesAsync(...).then(function (cookies) {});

if i do requestAsync.jar() it complains that the method does not exist.

Any insight appreciated.

**Comment by apoorva-shah** [comment]
What is performance difference between Bluebird promisify vs promisifyAll  when want to promisification of one method from module
Suppose,
I want to know performance difference between bluebird promisify vs promisifyAll.

I have tried performance test of bluebird promisify and promisifyAll.

But time and memory wise i do not see major difference, Still i thought promisify is slightly fast and less memory occupy. Still what is best.

Suppose i want Promisification of renderFile of ejs module for just 1 method renderFile.

I have 2 options

```
const ejs = require('ejs');
const renderFile = Promise.promisify(ejs.renderFile, {context: ejs});
```

`const ejs = Promise.promisifyAll(require('ejs'));
`
I test performance via

```
console.time('A');
console.timeEnd('A');
```

and `console.log(process.memoryUsage());`

Pls answer about what should i use when i want promisification of only 1 method.

http://stackoverflow.com/questions/42455669/bluebird-promisify-vs-promisifyall-performance-compare-when-want-to-promisificat
