### ISSUE TITLE
Promisified 'request' not throwing Error on error status code.

### ISSUE THREAD

**Issue by MIYankov** [petkaantonov/bluebird#1120]
This happens on 3.4.0

I'm not even sure if it's supposed to work. In your documentation [here](http://bluebirdjs.com/docs/api/catch.html) there is an example of a promisified request module that throws an Error with a code property.

```
var Promise = require("bluebird");
var request = Promise.promisify(require("request"));

function ClientError(e) {
    return e.code >= 400 && e.code < 500;
}

request("http://www.google.com").then(function(contents) {
    console.log(contents);
}).catch(ClientError, function(e) {
   //A client error like 400 Bad Request happened
});
```

This doesn't work. If you change the url to a non existing one like "http://www.google.com/test" it won't enter the catch(). The promisified request module doesn't throw an Error.

I get that this is an example of the predicate-based filter, but is the example supposed to work or should we handle the statusCode of the response ourselves and throw the Error ourselves?

**Comment by SimonSchick** [comment]
Not a bluebird problem?

```
> void(r = require('request'))
undefined
> void(r.get('http://google.com/sjdgpsihbufidgf', (err, res) => { console.log(err, res.statusCode); }))
undefined
> null 404
```

request only errors when there was an _actual_ error below the http layer, http status codes outside 200-399 are not considered errors but valid responses.

**Comment by SimonSchick** [comment]
If you want more refined error you can do something like that.
```javascript

const request = require('bluebird').promisify(require('request'))

class HTTPError extends Error {
	constructor(response) { super(...); ... }
}

// you can always extend ClientError for 4xx codes.
class ClientError extends HTTPError {
	constructor(response) { super(...); ... }
}

class ServerError extends HTTPError {
	constructor(response) { super(...); ... }
}

function assertHTTPError(res) { 
    const code = res.statusCode;
    if(code > 200 && code <= 400) throw new ClientError(res);
    if(code > 500) throw new ServerError(res);
    // you can always be more specific about codes, eg. 401, 403, etc.
}

// wraps up http error code responses with actual error objects.
function myRequest(opts) {
    return requestAsync(opts)
    .tap(assertHTTPError);
}
```

**Comment by MIYankov** [comment]
Thanks for the answer and the code. I already do something similar in my code, but stumbled upon the example in the docs and decided to ask.
