### ISSUE TITLE
Cancellation allows late catch and finally consumers

### ISSUE THREAD

**Issue by dwelle** [petkaantonov/bluebird#1121]
Not only late `catch`/`finally` observers are allowed, but __`catch` handler shouldn't be called for cancelled promises.__

```
Promise.config({ cancellation: true });
var p = new Promise(() => {});
p.cancel();
p.catch(() => console.log("catch") );
p.finally(() => console.log("finally") );
```

v `3.4.0`, `FF 46.0.1`, `Chrome 50`

**Comment by spion** [comment]
Bluebird cancellation semantics are precisely like that. Only operations prior to cancellation are fully aborted: any handlers attached after the cancellation event will be rejected with a cancellation error.

**Comment by dwelle** [comment]
From [docs](http://bluebirdjs.com/docs/api/cancellation.html):

> As shown in the example the handlers registered with `.finally` are called even if the promise is cancelled. Another such exception is `.reflect()`. No other types of handlers will be called in case of cancellation.

Thus I gather, `.catch` handlers shouldn't be called neither when registered prior to cancellation (currently they're not), nor when registered after cancellation (currently they are).

> Note that it is an error to consume an already cancelled promise, doing such a thing will give you a promise that is rejected with `new CancellationError("late cancellation observer")` as the rejection reason.

Registering `.then` to cancelled promise throws, but registering `.catch`/`.finally` doesn't. To me this seems inconsistent.
