### ISSUE TITLE
isCancelled() not true after cancel()

### ISSUE THREAD

**Issue by cazgp** [petkaantonov/bluebird#1122]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.3.4

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node 4.x

3) Did this issue happen with earlier version of bluebird?
Not sure.

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

```
Promise = require('bluebird')
Promise.config({
    cancellation: true,
    longStackTraces: true
})

test = Promise.resolve(true)
    .then(function () {
        return new B(function (resolve, reject) {
            setTimeout(resolve, 2000)
        })
    })
    .then(function (val) {
        console.log('after timeout')
    })
    .then(function (val) {
        console.log('final')
    })

Promise.resolve(true)
    .then(function () {
        console.log('test cancelling')
        test.cancel()
        console.log('cancelled state: ' + test.isCancelled())
    })
    .then(function () {
        console.log('cancelled state: ' + test.isCancelled())
    })  
```

The docs say that `Promise.cancel` is synchronous, so the expected output would be:

```
test cancelling
cancelled state: true
cancelled state: true
```

However, the actual output is:

```
test cancelling
cancelled state: false
cancelled state: true
```

Is this expected behaviour, or a bug?

**Comment by rowanoulton** [comment]
+1

**Comment by petkaantonov** [comment]
Fixed in a release coming today
