### ISSUE TITLE
`util.isError` uses duck typing

### ISSUE THREAD

**Issue by ktrain** [petkaantonov/bluebird#1123]
I'm working with Bluebird 3.4.0.

I've noticed that `util.isError` uses various property checks on the error to decide whether the thing you rejected the promise with is an error.

`js/release/util.js`, lines 225-230:
```javascript
function isError(obj) {
    return obj !== null &&
           typeof obj === "object" &&
           typeof obj.message === "string" &&
           typeof obj.name === "string";
}
```

Is there any reason why it doesn't allow for `obj` being an instance of Error with alternative property types? The reason I ask is that we use a custom error type that extends Error, and we often use an object as the message, and as things currently are, we get a warning: `(node:9482) Warning: a promise was rejected with a non-error: [object Object]`

Perhaps the following would be a reasonable change:

```javascript
function isError(obj) {
    return obj instanceof Error || (
           obj !== null &&
           typeof obj === "object" &&
           typeof obj.message === "string" &&
           typeof obj.name === "string"
    );
}
```

**Comment by benjamingr** [comment]
Good question! 

The reason the library does this is that bluebird supports several environments that have multiple base `Error` types where there is more than one base `Error`. Doing `instanceof Error` when there are three base `Error` types won't work since there is more than one `Error` base type.

Now - as for your actual issue - it should still work when extending the base `Error` type - can you show me how you extended it? If you extend it correctly it should work - I use a lot of specific Error subtypes in order to have fine grained error handling and bluebird itself exports several error types.

**Comment by ktrain** [comment]
Thanks for the quick response!

I've tried two ways: first, using the [extend-error npm package](https://www.npmjs.com/package/extend-error) (I should have noted in the initial post that I'm on node 6.2.1), and then, when I started encountering the warnings, by doing the extension myself:

```javascript
function MyError(message) {
    this.message = message;
    this.name = 'MyError';
    Error.captureStackTrace(this, MyError);
};
MyError.prototype = Object.create(Error.prototype);
MyError.prototype.constructor = MyError;
```

But I continued to encounter the warnings, which I believe is happening because I'm passing an object as `message`, so the`util.toError` check fails.

**Comment by spion** [comment]
Passing an object as an error message makes the stack trace look pretty bad, doesn't it? any particular reason why thats useful?

**Comment by ktrain** [comment]
Good point - my use case is that Express middleware up above catches the error, possibly does some logic based on the object's properties, and responds. So the stack trace doesn't actually matter to me.

**Comment by spion** [comment]
Might I suggest adding an additional property to the error object then? That way you can keep the good error behaviour in stack traces but have the additional (meta)data in the object.

**Comment by benjamingr** [comment]
@ktrain ECMAScript errors have string `.message` properties. If I made my own array subclass that defined `.length` as an object I don't think it would work in a lot of places.

I don't think tooling that recognizes and monitors errors (like NewRelic, app insights etc) would recognize your errors.

(Also, my opinion is that stack traces are very important for writing debuggable code, but that's just my personal opinion)

**Comment by ktrain** [comment]
@benjamingr In this case, the custom error type being thrown signifies an input/missing data error, not something unexpected that should end up logged in New Relic. It's used for communication between modules and middleware.

@spion Yes - that's going to be my next approach since it looks like the `util.isError` is written with good purpose. Just wanted to float the idea first and see what the decision was behind its implementation.

Thanks for the great feedback!
