### ISSUE TITLE
Feature: shorthand combination of props and each

### ISSUE THREAD

**Issue by dadleyy** [petkaantonov/bluebird#1124]
Is there a use case for a function that acts as a combination of [`props`](http://bluebirdjs.com/docs/api/promise.props.html) and [`each`](http://bluebirdjs.com/docs/api/promise.each.html), where an array of objects has each object iterated over, resolving each property of that object into a single object?

```javascript
function mapped(results) {
  // results.user, results.parents, results.brothers and results.uncles exist
}

function failed() {
  // anything was rejected...
}

Promise.mapping([{
  user: function() { return User.get({id: 123}) }
}, {
  parents: function(results) { 
    return Promise.all([
      User.get({id: results.user.mother}),
      User.get({id: results.user.father})
    ]);
  },
  brothers: function(results) {
    return User.get({id: results.user.brothers});
  }
}, {
  uncles: function(results) {
    return Promise.all([
      User.get({id: results.parents[0].brothers}),
      User.get({id: results.parents[1].brothers})
    ]);
  }
}]).then(mapped).catch(failed);
```

The `parents` and `brothers` functions would be executed immediately after one another in this example, once the `user` function was resolved. Once both the `brothers` and `parents` functions have completed, the `uncles` function would be called.

**Comment by petkaantonov** [comment]
Well if there is, one should just use a combination of props and each I think.

**Comment by dadleyy** [comment]
yeah I agree; users looking for this can implement it:
```coffeescript
```
