### ISSUE TITLE
Are those benchmark results normal?

### ISSUE THREAD

**Issue by philippevk** [petkaantonov/bluebird#1128]
I did some benchmark for join vs all/spread and the results were surprising. Spread seems to have a huuuge impact. Is this normal?

```
  join       x 2,039,561 ops/sec ±1.09% (85 runs sampled)
  all        x 1,470,510 ops/sec ±1.46% (83 runs sampled)
  all+spread x   683,240 ops/sec ±2.46% (80 runs sampled)
```

https://gist.github.com/philippevk/ab4aa97704a4db9b169713ddaacdaa60

**Comment by petkaantonov** [comment]
Spread does .all implicitly.
