### ISSUE TITLE
Feature request for method `chain`

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#1129]
Syntax for the proposed method:

```js
// with a single parameter - array
.chain([value1, value2,...])

// with multiple arguments:
.chain(value1, value2,...)
```
value1, value2,...can be of the following types (at the very least):

* a simple value
* a promise
* a function that returns a simple value
* a function that returns a promise

**Logic for the method:**

* Resolve every value in the same sequence as they are defined, like an explicit `.then` chain
* When the value is a function, it must be passed one parameter - resolved value from the previous element.
* When successful, the method resolves with the value from the last element in the sequence.
* When fails, the value that failed to resolve is the one to be used as the rejection reason.

**Virtue:**

It will make a great convenience for simplifying short promise chains with sporadic dependencies between elements. Think about it as a compressed / abbreviated `.then` chain.

See also: [Chaining results with Bluebird](http://stackoverflow.com/questions/37752653/chaining-results-with-bluebird)

**Options to consider**

For the syntax that accepts an array we can have a second parameter - `thisArg` to be used for any function call that's in the sequence.

**Comment by ben-page** [comment]
Is this really too verbose?
```javascript
.then(function() {
})
.then(function() {
})
.then(function() {
})
```
It's just as many lines as `chain` when well formatted.
```javascript
.chain(function() {
  },
  function () {
  },
  function () {
  }
)
```

**Comment by ben-page** [comment]
>- a simple value
- a promise
- a function that returns a simple value
- a function that returns a promise

Mixing value types and functions like that is dangerous. Remember, a Function is also a "simple value".

What if I don't want Bluebird to execute a function just because I passed it to `chain`? What if I actually just want to pass the function without it being executed?

In this example would `f` be "a" or func1?

```javascript
let func1 = function() {
  return 'a';
}

somethingThatReturnsPromise()
  .chain(func1, function two(f) {
    f();
  });
```

**Comment by vitaly-t** [comment]
> Remember, a Function is also a "simple value".

Since when?

**Comment by ben-page** [comment]
Always. Functions are just a type of object. They can be passed around like any other variable.

> In JavaScript, functions are first-class objects, because they can have properties and methods just like any other object.

[MDN Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions)

**Comment by vitaly-t** [comment]
That's not applicable to promises where functions are normally for callbacks to get a simple value or a promise.

But I do not have time arguing here. If my idea isn't welcome, then so be it, I'm closing it here, and will implement it myself where I need it.

Cheers!
