### ISSUE TITLE
`Promise.version` is incorrect for v3.4.1

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1136]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

v3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node 6.2.1, OS X 10.9.5

3) Did this issue happen with earlier version of bluebird?

No.

The value of `Promise.version` in v3.4.1 is `'3.4.0'`. Not a big deal, just I happened to notice it.

**Comment by petkaantonov** [comment]
Fixed since 3.4.2
