### ISSUE TITLE
Add `Promise.version` property to 2.x branch

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1138]
Next time a 2.x version is released, would it be possible to add a `Promise.version` property, same as introduced in v3.4.0?

This would allow modules such as [cls-bluebird](https://www.npmjs.com/package/cls-bluebird) that allow bluebird to be injected, to determine whether it's bluebird v2 or v3.

**Comment by benjamingr** [comment]
It's pretty easy to feature check now and I think that's better than version checking but I guess that it could be added. v2 is not really a priority for new features - care to make a PR?

**Comment by overlookmotel** [comment]
@benjamingr Thanks for swift response. I would be totally happy to submit a PR, but I don't think I can.

The value that the `version` property should be set to can't be known until a release is made, so I can't see a way to add it to the build process.

It could be a added dynamically with `Promise.version = require('../package.json').version` and that'd work in node, but I'm not sure if it would in the browser (I only do server-side so I don't know).

When @petkaantonov added the `version` property to v3.x branch, he did it (as far as I can see) by hard-coding it into the code at release time. But it didn't get updated for v.3.4.1 (#1136).

If there is a script used for creating releases that I can add this to, please can you point me in the right direction and I'll definitely create a PR.

**Comment by overlookmotel** [comment]
By the way, yes you're right, you can deduce the version via feature check (I've just published [is-bluebird](https://www.npmjs.com/package/is-bluebird) which does this). But it's not as robust as an explicit `version` property.

The `version` property was already introduced in v3.x, so I was just requesting it's addition to v2.x to aid in distinguishing between the two.

I promise to stop bugging you for amends to v2 after this!

**Comment by benjamingr** [comment]
I don't know if it's worth a release. It would be useless since you could check if it's 3.x by having `.version` and it would be useless for 2.x versions since we're not going to have any of those except for bug releases which is going to be pointless.

You can always `require("package.json").dependencies.bluebird` to get the version anyway.

**Comment by benjamingr** [comment]
Fixed in https://github.com/petkaantonov/bluebird/commit/481e823d19690c26fbef71afe331da9c5722defc
