### ISSUE TITLE
Handling simple value rejects

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#1142]
With relation to [Warning: a promise was rejected with a non-error](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-rejected-with-a-non-error).

It would be very nice to extend there with a recommendation on how to handle it within your own reusable library that's based on Bluebird (or on any promise library for that matter).

I'm talking about handling simple value errors thrown by the client code.

Since I couldn't find it anywhere, I opened a question: [Handling simple value rejects in a promise library](http://stackoverflow.com/questions/37982643/handling-simple-value-rejects-in-a-promise-library)

**Comment by benjamingr** [comment]
Closing since answered in StackOverflow

**Comment by vitaly-t** [comment]
>It would be very nice to extend there with a recommendation on how to handle it within your own reusable library that's based on Bluebird (or on any promise library for that matter).

The suggestion was to extend the official documentation, not about answering my question on StackOverflow. Why close it?

**Comment by spion** [comment]
This is general JavaScript question. Its recommended for the user to use `new Error` at the exact place where the error has occurred. This will result with the best stack traces. Anything else is a crude workaround and only provides "best effort" stack traces.
