### ISSUE TITLE
Coroutines and fromCallback

### ISSUE THREAD

**Issue by perrin4869** [petkaantonov/bluebird#1145]
Is there a way to integrate coroutines with `fromCallback`, in the same manner as with normal promises? The use case I'm thinking about is when writing `express` middlewares. When doing async operations inside a middleware, I would just stick an `asCallback` to the end of the promise, and voila - callback handled automatically. With coroutines however, I don't see an analogous operation.

**Comment by benjamingr** [comment]
Define your own handler with addYieldHandler to support yielding callbacks.

**Comment by perrin4869** [comment]
hm... what do you do with the yielded handler though?

**Comment by bergus** [comment]
I believe you're looking for a simple helper function
```
coroutineWithCallback(genFn) {
    const co = Promise.coroutine(genFn);
    return function(...args) {
        const nodeback = args.pop();
        co(...args).asCallback(nodeback);
    };
}
```
Now you can write your asynchronos express handlers as promise-yielding generator functions.

**Comment by perrin4869** [comment]
Yeah that works, thanks!
