### ISSUE TITLE
Invalid `rejected with a non-error` warning

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#1146]
When we set a message in out custom error object based on some non-string data, Bluebird displays `Warning: a promise was rejected with a non-error: [object Object]`, which is clearly a mistake.

Here's complete example:

```js
'use strict';

var util = require('util');
var promise = require('bluebird');

function CustomError(data) {
    this.message = data;
    Error.captureStackTrace(this, CustomError);
}

util.inherits(CustomError, Error);
CustomError.prototype.name = 'CustomError';

promise.reject(new CustomError([]))
    .catch(error=> {
        console.log(error);
    });
```

This should not produce that warning, but it does.

**Comment by benjamingr** [comment]
You haven't defined a `.message` string property on your error object. All error objects in ECMAScript have message string properties. Instead you passed it an array.

This breaks code that expects `.message` to be a string like it is on `Error.prototype` which is why bluebird rejects your error.

If you subclass `Error` with a message property which is a string then the error would not trigger.

Thanks for the report.

**Comment by vitaly-t** [comment]
Why wouldn't Bluebird just check `if(error instanceof Error)`?

**Comment by benjamingr** [comment]
Good question! Bluebird runs in multiple environments where that check does not make sense - here are some:

 - Across iFrames.
 - Across a page and a different page it opened.
 - Across contexts in NodeJS.
 - In electron between the node realm and browser realm.
 - In extensions in Chrome and Firefox where the extension code and the browser code.

All those are examples where errors originate in different _realms_. There is also a lot of difference between engines and in execution contexts like in Rhino.

There was an [`Error.isError`](https://github.com/ljharb/proposal-is-error) proposal by @ljharb but I don't think that's being pursued.

**Comment by benjamingr** [comment]
I tried to talk @petkaantonov into doing `|| instanceof Error` but he was against it by the way.

**Comment by ljharb** [comment]
The committee rejected `Error.isError`, but I'm working on a proposal for a method to get stack traces in a standard way that would allow for the same brand checking, and that should be polyfillable in most browsers - I'll let you know when I have one ready :-)

**Comment by vitaly-t** [comment]
I've killed a full day trying to adjust my custom error objects so that Bluebird wouldn't produce the warning, giving up now, it's not worth it.

I don't think it is a good idea to request that your custom error objects in Node.js can't be used for rejection, unless they do a few more tricks just to circumvent Bluebird. A bit of a hack this is.

**Comment by benjamingr** [comment]
It's not a hack, all error properties should behave like standard JavaScript errors which means they should include a `.message` property like every JavaScript error - I'm not sure how else to explain this.

**Comment by vitaly-t** [comment]
Well, I'm still trying to figure out what else is causing Bluebird to think that a custom error object isn't really an Error. That first example I provided was just one case, and apparently there is more, I just can't figure out yet what that is, something elusive...

**Comment by benjamingr** [comment]
```js
function isError(obj) {
    return obj !== null &&
           typeof obj === "object" &&
           typeof obj.message === "string" &&
           typeof obj.name === "string";
}
```

**Comment by vitaly-t** [comment]
Ok, more results, after a long digging into Bluebird.

Here's [the reason all custom errors are failing](https://github.com/petkaantonov/bluebird/blob/master/src/promise.js#L490):

```js
    var hasStack = trace === reason;
```
It decides whether the object has stack based on this comparison, which from what I see is invalid. And then it produces a warning based on that.

I think you guys didn't test it properly, when a custom error is defined in one module, then used in another, and your library uses the last one, I am always getting the error object for which that condition `trace === reason` is false, hence the problem.

**Comment by spion** [comment]
No, `ensureErrorObject` returns the same argument that is passed when the object is successfully checked to be an error. That in turn does that if `canAttachTrace` returns true. And that is equivalent to:

```js
function canAttachTrace(obj) {
    return isError(obj) && es5.propertyIsWritable(obj, "stack");
}
```

`isError` was pasted above by @benjamingr

**Comment by vitaly-t** [comment]
> No
LOL

Here I patched the source code with messaging:
```js
Promise.prototype._rejectCallback =
function(reason, synchronous, ignoreNonErrorWarnings) {
    var trace = util.ensureErrorObject(reason);
    console.log("TRACE:", trace);
    console.log("REASON:", reason);
    console.log("EQUAL:", trace === reason);
    var hasStack = trace === reason;
    if (!hasStack && !ignoreNonErrorWarnings && debug.warnings()) {
        var message = "a promise was rejected with a non-error: " +
            util.classString(reason);
        this._warn(message, true);
    }
    this._attachExtraTrace(trace, synchronous ? hasStack : false);
    this._reject(reason);
};
```

It outputs:
```
TRACE: [Error: BatchError: ops]
REASON: { [BatchError: ops]
  data: [ { success: false, result: [Error: ops] } ],
  getErrors: [Function],
  first: [Error: ops],
  message: 'ops',
  stat: { total: 1, succeeded: 0, failed: 1, duration: 1 } }
EQUAL: false
Warning: a promise was rejected with a non-error: [object Object]
    at D:\NodeJS\tests\node_modules\pg-promise\lib\database.js:1195:31
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Database.taskProcessor (D:\NodeJS\tests\node_modules\pg-promise\lib\database.js:1193:23)
    at Database.obj.task (D:\NodeJS\tests\node_modules\pg-promise\lib\database.js:1027:34)
    at test (D:\NodeJS\tests\test.js:62:8)
    at Object.<anonymous> (D:\NodeJS\tests\test.js:55:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by spion** [comment]
Here, let me try and explain it again.

1. Bluebird calls `var trace = util.ensureErrorObject(error)`. It works like this

```js
function ensureErrorObject(error) {
  if (isReallyError(error)) return error;
  else return wrapIntoActualError(error);
}
```

Bluebird does a reference comparison to see if ensure returned the same object

```js
if (trace === error)
```

This will only be true if the first branch was triggered i.e. `if (isReallyError(error)) return error;`

The reason for this magic is that the cost of a reference comparison is much lower than checking the error object all over again.

My suggestion would be to make a minimal test case - that should make it easier to figure it out.

**Comment by vitaly-t** [comment]
As I explained earlier, when a custom error travels from one module dependency to another, your `trace` vs `reason` are no longer what you think they should be.

A "simple" test requires: declare module A with a custom error, then use it within module B, and have your client use that module B. I cannot replicate the problem within a single module.

**Comment by vitaly-t** [comment]
Ok, this is the last time spent so many hours trying  to figure it out...

Now without the hypothetical...

I have module [spex](https://github.com/vitaly-t/spex), that never throws any Bluebird warnings, works perfectly, has 100% test coverage.

I have module [pg-promise](https://github.com/vitaly-t/pg-promise), which is again, never throws any Bluebird warnings, works always perfectly, has 100% test coverage.

And yet, just as `pg-promise` attempts to use `spex`, any reject results in that Bluebird warning.

Now, considering that both module separately never produce that warning on rejects, only when one is called from the other - that doesn't really make any sense.

A complete test application:

```js
'use strict';

var promise = require('bluebird');
var pgp = require('pg-promise')({
    promiseLib: promise
});

var cn = "postgres://postgres@localhost:5432/pg_promise_test";
var db = pgp(cn);

function f() {
    throw new Error("ops");
}

db.task(function (t) {
    return t.batch([f]);
})
    .catch(function (error) {
        console.log(error);
    });
```

**Comment by spion** [comment]
Your example doesn't currently generate warnings. Which versions of spex and pg-promise does it use?

**Comment by vitaly-t** [comment]
I am using those very versions, under Node.js 4.4.5 and 6.2.2, under Windows 10, 64-bit.

I am getting those warnings in that example 100% of a time.

**Comment by spion** [comment]
Remove `Object.freeze(error)` from lib/ext/batch.js

(You'll probably need to do it for lib/ext/sequence.js too)

**Comment by vitaly-t** [comment]
@spion wow! great job, man, right to the point!

So Bluebird fails to do detection for read-only Error objects! That's quite unexpected.

**Comment by spion** [comment]
Not exactly unexpected. This only happens when longStackTraces is on, in which case bluebird must modify the stack property to add to the stack trace. In normal situations you'll get a clearer error, however when the above type error occurs, `spex` converts it again to a BatchError which fails to pass the isError test. I don't know where that happens in spex.

**Comment by vitaly-t** [comment]
If I chnage the test to use `spex` directly:
```js
'use strict';

var promise = require('bluebird');
var pgp = require('pg-promise')({
    promiseLib: promise
});

var cn = "postgres://postgres@localhost:5432/pg_promise_test";
var db = pgp(cn);

function f() {
    throw new Error("ops");
}

pgp.spex.batch([f])
    .catch(function (error) {
        console.log(error);
    });
```

then it doesn't care whether Error is read-only or not.

**Comment by spion** [comment]
What you are doing is reject(e) then Object.freeze(e). Essentially this mutates the error object after passing it to bluebird. Is there any reason for this reversed behaviour?

**Comment by spion** [comment]
The above code you pasted produces

`TypeError: Cannot redefine property: stack`

when longStackTraces is on.

**Comment by vitaly-t** [comment]
>The above code you pasted produces

Do you mean when the `Object.freeze` is used?

**Comment by vitaly-t** [comment]
I think I may add some checks for Bluebird specifically. That's why I've just asked this question: [Bluebird detection](http://stackoverflow.com/questions/38079597/bluebird-detection).

**Comment by spion** [comment]
@vitaly-t Just don't freeze the error. At the very least, leave the `stack` property writable, or don't turn on longStackTraces.

**Comment by vitaly-t** [comment]
>or don't turn on longStackTraces.

That's out of my hands, as the library simply consumes the promise library, which is configurable by the client. I will likely just remove the object freezing.
