### ISSUE TITLE
MySQL sample code appears to be wrong

### ISSUE THREAD

**Issue by drekka** [petkaantonov/bluebird#1150]
I'm trying to follow the MySQL example code in the various code samples supplied in the doco. I've found several things either confusing or incomplete. My current code looks like this:

    Database.prototype.addStory = function (projectId, title, text) {
        return Promise.using(getConnection(), function (connection) {
            return Promise.using(getTransaction(connection), function (tx) {
                return tx.queryAsync('INSERT INTO story SELECT ?, MAX(storyNumber) + 1, ?, ?, 0 FROM story WHERE projectID = ?',
                    [projectId, title, text, projectId])
                    .then(tx.queryAsync('select LAST_INSERT_ID()'))
                    .then(function (rows) {
                        return getStory(tx, rows[0]);
                    });
            });
        });
    }

    function getConnection() {
        return pool.getConnectionAsync().disposer(function (connection) {
            connection.release();
        });
    }

    function getTransaction(connection) {
        return connection.beginTransactionAsync().disposer(function (tx, promise) {
            if (promise.isFulfilled()) {
                tx.commitAsync();
            } else {
                tx.rollbackAsync();
            }
        });
    }

The first problem I encountered is that the sample code makes reference to `db.`, but doesn't say what `db` is. Is it a connection, the MySQL variable, a connection pool, what?

The second problem I encountered is that the sample code doesn't show how to use transactions in relation to connections. From messing with this stuff for the past week trying to get it working, I've found that I have to use nested promises where as the sample code implies that `getTransaction()` can be called by itself and it will somehow magically get a connection from the connection pool.

The third problem I've encountered and is yet unsolved, is that the above code will generate an error because it cannot find the `tx.commitAsync()` or `tx.rollbackAsync()` functions. Debugging through shows me that tx is a `OkPacket` which sounds very wrong. But I have no idea how to fix it.

**Comment by spion** [comment]
The transaction code isn't an example, its an illustration of the transaction pattern using a different API. For the base MySQL library you will need to actually write a transaction wrapper.
