### ISSUE TITLE
How can I make a chain?

### ISSUE THREAD

**Issue by fabiooshiro** [petkaantonov/bluebird#1154]
I have a chain like:
```js
obj.sum([1,2,3]).subtract([3]).compute().then(function(result) {
});
```

There is any way to remove the compute() ?
```js
obj.sum([1,2,3]).subtract([3]).then(function(result) {
});
```

**Comment by bergus** [comment]
Of course there is, just provide a `then` method instead of the `compute` one on your API.
However, this is support question, please ask such at StackOverflow (and make sure to include your full code there).

**Comment by bergus** [comment]
See also https://stackoverflow.com/questions/28375619/chainable-promise-based-class-interfaces-in-javascript

**Comment by benjamingr** [comment]
Thanks Bergi
