### ISSUE TITLE
Unhandled rejection when calling `Promise.all()` on promise of array where array contains rejected promise

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1158]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

v3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node v6.3.0, OS X 10.9.5

3) Did this issue happen with earlier version of bluebird?

Issue not present on bluebird v2.10.2.

---

There's inconsistency in whether an unhandled rejection is thrown when calling `Promise.all()` on a *promise of* an array where the array contains a rejected promise. Behavior is different depending on whether the promise of an array is created from main bluebird `Promise` constructor, or another `Promise` constructor.

An unhandled rejection is thrown if the promise passed to `Promise.all()` is a bluebird promise but *created from another constructor*. Only affects bluebird v3.x.

```js
var Promise = require('bluebird');
var OtherPromise = Promise.getNewLibraryCopy();

var p = OtherPromise.resolve( [ Promise.reject( new Error('foo') ) ] );
Promise.all(p).catch( function() {} );
```

The above calls the unhandled rejection handler. And so does:

```js
var Promise = require('bluebird');
var OtherPromise = require('bluebird2');

var p = OtherPromise.resolve( [ Promise.reject( new Error('foo') ) ] );
Promise.all(p).catch( function() {} );
```

If `OtherPromise = global.Promise` (i.e. native JS promise), no unhandled rejection is thrown.

So unhandled rejections are created when acting on a promise of an array which:

* is a bluebird promise
* is not an instance of the same Promise constructor
* may be a bluebird 2 promise, or bluebird 3 promise

Other collection methods e.g. `Promise.map()` are similarly affected.

```js
var p = OtherPromise.resolve( [ Promise.reject( new Error('foo') ) ] );
Promise.map( p, function() {} ).catch( function() {} );
```

I'm not sure what is the correct behavior (i.e. maybe rejected promises within the array should *never* be handled), but I feel it would probably be better if behavior was consistent no matter what kind of promise is in the array.

**Comment by ben-page** [comment]
I think the problem is that you aren't calling `Promise.all()` on the array of promises. You are calling it on Promise that is is resolved to an array.

This also throws an Unhandled rejection Error:
```javascript
Promise.resolve([Promise.reject(new Error('foo'))])
    .then(arr => {
        console.log(arr); //an Array with an Promise in it
    })
    .catch(err => {
        console.log(err.stack);
    });
```
See then resolves to the array, but nothing is handling the Promise created by `Promise.reject()`.

If you swith to using `Promise.all()` it works as expected (ie. no Unhandled rejection)
```javascript
const Promise = require('bluebird');

Promise.all([Promise.reject(new Error('foo'))])
    .catch(err => {
        console.log(err.stack);
    });
```

Lastely, Your first example works if you swap the `Promise.all()` and `Promise.resolve()` calls:
```javascript
var Promise = require('bluebird');
var OtherPromise = Promise.getNewLibraryCopy();

var p = OtherPromise.all( [ Promise.reject( new Error('foo') ) ] );
Promise.resolve(p).catch( function() {} );
```

**Comment by overlookmotel** [comment]
Thanks for replying @ben-page.

My original post wasn't very clear, so I've now updated it. I'm not sure whether the throwing of unhandled rejections is a bug or not, but there's an inconsistency in behavior depending on what promise constructor the promise passed to `Promise.all()` is created from.

In truth, I'm not sure why anyone would want to call `Promise.all()` with a promise of an array of promises - I can't see a use case for it. But the docs state the API as `Promise.all(Iterable<any>|Promise<Iterable<any>> input) -> Promise` so it is a legal part of the API.

Your final example does avoid the unhandled rejection, but it's no longer passing a *promise of* an array to `Promise.all()`.

If this is a bug at all, it's very minor. But I just figured best to raise an issue so it's documented somewhere and anyone else who comes across it might find this helpful.

For context, the reason I came across this is that I'm working on a new patch for bluebird to support [CLS](https://www.npmjs.com/package/continuation-local-storage) (https://github.com/overlookmotel/cls-bluebird/tree/refactor) which includes an extensive test suite that tests every aspect of the documented API. So that's how I came across this. In the real world, it's a very odd edge case.

**Comment by petkaantonov** [comment]
Promise of an array of promises is not recognized by the docs, I.E. there is no `Promise<Iterable<Thenable>>` or `Promise<Iterable<Promise>>`

**Comment by overlookmotel** [comment]
@petkaantonov Ah I see. But from what I can gather from doing tests on all the documented methods, bluebird (documented or not) accepts a promise anywhere it accepts a value.

So all the following work:

```js
Promise.all( Promise.resolve( [ Promise.resolve( 1 ) ] ) );
Promise.map( Promise.resolve( [ Promise.resolve( 1 ) ] ), function() { ... } );
Promise.bind( Promise.resolve( 1 ) );
promise.return( Promise.resolve( 1 ) );
```

Aside from this particular issue and a few others I've raised, it seems to work 100% everywhere.

So I'd suggest one of:

* Add this to the docs so it's officially supported
* Add to the docs that it's *not* supported and behavior is unknown
* Stop it working completely to avoid confusion
