### ISSUE TITLE
Docs Anti-Patterns: incorrect "translation" between try/catch and promises example?

### ISSUE THREAD

**Issue by Laoujin** [petkaantonov/bluebird#1159]
From the live documentation:
http://bluebirdjs.com/docs/anti-patterns.html#the-.then

```js
try {
    var stuff = JSON.parse(doThat());
}
catch(e) {

}

doThat()
.then(function(v) {
    return JSON.parse(v);
})
.catch(function(e) {

});
```

Isn't there a fundamental difference between those two with regard to exceptions happening in `doThat`?

Consider:

```js
function doThat() {
  throw new Error('oepsie');
}

doThat()
.catch(e => console.log("catch", e));
// --> "catch" block is never reached!

console.log('------');

Promise.resolve()
.then(function() {
  return doThat();
})
.catch(e => console.log("catch", e));
```

Perhaps the docs should state that `doThat` must be promisified for it to be exactly the same? Or is it already assumed to always return a Promise?

Or perhaps use `Promise.try` in the example?
http://bluebirdjs.com/docs/api/promise.try.html

**Comment by bergus** [comment]
Yes, `doThat` is expected to be a promisified function that never throws (but returns a rejected promise instead).
