### ISSUE TITLE
Update benchmark results?

### ISSUE THREAD

**Issue by albell** [petkaantonov/bluebird#1167]
The published <a href="https://github.com/petkaantonov/bluebird/tree/master/benchmark">benchmarks</a> are now a year and a half old. I would love to see comparisons across the current landscape, including the recent Promise optimizations in <a href="http://v8project.blogspot.co.uk/2016/07/v8-release-53.html?m=1">V8 Release 5.3</a>. Thanks.

**Comment by petkaantonov** [comment]
The benchmark runner is written for node which doesn't use 5.3 for a while I think

**Comment by benjamingr** [comment]
I think we should update the results once V8 is at 5.3 for Node, which I think is Node 8.

Once that lands - let's re run the benchmarks and update the page. Before that it makes no sense.

**Comment by gajus** [comment]
Node.js V8 is now 5.4.

Would make sense to update the benchmarks.

In the mean time, please see https://github.com/petkaantonov/bluebird/issues/1279
