### ISSUE TITLE
Feature Request: make the promisified promise assertable

### ISSUE THREAD

**Issue by matianfu** [petkaantonov/bluebird#1168]
It is common to write functions return promise.

For unit testing such functions, the returned promises are usually resolved and the fulfilled value or rejected error are asserted. If the returned promises contains only asynchrony but no side effect, that is, asynchronously pure, this approach is acceptable.

But in real world applications, especially in node, the promise probably wrapped a function with side effect, such as I/O operation. Then the test must take into account the side-effect function's possibilities, which is annoying, especially in the case that the promise wrapped a single node api or third party library function. We are not intended to test them at all.

So I think a better approach is to directly assert the returned promise itself. Of course, in some cases the promise wraps an asynchronous function, which can not be applied for an equality check. But we can always slightly modify the source code to give it a name.

The feature I requested could be described as:

If the promise is promisified from an asynchronous function, and then it is called with arguments and returned. Then I hope that I can assert:

1. it is a promisified promise.
2. the original promisified function equals to certain function
3. the bound function's boundThis and boundArgs can be retrieved and asserted.

If all these are available. then users, who want to practice functional programming as purely as possible, can write pure functions returning promise, and the promise can be asserted directly without resolving it and considering all the side-effect operations wrapped into the promise for testing.

I consider this would be a huge benefit. Promise is a great solution for asynchronous problem. But Promise itself is an opaque object, with no way to inspect it unless it is resolved. This contradict to the functional programmer's belief. All pure functions must return values or collection of values that can be verified directly, without ambiguity and side-effect.

I really really really hope bluebird will provide such feature. Otherwise, I must write a separate wrapper function, wrapping all functions passed to .then() and .catch() call. And all pure functions which will trigger an asynchronous/side-effect operation will return a plain object equivalent to a (partially) bound callback function. This is painful. Since such functions won't be directly compatible with other codes which aren't written in this way.

**Comment by spion** [comment]
Promises are not pure, unfortunately, since their side effects are executed immediately after they're created. If I understood correctly, you probably want an abstraction with different semantics, like IO actions (where you can swap the interpreter with one that verifies that the correct actions have been produced), or to use more conventional techniques like spies to verify that methods have been called...

**Comment by petkaantonov** [comment]
Not sure if I fully understood this but it seems far out of scope and something that should be in a testing framework.
