### ISSUE TITLE
blue

### ISSUE THREAD

**Issue by blackevil245** [petkaantonov/bluebird#1169]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) This happend on Bluebird@3.4.1

2) Node 4.3.2

3) Yes

BLUEBIRD_LONG_STACK_TRACES Doesn't behave like it should. As documented it is set to false by default, which is 0, so setting it to 1 is supposed to enable long stack trace, but now it is reversed, 1 actually shorten the trace and 0 lengthen it ( by default )

**Comment by benjamingr** [comment]
Only when you have the node environment variable not set to "production" which is typically locally, this is similar to what a lot of libraries and frameworks do.

Set the `NODE_ENV` environment variable to "production" and the default becomes no long stack traces.

http://stackoverflow.com/questions/16978256/what-is-node-env-in-express
