### ISSUE TITLE
`Promise.delay()` does not delay when 

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1174]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

v3.4.1 and v2.10.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node v6.3.0, OS X 10.9.5

3) Did this issue happen with earlier version of bluebird?

Yes - apparent on both bluebird v2 and v3

---

`Promise.delay()` does not delay if the value it's returning after the delay is a rejected promise.

```js
Promise.delay( 10000, Promise.reject( new Error('foo') ) )
.catch( function() {
	console.log('Caught!');
} );
```

```js
Promise.reject( new Error('foo') ).delay( 10000 )
.catch( function() {
	console.log('Caught!');
} );
```

In both cases, the catch callback is executed immediately, rather than after a 10 sec delay.

I'm not sure if this is the desired behavior or not.

**Comment by benjamingr** [comment]
Yes, this is the intended behavior.

**Comment by benjamingr** [comment]
Added clarification, will be up on next docs build-  thanks https://github.com/petkaantonov/bluebird/commit/012d5e75a815e88a3428b8c414ba82a8fca221a9

**Comment by overlookmotel** [comment]
OK great. Thanks for clarifying.
