### ISSUE TITLE
`onCancel` handler executed asynchronously

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1177]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

v3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node v6.3.0, OS X 10.9.5

3) Did this issue happen with earlier version of bluebird?

Not applicable for Bluebird v2.x. I haven't checked previous 3.x versions.

---

The docs state that ".cancel() is synchronous" but `onCancel` handlers are executed asynchronously.

```js
Promise.config( {cancellation: true} );

var p = new Promise( function(resolve, reject, onCancel) {
	onCancel( function() {
		console.log('cancelled');
	} );

	setImmediate( resolve );
} );

p.cancel();

console.log('next sync statement');

Promise.resolve().then( function() {
	console.log('then');
} );
```

The above outputs:

```
next sync statement
cancelled
then
```

i.e. the `onCancel` handler is not executed synchronously.

This may be intended behavior, but if so it'd be good to mention it in the docs.

**Comment by petkaantonov** [comment]
Yes onCancel user callback execution is queued to be executed asynchronously
