### ISSUE TITLE
Thrown error in `onCancel` handler is not thrown synchronously

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1178]
1) What version of bluebird is the issue happening on?

v3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node v6.3.0, OS X 10.9.5

3) Did this issue happen with earlier version of bluebird?

Not applicable for Bluebird v2.x. I haven't checked previous 3.x versions.

---

When an error is thrown in an `onCancel` handler, it is not handled and crashes the node process.

That's expected, but what is strange is that it does not crash node immediately - it does so in next tick.

```js
Promise.config( {cancellation: true} );

var p = new Promise( function(resolve, reject, onCancel) {
	onCancel( function() {
		console.log('cancelled');
		throw new Error('Cancelled');
	} );

	setImmediate( resolve );
} );

p.cancel();

console.log('next sync statement');

Promise.resolve().then( function() {
	console.log('then');
} );
```

Outputs:

```
next sync statement
cancelled
then
[stack trace]
```

i.e. the later `.then()` callback executes between the onCancel handler being run and the error being thrown.

Possibly related to issue #1177.

**Comment by petkaantonov** [comment]
That's intended, like with disposer cleanup callbacks. The error is caught first and only rethrown later so that all internal state can be finished and cleaned properly.
