### ISSUE TITLE
Scheduler (MutationObserver) stops firing on iOS 9.3.2 after heavy use

### ISSUE THREAD

**Issue by curveship** [petkaantonov/bluebird#1180]
1) What version of bluebird is the issue happening on?
2.10.2 (relevant code looks to be the same in 3.4.1 but have not tested)

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Cordova application running on iOS 9.3.2

3) Did this issue happen with earlier version of bluebird?
Yes for 2.9.25, probably all others.

We have a Cordova application which uses bluebird for handling async calls to Cordova plugins.  We've observed that under heavy use, like 10-30 seconds of rapid interaction with the application, bluebird stops draining its internal queue of callbacks when running on iOS 9.3.2.  In this environment, bluebird is picking the MutationObserver schedule strategy (window.navigator.standalone is false in a Cordova iOS project).  Async.isTickUsed is true, indicating that the internal DIV has apparently had its class toggled, but drainQueues is never called and callbacks continue to accumulate.

Using setScheduler() to replace the MutationObserver scheduler with setTimeout(..., 0) resolves the problem.

Unfortunately, we don't have a reduced repro of this scenario.  We can produce it fairly consistently in our application via a short period of heavy use.

Our hypotheses are either:
- a bug in bluebird causes Async.isTickUsed to remain true, preventing further ticks to the scheduler, or
- a bug in UIWebView 9.3.2 causes MutationObserver to stop firing, or
- same as above, but it's an intentional strategy on Apple's part to muzzle a too-active MutationObserver?

**Comment by petkaantonov** [comment]
Afaik setTimeouts are also dropped or at least not called when the app is in background.

**Comment by benjamingr** [comment]
@petkaantonov how do you feel about racing multiple schedulers? Would the overhead of just setting a setTimeout and clearing it in browsers be problematic?
