### ISSUE TITLE
No call stack with runaway promise warning

### ISSUE THREAD

**Issue by ben-page** [petkaantonov/bluebird#1181]
1) What version of bluebird is the issue happening on? **3.4.1**

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32) **Node.js 6.3.1 on Windows x64**

3) Did this issue happen with earlier version of bluebird? **It appears to have started in 3.3.0**

When I receive the runaway promise warning, I never receive a call stack. 

```javascript
'use strict';
const Promise = require('bluebird');
Promise.config({
    warnings: true,
    longStackTraces: true
});

Promise.resolve()
    .then(() => {
        Promise.resolve()
            .then(() => {
                console.log('inner');
            })
    })
    .then(() => {
        console.log('outer');
    });
```

Here's the console output:
```shell
(node:3264) Warning: a promise was created in a handler but was not returned from it
inner
outer
```

It seems to be a regression in version 3.3.0, because on 3.2.2 I get a stack trace.
```
Warning: a promise was created in a handler but was not returned from it
    at Promise.resolve.then (C:\projects\test\index.js:10:17)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
From previous event:
    at Object.<anonymous> (C:\projects\test\index.js:9:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

inner
outer
```

**Comment by ben-page** [comment]
The call stack works with bluebird 3.4.1 on Nodejs 4.7.1. So it seems like 3.3.0 broke support for the Nodejs 5.x./6.x call stack format.

**Comment by ben-page** [comment]
I've noticed a second related problem. Promise.delay() does not produce a useful call stack.

**Comment by ben-page** [comment]
So the problem is that by default Nodejs 6.x does not display stack traces for warnings. There is a command line option (`--trace-warnings`) to enable them. Without this option Bluebird warnings are a lot less useful, because it can be very difficult to figure out where they are coming from.

**Comment by ben-page** [comment]
Another option is to replace the default event handler for the `process` `warning` event. 

```javascript
        //remove default listener that does not print call stack and replace it with one that does
        if (process.listenerCount('warning') === 1) {
            process.removeAllListeners('warning');
            process.on('warning', function (warning) {
                console.error(warning.stack);
            });
        }
```

I put that behind the `warnings` Bluebird option and it worked perfectly in 6.x, 5.x, and 4.x, because it's ignored in old versions of Node as the 'warning' event does not exist and has 0 listeners.

**Comment by petkaantonov** [comment]
I think the only option is to change the event name, the warning event is implemented in a strange way in node: the event is emitted regardless if there are any listeners and default behavior is implemented through a forced event listener that doesn't disappear when the users add their own listeners

**Comment by benjamingr** [comment]
I don't see the problem with having people run Node with --trace-warnings

**Comment by benjamingr** [comment]
@petkaantonov it's just controlled from command line flags. Bluebird was actually a consideration for a userland user of warnings. I don't think we should change the event name.

**Comment by petkaantonov** [comment]
We should document the flag
