### ISSUE TITLE
`.fork()` method missing

### ISSUE THREAD

**Issue by overlookmotel** [petkaantonov/bluebird#1188]
1) What version of bluebird is the issue happening on?

v3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node v6.3.0, OS X 10.9.5

3) Did this issue happen with earlier version of bluebird?

Issue not present on bluebird v2.10.2.

---

The docs (http://bluebirdjs.com/docs/deprecated-apis.html) state that "Again, only the variant with the progression handler is deprecated here. `.fork` is still fully supported." But in bluebird v3.4.1 the `.fork()` method doesn't exist.

I don't know if `.fork()` makes sense with the v3 cancellation semantics. But if it has been removed, the docs should be updated.

**Comment by benjamingr** [comment]
Did you enable cancellation through `Promise.config`?

**Comment by overlookmotel** [comment]
@benjamingr Yes, I tried with cancellation enabled.

Searching the source code for "fork" also brings up no matches.

**Comment by petkaantonov** [comment]
The docs should be updated.. that text is assuming 2.x

**Comment by overlookmotel** [comment]
Thanks for clarifying.
