### ISSUE TITLE
NativePromise.resolve not a function?

### ISSUE THREAD

**Issue by jdelStrother** [petkaantonov/bluebird#1192]
1) What version of bluebird is the issue happening on?
3.3.5

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Linux Chrome 52 (allegedly)

3) Did this issue happen with earlier version of bluebird?
Unsure.

I have a number of error reports in my js reporter that claim to be coming from Linux Chrome 52, where requiring bluebird immediately throws an exception on calling `NativePromise.resolve()` (https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js#L22).   I can't reproduce this on my own version of Chrome 52 on Ubuntu, but wondered if anyone was aware of an environment where `util.getNativePromise()` would return a value, yet that value wouldn't have a `resolve` function.

**Comment by jdelStrother** [comment]
@petkaantonov awesome, thanks.  Were you ever able to actually reproduce the problem?

**Comment by petkaantonov** [comment]
no unless you mean doing something like `delete Promise.resolve` before loading bluebird

**Comment by petkaantonov** [comment]
It seems to be an issue with some Chrome extensions: https://www.reddit.com/r/javascript/comments/4zk25d/why_doesnt_chrome_52_have_promiseall_why_doesnt/?st=isben1as&sh=e087c177
