### ISSUE TITLE
Hard-coded debug = true kills IE11 performance

### ISSUE THREAD

**Issue by MikaelPorttila** [petkaantonov/bluebird#1197]
Hard-coded debug true on this line makes IE11 extremely slow:
https://github.com/petkaantonov/bluebird/blob/v3.4.1/js/browser/bluebird.core.js#L539

1) What version of bluebird is the issue happening on?
3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
IE11

**Comment by petkaantonov** [comment]
That's the development build, the value isn't hard coded but chosen at build time
