### ISSUE TITLE
Promises with a timeout set to `Infinity` are immediately rejected

### ISSUE THREAD

**Issue by not-an-aardvark** [petkaantonov/bluebird#1200]
Please answer the questions the best you can:

> 1) What version of bluebird is the issue happening on?

3.4.1

> 2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node v6.4.0

> 3) Did this issue happen with earlier version of bluebird?

Unsure

> (Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

```js
var Promise = require('bluebird');

var myPromise = Promise.delay(50).timeout(Infinity);
```

This Promise should never time out, since its timeout counter is infinite. Instead, the Promise immediately rejects with a TimeoutError.

This came up in practice when implementing an optional timeout parameter for an API:

```js
// should use the timeout parameter if one is provided, but should never time out if no parameter is provided
getAPromise().timeout(userProvidedOptions.timeout || Infinity)
```

---

The issue seems to occur because bluebird uses `setTimeout` to schedule Promise timeouts, but `setTimeout` only works up to delays of 2147483647 (~25 days), above which the function executes immediately.

**Comment by jcready** [comment]
> This came up in practice when implementing an optional timeout parameter for an API:
> 
> ```js
> // should use the timeout parameter if one is provided, but should never time out if no > parameter is provided
> getAPromise().timeout(userProvidedOptions.timeout || Infinity)
> ```

Why can't you just handle this in your code?

```js
// should use the timeout parameter if one is provided, but should never time out if no parameter is provided
var promise = getAPromise()
if (userProvidedOptions.timeout) {
  promise = promise.timeout(userProvidedOptions.timeout)
}
return promise
```

**Comment by not-an-aardvark** [comment]
> Why can't you just handle this in your code?

I did. This issue certainly has workarounds, but I was just giving an example of a realistic use-case for setting a timeout to `Infinity`.

---

One potential fix for this would be to cap the timeout at 2<sup>31</sup> - 1 in all cases. It's incorrect, but it's unlikely anyone will ever notice.

**Comment by benjamingr** [comment]
Ok, after losing 15 minutes over this:

What you describe is the intended behavior actually.

This is an issue with `setTimeout`. In some browsers (like Chrome) setTimeout executes the called code _immediately_ sometimes for no good reason.

I don't see anything in [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#timer-initialisation-steps) to allow this. 

```js
// ran in Chrome 52
setTimeout(function () {
        console.log("HI")
}, 192e90);
// Hi is logged immediately
setTimeout(function () {
        console.log("HI")
}, 192e35)
// Hi is logged immediately
setTimeout(function () {
        console.log("HI")
}, Infinity)
// hi logged immediately (VM192:2 HI)
```

There is not much bluebird can do about this - I suggest you open a ticket @ Chromium. Node actually [explicitly aligns itself](https://github.com/nodejs/node/blob/master/lib/timers.js#L10) with what browsers do.

I think it is better to behave the same as browsers and Node with regards to timing things and not differently - though I find this behavior somewhat confusing.
