### ISSUE TITLE
API addition: like .tap, but for errors

### ISSUE THREAD

**Issue by Ry7n** [petkaantonov/bluebird#1204]
If find myself writing code like this quite a bit:

```js
Bluebird.
  try(() => { /* do something */ }).
  catch(SpecialTypeOfError, e => { doSomethingSpecial(e); throw e; }).
  // onward with the promise chain...
```

Would you accept a PR to add a `.rethrow` method, that works essentially like `.tap`:

```js
Bluebird.
  try(() => { /* do something */ }).
  rethrow(SpecialTypeOfError, doSomethingSpecial).
  // onward with the promise chain...
```

**Comment by spion** [comment]
Can you please post concrete examples?

**Comment by benjamingr** [comment]
This is the fourth time this is requested btw https://github.com/petkaantonov/bluebird/issues/517 - I'm going to close this since we already discussed this three times - but feel free to reopen @petkaantonov @spion

**Comment by Ry7n** [comment]
The primary use case for this would be error cases that have side effects, or trigger behavior based on aggregate data that might succeed, or might fail with an error we want to ignore in the context of the promise chain.

**Rate Limiting**
```
Bluebird.
  try(logIn).
  then(respondWithSuccess).
  catch(InvalidCredentialsError, countFailuresForRateLimitingPurposes).
  catch(respondWithError);
```

**Circuit Breakers**
```
Bluebird.
  try(makeRequest).
  then(respondWithSuccess).
  catch(RequestError, adjustCircuitBreakerState).
  catch(respondWithError);
```

**Logging**
```
Bluebird.
  try(doAThing).
  catch(logErrorsRelatedToThatThing).
  then(respondWithSuccess).
  catch(respondWithError);
```

This case is useful when you're stuck using generic error types (e.g. just `Error`).
