### ISSUE TITLE
promisifyAll doesn't update protoypes of mysqljs when bundled using Webpack

### ISSUE THREAD

**Issue by sxmichaels** [petkaantonov/bluebird#1211]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.4.3

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js v6.4.0, Mac OS X 10.11.6.

3) Did this issue happen with earlier version of bluebird?
Unknown. This is the first version of Bluebird that I've used.

I use the following code in a module I'm working on:
```
const mysql = Promise.promisifyAll(require('mysql'));
Promise.promisifyAll(require('mysql/lib/Connection').prototype);
Promise.promisifyAll(require('mysql/lib/Pool').prototype);

const pool = mysql.createPool(MYSQL_CONFIG);

function getConnection() {
  return pool.getConnectionAsync();
}
```

In my application's `index.js`, I `require` the above module and run `getConnection()`.
If I run the `node` interactive CLI and `require('./index.js')`, the module runs as expected — `getConnection()` doesn't cause any errors. However, something strange happens when I bundle my application with Webpack: when the resulting code runs, I get the following error:

```
/srv/nSERVER/webpack:/app/database.js:21
  return pool.getConnectionAsync().disposer((conn) => {
^
TypeError: pool.getConnectionAsync is not a function
    at getConnection (/srv/nSERVER/webpack:/app/database.js:21:1)
    at Object.testConnection (/srv/nSERVER/webpack:/app/database.js:31:1)
    at Object.<anonymous> (/srv/nSERVER/webpack:/server.js:12:1)
    at __webpack_require__ (/srv/nSERVER/webpack:/webpack/bootstrap 686ec6e0eea1e08d3780:19:1)
    at /srv/nSERVER/webpack:/webpack/bootstrap 686ec6e0eea1e08d3780:39:1
    at Object.<anonymous> (/srv/nSERVER/webpack:/webpack/bootstrap 686ec6e0eea1e08d3780:39:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Some manual debugging reveals that the `Async`-suffixed functions are added to the `mysql` Pool and Connection classes properly when running `index.js` manually, but when the application is built with Webpack, none of those methods are present. (Async functions within `mysql` itself are added.)

If I save the results of `promisifyAll` like so
```
const Connection = Promise.promisifyAll(require('mysql/lib/Connection').prototype);
const Pool = Promise.promisifyAll(require('mysql/lib/Pool').prototype);
```
then I can write something like
```
const pool = mysql.createPool(MYSQL_CONFIG);
function getConnection() {
  return Pool.getConnectionAsync.call(pool);
}
```
and get the intended behavior. However, it's my impression that the Webpack version should not behave any differently — is this a bug, or is there a Webpack/Bluebird compatibility setting that I don't know about?

**Comment by petkaantonov** [comment]
If it works in node but not in webpack, then it seems it's a webpack issue not bluebird. Besides I don't think the mysql module works on client side anyway.
