### ISSUE TITLE
Promise.config should return Promise for method chaining

### ISSUE THREAD

**Issue by artemjackson** [petkaantonov/bluebird#1223]
It would be great if `Promise.config` returns `Promise` object.
This will allow method chaining e.g.:
```
var Promise = require('bluebird')
  .config({
    ...
  });
```

**Comment by benjamingr** [comment]
#1225 closes this.

**Comment by benjamingr** [comment]
I'm wondering if we should do this for consistency on all `Promise` methods. Will open another issue/pr

**Comment by benjamingr** [comment]
Nevermind, I see most other methods like setScheduler already have return values.
