### ISSUE TITLE
Does Bluebird have a feature that allows the promise chain to act like scope chain?

### ISSUE THREAD

**Issue by fourq** [petkaantonov/bluebird#1228]
Does Bluebird have a feature that allows the promise chain to act like a scope chain?

```js
func()
  .then(one => {//has access to ...global})
  .then(two => {//has access to 1, ...global})
  .spread(three => {//has access to 2, 1, ...global})
  .then(four => {//has access to 3, 2, 1, ...global});
```

**Comment by benjamingr** [comment]
Please ask support questions in the appropriate support channels (disqus, StackOverflow, IRC etc) as mentioned in the README and in the site.

**Comment by bergus** [comment]
That said, you're looking for http://stackoverflow.com/q/28250680/1048572?how-do-i-access-previous-promise-results-in-a-then-chain and http://bluebirdjs.com/docs/api/promise.coroutine.html

**Comment by fourq** [comment]
Thanks @bergus
