### ISSUE TITLE
Detect if bluebird is used instead of native Promises

### ISSUE THREAD

**Issue by jan-swiecki** [petkaantonov/bluebird#1237]
Is there a way to automatically verify that my code uses bluebird promises instead of native ones? In other words I would like every file that uses `Promise` object to be checked if there is a `var Promsie = require('bluebird');` in the beginning of the file.

If there is no such tool I will happily write one, when I have time that is:).

Edit
I'm using Node v4 with ES6 and the way I'm using promises is polyfilling/replacing original Promise object with Bluebird one. It's the same approach that Bluebird promotes in their documentation [here](http://bluebirdjs.com/docs/getting-started.html).

**Comment by MarkHerhold** [comment]
I don't know if there is a better way, but you could do:

```js
var Promise = require("bluebird");
console.log(Promise.version); // "3.4.6"
```

So if you get a string back from `Promise.version` it's not the native promise implementation. :)

**Comment by jan-swiecki** [comment]
Interesting, thanks for reply:).

I still need to remember about adding check for `Promise.version` though. It's like remembering about adding `var Promise = require("bluebird");" in the first place:).

**Comment by MarkHerhold** [comment]
Oh are you talking about polyfilling a promise implementation if none exists? That's not what your original question asked.

**Comment by spion** [comment]
You can switch to `var Bluebird = require('bluebird')`

**Comment by eteeselink** [comment]
You could use a tool like eslint. Eslint, in ES6 mode (`{env: "es6"}`) assumes `Promise` is a global object, but if you *don't* put it in ES6 mode it'll consider Promise to be undefined and raise the `no-undef` warning if it's used in a file but not required.

As a bonus it won't just catch undefined `Promise` variables being used, but all undefined variables :-)

**Comment by jan-swiecki** [comment]
To clarify guys.

1. I'm using NodeJS with ES6 (lambdas for example).
2. I'm polyfilling native Promises via `var Promise = require('bluebird');`

Sometimes I forget to polyfill and I get unexpected application behaviour, because native promises were used (for example bluebird shows uncaught exepctions, native Promises don't).

I wanted something along the lines what @eteeselink proposed. Something that would analyze code and show here I didn't polyfill original promises.

Alternative is what @spion proposed, of course :). But I wanted to polyfill because it seems more elegant (at least from one point of view) and that is what Bluebird promotes as way using Bluebird.

Thanks all for your input.

**Comment by MarkHerhold** [comment]
@jan-swiecki Does setting it to the global object at application load not work?

```js
global.Promise =  = require('bluebird');
```

**Comment by jan-swiecki** [comment]
@MarkHerhold It does, but I believe it's not considered a good practice to have global objects. Of course you have pros and cons of this approach. Thanks for suggestion, I might use it. What I believe is that too that analyzes code is best. It seems no such tool exists.

It would be easy to create such tool I believe - It's possible to use esprima [identifier highlighting](http://esprima.org/demo/highlight.html) feature and find `Promise` variable declaration - if there is none then report an error.

**Comment by jan-swiecki** [comment]
After some thinking on this I have a thought on this. There maybe should be some way of replacing `Promise` object in NodeJS runtime. So `Promise` object would be replaced with bluebird instance. For example

    node --promise=bluebird index.js

It's crazy probably :).

**Comment by benjamingr** [comment]
@jan-swiecki it was discussed internally (in Node) and ruled out. Bluebird promises are not JS builtins, they fulfill the same contract with a richer faster API.

**Comment by jan-swiecki** [comment]
@benjamingr so please modify Bluebird documentation. Currently Bluebird is encouraging usage of `var Promise = require('bluebird');` which is a trap. By trap I mean situation whenever somebody forgets to import blurbird and by mistake original Promise object is used and application either breaks (easy to fix) or there are silent errors (original Promise doesn't print to console uncaught errors in promise chain).

**Comment by eteeselink** [comment]
I think most people just use bluebird to replace the global `Promise` object and call it a day.
