### ISSUE TITLE
Is Bluebird compatible with node 0.10.33

### ISSUE THREAD

**Issue by aabm00** [petkaantonov/bluebird#1241]
Hi.

I have 2 Arduino Yun working as a client sending messages every 30 seconds (at 00 and 30 seconds). 
The versions of node and node-serial and socket.io in the Arduinos are:

node --> 0.10.33-1
node-serialport --> 1.4.6-2 
socket.io-client --> 1.4.8
bluebird            --> 3.4.1

The versions in the server are:

node --> 4.4.5
socket.io --> 1.4.8

I have 2 version of the code, with **Callbacks** and with **Promises**.

With **Promise code**  The Arduinos are switched off and after 22 seconds or so are reconnected, but it'doesn't happen with the **Callback code**

Can be some problem with the version of the Bluebird library?
What version would be the correct for node 0.10.33-1?

Keep in mind that I can't upgrade the version of the node and node-serialport in the arduinos because it depends of the linux installed) so in case that can be problems with the versions, I'd have to change the Bluebird version.

Thanks

**Comment by benjamingr** [comment]
Bluebird integration is run regularly against Node 0.10, everything is tested against Node 0.10 at every version release. That said, non of use use 0.10 anymore (I think?). 

If you could create a short self reproducing example I can help you out.

**Comment by aabm00** [comment]
I understand for your answer that any Bluebird must work with node 0.10.

It's a litle bit complicated to reproduce it with a snippet, but I try to explain it

I have 10 sensors sending data every 30 seconds. 
The listener of every sensor is an instance of EventEmitter so we'd have:

> p0.on('data', listener)..... p9.on ('data', listener).

I create the listeners from a for loop like:

    pSensors = {},

    function _createSensors() {

       for( var i = 0; i < pKeys.length; i++){

           var sensor  = 'p' + i;
 
           pSensors[sensor] = new Sensor( );


           // CREATE LISTENERS FOR SENSORS //
          var listener = _createListener(sensor);

          // ADD LISTENERS TO SENSORS //
          pSensors[sensor].on('data', listener);
    }

> _createListener(sensor) --> return a callback -->  function( data ) {...}

So the result final would be 10 listeners for the data received from the sensors like 

> p0.on ('data', function( data ) {...})..... p9.on ('data', function( data ) {...}).

So my question is:

**How can I do this same code with Promises (Bluebird)?**  

So I get a fullfilled promise from every sensor when it receive data

Thanks

**Comment by benjamingr** [comment]
Promises are for one time events - they do not work well in multiple-events scenarios.

I recommend you use something other than promises for this - EventEmitters are easy, Rx is nice.

**Comment by aabm00** [comment]
Thanks for the quick answer.

I am new with promises and I would appreciate a little explanation about the reason promises doesn't work fine with events. 

Thanks again

**Comment by aabm00** [comment]
Hi @benjamingr 

I am sorry, I would appreciate if you could clarify one doubt.

I wanted to use ES6  Promises + Generators  using Bluebird and the Bluebird.cororutine, in both (client and server) but in my Use case (multiple-event) you said isn't the best option. 
I've taken a look to RxJS, as you recommend and as you said it looks like can do the same as the Promises but even better.
I wanted to use generators (async/await) to write the async code to look as sync, and my question is:

Can I use RxJS + (async/await) or RxJS  has already its own way to do the same as (async/await) ?

Thanks again

**Comment by benjamingr** [comment]
Promises are for one time events. You can't use them for tre data event of sensors once since those fire multiple times.

**Comment by aabm00** [comment]
Thanks for clarify, but I don't know If you have seen my last message !!!

**Comment by benjamingr** [comment]
The issues are for bug reports and feature requests as clearly stated in the readme. I intend to answer your question when scoped as such - at this point you're asking for general advice in writing your code which I can gladly answer in StackOverflow or in IRC or in the SO gothic chat. Just not here since it pings tens of people who watch bug reports.

Thanks for understanding.
