### ISSUE TITLE
memory leak on mobile safari iso9.3.3

### ISSUE THREAD

**Issue by guzuomuse** [petkaantonov/bluebird#1242]
1) What version of bluebird is the issue happening on?
3.4.6
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
IOS--9.3.3
3) Did this issue happen with earlier version of bluebird?
not test...
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

you can make a empty html file, and inclue the  script src='bluebird.js'

and then refresh your mobile safrari browser again and agian, open your ssh connect your iphone ,and you can see the memory increasing infinitly......!!

**Comment by benjamingr** [comment]
You're claiming bluebird is leaking memory when the page is refreshed _on the device_. This is not something related to bluebird nor can we fix this.

I have been unable reproducing this (I was curios) - I'm not sure what setup you have going on.
