### ISSUE TITLE
make Promise.each run in parallel, add Promise.eachSeries

### ISSUE THREAD

**Issue by charlierudolph** [petkaantonov/bluebird#1244]
It seems inconsistent to me that `each` runs serially and `map` runs the iteration in parallel.
Since there is already `mapSeries`, I'd suggest a breaking change where `each` is updated to run in parallel (and also gets the concurrency option map has) and `eachSeries` is added to retain the current functionality.

**Comment by benjamingr** [comment]
That's not going to happen. The naming convention is established and other languages and libraries behave similarly.

Each is `forEach` where iteration order can be meaningful since the intention is to do side effects. `map` means the items are execution order independent.

**Comment by benjamingr** [comment]
Also it would be a bug breaking change.

**Comment by charlierudolph** [comment]
Can we have a variant of `Promise.each` then that runs in parallel? I don't like the word `map` when I'm iterating over something and don't care about the results but I like the API it provides.

**Comment by charlierudolph** [comment]
@benjamingr any response to my previous comment

**Comment by spion** [comment]
`Promise.each` running in parallel means side-effects with random order, something that should be discouraged.
