### ISSUE TITLE
Promise.reject leads to catch rather than error

### ISSUE THREAD

**Issue by allonhadaya** [petkaantonov/bluebird#1245]
```
bluebird: 3.4.6
node: 5.12.0
```

My impression is that `Promise.reject` is supposed to return a rejected promise and trigger `error`, but instead I'm seeing it trigger a `catch`:

```js
var Promise = require('bluebird').Promise;

Promise
  .reject()
  .error(() => { console.log('error!'); })
  .catch(() => { console.log('catch!'); });

// > catch!
```

It looks like [this commit](https://github.com/petkaantonov/bluebird/commit/9c649f703ff809f9facb052fd6f2a32bacbd89d9#diff-bdbe8b178ed02fc38d7fda842fc1975aR242) was supposed to make `Promise.reject` lead to `error`, but it's no longer the case in `src/promise.js`.

Is this a regression, or a change in the interface?

Thanks!

**Comment by allonhadaya** [comment]
Okay, [the interface was changed](https://github.com/petkaantonov/bluebird/blob/5bffd55f20f1df5361603612867f286fa13e56e3/docs/docs/new-in-bluebird-3.md):

> Errors created with Promise.reject or reject callback of new Promise are no longer marked as OperationalErrors.

So how do I distinguish between rejections and thrown errors?

**Comment by benjamingr** [comment]
This is required for compatibility with native `Promise.reject`. You should always reject with proper errors and you will receive a warning if you reject with a non-warning.

You are not supposed to distinguish rejections and thrown errors - you can use `.catch` with a predicate/type and `error` still works great - you just need to raise errors with `isOperational = true` (promisified errors are of that sort automatically).

In general - support questions are a better fit on StackOverflow.

**Comment by allonhadaya** [comment]
Aha, thanks for the explanation! Very informative. (I'll post support questions on StackOverflow next time)
