### ISSUE TITLE
putting catch before then in the chain, intended behavior?

### ISSUE THREAD

**Issue by wayofthefuture** [petkaantonov/bluebird#1251]
So to make our code more concise, we implement a module-wide error function catch. It really reduces and cleans up the code, especially when you have 20 on a page:

```javascript
myPromise.catch(logError).then((res) => {
    console.log(res);
});
```

But this has unintended behavior because the "then" is always called even when a reject() is fired.

```javascript
test('a')
	.catch(err => {console.log('error ' + err.message)})
	.then(res => { console.log(res) });

function test(item) {
    return new Promise((resolve, reject) => {
    	if (typeof item === 'number') {
    		resolve(item);
    	} else {
    		reject(new Error('item not number'));
    	}
    });
}
```

which yields:
error item not number
undefined

The "undefined" means the "then" was called. Is it crazy to put the catch before the then? Is there another way to accomplish this without putting the catch last? Thanks.

**Comment by spion** [comment]
`.catch` transforms errors into non-errors.

You want https://github.com/petkaantonov/bluebird/pull/1220

**Comment by wayofthefuture** [comment]
Would ".tap" work for what I'm trying to do? Thanks.
