### ISSUE TITLE
Question/Feature Request: `.props` to work on ES6 class instances

### ISSUE THREAD

**Issue by jasonkarns** [petkaantonov/bluebird#1253]
The following does not work because the defined properties are not enumerable:

```
class Foo {
  get bar() { return somePromise; }
  get baz() { return otherPromise; }
}

Promise.props(new Foo()).then(
  ({bar, baz}) => // doesn't resolve these properties
);
```

Personally I think it *should* resolve ES5 non-enumerable properties (such as those defined via ES6 classes). Presently, the code is getting the properties to resolve via `Object.keys`, which only lists own enumerable properties.

While we're discussing this, I'd expect .props to resolve inherited properties as well. Is there an intentional reason for only resolving own properties that are enumerable? Or was this just an incidental side effect of using Object.keys for the enumeration?

Do others see value in this behaving one way or the other?

**Comment by benjamingr** [comment]
I presume the lack of response is that we all only ever used it for enumerable own properties when passing an object literal and not a class. 

It was intended to not enumerate enumerable properties since someone might extend `Object.prototype` with an enumerable property and it'd break `.props` otherwise.

**Comment by jasonkarns** [comment]
This: 

> It was intended to not enumerate enumerable properties

does not make sense. bluebird _does_ resolve enumerable properties. What it does _not_ do is resolve *non* enumerable properties. I can see a case for not resolving _inherited_ properties so I'll ignore that for now. (Though nothing thus far has addressed inherited _enumerable_ properties.)

So this still leaves my original request of resolving _own non-enumerable_ properties; which would not be susceptible to the `Object.prototype` extension issue that you mentioned. My proposal would simply change the current `Object.keys` iteration to `Object.getOwnPropertyNames`

**Comment by benjamingr** [comment]
I obviously meant to say "non enumerable" no need to be snarky.

The point of non-enumerabity being a thing is precisely to opt out of enumerations like Promise.props does. If you want enumerating methods to enumerate your properties - why not make them enumerable?

**Comment by jasonkarns** [comment]
There was no snark intended.

I could make them enumerable, but the code for that is ugly. So ugly, in fact, that i don't find it worth doing just to get support for a single method. That's why I feel bluebird.props should just support simple ES6 class- created objects like:

```
class Foo {
  get bar() { return somePromise; }
  get baz() { return otherPromise; }
}
```

In my current codebase, I converted the entire class into a factory just so I could return a plain object rather than class instance. (which I hated doing) But conceptually, I don't see why bluebird should distinguish: `{ bar, baz}` from `new Foo` when they are nearly identical objects.

**Comment by spion** [comment]
We can't support getter properties without also supporting all non-enumerable properties. Not only would that break backward compatibility, but once we do that, there is no longer a way for users to hide properties from the `props` method. The capability is easily achieved with a factory function, and will become less ugly for classes via decorators once they become available. So overall I'm -1 on this.

**Comment by benjamingr** [comment]
Or a decorator, or your own .props. The point of enumerability in the language is that these things should not be enumerated. Enumerating getters is stateful which is another possible issue. Also -1

@petkaantonov let us know if you strongly disagree.
