### ISSUE TITLE
isFullfilled returning false

### ISSUE THREAD

**Issue by c0debreaker** [petkaantonov/bluebird#1258]
Hi,

We are using BluebirdJS. My teammate showed his code to me. Basically inside .then(), he is calling an outside function that has an `if (this.thePromise.isFullfilled()) { ....}`. However, the value of isFullfilled() is still false.

```
the.model.fetch().then() {
  this.FilterData();
}

FilterData() {

  if (this.thePromise.isFullfilled()) {
    // do stuff here, however, it's not happening
  }
}
```

**Comment by bergus** [comment]
Are you sure they refer to the same promise? Please post a complete reproducable example.

**Comment by c0debreaker** [comment]
How can we verify if the isFullfilled() was for that promise? Is there an id I can display on the console?

**Comment by petkaantonov** [comment]
sounds like you have something like:

```js
this.thePromise = something().then(function() {
    if (this.thePromise.isFulfilled()) {
         // ...
    }
});
```

`thePromise` is not fulfilled because its fate depends on what happens inside the function. If error was thrown there it would be rejected for instance.

**Comment by c0debreaker** [comment]
Yes like that. Is it wrong?

**Comment by bergus** [comment]
@c0debreaker 
> Everyone in our team thinks that inside every `.then()` block, promise has been fulfilled

That is true. Your problem is that you have

    b = a.then(…)

where inside the `then` callback, `a` *is* fulfilled but `b` is not (yet).

**Comment by c0debreaker** [comment]
Thanks for that explanation. What is the proper solution?

**Comment by bergus** [comment]
@c0debreaker 
> What is the proper solution?
Just omit the condition - as established, you already know that `a` is fulfilled so you don't need to test for it.
If that's not what you want, please [ask a question at StackOverflow](http://stackoverflow.com/questions/ask) about the problem you have.

**Comment by c0debreaker** [comment]
I'm good. Thanks!
