### ISSUE TITLE
[feature-request] Flow-type API

### ISSUE THREAD

**Issue by guigrpa** [petkaantonov/bluebird#1265]
1) What version of bluebird is the issue happening on?
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
3) Did this issue happen with earlier version of bluebird?
**N/A (feature request)**

Sorry if this has been requested elsewhere, but I couldn't find an issue. [Flow-typed](https://github.com/flowtype/flow-typed) has recently published a [Flow API for Bluebird](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/bluebird_v3.x.x/flow_v0.32.x-/bluebird_v3.x.x.js) that is really useful.

However, it would be beneficial that there is an _official_ Flow API, and that it is included in the Bluebird library itself. We would avoid discrepancies, delays when the API changes, **plus some apps would not require an additional tool (_flow-typed_) for a single library**.

In addition, at least from my experience I have found it very useful to have a single file where the whole API is defined (as a quick reference, or cheat sheet...).

The first version of this _official_ Flow API may be based on the one published in flow-typed, so I guess not much effort would be required. Of course, I'm only a Bluebird user, so I ignore whether that API is 100% correct.

**Comment by benjamingr** [comment]
I think our consensus at the moment is to support flow and TypeScript from the outside and not internally as none of us use either frequently enough to be good maintainers of such typings. Major versions with API breakages typically have a fairly long period of beta where third-parties can update typings.

**Comment by guigrpa** [comment]
Understood. In any case, keep up the good work!
