### ISSUE TITLE
Promise.all fails with error: AssertionError: handle != self._handle

### ISSUE THREAD

**Issue by pinalbhatt** [petkaantonov/bluebird#1266]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
    BlueBird version: 3.4.6
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
      NodeJS: 6.5, 6.8, 6.8.1, 6.9
3) Did this issue happen with earlier version of bluebird?
     Its new implementation so not checked previous versions.

Promise.all(tasks) fails with error
`"trace":[{"column":3,"file":"net.js","function":"TLSWrap.onread","line":533,"method":"onread","native":false}],
"stack":["AssertionError: handle != self._handle","   
 at TLSWrap.onread (net.js:533:3)"],
"level":"error",
"message":"uncaughtException: handle != self._handle","timestamp":"2016-10-19T20:32:59.652Z"
`
`AssertionError: handle != self._handle
Expected :true
Actual   :false
<Click to see difference>

at TLSWrap.onread (net.js:533:3)
`

If tasks contains only one promise it works fine but as we add more promises in task i get above error.

**Comment by benjamingr** [comment]
Thanks for the report. This error is not bluebird related.
