### ISSUE TITLE
Can't execute something after bluebird.map

### ISSUE THREAD

**Issue by rightaway** [petkaantonov/bluebird#1268]
```
  bluebird.map([1,2,3,4,5], somePromise, { concurrency: 3 }).then(() => console.log('done'))
```
`done` is printed before the promises get executed, should it not be printed after? How to execute some code when all promises have completed?

**Comment by benjamingr** [comment]
What's `somePromise`? You're supposed to be passing a _function_ to `map` not a promise.

**Comment by rightaway** [comment]
I've changed it but this code doesn't seem to work. `getPromise` returns a promise that has its own `then` and `catch`. And the `run` function `await`s on bluebird.map to complete.

But often bluebird.map freezes after going through all the items and the program doesn't terminate even though all 1000 items from the array have been done (total of 1000 'requested' and 'failed' printed to console).

```
function getPromise() {
  return requestPromise(url)
   .then(() => console.log('requested'))
   .catch(() => console.log('failed'))
}

async function run() {
  const array = [1, ........, 1000]
  await bluebird.map(array, getPromise, { concurrency: 500 })
  console.log('done')
}
```

**Comment by benjamingr** [comment]
I cannot reproduce this.

**Comment by rightaway** [comment]
The problem was actually caused by the requests not having a timeout set, which would sometimes cause it to hang. Thanks for taking a look at this issue.
