### ISSUE TITLE
Scoped prototypes nonfunctional

### ISSUE THREAD

**Issue by baffo32** [petkaantonov/bluebird#1269]
version: bluebird 3.4.6
platform: node.js 4.5.0
happens with earlier version: unknown

The 'scoped prototypes' use documented at http://bluebirdjs.com/docs/features.html#scoped-prototypes does not work.  For one thing, there is no "bluebird/js/main/" folder, and when I change it for the existing folder "bluebird/js/release/", the code still does not work and the same error is thrown:

```
     TypeError: the promise constructor cannot be invoked directly

    See http://goo.gl/MqrFmX

      at check (node_modules/bluebird/js/release/promise.js:65:15)
      at Promise (node_modules/bluebird/js/release/promise.js:76:9)
```

**Comment by benjamingr** [comment]
You still need to `new` the promises you get from your own prototype.
