### ISSUE TITLE
Detailed information and longstacktrace is not shown even though enabled.

### ISSUE THREAD

**Issue by bonesoul** [petkaantonov/bluebird#1270]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.4.6

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
7.0.0

```
// globaly set promise library as bluebird.
global.Promise = require('bluebird');

// configure bluebird.
Promise.config({
	warnings: true, // note, run node with --trace-warnings to see full stack traces for warnings
	longStackTraces: true
});

```

and getting mass of of these warnings when i started my project;

```
(node:18396) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
```

Why i don't see the exact line that causes the issue and long stack traces?

**Comment by benjamingr** [comment]
These are warnings and not unhandled rejections. If you want to get a stack trace from those run node with `--trace-warnings`.

**Comment by bonesoul** [comment]
I'm already doing so with --trace-warnings but no luck.
