### ISSUE TITLE
Feature: get current expanded stack trace

### ISSUE THREAD

**Issue by baffo32** [petkaantonov/bluebird#1271]
It would be great to be able to get the current expanded stack trace in some way.  Currently one needs to create a dummy promise to do this.

**Comment by benjamingr** [comment]
This is similar to how you interact with regular errors. I guess that if errors had a way to do this we could have hooked on it.

**Comment by baffo32** [comment]
Errors do have a way to do this; it is `error.stack`.  But there is no `promise.stack`, which would be very convenient.  My implementation using current API is at https://github.com/OpenBCI/OpenBCI_NodeJS/blob/master/test/bluebirdChecks.js#L42 -- but it is verbose, slow, and obscure.  The number of promises created by the application is doubled.

**Comment by spion** [comment]
Can you tell us something about your use case?

**Comment by baffo32** [comment]
There were some issues with the code caused by runaway promises that were still doing work after processing had completed.  The main purpose of the module is to create a `getPendingPromises` function which returns promises that have not yet resolved.  The use of a stack trace is to identify where the promises were created so that the issue may be fixed without guesswork.
