### ISSUE TITLE
Long stack traces in Microsoft Edge

### ISSUE THREAD

**Issue by thcgit** [petkaantonov/bluebird#1274]
Long stack traces don't seem to work in the current version of Edge.

captureStackTrace returns null because the stack detection doesn't find something that it recognises.

Possibly it used to work at one point, as according to https://connect.microsoft.com/IE/feedbackdetail/view/1192551/ie-does-not-add-stack-trace-to-error-object, the Error object used to behave like IE and didn't record the stack on construction.

**Comment by benjamingr** [comment]
This is a known limitation. PR welcome.
