### ISSUE TITLE
Add Symbol.toStringTag to promise instance

### ISSUE THREAD

**Issue by Strate** [petkaantonov/bluebird#1277]
As for now, promise created by Bluebird does not have `Symbol.toStringTag`, but have `toString` method which returns `"[object Promise]"` string. Having `[Symbol.toStringTag]: "Promise"` make `Object.prototype.toString.call(promise)` to return  same string: `"[object Promise]"` (as for now it will return `"[object Object]"` string.
So, I suggest to add `Symbol.toStringTag` property to bluebird's promise prototype.

**Comment by benjamingr** [comment]
I don't know how I feel about this. How would users be able to tell native promises apart?

**Comment by ronzeidman** [comment]
import * as Bluebird from 'bluebird';
console.log(Promise.toString().includes('[native code]')); //true
global.Promise = Bluebird;
console.log(Promise.toString().includes('[native code]')); //false

**Comment by torkelrogstad** [comment]
The fact that Bluebird promises and native ES6 promises are incompatible makes it very difficult to work with packages like Sequelize in TypeScript. Please consider implementing this change.

**Comment by benjamingr** [comment]
I don't understand why you think bluebird is incompatible with native promises in TypeScript - I've been happily using them together for quite a while. That fact is unrelated to how toStringTag behaves.

**Comment by spion** [comment]
They cannot be passed where a native promise is required as an argument due to the missing toStringTag symbol.

**Comment by spion** [comment]
Theoretically, the .d.ts file could contain it -- however, DT maintainers are reluctant to add something that does not exist (and with good reason):

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11027#issuecomment-250976787

**Comment by spion** [comment]
We should definitely do this, the only questions are:

* can we can make it so that `.toString()` returns the same thing it did before
* is anyone using the presence of [Symbol.toStringTag] to tell native from BB promises apart.
