### ISSUE TITLE
longStackTraces lose the context for SyntaxErrors

### ISSUE THREAD

**Issue by broofa** [petkaantonov/bluebird#1280]
1) What version of bluebird is the issue happening on? **v3.4.6**

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)  **MacOSX, node v6.9.1**

It appears Bluebird loses the file/lineno info on longStackTraces when a SyntaxError is raised inside a promise.  For example ...

With `longStackTraces: false`, Syntax Errors [correctly] appears like this:

```
boss/db/Command.js:114
  }
  ^
  SyntaxError: missing ) after argument list
  at Object.exports.runInThisContext (vm.js:76:16)
  at Module._compile (module.js:542:28)
  at Object.Module._extensions..js (module.js:579:10)
(etc...)
```

With `longStackTraces: true`, that same error appears like this:
```
SyntaxError: missing ) after argument list
  at Object.exports.runInThisContext (vm.js:76:16)
  at Module._compile (module.js:542:28)
  at Object.Module._extensions..js (module.js:579:10)```

**Note**: the first 3 lines - the lines with the context for the SyntaxError - are missing.   As you can imagine, this makes diagnosing syntax errors difficult.  I find myself having to restart my app with the appropriate longStackTraces setting, depending on the type of error. :-/

**Comment by broofa** [comment]
Any ETA on when this might be merged/published?  This is a non-trivial pain point for me - any time I have a syntax error in my code I have to disable long stack traces to determine the location.  :-(

**Comment by petkaantonov** [comment]
I'll try to get release today

**Comment by SimonSchick** [comment]
@petkaantonov can this be closed with https://github.com/petkaantonov/bluebird/releases/tag/v3.4.7 ?

**Comment by benjamingr** [comment]
Yes.
