### ISSUE TITLE
unnecessary "Promise Not Return Warn" when i have multiple `await` statments.

### ISSUE THREAD

**Issue by liuyanjie** [petkaantonov/bluebird#1289]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

"Promise Not Return Warn" when i have multiple `await` statments.

`async/await` feature comes from `babel`

example:
```js
async function loading() {
  let result1 = await loadingData1();
  let result2 = await loadingData2();
  let result3 = await loadingData3();
}
```
console:
```
Warning: a promise was created in a handler but was not returned from it
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
Warning: a promise was created in a handler but was not returned from it
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node.js 6.9.1

3) Did this issue happen with earlier version of bluebird?

No. version is 3.3.1

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

**Comment by benjamingr** [comment]
Show us `loadData1...3`

**Comment by liuyanjie** [comment]
I try to reproduce this situation with simple code, but failed.

I have fixed this problem when update `bluebird` to `3.4.6`, The situation is no longer appeared.

Thank You for reply.
