### ISSUE TITLE
`npm install {github repo}` is not working

### ISSUE THREAD

**Issue by broofa** [petkaantonov/bluebird#1290]
I'd like to use a version of bluebird that has the longStackTrace fix mentioned in the issue I filed previously.  To that end, I've forked this repo (as broofa/bluebird), and am trying to install it using NPM's github reference feature.  I.e. I do `npm install broofa/bluebird`.  Unfortunately this results in a node_modules/bluebird directory with the following contents:

```bash
kieffer@Roberts-MacBook-Pro$ ls -Fl node_modules/bluebird/
total 40
-rw-r--r--  1 kieffer  staff  1086 Nov 30 14:58 LICENSE
-rw-r--r--  1 kieffer  staff  2711 Nov 30 14:58 README.md
-rw-r--r--  1 kieffer  staff    87 Nov 30 14:58 changelog.md
-rw-r--r--  1 kieffer  staff  6936 Nov 30 14:58 package.json
```

Note the lack of any actual executable code. :-(

`npm install petkaantonov/bluebird` has the same issue.

Any suggested workarounds for how I might get fixed version of bluebird into the project I'm working on (in a team of developers, so need to be able to share npm package.json configuration).

**Comment by gswalden** [comment]
You can see in the [package.json](https://github.com/petkaantonov/bluebird/blob/master/package.json#L71) that the only files included when installing are in the `js/` directory, which is generated by the script `npm run prepublish`. If you run that script in your fork and commit the result, those files will be there.

**Comment by benjamingr** [comment]
What @gswalden says, also more generally for all other npm packages too.
