### ISSUE TITLE
No Stacktrace/ Line number on warning, Bluebird with Mongoose

### ISSUE THREAD

**Issue by 360disrupt** [petkaantonov/bluebird#1297]
`node v7.2`
`"bluebird": "^3.4.6"`

I found this for FE-Apps
https://github.com/petkaantonov/bluebird/issues/846

But I don't get any information from the warning on the backend side. I use bluebird for my `mongoose` promises. I just have callback functions which return from mongoose.

The only thing node shows me is:
`Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw`

## Code
```
chalk = require('chalk')
inspect = require('util').inspect

Promise = require("bluebird")
Promise.config({
  longStackTraces: true
  warnings: true
  monitoring: true
})
mongoose = require('mongoose')
mongoose.Promise = Promise
mongoose.set('debug', true)

process.on 'warning', (warning) ->
  console.log(warning.name) #warning
  console.log(warning.message) #a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
  console.log(warning.stack)# Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
  throw warning
  return
```

**Comment by benjamingr** [comment]
To get warning traces run node with `--trace-warnings`.
