### ISSUE TITLE
Make Promise.method() compatible with Q.promised()?

### ISSUE THREAD

**Issue by arikon** [petkaantonov/bluebird#1300]
Is there a point to not to do `Promise.method()` compatible with `Q.promised()` in a way how the arguments to the promised function/method are handled?

`Promise.method()` does not resolve promises as function arguments to their values, but `Q.promised()` does:
https://github.com/kriskowal/q/blob/v1/q.js#L1371-L1393

**Comment by bergus** [comment]
This is a pretty rare requirement. It might lead to surprises when the function call doesn't immediately execute the body.
Instead, Bluebird encourages the *caller* of a function to use `Promise.join`. It shouldn't be the responsibility of the callee to wait for argument promises.

**Comment by arikon** [comment]
The code with `Q.promised()` becomes cleaner and simpler when with `Promise.method()`.

**Comment by benjamingr** [comment]
This would likely slow `Promise.method` down if called repeatedly and the use case is rare - it's very easy to build in userland too (I think there's even an example in the docs somewhere). 

Another -1 for me for putting this in core.
