### ISSUE TITLE
Promise still go to the next chain after I return res.end()

### ISSUE THREAD

**Issue by Eivlys** [petkaantonov/bluebird#1301]
Hi,

I'm using bluebird in node with express ,when I return res.end(),Promise still goes to the next chain,here's my code:
`Promise.resolve(operate).then(function(data){
     if (!!data && data.length !=0) {
            log.info('success');
            return true;
        }else {
            log.warn('fail');
            return res.end();
        }
}).then(function(data){
    if(data) {
          log.info('done');
          return res.end();
    }else {
          log.warn('fail');
          return res.end();
    }
})`

And I got 2 'fail' in the log if it's failed,how can i make it stop if i got fail in the first time?Thank you!

bluebird version:~2.10.2
node: 4.3.1
express:~4.2.0

**Comment by benjamingr** [comment]
Please ask support question in the correct channels - for example StackOverflow

**Comment by Eivlys** [comment]
Ok, thanks
