### ISSUE TITLE
Implement Bluebird API on top of native promises in separate library

### ISSUE THREAD

**Issue by ireuhfhjk1** [petkaantonov/bluebird#1302]
When performance doesn't matter, but bundle size does matter (which is the case for many front-end applications), it becomes very tempting to drop Bluebird in favor of native promises.  This is a choice that more and more developers will face as the market share of promise-lacking browsers dwindles.

But since native promises are not a drop-in replacement for Bluebird, it is only a matter of time until someone implements Bluebird's API on top of native promises.  There are advantages of that being done as part of bluebird's codebase: 1) it will be done well, and 2) it will be easier to preserve API equivalence.

**Comment by benjamingr** [comment]
It cannot be done "well" without copying half the library over.

**Comment by ireuhfhjk1** [comment]
@benjamingr 
I am trying to understand why that is so.  If I list my thoughts, could you tell me where I am wrong?

1. There is a lot of overlap between the functionality of Bluebird and the functionality of native promises

2. Whenever the functionality overlaps, implementing Bluebird's API on top of native promises would be very easy

3. The things that Bluebird can do but native promises cannot do are disposers, cancellation, and generators.  Only these would have to be reimplemented.

Or perhaps there is something about "done well" that I do not understand?

**Comment by benjamingr** [comment]
Bluebird is based on a `PromiseArray` abstraction and fast promisification through closure avoidance by having its own `_` prefixed "secret" methods you can call.

Doing what you suggest would end up re-implementing bluebird.

**Comment by spion** [comment]
@benjamingr I think @ireuhfhjk1 means providing an API, not speed. Thats doable, but a large undertaking.

**Comment by ireuhfhjk1** [comment]
@spion Yes, I'll have a stab at it.  Do you expect passing Bluebird's existing tests to be a good indicator for guaranteed drop-in-ness?

**Comment by spion** [comment]
Yes, I think they should be good enough for the most part. @petkaantonov ?
