### ISSUE TITLE
native vs. this - question

### ISSUE THREAD

**Issue by ORESoftware** [petkaantonov/bluebird#1309]
Hey all, native promises apparently tap into the "microtask queue" in V8, whatever that means. Does bluebird do similarly, and if not, does this disparity get mitigated somehow? Just curious about that, thanks.

This has probably been touched on here and there, I will dig for discussions on it.

**Comment by ORESoftware** [comment]
not seeing too much
https://github.com/petkaantonov/bluebird/issues?utf8=%E2%9C%93&q=microtask

so not ashamed to ask the question here! :)

**Comment by benjamingr** [comment]
https://github.com/petkaantonov/bluebird/blob/master/src/async.js
https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js
https://github.com/petkaantonov/bluebird/blob/master/src/queue.js

**Comment by ORESoftware** [comment]
@benjamingr always a pleasure :) would you mind elaborating, I am checking out the source, and it seems like Bluebird does use the node.js asynchronous tools, but I am wondering about any "bigger" plans to more closely mirror the native promise implementation, whilst also providing important utility functionality that the native library does not provide.

**Comment by spion** [comment]
Bluebird has its own microtask queue. Any tasks scheduled in the middle of another task get pushed to the queue while its executing, and get executed immediately after, synchronously. If the queue is empty when a task is scheduled, one of the schedulers in `schedule.js` is used to schedule an action (setImmediate, nextTick or MutationObserver, depending on platform)

**Comment by ORESoftware** [comment]
@spion thanks for the info - I simply can't tell if this means Bluebird will play nicely with other libs that also use the/a microtask queue, TBH, I am guessing that it won't.

Would it really be that far out of the question to change Bluebird to monkeypatch the native implementation and add the utility methods? Sounds like that's out of the question.

**Comment by spion** [comment]
@ORESoftware what makes you think that bluebird wont play nicely with other libraries? What other libraries do you mean? What precisely is your concern?

**Comment by ORESoftware** [comment]
@spion thanks, I will experiment, just heard about some bugs that had to do with timing etc

**Comment by benjamingr** [comment]
Bluebird will play nice with NodeJS promises and the microtask queue, both me and @petkaantonov are Node core collaborators and wrote PRs that have to do with promises in Node.
