### ISSUE TITLE
Allow custom awaiters

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#131]
Currently `Promise.coroutine` generators can yield on two things:
- Promises. Waiting for the promises to resolve.
- Arrays ( `yield arr` acting similarly to `Promise.all(arr` ) as seen [here](https://github.com/petkaantonov/bluebird/blob/master/src/promise_spawn.js#L49). 

It would be beneficial to allow the API to be extended from the outside without modifying it. It would allow configurability with little cost. @petkaantonov discussed exposing the interface which would solve this issue. 

@spion has suggested `.registerAwaiter( predicate | type , function that returns awaiter)` which I believe is interesting. 

This is similar to C#'s `GetAwaiter` method that allows `await`ing arbitrary things. 

Also see - related discussion on https://github.com/petkaantonov/bluebird/issues/128 . 

Pros: 
- Interesting features. 
- More consistent and configurable API.
- Richer API. 

Cons:
- Configuration (though end users who are uninterested are not exposed). 
- More logic and features in the library.

**Comment by zj8487** [comment]
Is it possible to yield more things in Promise.coroutine:
* thunk

* GeneratorFunction

* Generator

the things above will make Promise.coroutine powerful.


things can yield in co as follow:

```js
function toPromise(obj) {
  if (!obj) return obj;
  if (isPromise(obj)) return obj;
  if (isGeneratorFunction(obj) || isGenerator(obj)) return co.call(this, obj);
  if ('function' == typeof obj) return thunkToPromise.call(this, obj);
  if (Array.isArray(obj)) return arrayToPromise.call(this, obj);
  if (isObject(obj)) return objectToPromise.call(this, obj);
  return obj;
}
```

**Comment by petkaantonov** [comment]
you can yield anything just use addYieldHandler see docs

**Comment by benjamingr** [comment]
@zj8487 you can trivially add this in bluebird but we don't want to support this sort of thing because it is very error prone. Not to mention the implications on performance.

**Comment by zj8487** [comment]
thanks a lot

**Comment by bergus** [comment]
@zj8487 I don't think yielding GeneratorFunctions or Generators/Iterators makes much sense. You just should do

    yield* generatorFunction();

instead of `yield generatorFunction`. And when you yield an iterator, Bluebird doesn't know whether it's a promise-yielding coroutine iterator or a value-yielding iterator that would like to be handled like an array (+`Promise.all`). You'd better be explicit in your own code about what to yield, instead of letting Bluebird guess what you want.
