### ISSUE TITLE
Function not getting called after promisifying

### ISSUE THREAD

**Issue by RoopamKothari** [petkaantonov/bluebird#1310]
I am trying to promisify cloudant function but some how they are not getting called. Here is the code snippet: 

dbGet(dbName) just doesn't get called. Can anyone help why the call doesn't enter in dbGet function. Is it a bug when we promisify cloudant.db.get??

var Cloudant = require('cloudant');

var Promise = require('bluebird');

module.exports = {

		getDbInstance : getDbInstance

}

var cloudant;

var dbGet, dbCreate;

function getDbInstance(dbName, cloudantUrl)

{

	return new Promise(function(resolve, reject){

		try{

		

		cloudant = Cloudant(cloudantUrl);

//		console.log("cloudant ", cloudant);

		dbGet = Promise.promisify(cloudant.db.get);

		dbCreate = Promise.promisify(cloudant.db.create);

                

                 dbGet(dbName)

		.then(function(resp){

			console.log('db exists');

		}, function(error){

			console.log('db does not exists. Creating db ...');

			return dbCreate(dbName);

		})

		.then(function(){

			var dbInstance = cloudant.db.use(dbName);

			console.log("returning db instance..");

			return resolve({statusCode: constants.SUCCESS, body: dbInstance});

		})

		.catch(function(error){

				console.log('INSIDE INNER CATCH');

				console.log(error);

				return reject({statusCode: constants.INTERNAL_SERVER_ERROR, body: error});

			});

               }

		catch(error){

			console.log('INSIDE CATCH');

			console.log(error);

			return reject({statusCode: constants.INTERNAL_SERVER_ERROR, body: error});

		}

});

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?    v3.4.6

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32) v7.2.1 Node

3) Did this issue happen with earlier version of bluebird? yes

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

**Comment by RoopamKothari** [comment]
I am working on high priority project. Request you to please help asap :)

**Comment by ORESoftware** [comment]
For a high priority project, I would personally not elect to use the promisification aspects of this library

**Comment by benjamingr** [comment]
@RebootJeff you have an error in your promisification code - please ask support questions on StackOverflow.

**Comment by RebootJeff** [comment]
@RoopamKothari - I think @benjamingr meant to tag you instead of me in [his previous comment](https://github.com/petkaantonov/bluebird/issues/1310#issuecomment-269101710)

**Comment by benjamingr** [comment]
Sorry @RebootJeff my bad!
