### ISSUE TITLE
Promise.coroutine: yielding a function should not call the function

### ISSUE THREAD

**Issue by giltayar** [petkaantonov/bluebird#1314]
1) What version of bluebird is the issue happening on?
  3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
  Tested on Node 7, but I'm guessing it's true for all platforms

3) Did this issue happen with earlier version of bluebird?
  Probably.

Given:
```js
(Promise.coroutine(function*() {
  yield function () { console.log('hi'); };
}))();
```
You would not expect "hi" to be written to log, because we're yielding a _value_ (which is a function), and not calling the function.

But it does print "hi". And then returns a rejected error.

I have prepared a pull-request that contains a fix, which I will submit in a few minutes.

**Comment by benjamingr** [comment]
Fix LGTM. @petkaantonov ptal.

**Comment by petkaantonov** [comment]
`+ ""` is sufficient

**Comment by benjamingr** [comment]
Or `String(value)`

**Comment by giltayar** [comment]
I chose @benjamingr's change - it seems more explicit to me. Thanks for pointing the (I hope slightly) awkward code out.
