### ISSUE TITLE
delay and timeout should use scheduler

### ISSUE THREAD

**Issue by marcfallows** [petkaantonov/bluebird#1321]
1) What version of bluebird is the issue happening on?
3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Chrome 55, but true of all platforms.

3) Did this issue happen with earlier version of bluebird?
Yes

If I use `Promise.setScheduler` to define a custom scheduler, I would expect `Promise.delay` and `Promise.timeout` to use this scheduler. Instead, it continues to use the native `window.setTimeout`.

**Comment by petkaantonov** [comment]
scheduler is something that determines how to flush the promise callback queue, it has nothing to do with delay and timeout
