### ISSUE TITLE
Taboola ads on Bluebird's Website

### ISSUE THREAD

**Issue by abdulhannanali** [petkaantonov/bluebird#1322]
Disqus is filling full bluebird pages with advertisements. If this is something that isn't activated by the site owners, then it's quite bad and damages the user experience. As, it seriously leads to clicks just because of the size of ads relative to the content. 
Here's an image, inspecting the iframe it seems Disqus is adding these iframe. I am sorry if this is distracting for people here.
![download](https://cloud.githubusercontent.com/assets/8170969/22032872/191bb44e-dd08-11e6-8986-53ab924e7d9b.png)

**Comment by abdulhannanali** [comment]
I am sorry, seems like it's enabled by Owners themselves, should have read this https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/how_do_i_remove_the_ads/

**Comment by abdulhannanali** [comment]
Please avoid

**Comment by petkaantonov** [comment]
ads are again removed

they updated their ad system which came with default enabled...
