### ISSUE TITLE
Method for identifying Bluebird promises?

### ISSUE THREAD

**Issue by blesh** [petkaantonov/bluebird#1323]
Hi, I work on RxJS (https://github.com/reactivex/rxjs) and I have a keen interest in interop with other async types.

Currently, RxJS's `Observable.from` and MANY other operators accept not only observables but promises as well as a form of ergonomics. I think it would be great if we (Rx) could detect a Bluebird promise and account for cancellation appropriately.

Here is a simple use case: A polling interface

```js
// do an ajax get once every second with some bluebird-based promise impl
// NOTE: `switchMap` wants to cancel any in-flight AJAX request that takes longer than
//       the polling peroid.
const subscription = Rx.Observable.interval(1000)
  .switchMap(() => getBluebirdBasedAjax())
  .subscribe(x => console.log(x))


// stop polling at an arbitrary time less than 50 seconds in the future
// NOTE: We want to cancel the current request when this happens.
setTimeout(() => subscription.unsubscribe(), Math.random() * 50000)
```

Since bluebird supports cancellation, it would be great if we could detect a bluebird promise in some simple way and use that when converting from a promise within RxJS. Ideally this would be done in a way that could also be used by other promise libraries and promise-based APIs (perhaps like `fetch` in the future?)

**Comment by blesh** [comment]
FWIW: My gut tells me that we *could* just do a check for a `cancel` method after the check for thennability:  `(typeof x.then === 'function' && typeof x.cancel === 'function')`, but I'm not certain that's valid.

**Comment by blesh** [comment]
cc @jaffathecake do you know if `fetch` will have a congruent API to bluebird's? or will it be using tokens?

**Comment by blesh** [comment]
Damn, I meant @jakearchibald

**Comment by benjamingr** [comment]
This would be very nice, I usually do it manually. You can check several things:

 - `Promise.prototype.cancel` seems like the most obvious to probe for cancellation (bluebird has a build without it).
 - `Promise.prototype._cancel` is also fine if you want to detect bluebird in particular.
 - `Promise.version` detects bluebird.


Fetch is going to support ad-hoc cancellation by the way (as you saw [here](https://github.com/whatwg/fetch/issues/447#issuecomment-273633060))

**Comment by jakearchibald** [comment]
@blesh here's the current thinking for fetch https://github.com/whatwg/fetch/issues/447. Less likely to be tokens, and more like a controller object.
