### ISSUE TITLE
Unhandled rejection error.

### ISSUE THREAD

**Issue by ivands** [petkaantonov/bluebird#1328]
1) What version of bluebird is the issue happening on?
v3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Chrome 55.0.2883.95

3) Did this issue happen with earlier version of bluebird?
Don't know.

I have the following code. And it works as expected without throwing an unhandled rejection error.

```
p = new Promise (fulfill, reject) ->
  reject new Error 'some error'

p.catch (error) ->
  console.log 'error'

```

Now, in the second code example something weird is happening.
I'm getting an unhandled rejection error even tho the 'error' string is logged to the console.
Can someone explain to me why this is happening when im clearly handling the error.
This seems like a bug to me.

Wouldn't it be more sensible to call the catch callback or throw an unhandled rejection error.
But not both at the same time.

```
p = new Promise (fulfill, reject) ->
  reject new Error 'some error'

p.then ->
  console.log 'ok'

p.catch (error) ->
  console.log 'error'
```

**Comment by benjamingr** [comment]
You're forking the promise, in order to handle the error you need to handle the error both in the `.then` and in the original promise.

p   ---> p.then fork
|
\ ---> caught 

Someone can listen to `p.then` and not handle the error (what if the code `console.log "ok"` throws?)

**Comment by ivands** [comment]
So whats the method i need to call to listen for the 'done' event without forking the promise.

**Comment by benjamingr** [comment]
```js
p = new Promise (fulfill, reject) ->
  reject new Error 'some error'

p.then ->
  console.log 'ok'
.catch (error) ->
  console.log 'error'
```

Also, please ask support questions in the appropriate support channels :)

**Comment by ivands** [comment]
Ok thanks i will
