### ISSUE TITLE
Is this a valid way to use Promise.coroutine

### ISSUE THREAD

**Issue by dagda1** [petkaantonov/bluebird#1330]
Hi,

I am using loopback and they have model endpoints that are similar to express routes, I am using `Promise.coroutine` like this:

```
  Feedback.createFeedback = function(payload, next) {
    Promise.coroutine(function * () {
      try {
        const feedback = yield Feedback.create(payload);

        return next(null, feedback);
      } catch (err) {
        next(null, err)
      }
    })();
  };
```
For example the above would map to a `feedback/createFeedback` route.

I am using `Promise.coroutine` as a self executing function and it all seems to work as I would expect.

Is there a better way of using coroutines or is this a perfectly valid approach?

**Comment by benjamingr** [comment]
Please ask support questions on StackOverflow.
