### ISSUE TITLE
Why list of listeners resets silently?

### ISSUE THREAD

**Issue by avukmirovich** [petkaantonov/bluebird#1333]
Hi all!

Bluebird 3.4.7
Node 6.9.2

Snippet from [here](https://github.com/petkaantonov/bluebird/blob/master/src/promise.js#L405)

```javascript
if (index >= MAX_LENGTH - CALLBACK_SIZE) {
        index = 0;
        this._setLength(0);
}
```

Can somebody explain me, why list of listeners resets to 0 without any warnings or errors?

**Comment by benjamingr** [comment]
See discussion in https://github.com/petkaantonov/bluebird/issues/36 and comments in  https://github.com/petkaantonov/bluebird/commit/954565108e708ad1ab2a8b9b00069890bc529969

**Comment by floatdrop** [comment]
@benjamingr hi, thanks for quick response. But discussion and comments are not answering question – why length is cut without even a warning? I understand, that this is a rare case - when you are attaching 65535 listeners to a promise, but no warning even in debug mode?

**Comment by sindresorhus** [comment]
ping @benjamingr
