### ISSUE TITLE
Expected identifier - IE8 

### ISSUE THREAD

**Issue by codeuniquely** [petkaantonov/bluebird#1336]
I get the following error message when running Bluebird on IE8 with version 3.4.7

Specifically trying to execute the following code:
```
Promise.prototype.break=Promise.prototype.cancel=function(){
   ... 
}
```

Webpage error details
```
Promise.prototype.break = 
                 ^
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Timestamp: Wed, 8 Feb 2017 11:36:58 UTC

Message: Expected identifier
Line: 3
Char: 15341
Code: 0
```

I believe that for this to work on IE8 then the line would have to be changed to 
```
Promise.prototype['break'] = 
```

**Comment by codeuniquely** [comment]
Looking through the source code the line is correctly written - this must be a BabelJS issue - closing

**Comment by benjamingr** [comment]
probably a `screwIE` option flag in uglifyjs
