### ISSUE TITLE
Bluebird.props for empty Map returns an Object

### ISSUE THREAD

**Issue by alanhoff** [petkaantonov/bluebird#1338]
1) What version of bluebird is the issue happening on?
v3.4.7

2) What platform and version?
v7.5.0
`Darwin Alans-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64`

3) Did this issue happen with earlier version of bluebird?
Yes

`Bluebird.props` should return an empty ES6 `Map` instead of a plain object `{}` when called with an empty `Map`:

<img width="584" alt="screenshot 2017-02-13 15 10 54" src="https://cloud.githubusercontent.com/assets/1044223/22907619/d3320e68-f1fe-11e6-82c0-4872f74e961d.png">

**Comment by benjamingr** [comment]
I'm not sure I agree. `Promise.props` is just for returning multiple named values and passing it a map as configuration is a nice bonus - but Bluebird can't be expected to deal with every case.

**Comment by alanhoff** [comment]
@benjamingr I don't think it's about dealing with every case (empty Map only?) but not being predictable is what hurts the most. I'm ok with it if we add it to the docs:

```
The promise's fulfilment value is an object or a Map with fulfilment values at respective keys to the original object or a Map unless it's an empty Map, in this case it will return an empty object.
```

Don't you think it seems highly inconvenient? The resolved value depends on the number of items inside a Map

**Comment by bsiddiqui** [comment]
@benjamingr seems like odd behavior that `Promise.props` called with a `Map` sometimes returns a `Map` and sometimes returns an `Object`. 

You're totally right that passing it a map as a configuration is a nice bonus but feels like if Bluebird is going to include that functionality it should be consistent and predictable.

**Comment by spion** [comment]
👍 different return value types are strange
