### ISSUE TITLE
TimeoutError causes promise to be cancelled, not rejected

### ISSUE THREAD

**Issue by bpytlik** [petkaantonov/bluebird#1339]
1) What version of bluebird is the issue happening on?
3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 0.12

3) Did this issue happen with earlier version of bluebird?
Unknown. It couldn't happen in 2.x, I've not tried earlier 3.x versions.

Here's set of commands I ran at coffee's interactive prompt:
```
coffee> Promise = require("bluebird")
...
coffee> Promise.config({cancellation: true})
...
coffee> p = new Promise((() ->), (() ->))
...
coffee> p.isCancelled()
false
coffee> p.timeout(100)
<timeout fires>
coffee> p.isCancelled()
true
coffee> p.isRejected()
false
```

Note that nowhere in the documentation of timeout does it mention that the promise will be cancelled.  It explicitly says the promise is rejected, but that appears not to be the case, according to inspection.

I hit this problem originally because I had code that looked like this (and worked as expected in bluebird 2.x):
```
p = <create promise>
p.timeout(500).catch(Promise.TimeoutError, () ->
    <do some stuff>
    p.timeout(1000)
)
```

The second p.timeout was failing w/ a `CancellationError("late cancellation observer")` failure, which confused me to no end because I wasn't explicitly canceling the promise anywhere. It's also very strange that the promise isn't considered rejected, even though it triggered a catch block.

I'm definitely not an expert on the bluebird source code, but this bit of code looks like it could be the source of my confusion (from src/timers.js):
```
Promise.prototype.timeout = function (ms, message) {
...
    if (debug.cancellation()) {
        parent = this.then();
        ret = parent._then(successClear, failureClear,
                            undefined, handleWrapper, undefined);
        ret._setOnCancel(handleWrapper);
...
};
```

**Comment by petkaantonov** [comment]
`p` is the promise's parent, the promise itself is not cancelled but rejected like the docs say

in 3.0.0 the additional timeout should be done synchronously:

```js
p = <create promise>
var oneSecond = p.timeout(1000);
p.timeout(500).catch(Promise.TimeoutError, () ->
    <do some stuff>
    oneSecond.then(..., ....)
)
```
