### ISSUE TITLE
Implement Promise.series

### ISSUE THREAD

**Issue by epoberezkin** [petkaantonov/bluebird#134]
When you have the list of values to be passed to the same function sequentially, so that the next call is only made only when the promise returned by the previous call is resolved, you either have to "manually" chain promises or use Promise.reduce, which both looks a bit ugly and also not so obvious.

It could be nice to have something like this:
```
Promise.series = function (arr, iteratorAsync) {
    return Promise.reduce(arr, function(memo, item) {
        return iteratorAsync(item);
    }, 0);
}
```

**Comment by MaffooBristol** [comment]
I'm still confused about all this. I assumed there would be an easy way in the API to implement sequential resolutions like in [async](https://github.com/caolan/async), where it would work something like this:

```javascript
Promise.series([
  // Direct function call...
  function (resolve, reject) {
    setTimeout(function () {
      console.log('One');
      resolve();
    }, 1000);
  },
  function () {
    // ... or by returning a new promise, could be a function ref
    return new Promise(function (resolve, reject) {
      setTimeout(function () {
        console.log('Two');
        resolve();
      }, 1000);
    });
  }
]).done(function () {
  doSomething();
});
```

Basically exactly the same as `.all()` but sync not async.

I know it can be done with a series of `.then()` methods but it seems cumbersome, unless I'm missing something?

**Comment by benjamingr** [comment]
@MaffooBristol  probably you're missing `Promise.each` although your example is missing the point of promises - you should always promisify at the lowest level possible.

**Comment by MaffooBristol** [comment]
I deleted my comment when I glanced about 2cm up and saw that that is what `.each()` does, but kudos for a lightning fast reply!

And I do have the majority of my promises at a low level but there's an instance where I want to use it just to control initialisation events (in Marionette) that include both promises and non-promises, so to be able to combine it all in one whilst maybe sacrificing some not-exactly-what-they're-made-for promises seemed a good idea!

**Comment by adambuczynski** [comment]
The only gripe I have with `reduce` is the added verbosity due to the introduction of the accumulator and initial value parameters, e.g.:

```js
Promise.reduce(operations, (i, [query, update]) => {
  return Model.update(query, update);
}, 0);
```

Versus what a cleaner `series` method could be:

```js
Promise.series(operations, ([query, update]) => {
  return Model.update(query, update);
});
```

This avoids having to accept the accumulator as a first parameter in the reducer function and makes the api behave the same like for example the `map` function, where the item from the array is passed as the first parameter.

**Comment by benjamingr** [comment]
This is what Promise.each does

**Comment by adambuczynski** [comment]
Ah thanks 👍

**Comment by andyhu** [comment]
Anyone knows why the following code takes around 1 second to execute? I expected it to take 3 seconds though:

```js
const { each, delay } = require('bluebird');

console.time('promise');
each(
  [delay(1000), delay(1000), delay(1000)],
  () => console.log(new Date)
).then(() => console.timeEnd('promise'))
```

**Comment by CodeMedic42** [comment]
Here is something I needed. I did not see anything that did exactly what I wanted so I created this. If there is something like this already please let me know, Sometimes it is hard to find what you are looking for and I really hate recreating the wheel. If not then let me know what you think. I always appreciate feedback.

```
const Promise = require('bluebird');
const _ = require('lodash');

function series(iterable, inital) {
    return _.reduce(iterable, (accumulator, iteree) => {
        return accumulator.then((result) => {
            return iteree instanceof Function ? iteree(result) : iteree;
        });
    }, Promise.resolve(inital));
};

function X(result) {
    return result + 'X';
}

function Y(result) {
    return result + 'Y';
}

function Z(result) {
    return result + 'Z';
}

const seriesArray = [X, Y, Promise.method(Z)];

series(seriesArray, 'W').then((result) => {
    console.log(result); // => 'XYZ'
});

```

Lot's of room for improvement but can seriously clean code up and make it more readable I think.

What this does is take an array (can be improved to just take params). With this array it creates a promise chain where the output from the first goes into the next and then the output from that goes into the next. If there is a catch anywhere in the chain it should be bubbled out. It can be initialized with a starting value. The array can have promises, functions, or even static values/objects. They all just feed into the next item in the array. The first item in the array is the final output of the series. Obviously this can be used if you want your items to run in a particular order.

**Comment by benjamingr** [comment]
> Here is something I needed. I did not see anything that did exactly what I wanted so I created this. If there is something like this already please let me know,

Read the above comments, there is.

**Comment by CodeMedic42** [comment]
@benjamingr

I'm sorry sometimes I miss things. For example the particular comment you are referring to. I just re-read the above and did not find the comment in particular which you are referring to which solved the particular problem I was attempting to solve with my example.

I looked into the documentation for "each", "map", and "mapSeries" and they all return an array. If I am incorrect about this please let me know which one of these do not return an array so I can re-review the documentation. Either way I was not interested in an array but the result of the last item being ran in the series. This is also the result which I feel is correct when the word "series" is used.

However, the "reduce" function would do the trick but it is, and appropriately as well, designed to be generic when it comes to the use of the accumulator. But this requires a mutli-line blob of code to implement a function which can run particular artifacts in series one after the other passing the result through.
