### ISSUE TITLE
Promise cancellation fails if promise is resolved too quickly

### ISSUE THREAD

**Issue by abirmingham** [petkaantonov/bluebird#1342]
1) What version of bluebird is the issue happening on?
3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Version 56.0.2924.87 (64-bit) OSX 10.12.3

3) Did this issue happen with earlier version of bluebird?
Don't know

If a promise is created with either 1) Promise.resolve() or 2) new Promise((resolve) => resolve()), then that promise's callbacks will be executed even if promise.cancel() is immediately called.

See this fiddle for three cases, all of which I expect to console.log('pass'), but two of which console.log('fail'): https://jsfiddle.net/avzqb4d7/1/

**Comment by spion** [comment]
Once a promise's state has been decided, it can no longer be changed: if a promise is first fulfilled, then rejected, the fulfilment value is the only one that will be accepted.

Similarly, if a promise is cancelled after its fate is sealed, that will not have an effect.

**Comment by abirmingham** [comment]
@spion makes sense. With that in mind, case 2 should clearly fail. Case 3, however, should only fail if the function passed to the Promise constructor is called synchronously. I see now that it is. I also see that the 'new Promise' documentation notes this: "The resolver is called synchronously (the following is for documentation purposes and not idiomatic code):". So this isn't a documentation issue. Just user misunderstanding.

I would expect a warning when attempting to change the state of a promise after its fate is sealed. No warning is logged in the cases shown in the jsfiddle above. It appears that a warning is not logged if resolve() is followed by reject() either:
`
new Promise((resolve, reject) => {
    resolve();
    reject(new Error('no warning'));
}
`
