### ISSUE TITLE
new Bluebird((resolve, reject) => {}) in react-native gives "TypeError: Object is not a constructor"

### ISSUE THREAD

**Issue by pocesar** [petkaantonov/bluebird#1344]
1) What version of bluebird is the issue happening on? 3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32) react-native 0.41.2 on Android

3) Did this issue happen with earlier version of bluebird? Not sure

 when using 

```
import * as Bluebird from 'bluebird'

(new Bluebird(function(resolve, reject) {
}))
```

crashes with `Object is not a constructor (evaluating 'new Bluebird(function(resolve, reject){})')`. but if you do

```
import Bluebird from 'bluebird'

(new Bluebird(function(resolve, reject) {
}))
```

it works. this is a 'stock' react-native init. what is the difference between the two?

**Comment by benjamingr** [comment]
This is how imports work and depends on whether you import the default export or the module as a module. Use the second - this is unrelated to bluebird.
