### ISSUE TITLE
warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by dagda1** [petkaantonov/bluebird#1345]
I am using bluebird 3.4.6.

And when I run my tests, I get this error:

> (node) warning: possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit.
> Trace
>     at Server.addListener (events.js:239:17)
>     at Server._listen2 (/Users/paul/projects/cpt-webapi-ee/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:44:10)
>     at listen (net.js:1273:10)
>     at Server.listen (net.js:1369:5)
>     at Test.serverAddress (/Users/paul/projects/cpt-webapi-ee/node_modules/supertest/lib/test.js:59:33)
>     at new Test (/Users/paul/projects/cpt-webapi-ee/node_modules/supertest/lib/test.js:36:12)
>     at Object.obj.(anonymous function) [as post] (/Users/paul/projects/cpt-webapi-ee/node_modules/supertest/index.js:25:14)
>     at Context.<anonymous> (/Users/paul/projects/cpt-webapi-ee/test/unit/models/pension-user.test.js:94:10)
>     at next (native)
>     at tryCatcher (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/util.js:16:23)
>     at PromiseSpawn._promiseFulfilled (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/generators.js:97:49)
>     at Promise._settlePromise (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/promise.js:572:26)
>     at Promise._settlePromise0 (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/promise.js:612:10)
>     at Promise._settlePromises (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/promise.js:691:18)
>     at Async._drainQueue (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/async.js:138:16)
>     at Async._drainQueues (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/async.js:148:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (/Users/paul/projects/cpt-webapi-ee/node_modules/bluebird/js/release/async.js:17:14)

I am using `Promise.coroutine` a lot in this project and could this be related?

**Comment by benjamingr** [comment]
This is an issue with continuation-local-storage as your stack trace tells you and not in bluebird. 

Thanks for reporting.
