### ISSUE TITLE
nativescript web workers error handling

### ISSUE THREAD

**Issue by m3l7** [petkaantonov/bluebird#1347]
I'm trying to catch bluebird unhandled errors (through the unhandledRejection event) inside a web worker in native script.

In native script, neither the process/self nor the window object are available, so I cannot listen to the proper event with addEventListener.

Is there another way to handle errors?

see https://github.com/NativeScript/NativeScript/issues/3695 for the same bug in the nativescript repo

**Comment by benjamingr** [comment]
You can catch the event on the Promise instance itself:

```js
Promise.onPossiblyUnhandledRejection(function(e) { 
   // do something with `e` here.
});
```

Cheers.
