### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by bbenezech** [petkaantonov/bluebird#1348]
**npm webpack browser**

Something is really wrong with the config management.
- The doc is buried here http://bluebirdjs.com/docs/api/promise.config.html, where even Indiana Jones would not find it. It think it belongs to the Readme.
- Someone (on drugs I guess) thought it was acceptable to override an explicit setting with a collection of implicit buggy ENV variables overrides that would drive anyone mad, and that doesn't actually work. I set no variables at all, and warnings appear in dev and prod. Wth

**Comment by benjamingr** [comment]
Yeah, I don't think we're going to have any discussion with that tone.
