### ISSUE TITLE
Recipes for partially applying/currying `Promise.prototype.then` callbacks

### ISSUE THREAD

**Issue by benderTheCrime** [petkaantonov/bluebird#1352]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
All of them, I don't think this functionality is supported

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
All of them, I don't think the platform matters here

3) Did this issue happen with earlier version of bluebird?
Yes, I don't think this functionality has ever been supported.

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I'm looking for some helpful recipe for passing a function to a Promise "then" without explicitly binding or currying the callback.

Example, currently, I do something of this nature:

```javascript
someAsyncFunctionCall().then(createHandleResponse(target));

function createHandleResponse(target) {
    return function handleResponse(response) {
        return Object.assign({}, target, response);
    }
}
```

The code here is completely demonstrative, but does a good job of showing a problem with repetition I currently face in my code. It doesn't seem like much, but I don't really want to create curry versions of all of my callbacks and I think perhaps using a curryN function on top of already loading bluebird is superfluous. I would like to avoid binding of any flavor.

I wrote a really naïve implementation of this using then as a demonstration before remembering that "then" takes more than one function callback:

```javascript

.then(func, ...args);

```

Which clearly won't work, so perhaps an implementation that does not take a rejection callback or one that will detect if the first 2 arguments are functions? The signature here is tricky, but perhaps:

```javascript

Promise.prototype.apply = function(func, ...args) {}:

```

I don't particularly like this, but it's the best I can think of at the time of writing this. The biggest problem here are functions with variable arity.

If anyone else has a recipe using an existing Bluebird API endpoint that does not curry inline or explicitly bind, please share!

**Comment by benderTheCrime** [comment]
Alternatively, I could see acheiving this with `Promise.bind`/`Promise.prototype.bind` being valuable, provided `Promise.prototype.bind` exists and can be chained.

**Comment by benjamingr** [comment]
Your `.apply` would be confusing with the current `.call`. 

This is up to you producing the function and not to the library. I recommend using Ramda to automatically curry your function. For what it's worth with modern ES your function would be:

```js
const handleResponse = target => response => Object.assign({}, target, response);
```

Which is a lot nicer, not to mention `Promise.coroutine` or async functions.

In any case, you could always drop the eta reduction and do: `.then(x => handleResponse(target, x))` or curry:


```js
const handleResponse = R.curry((target, response) => Object.assign({}, target, response));
```

For doing it automatically.
