### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by isiahmeadows** [petkaantonov/bluebird#1353]
The benchmarks [here](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/benchmarks.md) are fairly out of date now (1 1/2 years at this point). Also, V8 has made some [drastic performance improvements](https://v8project.blogspot.com/2017/02/v8-release-57.html) to their Promise implementation recently, so their performance is close to on par with Bluebird's now. The benchmarks *really* need updated.

**Comment by petkaantonov** [comment]
updated

note that latest node is using v8 5.5 so those improvements are still not reflected

**Comment by isiahmeadows** [comment]
@petkaantonov Chrome is using 5.8 now, so they have the latest optimizations. [The next major Node release is also going to use either that or 5.7](https://github.com/nodejs/node/issues/10117#issuecomment-264954525), so they're going to have them, too. So when that happens (late this April), you should be able to update the benchmark again with faster numbers.
