### ISSUE TITLE
Promise.join does not call handler with bound value

### ISSUE THREAD

**Issue by roadrunner2** [petkaantonov/bluebird#1357]
1) What version of bluebird is the issue happening on?
3.5.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 0.10 - but should be platform independent

3) Did this issue happen with earlier version of bluebird?
Unknown

The following illustrates the behaviour:
```
Promise.join(Promise.resolve(1),
             function(res1) { console.log("this.x:", this.x); }
).bind({ x: 3 });
```
This prints `this.x: undefined`. A workaround is to use all+spread:
```
Promise.all([Promise.resolve(1)])
.bind({ x: 3 })
.spread(function(res1) { console.log("this.x:", this.x); });
```
which prints `this.x: 3` as expected.

**Comment by spion** [comment]
The value is bound after join, so this is working as intended. Similar rules apply to all static methods, e.g. `Promise.try(fn).bind({x: 3})` will not assign a `this` value in `fn`
