### ISSUE TITLE
Distribute bluebird-core via NPM

### ISSUE THREAD

**Issue by gajus** [petkaantonov/bluebird#1361]
I am assuming that `bluebird.core.js` (as seen in the releases https://github.com/petkaantonov/bluebird/releases) is a Bluebird version without the custom Promise extensions. It would be nice to have an NPM package `bluebird-core` that distributes this version.

**Comment by petkaantonov** [comment]
>  is a Bluebird version without the custom Promise extensions

It's not, it's just the minimal custom build but it still comes with a lot of non standard features..
