### ISSUE TITLE
Debugging with async stack traces in Node.js

### ISSUE THREAD

**Issue by bajtos** [petkaantonov/bluebird#1364]
The commit d37d0fff, which fixed #542, modified Bluebird to detect when it's running in a Chrome/Blink DevTools debugger and use a different queueing mechanism that plays well with DevTools "async stack traces" feature.

AFAICT, this does not work in DevTools provided by Node.js built-in debugger (`node --inspect`):
 - `bluebird@3.5.0`
 - `node@6.10.1` (but also `8.0.0-pre` compiled locally from nodejs/node@e1d4f0ed)

It would be great to modify Bluebird to support async stack traces in Node.js too. I think this will most likely require changes in Node.js too - AFAICT, right now there is no way how to detect whether a debugger is running or not.

A sample app I am using to reproduce the problem.

```js
'use strict';

const Promise = require('bluebird');

setInterval(tick, 500);

function tick() {
  tickAsync().then(
    success => console.log('PASS', success),
    error => console.log('FAIL', error)
  );
}

function tickAsync() {
  return first().then(second).then(() => {
    debugger;
    return 'ok';
  });
}

function first() {
  return delay(10).then(() => {
    console.log('first done');
  });
}

function second() {
  return delay(10).then(() => {
    console.log('second done');
  });
}

function delay(ms) {
  // originally, I used setTimeout(resolve, ms)
  // but it looks like setTimeout is breaking 
  // V8's async-stack-trace detection :(
  return new Promise(resolve => resolve());
}
```

Async stack trace when using bluebird:

<img width="371" alt="screen shot 2017-03-25 at 15 16 31" src="https://cloud.githubusercontent.com/assets/1140553/24322974/1064058c-116e-11e7-941c-84d0b75e9b4f.png">

Async stack trace when I comment-out `const Promise = require('bluebird')`:

<img width="370" alt="screen shot 2017-03-25 at 15 15 25" src="https://cloud.githubusercontent.com/assets/1140553/24322966/fa573174-116d-11e7-8f51-f1df4f36676c.png">

**Comment by bajtos** [comment]
> setTimeout breaks async stack traces in DevTools debugger

I filled a Node.js issue for that - see https://github.com/nodejs/node/issues/12038

**Comment by benjamingr** [comment]
There is nothing we can do on our side about this, sorry. Blocked on https://github.com/nodejs/node/issues/11370

**Comment by bajtos** [comment]
Thank you for a quick response, @benjamingr. As I see it, there are two problems here:
 - Node.js's `setTimeout` function is breaking async stack traces (nodejs/node#11370), I agree that cannot be fixed in Bluebird.
 - Bluebird's `then` is breaking async stack traces in Node.js. IMO, this is something that can be fixed in Bluebird, since a similar problem in Chrome was already fixed by d37d0ff.

**Comment by benjamingr** [comment]
It's just disabling the trampoline, does this not work with `--inspect` at the moment?

**Comment by bajtos** [comment]
> It's just disabling the trampoline

Yes, I agree!

>  does this not work with `--inspect` at the moment?

No, that's why I have reported this issue :)

See [src/util.js](https://github.com/petkaantonov/bluebird/blob/ac381051cd26a6d1b735d9f8a239710f68a899c4/src/util.js#L373-L374) at the current master:

```js
    hasDevTools: typeof chrome !== "undefined" && chrome &&
                 typeof chrome.loadTimes === "function",
```

There is no global `chrome` object defined by Node.js, therefore this detection does not work in Node.js.

See also what I wrote in the issue description:

> I think this will most likely require changes in Node.js too - AFAICT, right now there is no way how to detect whether a debugger is running or not.

cc @petkaantonov It makes me wonder, since you are Node.js committer (IIRC), what's your opinion on this?

**Comment by benjamingr** [comment]
@bajtos we're both NodeJS collaborators. There is no flag that I'm aware of that's set automatically with `--inspect`, we can read the process arguments and check for `--inspect` ourselves but I'm not sure if that's optimal.

In any case, it looks like the Node issue is a lot bigger than the Bluebird one.

**Comment by bajtos** [comment]
> In any case, it looks like the Node issue is a lot bigger than the Bluebird one.

You are right. I realised it last night - there is little value in Bluebird preserving async stack traces if Node.js APIs break them anyways.

**Comment by Serha31** [comment]
Need help how to solve this : (node:740) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.

**Comment by bajtos** [comment]
> Need help how to solve this : (node:740) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.

This is off-topic here.

Async stack traces are no supported on 32bit platforms because of a limitation of V8 inspector/debugger. See the discussion in https://github.com/nodejs/node/pull/13870, especially the following threads: https://github.com/nodejs/node/pull/13870#discussion_r124930411, https://github.com/nodejs/node/pull/13870#discussion_r127086782, https://github.com/nodejs/node/pull/13870#issuecomment-315126472. 

https://github.com/nodejs/node is the place where to discuss this issue further.
