### ISSUE TITLE
Simple check for isBluebirdPromise()

### ISSUE THREAD

**Issue by ORESoftware** [petkaantonov/bluebird#1365]
Is there a simple property or method on the Bluebird Promise object that we can check to see if the Bluebird library has loaded and the Promise object that we are using is the Bluebird one?

`Promise.isBluebirdPromise or Promise.isBluebird()?`

thanks

**Comment by ericmdantas** [comment]
I don't think there's a single (and reliable) way to do that right now, but there's https://github.com/petkaantonov/bluebird/issues/1323#issuecomment-273705651.

> Promise.prototype.cancel seems like the most obvious to probe for cancellation (bluebird has a build without it).

>Promise.prototype._cancel is also fine if you want to detect bluebird in particular.

>Promise.version detects bluebird.

**Comment by ORESoftware** [comment]
Thx

On Mar 28, 2017 6:05 AM, "Benjamin Gruenbaum" <notifications@github.com>
wrote:

Promise.version works. Cheers.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/petkaantonov/bluebird/issues/1365#issuecomment-289763050>,
or mute the thread

**Comment by ORESoftware** [comment]
@benjamingr thanks, on this topic, do you happen to know how to check if global.Promise is the native implementation?
