### ISSUE TITLE
Can't get unforgotten return to actually warn

### ISSUE THREAD

**Issue by q42jaap** [petkaantonov/bluebird#1368]
1) What version of bluebird is the issue happening on?
3.5.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node v6.10.1

Hi I've created a minimal example of a promise that is forgotten to return. Is this supposed to work in node, because I can't get it to work.

```
Promise.delay(100)
  .then(() => {
    console.log('after 100', Date.now() - start);
    Promise.delay(200)
      .then(() => {
        console.log('should be after 100+200, really', Date.now() - start);
      });
  })
  .then(() => {
    console.log('should be after 300, really', Date.now() - start);
  });
```

The output is:
```
$ node index.js
after 100 107
should be after 300, really 110
should be after 100+200, really 314
```

How should the warning show up?

https://github.com/q42jaap/bluebird-forgotten-test (just checkout `npm install` and run `node index.js`).

**Comment by mkjois** [comment]
At first glance, I think you need to `return` the inner promise:

```
Promise.delay(100)
  .then(() => {
    console.log('after 100', Date.now() - start);
    return Promise.delay(200)
      .then(() => {
        console.log('should be after 100+200, really', Date.now() - start);
      });
  })
  .then(() => {
    console.log('should be after 300, really', Date.now() - start);
  });
```

**Comment by q42jaap** [comment]
@mkjois the code is intentionally bogus, there is a feature in bluebird which warns for the forgotten return. But I can't seem to get the warning to show up.

**Comment by mkjois** [comment]
Oh lol I forgot to even read the title and description...all I saw was "I can't get it to work" and read the code. My bad!
