### ISSUE TITLE
Docs are contradictory regarding disposers and SQL transactions

### ISSUE THREAD

**Issue by mrtbld** [petkaantonov/bluebird#1372]
Documentation about disposers contradicts itself about whether or not it's a good idea to use them for SQL transactions.

On one hand [Working with callbacks](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/working-with-callbacks.md) says that 

> It's also possible to use disposers for transaction management

and suggests the snippet :

```js
function getTransaction(connectionString) {
    var close;
    return pg.connectAsync(connectionString).spread(function(client, done) {
        close = done;
        return client.queryAsync('BEGIN').then(function () {
            return client;
        });
    }).disposer(function(client, promise) {
        if (promise.isFulfilled()) {
            return client.queryAsync('COMMIT').then(closeClient);
        } else {
            return client.queryAsync('ROLLBACK').then(closeClient);
        }
        function closeClient() {
            if (close) close(client);
        }
    });
}
```

On the other hand [Disposer API documentation](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/api/disposer.md#note-about-disposers-in-node) says that

> disposers should not contain code that does anything other than resource disposal. For example, you cannot write code inside a disposer to commit or rollback a transaction, because there is no mechanism for the disposer to signal a failure of the commit or rollback action without crashing the process.

and suggests :

```js
function withTransaction(fn) {
  return Promise.using(pool.acquireConnection(), function(connection) {
    var tx = connection.beginTransaction()
    return Promise
      .try(fn, tx)
      .then(function(res) { return connection.commit().thenReturn(res) },
            function(err) {
              return connection.rollback()
                     .catch(function(e) {/* maybe add the rollback error to err */})
                     .thenThrow(err);
            });
  });
}
```

**Comment by benjamingr** [comment]
Hah! The things we learned on the way, thanks!

@petkaantonov please run a docs rebuild?

**Comment by vitaly-t** [comment]
@mrtbld a better take on transactions, while also using Bluebird in the background: http://stackoverflow.com/questions/37051683/optional-insert-statement-in-transaction-chain-using-nodejs-and-postgres/37054241#37054241
