### ISSUE TITLE
Beginner's guide does not exist on website

### ISSUE THREAD

**Issue by techmexdev** [petkaantonov/bluebird#1373]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.0

**Comment by benjamingr** [comment]
https://github.com/petkaantonov/bluebird/issues/1111
 
> It's a blank page because it's not written yet
 😄 1
