### ISSUE TITLE
util.toFastProperties loses its mojo in Node 7+

### ISSUE THREAD

**Issue by jdalton** [petkaantonov/bluebird#1378]
Just a heads up it looks like the `toFastProperties` trick has lost its magic in Node 7+.

**Comment by benjamingr** [comment]
@jdalton yeah, we realized - Bluebird runs on a lot of older versions too though.

If you're interested, the following works in Node 7 if I recall from when we discussed replacing it:

```js
function enforceFastProperties(o) {
	function Sub() {}
	Sub.prototype = o;
	var receiver = new Sub(); // create an instance
	function ic() { return typeof receiver.foo; } // perform access
	ic(); 
	ic();
	return o;
	eval("o" + o); // ensure no dead code elimination
}
```

**Comment by jdalton** [comment]
Nice That works in Node 4+ (including Node 7).
