### ISSUE TITLE
Memory leak in Promise.each

### ISSUE THREAD

**Issue by polomsky** [petkaantonov/bluebird#1380]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.0
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
nodejs 6.10.3
3) Did this issue happen with earlier version of bluebird?
I do not know

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

leak.js
```javascript
global.Promise = require('bluebird');
Promise.config({
    warnings: true,
});
function *gen() {
    var i;
    for (i = 0; i< 10000000; i++) {
        yield i;
    }
}
Promise.each(gen(), function() {
// no content is needed
});
```
launched as `NODE_ENV=production node leak.js`

**Comment by petkaantonov** [comment]
There isn't enough memory to chain 10 000 000 promises, that's not a leak.

**Comment by polomsky** [comment]
I was able to rewrite it by using of process.nextTick to avoid this problem so there is no need to chain them all at once. I tried to find if another promise returning function is leaking and I only found that used "loop" function is leaking itself.
