### ISSUE TITLE
Does Promise.map () execute in thread context?

### ISSUE THREAD

**Issue by chiarelli** [petkaantonov/bluebird#1381]
When executing a code that merge a file using the **File System** (API core nodejs) with stream using the **Promise.map()** implementation, with the concurrency option, the resulting file was truncated; But without the option of concurrency the resulting file presented no problem.

**Promise.map()**, with concurrency option enabled, is executed using **Workers**? If it is believed this might be the problem, since **File System** is singleton and run in another context it may not be thread-safe.

**Comment by benjamingr** [comment]
There is only one thread in user land Node. You've probably promisified ads wrong or didn't understand that it's for callbacks and doesn't work with streams.

Thanks for the report and reaching out.
