### ISSUE TITLE
.bind() should support rest args

### ISSUE THREAD

**Issue by estaylorco** [petkaantonov/bluebird#1385]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
**3.4.1**

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
**Chrome Version 57.0.2987.133 (64-bit)**

3) Did this issue happen with earlier version of bluebird?
**Not aware of whether it did**

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Consider the following code snippet from my authentication controller:

```
  tryRequestRecoveryCode(emailAddress) {
    require: {
      emailAddress, 'Email address exists';
    }

    check: this._authController, 'Authentication controller exists';
    return this._authController.issueRecoveryCodeTo(emailAddress)
      .then(this._doRecoveryCodeIssued.bind(this, emailAddress))
      .catch(this._doEmailAddressNotOnFile.bind(this, emailAddress));
  }
```

It would be desirable to be able to write this as

```
  tryRequestRecoveryCode(emailAddress) {
    require: {
      emailAddress, 'Email address exists';
    }

    check: this._authController, 'Authentication controller exists';
    return this._authController.issueRecoveryCodeTo(emailAddress).bind(this, emailAddress)
      .then(this._doRecoveryCodeIssued)
      .catch(this._doEmailAddressNotOnFile);
  }
```

But it seems that this is not possible.  Shouldn't `#bind` support rest args?

Thank you.

**Comment by benjamingr** [comment]
This code produces a syntax error. Moreover, `bind` is just for context and not for partial application in bluebird, you can use a library like lodash to get the sort of API you'd like. 

Assuming you're writing in Node, you should be using async/await or coroutines most likely anyway.
