### ISSUE TITLE
Calling `toJSON` unsets unhandled rejection state.

### ISSUE THREAD

**Issue by 10xjs** [petkaantonov/bluebird#1386]
Using v3.5.0 on Chrome v57.0.2987.133

If `toJSON` is called on a promise instance, the unhandled rejection state is unset.

This means that any promise that gets serialized to JSON will not be caught in an unhandled rejection event.

![image](https://cloud.githubusercontent.com/assets/1074748/26021817/7a7bab62-374a-11e7-9900-c0822a2a1526.png)

The expected result is that calling `toJSON` makes no changes to the target instance.

Issue exploration:
`toJSON` calls [`reason`](https://github.com/petkaantonov/bluebird/blob/9d03393aab53b879c05069fc3c3fa78cc2ba698b/src/promise.js#L153) which calls [`_unsetRejectionIsUnhandled`](https://github.com/petkaantonov/bluebird/blob/9d03393aab53b879c05069fc3c3fa78cc2ba698b/src/synchronous_inspection.js#L98)

**Comment by benjamingr** [comment]
Hmm, maybe we should define a toJSON on 'reason'?

**Comment by benjamingr** [comment]
Made a PR: https://github.com/petkaantonov/bluebird/pull/1387

**Comment by petkaantonov** [comment]
The reason has been made available, therefore it is considered handled.

**Comment by benjamingr** [comment]
@petkaantonov I understand the original logic - but I'm not sure it should work this way - just because you logged a promise (and its rejection is observed) doesn't mean an attempt to handle it was performed.

**Comment by petkaantonov** [comment]
That applies to any rejection consumption. I.E. Just because you caught an error and just logged it doesn't mean it was handled yet we don't report it. Same with .reason() etc.

**Comment by benjamingr** [comment]
@petkaantonov yes, I understand `.reason`, but people who `JSON.stringify` an object containing a unhandled rejection promise as a side effect of logging all payloads (for example) would not expect the rejection to be silent - would they?

**Comment by 10xjs** [comment]
@petkaantonov I'm looking for an example to use to show precedent, but I can't find anything to prove my case yet.

However, I feel like the implicit `toJSON` behavior should not mutate the target object. This to me is an anti-pattern where simply observing a value causes it to change.

If `toJSON` wasn't something that was called implicitly, this wouldn't be an issue.

**Comment by 10xjs** [comment]
Since the fix proposed by @benjamingr would be a breaking change, I know if it's the best approach.

One solution could be to add a config option disable JSON serialization altogether, and instead mirror the behavior of the native `Promise` object.

```
import Promise from 'bluebird';

Promise.config({
  toJSON: false,
});
```

![image](https://cloud.githubusercontent.com/assets/1074748/26078962/0ad5f96a-3976-11e7-8f05-6e1ff3b702a1.png)
