### ISSUE TITLE
"Optimization killers": INLINE_SLICE seems unnecessary

### ISSUE THREAD

**Issue by jareguo** [petkaantonov/bluebird#1389]
In [What is safe arguments usage?](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#what-is-safe-arguments-usage), you saild:

> STRICTLY fn.apply(y, arguments) is ok, nothing else is, e.g. .slice. Function#apply is special.

So if we have a function like:

```js
// just the same as INLINE_SLICE
function sliceArguments () {
    var $_len = arguments.length;
    var args = new Array($_len); 
    for(var $_i = 0; $_i < $_len; ++$_i) {
        args[$_i] = arguments[$_i];
    }
    return args;
}
```

and use it like this:

```js
function doesntLeakArguments() {
    var args = sliceArguments.apply(null, arguments);
    return args;
}
``` 

it should be safe and optimizable, is it true?

IMHO, this way is better than INLINE_SLICE because we don't need the macro's build-step.

**Comment by benjamingr** [comment]
Yes, and also that tip is only valid until the new compiler lands in like a month

**Comment by jareguo** [comment]
Thanks @benjamingr .
What's the change of  INLINE_SLICE in the new compiler?

**Comment by benjamingr** [comment]
In TF using rest args syntax `...args` is as fast as inline slicing when skipping one and as fast when just passing arguments

**Comment by jareguo** [comment]
That's perfect, thanks!
