### ISSUE TITLE
Feature/ Promise.method - match function.length property with number of defined arguments

### ISSUE THREAD

**Issue by fogine** [petkaantonov/bluebird#1390]
1) What version of bluebird is the issue happening on?
 `3.5.0`
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
`node 6.x`
3) Did this issue happen with earlier version of bluebird?
`yes`

It would be cool if methods defined via `Promise.method` reflected number of arguments that the actual function implements. Consider the following example:  

```javascript
function method(arg1, arg2) {};
Module.prototype.method = Promise.method(method);

console.log(Module.prototype.method.length == method.length); //false
```

Thank you for your great contributions to opensource!

**Comment by petkaantonov** [comment]
As far as I can tell it's not worth the complexity, it would require dynamic function evaluation which cannot be used in browsers due to CSP
