### ISSUE TITLE
utilize util.promisify?

### ISSUE THREAD

**Issue by icodeforlove** [petkaantonov/bluebird#1398]
Will bluebird start using util.promisify?

**Comment by benjamingr** [comment]
No, since it's slower, less versatile and wouldn't reduce allocations.

**Comment by benjamingr** [comment]
Full disclosure - I worked on util.promisify

**Comment by icodeforlove** [comment]
Chad Scira liked your email
Spark by Readdle

**Comment by vitaly-t** [comment]
> Will bluebird start using util.promisify?

It would be just as good an idea as for Bluebird to become based off ES6 Promise :smile:
