### ISSUE TITLE
Disposer does not cleanup after rejection

### ISSUE THREAD

**Issue by ptusch** [petkaantonov/bluebird#1399]
Good day everyone,

today I encountered an issue with the Disposer object which looked pretty nice at first glance but seems to be a tricky to use.

First things first:
--
* Bluebird version: 3.5.0
* Platform: Windows 7 (x64) 
* Node version: 4.4.3

"Did this issue happen with earlier versions of bluebird"?
I am not sure. First I thought it worked with 3.3.5 but that was not the case.

The issue
--
Alright, I might not use the correct approach to use Disposers and `Promise.using` so please let me know when I failed that regard - if I didn't mess up it might be my understanding of Disposers and resources in general; Again, please let me know.

Code explains better than my linguistic skills would allow:
```js
'use strict';

const Promise = require('bluebird');

function eww() {
  return Promise.reject(new Error('evil issue'))
    .delay(100)
    .disposer(() => {
      console.log('should be called but never is');
    });
}

Promise.using(eww(), () => {
  console.log('positive case - never called');
})
.catch((err) => {
  console.log('failed as expected - resource is not cleaned up.');
})
```

The basic issue is that my disposer function is never called which should be a Bluebird issue.
The reason being - again, my understanding - that whenever I attempt to claim a resource, the disposer _always_ takes care about the proper cleanup.

Currently, when my resource claiming function (`eww()` from the example) fails, I have to manually clean up my mess - which may is impossible when I wrap my code behind the disposer.

The problem is [this code chunk](https://github.com/petkaantonov/bluebird/blob/9ab9d545b2fa0dd29efc5df43789cf43b6555c68/src/using.js#L66-L83).

The issue is not to be mistaken with [this issue](https://github.com/petkaantonov/bluebird/issues/1099).
I suspect it never worked like I thought it would..

Can anyone confirm this behavior?
I wonder if this is intended. If I have to manually clean up after disposers, I rather not use them at all.
The caller should not care about cleaning up in such cases - especially in rejection cases.

Edit:
I changed the code within the using.js to the following (`resource` method):
```js
Disposer.prototype.resource = function () {
        if (this.promise().isFulfilled()) {
            return this.promise().value();
        }
        if (this.promise().isRejected()) {
            return this.promise().reason();
        }
        return NULL;
    };
```
This causes the disposer to work as intended. If this is a proper change to you, let me know and I'll PR you it.

Best regards,
Philipp

**Comment by spion** [comment]
The issue is that the resource was never acquired in the first place. If the promise that acquires a resource fails, it makes sense to assume that the resource was not acquired and is therefore unnecessary to clean it up.

**Comment by ptusch** [comment]
The thing is we can't be certain that the resource was never acquired. Surely, we didn't receive a connection (to simplify the terms a bit) but what if we already created like a socket or something similar which doesn't clean up itself (or not at all) and the reason for the rejection may be something different like setting a flag based on wrongly configured connections.

The current patterns makes aggregations over different steps impossible.
One example would be that I want to create a bound LDAP client using [ldapjs](http://ldapjs.org/client.html).
For that I'd create a new function `createBoundLdapClient` that returns a bound Ldap client. 
So when the [creation](http://ldapjs.org/client.html#create-a-client) works but the [bind](http://ldapjs.org/client.html#bind) fails I'm at a dead end with disposers and can't roll back - the socket is forever open and memory is leaked.

The workaround would be to always resolve a disposer function and open another channel to propagate errors (like events) but that sounds like a big anti pattern..

**Comment by spion** [comment]
Yes, chaining disposers is important. I reopened #1379

**Comment by ptusch** [comment]
Hi,

today I checked with c# (which I assume worked as heavy inspiration for Bluebird Disposers) and their Dispose (or IDisposable interface) works exactly the same way - they do not execute the Disposer upon thrown exceptions.

I'm sorry for the heavy tone and look forward to Disposer chaining.

Cheers

**Comment by benjamingr** [comment]
@ptusch if you're interested, when we designed `using` I asked this from a C# perspective: https://stackoverflow.com/questions/21118201/can-using-with-more-than-one-resource-cause-a-resource-leak

**Comment by ptusch** [comment]
@benjamingr Ahh, I just read [your comment](https://stackoverflow.com/questions/21118201/can-using-with-more-than-one-resource-cause-a-resource-leak#comment31797113_21123756) there. I didn't know that a `.disposer` function requires to guarantee no throw.

Thanks for the link!

**Comment by petkaantonov** [comment]
Disposer cannot be called because there is nothing to call it with.
