### ISSUE TITLE
Spread with jQuery XHR as argument transforms it into data

### ISSUE THREAD

**Issue by bisrael** [petkaantonov/bluebird#1406]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

Bluebird 3.5.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Google Chrome  58.0.3029.110 on macOS 10.12.4

3) Did this issue happen with earlier version of bluebird?

n/a

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Given the following code:

```javascript
var Promise = require('bluebird');
var $ = require('jquery');

// Wraps a jQuery ajax call in a Bluebird promise
function myAjax(ajaxOptions, behavioralOptions) {
  return new Promise(function (_resolve, _reject, _onCancel) {
    var $ajax = $.ajax(ajaxOptions).then(function (data, textStatus, jqXHR) {
      if (behavioralOptions.asArray) {
        // optional because Bluebird only pays attention to the first argument of _resolve
        _resolve([data, textStatus, jqXHR]);
      } else {
        _resolve(data);
      }
    }, function (jqXHR) {
      _reject(jqXHR);
    });

    if ($.isFunction(_onCancel)) {
      _onCancel(function () {
        $ajax.abort();
      });
    }

  });
}
```

when you call

```javascript
myAjax({url: 'http://www.example.com'}, {asArray: true}).spread(function (data, textStatus, jqXHR) {
  console.log(data, textStatus, jqXHR);
  if (jqXHR === data) {
    console.log('wtf!?');
  }
});
```

`jqXHR` is exactly `data`.

my understanding is that `.spread` implicitly calls `.all`, which sees jqXHR as a thenable object, converts it's `.then(data, textStatus, jqXHR)` response dropping the other items, and converting it back to just `data`.

this is unintuitive behavior.

i would like to see `.spread` decoupled from `.all` or at least an alternative helper method provided that does not call `.all` magically.

**Comment by benjamingr** [comment]
That's how spread works and I don't think we're going to break that after over 4 years (not to mention compatibility with Q).

You can however use regular JavaScript spread which behaves the way you'd like:
```
myAjax({url: 'http://www.example.com'}, {asArray: true}).spread(([data, textStatus, jqXHR]) => 
```

**Comment by bisrael** [comment]
I think it's more of a feature request than a bug, like having a `splat` that doesn't do an implicit `all`
