### ISSUE TITLE
Temporarily disabling Bluebird warnings in tests

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#1407]
This is for a question on StackOverflow that never got an answer: [Temporarily disabling Bluebird warnings in tests](https://stackoverflow.com/questions/44496334/temporarily-disabling-bluebird-warnings-in-tests).

I'm guessing it is because such thing is not supported, in which case I kindly ask for this to be a feature request.

---

Republishing the question from StackOverflow here...

> When implementing tests that knowingly produce warnings from Bluebird....
>
> Is there a way to disable all warnings for a specific test or even a test line?
>
> I mean, is there any provision for it in the library?
>
> I know about the [global configuration](http://bluebirdjs.com/docs/api/promise.config.html) and how to switch warnings off completely, but this is not what I'm looking for.
>
> **clarification**
>
> This is for negative tests that are supposed to be invalid. I just don't want Bluebird to pollute the console with warnings for such specific tests. I'm looking for a way to say in any given test - `Warnings in this test are by design, do not write anything into the console`.

**Comment by benjamingr** [comment]
I'm fine with this feature, PR welcome.

**Comment by charlierudolph** [comment]
Could you use the global configuration to turn warnings off before the test and turn them back on after the test?

**Comment by vitaly-t** [comment]
@charlierudolph it would be good to know, yes.

My only concern - changing it globally will mess up with any concurrent test framework where tests may be executing in parallel.

**Comment by petkaantonov** [comment]
Use different instance of bluebird library where you have called `.config` with warnings = false
