### ISSUE TITLE
Unhandled rejection occurs when not chained

### ISSUE THREAD

**Issue by bstutsky** [petkaantonov/bluebird#1408]
1) What version of bluebird is the issue happening on?
3.5.0
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Chrome 58 - jsfiddle
3) Did this issue happen with earlier version of bluebird?
Yes

It seems that chaining then, catch, and finally properly handles rejection, but when the calls to then, catch, and finally are not chained an unhandled rejection is thrown. I have a jsfiddle [here](http://jsfiddle.net/stutsky1/28opy0fa/).

```
var promiseCBs = [];

var promise1 = new Promise((resolve, reject) => {
	promiseCBs.push({resolve, reject});
});
var promise2 = new Promise((resolve, reject) => {
	promiseCBs.push({resolve, reject});
});

promise1.then(() => console.log('a'));
promise1.catch(() => console.log('b'));
promise1.finally(() => console.log('c'));

promise2.then(() => console.log('1'))
	.catch(() => console.log('2'))
  .finally(() => console.log('3'));

//unhandled rejection
promiseCBs[0].reject(new Error('rej0'));

//no unhandled rejection
promiseCBs[1].reject(new Error('rej1'));
```

**Comment by benjamingr** [comment]
By design, here is a simpler case to demonstrate why:

```
function api() { 
  var p1 = Promise.reject(new Error("rej1"); // in reality, some API call that may fail
  p1.catch(handleAPIRejection);
  // the below is unhandled, since the chain is forked, the `then` is never called and 
  // the error is swallowed for the function caller if we don't emit unhandledRejection here
  return p1.then(x => console.log(x)); 
}
```
This is also the behavior of native promises.

**Comment by bstutsky** [comment]
Interesting, I didn't realize this previously. Thanks for the knowledge!

**Comment by kswope** [comment]
Is this the same mechanism?  I found this minimal example of a unhandled rejection in bluebird and native node promises.

```
let p = Promise.reject( 'hi' )
p.then( () => {} )
p.catch( ( x ) => { console.log( x ) } )
```

The above prints out both 'hi' and 'Unhandled rejection hi'.  Looks to me like a noop call to p.then is changing the state of p.  If you properly chain them the warning goes away.

**Comment by benjamingr** [comment]
That’s intentional, the sample you posted has an unhandled rejection...

**Comment by kswope** [comment]
Its 'unhandled', yet its being handled.

**Comment by benjamingr** [comment]
No, it’s not handled, this line:


     p.then( () => {} )

Creates and returns a new rejected promise whose rejection is never handled

**Comment by kswope** [comment]
Well damn, promises can 'fork'

```
let p = Promise.reject( 'hi' )
p.then( () => {} ).catch(x => console.log('fork1'))
p.then( () => {} ).catch(x => console.log('fork2'))
p.then( () => {} ).catch(x => console.log('fork3'))
p.catch( ( x ) => { console.log( 'catch', x ) } )
```

I don't think I've seen one mention of that anywhere and I've read a book and countless blog posts.

Thank you for clueing me in!  I'm sure you had better things to do on a sunday.

Is this part of the spec or just happens naturally?  If I wrote a promise library that prevented this behavior would it still pass the specs tests?

**Comment by benjamingr** [comment]
Multicast semantics are fundamental to promises, this is part of the spec and you can create a model that only allows one continuation (in JS those are typically called “tasks”). 

Multicast semantics are fundamental in the design of promises. In practice if promises were unicast then things like unhandled rejections and cancellation become a lot simpler at the expense of the end user.
