### ISSUE TITLE
bluebird missing index.js

### ISSUE THREAD

**Issue by Freyert** [petkaantonov/bluebird#1410]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.0
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node v6.9.4
3) Did this issue happen with earlier version of bluebird?
No
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

We can download bluebird using `npm i bluebird`, but when it installs the module folder in `./node_modules/bluebird` does not contain an `index.js`. Therefore `node`'s module system can not properly require the `bluebird` module.

**Comment by benjamingr** [comment]
What? Can you give more details on your build system I cannot reproduce

**Comment by Freyert** [comment]
This is just me trying to `npm i` on my desktop. I use `nvm`, but other than that I'm `macOS 10.12.5`.

**Comment by Freyert** [comment]
Looks like this is an issue with our NPM proxy messing around with the `package.json` as it is coming in. It removed the `"main"` directive from the `package.json`.

**Comment by ogntng** [comment]
i get same issue, how to solve that? @Freyert ? 🙏

**Comment by Freyert** [comment]
@ogntng it's specific to your private registry, but I would recommend if possible you only use your private registry to pull private packages.

See [Associating a scope with a private registry](https://docs.npmjs.com/misc/scope#associating-a-scope-with-a-registry).

I have no idea why the issue occurred or how we fixed it, but someone higher up in the chain fixed the registry.
