### ISSUE TITLE
Cannot override "Promise" keyword in REPL.

### ISSUE THREAD

**Issue by richardpringle** [petkaantonov/bluebird#1413]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
bluebird@3.4.6

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
v7.10.1-pre (7.10.0 was fine)

3) Did this issue happen with earlier version of bluebird?
nope

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I only experience this from REPL:
```node
> const Promise = require('bluebird');
ReferenceError: Promise is not defined
    at Object.<anonymous> (<path_to_project>/node_modules/bluebird/js/release/bluebird.js:3:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at repl:1:17
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
```
I get the same issue with `let`.

A simple workaround is to just use `var` instead of `const` or `let` so this isn't a big deal. I've also only noticed it in REPL, `const` still works fine in my actual app.

Even if you don't decide to fix the issue, an explanation would be much appreciated!

**Comment by benjamingr** [comment]
`const` defines scope locally per command in the REPL, there is nothing Bluebird can do.

This behavior is "by design" in Node. You're welcome to comment on the relevant issue there.

Thanks for reporting, and sorry there isn't anything we can do to help on our side!
