### ISSUE TITLE
Promise.all() doesn't allow for handling exceptions.

### ISSUE THREAD

**Issue by cha0s** [petkaantonov/bluebird#142]
I was expecting that `Promise.all(promises).done(...)` would suppress the 'possibly unhandled exception' emission. I may be misunderstanding how this machinery works! Here's a test case:

``` coffeescript

Promise = require 'bluebird'

promises = [
    new Promise (resolve, reject) -> resolve()
    new Promise (resolve, reject) -> reject new Error "ohnoes"
]

Promise.all(promises).done(
    -> console.log 'resolved!'
    (error) -> console.log error.stack
)
```

and the output:

```
$ coffee bluebird-test.coffee 
Error: ohnoes
  at promises (bluebird-test.coffee:12:14)
  at tryCatch2 (node_modules/bluebird/js/main/util.js:74:19)
  at Promise$_resolveFromResolver [as _resolveFromResolver] (node_modules/bluebird/js/main/promise.js:608:13)
  at new Promise (node_modules/bluebird/js/main/promise.js:88:37)
  at Object.<anonymous> (bluebird-test.coffee:10:6)
  at Object.<anonymous> (bluebird-test.coffee:2:1)
  at Module._compile (module.js:449:26)

Possibly unhandled Error: ohnoes
  at promises (bluebird-test.coffee:12:14)
  at tryCatch2 (node_modules/bluebird/js/main/util.js:74:19)
  at Promise$_resolveFromResolver [as _resolveFromResolver] (node_modules/bluebird/js/main/promise.js:608:13)
  at new Promise (node_modules/bluebird/js/main/promise.js:88:37)
  at Object.<anonymous> (bluebird-test.coffee:10:6)
  at Object.<anonymous> (bluebird-test.coffee:2:1)
  at Module._compile (module.js:449:26)
```

Oh, and in case coffeescript makes you sad, here's the emitted JS:

``` javascript
  var Promise, promises;

  Promise = require('bluebird');

  promises = [
    new Promise(function(resolve, reject) {
      return resolve();
    }), new Promise(function(resolve, reject) {
      return reject(new Error("ohnoes"));
    })
  ];

  Promise.all(promises).done(function() {
    return console.log('resolved!');
  }, function(error) {
    return console.log(error.stack);
  });
```

**Comment by LuisPerez64** [comment]
I'm unsure if people are still listening on this end, but I've somewhat run into this problem, and I am unsure of how JS Syntax proper it is, but may provide a workaround. Relatively new to JS, and extremely new to Promises.
`//Function that is called, returning the needed Promise
myAll = (val) => {
  return new Promise(function(resolve, reject) {
    if (val > 0)
      resolve((val + 1) * 5)
    else if (val < 0)
      reject(val * 2)
    else {
      var tmp = new Error("No work for 0");
      tmp.type = 'CustomError';
      reject(tmp);
    }
  })
}

// .catch using Promise.all 
/* 
  Extrending to the catch block handling, Attempting to call the catch block 
   explicitly will fail. They will reject on the first fail case, so attempting
    to throw from the function that is calling, will not work. 
    For the purpose of maintianing the try/catch syntax, the Exception case
    is wrapped around a resolve in itself, which then throws the Error, which 
    is caught by the needed Catch Block.

*/
Promise.all([myAll(1), myAll(0), myAll(-3)])
  .then(
    arr => {
      for (var ind = 0; ind < arr.length; ind++) {
        console.log(arr)
      };
    }, rej => {
      if (rej.type == 'CustomError')
        throw rej;
      console.log(arr)
    })
  .catch(e => {
    console.log("Catching Internal ", e.message)
  })`

**Comment by LuisPerez64** [comment]
Wrote a small bit of sample code to test out another possible way of handling this. Since the Promises force Sync/Async behaviors. I am new to the language, and was wondering if this was Syntactically correct, or if I am tripping over some major pitfalls by doing things under this assumption. Link to a JSFiddle [Promise.all Catch](https://jsfiddle.net/Luis_Perez64/eh4mope3/)
