### ISSUE TITLE
Importing promises in Angular 4

### ISSUE THREAD

**Issue by yvessabourin** [petkaantonov/bluebird#1423]
The Bluebird version is 3.5

I have developed a service to pick up a list of invoices from RabbitMQ using amqplib and bluebird.

When I use pure Javascript, that part works fine. I then migrated to Typescript with an ES5 target and got the invoice recuperation part to work alright, but the objective is to import the result into a component to display the information (or use dependency injection eventually). The import however was always showing the promise as undefined.

After noticing that bluebird was ignored by the compiler, I decided to remove bluebird in view of some conflicts with zone.js and use native promises instead, but the result was the same.

Using Gulp to target ES5 I have managed to make things work as expected with pure Javascript, but bringing the code back into Angular I always run into the same wall.

**Comment by benjamingr** [comment]
> After noticing that bluebird was ignored by the compiler, I decided to remove bluebird in view of some conflicts with zone.js and use native promises instead, but the result was the same.

So, it's clearly not a bluebird bug. I've imported promises in general, and bluebird in particular into Angular before - you have a problem with your configuration or what you're exporting from the file.

**Comment by yvessabourin** [comment]
benjamingr

What information would be useful for me to figure this out ?  From the debug information, even with bluebird removed I often see references to bluebird functions in the trace, why is that ?

**Comment by benjamingr** [comment]
@yvessabourin this is a webpack issue or a deployment issue - I realize this is frustrating - but it's not a bluebird bug or feature request. Every message you send here get read by 381 watchers - Try asking on webpack support channels.
