### ISSUE TITLE
Predicate functions appear to break catch blocks

### ISSUE THREAD

**Issue by jonnyt886** [petkaantonov/bluebird#1425]
Bluebird v3.5.0, Node v7.10.0

I have a function like this:

```
exports.is = (name) => {
    return function (e) {
        return e.name === name;
    };
};
```

And I use it as a predicate function, such as here:

```
doSomething()
.catch(is('MyCustomErrorType'), (e)=> {
   // handle error
})
.catch((e)=> {
    // global handler
});
```

The above works for `MyCustomErrorType` - i.e. if an exception with that `name` is thrown, the first catch block runs. However, the second catch-all block *never* runs if a different error type is thrown. The exception is simply lost - even though I have `monitoring` and `warnings` set to `true`:

```
var Promise = require('bluebird');
Promise.config({
    warnings: true,
    longStackTraces: true,
    //cancellation: true,
    monitoring: true
});
```

And I have an `unhandledRejection` handler registered, which never gets called.

Changing the catch block to read:

```
doSomething()
.catch({name:'MyCustomErrorType'}, (e)=> {
   // handle error
})
.catch((e)=> {
    // global handler
});
```

...and the code works as expected, the issue goes away.

**Comment by jonnyt886** [comment]
Actually, I have spotted a related issue; multiple filtered catches appear to break all filtered catches:

```
	return doSomething()
	.then((data)=> {
		// ...
	})
	.catch({name:'Error1'}, (e)=> {
		// ...
	})
	.catch({name:'Error2'}, (e)=> {
		// ...
	})
	.catch(genericErrorHandler);
```

With this code above, when `Error1` or `Error2` are thrown, the `genericErrorHandler` is called and my filtered catches are ignored!

My errors are declared in line with your documentation, namely...

```
exports.Error1 = function() {
    this.message = 'blah';
    this.name = "Error1";
    Error.captureStackTrace(this, exports.Error1);
}
exports.Error1.prototype = Object.create(Error.prototype);
exports.Error1.prototype.constructor = exports.Error1;
```

**Comment by benjamingr** [comment]
@petkaantonov

**Comment by jonnyt886** [comment]
I've only glanced at the bluebird sources for this, but does the fact I'm using `genericErrorHandler` in my last catch have anything to do with it? I simplified the code above for the sake of brevity but I call another function in order to get my generic error handler:

```
exports.doSomething = (req, res, next) => {
	return doSomethingElse()
	.then((data)=> {
		// ...
	})
	.catch({name:'RegistrationTypeFullError'}, (e)=> {
		// ...
	})
	.catch({name:'RegistrationTypeInvalidError'}, (e)=> {
		// ...
	})
	.catch(handleRequestError(req, res, next));
};
```

and `handleRequestError` looks a bit like this:

```
exports.handleRequestError = (req, res, next, opts) => {
	if (!opts) opts = {};

	return function(e) {
		// log error then do some logic based on opts
	};
};
```

I wonder whether bluebird thinks me generic error handler is in fact a predicate function and calls it errorneously?

**Comment by jonnyt886** [comment]
Any news on this issue?

**Comment by bttmly** [comment]
@jonnyt886 Can you provide a complete code sample plus the Node and Bluebird versions to exactly replicate this issue?

**Comment by jonnyt886** [comment]
Coming back to it I'm struggling to reproduce this, so I suggest you close. If I hit it again I'll reopen.
