### ISSUE TITLE
Bluebird browser support for IE11 is not clear

### ISSUE THREAD

**Issue by hagcin** [petkaantonov/bluebird#1429]
According to the website: http://bluebirdjs.com/docs/install.html

It is not clear to what extend bluebird is supporting IE11. According to chart at bottom of the page, it looks like it is failing tests for IE11. Does this mean Bluebird does not support IE 11 at all or not well? Any documentation on IE11 support would be helpful.

**Comment by benjamingr** [comment]
IE11 supports IE11, IE10, IE9, IE8, IE7, and even IE6.

It also runs on Netscape 7, seriously - try it (I did). 

The two failing tests in IE11 are about support for assimilating `Map`s (you can see this by clicking it. I think that IE11 ships with an implementation of `Map`s but a faulty one.

I'm going to leave this open until we fix these tests.
