### ISSUE TITLE
browser common js version has debug enabled by default

### ISSUE THREAD

**Issue by AVVS** [petkaantonov/bluebird#1435]
1) What version of bluebird is the issue happening on?

`3.5.0`

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

bundling with browserify, dist picked via browser field `js/browser/bluebird.js`

https://github.com/petkaantonov/bluebird/blob/v3.5.0/js/browser/bluebird.js#L687

Issue is that `__DEBUG__` global is set to `true` by default in this version, so unless it's explicitly disabled via other env vars, performance is insanely poor in IE11 due to long stack traces (at least thats one of the problems)

I didn't see anywhere that this is the documented behaviour, so I expect that to be a bug. If not - would be nice to have a clarification in the README about it

Thanks!

**Comment by benjamingr** [comment]
I think the installation instructions are pretty clear at http://bluebirdjs.com/docs/install.html - feel free to edit them and submit a PR if you think we can clarify them.

**Comment by AVVS** [comment]
Thing is, using these instructions with browserify:

```
var Promise = require('bluebird')

// ... do stuff
```

Leads to inclusion of https://github.com/petkaantonov/bluebird/blob/master/package.json#L71 (debug browser build) - therefore I'd suggest this is at least changed to minified version
