### ISSUE TITLE
Question about bluebird.join() with a then vs a callback

### ISSUE THREAD

**Issue by JemiloII** [petkaantonov/bluebird#1439]
So I noticed that I used `bluebird.join()` without a callback. Wondering if this is around to stay or don't use it! Going to be nuked. I didn't see it in the docs. If it's around to stay I'll make a pr.

```js
bluebird.join(bluebird.resolve(1), bluebird.resolve(2))
    .then(([a, b]) => {
        return a + b;
    });
```

Now the docs say we should to this.

```js
bluebird.join(bluebird.resolve(1), bluebird.resolve(2), (a, b) => {
    return a + b;
});
```

**Comment by benjamingr** [comment]
Don't use it :) Use the version that takes a function or coroutines.

**Comment by benjamingr** [comment]
It's deliberately undocumented

**Comment by JemiloII** [comment]
thanks
