### ISSUE TITLE
Promise.settle replacement

### ISSUE THREAD

**Issue by karlhadwen** [petkaantonov/bluebird#1440]
Just updated to Bluebird 3.5.0 and I've just noticed .settle() is now depreciated and replaced with .reflect(). From my understanding .reflect() isn't exactly the same.

How would I replace the following code to be up to date and use the replacement .reflect()?

Promise.settle([x, p]).then(function (results) {});

[x, p] are two promises.

I've taken the inner logic out.

**Comment by benjamingr** [comment]
Promise.all([x, p].map(x => x.reflect()))
