### ISSUE TITLE
where is the beginner's guide?

### ISSUE THREAD

**Issue by bi-kai** [petkaantonov/bluebird#1443]
There is nothing in http://bluebirdjs.com/docs/beginners-guide.html.
When uses `new Promise(..)` and `Promise.promisify(..)`, what's the different between them?
I need a guide to start bluebird, Thx.

**Comment by benjamingr** [comment]
`new Promise` is manual for promisification, promisify is automatic.


You can ask support questions on StackOverflow and see the doc segment on 'promisification'

**Comment by bi-kai** [comment]
@benjamingr `promisify` seems not working on `ldapjs`(a node module), does it has some conditions?
