### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by loyd** [petkaantonov/bluebird#1445]
1) What version of bluebird is the issue happening on?
3.5

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
nodejs 6.9.2

The following code demonstrates the problem:
```js
'use strict';

if (process.argv[2] === 'bluebird') {
    Promise = require('bluebird');
}

log('START');

(function () {
    const x = Promise.resolve(1);

    for (let i = 0; i < 1000000; ++i) x.then(() => {});
})();

log('AFTER');

setTimeout(() => {
    gc();
    log('AFTER GC');
}, 100);

function log(label) {
    console.log(process.memoryUsage().heapUsed, label);
}
```

When run it with native promises:
```sh
$ node --expose-gc case.js native
4156960 'START'
788023832 'AFTER'
4039296 'AFTER GC'
```

When run it with bluebird:
```sh
node --expose-gc case.js bluebird
5925024 'START'
295568448 'AFTER'
40371040 'AFTER GC'     # <== HERE
```

**Comment by benjamingr** [comment]
Are you running without NODE_ENV=production or with long stack traces turned on by any chance?

**Comment by loyd** [comment]
That's all.

`NODE_ENV=production` doesn't affect the result =(

**Comment by petkaantonov** [comment]
I don't see the problem, internal queue sizes are expanded because such huge amount of concurrent promises is anticipated. That's why the memory usage doesn't shrink back to "normal".

Maybe run the same thing 10 times and see if the memory goes always from 281 MB to 38.5MB?

**Comment by jdmarshall** [comment]
@loyd my read of the code is also that this is retained memory not leaked memory.

Short version:  
If the queue resized down on every settle() operation then you'd be resizing twice (one up and one down) every time there was a spike in promises.

Possibly more helpful version:
The benchmark you're doing has a high water mark of 1 million promises on the queue.  The queue doubles in size whenever space is exhausted (starts at 2^16), and never shrinks.  To avoid creating objects, bluebird typically uses 3 sequential slots for every promise.  So when i=699050, the array resizes to accommodate 2^22 entries.  The GC numbers you're reporting work out to 8 bytes per slot, and the way the queue is currently being managed, that sounds about right to me.

I believe there is room for improvement in the time and/or space performance of queue.js, and I intend to do some experiments and see if I can make a dent.  One of the ideas I have in mind might fix your issue, but I don't know yet if it'll pan out.  Benchmarks are hard, especially when you have to consider a bunch of browsers and node versions...
