### ISSUE TITLE
Promise is not assignable to PromiseLike

### ISSUE THREAD

**Issue by nathand8** [petkaantonov/bluebird#1453]
1) What version of bluebird is the issue happening on?
3.5.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node v8.4.0

3) Did this issue happen with earlier version of bluebird?
Not that I can tell (I'm, having difficulty downgrading bluebird to test)

I'm using bluebird in a protractor environment. Running the following code gives an error:

```typescript
        let packageNameUniqueCheckbox = this.element(this.packageNameUniqueCheckbox);
        let requirePackageNameCheckbox = this.element(this.requirePackageNameCheckbox);
        Promise.all([
            packageNameUniqueCheckbox.isSelected(),
            requirePackageNameCheckbox.isSelected()
        ]).then((boolArray) => {});
```

I get the following tsc compile error:

```
pageobjects/DocumentPreparationAndWorkflow.ts(48,21): error TS2345: Argument of type 'Promise<boolean>[]' is not assignable to parameter of type '(boolean | PromiseLike<boolean>)[] | PromiseLike<(boolean | PromiseLike<boolean>)[]>'.
  Type 'Promise<boolean>[]' is not assignable to type 'PromiseLike<(boolean | PromiseLike<boolean>)[]>'.
    Property 'then' is missing in type 'Promise<boolean>[]'.
```

I would expect `Promise.all` to be able to take `PromiseLike` types. Is this not the case?

Note: casting the promises like this fixes my issue (but it's ugly):

```
Promise.all([
    new Promise(packageNameUniqueCheckbox.isSelected().then)
])
```

**Comment by petkaantonov** [comment]
Yes, all promise methods work with PromiseLikes. Please post usage questions on StackOverflow

**Comment by nathand8** [comment]
Any idea why I was getting that error?
