### ISSUE TITLE
Promise bind method does not work with fat arrows

### ISSUE THREAD

**Issue by VilleMiekkoja** [petkaantonov/bluebird#1458]
Just wanted to point out this important aspect.

I think this should be mentioned in the docs somewhere. Using bind can be risky, as someone might easily change a function to use a fat arrow style.

**Comment by benjamingr** [comment]
`.bind` is used primarily in environments where arrow functions aren't available, with fat arrows there is no need to use it.

**Comment by benjamingr** [comment]
@VilleMiekkoja yes, because `this` is already bound to the lexical scope and not window/undefined. That's what .bind attempts to solve.

**Comment by VilleMiekkoja** [comment]
But the bind does not use the lexical scope. If you are doing asynchronous functions, you should not set variables to this. Because otherwise the next function call might change the value declared in this before the previous function has finished, and therefore alter the variable, which is surely not wanted. The bluebirds Promise.bind creates a scope that applies for the promise chain only, and per function call. The next call has a different scope.

So just using fat arrows does not solve the issue here.

**Comment by benjamingr** [comment]
@VilleMiekkoja let me clarify, fat arrows are a syntactic and semantic language feature - there is nothing bluebird can do about this. You can't change their `this`, they are _already bound_, think of these two as the same:

```js
var foo = function() { 
  console.log(this);
}.bind(5);
foo.call(6); // still 5
foo.call(10); // still 5, the `this` was already bound and cannot be rebound.
```

**Comment by VilleMiekkoja** [comment]
I understand that. My point was, that using bluebirds Promise.bind vs fat arrows is not the same thing at all.
Promise.bind works well if you do not use fat arrows. Then it creates a scope, that is not lexical. So claiming that you do not need the bind when you are using fat arrows is false. They are not the same thing, and you cannot achieve the same things with them. You won't achieve anything using the bind when you are using the fat arrows. But one might think bluebirds Promise.bind does some tricks underhood that it should work also with fat arrows.

Because the bind was not working with fat arrows, and because we didn't want give up using fat arrow functions, we abandoned bind, and made another, perhaps more uglier solution to the problem.

**Comment by benjamingr** [comment]
I'll try one more time:

 - `.bind` was added to bluebird to make working with `this` easier. I realize it can be used for different stuff.
 - arrow functions are already scoped to `this` from the lexical scope, so it's not really needed.
 - I realize you can use `bind` to carry arbitrary state, you can just use a closure for that instead if you want to use fat arrows.
 - You should be using coroutines or async functions anyway.
 - This is a JavaScript thing, not a bluebird thing, it's exactly the same with `Function.prototype.bind`: `var f = () => console.log(this); f.bind("Hello")(); // doesn't work`. This is how the JavaScript language works, simply put.

In general, your above code could be just:

```js
return loginApi(accessToken).get('userRole').then(x => x || "unauthorized");
```

**Comment by VilleMiekkoja** [comment]
The example I provided was silly, but I have no time nor will to give you a better one. I understand fully that the this inside a fat arrow function is from the lexical scope. Even if you can't do anything about it, I think you should warn people when using that Promise.bind method. This is different from your example in a way that Promise.bind is made by bluebird. That f.bind in your example is a regular javascript bind method.

**Comment by jiyuhan** [comment]
This is some stuff I have been working on while I have to use ```bind()```.

```this.setAsync = promisify(this.redis.set).bind(this.redis);```

I was trying to use a fat arrow but couldn't figure out a way.
