### ISSUE TITLE
Opinion Wanted: Reusing the same Promise instance "forever"

### ISSUE THREAD

**Issue by iamjochem** [petkaantonov/bluebird#1460]
hi there,

I have a module, it contains a couple of functions with Promise interface that perform API calls when needed but sometimes the function has no need to perform a call, in which case the return value is an "empty" resolved Promise, I was wondering if you see an conceptual or performance problems  in creating one "empty" resolved Promise in the module and repeated returning that:

e.g. this: 
```js
const noopPromise   = P.resolve(null);

module.exports = {
    // let's assume the real functions have conditional logic where by the `noopPromise` 
    // is only sometimes returned
    one : function() { return noopPromise; },
    two : function() { return noopPromise; },
};
```

instead of this:
```js
module.exports = {
    // let's assume the real functions have conditional logic where by the `noopPromise` 
    // is only sometimes returned
    one : function() { return P.resolve(null); },
    two : function() { return P.resolve(null); },
};
```

rgds,
Jochem

**Comment by benjamingr** [comment]
This is fine and I've done it many times. The only caveat is if the promise never resolves.

Also note this doesn't work with rejected promises well.

**Comment by iamjochem** [comment]
@benjamingr - thanks for clarifying, the rejected version `P.reject(null)` is not something I'm doing but I was wondering why that would be problematic?

**Comment by benjamingr** [comment]
- Don't reject with null (no stack trace)
 - Don't leave unhandled rejections around - that triggers warnings

**Comment by iamjochem** [comment]
ah of course, reject should always be with an `Error` instance.

thanks @benjamingr.
