### ISSUE TITLE
BlueBird does not interoperate with native Promises

### ISSUE THREAD

**Issue by mrstux** [petkaantonov/bluebird#1466]
Various native APIs return a native Promise object, for example ```fetch```, even after window.Promise is overridden by Bluebird.

This should succeed, assuming Fetch API is present:

```Promise.resolve(fetch(""))```

It does not work in Chrome if window.Promise is the BlueBird implementation.

```
Promise.resolve(fetch(""))
15:44:13.307 d {_c: Array(0), _a: Array(0), _s: 2, _d: true, _v: TypeError: Method Promise.prototype.then called on incompatible receiver function (a){this._c=[],thi…, …}
15:44:14.489 site-core.js:28 Unhandled promise rejection TypeError: Method Promise.prototype.then called on incompatible receiver function (a){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}
   at Function.then (<anonymous>)
   at site-core.js:28
   at MutationObserver.j (site-core.js:27)
```

This can be tested in the console, on a page where BlueBird has been used to override window.Promise

Of course, this is just a minimal repro of a much bigger issue.

Thankyou.

**Comment by petkaantonov** [comment]
Cannot repro
