### ISSUE TITLE
Promise.inSequence

### ISSUE THREAD

**Issue by philippefutureboy** [petkaantonov/bluebird#1470]
Hey!

I thought it would be interesting to have a Promise.inSequence function in the library.

Promise.inSequence is a function that would takes an array of functions and iterate through it sequentially. This would indeed be a wrapper to the Promise.reduce function.

You can find four implementations below; the first one uses a recursive, functional programming approach, whilst the second is a wrapper around the Promise.reduce function, the third is syntax sugar for a neater interface and the fourth provide lazy evaluation.

```js
import Promise from 'bluebird';

// Promise.inSequence :: [(a -> Promise *), ... ,(* -> Promise *)], a -> Promise *
Promise.inSequence = function inSequence([head, ...tail], arg = void 0){
  return tail.length ? head(arg).then((a) => Promise.inSequence(tail, a)) : head(arg);
};

// Promise.inSequence :: [(a -> Promise *), ... ,(* -> Promise *)], a -> Promise *
Promise.inSequence2 = function inSequence2(cbs, arg = void 0){
  return Promise.reduce(cbs, (val, next) => next(val), arg);
};

// Promise.inSequence :: [(a -> Promise *), ... ,(* -> Promise *)] -> (* -> Promise *)
Promise.inSequence3 = function inSequence3(...cbs){
  return (arg) => Promise.inSequence2(cbs, arg);
};

// Promise.inSequence :: [(a -> Promise *), ... ,(* -> Promise *)] -> (a -> Object) -> (* -> Promise *)
Promise.inSequence4 = function inSequence4(...cbs){
  return (arg) => { return { perform: () =>  #Promise.inSequence3(cbs, arg) }; }
};

return Promise;

// Examples

await Promise.inSequence([
  (cnf) => db.setConfig(cnf),
  () => db.beginTransaction(),
  () => db.run(query1),
  () => db.run(query2),
  () => db.endTransaction()
], config);

await Promise.inSequence2([
  (cnf) => db.setConfig(cnf),
  () => db.beginTransaction(),
  () => db.run(query1),
  () => db.run(query2),
  () => db.endTransaction()
], config);

await Promise.inSequence3(
  (cnf) => db.setConfig(cnf),
  () => db.beginTransaction(),
  () => db.run(query1),
  () => db.run(query2),
  () => db.endTransaction()
)(config);

const transaction = Promise.inSequence4(
  (cnf) => db.setConfig(cnf),
  () => db.beginTransaction(),
  () => db.run(query1),
  () => db.run(query2),
  () => db.endTransaction()
)(config);

transaction.perform();
```

Let me know what you think 😄  ✨ 

EDIT: Promise.pipe is also a valid name 🦄

**Comment by benjamingr** [comment]
This is `Promise.each`, 😃  Thanks for your suggestion though.

**Comment by philippefutureboy** [comment]
Ouh that's pretty! Thanks I didn't see this ❤️

**Comment by philippefutureboy** [comment]
Hmm, after running it in my application, it seems that this is not the same behaviour I expected;
Promise.each iterates through a series of already made Promises, whereas Promise.inSequence **sequentially runs functions that return promises and wait for them to resolve to move to the next one**.

The advantage of Promise.inSequence is that it is a syntactic sugar for a chain of .then.

**Comment by benjamingr** [comment]
Run the same function sequentially:

```js
const data = [1,2,3,4];
Promise.each(data, (item) => process(item, extra));
```

In JS, functions are just objects:

```js
const actions = [fn1,fn2,fn3,fn4];
Promise.each(actions, (action) => action());
```
