### ISSUE TITLE
Bluebird Always Defaults to Debug Config w/ Webpack

### ISSUE THREAD

**Issue by Cleod9** [petkaantonov/bluebird#1478]
1) What version of bluebird is the issue happening on?
Bluebird 3.5.1

2) What platform and version?
Windows 10 64-bit
Node v6.11.1
NPM 3.10.10

3) Did this issue happen with earlier version of bluebird?
At least as early as 3.4.x

When using Bluebird with Webpack 2.x/3.x, the JavaScript pulled in always comes from `node_modules/bluebird/js/browser/bluebird.js`. This originates from:
https://github.com/petkaantonov/bluebird/blob/0da7d15c7241857fc2b853393fb8dd1ab3bbd5d7/src/debuggability.js#L21
But in bluebird's unminified JS  `__DEBUG__` was replaced with a `true` when it was built. As a result, `debugging` will always default to `true` consequently enabling `longStackTraces` and other options which may be undesired by the developer.

A workaround for the problem is to explicitly pass debug options via `Promise.config()`, however if the developer does not specify all relevant options then they will all be enabled by default. A second workaround is to set the `BLUEBIRD_DEBUG` environment variable to `0`. Both of these solutions contradict the defaults specified in the Bluebird API docs: http://bluebirdjs.com/docs/api/promise.config.html#promise.config

Created a repo to demonstrate:
https://github.com/Cleod9/minimal-bluebird-webpack-debug-issue

**Comment by benjamingr** [comment]
Honestly I've run bluebird on dozens of frontend applications and I've always kept the stack traces turned on because at the client (not server) debugging issues in production was always a much bigger problem for me than performance.

**Comment by Cleod9** [comment]
Luckily there was a workaround for this, but do know that `longStackTraces` can be a real showstopper for games have specific memory requirements and a demanding frame-rate. We had been dealing with memory issues for years and sadly this was the biggest contributor. I personally feel this should be off by default, and it was apparently meant to be off, however unfortunately the binary for this package had `__DEBUG__` baked in as `true` :/

**Comment by benjamingr** [comment]
> Luckily there was a workaround for this

What do you mean? We explicitly allow you to build without long stack traces - what behavior would you prefer?

**Comment by Cleod9** [comment]
I created a [minimal use-case repo](https://github.com/Cleod9/minimal-bluebird-webpack-debug-issue) to demonstrate the problem late last year. Again to put it simply, the docs claim that all of these debug values default to false:

http://bluebirdjs.com/docs/api/promise.config.html#promise.config

However this is not the case due to the problem I demonstrate in the repo. You have to explicitly set them to false or the entire library executes in debug mode. I'm not going to push to change the defaults but I do think the docs should address this so that devs don't rule out Bluebird too quickly when investigating memory leaks

**Comment by benjamingr** [comment]
> Again to put it simply, the docs claim that all of these debug values default to false:

The first sentence after the function signature is:

> Configure long stack traces, warnings, monitoring and cancellation. Note that even though false is the default here, a development environment might be detected which automatically enables long stack traces and warnings.

I can make that bigger or bolder but I'm not sure there is anything else actionable on our behalf. I agree this behaviour is potentially confusing but the alternative is more confusing and bluebird has always opted for what we think helps users.

I apologize for your bad UX and I'm open to ways to fix it.

**Comment by benjamingr** [comment]
And I just noticed the issue is from 2017 😮 sorry for the late reply!

**Comment by Cleod9** [comment]
@benjamingr No worries! Thanks for taking the time to respond.

So I'm just curious, is a "debug environment" the default in my minimal use case? I disregarded text since I assumed that wasn't the case, so I might be missing something here with webpack or something

**Comment by Cleod9** [comment]
Even with `NODE_ENV=production`, output is still:

```
Debugging value: true
Done.
```
Remember that a `true` is baked into `node_modules/bluebird/js/browser/bluebird.js` which messes with the defaults. And that's the file that appears to be loaded when require()'d regardless of environment vars

**Comment by Matrosskin** [comment]
If you use bluebird in browser then no matter what value set in environment variable because it is not available inside browser. Also `util.env("BLUEBIRD_DEBUG")` always return `undefined` which is not equal to 0 so this:
```
var debugging = !!(util.env("BLUEBIRD_DEBUG") != 0 &&
                        (true ||
                         util.env("BLUEBIRD_DEBUG") ||
                         util.env("NODE_ENV") === "development"));
```
will always set `debugging` to true.
So we have debugging mode forever.

**Comment by Cleod9** [comment]
@Matrosskin Yup, that is absolutely correct. Have you tried my workaround by explicitly setting those environment variables via `Promise.config()`?

As with most open source repos I assume perhaps the contributors are waiting for us to submit a PR (which may or may not ever get merged judging by the current queue). Unfortunately I don't have the time to craft the proper solution myself, but as long as this ticket is open I hope others are able to at least find this thread

**Comment by Matrosskin** [comment]
@Cleod9 yes, I also set required options via `Promise.config()`. Today I just returned to the issue with hope to see the fix :)

**Comment by petkaantonov** [comment]
- node_modules/bluebird/js/browser/bluebird.js is the build for development
- node_modules/bluebird/js/browser/bluebird.min.js is the build for production

**Comment by Matrosskin** [comment]
@petkaantonov what does your message should mean?

**Comment by petkaantonov** [comment]
browser/bluebird.js has always debug values, this is intended as you wouldn't use non minified file in production

browser/bluebird.min.js has debug values disabled because you use minified file in production

I don't know how to make webpack use different file, the browser field in package.json only allows 1 file to be chosen, and it is currently the debug file (browser/bluebird.js).

**Comment by Matrosskin** [comment]
I see. But such configuration confuse me. Possibly it is just my own opinion - I expect that the browser/bluebird.js and browser/bluebird.min.js have same behavior. I expect that the min version is just smaller and less readable. So I expect that I can work with any file in same way. But, with bluebird it was wrong assumption which cause a additional time for investigation of different behavior.
Also, if we use webpack then it often mean that we use own config to minify script, so (again my personal opinion) I would rather use not minified version - it allow to debug every script during developing the own app, and in production it still will be minified.
Also, as you mentioned, in package.json can be configured only one script - as I understand it means I need some additional logic in webpack to use min verssion instead of version from package.json, is not it? So the environment and/or configuration of of my project to develop and to build for production will be a little different - it does not look fine for me.
Sorry if wrong somewhere, I have not much practice. Can you help me if I miss something?

**Comment by petkaantonov** [comment]
The differences between the browser files is documented here:http://bluebirdjs.com/docs/install.html#browser-installation

For webpack: http://bluebirdjs.com/docs/install.html#browserify-and-webpack The instructions imply usage of Promise.config is needed

**Comment by petkaantonov** [comment]
I updated the http://bluebirdjs.com/docs/install.html#browserify-and-webpack docs to make it more clear.

**Comment by petkaantonov** [comment]
Also updated http://bluebirdjs.com/docs/api/promise.config.html#promise.config

**Comment by Matrosskin** [comment]
Awesome, thank you!

**Comment by Cleod9** [comment]
The documentation update is much appreciated, thanks for the follow up!
