### ISSUE TITLE
error domain's don't always capture exceptions thrown from onPossiblyUnhandledRejection

### ISSUE THREAD

**Issue by iarna** [petkaantonov/bluebird#148]
Specifically, the following works:

```
"use strict";
var Promise = require('bluebird');             
Promise.onPossiblyUnhandledRejection(function(error,promise) { throw error });

require('domain').create()
  .on('error', function(E){ console.log("ok trapped error "+E.message) })
  .run(function() {
      var P = new Promise(function(resolve,reject){ reject(new Error('boom')) });
  });

Promise.fulfilled(23).then(function(V){ console.log("#",V) });
```

The above outputs the following, as expected:

```
#23
ok trapped error boom
```

However, if I rearrange the promises it fails:

```
"use strict";
var Promise = require('bluebird');             
Promise.onPossiblyUnhandledRejection(function(error,promise) { throw error });

Promise.fulfilled(23).then(function(V){ console.log("#",V) });

require('domain').create()
  .on('error', function(E){ console.log("ok trapped error "+E.message) })
  .run(function() {
      var P = new Promise(function(resolve,reject){ reject(new Error('boom')) });
  });
```

And outputs:

```
#23

bluebird/js/main/async.js:79
            throw res.e;
                     ^
Error: boom
    at bluebird/domain-failure.js:10:60
    at new Promise (bluebird/js/main/promise.js:88:37)
    at bluebird/domain-blue.js:10:15
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at Object.<anonymous> (bluebird/domain-failure.js:9:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
From previous event:
    at new Promise (bluebird/js/main/promise.js:88:37)
```

Relates to #124

**Comment by ORESoftware** [comment]
promises don't catch this TMK

```js
aPromise().then(function(){
   setImmediate(function(){
       throw new Error("Won't get caught by promise");
    });
}).catch(function(err){
 // no
});
```

that's why we need domains, or domain-like functionality

**Comment by benjamingr** [comment]
@ORESoftware that's because you've used `setImmediate`. In order to enjoy the throw-safety of promises you need to promisify all your APIs. If that `setImmediate` becomes a `Promise.delay` you can throw in it and things will work like you expect.

Also see https://github.com/petkaantonov/bluebird/issues/51 

Much like anyone can call `process.abort` in their code even if you use domains - there are always assumptions about how the code is used.

**Comment by ORESoftware** [comment]
I hear from @benjamingr that process.on('unhandledRejection') can take care of this? or no?

**Comment by benjamingr** [comment]
@ORESoftware I _am_ @benjamingr :) 

`unhandledRejection` would catch cases where a _Promise_ rejected and no one handled it in a reasonable amount of time. If you throw inside a `setImmediate` all bets are off - it creates really confusing cases and it's part of why domains are deprecated. 

```
aPromise().then(function(){
   return Promise.delay(0).then(function(){
       throw new Error("Won't get caught by promise");
    });
}).catch(function(err){
 // yes
});
```

**Comment by ORESoftware** [comment]
hmmmm, but Promises don't allow us to create (pseudo) async code...setTimeout, setImmediate, process.nextTick are what we need to do that, promises don't offer a substitute for those..so? We need process.nextTick and setImmediate, and we damn well may need them inside a promise chain.

also, as I mentioned, I am writing a test library, and I can't control the input (users will write code that may have setImmedate inside a promise etc). I believe you are very smart and I wish you would quit knocking domains until someone finds a reasonable alternative ;)

**Comment by petkaantonov** [comment]
you can wrap setimmediate as promise.immediate same way as delay wraps settimeout

**Comment by benjamingr** [comment]
@ORESoftware they most certainly do.

### `nextTick`

```js
Promise.resolve().then(() => {
   // this code always runs in the nextTick, promises guard against Zalgo by 
   // always running the code when only platform code remained
});
```

### setTimeout

```js
Promise.delay(100).then(() => {
   // after 100ms, uses timer internally
});
```

**Comment by ORESoftware** [comment]
i see, hummity hum hums

**Comment by ORESoftware** [comment]
what is Zalgo btw? Is that a real thing

**Comment by benjamingr** [comment]
@ORESoftware http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by ORESoftware** [comment]
Gotcha thanks, even after reading Isaac's post I am still not sure what
Zalgo is but sounds a bit like Pandora's Boxxx
