### ISSUE TITLE
Bizarre behavior with p-throttle and Bluebird

### ISSUE THREAD

**Issue by kaatt** [petkaantonov/bluebird#1480]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node v8.9.0 and v9.1.0 on macOS and Linux.

3) Did this issue happen with earlier version of bluebird?
Yes afaik.

When the global Promise object is replaced with bluebird, the async function mysteriously never resolves in the below code:

```
global.Promise = require('bluebird')
const pThrottle = require('p-throttle')
const PCancelable = require('p-cancelable')
const got = url => new PCancelable((onCancel, resolve, reject) => resolve({ headers: { date: new Date() }}))

const throttled = pThrottle(got, 1, 1000)

async function main() {
  console.log('Start')
  const { headers } = await throttled('http://httpbin.org/response-headers')
  console.log(headers.date)
  console.log('End')
  return 'Returned'
}

main().then(console.log).catch(console.error)
```

When Promise is patched, the process just exits with code `0` and even `~End~` is not logged to the console.
When Promise isn't patched, or when pThrottle isn't used (just got), then it works as it should.

Prev issue: https://github.com/sindresorhus/p-throttle/issues/4

**Comment by benjamingr** [comment]
Don't replace `global.promise` with Bluebird (in general) - just import bluebird as promise. This might be something about how async functions work with node.

Also, there is no point in using `p-throttle` with bluebird since you could just use `.map` in this case from bluebird (which takes a concurrency parameter).

Can you file an issue against Node.js?

**Comment by kaatt** [comment]
`p-throttle` has more options than `bluebird.map`, like rate limiting a promise to once every second. 

Filed against Node.js: https://github.com/nodejs/node/issues/17278

**Comment by kaatt** [comment]
So the issue might be caused because of this line: https://github.com/sindresorhus/p-cancelable/blob/47b502789c1ef55319cfad3991782f373c0e1e55/index.js#L74

Should I create an issue for https://github.com/sindresorhus/p-cancelable or does this need fixing in bluebird?

**Comment by benjamingr** [comment]
@kaatt this needs fixing in Node, probably in V8. If you can create a more minimal sample that would be a great help.

**Comment by kaatt** [comment]
Minimal repro (thanks to https://github.com/nodejs/node/issues/17278#issuecomment-346765943):
```
global.Promise = require('bluebird')

function main() {
  const p = Object.create(Promise.prototype)
  const prom = Object.assign(p, {
    then: resolve => resolve('done')
  })
  return new Promise(resolve => resolve(prom))
}
main().then(console.log).catch(console.error)
```
Not patching `global.Promise` makes it work.

**Comment by kaatt** [comment]
```
// global.Promise = require('bluebird')
function main() {
  const p = Object.create(Promise.prototype)
  const prom = Object.assign(p)
  return new Promise(resolve => resolve(prom))
}
main().then(console.log).catch(console.error)
```
shows this error:
```
TypeError: Method Promise.prototype.then called on incompatible receiver #<Promise>
    at Promise.then (<anonymous>)
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```
while patching Promise with Bluebird doesn't.

**Comment by benjamingr** [comment]
Yeah that makes sense, bluebird does subclassing differently for performance reasons.
