### ISSUE TITLE
Question: Combine Promise.join and Promise.spread

### ISSUE THREAD

**Issue by ybonnefond** [petkaantonov/bluebird#1482]
This code seems to work properly:

```javascript
Promise
  .join(promise1, promise2)
  .spread((p1Result, p2Result) => {
    // ...
  });
```

Is it safe to use as this is not documented?

**Comment by benjamingr** [comment]
The behavior of `.join` without a function is deprecated and should not be used. If you can use arrow functions you can just do:

```js
Promise.join(promise1, promise2, ([p1Result, p2Result]) => {
  // ...
});
```
