### ISSUE TITLE
Timers docs has nothing

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [petkaantonov/bluebird#1485]
http://bluebirdjs.com/docs/api/timers.html

Does not have any content relating to the methods that are under its section in the API Reference

### API Reference
- Timers
    - delay
    - timeout

### Timers Doc Page
```
Timers
Methods to delay and time promises out.
```

**Comment by benjamingr** [comment]
That's a description, if you click `delay` or `timeout` it will tell you what those do.

**Comment by BebeSparkelSparkel** [comment]
It is a description but there is no link to delay or timeout
