### ISSUE TITLE
A fulfilled promise if *then*ed becomes unfulfilled

### ISSUE THREAD

**Issue by jvenki** [petkaantonov/bluebird#1497]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Google Chrome 60.0.3112.78

3) Did this issue happen with earlier version of bluebird?
NA

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

In my application, there is a client side data source which fetches data from server.  Therefore I am using Promise. However, sometimes the data can get cached and therefore there is no async nature. However, to keep things simple, even if it is returning locally cached data, it returns it as a resolve promise. Now if I do a synchronous inspection, it says that the promise is Fulfilled which is correct. If however, it passes through a **then**, it becomes unfulfilled.

A Simple Example 

```console.log(Promise.resolve(true).isFulfilled())```
--> TRUE

```console.log(Promise.resolve(true).then((v) => v).isFulfilled())```
--> FALSE

I understand that there is a chaining of promises. But if the **then** is not asynchronous, why is the Promise becoming unfulfilled?

**Comment by benjamingr** [comment]
This is expected behavior and is required by the specification.

The promise isn't becoming unfulfilled, `then` creates a _new_ promise - the function runs _after a microtick_ and so the promise is actually resolved later. You can see this behavior by doing:

```js
Promise.resolve().then(() => console.log("now fulfilled"));
console.log("this runs first");
```

Thanks for reporting a suspected bug.
