### ISSUE TITLE
Use Bluebird promises by default in browser

### ISSUE THREAD

**Issue by kirillgroshkov** [petkaantonov/bluebird#1506]
I apologize if this was answered maybe 100 times before, but I wasn't able to find a good answer for this.

I know how to do it in Node environment (`global.Promise = ...`), but how to do it for the browser?

What I want to achieve is to not import (`import * as Promise from 'bluebird') bluebird in every file, but instead do it once.

**Comment by benjamingr** [comment]
```
window.Promise = require('bluebird');
```

That won't work for `async` functions without a babel transform though.
