### ISSUE TITLE
Bluebird throwing massive amount of errors

### ISSUE THREAD

**Issue by danhab99** [petkaantonov/bluebird#1511]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?

3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

I guess Atom?

3) Did this issue happen with earlier version of bluebird?

IDK why it's here

---

I don't understand why but I get 100s of errors flooding [my project](https://github.com/danhab99/Reddit-For-atom) from this plugin and I suspect it might be causing me [other problems](https://github.com/danhab99/Reddit-For-atom/issues/1).

**Comment by benjamingr** [comment]
In case that was implied, we're not going to go over your code in your project and debug it for you. You're welcome to post support questions in StackOverflow as CONTRIBUTING.md specifies - the issue tracker is for bug reports and feature requests (every time someone posts here 380 people get pinged).
