### ISSUE TITLE
TypeError when a filter in catch handler is not a function

### ISSUE THREAD

**Issue by marijaselakovic** [petkaantonov/bluebird#1517]
1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js v8.5, Ubuntu 16.04.4

3) Did this issue happen with earlier version of bluebird?
Not sure

If a non-function value is passed as a filter to catch I get the following error: TypeError: Cannot read property 'apply' of undefined
The following code demonstrates this:

```
var p2 = Promise.reject(10);
p2.catch(function(){return true},undefined)
```
You should consider adding a type check on arguments passed to catch.

**Comment by benjamingr** [comment]
@marijaselakovic honestly I just use TS which catches that - a PR is welcome I believe though.

cc @petkaantonov

**Comment by marijaselakovic** [comment]
Sure, PR [1518](https://github.com/petkaantonov/bluebird/pull/1518)

**Comment by marijaselakovic** [comment]
Yes, I added the test, which would fail in both versions, but you can see the difference in error messages. Not sure if thiat's enough
