### ISSUE TITLE
Promise with asCallback does not capture errors from .tap

### ISSUE THREAD

**Issue by Nokel81** [petkaantonov/bluebird#1519]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node 4.8.6 Node 8.11.1

3) Did this issue happen with earlier version of bluebird?
don't know

MWE:
```js
const Promise = require('bluebird');

const array = [
    {a: 1},
    {a: 2},
    {a: 3},
    {a: 4}
];

function a(e, c)
{
    if (e)
    {
        return console.log("Error: " + e.toString());
    }

    console.log("done");
}

process.on('unhandledRejection', function ()
{
    console.log('unhandledRejection');
})

Promise.each(array, val => Promise.resolve(val)
    .tap(console.log)
    .tap(_ => Promise.reject(new Error('sl')))
    .asCallback(a)
);
```

The output to this is:
```
{ a: 1 }
Error: Error: sl
unhandledRejection
```

But if the final statement is:
```js
Promise.each(array, val => Promise.resolve(val)
    .tap(console.log)
    .tap(_ => Promise.reject(new Error('sl')))
    .then(_ => a(null, _))
    .catch(e => a(e))
);
```

the output is:
```
{ a: 1 }
Error: Error: sl
{ a: 2 }
Error: Error: sl
{ a: 3 }
Error: Error: sl
{ a: 4 }
Error: Error: sl
```

**Comment by benjamingr** [comment]
This is working as intended.

After you log `{ a: 1 }` you `Promise.reject` in the `tap` which creates a rejected promise which propagates to the `each`.

That causes the `each` to stop and return a rejected promise. You don't `catch` on it which causes the unhandled rejection.
