### ISSUE TITLE
Stacked promises break when length is bigger than 65533

### ISSUE THREAD

**Issue by marcj** [petkaantonov/bluebird#1527]
1) What version of bluebird is the issue happening on?

3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node: 9.11.1
OS: darwin x64

3) Did this issue happen with earlier version of bluebird?

With bluebird 2.11.0 breaks when stack is greater than 131068.

Example code

```javascript
global.Promise = require('bluebird');

let lastPromise;

async function doIt(id) {
    while (lastPromise) {
        await lastPromise;
    }

    const wait = 1;
    console.log('doIt', id, 'DOING', wait, 'ms');

    lastPromise = new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('doIt', id, 'DONE');
            lastPromise = null;
            resolve();
        }, wait)
    });
}

//for bluebird v2 use stackSize=131068;
let stackSize = 65532;
for (let i = 0; i < stackSize; i++) {
    doIt(i);
}

console.log('waiting now');
```

Given `let stackSize = 1000` then everything is working as expected, output would be:

```
doIt 0 DOING 1 ms
waiting now
doIt 0 DONE
doIt 1 DOING 1 ms
doIt 1 DONE
doIt 2 DOING 1 ms
doIt 2 DONE
doIt 3 DOING 1 ms
doIt 3 DONE
doIt 4 DOING 1 ms
doIt 4 DONE
doIt 5 DOING 1 ms
doIt 5 DONE
doIt 6 DOING 1 ms
doIt 6 DONE
```

but when you use stackSize >= `65533` then all promises created after the first and before the 65533th call will simply be destroyed and never used. Output when `stackSize = 65533`:

```
doIt 0 DOING 1 ms
waiting now
doIt 0 DONE
doIt 65532 DOING 1 ms
doIt 65532 DONE
//end of script
```

In bluebird 2 this behaviour starts to happen when stackSize>=131068.

I'm not sure if this is a bug or known limitation. Also, if you know a better way to handle such functionality like the `doIt` function has (blocking multiple calls and stacking them up in a queue) I'd love to hear it.

Btw, using the native Promises of Node/v8 is extremely slow when you hit 8000 stack size, this is why I want to use Bluebird, however it still works when the stack is bigger than 65533.

**Comment by benjamingr** [comment]
Thanks for the report,

This is a known limitation if I remember correctly. Can you share a little about what your code actually does in real life?

I can get this to the V8 team pretty quickly and they might be able to address the limitation on Chrome's end.

I think bluebird can be modified so that when cancellation (for example) is turned off then the number would be bigger than `2 << 15`.

By the way, this is because the [bitfield structure](https://github.com/petkaantonov/bluebird/blob/c5b3ef3c74c36d0d1fe80c236849e6df3e887efa/src/constants.js#L30-L33) reserves 16 bits for promises to follow:

```
//Layout for ._bitField
//[RR]RO GWFN CTBH IUDE LLLL LLLL LLLL LLLL
//[RR] = [Reserved] (Both bits are either on or off to represent
//                    1 bit due to 31-bit integers in 32-bit v8)
//R = [Reserved]
//O = returnedNonUndefined
//G = isAsyncGuaranteed
//W = isFollowing (The promise that is being followed is not stored explicitly)
//F = isFulfilled
//N = isRejected
//C = willBeCancelled
//T = isFinal (used for .done() implementation)
//B = isBound
//I = isRejectionIgnored
//H = isRejectionUnhandled
//U = isUnhanldedRejectionNotified
//D = isDisposable
//E = isCancelled
//L = Length, 16 bit unsigned
```

Remove isCancelled and isDisposable and the number gets up to 262144

**Comment by benjamingr** [comment]
It would be possible to fork bluebird and modify this - it would not require a lot of changes - but you're the first person to ask for this in 5 years so I'm not sure we're inclined to make the changes for it - sorry!

**Comment by benjamingr** [comment]
PR upping the limit when cancellation is not turned on - welcome

**Comment by samson-sham** [comment]
> It would be possible to fork bluebird and modify this - it would not require a lot of changes - but you're the first person to ask for this in 5 years so I'm not sure we're inclined to make the changes for it - sorry!

I guess this is why:
> With bluebird 2.11.0 breaks when stack is greater than 131068.

**Comment by samson-sham** [comment]
@marcj 
I'm not sure the actual use-case however I suspect this is a mis-use of promise...where you want 65533 promises racing for a single point of resources, then you may chain them instead of using defer() methodology.

I have rewritten the script as follow:
```
const Bluebird = require('bluebird');

function doIt(id = 0) {
    return new Bluebird((resolve, reject) => {
        setTimeout(() => {
            console.log('doIt', id, 'DONE');
            resolve();
        }, 1)
    });
}

let lastPromise;

let stackSize = 65533;
for (let i = 0; i < stackSize; i++) {
    lastPromise = Bluebird.resolve(lastPromise).then(() => {
        return doIt(i);
    });
}
```

**Comment by petkaantonov** [comment]
Regardless of promise implementation stacking parallel listeners on single promise is a bad idea.

Use

    if (lastPromise) {
        lastPromise = lastPromise.then();
        await lastPromise;
    }

Instead.
