### ISSUE TITLE
Catch type filter not catching custom error thrown from async function

### ISSUE THREAD

**Issue by acinader** [petkaantonov/bluebird#1532]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node v8.11.1

3) Did this issue happen with earlier version of bluebird?
I do not know.

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Catch filter is not working as expected with errors thrown in async functions.

```
const myFunc = async function myFunc() {
    throw new CustomError();
};

 myFunc()
  .then(() => done('should not be here')) // ✔
  .catch(CustomError, function () {
      // this should get called, but doesn't ✘
      done();
  })
  .catch((e) => {
      // this shouldn't get called and doesn't. ✔
      done('should not be in the generic catch.');
  })
  .then(() => {
      // not clear to me why we get here. ✘
      done('why would this get called since filtered didn\'t');
  });
```

Here is a branch with a unit tests that pass for throwing the CustomError and catching it in a generic catch, but fails when catching with a class filter: https://github.com/petkaantonov/bluebird/compare/master...acinader:async-catch-filter

**Comment by benjamingr** [comment]
async function use native promises and not bluebird - You'd want to wrap that with `Promise.method` to use bluebird methods on it.
