### ISSUE TITLE
Add stack trace for warnings

### ISSUE THREAD

**Issue by jehy** [petkaantonov/bluebird#1552]
> What version of bluebird is the issue happening on?

Bluebird 3.5.2
> What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node 8
> Did this issue happen with earlier version of bluebird?

Yes

**Problem:**
Bluebird warnings have no stack trace so it's very difficult to see where warning actually happened.
For example, see https://github.com/zkat/cipm/issues/58

There is a problem in code but I could only see
> (node:21662) Warning: .then() only accepts functions but was passed: [object Object]

Adding stack trace there would be very helpful.

**Comment by benjamingr** [comment]
Not an excuse - but IIRC `--trace-warnings` shows it (it's a Node thing - not a bluebird thing afaik)

**Comment by jehy** [comment]
> Not an excuse - but IIRC `--trace-warnings` shows it (it's a Node thing - not a bluebird thing afaik)

Thanks, never knew about this feature! However, there are many cases when it is difficult to pass a flag (complex startup scripts, npm and other command line tools, for example).

**Comment by benjamingr** [comment]
Of course, it was never the intention to hide this unless warnings are traced. (I'm not even sure we do - just a hunch).

**Comment by petkaantonov** [comment]
There should be stack trace for warnings, even long stack traces.

**Comment by petkaantonov** [comment]
You should see stack traces for warnings, the warning itself is an error object with its own stack trace.
