### ISSUE TITLE
Doc not rendered properly

### ISSUE THREAD

**Issue by DEVAbhinav** [petkaantonov/bluebird#1556]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
On doc at [url ](http://bluebirdjs.com/docs/api/promise.each.html)
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

3) Did this issue happen with earlier version of bluebird?
No idea about that. I guess its a rendering issue that could be solved by markdown changes.
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

The official doc was not rendering properly on chrome. the code block was rendered as text. from line 43 ownward. 

I would be happy to contribute to this project, but i need to know how to resolve this.

**Comment by benjamingr** [comment]
Thanks! Want to make a PR? 

The bug is in this file where a ``` block is used instead of four spaces indentation

**Comment by DEVAbhinav** [comment]
Sure. thanks @benjamingr

**Comment by benjamingr** [comment]
@DEVAbhinav the bug is because github supports ``` formatting for code quotes but our static site generator does not. If you change the ```s for multiline code comments with an indent it'll work :)

**Comment by DEVAbhinav** [comment]
I am unable to preview my changes...
