### ISSUE TITLE
thenable callback should be run asynchronously

### ISSUE THREAD

**Issue by Berzeg** [petkaantonov/bluebird#1558]
1) What version of bluebird is the issue happening on?

3.5.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Node.js 10.11.0

3) Did this issue happen with earlier version of bluebird?

Tested on 3.4.7 and 2.11.0 ... Still happens there

If you resolve a promise from a thenable with the Node.js's built-in Promise then the thenable callback would not be called immediately:

```
testA = () => {
  Promise.resolve({then: () => console.log('inside thenable')});
  console.log('outside thenable');
};

testA();
// 'outside thenable'
// 'inside thenable
```

However, if you do the same, but using bluebird's Promise then the thenable callback would be called synchronously:

```
testB = () => {
  require('bluebird').Promise.resolve({then: () => console.log('inside thenable')});
  console.log('outside thenable');
};

testB();
// 'inside thenable
// 'outside thenable'
``` 

The thenable callback should be scheduled as if it were a `.then()` callback (i.e. `Promise.resolve({then: cb})` has the same run order as `Promise.resolve(undefined).then(cb)`).

**Comment by benjamingr** [comment]
😮

**Comment by petkaantonov** [comment]
Bluebird follows the [promises/a+](https://promisesaplus.com/) standard, not ES6 spec.
