### ISSUE TITLE
Cannot read property `node` of undefined

### ISSUE THREAD

**Issue by jefflewis** [petkaantonov/bluebird#1563]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
`3.5.2`

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
`React Native 0.57`

3) Did this issue happen with earlier version of bluebird?
Unknown

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

When starting my React Native app with remote debugging on, I get this error from Bluebird as it attempts to check the process' version number: 

>bluebird.js:5637:35
```
var version = process.versions.node.split(".").map(Number);
```

When I disable remote debugging, the app works as expected. Remove the package that depends on Bluebird also re-enables the remote debugging feature.

**Comment by mlostekk** [comment]
Same here!

**Comment by mlostekk** [comment]
Here is the fix for this

https://github.com/petkaantonov/bluebird/pull/1576

**Comment by rafaismyname** [comment]
Hey @mlostekk i'm facing the same issues trying to debug RN trough VSCode :(

How did you managed to solve this issue?

Best!

**Comment by mlostekk** [comment]
See this commit.

https://github.com/petkaantonov/bluebird/pull/1576/commits/28683161d1fcb21524942e6ae44a2e2cfdfc6074

in the release from NPM you have to adjust this part in the file `node_modules/js/browser/bluebird.js` near the very end (in my case line number 5636)

**Comment by rafaismyname** [comment]
@mlostekk thank you so much!

it's funny (and scary) that the only solution for this now is editing the node_module...

what would be the library using the outdated version of bluebird resulting into this exception? maybe we could find it and pull request the fix for it for a proper solution...

thx!!!

**Comment by mlostekk** [comment]
Well, its already fixed, but @petkaantonov needs to trigger a release and seem to be not available at the moment
