### ISSUE TITLE
filtered catch broken with typescript 2.0, 3.0

### ISSUE THREAD

**Issue by renewooller** [petkaantonov/bluebird#1574]
I realise that this could be considered "typescript's problem", however I just thought it'd be handy to let you know it's happening in case you want to support it. 

1) What version of bluebird is the issue happening on?
3.2.5

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
ts-node v7.0.1
node v8.9.4
typescript v3.2.2

3) Did this issue happen with earlier version of bluebird?
No

See https://stackoverflow.com/questions/41445829/bluebirds-filtered-catch-broken-when-js-is-generated-by-typescript-2-0
And
https://stackoverflow.com/questions/38927394/catch-error-type-in-bluebird-not-working

For a nice summary.

**Comment by benjamingr** [comment]
I'm not sure what's the action item required of bluebird here - this looks like a d.ts fix needed.
