### ISSUE TITLE
"promise was created in a handler" warning not being reported

### ISSUE THREAD

**Issue by itaisteinherz** [petkaantonov/bluebird#1575]
1) _What version of bluebird is the issue happening on?_
Bluebird v3.5.3.

2) _What platform and version? (For example Node.js 0.12 or Google Chrome 32)_
Node v9.7.1 (running on Linux), as well as Node v11.0.0 (running on macOS).

3) _Did this issue happen with earlier version of bluebird?_
Yes, it happens on v3.4.0 as well.

When running [the example in Bluebird's docs for code that should generate the "promise was created in a handler but was not returned" warning](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it), no warning is being emitted to the console by Bluebird. The code I used can be found in [this REPL](https://repl.it/repls/ConsiderateWildLocations).

**Comment by petkaantonov** [comment]
The REPL is very bugged, it works fine.
