### ISSUE TITLE
then-like operator without result promise

### ISSUE THREAD

**Issue by awto** [petkaantonov/bluebird#1578]
I have an async/generator functions transpiler. Comparing to the native implementation and regenerator it adds abstract API, implicit parallelism, persistent state and it may be faster. Also, it can utilize Bluebird Promises instead of the native ones.

To make its generated code faster I need another low-level operator which may probably never be used by developers directly.

The new operator is the same as `then` but it doesn't create and return the resulting Promise - only calls corresponding callbacks on the object's Promise is settled. 

This way we avoid creating a long-living object and so optimizing memory usage.

I can add this myself, however, I need to know if there are chances this is accepted.

**Comment by benjamingr** [comment]
We have `Promise#_then` for internal things and you can use that. 

It has a 5th paramter - if you pass that it in does not create a promise. You can look at the code at `promise.js`

Also note that `then` that does not return a promise is basically a much simpler construct and I'd consider rolling out a similar-to-promises-but-not-quite construct that does not chain.
