### ISSUE TITLE
Feature Request: Add Promise.tryAll

### ISSUE THREAD

**Issue by matthewadams** [petkaantonov/bluebird#1587]
Add a convenient static method to `Promise` called `tryAll` that _always_ resolves, returning, for each `Promise`, the `Promise`'s resolved value or, if rejected, the `Promise`'s rejection reason.

Here's an admittedly-oversimplified ES6 implementation to illustrate the desired behavior:
```
Promise.tryAll = promises => Promise.all(promises.map(p => p.then(value => value, error => error)))
```

**Comment by benjamingr** [comment]
I think you're looking for `Promise.reflect` or `Promise.settle` :)

**Comment by matthewadams** [comment]
Oops.  Righty-o, boss.
