### ISSUE TITLE
Proposal: Promise.fromEvent

### ISSUE THREAD

**Issue by leontastic** [petkaantonov/bluebird#1588]
I frequently find myself writing the following pattern:

```js
const eventPromise = new Promise(resolve => someEventEmitter.once('my-event', resolve))

eventPromise.then(event => {
  // do something with event
})
```

However, not all event emitters in the wild provide a `once` handler. In these cases, it's necessary to write extra logic to dispose the event handler, to avoid memory leaks:

```js
const eventPromise = new Promise(resolve => {
  const resolveAndDispose = event => {
    someEventEmitter.removeEventListener('my-event', resolveEvent)
    resolve(event)
  }
  someEventEmitter.addEventListener('my-event', resolveAndDispose)
}

eventPromise.then(event => {
  // do something with event
})
```

A helper function which automagically creates these types of promises for me would be nice, similar to [RxJS `fromEvent`](https://www.learnrxjs.io/operators/creation/fromevent.html):

```js
const eventPromise = Promise.fromEvent(emitter, 'my-event')

eventPromise.then(event => {
  // do something with event
})
```

Alternatively, a promisification method which allows me to start listening at anytime in the future:

```js
const resolveNextEvent = Promise.promisifyEvent(emitter, 'my-event')

emitter.emit('my-event', { data: 'foo' })

resolveNextEvent().then(event => {
  // event.data === 'bar'
})

emitter.emit('my-event', { data: 'bar' })
```

IMO converting event emitter event handlers into Promises is a very common use case, Bluebird would become more valuable if it had some utility methods like the ones I suggested to handle these cases.

**Comment by benjamingr** [comment]
We recently shipped `EventEmitter.once` (static) that does this in Node.js as a built in.

Other than that - there are userland libraries that can do thtis.
