### ISSUE TITLE
Promisify rimraf: callback function required

### ISSUE THREAD

**Issue by jcald1** [petkaantonov/bluebird#1590]
1) What version of bluebird is the issue happening on?
3.5.3

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
v10.15.3

3) Did this issue happen with earlier version of bluebird?
N/A - Didn't try an earlier version

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I'm getting the error "callback function required"

```
global.Promise = bluebird;
const rimrafAsync = Promise.promisifyAll(require('rimraf'));

exports.handler = async (event) => {
...
await rimrafAsync('/tmp/*');
```

results in:

```
{"errorMessage":"rimraf: callback function required","errorType":"AssertionError [ERR_ASSERTION]","stackTrace":["rimraf (/var/task/node_modules/rimraf/rimraf.js:52:10)","exports.handler (/var/task/index.js:211:11)","<anonymous>"]}
```

I'm following the rimraf code example in:
`http://bluebirdjs.com/docs/api/promisification.html`

**Comment by benjamingr** [comment]
Rimraf takes two arguments. Not a bug in bluebird, please open a stackoverflow question :]
