### ISSUE TITLE
Bluebird seems to not handle async/await properly

### ISSUE THREAD

**Issue by mcalhoun** [petkaantonov/bluebird#1595]
1) What version of bluebird is the issue happening on? 3.5.4

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32): Node v8 and Node v12

3) Did this issue happen with earlier version of bluebird? Also tried with v3.5.0 and same issue is occuring

The following code illustrates the issue. The code maked as from the 3rd party library is intended execute a series of promises in order (fooLoader, barLoader, bazLoader) where `barLoader` should not execute until `fooLoader` has resolved.

```typescript
const log = (message: string) => {
  // tslint:disable-next-line:no-console
  console.log(`${new Date().toISOString()}    ${message}`);
};

const sleep = (timeToSleepMs: number): Promise<void> => {
  return new Promise<void>(res => setTimeout(res, timeToSleepMs));
};

// this code is taken from a 3rd party library
function runInSequence<T, U>(
  collection: T[],
  callback: (item: T) => Promise<U>
): Promise<U[]> {
  const results: U[] = [];
  return collection
    .reduce((promise, item) => {
      return promise
        .then(() => {
          return callback(item);
        })
        .then(result => {
          results.push(result);
        });
    }, Promise.resolve())
    .then(() => {
      return results;
    });
}

const fooLoader = async () => {
  log("foo loader begin");
  await sleep(1000);
  log("foo loader complete");
};

const barLoader = async () => {
  log("bar loader begin");
  await sleep(2000);
  log("bar loader complete");
};

const bazLoader = async () => {
  log("baz loader begin");
  await sleep(3000);

  log("baz loader complete");
};

const runIt = (message: string) => {
  return (
    runInSequence([fooLoader, barLoader, bazLoader], loader => {
      const loaderResult = loader();
      return loaderResult instanceof Promise ? loaderResult : Promise.resolve();
    })
      .then(() => log(message))
      // tslint:disable-next-line: no-console
      .catch(err => console.error(err))
  );
};

const runWithoutBluebird = () => {
  log("running without Bluebird...");
  return runIt("without bluebird complete");
};

const runWithBluebird = () => {
  log("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
  log("running with Bluebird...");
  const Promise = require("bluebird");
  Promise.config({ longStackTraces: true });
  global.Promise = Promise;

  return runIt("with bluebird complete");
};

runWithoutBluebird()
  .then(() => runWithBluebird())
  // tslint:disable-next-line: no-console
  .catch(err => console.error(err));
```
output:

```
2019-05-10T15:55:25.452Z    running without Bluebird...
2019-05-10T15:55:25.456Z    foo loader begin
2019-05-10T15:55:26.461Z    foo loader complete
2019-05-10T15:55:26.462Z    bar loader begin
2019-05-10T15:55:28.463Z    bar loader complete
2019-05-10T15:55:28.464Z    baz loader begin
2019-05-10T15:55:31.467Z    baz loader complete
2019-05-10T15:55:31.467Z    without bluebird complete
2019-05-10T15:55:31.467Z    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-05-10T15:55:31.467Z    running with Bluebird...
2019-05-10T15:55:31.495Z    foo loader begin
2019-05-10T15:55:31.495Z    bar loader begin
2019-05-10T15:55:31.496Z    baz loader begin
2019-05-10T15:55:31.496Z    with bluebird complete
2019-05-10T15:55:32.498Z    foo loader complete
2019-05-10T15:55:33.497Z    bar loader complete
2019-05-10T15:55:34.499Z    baz loader complete
```

**Comment by mcalhoun** [comment]
Actually, it just dawned on me that this is running through `ts-node`, not `node` directly. When I transpile my code and run natively on node, it works correctly. So this seems to be a `ts-node` issue, but I'd like to hear a maintainer's input on this. 

```
ts-node v7.0.1
node v8.10.0
typescript v2.9.2
```

I will also try with a newer version of `ts-node`...

**Comment by spion** [comment]
Can you post a reduced test case that hopefully doesn't modify any globals?

**Comment by mcalhoun** [comment]
Honestly, I provided a fully self-contained example of the issue, so I'm not sure why a different case is necessary. Replacing the global promise is our use-case as we want long stack traces in the node app we're wiring.

**Comment by spion** [comment]
Well, okay, your code sample works fine with freshly installed ts-node and the default configuration targets for typescript:

```
49926 % yarn ts-node test.ts
yarn run v1.15.2
$ /home/spion/Projects/tests/bb-33/node_modules/.bin/ts-node test.ts
2019-05-12T22:34:19.014Z    running without Bluebird...
2019-05-12T22:34:19.017Z    foo loader begin
2019-05-12T22:34:20.019Z    foo loader complete
2019-05-12T22:34:20.020Z    bar loader begin
2019-05-12T22:34:22.022Z    bar loader complete
2019-05-12T22:34:22.023Z    baz loader begin
2019-05-12T22:34:25.024Z    baz loader complete
2019-05-12T22:34:25.024Z    without bluebird complete
2019-05-12T22:34:25.024Z    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-05-12T22:34:25.024Z    running with Bluebird...
2019-05-12T22:34:25.048Z    foo loader begin
2019-05-12T22:34:26.049Z    foo loader complete
2019-05-12T22:34:26.050Z    bar loader begin
2019-05-12T22:34:28.051Z    bar loader complete
2019-05-12T22:34:28.052Z    baz loader begin
2019-05-12T22:34:31.055Z    baz loader complete
2019-05-12T22:34:31.056Z    with bluebird complete
Done in 12.91s.
```

However if I target ES2018, which includes native async-await, it doesn't work. That's because replacing the global promise isn't actually possible to do. node and async-await have their own custom hooks into promises and they rely on them to work.

So if you really want to do this, you'll have to stick to a lower target that transpiles to generators. async-await is a black box not meant to be modified in any way.

**Comment by spion** [comment]
I would also suggest looking into node 12, which adds long(er) stack traces behind a flag:  http://thecodebarbarian.com/async-stack-traces-in-node-js-12.html

**Comment by mcalhoun** [comment]
Hi @spion,

It actually works targeting `es2015` but not `es2017`. 

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "moduleResolution": "node",
    "lib": ["es5", "es2015", "dom", "es2017"],
    "target": "es2017"
  }
}
```

FWIW on node 12, we went down that path and we'd love to do that but (a) our code is running in AWS lambda and don't want to have to build our own custom runtime and (b) we tried the new async stack traces and they only work with `async/await` not with promises (and we are using a bunch of 3rd party libraries that we'd like the stack traces in -- i.e., the AWS SDK)

**Comment by spion** [comment]
I'm afraid that transpiling to at least generators seems to be your only option then...

This would likely be considered a good bug for node core though. They should probably protect from global replacements of `Promise`. I'm guessing the issue is somewhere in [async_hooks](https://nodejs.org/api/async_hooks.html).

**Comment by spion** [comment]
Actually - never mind, scratch that. I see the issue.

You are using `instanceof Promise` to check if the result is an instance of Promise. But `async` functions always return an instance of the native Promise. 

So then, you're returning a Promise.resolve() thats because the returned Promise isn't a bluebird one.

Async functions always return promises, even if they don't await anything. Simply modifying the runinsequence invocation to be:

```typescript
runInSequence([fooLoader, barLoader, bazLoader], loader => loader());
```

solves the problem.

**Comment by mcalhoun** [comment]
Ah...very interesting...and great catch! That code is actually from a 3rd party library (I just pulled it out to make the example standalone)...I will open a PR with them to make that change. Thanks @spion!
