### ISSUE TITLE
Promise.map doesn't support AsyncGenerator's

### ISSUE THREAD

**Issue by koistya** [petkaantonov/bluebird#1603]
1) What version of bluebird is the issue happening on?

`3.5.5`

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

`v12`

3) Did this issue happen with earlier version of bluebird?

`n/a`

```js
async function* test() {
  yield 1;
  yield 2;
}

Promise.map(test(), () => {});

// => Unhandled rejection TypeError:
//       expecting an array or an iterable object but got [object Null]
```

https://repl.it/@koistya/async-generator-example

**Comment by benjamingr** [comment]
@koistya I think axax does this.
