### ISSUE TITLE
Property 'toStringTag' does not exist on type 'SymbolConstructor'

### ISSUE THREAD

**Issue by normancarcamo** [petkaantonov/bluebird#1611]
Hello, I would like to know if you can help me with this issue, it's related to the types, but I do think that this could be right place, if not let me know and close it to open it in the right place, thanks.

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
According to the package.json of sequelize is: "^3.5.0"

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

```
node -v
v10.16.3

npm -v
6.11.3
```

3) Did this issue happen with earlier version of bluebird?
Yes

I'm not working for the sequelize team, but I use the sequelize ORM for relational databases, it turns out that they internally use bluebird as a dependecy. The thing is that I started to a new project using typescript and it turns out that the types of bluebird are broken or something like that. 

I attached some screenshots of my files and the errors found during the compilation process using typescript:

<img width="1440" alt="bluebird" src="https://user-images.githubusercontent.com/2402579/65889756-09f59b00-e35f-11e9-8446-37c028ee39ec.png">

This is my tsconfig.json file:
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "rootDir": "./src",
    "outDir": "./dist"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

and this is the content that I'm compiling:

<img width="980" alt="Screen Shot 2019-09-30 at 8 50 18 AM" src="https://user-images.githubusercontent.com/2402579/65890000-6d7fc880-e35f-11e9-8f82-0c75a8850ad6.png">

Also, I've tried things from this issue: [https://github.com/petkaantonov/bluebird/issues/1277](url) without luck.

**Comment by petkaantonov** [comment]
I haven't used typescript so I don't know @benjamingr @spion

**Comment by normancarcamo** [comment]
I solved the issue with just adding ecmascript version using the year or the version number: 
```
{
  "lib": [ "es2015" ]
}
```
or
```
{
  "lib": [ "es6" ]
}
```
Here's the issue that helped out: https://github.com/dfahlander/Dexie.js/issues/736
@petkaantonov thanks for the help!.
