### ISSUE TITLE
Release functions individually in NPM

### ISSUE THREAD

**Issue by villesau** [petkaantonov/bluebird#1612]
Bluebird is packed with useful helper functions like `Promise.props` that would be useful outside the context of Bluebird. So the request I have is to release the helper functions individually in NPM. Something like `@bluebird/props`.

**Comment by petkaantonov** [comment]
Such isolated functions wouldn't be bluebird anymore, so if you want generic isolated props function you can just do it.

**Comment by villesau** [comment]
@petkaantonov can you elaborate a bit? If they are usable as standalone, why wouldn't it make sense to publish them in NPM as standalone?

As an extreme example, Babel does that for even packages that might not be very usable individually: https://github.com/babel/babel/tree/master/packages

**Comment by papb** [comment]
I think I agree with petkaantonov here. If you need isolated functions, you can use [the great set of libraries by sindresorhus](https://github.com/sindresorhus/promise-fun).

**Comment by petkaantonov** [comment]
@villesau The code from bluebird isn't usable as is, it would need to be rewritten so that it works as standalone.
