### ISSUE TITLE
can't resolve async_hooks

### ISSUE THREAD

**Issue by manotoor** [petkaantonov/bluebird#1615]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
^3.5.0
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node v8.16.1 and v8.12.1 (tested on both)
3) Did this issue happen with earlier version of bluebird?
no
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
seeing this issue with ^3.5.0
can't resolve 'async_hooks' in /node_modules/bluebird/js/release
node_modules/bluebird/js/release/promise.js 34:4-26

seems like switching to version 3.5.0 fixed it

**Comment by petkaantonov** [comment]
cant repro

**Comment by benjamingr** [comment]
This happens when `Node < 8` is used, log `process.version` you will see it's not _actually_ Node 8 and you have something else going on

**Comment by ultrakeypoint** [comment]
![image](https://user-images.githubusercontent.com/73173310/193734169-b38491b7-cc3b-494c-802d-26e0f8d2ac61.png)

How to fix?
