### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by jehy** [petkaantonov/bluebird#1616]
Travis build failing on master (release 3.7.0) - badge also broken:

![image](https://user-images.githubusercontent.com/2296742/66481382-7e3fe500-eaa9-11e9-8c65-310508c7a8b9.png)

![image](https://user-images.githubusercontent.com/2296742/66481414-8d269780-eaa9-11e9-8a95-b0744a954950.png)

**Comment by petkaantonov** [comment]
Fixed in 3.7.1
