### ISSUE TITLE
unhandled rejection cannot been detected.

### ISSUE THREAD

**Issue by totoSalad** [petkaantonov/bluebird#1621]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.7.1 / 3.7.0 / 3.6.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node v10.14.1
Chrome 77

3) Did this issue happen with earlier version of bluebird?

https://codesandbox.io/embed/wizardly-shadow-6yhvp?fontsize=14

happened: no console warn. (3.7.1 / 3.7.0 / 3.6.0).
expected: console.warn 'unhandled rejection'.  (3.5.5)

If it's not bug,  please give a way to detect 'unhandledrejection'

**Comment by xyqiao** [comment]
Locking the version to 3.5.0 should work

**Comment by tuures** [comment]
seems like this got fixed in 3.7.2 https://codesandbox.io/s/cold-fire-q5mb7
