### ISSUE TITLE
Feature request: Util toArray

### ISSUE THREAD

**Issue by valoricDe** [petkaantonov/bluebird#1624]
Are there downsides of using something like
`const [error, result] = await to(myPromise)`
with to equal: 
```
function to(promise) {
  return promise
    .then((data) => {
      return [null, data]
    })
    .catch((err) => [err])
}
```
If not. What do you think about adding this util to bluebird?

Inspired by: https://blog.grossman.io/how-to-write-async-await-without-try-catch-blocks-in-javascript/

**Comment by benjamingr** [comment]
You can .reflect() a promise and get it's value or error

**Comment by valoricDe** [comment]
Thank you @benjamingr. I know that reflect gives be a PromiseInspection but it's unpracticable to do ...(follows) to meet the desired interface
```
const inspection = await promise.reflect()
const [error, result] = [inspection.isRejected() && inspection.reason(), inspection.isFulfilled() && inspection.value()] 
```
or with pipeline to prevent variable cluttering:
```
const [error, result] = await promise.reflect() |> (i) => [i.isRejected() && i.reason(), i.isFulfilled() && i.value()] 
```
Also `const [error, result] = await to(myPromise)` resembles the easiness like reacts `[state, setState] = useState()` which we all love

**Comment by bergus** [comment]
No need to write your own, there already are some: https://www.npmjs.com/package/await-handler, https://www.npmjs.com/package/await-to-js

**Comment by valoricDe** [comment]
Thanks for the links to await-handler. Like I said I would like to see this integrated into the bluebird api. But there seems to be not much support for this. Therefore I closed this ticket

**Comment by bergus** [comment]
See also https://es.discourse.group/t/try-catch-oneliner/107 for a recent discussion (including detailed benefit and problem analysis)
