### ISSUE TITLE
cancel array of promises

### ISSUE THREAD

**Issue by vipinrana** [petkaantonov/bluebird#1630]
I am using bluebird(3.7.2) with request-promise(4.2.5) to cancel the list of promises after a given time. The problem is if i cancel a individual promise it cancel without throwing any error.

`
const Promise = require('bluebird');
const request_promise = Promise.promisify(require('request-promise'));
Promise.config({
    cancellation: true
});

let r_promise = [request_promise({
        method: 'get',
        uri: 'https://reqres.in/api/users?page=2'
    }).catch((error) => {
        console.error('error 1')
    }), request_promise({
        method: 'get',
        uri: 'https://reqres.in/api/users?page=2'
    }).catch((error) => {
        console.error('error 1')
    })];

r_promise.forEach((row, index) => {
    row.cancel();
});

setTimeout(() => {
    Promise.all(r_promise).then(data => {
        console.log(data);
    }).catch(err => {
        console.log(err);
    });
}, 2000);
`

Its generating a late observation observer error. 
By seeing error I think I am cancelling promises after promise handlers. Please correct me.

**Comment by benjamingr** [comment]
Please read about cancellation with third-state semantics here: http://bluebirdjs.com/docs/api/cancellation.html
