### ISSUE TITLE
Upgrade `open` dependency

### ISSUE THREAD

**Issue by ryw** [petkaantonov/bluebird#1647]
`open` 0.0.5 is vulnerable https://www.npmjs.com/advisories/663 - fixed in any version >0.0.5

**Comment by benjamingr** [comment]
Sure, though note bluebird has no dependencies and this is just a devDependency

**Comment by ryw** [comment]
For some reason Twistlock (CVE scanner from Palo Alto Networks) is alerting this CVE on our API image, possibly it's coming from some other dependency - will re-check.
/cc @samblackk

**Comment by ryw** [comment]
devDependency, closing
