### ISSUE TITLE
fetchPackageMetaData error error for bluebird@3.7.2 Unexpected token } in JSON 

### ISSUE THREAD

**Issue by druveen** [petkaantonov/bluebird#1653]
Getting below error on running the command

When running below command
```
npm i bluebird@3.7.0
or
npm install @angular/cli
```
getting following error

```
http fetch GET 304 http://registry.npmjs.org/bluebird 81ms (from cache)
8 silly fetchPackageMetaData error for bluebird@3.7.2 Unexpected token } in JSON at position 5285 while parsing near '...uebird-0.7.12-1.tgz"}},"0.7.12-2":{"name...'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 208ms
```

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.7.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node v12.18.2 
npm v6.14.5
Mac

3) Did this issue happen with earlier version of bluebird?

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

**Comment by benjamingr** [comment]
Hey, not related to bluebird.
