### ISSUE TITLE
Memory leak for using promisify() in setInterval

### ISSUE THREAD

**Issue by imechZhangLY** [petkaantonov/bluebird#1663]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
     3.7.2
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
     Node.js 8.11.3
3) Did this issue happen with earlier version of bluebird?
    yes, bluebird v3.5.5 also has the same problem.

Using `promisify()` in `setInterval()` will cause memory leak. The code is showing below.

```js
const Promise = require('bluebird');

setInterval(async () => {
    const a = Promise.promisify(callback => {
        setTimeout(() => callback(null, 2), 0);
    });
    await a();
}, 1000);
```

With using Chrome DevTools to debug the code, I found the `makeNodePromisifiedEval()` in `promisify.js` will cause the problem.
![image](https://user-images.githubusercontent.com/29969079/96096122-10bb6580-0f02-11eb-909a-ce3662364974.png)

I think maybe the compiled code of `new Function()` in `makeNodePromisifiedEval()` can't be collected by GC. But I don't know why and how to solve it.

The code may cause meomry leak in `promisify.js`
![image](https://user-images.githubusercontent.com/29969079/96097228-4b71cd80-0f03-11eb-9d9b-bfdfa312770b.png)

**Comment by benjamingr** [comment]
Turn off long stack traces - does it reproduce?

**Comment by imechZhangLY** [comment]
> Turn off long stack traces - does it reproduce?
@benjamingr 

still have the memory leak problem after turning off long stack traces by the following code.

```js
const Promise = require('bluebird');

Promise.config({
    longStackTraces: false
});

setInterval(async () => {
    const a = Promise.promisify(callback => {
        setTimeout(() => callback(null, 2), 0);
    });
    await a();
}, 1000);
```

**Comment by petkaantonov** [comment]
The function returned by promisify is fast but the promisify function is very slow and never intended to be used this way. The intended usage is:

```js
    const a = Promise.promisify(callback => {
        setTimeout(() => callback(null, 2), 0);
    });

setInterval(async () => {
    await a();
}, 1000);
```

A function is promisified only once for the whole lifetime of a program.
