### ISSUE TITLE
Dead code in a function

### ISSUE THREAD

**Issue by Sonnerz** [petkaantonov/bluebird#1666]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
@3.7.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
node 10.15.3

3) Did this issue happen with earlier version of bluebird?
Do not know

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

/node_modules/bluebird/js/release/util.js
Last line of function cannot be reached:  **eval(obj);**

```
function toFastProperties(obj) {
    /*jshint -W027,-W055,-W031*/
    function FakeConstructor() {}
    FakeConstructor.prototype = obj;
    var receiver = new FakeConstructor();
    function ic() {
        return typeof receiver.foo;
    }
    ic();
    ic();
    return obj;
    eval(obj);
}
```

**Comment by bergus** [comment]
https://github.com/petkaantonov/bluebird/blob/400b6afcfea0056827676d252360f019f12f4f41/src/util.js#L213-L216

**Comment by Sonnerz** [comment]
Yes, a scan that included node_modules.
I needed to show that I followed through on an issue found, besides just highlighting it.
