### ISSUE TITLE
Minified version throws errors

### ISSUE THREAD

**Issue by dippas** [petkaantonov/bluebird#1669]
1) What version of bluebird is the issue happening on?
3.7.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 14.15.0 

3) Did this issue happen with earlier version of bluebird?
Yes

The minified version (bluebird.min.js) is throwing  50 errors

Normal version:

![image](https://user-images.githubusercontent.com/10220287/103668975-b1547b00-4f6f-11eb-8d62-8f0476a438ee.png)

Minified version:

![image](https://user-images.githubusercontent.com/10220287/103669183-f082cc00-4f6f-11eb-8fc4-7bdae2cd9d2e.png)

**Comment by benjamingr** [comment]
what?

**Comment by dippas** [comment]
@benjamingr  sorry, see updated issue

**Comment by benjamingr** [comment]
Don't lint/style-check your vendor file or dist folder. That's optimized to be small not readable ^^

**Comment by dippas** [comment]
I'm not linting the file, this is the only package minified throwing errors, the others don't (such as swiper, axios etc),

These errors are being thrown by VSCode itself. so IMHO this is a package issue, not a linting one
