### ISSUE TITLE
Travis-ci: builds are failing for node.js 0.10, 0.12,4,5 versions for AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [petkaantonov/bluebird#1673]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.7.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 0.10/0.12/4/5 

3) Did this issue happen with earlier version of bluebird?
Not checked

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
While testing on AMD64 on travis-ci build , its failing for all the above mentioned node versions. Please have a look on the log of travis build https://travis-ci.com/github/sanjaymsh/bluebird/builds/216197979. 

Please have a look on the issue.

Thanks !!

**Comment by benjamingr** [comment]
That's because a devDependency bluebird uses uses syntax not supported in EoL versions of Node.js

Since there is really nothing we can do to get other people to support EoL versions with security bugs - I don't think there is anything bluebird can do here.
