### ISSUE TITLE
Error finalising an async function promise => this._passThrough is not a function

### ISSUE THREAD

**Issue by emahuni** [petkaantonov/bluebird#1682]
1) What version of bluebird is the issue happening on?
3.7.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Google Chrome 92

3) Did this issue happen with earlier version of bluebird?
Was using native promises, so it didn't happen until I did this for all my promises
```js
import Bluebird from 'bluebird'
globalThis.Promise = Bluebird
```

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
```js
const fn = async (v)=> 'the response';
fn('args')
.then(r=>{
   console.log(r);
   return 'some other response';
})
.catch(e=>{ /* handle error */})
.finally(r=>console.log(r));
```
![image](https://user-images.githubusercontent.com/7290508/129066239-13769a30-dbe9-407a-86e6-5dfced9ece8a.png)

This is a contrived example of how this is happening. Note that this works when using native Promises.

**Comment by benjamingr** [comment]
Hey thanks for the report.

Async functions typically always create native promises - I don't understand how your example works. Are you transpiling somehow? Overriding native `window.Promise` should not matter.

**Comment by emahuni** [comment]
yes there is webpack involved, this is Vue project with webpack...

However, the particular example is in the console of the said project. So Blue is being loaded by the project as transpiled.

**Comment by benjamingr** [comment]
Yeah you are transforming your async functions using some non-spec-compliant transform and that's causing the error most likely. It's very hard to say without seeing the actual code or project - but this doesn't look like an issue with bluebird itself.

**Comment by emahuni** [comment]
yes I can see that now. tried it in code pan
