### ISSUE TITLE
Bluebird module generates output spam in npm v7 during installation

### ISSUE THREAD

**Issue by CalculonPrime** [petkaantonov/bluebird#1683]
1) What version of bluebird is the issue happening on?

3.4.7

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

Windows 8.1, node 16.10.0, npm v7.24.1

3) Did this issue happen with earlier version of bluebird?

Don't know.

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I have a module that depends on unzipper v 0.10.11, which in turn depends on your module.  When I install my module with "--foreground-scripts" the output of my script is intermingled with spam lines like:

[##################] \ reify:bluebird: timing reifyNode:node_modules/binary Completed in 331ms

which I don't see coming from any other modules but bluebird (identifying it from the mention in the text).  Even without "--foreground-scripts" the spam from bluebird appears to be generated, but doesn't interfere with anything in that case since nothing else gets printed during installation.

**Comment by CalculonPrime** [comment]
This seems to be an npm v7 issue, not specific to bluebird.  When I removed the unzipper dependency (which was what pulled in bluebird), then I just got spam from fs-extra, another dependency.  So I'm going to close this out.

However, if someone knows what's going on here (i.e. why npm is spamming in this case), or has some connection to someone who might know, please let them know it's an issue.

**Comment by benjamingr** [comment]
Bluebird by-design has 0 dependencies - it should pull in nothing itself and has no post-pre install scripts. So it's really as polite as a library can get in terms of impact on your installation.

You are welcome to open an NPM issue or run npm with `--silent`
