### ISSUE TITLE
Vulnerable to memory leak

### ISSUE THREAD

**Issue by bahadrix** [petkaantonov/bluebird#1704]
I'm using version 3.7.2 and my IDE (WebStorm) warns about the following vulnerability:

> The package `bluebird` is vulnerable to memory leak, when running the function longStackTraces() with the flag `--expose_gc`. This causes a significant increase in the memory usage, affecting the server's availability.

Details at: https://devhub.checkmarx.com/cve-details/Cxda14f253-4e52/

**Comment by benjamingr** [comment]
That's silly, if you have long promise chains turning on longStackTraces (debugging mode) will increase memory consumption and reduce performance. _That's the feature_, you get slower code that retains more memory but it's easier to debug - like connecting the inspector to a Node project.
