### ISSUE TITLE
[question] How to handle chained methods

### ISSUE THREAD

**Issue by Ruudieboy** [petkaantonov/bluebird#178]
Forgive me if I didn't see this in the example section;

How should I handle chained methods? Below is a mongoose example.

```
Story
.findOne({ title: 'Once upon a timex.' })
.populate('_creator')
.exec(function (err, story) {
...
}
```

I tried something like this, but that doesn't seem to work...

```
Story.findOneAsync(({ title: 'Once upon a timex.' }))
.populateAsync('_creator')
.exec(function (err, story) {
...
}
```

**Comment by mcpDESIGNS** [comment]
Saved my life @uschen . I don't know why but it's not documented anywhere that you do `limit / populate` etc like normal then do an `execAsync` after to get it all working... Appreciate it

**Comment by aliirz** [comment]
@uschen You rock!

**Comment by macliems** [comment]
Saved my day too, @uschen 
Thanks!

**Comment by yiannissakk** [comment]
mine too @uschen
