### ISSUE TITLE
Using bluebird to promisify Node's http.request?

### ISSUE THREAD

**Issue by kirkouimet** [petkaantonov/bluebird#196]
Can anyone help me promisify Node's http.request with bluebird?

Here is my try:

```
var http = require('http');
var Promise = require('./framework/libraries/bluebird');
var PromiseRequest = Promise.promisify(http.request);

var myRequest = PromiseRequest({
    method: 'GET',
    host: 'nodejs.org',
    port: 80,
    path: '/',
}).then(function(value) {
    console.log('value:', value);
});

console.log('myRequest:', myRequest);
```

Unfortunately this code never completes and the 'then' callback is never executed.

@petkaantonov - love the library! Especially how performant it is!

**Comment by iwllyu** [comment]
In 2015 @benjamingr you posted this SO 
http://stackoverflow.com/a/28308596/1552116

Does that mean with newer versions of bluebird (> 2.8.0) I can use `Promise.promisify(http.request);` instead of the `Promise.method` example above?

**Comment by mhawila** [comment]
Neat

**Comment by radio-miskovice** [comment]
What about resolving the promise when headers are complete and then return another promise for the completed response body?  This would allow for separate processing of headers (possibly rejecting when they were not what you expect/need) and separately processing body errors.  Sorry, don't have an example yet, have to think about one.

**Comment by benjamingr** [comment]
Discussion not related to bug reports or feature requests is better held in StackOverflow Q&A format, IRC or other supported support channels.
