### ISSUE TITLE
"Optimizaton Killers" is misleading.

### ISSUE THREAD

**Issue by rwaldron** [petkaantonov/bluebird#203]
The wiki page "Optimization Killers" is very interesting and important, and very much a good resource. 

Now that I've made my position clear, it's also important that the document be updated to include some "disclaimers" or additional clarifications. Regarding: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax, there are several items listed under "Not optimizable" that should be clarified. Specifically, the following items are not fundamentally "not optimizable", they are simply not optimized and cause the explicit de-opt because they are considered "unstable" (specification wise) implementations. 
- Generator functions
- Functions that contain a for-of statement
- Functions that contain a compound let assignment
- Functions that contain a compound const assignment

Furthermore, two of these: `let` and `const` are obsolete prototype implementations (in v8) that shouldn't be used in any program code until the semantics are updated to current specification. 

All I ask that some additional information be provided with this list which clearly states that these syntactic features themselves are not pathologically optimization hostile (which `with` and `eval` truly are).

Thanks!

**Comment by llambda** [comment]
Hey guys, maybe you are aware already, but I noticed in Chrome 43 that Object.freeze, seal, etc is now 2-3% faster than unfrozen counterparts. It used to be ~93% slower. Does this help with Promise implementation? E.g. to prevent promise tampering with after settling; I thought there was some talk about that being a concern.
