### ISSUE TITLE
Inconsistent naming between .resolve() and .fulfilled()

### ISSUE THREAD

**Issue by tasinet** [petkaantonov/bluebird#210]
Hello,

I noticed an inconsistency between the aliases of the "return a resolved promise, immediately" method: One is named `.resolve()`, and the other `.fulfilled()`. I would expect `.resolve()` to be called `.resolved()` (or `.fulfilled()` -> `.fulfill()`). By contrast, the "return a rejected promise" method exists as both `.rejected()` and `.reject()`.

I've tried to do `.resolved()` on more than one occasion, so I thought I'd post this. It isn't a huge deal, but seeing as this is a beautiful and (otherwise) very consistent library, it might be worth it to create the `.fulfill()` and `.resolved()` aliases.

**Comment by SimenB** [comment]
@benjamingr I realize this is old, but googling led me nowhere else, so here goes. Does 
> You're not supposed to use `Promise#fulfilled` at all

mean that `deferred.fulfill()` like [here](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern) is "wrong"?

If it's not wrong, is there any difference between `fulfill` and `resolve`?

**Comment by benjamingr** [comment]
Yes, it is wrong.

**Comment by spion** [comment]
fulfil is simply the wrong word. Because the method takes a promise as an argument, and that promise may be rejected with an error (and therefore not fulfilled) resolved is the right word.

Here is the state tree of Promises:

```
          Pending
Promise /
        \            Locked-in 
          Resolved /
                   \           Fulfilled
                     Settled /
                             \ 
                               Rejected
```

* Pending - value not known yet, can be changed via resolve or reject
* Resolved - resolve and reject not working anymore
  * Locked-in - ... and value not known yet, but it will be the same as the value of another promise
  * Settled - ... and value is known
    * Fulfilled - ... and value is of "Right" type (i.e. a normal value) 
    * Rejected  - ... and value is of "Left" type (i.e. a rejection value)

**Comment by SimenB** [comment]
Sweet, thanks for the explanation!

**Comment by bergus** [comment]
See also [https://stackoverflow.com/questions/29268569/what-is-the-correct-terminology-for-javascript-promises](http://stackoverflow.com/q/29268569/1048572). The terminology outlined there is a bit different (and more ambigous, to cover lax usage) though.
@spion is that state tree official and documented somewhere? Even cross-library? I must have missed domenics standardisation efforts :-/

**Comment by spion** [comment]
@bergus I based the state tree on https://github.com/domenic/promises-unwrapping, and I'm not sure if its still official (for ES6) but at least it used to be

**Comment by bergus** [comment]
@spion Oh of course it's there: http://www.ecma-international.org/ecma-262/6.0/#sec-promise-objects - and I even have cited that section in my SO answer. I just forgot they used the term "locked in" in the standard.
