### ISSUE TITLE
Promise.promisify fails on fs.createReadStream

### ISSUE THREAD

**Issue by chrisprobst** [petkaantonov/bluebird#225]
Hi,

I just wanted to checkout this library and played a little bit with the pomisify stuff but it does not work for all methods:

```
var Promise = require('bluebird');
var createReadStream = Promise.promisify(require('fs').createReadStream);


var p1 = createReadStream('app.js').then(console.log);

setTimeout(function() {
    console.log(p1);
}, 1000);
```

The p1 gets never fulfilled, no error, no success. I did test it for createWriteStream and it did not work, either.

**Comment by manast** [comment]
Something to note here is that createReadStream can fail in the future, and even if you created the stream inside a promise chain the error will be reported uncatched (and your application die). This is quite unfortunate, for example in the case of a trying to open a missing file, you get a stream and in the next tick you get an exception.
You need to create a stream like this to avoid problems, although this is far from ideal:
```
function createReadStream(filename){
  return new Promise(function(resolve, reject){
    function onError(err){
      reject(err);
    }

    function onReadable(){
      cleanup();
      resolve(stream);
    }

    function cleanup(){
      stream.removeListener('readable', onReadable);
      stream.removeListener('error', onError);
    }

    var stream = fs.createReadStream(filename);
    stream.on('error', onError);
    stream.on('readable', function(){
      resolve(stream);
    });
  });
}
```

@petkaantonov have you give some thought about a proper way to make streams work well together with promises?

**Comment by servatj** [comment]
Your comment is really useful, thanks @manast !!

**Comment by danjl1100** [comment]
Regret digging up an old/closed thread, but I found @manast 's example useful and informative.

Hoping this will help anyone else who stumbles upon it: (tiny correction at the end)
```
function createReadStream(filename){
  return new Promise(function(resolve, reject){
    function onError(err){
      reject(err);
    }

    function onReadable(){
      cleanup();
      resolve(stream);
    }

    function cleanup(){
      stream.removeListener('error', onError);
      stream.removeListener('readable', onReadable);
    }

    var stream = fs.createReadStream(filename);
    stream.on('error', onError);
    stream.on('readable', onReadable);    // <-- small correction
  });
}
```

Expanded for the Writable case: 
```
function createWriteStream(filename){
  return new Promise(function(resolve, reject){
    function onError(err){
      reject(err);
    }

    function onOpen(){
      cleanup();
      resolve(stream);
    }

    function cleanup(){
      stream.removeListener('error', onError);
      stream.removeListener('open', onOpen);
    }

    const stream = fs.createWriteStream(filename);
    stream.on('error', onError);
    stream.on('open', onOpen);
  });
}
```

**Comment by sgronblo** [comment]
Why is the cleanup needed here?
