### ISSUE TITLE
Cannot promisify NeDB

### ISSUE THREAD

**Issue by srigi** [petkaantonov/bluebird#324]
I try to `promisify()` kinda popular in-memory database for JS - [NeDB](https://github.com/louischatriot/nedb). I tried to follow instructions in wiki, but cannot get this done. I always get `Cannot call method 'then' on undefined`. Both browser & node.

I created [plunk](http://plnkr.co/edit/hcwBv27DQ3e8vNta6eg2?p=preview), any help would be appreciated.

**Comment by Yimiprod** [comment]
I know it's an old and closed ticket but for me doing:
```
var DBStore = Promise.promisifyAll(require('nedb').prototype);
var db = new DBStore();
```
result in typeError "object is not a function";

**Comment by wayofthefuture** [comment]
Does anyone known if promisifyAll will also work with the cursors? i.e., find().exec().then() ??
