### ISSUE TITLE
Provide means to extend Promise

### ISSUE THREAD

**Issue by rektide** [petkaantonov/bluebird#325]
Bluebird should be useable by people who wish to extend promises with other enhancements and things they want to try. At present this is made difficult because the Promise constructor throws an error if the constructor is not of type Promise.

I'd prefer to see a means to sidestep this constraint entirely, as it's a betrayal of the nature of prototypal inheritance. If someone wants to mixin all of the Promise methods and call it's constructor, JavaScript is a language designed to permit and allow that.

In a slightly more strict case, perhaps a `this instanceof Promise` call might suffice. I see this is way more strict than strictly necessary, but it's a starting place and a compromise which would allow Bluebird to be at least somewhat useful for people trying to experiment with promises.

The line in question which prevents Bluebird from being extended by anyone else:
https://github.com/petkaantonov/bluebird/blob/3e3a96aaa8586b0b6aa3b7ca432c03f58c295613/src/promise.js#L51

**Comment by opensourcejunkie** [comment]
Hey, sorry to reopen a dead thread; I'm about to start working on a library that extends bluebird, and I want to ensure I'm doing it the best way.  Per this discussion, and the "For library authors" section, it sounds like extending bluebird by decoration is still the best method.  Does anyone know anything to the contrary?

Thanks :-)
~ OSJ

**Comment by nmccready** [comment]
It's been a long time since this thread started; but now since we're on 3.X.. where did this  documentation of "library authors section" go to? Anyone have the url?

**Comment by nmccready** [comment]
nvm ugh https://github.com/petkaantonov/bluebird/issues/1040

**Comment by SystemDisc** [comment]
I'd really like subclassing to be allowed.

My use case:
```typescript
import * as Promise from 'bluebird';

export class PromiseWhile<T> extends Promise<T> {
	private valueWrap: () => T;
	private result: Promise<T>;

	constructor(callback: () => PromiseLike<T>, value: T);
	constructor(callback: () => PromiseLike<T>, value: () => T);
	constructor(private callback: () => Promise<T>, value: any) {
		super((resolve, reject) => {
			if (this.result) {
				resolve(this.result);
			}
			this.resolve = resolve;
			this.reject = reject;
		});
		if (typeof value === 'function') {
			this.valueWrap = value;
		}
		else {
			this.valueWrap = () => value;
		}
		setTimeout(() => {
			this.runCallback();
		});
	}

	// in case resolve gets called before promise is set up
	private resolve(value?: T | PromiseLike<T>) {
		if (this.result === undefined) {
			this.result = Promise.resolve(value);
		}
	}

	// in case reject gets called before promise is set up
	private reject(value?: any) {
		if (this.result === undefined) {
			this.result = Promise.reject(value);
		}
	}

	private runCallback() {
		Promise.resolve(this.callback()).then((rVal) => {
			if (rVal == this.valueWrap()) {
				setTimeout(() => {
					this.runCallback();
				});
			}
			else {
				this.resolve(rVal);
			}
		}).catch((error) => {
			this.reject(error);
		});
	}
}
```
