### ISSUE TITLE
Streams and promises

### ISSUE THREAD

**Issue by greghart** [petkaantonov/bluebird#332]
I've a question on best practices when working with Promises and streams, with specific regards in how to "promisify" them. The example problem I'm trying to solve is with an API that returns a file stream. I then want to use Promise.map with concurrency on a large list of files, so that only `c` files are streaming at any given time. I've solved this to my needs below:

``` javascript
Promise.map(files, function(file){ 
  return new Promise(function(resolve, reject) {
    var stream = API.getStream(file); 
    // Pipe/use stream
    stream.pipe(endPoint);
    stream.on('end', resolve);
    stream.on('error', reject);    
  });
}, {concurrency: 3});
```

Main question is, is there a more semantic way to accomplish this? I've never before had to write new Promise(...) myself, so I have an instinctual feeling I'm missing something. On the other hand, I'm pretty sure it doesn't make sense to automatically promisify API.getStream.
- The stream is returned synchronously already
- You don't want a promise of a stream, you want a promise of a "finished" stream.
- You want the underlying stream for piping and other stream specific functions
- There's no guarantee that an input is a stream, and not just a general EventEmitter style object. 

An example where the API returns a promise of a finished stream.

``` javascript
Promise.map(files, function(file){
  var streamPromise = API.getFinishedStreamAsync(file);
  streamPromise.pipe(streamPromise.stream); // Stream is attached synchronously
  // API now handles stream/promise resolution
  return streamPromise;
}, {concurrency: 3});
```

**Comment by gurdotan** [comment]
@bendrucker nice module!

**Comment by Domiii** [comment]
@petkaantonov Very simple! But if you don't want to `pipe`, you need explicit handling of `data`.

That's why I'm proposing:

    function streamToPromise(stream, onData) {
        return new Promise(function(resolve, reject) {
            stream.on('data', onData);
            stream.on('end', resolve);
            stream.on('error', reject);
        });
    }

What do you think?

**Comment by dennismonsewicz** [comment]
@petkaantonov thanks for your example!! I am attempting something where I am grabbing HTML using https://www.npmjs.com/package/wkhtmltopdf to generate a PDF. I'm trying to follow your example above, but am having issues with getting it to work. 

Here is my code: http://stackoverflow.com/questions/34216417/using-wkhtmltopdf-and-node-js-to-generate-pdfs

I'm very sorry for commenting on A) a closed issue and B) for not opening up a new one. I didn't think it was worthy of opening up a new issue since my question was similar. I'll be more than glad to remove my comment, open a new one, or ask my question(s) elsewhere. Thanks for the awesome library and the help!!

**Comment by jghaines** [comment]
Also:
https://github.com/spion/promise-streams

**Comment by beck** [comment]
A small addition to @petkaantonov's solution, suggest adding `stream.resume();`, otherwise there is no guarantee that the stream will drain and emit `end`.

Example:
```js
const gs = require('glob-stream');
const through = require('through2').obj;

function streamToPromise(stream) {
  return new Promise(function(resolve, reject) {
    stream.on('end', resolve);
    stream.on('error', reject);
  });
}

function log(data, enc, cb) {
  console.log(data.path);
  cb();
}

const stream = gs.create('./*.txt')
  .pipe(through(log));

streamToPromise(stream)
  .then(() => { console.log('I never print, womp womp'); });
```

but the print will happen if one uses:
```js
function streamToPromise(stream) {
  return new Promise(function(resolve, reject) {
    stream.on('end', resolve);
    stream.on('error', reject);
    stream.resume();
  });
}
```

**Comment by manast** [comment]
isn't there a risk that these event handlers: 
```return new Promise(function(resolve, reject) {
    stream.on('end', resolve);
    stream.on('error', reject);
  });
```
leak memory?

**Comment by wmertens** [comment]
@manast EventEmitters (like Streams) should remove their listeners when they complete. That allows GCing them.
