### ISSUE TITLE
Promise.settle -> can it return an array of the promises instead?

### ISSUE THREAD

**Issue by EtaiG** [petkaantonov/bluebird#351]
Instead of PromiseInspection results?

I think a really useful method would be Promise.allSettled, similar to Q.allSettled - where you wait for all of the promises to be fulfilled, and return a promise which is fulfilled if all of the promises had been resolved, and rejected if at least one had been rejected.

In other words:

```
Promise.allSettled([promises]).then(function(){ ... }).catch(function(){...})
```

Would be equivalent to:

```
Promise.settle([promises]).all().then(function(){ ... }).catch(function(){...})
```

if Promise.settle returned an array of promises or if Promise.all could receive an array of PromiseInspection results and work on it.

May I submit a PR to be considered?

**Comment by vitaly-t** [comment]
@EtaiG , a version of it: [spex.batch](https://github.com/vitaly-t/spex/blob/master/docs/code/batch.md)
