### ISSUE TITLE
[Doc] What assumptions does bluebird make on error handling?

### ISSUE THREAD

**Issue by andig** [petkaantonov/bluebird#352]
On a similar not like https://github.com/petkaantonov/bluebird/issues/349 I've noticed that I'm getting `Possibly unhandled error` messages when the rejection is a simple string:

    Promise.resolve("OK").then(function(res) {
      console.log("1st then: " + res);
      return Promise.resolve("OK 2");
    }).then(function(res) {
      console.log("2nd then: " + res);
      return Promise.reject("2nd Error"); // Possibly unhandled error: 2nd Error
      return Promise.reject({e: "2nd Error"}); // Handled error
      return Promise.reject(new Error("2nd Error")); // Handled error
    }).error(function(error) {
      return console.error(error);
    });

What assumptions does bluebird make on error handling?

**Comment by petkaantonov** [comment]
Fixed in 3.0 release
