### ISSUE TITLE
Difficult to get onPossiblyUnhandledRejection to work all of the time in Node.js due to submodules

### ISSUE THREAD

**Issue by sheltond** [petkaantonov/bluebird#357]
onPossiblyUnhandledRejection sets some global state in the module instance to record the function to call in the event of an unhandled rejection.

However, since npm's default is to install a separate instance of modules in the "node_modules" directory of modules that the app depends on, it's difficult for the app to set up error handling for instances of Bluebird which are referenced from another module.

I came across this with Sequelize - I set up an error handler at the top level in my app, and it usually works fine. However, sometimes the default error handler is used instead. It turned out that this is due to the separate instance of Bluebird that Sequelize is using.

(In fact, certain versions of Sequelize use the sequelize-bluebird module instead, which has some differences, but the same problem applies)

The problem gets worse as your app uses more modules that make use of Bluebird.

I don't really have a good suggested solution, but it seems like this is the sort of thing that an app wants to configure for the entire system, rather than a specific instance of the module.

The only ways that I can really think of to do this is for Bluebird to use some global object in Node.js to co-ordinate the error handling mechanism across the different Bluebird instances. The most likely candidate is the 'process' object, I guess.

For example, this could be done by recording the error handling function in a property of the process object, which would be shared by all Bluebird instances, or by emitting an event on the process object instead of using the onPossiblyUnhandledRejection mechanism, which the app could listen for.

I realise that npm installs modules this way to isolate modules from behavioural changes in their dependencies when other modules in the system have difference versions of the module, but in this case I think it might be worth putting in a 'global' mechanism to set the error handler.

**Comment by petkaantonov** [comment]
If a library is using their own private instance, they should expose the hook.

e.g. with sequelize

    Sequlize.Promise.onPossiblyUnhandledRejection(function() {
        // Your application specific handler        
    });

**Comment by benjamingr** [comment]
@petkaantonov I think what he's asking for is a way to hook up to _every_ bluebird instance currently running (yours, Sequelize's etc). 

That's like adding a:

    process.on("bluebirdLoaded", yourHandler); 

And having every instance of bluebird do: 

    process.emit("bluebirdLoaded", Promise)

When it loads.

**Comment by petkaantonov** [comment]
But you still need to know about each library specifically whether you can just override their onUnhandledRejection hook, the library might depend on it.

**Comment by benjamingr** [comment]
@petkaantonov that's true - it might be wise to expose the old handler in the function so:

```js
Promise.onPossiblyUnhandledRejection(function(e, promise, oldHandler) {
    //...
});
```

Which would let you in turn do:

```js
Promise.onPossiblyUnhandledRejection(function(e, promise, oldHandler) {
    // your own before hooks.
    try{
      var res = oldHandler.apply(this, arguments);
    } catch(e){
         // hook on the library throwing, most likely a rethrow
    } finally {
        // your after hooks here
    }
    return res; // or override, return value isn't used here anyway
});
```

With a similar parameter for handled possibly unhandled rejections. This might also be useful for adding to the default pretty print behavior.

I don't mind writing a quick PR this weekend if you think this is a good idea. Will help me get acquainted with the code changes anyway.

**Comment by petkaantonov** [comment]
So when is a good time to fire the onloadedevent so that if the loader were to add a custom hook, the oldHandler would reference it? just setTimeout for the next turn or?

**Comment by benjamingr** [comment]
Ah, that indeed is an interesting problem to guard against - I'll have a quick look at what bookshelf and a few other libraries do and see if anyone is adding an async `unPossiblyUnhandledRejection` hook. 

Intuition is an `async.invoke` should definitely be enough - is there any scenario where it'd run after an unhandled rejection is reported?

**Comment by petkaantonov** [comment]
Btw it could take a long time to get the benefit from this as the older versions obviously don't fire the event.

**Comment by petkaantonov** [comment]
All unhandled rejections are notified in an invokeLater queue, so async.invoke queue is fine

**Comment by petkaantonov** [comment]
I really wonder though what a library could possibly do in the handler that it would depend on or couldn't have the application control. What if we just made them global, but allowed multiple listeners, in 3.0.0

**Comment by benjamingr** [comment]
I'm collecting stats, give me 10 minutes.

**Comment by petkaantonov** [comment]
I really like

    process.on("possiblyUnhandledRejection")
    process.on("unhandledRejectionHandled")

 - It allows multiple listeners
 - It allows the application to remove any custom listeners libraries added

 Like with uncaughtException, if there is not any listener it would only then do the default behavior of console.error (not crash cos it's still only "possible")

**Comment by benjamingr** [comment]
I like it too, just give me a few more minutes to collect data.

**Comment by benjamingr** [comment]
Some data from GitHub (NPM data incoming):

Ignored people who actually cloned Bluebird's code for this.
Testing code not included - those were the vast majority.
Lots of libraries (> 20) document having `onPossiblyUnhandledRejection` usable (in HTML and MD).
A _lot_ of people copied Bluebird's source - mostly frontend projects.

Large (>1000 stars) libraries typically don't change onPossiblyUnhandledRejection:
 - Largest ORMS: Sequelize, Waterline and Bookshelf do not hook on it

Libraries and projects using `onPossiblyUnhandledRejection` in their code:

 - https://github.com/FelisCatus/SwitchyOmega (843 stars, proxy switch, custom logger)
 - https://github.com/AppGyver/steroids (237 stars, PhoneGap extension, throw and crash)
 - https://github.com/att/rcloud (153 stars, AT&T R script cloud thing, defaults to custom logging)
 - https://github.com/simplyianm/githubfollowers/ (101 stars, defaults to log and adds a console log, rather pointless call)
 - https://github.com/ripple/gatewayd (89 stars, framework for financial network, custom logging)
 - https://github.com/tyabonil/request-promise/ (50 stars, promisified package, actual custom logic)
 - https://github.com/mikermcneil/waterline2/ (20 stars, waterline ORM proposed next generation, defaults to suppress behavior)
 - https://github.com/PhilWaldmann/openrecord (19 stars, ORM, lets user configure, defaults to log)
 - https://github.com/wikimedia/restbase (14 stars, Wikipedia people, log)
 - https://github.com/zaggino/brackets-snippets (14 stars, overrides to crash).
 - https://github.com/mozilla/fxa-oauth-server (9 stars, by Mozilla, undefined passed to get Q like behavior).
 - https://github.com/kenspirit/kanban-cfd (8 stars, Kanban graph visualization, crash)
 - https://github.com/mattlewis92/angular-bluebird-promises (6 stars, bluebird for angular, passes noop (this is slighly upsetting :D))
 - https://github.com/Evisions/vertebrae (5 stars, Backbone extension, custom logging)
 - https://github.com/mzgol/check-dependencies (6 stars, npm dependency check, suppress (TODO above))
 - https://github.com/speech/speech.js (3 stars, namecoin domain thing, crash)
 - https://github.com/iarna/promisable (3 stars, promises module, references that it acts like `throw e;` not actual bluebird)
 - https://github.com/maseb/thicket (2 stars, framework, crash)
 - https://github.com/sebinsua/neo4j-promised (2 stars, custom logic to overcome heavior change)
 - https://github.com/ELLIOTTCABLE/wikipedi.as (2 stars, wikipedia thing, log)
 - https://github.com/vkarpov15/wagner-core (1 star, framework, suppress (comment above "swallow bluebird annoying error messages"))
 - https://github.com/jdeanwaite/eDVR (1 star, DVR, defaults to log with default to throw commented)
 - https://github.com/opinsys/puavo-ticket (1 star, ticket system,  custom logging)
 - https://github.com/wikimedia/mediawiki-services-restbase (0 stars, mirror of Wikipedia service, logging)
 - https://github.com/ZJONSSON/express-clues (1 star, express api wrapper, suppress)
 - https://github.com/AaronO/q-bluebird (0 stars, Q API Bluebird wrapper, custom logging)
 - https://github.com/mattlewis92/generator-nasty (0 stars, yeoman generator, defaults to log)
 - https://github.com/bjoerge/proxyreload (0 stars, proxy, passes null)
 - https://github.com/ericnorris/node-cdb (0 stars, cdb implementation, ignores)
 - https://github.com/shanesmith/gerrit-cli (0 stars, no diea, throws)
 - https://github.com/Bornholm/nap-bootstrap (0 stars, overrides to crash).
 - https://github.com/mcirclek/website-client (0 stars, defaults to custom logging)
 - https://github.com/chrisdoble/amd-to-closure (0 stars, converts AMD to closure compiler syntax, suppress)
 - https://github.com/colonyamerican/cah-logger (0 stars, overrides to crash)
 - https://github.com/micirclek/cki-portal (0 stars, site, suppress)
 - https://github.com/dinexcode/dnxapp-gatewayd (0 stars, unclear, log)
 - https://github.com/srcspider/prototyping (0 stars, seed, defaults to crash)
 - https://github.com/martin-liu/m-sails/blob/f02f33a60c424517168b365c0c61da4ad85b8ba6/api/coffee/services/Promise.coffee (0 stars, personal project)
 - https://github.com/danprince/cyvasse (Game, 0 stars, undefined passed to get Q like behavior, lots (100) like this using bundler.js)

**Comment by benjamingr** [comment]
Some conclusions: 

 - A lot of people find `unPossiblyUnhandledRejection` is really useful.
 - We might want to have a "users" section advertising all these people are using Bluebird as users tend to trust that stuff :P 
 - The idea @petkaantonov proposed here (with the process events) seems like a pretty viable option but indeed it'll require older bluebird to upgrade. We might want a `1.x` branch patch that emits these too. The bigger projects usually update to new versions of Bluebird.

**Comment by domenic** [comment]
It may also be useful to at least glance at http://lists.w3.org/Archives/Public/public-whatwg-archive/2014Sep/0024.html which we plan on for the browser. I doubt it makes sense to be entirely compatible (since e.g. ErrorEvent is not a thing in Node) but I'd love to make sure the concepts are aligned. Both of them are global handlers (`window` or `process`), is the idea.

**Comment by benjamingr** [comment]
@Domenic it seems like this proposal is about logging unhandled rejected promises to `window.onerror` so it's not useful for this particular issue (multiple instances of bluebird and a global hook on errors).

@petkaantonov  It might be interesting to call `window.onerror` on a possibly unhandled rejection (and that's definitely something we should consider) - I'll open a new issue.

**Comment by benjamingr** [comment]
Some more stats, out of all the libraries that are on GH in npm and are dependent on Bluebird:

 - 1020 do not override `onPossiblyUnhandledRejection` in their code.
 - 60 do, __most for testing__ or for `d.ts` definitions.
 - 35 say they have a github repo but really don't :) 

I think we're ready to go forward with the event emission idea. Let's specify:

 - What does this do on browsers? (I believe `nothing` or call `window.onPossiblyUnhandledRejection` if it's a function are a good idea)
 - What does it do if the `emit` call throws? (suppress or raise a second unhandled rejection, throw seems unreasonable)
 - What does it get called with? (I believe the current `err, promise` is good)

**Comment by benjamingr** [comment]
https://gist.github.com/benjamingr/0237932cee84712951a2

**Comment by sheltond** [comment]
> I think what he's asking for is a way to hook up to every bluebird instance
> currently running (yours, Sequelize's etc).

Yes, thanks, that's what I meant.

> process.on("possiblyUnhandledRejection")
> process.on("unhandledRejectionHandled")

Great - that looks like it would solve my problem.

**Comment by domenic** [comment]
> What does this do on browsers? (I believe nothing or call window.onPossiblyUnhandledRejection if it's a function are a good idea)

I would suggest constructing a new `CustomEvent`, setting a `.promise` property, and firing it on window. Basically, polyfill the future API, except choose the variant that does not overload `window.onerror`.
