### ISSUE TITLE
Feature Request — spread option for array methods

### ISSUE THREAD

**Issue by dillonkrug** [petkaantonov/bluebird#374]
Hopefully this wouldn't be too difficult to add; it would be nice to have available.

As I was writing the demo I realized it makes passing in the `index` and `arrayLength` parameters tricky.
I for one wouldn't mind losing those if I choose to use the `spread` option.

Example:

```
Promise.resolve([1, 2, 3, 4, 5]).
    map(function(postId) {
        return [
            db.posts.findOneAsync({ '_id': postId }),
            db.comments.findAsync({ 'post._id': postId })
        ];
    }).
    map(function(post, comments) {

        // with a `spread` options we avoid the following:
        //
        // var post = data[0],
        //     comments = data[1];
        //
        // at the expense of not having an index parameter.

        post.comments = comments;
        return post;
    }, {
        spread: true // <- this would be nice
    });
```

**Comment by tiriana** [comment]
I know it's closed, but I agree with @dillonkrug - this feature would be great.

**Comment by phpnode** [comment]
@tiriana spread is just a substitute for ES6 destructuring, so if possible just use that. Remember than `.map()` supplies more than one argument so the proposal could never have worked anyway.

**Comment by tiriana** [comment]
@phpnode I completely forgot about that :confused:   So Yeah, I guess I can't be done.
