### ISSUE TITLE
Relationship to tj's co?

### ISSUE THREAD

**Issue by taoeffect** [petkaantonov/bluebird#400]
Promises newb here, so sorry if this is a dumb question, but could someone better informed than I comment on [tj's co](https://github.com/tj/co) library as it relates to this project?

Do the two projects "compete" in any way or are they complimentary? If they compete, how do they compare (and should benchmarks be added)? If they're complimentary, how so exactly?

Thanks so much for any help clearing this up!

**Comment by timaschew** [comment]
why there is no benchmark for co anymore?

**Comment by benjamingr** [comment]
I'm going to assume because `co` relies on promises nowdays - in co what
you yield are promises now anyway so at best you'd yield bluebird promises
(which'd still be slower than promise.coroutine)

**Comment by petkaantonov** [comment]
Yes promise.coroutine can avoid allocating a new promise if you return bluebird promises to it. Other than that it's implementation efficiency differences.
