### ISSUE TITLE
Promisify function that returns some value and takes callback for result/error

### ISSUE THREAD

**Issue by thesebas** [petkaantonov/bluebird#402]
I think that promisifying function that returns some value and takes callback for result/error makes result of this function lost, lets say there is some function that returns object for controlling this async process:

``` javascript
function doAsync(params, cb){
  ///...
  return {
    abort: function(){ /* ... */},
    // ....
  }
}

var process = doAsync({/* some params */}, function(err, result){ 
 // handle result or err 
});

// something happens
process.abort();
```

now after promisifying this function I can't access this `process` object

``` javascript
var doAsyncPromised = Promise.promisify(doAsync);
doAsyncPromised({/* some params */})
  .then(function(result){
    // handle result
  }, function(err){
    // handle err
  });
```

so what I'm missing here is some callback that I could `intercept` this returned value 

``` javascript
doAsyncPromised({/* some params */})
  .intercept(function(process){
    // something happens
    process.abort();
  })
  .then(function(result){
    // ...
  });
```

Maybe creating functions that returns value and calls callback is not the best pattern but some libraries doing that already exists (for example `request`).

**Comment by spacemonkey92** [comment]
Tried to use promisifyAll on sign.
```
jwt.sign({ foo: 'bar' }, cert, { algorithm: 'RS256' }, function(token) {
  console.log(token);
});
```
I end up getting the token value inside the error. ( because it doesn't have any error param)
Im quite new to promises. is it just me or is it really strange ?

**Comment by phpnode** [comment]
@spacemonkey92 sounds like you're not actually using the promisified version.

**Comment by spacemonkey92** [comment]
That was the actual method.
```
jwt.signAsync({ foo: 'bar' }, cert, { algorithm: 'RS256' })
      .then((token)=>{
      console.log(token);
      })
      .catch((err)=>{
      console.log(err);
      });

```
This is going to the error block.
gives me this 
{ [Error: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzZXNzaW9uSWQiOiJibGI1SEI1VWNqZElzNVR6c1ViR0RrOGxTWVJWQU5jWGh6QXkiLCJpYXQiOjE0NTcwOTkxNDAsImV4cCI6MTQ1NzEwMjc0MH0.V-ClT-in0dzyl1lGZ8vJh-F0Nn5fWxbXOqchhfUXOi-nsfkidN034FP-X7p-9qCl9s1WqE6_75d0WrTH5qVt-5mpKR310FJW0crf2ZDF3chXYf17_BpcqM72XotKmxi4lIaDOUlNyPxQcJeg4LX2HSKVLsGD1Aw62SsoClfGv3s]
  cause: [Error: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzZXNzaW9uSWQiOiJibGI1SEI1VWNqZElzNVR6c1ViR0RrOGxTWVJWQU5jWGh6QXkiLCJpYXQiOjE0NTcwOTkxNDAsImV4cCI6MTQ1NzEwMjc0MH0.V-ClT-in0dzyl1lGZ8vJh-F0Nn5fWxbXOqchhfUXOi-nsfkidN034FP-X7p-9qCl9s1WqE6_75d0WrTH5qVt-5mpKR310FJW0crf2ZDF3chXYf17_BpcqM72XotKmxi4lIaDOUlNyPxQcJeg4LX2HSKVLsGD1Aw62SsoClfGv3s],
  isOperational: true }
