### ISSUE TITLE
'this' is undefined even when .bind({}) used

### ISSUE THREAD

**Issue by klimashkin** [petkaantonov/bluebird#426]
In 2.6.0

**Comment by petkaantonov** [comment]
Working fine for me

**Comment by benjamingr** [comment]
Working fine for me too.

**Comment by klimashkin** [comment]
I'm Using with promisified mongoose. If ```all``` replace with ```join``` then this is object as expected.
Sorry for webstorm screenshot
https://www.dropbox.com/s/px77sa2jdjhf4c8/thisundefined.png
![screenshot](https://www.dropbox.com/s/px77sa2jdjhf4c8/thisundefined.png)

**Comment by klimashkin** [comment]
In 2.5.3 works fine

**Comment by klimashkin** [comment]
Thanks for quick fix! Work like a charm
