### ISSUE TITLE
Bower distribution no longer contains browser build file

### ISSUE THREAD

**Issue by iwehrman** [petkaantonov/bluebird#427]
Recently (perhaps from 2.5.2 to 2.5.3) the bower distribution that results from `bower install bluebird` no longer contains the "browser" builds. This seems like a bug, but maybe it's a feature? Is the intent that that bower clients now need to perform the build step themselves?

(CC @mcilroyc)

**Comment by petkaantonov** [comment]
The browser build is no longer in the git repo but in npm, is there a way to specify that in bower?

**Comment by iwehrman** [comment]
I don't believe there is a way to add files to the bower distribution without changing the files in the repository, but I could be wrong. A workaround might be to use [https://github.com/bower/bower/blob/master/HOOKS.md](bower hooks).

**Comment by bendrucker** [comment]
Bower basically just pulls semver git tags. Hooks can't be used for something like this. Bower is a pain in the ass since. I deal with it automatically by releasing using [browserify-bower-release](https://github.com/bendrucker/browserify-bower-release) which I'm planning on cleaning up, testing, and renaming soonish. Essentially it builds on a new branch, commits the build, tags the commit, then deletes the branch. The result is that the tag remains.

**Comment by petkaantonov** [comment]
If it pulls the repo then you can generate the browser files by doing `node tools/build --browser`, I suppose that could be added as post install hook?

**Comment by bendrucker** [comment]
Right on being able to manually run the build. Bower hooks are for users though, not package authors. Basically you can set stuff up that will be called when you call `bower install` or other commands from the same directory. But it's not like the special npm scripts where you can run build steps when you package is installed by someone else.

**Comment by iwehrman** [comment]
Yes, we can build ourselves after pulling, possibly with a bower hook. Of course it's more complicated than just that one-liner, since bluebird itself has npm dependencies which have to be installed before building.

I realize that this is essentially bower's fault for making this complicated but... are you sure you want to put this burden on all of your bower users instead of just keeping the different builds in the git repo?

**Comment by petkaantonov** [comment]
Having those files in the repo means most pull requests fail because the authors always commit the build files then I tell them they need to remove them and I never hear from them again.

I'll write a script similar to what bendrucker described

**Comment by bendrucker** [comment]
You can basically copy the important bits from mine:

https://github.com/bendrucker/browserify-bower-release/blob/master/src/index.js

While it's a pain to not be able to just use `npm version`, it's been easy enough on the roughly half a dozen or more projects I use it on. I bury the releases in tags for the same reason. Even if you put a note in CONTRIBUTING.md people still modify them.

**Comment by SAnDAnGE** [comment]
Fixing this would be very nice. I am using bluebird in browser with bower to download latest version and gulp to include it in my project. Not sure how easy it is to add another step to build the library before including it...

**Comment by cmwelsh** [comment]
This hit me too. I would consider this a broken bower release and issue a new one. My team is locked on "~2.5.2" but I'm going to lock it to "2.5.2" for now.

**Comment by petkaantonov** [comment]
The 2.6.1 tag contains the browser files js/browser/bluebird.js and js/browser/bluebird.min.js

Here's the script in case anyone is interested https://gist.github.com/petkaantonov/6a73bd1a35d471ddc586

**Comment by cmwelsh** [comment]
Thanks!f
