### ISSUE TITLE
Consider calling `window.onerror` on possibly unhandled rejections

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#428]
People often hook on `window.onerror` to log exceptions to the server. @domenic [proposed](http://lists.w3.org/Archives/Public/public-whatwg-archive/2014Sep/0024.html) native promises call `window.onerror` on unhandled rejections just like exceptions.

Pros:

 - Align with the proposed API for the web.
 - Bluebird remains a drop-in replacement for ES6 promises if the spec is approved with a more feature rich API.
 - Hook with tooling used to debug on the client.

Cons:
 - `Promise.onPossiblyUnhandledRejection`  is already exposed allowing this, in the next version we might fire an event to `process` from all promises possibly rejected. It's already overridable. 
 - API is not approved yet.
 - Add complexity to the library and more browser/node specific logic.
 - We have observed people treat `onPossiblyUnhandledRejection` in many different ways, some suppress it, some make it throw and some make it perform custom logic. This indicates not everyone treats these as errors.

I'm not aware of any other promise libraries considering this at the moment.

**Comment by petkaantonov** [comment]
I am not sure a separate issue is needed, whatever events we do on `process` in node will be done on `window` in browser. However, onerror is bad because we won't be using the equivalent in node (onUncaughtException) and its signature is very different.

**Comment by benjamingr** [comment]
@petkaantonov I tend to agree withthat. To be fair I don't understnad why Domenic would even want this behavior.

**Comment by domenic** [comment]
It's not me that wants it; it's the other Chrome engineers :(

**Comment by benjamingr** [comment]
@domenic calling `onerror` nondeterministically really didn't sound like you :)
