### ISSUE TITLE
No error is thrown for a wrongly promisifyied function

### ISSUE THREAD

**Issue by reggi** [petkaantonov/bluebird#430]
Here's a case with a node-style function within a function (dont ask it was in some library I found). When you promisify it as `example` without `example()` and use it in something like `Promise.props`, it doesn't return result. Even if I use `example().catch(returnFalse)` nothing is thrown and it breaks the whole promise. Thoughts?

```
function example(){
  return function(callback){
    return callback(null, "hello world")
  }
}

var example = Promise.promisify(example);

Promise.props({
  "halts": example()
}).then(function(result) {
    console.log(result);
})
```

It's the same if you use it as:

```
example()
  .then(function(x){
    console.log(x);
  }).catch(function(x){
    console.log(x);
  })
```

Nothing happens.

**Comment by petkaantonov** [comment]
`example` is a thunk, not a node callback convention conforming function

**Comment by reggi** [comment]
gotcha
