### ISSUE TITLE
Clarify nodeify behaviour

### ISSUE THREAD

**Issue by callumlocke** [petkaantonov/bluebird#434]
[`nodeify` in the API docs](https://github.com/petkaantonov/bluebird/blob/master/API.md#nodeifyfunction-callback--object-options---promise) doesn't make it clear what happens if a promise is rejected without a reason...

Does bluebird automatically create an Error object in this case, and pass this to the callback? If not, how can the callback differentiate between success and failure?

**Comment by petkaantonov** [comment]
A promise cannot be rejected without a reason, you can e.g. call `Promise.reject()` but this is equal to `Promise.reject(undefined)` which means `undefined` is the rejection reason.

**Comment by callumlocke** [comment]
OK, so it is possible to reject with `undefined` (or any other falsey value) as the reason. Therefore it's possible to just call `reject()` with no argument – sloppy as it may be, it doesn't cause an exception; it's a valid use of promises. In this case, as far as bluebird is concerned, the promise failed, yet `.nodeify(cb)` will effectively call back saying 'success', because that's how a conventional Node async callback interprets a falsey first argument.

I think that's a bug. `.nodeify(cb)`'s job is to be compatible with the node async callback convention, which is that a falsey first argument indicates success (and a truthy one indicates failure). I think `nodeify` should guarantee to always call back with something that will satisfy the conventional `if (err) {...}` check accurately.

Maybe it should work something like this... if the rejection reason is falsey, then construct a new Error object with the message `"Promise rejected with reason: " + reason` (and also make the reason available directly as `err.rejectionReason`.)

**Comment by petkaantonov** [comment]
I agree, and we already have an additional error object created when a promise is rejected with a primitive (all falsy values) for the stack trace which will be much closer to the original error than the error created in nodeify would be.

**Comment by benjamingr** [comment]
In my opinion you should never reject with anything that is not an error of object. 

It's possible to create a falsey rejection value - we should warn about this but it wouldn't surprise me if there are people relying on this behavior.

**Comment by callumlocke** [comment]
wow :godmode: nice work
