### ISSUE TITLE
Inconsistent README example and API functionality

### ISSUE THREAD

**Issue by chrisdotcode** [petkaantonov/bluebird#435]
One of the examples in the readme contains the following:

```javascript
request("http://www.google.com").then(function(contents){
    console.log(contents);
}).catch(clientError, function(e){
   //A client error like 400 Bad Request happened
});
```

Yet in API.md#promisification, the example explicitly says,
<code><pre>// Request
var Promise = require("bluebird");
Promise.promisifyAll(require("request"));
<b>// Use request.getAsync(...) not request(..), it will not return a promise</b></pre></code>

I will gladly send a pull request to fix the example in the readme.

**Comment by chrisdotcode** [comment]
Er, there are actually more than one occurrence of this in the API.md, upon further reading.

**Comment by benjamingr** [comment]
Right, the first version provides promisification via "promisify" which promisifies a single method. The promisification version calls "promisifyAll" which promisifies all methods on an object.

The API docs are not incorrect here - but if you feel that if this can be clarified documentation pull requests as always will be entertained.
