### ISSUE TITLE
A method / wrapper for passing nested anonymous functions?

### ISSUE THREAD

**Issue by reggi** [petkaantonov/bluebird#437]
Let's say I'm reading a `CSV` and I've promisified [`node-csv`](https://github.com/wdavidw/node-csv-parse) I use `fs.readFileAsync` to get the file.

Then I've got this gem of a one-liner.

```
 fs.readFile(myCsv, "utf8").then(parse)
```

But then I wanna add an option to parse like so.

```
return fs.readFile(import_csv, "utf8").then(function(data){
  return parse(data, {columns: true});
})
```

If I wanted to abstract that out I could pull the entire function or make a wrapper, annoying stuff.

```
function myParser(data){
  return parse(data, {columns: true});
}
return fs.readFile(import_csv, "utf8").then(myParser)
```

or to add some functionality something like 

```
function myParser(options){
  return function(data){
    return parse(data, options);
  }
}
return fs.readFile(import_csv, "utf8").then(myParser({columns: true}))
```

I was wondering if there was some promise helper that would allow me to pass in arguments to native functions (without anons within) that would prepend the signature with whatever was passed from the promise. So I could just do this with the native csv parser.

```
return fs.readFile(import_csv, "utf8").SOMETHING(parse({columns: true}))
```

Thoughts?

```
function action(foo, bar){
  console.log(foo)
  console.log(bar)
  return foo + bar
}
return fs.readFile(fooFile, "utf8").SOMETHING(action("bar"))
// would concatenate contents of fooFile to "bar"
```

**Comment by reggi** [comment]
After looking at all this, I understand that opening up the then function is probably best and easily readable. This would still be cool though.

**Comment by benjamingr** [comment]
I think that lodash's .partial could work here:

    fs.readFile("myFile").then(_.partialRight(parse, {columns: true}));

**Comment by reggi** [comment]
Thanks @benjamingr! I'll check it out.
