### ISSUE TITLE
Promise.resolve doesn't work as expected when exceptions are thrown

### ISSUE THREAD

**Issue by baer** [petkaantonov/bluebird#438]
I'm not sure this is something any library can deal with given the order of JavaScript evaluation but I did run into a case where Bluebird did not catch an error when I expected it to. Below is a code snippit. This might be just something worth noting in the docs.

```js
var validateOptions = function () {
  if (!options.id) {
    throw new InvalidArgumentError('Invalid id: ' + options.id)
  }
}

// Works as expected
new Promise(function (resolve, reject) {
  validateOptions(options);
  resolve(options);
}).catch(InvalidArgumentError, function () {
  console.log('I am here!')
});

// Does not work
Promise.resolve(validateOptions(options))
  .catch(InvalidArgumentError, function () {
    console.log('I am here!')
  });
```

**Comment by phpnode** [comment]
@baer yeah you're invoking the throwing function before passing it to `.resolve()`, you don't give it chance to wrap, there's nothing bluebird can do about that.

**Comment by baer** [comment]
Yup, that's what I realized when I was working out why the catch wasn't catching. Might be worth noting in the docs that Promise.resolve !== Promise.promisify and that errors will not be caught. If you think this is obvious or obscure feel free to close. If you'd like a PR I'll see what I can push out later tonight.

**Comment by benjamingr** [comment]
@baer  this is what `Promise.try` is for. 

```js
Promise.try(function(){
    return validateOptions(options);
})
```

Like @phpnode  said it is impossible to do with resolve given how the language works anyway.

**Comment by bendrucker** [comment]
Or with a more concise syntax, `Promise.try(validateOptions, options)`.
