### ISSUE TITLE
Issue promisifying node-mysql

### ISSUE THREAD

**Issue by richardfickling** [petkaantonov/bluebird#443]
I would expect the following two code fragments to output the same thing:

```
Promise = require 'bluebird'
mysql = require 'mysql'
Promise.promisifyAll(require("mysql/lib/Pool").prototype)
Promise.promisifyAll(require("mysql/lib/Connection").prototype)

pool = mysql.createPool { database: 'mydb', host: 'localhost', user: 'user', password: 'pw' }

pool.getConnectionAsync().then (db) ->
  db.queryAsync('select * from users where id=?', '1').then (rows) ->
    console.log rows
```

```
mysql = require 'mysql'

pool = mysql.createPool { database: 'mydb', host: 'localhost', user: 'user', password: 'pw' }

pool.getConnection (err, db) ->
  db.query('select * from users where id='?', '1', (err, rows) ->
    console.log rows
```

However for the first, the output looks like:
```
[ [ { id: 1, email: 'myemail', password: 'pw' } ],
      [ { catalog: 'def',
  db: 'mydb',
  table: 'users',
  orgTable: 'users',
  name: 'id',
  orgName: 'id',
  charsetNr: 63,
  length: 64,
  type: 8,
  flags: 20483,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }, ...
] ]
```

and for the second the output is just:

```
 [ { id: 1, email: 'myemail', password: 'pw' } ] 
```

I'm still digging in, but wanted to post an issue to see if this is a known problem (or if it's a case of PEBKAC)

**Comment by petkaantonov** [comment]
Mysql doesn't strictly conform to node callback convention, the callback parameters are actually: is `err, rows, columns` which doesn't map to single return value. So the promise fulfillment value is `[rows, columns]` instead of just `rows` like you expected, to avoid information loss.

You can use `spread` instead:

```js
pool.getConnectionAsync().then (db) ->
  db.queryAsync('select * from users where id=?', '1').spread (rows, columns) ->
    console.log rows
```

This cannot be fixed until 3.0.0, see https://github.com/petkaantonov/bluebird/issues/307

**Comment by bendrucker** [comment]
According to the [node-mysql docs](https://github.com/felixge/node-mysql/#introduction), the callback is called with `err, rows, fields`. Because promises can only be fulfilled with a single value and Bluebird resolves an array of values instead. Just change your code to:

```js
qb.queryAsync().spread(function (rows, fields) {});
```

**Comment by benjamingr** [comment]
Or just:


    pool.getConnectionAsync().then (db) ->
      db.queryAsync('select * from users where id=?', '1').then ([rows, columns]) ->
        console.log rows

**Comment by richardfickling** [comment]
:+1: thanks guys

**Comment by Prieston** [comment]
Is the connection being released after calling "queryAsync" ?

**Comment by Knowledge91** [comment]
@Prieston no. You need to release it yourself. Have a look at Bluebirds `.disposer()`
