### ISSUE TITLE
Map over objects?

### ISSUE THREAD

**Issue by reggi** [petkaantonov/bluebird#445]
https://github.com/petkaantonov/bluebird/blob/master/API.md#mapfunction-mapper--object-options---promise

Is this something that was left out for a specific reason?

**Comment by bendrucker** [comment]
Yup, it was specifically rejected in #181.

`Promise.prototype.map` retains the same callback signature as `Array.prototype.map`. See #181 for examples of how to use lodash to do it. 

Petka put it best there:

> .map and others are meant to be tools to handle concurrency (especially in 2.0) where array is just used as a mechanism - they are not about "promises-for-arrays" or about calling array methods at all.

> An object mapping function has no place on the promise prototype because it's simply an operation on some specific type the promise is wrapping - if it is added it means you can justify adding literally anything on the promise prototype.
