### ISSUE TITLE
tapSpread

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/bluebird#451]
From time to time I need the functionality of `.tap`, but in a spreading fashion, am I just being ridiculous for not just using the returned `array`?

**Comment by benjamingr** [comment]
Spread is a shim for ES6 destructuring anyway. You can shim a .tapSpread if you'd like I don't think it's common enough to include it in core. You can always .spread and return arguments:

     myChain.spread(function(a,b,c){
          console.log("Got",a,b,"and",c);
          return arguments;
     })....

**Comment by petkaantonov** [comment]
Please use [scoped prototypes](https://github.com/petkaantonov/bluebird#for-library-authors) to add any method you want

**Comment by benjamingr** [comment]
@petkaantonov  lol I think he was asking for it to be added. You could have just said no :P

**Comment by tjconcept** [comment]
@benjamingr I hadn't actually thought about the relation with destructuring. Thanks for the ideas.

@petkaantonov Oh, pretty neat feature!

It was more an "Am I doing something really wrong"-question and "no" is a more than acceptable answer in this case. Thanks both.
