### ISSUE TITLE
Add the ability to throw a real exception in the browser

### ISSUE THREAD

**Issue by baer** [petkaantonov/bluebird#452]
##### The Problem
It seems that it's not possible to throw a real Error in the browser from code that is running inside of a promise chain.

```js
myModuleInitializer()
  .then(render)
  .catch(myCustomException, function(error) {
    // This does not throw a real error. Bluebird code will always catch and handle this
    throw error;
  });
```

The issue it seems is related to [this block of code](https://github.com/petkaantonov/bluebird/blob/master/src/captured_trace.js#L171-L188). Bluebird doesn't actually throw errors, it has it's own logic to manipulates the stack and then logs a pseudo-error to the console/stderror. This approach is very clean in Node but there are a few issues I ran into when running this in the browser.

The only potential solution I've been able to find is attaching a function to `onunhandledrejection` but because the stack is not preserved, this was a dead end.
```js
window.onunhandledrejection = function(reason, promise) {
  // Throws a real error but does not preserve stack trace
  throw reason;
};
```

##### Reasons the ability to (also) throw a real error are important in the browser
* Logging rather than throwing errors circumvents the browser's ability to parse the source maps for a given trace. This prevents either sourcemaps+minified code or Promises themselves from being used in a production environment. There may be a way to inform Bluebird of the sourcemap but judging from #363 it doesn't look like it.
* Global error handlers like Sentry, Rollbar, Bugsnag, Airbrake etc. are set up to catch errors without extra instrumentation. With this setup you need to parse sourcemaps yourself and make sure that they fire properly on the `window.onunhandledrejection` and `window.onhandledrejection` cases or instrument any promises with a little snippit to handle the errors.

##### Solutions(?)
* Make sure the original stack is passed on to `window.onunhandledrejection` and allow errors to be fully re-thrown.
* Add a new method that would allow a real exception to be thrown from Bluebird.
* Actually throw errors when running in a browser

**Comment by benjamingr** [comment]
Please see the duplicate: https://github.com/petkaantonov/bluebird/issues/51

**Comment by benjamingr** [comment]
As for the window.onerror part - see https://gist.github.com/benjamingr/0237932cee84712951a2

In particular - for the window.onerror bits please see https://github.com/petkaantonov/bluebird/issues/428

**Comment by petkaantonov** [comment]
So it looks like what you actually want is just source maps and the firing of `window.onerror`

For source map support you can do: https://github.com/petkaantonov/bluebird/issues/363#issuecomment-60491306

As for firing window.onerror, you can simply:

```js
window.onunhandledrejection = function(reason, promise) {
      window.onerror(reason.message, "", "", "", reason);
};
```

**Comment by baer** [comment]
I didn't realize how deep this went, thanks for all the work you've been doing to get browsers to do better error handling for promises! I'm still reading the replies to Domenic's proposal and the issues included here but it seems like things are moving which is exciting.

As for the source maps, I installed that plugin and it works well enough for now. Thanks for the help and the awesome library!

**Comment by jardakotesovec** [comment]
> For source map support you can do: #363 (comment) . However even this should become unnecessary in the future when the .stack property will be automatically source mapped. 

@petkaantonov Do you have any link or something where would be possible to find out if thats gonna actually happen and when - that source maps will work well using just dev tools without node-source-map? 

I tried to make the node-source-map with webpack and did not manage to make it work and can't spend much time to elaborate.

I would expect that many devs are these days using promises in browsers and it will be sooner or later solved in browser dev tools. So just would like to know when that happens :-).

**Comment by Rush** [comment]
> @petkaantonov Do you have any link or something where would be possible to find out if thats gonna actually happen and when - that source maps will work well using just dev tools without node-source-map?

Bumping this question, source maps in conjunction with `longStackTraces` is really badly needed ....
