### ISSUE TITLE
Too heavy

### ISSUE THREAD

**Issue by steelbrain** [petkaantonov/bluebird#453]
I am using bluebird in an Atom Editor Package, every single milisecond counts. Doing `require('bluebird')` takes atleast 50 miliseconds (I don't want my package to look slow).

Is there any rewrite planned or something to make this a bit lightweight?

**Comment by petkaantonov** [comment]
No there is not, but the real problem is probably Atom Editor Package, 50ms for processing 140kb of code doesn't exactly sound right...

**Comment by domenic** [comment]
Atom switched to io.js, so there should be a native global `Promise` you can use.

**Comment by steelbrain** [comment]
@domenic, Thanks! that was helpful.
