### ISSUE TITLE
Dependency graphs:  let promise X declaratively waitFor promise Y

### ISSUE THREAD

**Issue by gebrits** [petkaantonov/bluebird#455]
I'm building a declarative rules framework. I.e.: conditions -> actions.  Bluebird seems a good fit since a lot of actions / conditions are async in nature. 

An important part is being able to declaratively configure that promise X should wait for Promise Y to finish. This would allow me to construct dependency graphs of promises which would be really powerful. 

afaik, this isn't supported in Bluebird. 

Is this something worth considering, since this would be a very powerful flow-construct I imagine. 
I might be able to put some time in it, if there's any interest.

**Comment by petkaantonov** [comment]
That should be pretty trivial:

```js
Promise.prototype.waitFor = function(y) {
    return this.tap(function() {
        return y;
    });
};
```

Example:

http://jsfiddle.net/LqmwuL7L/
