### ISSUE TITLE
Don't just call window.onunhandledrejection, fire a CustomEvent too

### ISSUE THREAD

**Issue by domenic** [petkaantonov/bluebird#456]
Would be nice to be able to use `addEventListener`. It's very jarring to have `.on...` work but `.addEventListener("...", fn)` fail.

**Comment by benjamingr** [comment]
@domenic to be fair it's stated very explicitly in the documentation. If it were up to me and not petka we wouldn't fire either until you guys decide what you want to do at a spec level.

I'm yet to see a browser case where multiple libraries are present that are capable of reporting unhandled rejections - and for a single library you can do `Promise.onPossiblyUnhandledRejection(...)`

**Comment by domenic** [comment]
> I'm yet to see a browser case where multiple libraries are present that are capable of reporting unhandled rejections

Pretty simple.

```js
require("log-unhandled-rejections-to-console");
require("store-unhandled-rejections-in-localstorage-when-offline");
require("send-unhandled-rejections-to-server");
```

Anyway what I'm largely concerned about here is that in every other place where there's a `.on... = ...` in my code, I can refactor it to addEventListener. Indeed this is a best practice that I try to encourage. Many developers coming into a project and seeing `.on... =` usage will say "oh, that must be because it's by a developer who isn't up to date with the latest DOM APIs!" and then go and refactor it to addEventListener, thinking they are doing a good thing.

**Comment by petkaantonov** [comment]
There would still be couple of differences:

    - There is no way to tell that any listeners are registered (unlike node `.emit` which returns `true`), so one has to call `e.preventDefault()`
    - There is only one parameter which is event object with `.error` and `.promise` properties, while the other apis just pass them as arguments directly

So you still wouldn't be able to simply replace `window.onunhandledrejection = fn;` with `window.addEventlistener("unhandledRejection", fn)`

**Comment by domenic** [comment]
Right, I think converging on a browser event model in browsers would make more sense. Consistency with Node is not very interesting.

**Comment by petkaantonov** [comment]
Btw wouldn't also `.target` property of the event be appropriate for storing the promise and `.detail` for the error (which would be null in rejectionHandled event)?

**Comment by petkaantonov** [comment]
Never mind, `.target` will be changed to `window` when it is fired...

**Comment by benjamingr** [comment]
@domenic  I agree that consistency with node is not very interesting for the window methods.

@petkaantonov  be careful not to break IE8 if you implement this.

**Comment by domenic** [comment]
`.target` is a DOM node generally. I would guess `.detail` being a `{ promise, rejection }`  pair would make the most sense.

**Comment by domenic** [comment]
Lovely, thank you!!

Maybe comment on why you would call `e.preventDefault()`?

**Comment by petkaantonov** [comment]
You mean on the readme?

**Comment by domenic** [comment]
Awesome, exactly what I was wondering.
