### ISSUE TITLE
Bluebird.method or any other wrapper as ES6 Class method

### ISSUE THREAD

**Issue by klimashkin** [petkaantonov/bluebird#457]
Hello! It's not straight bluebird issue, but maybe community will help.
How to declare ES6 Class method as Bluebird.method or Bluebird.coroutine? :)
```
class View {
  constructor(options) { ... }
  someMethod() { ... }
}
```
I want ```someMethod``` to be coroutine

**Comment by benjamingr** [comment]
This is an ES6 issue since there is no way to annotate `someMethod` as a Promise coroutine or method.

What I do since I use 6to5 is declare it as an async function and run 6to5 with the bluebird-coroutine option:

```
class View {
  constructor(options) { ... }
  async someMethod() { ... }
}
```

Alternatively - you can suffix methods with async and run through them:

```
class View {
  constructor(options) { ... }
  someMethodAsync() { ... }
  otherMethodAsync*() { ... }
}

Object.keys(View.prototype).forEach(function(key){
    if(endsWith(key, "Async"){
         if( fn.constructor.name === 'GeneratorFunction'){
             View.prototype[key] = Promise.coroutine(View.prototype[key]);
         } else {
             View.prototype[key] = Promise.method(View.prototype[key]);
         }
    }
});

function endsWith(str, suffix) {
    return str.indexOf(suffix, str.length - suffix.length) !== -1;
}
```

To be fair - I don't really like either approach. Simply put there is no real clean way to decorate functions in classes in ES6. You can always declare the methods with "enhanced" ES5 syntax using `Object.assign`.

**Comment by klimashkin** [comment]
Strange. Maybe es6 writers explained such restrictions somewhere?

**Comment by benjamingr** [comment]
@klimashkin what restrictions? This is just new syntax - the native ES way in ES7 would be async methods that use promises anyway (basically native and likely slower Promise.coroutine :))

**Comment by petkaantonov** [comment]
@benjamingr but the class syntax has no equivalent to annotations now, that's a disappointing limitation and will mean one has to to keep using prototypes in some situations

**Comment by Kiechlus** [comment]
@benjamingr `Object.keys(View.prototype)` didn't work for me with methods added in class syntax, I had to use your function like this: 
```
Object.getOwnPropertyNames(View.prototype).forEach(function(key){
...
}
```

**Comment by benjamingr** [comment]
You are correct - they are non enumerable so getOwnPropertyNames. 

Your `yield` issue is probably because you're not compiling correctly with babel.

**Comment by Kiechlus** [comment]
Yes. Seems we can call yield only from within generator functions: https://github.com/tj/co/issues/148#issuecomment-56975641
