### ISSUE TITLE
Error catching within .thens

### ISSUE THREAD

**Issue by samccone** [petkaantonov/bluebird#458]
This is more of a question about implementation than anything, but would very much appreciate any insight that you can provide. 

Given this implementation the error is caught as expected

```js
Promise = require("bluebird")

foo()
.then(function() {
  console.log("all is well")
})
.catch(function() {
  console.log("error caught")
})

function foo() {
  return new Promise(function(res, rej) {
    if (1) {
      throw(new Error("no"));
    }
  })
}
```

However when I change `foo`'s implementation to this

```js
function foo() {
   if (1) {
      throw(new Error("no"));
   }

  return new Promise(function(res, rej) {
    res("ok");
  })
}
```

The error is no longer caught within the `.catch`. I suppose I have been under the incorrect assumption that any error thrown within a `.then` will be propagated to the `catch`, however it seems like this assumption was flawed. 

Can you explain this behavior and or design decision. Thanks!

--------

Based on some further reading

https://promisesaplus.com/#point-42

> If either onFulfilled or onRejected throws an exception e, promise2 must be rejected with e as the reason.

It seems like it should be rejecting and catching.

**Comment by spion** [comment]
Its impossible for bluebird to catch the error. The error is thrown before any promises are created.

**Comment by benjamingr** [comment]
For this - `Promise.method` is used:

```js
var foo = Promise.method(function() {
   if (1) {
      throw new Error("no"); // any thrown errors are converted to rejections
   }
   return "bar; // any returns get converted to fulfillments
}
```

The Promises/A+ spec only specifies the `then` method by the way - it is unrelated to the promise constructor spec - both of which bluebird complies to.

In general you should ask questions like this one in StackOverflow to keep the issue tracker clean. We all frequent there too anyway.

**Comment by samccone** [comment]
Ok thanks for the insight, as I said, just more of a question implementation thanks!

**Comment by petkaantonov** [comment]
Your code is equivalent to

```js
function foo() {
   if (1) {
      throw(new Error("no"));
   }
}

foo();
```

So it actually has no relation to promises.
