### ISSUE TITLE
WebWorker, old browser, and schedule

### ISSUE THREAD

**Issue by fdecampredon** [petkaantonov/bluebird#459]
Schedule will be set to setTimeout in webworker (and in oldbrowser), I can understand that other method are a little buggy, but having a 4ms delay can be a serious perf killer, could you at list use 'setImmediate' if provided ? this way we can be sure to have a better delay if we provide a setImmediate shim.

**Comment by petkaantonov** [comment]
Doesn't [`Promise.setScheduler`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisesetschedulerfunction-scheduler---void) work for you ?

You would use it like:

```js
Promise.setScheduler(function(fn) {
    setImmediate(fn);
});
```

**Comment by fdecampredon** [comment]
ok sorry perfect I should have checked the doc before reporting an issue -.-
