### ISSUE TITLE
Promise.all is returning an array of rejections

### ISSUE THREAD

**Issue by cusspvz** [petkaantonov/bluebird#460]
### Wiki reference:

```
.all() -> Promise

Given an array, or a promise of an array, which contains promises (or a mix of promises and values) return a promise that is fulfilled when all the items in the array are fulfilled. The promise's fulfillment value is an array with fulfillment values at respective positions to the original array. If any promise in the array rejects, the returned promise is rejected with the rejection reason.

```

### Test Case:
```js

Promise.all([
  Promise.cast(),
  Promise.cast(),
  Promise.cast(),
])
.done(function ( err ) {
  // err is [ null, null, null ]
  expect( err ).to.be.null; 
});

```

### Final questions:

My interpretation of wiki is that `Promise.all` only rejects on the first rejection receive and only fulfills when all promises are fulfilled. Should in this case `err` be null? Is my interpretation wrong?

**Comment by benjamingr** [comment]
Promises are not node callbacks - your first parameter is the return value.

If you want to handle errors add a `catch` handler like you would with synchronous code - see API.md for examples. 

It is best to ask support questions on StackOverflow

**Comment by petkaantonov** [comment]
You have either misunderstood promises at basic level or meant to use `.nodeify` instead of `.done`:

```js
Promise.all([
  Promise.cast(),
  Promise.cast(),
  Promise.cast(),
])
.nodeify(function ( err ) {
  expect( err ).to.be.null; 
});
```

**Comment by cusspvz** [comment]
@benjamingr I understand what a promise is and how they work... thanks for your fast response.

@petkaantonov Well, seems like i've misunderstood `.done` method. I taught that `.done` was doing what `.nodify` does. Thats why i've placed `err` as handler's first param. :)

**Comment by cusspvz** [comment]
Thank you both for clarifying me and for your work on bluebird ;)
