### ISSUE TITLE
Change in Behavior of undefined passed to .spread

### ISSUE THREAD

**Issue by pon** [petkaantonov/bluebird#461]
The following code works in release 2.4.1, but breaks with the error ```Possibly unhandled TypeError: expecting an array, a promise or a thenable``` in 2.4.2. 
```
var Bluebird = require('bluebird');

return Bluebird.resolve().then(function (){
  if (false) {
    return ['a','b'];
  }
}).spread(function (a, b) {
  console.log('here');
});
```

Is the expected behavior to throw an error when ```.spread``` doesn't receive an array or should it continue with both ```a``` and ```b``` as ```undefined```?

**Comment by benjamingr** [comment]
In my opinion rejecting is the correct behavior. This is like destructuring would work in ES6:

```js
.then([x,y] => 
```

Throws an error if passed undefined for the destructuring. Since `spread` is a shim for that it makes sense to raise an assertion here. It's also more logical imo.

what would you expect?

**Comment by pon** [comment]
I agree with you that rejecting is the correct behavior. I just wanted to raise the issue since it was a breaking change in a patch version and didn't see any notes about it in the changelog or documentation. What do you think about adding to the ```.spread``` documentation to make it clearer that it will reject if not given an array?

**Comment by benjamingr** [comment]
@pon sure, in general pull requests that help clarify things in the documentation are always appreciated

**Comment by dmethvin** [comment]
In the docs, I would change this:

> Like calling `.then`, but the fulfillment value or rejection reason is *assumed to be* an array, ...

to *"must be an array"*. When called with invalid data I don't think the caller should assume specific behavior from the API. 

Alternatively you can document the behavior for `undefined` but in that case I would think you'd want to have corresponding unit tests to ensure there were no future regressions. Essentially @pon considered this to be a regression so a docs-only change would not fix that issue.

**Comment by pon** [comment]
I've created a PR for the documentation update I would be happy to add tests for it, but I would need some guidance on the correct way to do that in this code base.

**Comment by petkaantonov** [comment]
Thanks, the pre 2.4.2 behavior was indeed never intended and it should indeed give same result as doing

```js
.all().then(function(xxx) {
    return fn.apply(this, arguments);
})
```

but an internal optimization in pre 2.4.2 skipped doing that
