### ISSUE TITLE
promisifyAll to work with object's getters

### ISSUE THREAD

**Issue by olsonpm** [petkaantonov/bluebird#464]
So I just spent quite a bit of time looking into how promisify works and specifically why promisifyAll wasn't working as I expected with npm's api "require('npm')".  The reason is that instead of prototyping onto the npm.commands object or creating function properties, they assigned getter properties instead.  I was wondering from a design perspective whether it would make sense for bluebird to promisify getter properties.

I couldn't think of a reason why promisifyAll should discriminate against getters, but this is also a bit beyond my javascript proficiency so I thought I'd ask here.

Example code
```
var bPromise = require('bluebird')
  , bNpm = bpromise.promisifyAll(require('npm'));

bNpm.commands.installAsync('./', 'lazy.js')  // <----- Exception thrown here
  .then(...

// error message
'object has no method installAsync'
```

**Comment by benjamingr** [comment]
> I couldn't think of a reason why promisifyAll should discriminate against getters,

Getters have side effects so promisifying them could by itself cause a side effect. Moreover when promisification itself occurs Bluebird would have to define a getter itself to cause the same side effects to keep the app in consistent state and that sounds impossible.

**Comment by petkaantonov** [comment]
Because promisification would need to call the getter, to find out of it returns a function which causes side effects. On top of that the getter might return a different value on different calls.

However in npm's case the commands being getters make no sense - they do not do anything a normal data property wouldn't accomplish  And if they did do anything on top of that, see previous paragraph.

**Comment by olsonpm** [comment]
Thanks much both for your explanations.  And @petkaantonov yeah I was looking at exactly that code and didn't understand why they designed it that way - probably my root confusion in the first place.  I love open source, but sometimes it can be unwieldy.

**Comment by benjamingr** [comment]
@olsonpm the alternative for its source to be available is for it to have been closed source and we wouldn't know :D 

You can open an issue in their tracker if you'd like.
