### ISSUE TITLE
promisifyAll() fails in v2.9.1

### ISSUE THREAD

**Issue by timotm** [petkaantonov/bluebird#466]
It seems that at least in teh latest release, promisifyAll() fails with `escapeIdentRegex` being undefined, and it further seems that this conditional is new compared to working 2.8.2 release:

https://github.com/petkaantonov/bluebird/blob/58630f7e29bedd70dc818d2a8e60cda46c860c43/js/browser/bluebird.js#L3108

**Comment by petkaantonov** [comment]
Thanks, fixed in the [2.9.2 release](https://github.com/petkaantonov/bluebird/releases/tag/v2.9.2)
