### ISSUE TITLE
chainFinally: Execute at end of the chain.

### ISSUE THREAD

**Issue by andreialecu** [petkaantonov/bluebird#472]
I have a particular scenario in which I need to be able to have a method called when the entire chain of promises has finished, but I can't put the method at the end of the chain. Here's an example:

```
promise.chainFinally(chainDone).then().then().catch().finally();
```

I need chainDone to be called at the very end of the chain, after all other methods. Is there any way to do this?

From what I can see, there's already some state passed in between thenables such as for `.bind()`, This wouldn't be particulary hard to implement if it's not already implemented. Is there any other way?

I need to do this because I have a promise returned from a method, and then there are thenables added by other callers in other places, but I still need to know when the chain is done.

**Comment by benjamingr** [comment]
If you can implement this problem you deserve a Turing award and probably a million dollar prize. This is undecidable. 

A similar question is: given a program, write another program that tells you whether or not it terminates.

**Comment by andreialecu** [comment]
Perhaps I didn't explain this clearly enough, considering the promise is not resolved, when you have this chain:
```
promise.then().then().catch()
```
There are 3 promises added synchronously. It's easy to determine that we only have 3 here through: https://github.com/petkaantonov/bluebird/blob/master/src/promise.js#L555

If you later check whether all 3 promises are resolved, you can determine whether to call `.chainFinally()` or not.

An alternative would be to expose a property on the main promise `chainedPromises` which you could then inspect and see whether all promises are resolved.

**Comment by andreialecu** [comment]
Actually `chainedPromises` would be enough for my purposes, because I can then do `process.nextTick(function() { Promise.all(chainedPromises, function() { ...finally... }))` for mostly the same functionality.

**Comment by benjamingr** [comment]
How do you know when no more promises will be added?

**Comment by andreialecu** [comment]
I can control that. 

I've settled with just needing the `ChainedPromises` property, possibly accessible through `PromiseInspector` . I can then go through all children, considering it can be a tree of thenables, and collect all the promises into an array and feed them into a `Promise.all()` call.

Do you see anything wrong with this property? Shall I do a PR for it?

**Comment by benjamingr** [comment]
@andreialecu 

I still don't understand - how would you know when no more promises will be added to the chain?

**Comment by andreialecu** [comment]
Here's an example:

```javascript
var promise = Promise.resolve(1);
process.nextTick(function() {
  var allPromises = getAllChainedPromises(promise); // to be implemented
  assert(allPromises.length === 2);
  Promise.all(allPromises, function() { console.log('all promises done'); }
});
promise.then(Promise.resolve(2)).then(Promise.resolve(3))
```

bluebird doesn't have to care how I implement my code, I just need access to all the Promise chain and that's it.

**Comment by benjamingr** [comment]
@andreialecu what if a handler is added asynchronously?

(Also, you're using `then` wrong in the example, `then` takes a function - if you pass it a promise instead of a function it will ignore it. Your `.all` is likely meant to be a `.all([allPromises]).then(func...` I assume)

**Comment by andreialecu** [comment]
It was pseudocode. A handler won't be added asynchronously in my use case, I already know all the quirks which is why I mentioned "I can control that" in a previous message.

**Comment by benjamingr** [comment]
@andreialecu  right, but you have _no control_ how and when handlers will be added once you return the chain. This sounds like it could introduce bugs.

If you're creating a resource and want something to happen when the resource is released you can use `.using` with `.disposer` or implement the disposer pattern yourself:

```js
function foo(){
    return getDb(); // I want to release the DB so chainFinally would be nice here
}

var res foo().then(makeQuery); // if I don't close the connection I just leaked a db connection
                                                   // if I had chainFinally I could close it in `foo`
```

Since the above is theoretically impossible in the general case. You can instead do this:

```js
function foo(fn){
    var _db = null;
    return getDb().then(function(db){
         _db = db;
         return fn(db);
    }).finally(function(){ _db.close(); })
}

foo(function(db){
    return db.query("...")
}).then(function(result){
    // db closed for us here
});

//Or in the above example:
    foo(db);
```

This pattern is similar to a C# `using`, a python `with` or a java try with resource. If you need to work with multiple resources at once please do consider using  `Promise.using` as it is very robust compared to doing it manually for multiple resources at once.

**Comment by andreialecu** [comment]
As far as I can tell `Promise.using` is the same as `finally` is it not?

In my example above, if I used `using` on the initial promise, it would call immediately once it was resolved, regardless of what other thenables follow it.

**Comment by benjamingr** [comment]
@andreialecu what problem are you actually solving here? Why do you need to do this?

**Comment by andreialecu** [comment]
I have a method that returns a promise to which there can be various subscribers. I need to know from inside this method when all the subscribers have finished doing their work. 

Before you suggest that I add other methods to be called or anything of that nature, that would've probably been best, but this is an existing API that I can't change. I'm fine with assuming that all the thenables will be added synchronously immediately after the method returns the promise and that on `nextTick` they will all be there. This will be documented.

**Comment by benjamingr** [comment]
I don't think we're interesting in supporting a use case you're aware is not the best solution and would need to change anyway.

That said, here is how I'd do it given your constraint using a semaphore:

    function getResource(){
         var count = 0;
         var db = getDb();
         return Promise.method(function(fn){
              try{
                   count++;
                   return fn(db).finally(function(){ 
                       count--;
                       if(count === 0) return db.close(); // close the resource
                    });
              } finally {
                   count--;
              }
         });
    };

Usage would be something like

    var handle = getResource();
    // call site 1
    handle(function(db){
          return queryAsync(...);
     }); // chain to use value

    // call site 2
    handle(function(db){
          return queryAsync(...);
     }); // chain to use value

    // call site 3
    handle(function(db){
          return queryAsync(...);
     }); // chain to use value

The db will be closed when all of these finished _assuming they were all added synchronously_. I still don't think this is the best approach but given they have to share the initial value (the promise in your case) and you can't make a bigger scale refactor this is how you could go about it.

**Comment by andreialecu** [comment]
The call sites use the regular promise methods like `.then()`, I can't change those. I'd need to monkey patch `.then()` in the returned promise or there should be another hook in bluebird where I could implement the semaphore in.

**Comment by petkaantonov** [comment]
You could indeed monkey patch `.then` on the promise before you return it, no?

**Comment by andreialecu** [comment]
@petkaantonov actually that is exactly what we're doing, but there are other methods in bluebird (catch/finally/caught/etc). They seem to all delegate to _then, Is it safe to monkey patch the private `_then` ?

**Comment by petkaantonov** [comment]
It depends what your monkey patch will do but generally yes as _then cannot change its signature due to https://github.com/petkaantonov/bluebird/blob/master/src/thenables.js#L13-L23
