### ISSUE TITLE
Parallel for multiple catch blocks in synchronous code

### ISSUE THREAD

**Issue by petkaantonov** [petkaantonov/bluebird#475]
Currently doing

```js
    .then(...)
    .catch(Predicate1, ...)
    .catch(Predicate2, ...)
    .catch(Predicate3, ...)

```

Is actually same as

```js
try {
    try {
        try {
            ...
        } catch (Predicate1(e)) {
            ...
        }
    } catch (Predicate2(e)) {
        ...
    }
} catch (Predicate3(e)) {
    ...
}
```

But there is currently no way to do the equivalent of:

```js
try {
    ...
} catch (Predicate1(e)) {
    ...
} catch (Predicate2(e)) {
    ...
} catch (Predicate3(e)) {
    ...
}
```
This could be an issue in some cases as the later predicates might catch errors thrown from earlier predicates while in a catch "group" the parallel catch blocks don't catch thrown errors from the catch blocks that belong to the group.

This is actually very simple to implement, it's just that the api for doing it has no perfect choice as all the handlers need to be attached in one call.

Some ideas:

```js
.$()
    .catch(Predicate1, ...)
    .catch(Predicate2, ...)
    .catch(Predicate3, ...)
.$()
```

```js
.begin()
    .catch(Predicate1, ...)
    .catch(Predicate2, ...)
    .catch(Predicate3, ...)
.end()
```

```js
.catch(
    [Predicate1, ...],
    [Predicate2, ...],
    [Predicate3, ...]
)
```

**Comment by spion** [comment]
Another alternative:

```js 
.catchMany(
  predicate1, handler1,
  predicate2, handler2,
  ...)
```

**Comment by benjamingr** [comment]
I like this idea but I'm not sure I have an actual use case for it.

**Comment by petkaantonov** [comment]
Yea keepin' it simple
