### ISSUE TITLE
"Infinite" promise chains, a bad thing?

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/bluebird#477]
I sometimes have values that are used the entire lifetime of the application, are regularly updated, and in some way depend on their old value:

```js
var count = fetchRemoteCount();

setTimeout(function(){
	count = Promise
		.join(count, fetchRemoteCount())
		.spread(function( locale, remote ){
			return locale + remote;
		});
}, 10000);
```

Is this going to leak memory or it is in another way an anti-pattern?

**Comment by benjamingr** [comment]
There used to be an issue with these and the old GC code but there isn't anymore. 

I use this pattern for caching in several places and haven't had any issues.

If issues do arise please report them and they'll be fixed.

**Comment by petkaantonov** [comment]
No it's not going to leak memory but make sure to use the latest version or at least 2.8+.

However just one error will stop the loop so if you truly want it to be infinite as long as the server is up, you'd do:

```js
Promise.resolve(0).then(function loop(local) {
    return fetchRemoteCount()
        .then(function(remote) {
            return local + remote;
        })
        .catch(function() {
            return local;
        })
        .delay(10000)
        .then(loop);
});
```

**Comment by benjamingr** [comment]
@petkaantonov how is he ever going to get any count out of that? To the consumer that's a never resolving promise :D

**Comment by petkaantonov** [comment]
@benjamingr oh right xD

**Comment by tjconcept** [comment]
Great, thank you both!
