### ISSUE TITLE
self not defined in captured_trace.js

### ISSUE THREAD

**Issue by Phoenixmatrix** [petkaantonov/bluebird#479]
This seems to be a recent regression from the refactor that changed global references to "self" (or something). Looking at captured_trace.js, I can't see where self gets defined (and neither does my browser, hehe). Reverting to an older version fixes the issue.

**Comment by petkaantonov** [comment]
https://github.com/petkaantonov/bluebird/issues/478#issuecomment-72399150

**Comment by petkaantonov** [comment]
I backported the fix from 3.0 to 2.9.6
