### ISSUE TITLE
Feature Request: Add utility function Promise.first()

### ISSUE THREAD

**Issue by timhuff** [petkaantonov/bluebird#480]
I'm frequently in a position where I want to say "Try this. If that doesn't work, try this. If that doesn't work, try this". It'd be nice to be able to write:
```javascript
Promise.first([
    method1,
    method2,
    method3
], {concurrency:1})
```

It appears that, currently, you can get bluebird to have this desired behavior, but it's not very clean. I might just be missing a useful pre-existing pattern, though.

**Comment by benjamingr** [comment]
Note that methods that take the concurrency parameter are not ordered so in your case (if it behaves like map and filter) you might get `method2()` or `method3` called first.

Moreover, promises represent an eventual value not an operation - once you get a promise you've already started so in your example they all run concurrently anyway.

**Comment by benjamingr** [comment]
By the way here it is as a promise returning function
```js
function chainPromises(arrayOfFunctions){
    return Promise.resolve().then(function loop(){
        if(arrayOfFunctions.length === 0) throw new Promise.OperationalError("None good");
        return arrayOfFunctions.shift()().catch(loop);
    });
}
```
Or as a coroutine:

```js
var chainFunctions = Promise.coroutine(function*(){
    for(var i = 0; i < arrayOfFunctions.length; i++){
         try{
                var res = yield arrayOfFunctions.shift()();
                return res; // or do more processing
         } catch(e){
                // suppress catch, let iteration continue
         }
    }
    throw new Promise.OperationalError("...");
}
```

**Comment by timhuff** [comment]
Yes, serial, ordered behavior would be desired.

It would still represent an eventual value. That value would be "the value of the first eventual value". I spoke of operations because my code is often structured as operations returning eventual values (method1(), method2(), and method3() would all be functions returning eventual values)

Your code examples demonstrate the behavior I had in mind and, in practice, your `chainPromises` functions is effectively what I do. However, it's not nearly as clean nor concise as `Promise.first(arrayOfPromises)`. I made the suggestion because I feel this is a common use-case that I run into and felt that such a utility function would be useful for me and for others.

**Comment by benjamingr** [comment]
Just to be clear, if you have an array of promises _all the API calls have
already been made_, all the operations have executed and you're just
looking for the first that is not rejected.

**Comment by timhuff** [comment]
I'm sorry. You're right. It's early in the morning here. It would be `Promise.first(arrayOfFunctions)`, not `Promise.first(arrayOfPromises)`. I made similar mistakes throughout what I was saying.

**Comment by timhuff** [comment]
I also feel that a proper implementation of this hypothetical utility function would make use of `Promise. AggregateError` and not simply an `OperationalError` with `"None good."` (but I understand that your example wasn't intended to be rigorous).

**Comment by timhuff** [comment]
I've also updated my original post to indicate that I'm talking about handling an array of functions and not an array of promises. Excuse my clumsiness, there.

**Comment by timhuff** [comment]
Considering how badly I botched this issue, I'm going to close it and open a new, more carefully-worded, one so that we can have a proper discussion on the matter.

**Comment by benjamingr** [comment]
Sure, it could be great if you can provide:

 - Motivation
 - Common use cases
 - Why this can't be solved cleanly with current functions and what the current solution you have is.

**Comment by petkaantonov** [comment]
I really doubt this is a common enough need that it should be implemented in the core.

If you need it once or twice, use

```js
Promise.reduce([
    method1,
    method2,
    method3
], function(result, fn) {
   return result ? result : fn().catch(function(){ return null; });
}, null);
```

If you use it more than once or twice, write a helper function.

**Comment by timhuff** [comment]
@petkaantonov Thank you! I agree. Your usage of `reduce` makes the solution succinct and readable enough. While I feel that it's a fairly common use-case, I don't think it's nearly common enough to necessitate an addition to the API. I'm not going to bother creating a new issue.

**Comment by timhuff** [comment]
An issue with your solution, though, is that it completely ignores any errors or exceptions coming out of the functions. Also, if the resolved result is, itself, `null`, then that would be ignored.
I ended up just making a helper function for this, written in coffeescript. In case anyone else finds this useful. Considering how nuanced this issue is and the fact that it is a use case that comes up from time to time, I'm going to go ahead and create that issue after all.
```coffee
Promise.first = (args..., methods=[], thisArg)->
	if methods.length == 0
		return Promise.resolve()
	errors = new Promise.AggregateError
	firstResolvedMethod = (n=0)->
		methods[n].apply thisArg, args
		.error (error)->
			errors.push error
			if n < methods.length-1
				return firstResolvedMethod n+1
			else
				return Promise.reject errors
	return firstResolvedMethod()
```
