### ISSUE TITLE
Feature Request: Add utility function for serially chaining handlers and returning the first resolved value

### ISSUE THREAD

**Issue by timhuff** [petkaantonov/bluebird#481]
I'm frequently in a position where, in an attempt to acquire some resource, I want to say "Try this. If that doesn't work, try this. If that doesn't work, try this". It'd be nice to be able to write:
```javascript
Promise.first(params, [
    method1,
    method2,
    method3
]).then(function(value){
//do something with value
})
```

It appears that, currently, you can get bluebird to have this desired behavior, but it's not very clean and requires either having a helper function laying around or a bunch of unnecessary code.

I believe there are many use-cases for such a utility function. It would be useful any time when there's a preferred method of acquiring a resource and then one or more alternate methods, that are perhaps less efficient. An example of a use case for this would be:
```javascript
function findStudents(query){
	Promise.first(query, [
		Students.findById
		Students.findByTeacher
		Students.findByMajor
	])
	.then(function(students){
		//do something with students
	})
}
```

My use-case that inspired this request is a reverse image lookup. Sometimes I'll have an exact match on SHA256 hash if that doesn't work, sometimes I'll have a close match on our proprietary image hash, and if that doesn't work and I can't find any matches, I'll upload the file and then say "ok, NOW it exists, here it is".

A rough implementation of the behavior I had in mind would be
```coffee
Promise.first = (args..., methods=[], thisArg)->
	if methods.length == 0
		return Promise.resolve()
	errors = new Promise.AggregateError
	firstResolvedMethod = (n=0)->
		methods[n].apply thisArg, args
		.error (error)->
			errors.push error
			if n < methods.length-1
				return firstResolvedMethod n+1
			else
				return Promise.reject errors
	return firstResolvedMethod()
```

This topic was discussed [here](https://github.com/petkaantonov/bluebird/issues/480) a little but I kind of botched the whole thing up by not thinking carefully enough about it beforehand. I created a new issue in the hopes of having a more structured discussion on the topic.

**Comment by timhuff** [comment]
I'd also like to note that, for the student example above, I assume that each function expects to have to extract the relevant pieces of information from the query object, as it's passed in. This is not typically how I would expect things to work. I work mostly in coffeescript, where I imagine the code would look more like:
```coffee
findStudents = (query)->
	Promise.first [
		->Students.findById(student.id)
		->Students.findByTeacher(student.teacher_name)
		->Students.findByMajor(student.major)
	]
	.then (students)->
```

**Comment by petkaantonov** [comment]
It seems unusual that methods like findByMajor or findByTeacher would throw when none is found, instead of returning null?

**Comment by spion** [comment]
@petkaantonov I don't think this feature is necessary, but in my code its not unusual at all. Its fairly common to forget to check a null value and get a NPE, so throwing is much better in this case. (If your code only deals with the happy case, the error is indistinguishable from a fatal error anyway)

**Comment by timhuff** [comment]
That's true and, perhaps, in practice, there would need to be something more along the lines of:
```coffee
throwOnNull = (result)-> 
    if !result?
        return Promise.reject new Error 'None Found'
    result
findStudents = (student)->
    Promise.first [
        ->Students.findById(student.id).then throwOnNull
        ->Students.findByTeacher(student.teacher_name).then throwOnNull
        ->Students.findByMajor(student.major)
    ]
```
Or something. But the alternative currently would be something like:
```coffee
Students.findById(student.id)
.then (result)->
    if result?
        return Promise.resolve result
    Students.findByTeacher(student.teacher_name)
    .then (result)->
        if result?
            return Promise.resolve result
        Students.findByMajor(student.major)
        .then (result)->
            if result?
                return Promise.resolve result
.then (actualResult)->
    #we use the result
```
The nesting increases with each additional failed method. The nesting can be eliminated like so:
```coffee
throwOnNull = (result)->
    if !result?
        return Promise.reject new Error 'no result'
Students.findById(student.id)
.then throwOnNull
.error (error)->
    if error.message != 'no result'
        return Promise.reject error
    Students.findByTeacher(student.teacher_name)
.then throwOnNull
.error (error)->
    if error.message != 'no result'
        return Promise.reject error
    Students.findByMajor(student.major)
.then (actualResult)->
    #we use the result
```
But, as you say, that's a bit of an abuse of throwing errors and I'm not a huge fan of it. However, one of the major positives of promises is how it prevents the ever-increasing callback situation seen in the former example.

**Comment by spion** [comment]
@timhuff I've always found the "exceptions for exceptional things" argument unconvincing anyway :) as its sometimes impossible to know what is or isn't exceptional from the consumer's point of view, and even if it is, drawing the line is very subjective.

**Comment by petkaantonov** [comment]
@spion I get throwing for not found ID's (where it's literally exceptional because your app either generated wrong links or is being hack attempted) but throwing for fuzzy searches that return 0 results?

**Comment by spion** [comment]
@petkaantonov beats returning null for sure. Otoh if the return type is a list, I'd just return an empty one.

**Comment by petkaantonov** [comment]
@spion  well yea, the method is called students.findByTeacher - a teacher is gonna have more than 1 student. 1 major is gonna have more than 1 student studying it too.

**Comment by timhuff** [comment]
Yea, I'm not a huge fan but I'm not against it. I'll return an empty array on a find request that finds nothing - the error will just be caught at the end of the chain and turned into a response of `[]`. But this isn't really a matter of this, particular, student example. I've come across this issue in one form or another many times in the past. One of my favorite things about bluebird is the differentiation between `.error` and `.catch`. Thinking on past use-cases, I'm beginning to suspect that what I'm actually after is a `complete`, `.completed` pairing where `complete`:`resolve`::`throw`:`reject`. Calling `reject` escapes the pipe and jumps to the closest `.error`. Perhaps a third parameter, `complete` that jumps to the nearest `.completed` handler is what I'm actually after. Seems like a much more fundamental change, though.

**Comment by timhuff** [comment]
Something like:
```coffee
completeOnFind = (result)->
    if result?
        return Promise.complete result
Students.findById(student.id)
.then completeOnFind
.then -> Students.findByTeacher(student.teacher_name)
.then completeOnFind
.then -> Students.findByMajor(student.major)
.then completeOnFind
.completed (actualResult)->
    #we use the result
```

**Comment by timhuff** [comment]
Or perhaps I'm just after an `.else`, which is a `.then` that only runs for falsey eventual values:
Something like:
```coffee
Students.findById(student.id)
.else -> Students.findByTeacher(student.teacher_name)
.else -> Students.findByMajor(student.major)
.then (actualResult)->
    #we use the result
```

**Comment by spion** [comment]
```js
function ifNull(action) {
  return function(result) {
    if (result != null) return result;
    else return action()
  }
}
```

```coffee
Students.findById(student.id)
.then ifNull -> Students.findByTeacher(student.teacher_name)
.then ifNull -> Students.findByMajor(student.major)
```

**Comment by timhuff** [comment]
@spion Yea, I just realized I can do that and it's so simple. I've been using bluebird (and prior promise libraries) for some time now. Had a major "whoosh" moment. It prevents a few niceties like that `AggregatedError` but it's much simpler. I still think having an `.else` syntactic sugar for that might be nice.

**Comment by spion** [comment]
The nice thing about this approach is that you can just plugin in any other combinator instead, and get the same functionality for values other than `null` :)

**Comment by timhuff** [comment]
That's true. I mentioned I like to respond to `find` queries that come up empty with `[]` rather than `null`. I could check for `result.length`.

**Comment by spion** [comment]
tuning the FP all the way up

```coffee

iff = (condition, action) -> (result) -> 
  if condition result
    action result
  else result

isNull = (val) -> !val?
isEmpty = (val) -> val.length == 0

Students.findById(student.id)
.then iff isNull, -> Students.findByTeacher(student.teacher_name)
.then iff isEmpty, -> Students.findByMajor(student.major)

```

**Comment by timhuff** [comment]
Nice.
