### ISSUE TITLE
Mongoose 'pre' hooks stop working in 2.9.7

### ISSUE THREAD

**Issue by klimashkin** [petkaantonov/bluebird#488]
I'm using bluebird and mongoose together, i.e. ```Bluebird.promisifyAll(require('mongoose'));```
After update from bluebird 2.9.6 to 2.9.7,  [mongoose schema hooks](http://mongoosejs.com/docs/api.html#schema_Schema-pre) stopped calling.
As I understand this is due to a change in ```promisifyAll``` ```this``` behaviour

**Comment by petkaantonov** [comment]
Cannot make npm release right now but you can test with master by cloning

    git clone https://github.com/petkaantonov/bluebird.git
    cd bluebird && npm install
    node tools/build --main
    // generated files are in js/main folder
