### ISSUE TITLE
Method name already has 'Async' suffix

### ISSUE THREAD

**Issue by olsonpm** [petkaantonov/bluebird#491]
In API.md under [promisifyall](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object), it is explained:
> If a method name already has an "Async"-suffix, it will be duplicated. E.g. getAsync's promisified name is getAsyncAsync.

However I have also received [this error before](https://github.com/petkaantonov/bluebird/wiki/Error:-Cannot-promisify-an-API-that-has-normal-methods)
> This error indicates you have tried to call Promise.promisifyAll on an object that already has a property with the Async suffix:

The above error is thrown [from line 40 in src/promisify.js](https://github.com/petkaantonov/bluebird/blob/master/src/promisify.js#L40-L56)
```
    // Verify that in the list of methods to promisify there is no
    // method that has a name ending in "Async"-suffix while
    // also having a method with the same name but no Async suffix
```

I assume the documentation just needs to be updated, but wanted to create an issue before blindly creating a pr.

**Comment by benjamingr** [comment]
?

**Comment by olsonpm** [comment]
Ah just got confused with the wording.  The above is perfectly valid.
