### ISSUE TITLE
BlueBird appears to throws fatal error for rejection that is supposed to be handled by .settle

### ISSUE THREAD

**Issue by dantman** [petkaantonov/bluebird#494]
I'm having an issue in some code I'm writing that looks like an error in bluebirds 'smart' uncaught error throwing.

Here are the contents of two relevant files (bin/cron.js and lib/git.js):

https://gist.github.com/dantman/f30bcd98ac92e8005170

The code runs fine except for one git repo where `git fetch` gives an error code, leading to my runs of bin/cron.js failing with:
```
Fetching WikibaseRepository
WikidataEntitySuggester: From https://git.wikimedia.org/git/mediawiki/extensions/WikidataEntitySuggester
WikidataEntitySuggester:  * branch            HEAD       -> FETCH_HEAD
Fetching WikibaseQuery
WikibaseView: From https://git.wikimedia.org/git/mediawiki/extensions/WikibaseView
WikibaseView:  * branch            HEAD       -> FETCH_HEAD
Fetching WikibaseMobile
WikibaseSolr: From https://git.wikimedia.org/git/mediawiki/extensions/WikibaseSolr
WikibaseSolr:  * branch            HEAD       -> FETCH_HEAD
Fetching WikibaseLib
Wikidata: From https://git.wikimedia.org/git/mediawiki/extensions/Wikidata
Wikidata:  * branch            HEAD       -> FETCH_HEAD
WikibaseRepository: fatal: Couldn't find remote ref HEAD

{extensionservice}/node_modules/bluebird/js/main/promise.js:658
            throw e;
                  ^
Error: WikibaseRepository: git returned exit code 128
    at {extensionservice}/lib/git.js:110:29
From previous event:
    at Object.pass ({extensionservice}/lib/git.js:106:6)
    at Object.exports.fetch ({extensionservice}/lib/git.js:209:13)
    at git.isCloned.then.then.then.HEAD.then.git.lsTree.tree ({extensionservice}/bin/cron.js:30:17)
From previous event:
    at gerrit.getExtensions.tap.map.concurrency ({extensionservice}/bin/cron.js:29:6)
    at process._tickCallback (node.js:419:13)
From previous event:
    at Object.<anonymous> ({extensionservice}/bin/cron.js:19:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
extensionservice daniel$ 
```

The problem is that I don't appear to have any spots where I've lost track of a promise. git.pass returns the rejection to git.fetch, which returns it to the call in cron.js which returns it to the chain that is returned to .map. Which should keep a reference to the rejection and pass it on to .settle which should stop the error from continuing to .done().

**Comment by petkaantonov** [comment]
You have misunderstood `.settle()`, which is equivalent to `Promise.settle(thePromise)` - settle only settles the promises inside the passed array, but if it was never passed an array to begin with it can't do that.

I suggest removing settle and calling .reflect() at the end of the mapper function, which will have the expected effect.

Also .done() usage is discouraged.
