### ISSUE TITLE
splay: bluebird.all for dictionaries of promises.

### ISSUE THREAD

**Issue by bitdivine** [petkaantonov/bluebird#497]
Lol.  Just encountered functions called q0-q12 being passed in to bluebird.all and then read into sanely named variables using spread.  May I suggest this instead?  Complete with one letter variables reused at every available opportunity.

function d2l(d){var k=Object.keys(d),v=k.map(function(k){return d[k];});return k.concat(v);}
function l2d(l){var d={};l.slice(l.length/2).forEach(function(v,i){d[l[i]]=v;});return d;}
var bb = require('bluebird');
bb.flay = function(d){return this.all(d2l(d)).then(l2d);}; 

r = require('request-promise');

bb.flay(
{a:r('http://tek.blue')
,b:r('http://tek.red')
}).then(console.log.bind(null,"Hey, look, I got a dictionary of results:"));

**Comment by benjamingr** [comment]
I have no idea what you're asking here. Please formulate your request clearly and use [github formatting](https://help.github.com/articles/markdown-basics/). 

If I had to _guess_ what you're asking about - you're looking for `Promise.props`.

**Comment by bitdivine** [comment]
It is indeed. Thanks.
