### ISSUE TITLE
Promise.reduce skips first array element.

### ISSUE THREAD

**Issue by RichAyotte** [petkaantonov/bluebird#500]
http://jsfiddle.net/RichAyotte/t0rjhrab/

```js
var pets = ['cat', 'dog', 'bird'];
Promise.reduce(pets, function(_, p) {
    console.log(p);   
});
```
Log
```txt
dog
bird
```

**Comment by cantremember** [comment]
your 0th argument is being used as the initial value for the reduce

http://jsfiddle.net/cantremember/766up1an/

```
var pets = ['cat', 'dog', 'bird'];
Promise.reduce(pets, function(_, p) {
    console.log(p);
    return _ + ',' + p;
}).then(function(_) {
    console.log('=', _); // => 'cat,dog,bird'
});
```

whereas pass a 3rd argument, such as `'mouse'` to Promise#reduce and you'll see each element of your Array being visited

**Comment by benjamingr** [comment]
Thanks, what @cantremember said is correct. This is just like `Array#reduce`

**Comment by RichAyotte** [comment]
Ah yes, thanks. Even null works.
```js
Promise.reduce(pets, function(_, p) {
 console.log(p);   
}, null);
```

**Comment by petkaantonov** [comment]
Are you sure you should even be using reduce?

**Comment by RichAyotte** [comment]
I'm building a promise chain from an array. Is there a simpler way or convenience function for this?
```js
	return Promise.reduce(classes, function(_, c){
		return drop(c).then(function(){
			console.log(c + ' dropped');
		});
	}, null);
```

**Comment by RichAyotte** [comment]
Something like this would be nice. Like map but chain instead.
```js
Promise.chain(Array, Function) -> Promise
```

**Comment by phpnode** [comment]
@RichAyotte could be wrong but it sounds like you're running into this issue: https://github.com/petkaantonov/bluebird/issues/134

**Comment by RichAyotte** [comment]
@phpnode Nice thread, thanks. It's exactly what I was looking for. I've got lots of options now between reduce, each and map. Figuring out which one is the most expressive for the task at hand is the challenge now :)

**Comment by petkaantonov** [comment]
```js
return Promise.each(classes, function(c) {
        return drop(c).then(function(){
            console.log(c + ' dropped');
        });
});
```

**Comment by RichAyotte** [comment]
@petkaantonov Yep, that's the one that I went for. :+1:

**Comment by phpnode** [comment]
@RichAyotte FYI if this actually happens to be related to [oriento](/codemix/oriento) then it's FIFO anyway, so you can probably just:
```js
return Promise.map(classes, drop)
```

**Comment by RichAyotte** [comment]
@phpnode It is :)
```js
exports.down = function (db) {
	return Promise.each([
		'InstitutionClass'
		, 'Establishment'
		, 'EstablishmentType'
		, 'Address'
		, 'AddressUnitDesignator'
		, 'AddressStreetType'
		, 'AddressStreeDirection'
		, 'AddressCivicNumberSuffix'
		, 'Region'
		, 'RegionType'
		, 'OrderItem'
		, 'Order'
		, 'Meal'
		, 'Drink'
		, 'contains'
		, 'FoodIngredient'
		, 'Food'
		, 'FoodType'
		, 'Person'
		, 'Obj'
	], db.class.drop);
};
```

**Comment by cantremember** [comment]
the API.md doesn't state otherwise, but `#each` executes its Promises in parallel, much like `#all`, correct?

**Comment by petkaantonov** [comment]
nope, its sequential

**Comment by cantremember** [comment]
thanks, good to know. i must have overlooked that
