### ISSUE TITLE
Promisify without suffix

### ISSUE THREAD

**Issue by whitecolor** [petkaantonov/bluebird#504]
I wonder why not make it possible to promisify methods without using suffix, just replace them with promise returning version, but leaving them callback-compatible.

Of course it may break things but whole `promisify` thing is a huge breaker if not used with care.

**Comment by petkaantonov** [comment]
It's not possible to make an arbitrary function both callback-compatible and promise compatible in the general case. It also would mean that the original reference cannot be updated because it has been acquired at promisification time, this breaks mongoose hooks for example.

**Comment by whitecolor** [comment]
> It's not possible to make an arbitrary function both callback-compatible
I understand this. Why not make just posible for custom scenario? Where one point the methods that should by promisified without suffic with care and understanding?

**Comment by petkaantonov** [comment]
If you have a scenario where this would actually work, can't you just use `promisify`? 

e.g. `fs.readFile = Promise.promisify(fs.readFile)`

**Comment by whitecolor** [comment]
Yes, it works, didn't think about it, thanks!
