### ISSUE TITLE
AFunction.prototype should be set in a variable for minification

### ISSUE THREAD

**Issue by marchant** [petkaantonov/bluebird#506]
The pattern used in the code today is to have AFunction.prototype.method = ... .Not only this is potentially slowing parsing as prototype is accessed over and over, that pattern works against minification.
function Promise(resolver) {...}
var PromiseP = Promise.prototype;
or simply 
var prototype =  Promise.prototype;

then prototype.toString = function () {...}; instead of Promise.prototype.toString = function () {...} would minify much better.

Doing this throughout bluebird could lead to serious gains

**Comment by petkaantonov** [comment]
The only size that matters is minified+gzipped, and I doubt this will make any real difference due to how gzip works.

**Comment by benjamingr** [comment]
Yeah the benefit from prototype lookup during the initial parsing is completely negligible and sounds like a wrong place to optimize.

**Comment by benjamingr** [comment]
@marchant unless you have anything else to add or can show a gain in doing this I think we can close this.
