### ISSUE TITLE
get "TypeError: this._trace is undefined" at Promise.prototype._attachExtraTrace

### ISSUE THREAD

**Issue by maxlath** [petkaantonov/bluebird#512]
hi,

Using bluebird browser version, with `Promise.longStackTraces()`, I got this error:
```
Uncaught TypeError: Cannot read property 'attachExtraTrace' of undefined ( bluebird.js:2321 )
Promise._attachExtraTrace ( bluebird.js:2321 )
Promise._settlePromiseFromHandler ( bluebird.js:2223 )
Promise._settlePromiseAt ( bluebird.js:2378 )
Promise._settlePromises ( bluebird.js:2495 )
Async._drainQueue ( bluebird.js:145 )
Async._drainQueues ( bluebird.js:155 )
Async.drainQueues ( bluebird.js:80 )
```

I resolved the issue by changing 
```
Promise.prototype._attachExtraTrace = function (error) {
    if (debugging && canAttachTrace(error)) {
        this._trace.attachExtraTrace(error);
    }
};
```
to
```
Promise.prototype._attachExtraTrace = function (error) {
    if (debugging && canAttachTrace(error) && this._trace != null) {
        this._trace.attachExtraTrace(error);
    }
};
```
but I guess I don't get this extra trace attached then.

**Comment by petkaantonov** [comment]
From the documentation:

> Long stack traces cannot be disabled after being enabled, and **cannot be enabled after promises have alread been created**

In 3.0 the check for whether promises have already been created covers more cases and a more descriptive error will be thrown

**Comment by petkaantonov** [comment]
I would also recommend setting the environment variable `NODE_ENV=development` (or `BLUEBIRD_DEBUG=1` if you want to enable it in production) over using runtime configuration as it enables long stack traces for all bluebird instances and does so before promises can even be created.

**Comment by maxlath** [comment]
That was it indeed, thanks!
The issue was on the client-side, so I can't use environment variable; instead I just initialize a `env_config` module at the very beginning of my app initialization, where I call `Promise.longStackTraces()`
