### ISSUE TITLE
.cancel() can cause an infinite loop

### ISSUE THREAD

**Issue by JLRishe** [petkaantonov/bluebird#520]
It looks like there are certain situations where it's possible for `._cancel()` to enter a tight infinite loop that basically locks up the execution context:

http://stackoverflow.com/questions/28811232/why-does-cancelling-a-bluebird-promise-in-a-callback-stop-setinterval/28815027#28815027

This can probably be chalked up to user error, but it seems like it would be possible to detect a cycle in the promise chain and avoid have everything come to a grinding halt.

It appears that there are talks about [overhauling the cancellation system](https://github.com/petkaantonov/bluebird/issues/415), but I wanted to make a note of this nonetheless, just in case safeguards could be added somewhere down the road.

**Comment by petkaantonov** [comment]
Promises/A+ requires only immediate cycle checking and it's a relatively rare user error, so I rather avoid it. 2.x will only receive important bug fixes, have you checked what happens in 3.0?

**Comment by rhys-vdw** [comment]
Okay. Well, I feel silly. How are you meant to cancel a Promise?

The code in stackoverflow is how I understood it was to be done. I think the documentation needs better examples. I'm quite confused now.

Why doesn't this cancel, for instance:

```CoffeeScript
p = Promise.resolve('value')
.cancellable()
.then (value) ->
  console.log('1st', value)
  p.cancel()
  return
.then (value) ->
  console.log 'I wasn\'t cancelled!'
.catch Promise.CancellationError, ->
  console.log('cancelled')
```

**Comment by petkaantonov** [comment]
Well, what is there to cancel? There is no operation pending to cancel.

**Comment by rhys-vdw** [comment]
I thought it prevented the promise from propagating down the chain. I guess I've misinterpreted the purpose of cancellation?

**Comment by petkaantonov** [comment]
The purpose of cancellation is not related to control-flow but to cancel operations. Say you made a http request to fetch data for some widget, but the user closes that widget before it arrives. So in that case you want to cancel the request because it would otherwise complicated the resulting code that needs to check if the request was relevant anymore. It also frees up resources faster but it's not really relevant in this example.

**Comment by rhys-vdw** [comment]
Ah. Okay. That makes more sense to me. I guess what I need is a custom exception type, rather than cancellation. I think I just got confused by the simplified toy examples I found online.
