### ISSUE TITLE
Bluebird in JDK Nashorn

### ISSUE THREAD

**Issue by akovari** [petkaantonov/bluebird#522]
Hello,

I'd like to use Bluebird in the nashorn engine provided by JDK 8 but I am having this problem:

```
➜  browser git:(master) ✗ /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/jjs bluebird.js
bluebird.js:29 TypeError: Cannot set property "Promise" of undefined
```

More specifically:

```
javax.script.ScriptException: TypeError: Cannot set property "Promise" of undefined in <eval> at line number 29
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:586) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:570) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:525) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:521) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:187) ~[nashorn.jar:na]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) ~[na:1.8.0_25]
```

Any idea what this is about?

Thanks a lot for bluebird and your help in advance

**Comment by petkaantonov** [comment]
Bluebird assumes browser or node

**Comment by akovari** [comment]
Thanks, is this because noone has tested it before with nashorn or are there any technical reasons for this assumption?
I'd be happy to help with some testing if that's the problem.

**Comment by petkaantonov** [comment]
The module system in use is common.js require, which works in browsers by using browserify and UMD. In node it's a core feature, not sure what nashorn uses.

The schedulers checked for are WebkitMutationObserver and setTimeout, but this can be set manually anyway.

The global event system is either `process as EventEmitter` (node) or `window as EventTarget` (browser DOM).

Otherwise the code should be pure js.

**Comment by akovari** [comment]
Hmm, I don't think nashorn implements common JS :( I've found out that RSVP.js works in nashorn, so I'll probably use that. Thanks

**Comment by benjamingr** [comment]
@akovari to clarify, it's not that @petkaantonov is saying bluebird does not want to support Nashhorn, it's that none of the people involve actively uses it and no one has asked for it before. 

You can shim a `process` object as an event emitter object, `require` to just put `module.exports` as an objet and use `setScheduler` to set the scheduler to something that works in Nashhorn and it should work - let us know how it works for you

**Comment by petkaantonov** [comment]
@benjamingr process cannot be shimmed, `{}.toString` is used to check for `[object process]`

**Comment by benjamingr** [comment]
@petkaantonov not sure what JS Nashhorn runs but 

```js
var process = {
   _handlers: {},
   [Symbol.toStringTag]: function(){ return "process"; },
    on(evName, handler): {
        this.handlers[evName] = (this.handlers[evName] || []).concat(handler);
    },
    emit(evName, args...): {
         for(handler of (this.handlers[evName] || [])){
             handler(...args);
         }
    }
};
```

**Comment by petkaantonov** [comment]
@benjamingr Nashorn runs nashorn, it's a js engine implemented in java :P

**Comment by benjamingr** [comment]
@petkaantonov I meant which _version_ it runs, if it runs JS2015 (es6) that hack would work, if it doesn't that hack would not work and bluebird might have to support overriding that check or maybe opting out of the `EventTarget` thing in window (maybe try/catching it, donnu)

**Comment by akovari** [comment]
Nashorn is still ecmascript 5.1 :/

**Comment by benjamingr** [comment]
@petkaantonov then I'm in favor of making it work in some way (maybe change
the ordering of checking `[object process]`?), what do you think?

**Comment by petkaantonov** [comment]
@benjamingr no, because some jerk always shims these stuff to the extent shimming is possible (implementing entire browser model in node's global 15 levells deep in some module dependency) and innocent people suffer

**Comment by benjamingr** [comment]
@petkaantonov what about not firing events on `window` if it's not possible and shimming `window`?

**Comment by petkaantonov** [comment]
just shim everything that the browser path needs

**Comment by stefanpenner** [comment]
Nashorn introduces threads to JavaScript which changes invariants RSVP and Bluebird were built on.

I believe the only way to make these libraries work in a safe way on nashorn is to introduce some thread safe runtime wrapper. Or re-think the internals dramatically.

**Comment by benjamingr** [comment]
@stefanpenner set the scheduler to call `sync(function(){ })` maybe?

Also @petkaantonov, you've got to admit this is a pretty funny coincidence :D

**Comment by petkaantonov** [comment]
I don't think thread safety changes anything, all it gives you is that an object will not get changed by 2 threads at the same time, but 2 threads can still change an object at different times.

**Comment by phpnode** [comment]
nashorn doesn't even have things like `setTimeout()`, `setImmediate()` etc so it'd need to be a platform specific build which shims them - https://blogs.oracle.com/nashorn/entry/setinterval_and_settimeout_javascript_functions

**Comment by benjamingr** [comment]
@phpnode bluebird doesn't need these things though - since you can use `setScheduler`. 

```js
var platform = Java.type("javafx.application.Platform");
Promise.setScheduler(function(fn){
    platform.runLater(fn);
});
```

**Comment by phpnode** [comment]
@benjamingr ah, pretty nice!

**Comment by akovari** [comment]
One other option, which doesn't depend on javafx: https://gist.github.com/bripkens/8597903
I got rid of context.XMLHttpRequest and am using it with RSVP for the time being, which works fine.

**Comment by stefanpenner** [comment]
> but 2 threads can still change an object at different times which is the actual problem.

Confirm, and this what breaks the invariants most JS is written against.
