### ISSUE TITLE
Promisify certain Mongoose Objects

### ISSUE THREAD

**Issue by codeHatcher** [petkaantonov/bluebird#523]
I would like to be able to promisify the following. I know how to do it with .save but not when I am doing a .find chained with a .sort with a .select with a .exec.
```javascript
User
.findOne({username: username})
.exec(function(err, user){
   if (err) {
      //handle error
   } else {
     // handle response
   }
  });

```

**Comment by benjamingr** [comment]
Please ask usage questions on StackOverflow with the promise and bluebird tags
