### ISSUE TITLE
Bluebird fails to load in a nwjs (nodewebkit) app

### ISSUE THREAD

**Issue by NervosaX** [petkaantonov/bluebird#525]
It gives me the error:

```
[23637:0312/105955:INFO:CONSOLE(81)] "Uncaught TypeError: Cannot read property 'isStatic' of undefined", source: file://.../dist/jspm_packages/npm/bluebird@2.9.10/js/browser/bluebird.js (81)
[23637:0312/105955:ERROR:nw_shell.cc(335)] Error evaluating file://.../dist/jspm_packages/npm/bluebird@2.9.10/js/browser/bluebird.js
Uncaught TypeError: Cannot read property 'isStatic' of undefined
[23637:0312/105955:INFO:CONSOLE(2237)] "Uncaught Error evaluating file://.../dist/jspm_packages/npm/bluebird@2.9.10/js/browser/bluebird.js
Uncaught TypeError: Cannot read property 'isStatic' of undefined", source: file://.../dist/jspm_packages/system.src.js (2237)
```

I've shortened the filenames for readability.

I can confirm that it worked fine in bluebird version 2.9.3, but I'd say that after commit 98b025231501734096cb77d4d789362e780b16a0 the issue occurred.

Reading over the code in that commit, it seems to be because 
```typeof window === "undefined"```
 isn't part of the isNode check. If I add this line manually then my application runs.

**Comment by petkaantonov** [comment]
Try with at least 2.9.6+

**Comment by NervosaX** [comment]
2.9.6 works. 2.9.13 fails.
I tried every version between 2.9.7 and 2.9.13 and each failed.

**Comment by petkaantonov** [comment]
Does node webkit delete the global setImmediate function or something? That's what's being undefined ... that or process nextTick?

What does process.versions.node say in nw?

**Comment by NervosaX** [comment]
It gives me: "1.2.0"

**Comment by petkaantonov** [comment]
That means `global.setImmediate` is undefined, why does nw delete it?

**Comment by NervosaX** [comment]
I found this old commit for nw.js https://github.com/nwjs/nw.js/issues/897

Sure enough if I add this line, bluebird will work.

```
if (typeof global !== "undefined") {
    window.setImmediate = global.setImmediate;
}
```

That's pretty unfortunate, as I'm not sure if it should be bluebird's problem to deal with that sort of issue.

**Comment by petkaantonov** [comment]
Well promises should always use nextTick anyway, I am not sure what the reason for the check even was originally. setImmediate is macro task.
