### ISSUE TITLE
"self is undefine" error occur in "fireGlobalEvent" function

### ISSUE THREAD

**Issue by zj8487** [petkaantonov/bluebird#527]
hi, i  use bluebird through browserify in my project. and the following error is thrown:
```
self is undefine
```
i find the code in the ```bluebird/src/captured_trace.js``` that the ``` self```  is really not defined.
error is thrown on this code:    ```var method = self[methodName];```

```
        return function(name, reason, promise) {
            var methodName = toWindowMethodNameMap[name];
            var method = self[methodName]; //Error occurs here
            if (!method) return false;
            if (name === REJECTION_HANDLED_EVENT) {
                method.call(self, promise);
            } else {
                method.call(self, reason, promise);
            }
            return true;
        };
    }
})();
```

**Comment by petkaantonov** [comment]
`self` is the global object in browsers http://jsfiddle.net/d9dow039/

**Comment by zj8487** [comment]
1,thanks for your response, i will try the ```Full build bluebird.js``` in my project.

**Comment by zj8487** [comment]
I finally find the issue in my environment!
there is no ```self``` object.

 so is it possible to do it like the following to make bluebird to work in more runtime environment?
``` js
      var local;

      if (typeof global !== 'undefined') {
        local = global;
      } else if (typeof window !== 'undefined' && window.document) {
        local = window;
      } else {
        local = self;
      }
```

**Comment by petkaantonov** [comment]
What is your environment? If there is no `self` then it's not a browser.

**Comment by zj8487** [comment]
native env for cocos2d-js
https://github.com/cocos2d/cocos2d-js

**Comment by milgner** [comment]
Have you found a solution? I'm on Appcelerator Titanium and while Bluebird used to work just fine, error messages saying "self is not defined" seem to be occurring more often, especially getting in the way of error handling.

**Comment by zj8487** [comment]
i use https://github.com/then/promise with cocos2d-js

https://www.promisejs.org/polyfills/promise-6.1.0.js

**Comment by milgner** [comment]
Ok, thanks for the info. I added a line `var self=this` at the top of `bluebird.js` and it seems to have helped with Titanium compatibility. Titanium unfortunately has a couple of quirks (especially on iOS) that I'm not very confident that switching Promise libraries would really solve everything...
