### ISSUE TITLE
Possible typo in benchmark Readme.md

### ISSUE THREAD

**Issue by nshulipa** [petkaantonov/bluebird#531]
In bluebird/benchmark/README.md we can see in section
`results for 10000 parallel executions, 1 ms per I/O op`
the following text
`Node.JS 1.1.0`
[full url](https://github.com/petkaantonov/bluebird/blob/master/benchmark/README.md)

Is it Io.JS 1.1.0 or Node.JS? 
Node.JS doesn't have version 1.x.x yet

**Comment by petkaantonov** [comment]
Take it to io.js
