### ISSUE TITLE
Question about anti-pattern page in wiki

### ISSUE THREAD

**Issue by nunofgs** [petkaantonov/bluebird#533]
> Almost a sure sign of using promises as glorified callbacks. Instead of doThat(function(err, success)) you do doThat().then(err, success) and rationalize to yourself that at least the code is "less coupled" or something.

Shouldn't this read `doThat().then(success, err)`? or were you alluding to the possibility that developers might simply add a `.then` and leave the function arguments switched?

@petkaantonov Can you clarify that paragraph?

**Comment by spion** [comment]
@nunofgs yup, it should be `doThat().then(successCallback, errCallback)`. Feel free to make corrections

**Comment by nunofgs** [comment]
Thanks. I've updated the wiki.
