### ISSUE TITLE
bluebird 2.9.14 hangs

### ISSUE THREAD

**Issue by ben-page** [petkaantonov/bluebird#534]
#### Description
One of my applications started hanging after upgrading to 2.9.14 (on node v0.12.0). I've narrowed the issue to the change from setImmediate to nextTick.

#### Example
This is the simplest example I could come up with that reliably demonstrates the problem: 

1. git clone [https://github.com/ben-page/bluebird-issue.git](https://github.com/ben-page/bluebird-issue)
2. cd bluebird-issue
3. npm install
4. node index.js

If you run the code as is, it will hang. If you uncomment line 7 (to change the scheduler to setImmediate) or install bluebird 2.9.13, it will complete as expected.

#### Background
Honestly, I don't fully understand the problem, but I have found found several discussions that may be helpful. Apparently there are issues with race conditions or IO starvation related to nextTick.

https://github.com/joyent/node/issues/7996
http://blog.nodejs.org/2013/03/11/node-v0-10-0-stable/
https://github.com/joyent/node/issues/3335
https://groups.google.com/forum/#!topic/nodejs-dev/DvENgK8Nubw

**Comment by petkaantonov** [comment]
2.9.14 doesn't do anything but specifically change to using anything but nextTick, so I guess you could use 2.9.13?

**Comment by ben-page** [comment]
Yes, I can use 2.9.13.

**Comment by benjamingr** [comment]
@petkaantonov _loves_ nextTick in node and how it's implemented :D 

@ben-page  you can use 2.9.14 and `setScheduler` if you'd like. The hanging is really odd though.

**Comment by ben-page** [comment]
@benjamingr That's what I'm currently doing. 

I'm not trying to say that bluebird shouldn't use nextTick, just that I've found an issue with its current usage. I don't understand the bluebird internals well enough to say whether the issue can be fixed in bluebird or if its  fundamental to nextTick.
