### ISSUE TITLE
API documentation using `then(function(val1, val2)`

### ISSUE THREAD

**Issue by shaoner** [petkaantonov/bluebird#539]
Hi,

I'm new to Promises, however there are two examples in the bind method description that confuse me a bit, here is one of them:
```javascript
somethingAsync().bind({})
.then(function (aValue, bValue) {
    this.aValue = aValue;
    this.bValue = bValue;
    return somethingElseAsync(aValue, bValue);
})
.then(function (cValue) {
    return this.aValue + this.bValue + cValue;
});
```
Is `then(function(aValue, bValue)` a typo? I would have thought spread was the only way to retrieve multiple values.

**Comment by petkaantonov** [comment]
Yes it's a typo, then handler only has 1 argument. PR fixes welcome
