### ISSUE TITLE
Cancellation tests are failing with --browser option for 3.0.0

### ISSUE THREAD

**Issue by Artazor** [petkaantonov/bluebird#541]
```
$ node tools/test --run=cancel.js --browser
```
failing in browser as there is no `Promise.config({cancellation:true})`, and I don't see any appropriate place where to put it.

**Comment by petkaantonov** [comment]
Cancellation is still under construction in 3.0, browser tests will be fixed when it's done

**Comment by Artazor** [comment]
Are you planning to change any significant part of its api? Seems that all cancellation tests are passing now and they are much more detailed than I've expected. Even if 'forget' semantics is a far future, the current use cases (found in tests) looks way better than what we have now. I'd like to develop a d.ts for the 3.0.0 and update a DefinetelyTyped/Bluebird repository that is now seriously outdated.

**Comment by petkaantonov** [comment]
No the api won't change but what remains to be done is interop testing with timers, `Promise.join`, `Promise.using` and `Promise.coroutine`. These features probably don't work with cancellation at all in 3.0 because I haven't implemented interop yet.
