### ISSUE TITLE
Debugging with Chrome async stack traces

### ISSUE THREAD

**Issue by Artazor** [petkaantonov/bluebird#542]
Copied from #415 
>> [offtopic: sorry about asking here, but what is the status of the https://github.com/sparhami/bluebirdBreaksAsyncStackTraces - is the Bluebird chrome-async-stack-frame-friendly? if not - maybe it worth to introduce some flag that prevents grouping of unrelated promises for debugging purposes?]

>I was unaware of such an issue but as far as I can see it could be easily solved by skipping the trampoline when running under debug mode

@petkaantonov can you elaborate? It would be extremely useful (and maybe worth to be mentioned in documentation)

**Comment by petkaantonov** [comment]
It's a fix that needs to be done inside bluebird, not something that you can fix from outside

**Comment by petkaantonov** [comment]
Fixed in 2.9.17
