### ISSUE TITLE
setScheduler regression when upgrading from 2.3.x

### ISSUE THREAD

**Issue by mtfranchetto** [petkaantonov/bluebird#543]
Hi guys,
I think I found an issue with the use of setScheduler in an AngularJS application.
Specifically, this piece of code:

`
Promise.setScheduler(function(fn) {
    $rootScope.$evalAsync(fn);
});
`

it's not triggering the AngularJS digest cycle anymore after upgrading Bluebird to 2.4.x and later.
We debugged some code and found that this specific problem started to appear after this commit aa36792689f50b8450a351f9e9ab781167e09b5c.
Am I the only one with this problem?

Thanks for the support, 
Mattia

**Comment by petkaantonov** [comment]
What version are you using exactly?

**Comment by mtfranchetto** [comment]
Now I'm using Bluebird 2.9.13, but the problem is there since 2.4.0.

**Comment by petkaantonov** [comment]
Cannot repro http://jsfiddle.net/8m9yfovw/

**Comment by mtfranchetto** [comment]
I figured it out. My mistake. Sorry for wasting your time.
Closing the issue.

**Comment by kingcheez** [comment]
@mtfranchetto How did you solve the problem? I've got the same issue.

**Comment by mtfranchetto** [comment]
I did not posted the solution since it was not Bleubird's fault. In my case the problem was having multiple versions of Bluebird at the same time (used by different libraries).

**Comment by benjamingr** [comment]
Everyone with a question is welcome to ask it on StackOverflow - me and @bergus frequent the promise tag there and would likely catch it. 

If you think it's a bug - please open a new issue.
