### ISSUE TITLE
Question/suggestion: Functional promisify syntax

### ISSUE THREAD

**Issue by jkarttunen** [petkaantonov/bluebird#544]
Instead of 

var fs = require("fs");
Promise.promisifyAll(fs);

how about 

var fs = Promise.promisifyAll( require("fs") );

**Comment by phpnode** [comment]
That works...

**Comment by spion** [comment]
`promisifyAll` mutates prototype objects too and unfortunately that part would break if the function was pure.

**Comment by petkaantonov** [comment]
```js
var fs = Promise.promisifyAll(util._extend({}, require('fs')));
```
