### ISSUE TITLE
.tap(console.log)

### ISSUE THREAD

**Issue by tyscorp** [petkaantonov/bluebird#547]
The example [here](https://github.com/petkaantonov/bluebird/blob/master/API.md#tapfunction-handler---promise) does not work (in browsers) because `console` throws an TypeError when the context isn't `console`.

This means you need to `.tap(console.log.bind(console))`.

As debugging seems to be one of the primary use-cases for `tap` (in my experience; YMMV), rather than fix the documentation it would be nice for either:

* `tap` to autobind `console` methods 
* provide a method `Promise.prototype.log` (or `print`?) that prints to stdout (or possibly stderr if there is a rejection?) and partially applies parameters.

Example of the second one:

```
> Promise.resolve(42).log('the answer is').then(...); void 0;
< undefined
  the answer is 42
```

**Comment by benjamingr** [comment]
In io.js and node.js console is bound and `.tap(console.log)` works just fine.

You can bind console in your browser code if you'd like:

    console.log = console.log.bind(console);

Again - in node/io it's not needed.

**Comment by tyscorp** [comment]
Do you think this should be noted in the docs that setting the binding for console is needed for browsers?

**Comment by benjamingr** [comment]
Well, most of the examples in the docs are server-code. You wouldn't expect the mysql/postgresql example to work in browsers would you? 

The fact you can't pass console.log as a free function to `.tap` in browsers (but can in node) doesn't seem like a big deal to me anyway - it's not bluebird specific.

**Comment by tyscorp** [comment]
I wouldn't expect mysql/postgresql examples to work in browsers. I would, however, expect an API that exists on both server/client to work on both.

The difference between them is non-obvious and fairly significant in this case, but you are right in that bluebird docs are not the right place to document it.

**Comment by petkaantonov** [comment]
@tyscorp Yes I think if there is such an example in the documentation that it should say it assumes console.log is bound.

**Comment by petkaantonov** [comment]
Pull requests to improve this is very welcome :)

**Comment by petkaantonov** [comment]
@benjamingr You have to understand that there is a lot of users of bluebird now who don't really know javascript deeply enough to understand why console.log cannot be passed as a free function in browsers or why it can in node.
