### ISSUE TITLE
Bluebird fails in the environment provided by react-native

### ISSUE THREAD

**Issue by aackerman** [petkaantonov/bluebird#550]
The [react-native](https://github.com/facebook/react-native) environment is neither `node` nor a browser, more like a raw vm context. I just wanted to bring it to the maintainers that this is an issue. facebook/react-native#335.

More specifically [this line here](https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js#L22). It appears that `MutationObserver` is available, but as I stated, the environment isn't a browser, and `document.createElement` throws an error.

**Comment by petkaantonov** [comment]
So the obvious question is what is the mutation observer supposed to observe?

**Comment by petkaantonov** [comment]
This has been fixed in https://github.com/facebook/react-native/commit/18cb5d0711d585bf703ab2606839f122ca2a1154
