### ISSUE TITLE
Are `defer` and `pending` deprecated?

### ISSUE THREAD

**Issue by thefourtheye** [petkaantonov/bluebird#555]
What is the future of `defer`/`pending` methods? Are they deprecated? Its not clear from the deprecated APIs documentation (it just says discouraged). Will they ever be removed from the library?

**Comment by benjamingr** [comment]
They'll likely never be removed but please do not use them.

**Comment by petkaantonov** [comment]
They are deprecated in 3.0 but not removed, you will get a warning if you have warnings enabled in 3.0

**Comment by jcready** [comment]
@benjamingr @petkaantonov could you provide some explanation as to why we shouldn't use them / why they've been deprecated? I saw this in [the docs](http://bluebirdjs.com/docs/deprecated-apis.html#promise-resolution):

> The use of `Promise.defer` and deferred objects is discouraged - it is much more awkward and error-prone than using `new Promise`.

However that argument isn't very compelling without some examples or explanation as to how it's more "awkward" or "error-prone".

**Comment by benjamingr** [comment]
@jcready : 

```js
function getUserStatus() { 
  return new Promise(resolve, reject) { 
      makeNetworkRequest("/userstatus", resolve, reject); // promisifying a poor API manually);
  });
}
```

```
function getUserStatus() { 
   var d = Promise.defer();  
   makeNetworkRequest("/userstatus", v => d.resolve(v), e => dreject(r)); 
  return d.promise;
}
```

The difference is when `makeNetworkRequest`  might  throw synchronously. In the `new Promise` example the consumer of the method only cares about rejections - in the `.defer()` case they have to handle both synchronous and asynchronous exceptions. This is effectively for the same reason `then` is always run asynchronously - providing an API that is _sometimes_ asynchronous - in general or in the way it emits errors - is problematic.
