### ISSUE TITLE
promisifyAll doesn't catch EADDRINUSE

### ISSUE THREAD

**Issue by colmaengus** [petkaantonov/bluebird#567]
Hi,

I'm trying to promisify a server created by http.createServer but the following doesn't catch EADDRINUSE errors.
Am I doing something wrong ?

```javascript
var http = require('http');
var BPromise = require('bluebird');

var server = http.createServer();
BPromise.promisifyAll(server);
server.listenAsync(3000)
  .then(function() {
    console.log('here we go');
  })
  .catch(function(err) {
    console.error(err.message);
  });
```

Regards

Colm A

**Comment by petkaantonov** [comment]
In that case the error is coming from an event emitter and not the callback

You can catch it by doing:

server.on('error, function() {

);
