### ISSUE TITLE
Clarify best practices and API docs statement: "it is *very unlikely* that you will ever need to create promises yourself"

### ISSUE THREAD

**Issue by HenriKarapuu** [petkaantonov/bluebird#568]
I was surprised by the API Docs stating in 'new Promise' documentation that there shouldn't be need to construct a new Promise manually -- I'm constructing them manually all the time, and feel there are good reasons for doing that: 

1. If you are building a library yourself, instead of consuming libraries, you'll be constructing a lot of Promises (or at least i am), so the statement doesn't seem to apply at all for library creators?

2. If your method throws before you start promise chain / before first .then(), the normal Promise error handling won't work. By manually creating new Promise() as the first line of a method enables uniform Promise style error handling regardless of what part of the method throws, which seems highly desirable and closer to a best practice?

3. There are bunch of more complicated use cases where creating promises manually seems natural, e.g. to do batching a good way seems to be to create a promise, put it to queue and return it for each request, and then later in single go execute the batch and resolve/settle all the given promises.

4. And of course there are bunch of libraries that cannot be promisified.

Should the API docs statement "it is *very unlikely* that you will ever need to create promises yourself" be clarified / expanded, or are my use cases above wrong / sub-optimal?

**Comment by bendrucker** [comment]
1. You shouldn't be, since the library is mostly going to consume callback APIs and should be using `promisify`
2. `Promise.try`
3. That's a case where you'd need to get `reject/`resolve` out of the constructor but you would indeed use it: https://github.com/petkaantonov/bluebird/blob/master/API.md#deferred-migration


I don't

**Comment by petkaantonov** [comment]
What @bendrucker noted, but for 3. you should use a PromiseQueue library instead of manually duplicating its mechanics in application code, maybe this could be even a core feature

**Comment by petkaantonov** [comment]
In fact, if something should be changed it should say "never" and the styling changed to big neon letters - library developers know how to use it anyway.

**Comment by Artazor** [comment]
@petkaantonov 

> you should use a PromiseQueue library instead of manually duplicating its mechanics in application code, maybe this could be even a core feature

Could you point to the implementation you'd recommend?

> In fact, if something should be changed it should say "never" and the styling changed to big neon letters - library developers know how to use it anyway.

What about new Promise(function(resolve, _, onCancel){ ... })

**Comment by petkaantonov** [comment]
@Artazor I don't know any pre-existing implementation (and haven't searched) but you can implement it yourself. It's still library code and not application code.

> What about `new Promise(function(resolve, _, onCancel){ ... })` :-P

This is library level code too, just like normal new Promise.

**Comment by bergus** [comment]
@Artazor a promise queue isn't that hard to implement, you can find [many examples on StackOverflow](https://stackoverflow.com/search?q=[promise]+queue). The promise primitive `then` does *chain*, which is nearly a synonym to *queue* :-) As such, you often wouldn't use some "PromiseQueue" library that wraps this in a `Queue`-like interface, but use it directly.
Two examples I've found are [this](http://stackoverflow.com/a/25459437/1048572) by @benjamingr and [that](http://stackoverflow.com/a/29000651/1048572) by myself.

**Comment by Artazor** [comment]
I know that it's easy. I've just thought that @petkaantonov has mentioned some particular implementation -)

**Comment by HenriKarapuu** [comment]
> In fact, if something should be changed it should say "never" and the styling changed to big neon
> letters - library developers know how to use it anyway.

Thanks for the replies, but the above is ambiguous. Do you mean:

A) Never use 'new Promise' if you are application developer. If you are library developer you know how and when to correctly use 'new Promise'?

B) Never use 'new Promise' if you are application or library developer. If you are library developer you know how to use Bluebird and the other ways it provides for starting a promise chain?

**Comment by bendrucker** [comment]
A little of A, a little of B
