### ISSUE TITLE
Promises/A+ point 2.2.7.1 compatability

### ISSUE THREAD

**Issue by rhys-vdw** [petkaantonov/bluebird#571]
Possible inconsistency here. Promises/A+ spec [2.2.7.1](https://promisesaplus.com/#point-41) seems to imply that a promise chain should stop being executed if no value is returned from an `onRejected` handler. I was under the impression this meant if `undefined` was returned (as close as you can get to no return value in JavaScript).

```JavaScript
Promise.try(function() {
  throw new Error('An error');
})
.catch(function() { })
.then(function(result) {
  return console.log('result', result);
});

// Unexpectedly outputs 'result undefined'
```

**Comment by domenic** [comment]
`undefined` is a value. https://promisesaplus.com/#point-8

**Comment by benjamingr** [comment]
What @domenic said.
