### ISSUE TITLE
`councurrency` option documentation clarification

### ISSUE THREAD

**Issue by thefourtheye** [petkaantonov/bluebird#574]
We might have to clearly express the purpose of the [`concurrency` option](https://github.com/petkaantonov/bluebird/blob/master/API.md#option-concurrency) in the documentation. As of now it looks like this

> The concurrency limit applies to promises returned by the mapper function (since the operations the promises in the input array are "watching" are already running and thus cannot be limited).

It took me a while to understand what it actually says (especially the parenthesized text). When I had to explain that to OP in [one of my Stackoverflow answers](http://stackoverflow.com/a/29590166/1903116), I used the following words

> The `concurrency` parameter basically limits the number of Promises which can be resolved before resolving more promises. So, in this case, since the limit is 1, it will execute the first promise and as the limit is reached, it will wait till the first Promise resolves, before moving on to the next Promise.

Should the actual documentation be updated?

PS: Please let me know if my text in the answer needs rework :-)

**Comment by bergus** [comment]
Yes, it needs rework imo.
If you have a promise, it resolves whenever it wants, you cannot really hinder it. A promise is not "executed", an operation that returns/ed a promise is.
Therefore, the concurrency parameter limits the number of promises that are created and awaited before more *calls to the mapper function*.

**Comment by thefourtheye** [comment]
@bergus Thanks :-) I updated the answer now, can you please check if it looks okay?

**Comment by benjamingr** [comment]
That's better. If you make a PR for the docs and it explains the fact that concurrency refers to the amount of `mapper`s called at once I'll merge it - please note that documentation should probably focus more on 3.0 which will be documented on the website and not on GH :)

**Comment by thefourtheye** [comment]
@benjamingr Here is the [PR](https://github.com/petkaantonov/bluebird/pull/575). Working on 3.x docs now. Thanks @joncle and @mattdmo for reviewing the text :-)

**Comment by thefourtheye** [comment]
Closing this because the PR is accepted :)
