### ISSUE TITLE
Promise.prototype.spread signature changed

### ISSUE THREAD

**Issue by Artazor** [petkaantonov/bluebird#576]
According to [2.x docs](https://github.com/petkaantonov/bluebird/blob/master/API.md#spreadfunction-fulfilledhandler--function-rejectedhandler----promise) we should be able to pass both `onFulfilled` and `onRejected` handlers to `.spread()`. Now in 3.0 it [looks like](https://github.com/petkaantonov/bluebird/blob/3.0/src/promise.js#L115-L120) that only `onFulfill` is expected. Is it by design?

**Comment by Artazor** [comment]
I'd like to note that `p.spread(a,b)` is not equivalent neither to the `p.spread(a).catch(b)` nor `p.catch(b).spread(a)`

**Comment by benjamingr** [comment]
Just wondering - are you actually using `.spread` in such a way? Also, what environment are you using bluebeird in?

**Comment by Artazor** [comment]
@benjamingr 
My legacy code has the following code
```
Promise.all([p1,p2,p3]).spread(function(a,b,c){
    // ok
}, function(e){
   // handle errors only in p1 or p2 or p3, (not from `ok` handler)
}).then(...
```
I would be glad to rewrite it using `Promise.join` but (alas!) join has only one handler (onFulfill).
How would you propose to rewrite the given code?

**Comment by petkaantonov** [comment]
Yes, it's by design and more consistent with other utilities now

**Comment by spion** [comment]
Sorry, this seems like a very bad idea to me. It breaks compatibility for no good reason while removing a feature that cannot be achieved otherwise.

I mean sure, a major version bump allows you to break things. But isn't it more sensible to only break things when there is a very good reason?

**Comment by benjamingr** [comment]
An alternative would be to add an error handler to other utility methods, what do you think about that @spion ?

**Comment by petkaantonov** [comment]
@spion this was bugged for most of 2.x and causes some implementation complexity. It also encourages the pokemon gotta catch em all anti-pattern as there is no way to specify the predicate. Finally, it is very inconsistent with rest of the utilities, e.g. why should .spread have this second argument and .all() not?

**Comment by spion** [comment]
@petkaantonov did you mean `join` rather than `all`?  if so, at least the replacement was very straightforward - `all(...).spread(...)` did work :)

Didn't know it was buggy and complex though.  I suppose spread will be less needed with ES6 anyway.
