### ISSUE TITLE
Should map() handle null or undefined better?

### ISSUE THREAD

**Issue by pulkitsinghal** [petkaantonov/bluebird#580]
I've noticed that a lot of times, when I'm working with Promise.map() I run into: https://github.com/petkaantonov/bluebird/wiki/Error:-expecting-an-array,-a-promise-or-a-thenable

And usually the reason is as simple as the first argument that I want to load (lets say from a JSON file) is either null or undefined. I think the method should be able to simply turn itself into a no-op if this happens because there is no work for it to do, rather than erroring out, what are your thoughts?

**Comment by petkaantonov** [comment]
Absolutely not, this is preposterous.

**Comment by pulkitsinghal** [comment]
@petkaantonov - I'm a bit surprised by your response :)
Please allow me the opportunity to explain where I'm coming from ... if developers ran an operation on a collection like `_.each(collection, function(){...})` for other well known JS libraries, it would not throw an error would it? `null` or `undefined` collection would be treated as no-op by default, right?

So why would this be "preposterous" for bluebird?

**Comment by dmethvin** [comment]
> if developers ran an operation on a collection like _.each(collection, function(){...}) for other well known JS libraries, it would not throw an error would it? 

It does for jQuery, and I think it's the right result.

![capture](https://cloud.githubusercontent.com/assets/157858/7119560/6ccf0c66-e1d4-11e4-89b9-d7aa6c4df2d0.PNG)

Libraries that silently discard invalid API inputs just leads to code that is very hard to debug.

**Comment by pulkitsinghal** [comment]
I concede.

**Comment by petkaantonov** [comment]
Not to mention the language also throws for null and undefined wherever possible:

```js
null.prop
null.method()
[].forEach.call(null, function(){})
Object.keys(null)
``` 
etc

**Comment by benjamingr** [comment]
Hehe, go @petkaantonov

**Comment by petkaantonov** [comment]
FWIW when working with json with deeply nested optional paths you can ease it with a helper:

```js
getProp(json, 'foo.bar.baz.qux', [])  // Default to empty array if not found
```

**Comment by pulkitsinghal** [comment]
@petkaantonov - that's good advice! thank you :)
