### ISSUE TITLE
Early Returns out of a long promise chain

### ISSUE THREAD

**Issue by sidazhang** [petkaantonov/bluebird#581]
```javascript

DoSomethingAsync()
.then(step1)
.then(step2)
.then(step3)
.then(step4)
.then(step5)
```

```javascript
function step2() {
  if (someCondition) {
    // I want to early return and skip the rest of the promise chain
  }

}
```

Is there an elegant way to do early return for a long promise chain?

**Comment by sidazhang** [comment]
An answer on stackoverflow suggests throwing and error and then catching it.

http://stackoverflow.com/questions/11302271/how-to-properly-abort-a-node-js-promise-chain-using-q

I am wondering if you feel the same or you would suggest an alternative solution

**Comment by bergus** [comment]
There are many ways to do this:
* http://stackoverflow.com/questions/29499582/how-to-properly-break-out-of-a-promise-chain
* http://stackoverflow.com/questions/20714460/break-promise-chain-and-call-a-function-based-on-the-step-in-the-chain-where-it
* http://stackoverflow.com/questions/26076511/handling-multiple-catches-in-promise-chain
* … (and many more, see the "linked questions")

But yes, if you don't want to restructure your chain, then you have to throw an error.

**Comment by petkaantonov** [comment]
The issue tracker is not for usage questions, stackoverflow or mailing list is better.

**Comment by vilic** [comment]
@sidazhang I've implemented a fake Promise.break statement to do so. https://github.com/vilic/thenfail

**Comment by bergus** [comment]
@sidazhang You should've called it `Promise.goto`, and make this `.enclose()` thing a label :-)

**Comment by vilic** [comment]
@bergus Actually not a bad idea! I'll think about that, thanks!

**Comment by vilic** [comment]
@bergus `goto` and `label` implemented. ;)

**Comment by digital-flowers** [comment]
i would also suggest  something like break; in native loop functions or case like switch statement this could be amazing :)

**Comment by shanemileham** [comment]
I think it would be a great feature to have a native break and early return - the existing solutions are exceedingly clunky. Can this be opened as a feature request?

**Comment by spion** [comment]
For exceptions (unexpected conditions), you can already throw to terminate the chain early. For most other cases, nesting one level works fine. If you have something that doesn't fit the above two solutions feel free to discuss, but given that async/await is just around the corner, it may not be worth the effort (IMO)

**Comment by lktvlm** [comment]
You can use asynquence for this, which integrates nicely with bluebird and other promise libraries.
It does a lot of other neat-but-unnecessary stuff, too.
https://davidwalsh.name/asynquence-part-1

**Comment by mikermcneil** [comment]
@spion Even with async/await, the early return thing comes up.  It's to a lesser degree, of course, but it's pretty confusing IMO.  I've only recently gotten it straight myself, so I imagine folks new to JavaScript will have a bit of a hard time.

Consider:

```
// The problem:
(async function(inputs, exits) {

  var result = await doSomething()
  .catch('missing', () => {
    return exits.notFound(); // could just as easily be `return res.sendStatus(404);`
  })
  .catch((e) => {
    return exits.error(e); 
  });

  // THIS WOULD NOT WORK AS EXPECTED BECAUSE, NO MATTER WHAT,
  // THE FOLLOWING CODE WOULD RUN.  ALTERNATIVELY, WE COULD THROW
  // FROM INSIDE THE CATCH HANDLERS, BUT THAT WOULD PREVENT US FROM
  // PROPERLY CALLING EXITS.NOTFOUND(), SINCE IT WOULD JUST HIT THE CATCHALL.

  console.log('Success!!', result);
  return exits.success(); // could just as easily be `return res.json(...);`

})({}, {
  error: function(err) {
    console.error('Hit proper error outlet', err);
  },
  notFound: function() {
    console.error('Hit proper notFound outlet');
  },
  success: function(result) {
    console.error('Hit proper success outlet', result);
  }
}).catch((e) => {
  console.error('Hit unhandled rejection catchall', e);
});
```




It's totally solvable in the normal, synchronous way:

```javascript
var result;
try {
  result = await doSomething();
} catch (e) {
  if (e.code === 'notFound') {
    return exits.notFound();
  }
  return exits.error(e);
}

console.log('Success!!', result);
return exits.success();
```


But it's not necessarily obvious that one should do that...  (Especially since everyone is still in the mindset of the pre async/await world)


> More thoughts on that:
> https://gist.github.com/mikermcneil/d781573e2e30d6963b5586ad69663979

**Comment by mikermcneil** [comment]
Could maybe even do something like this:

```javascript
var result = await doSomething()
.catchAndRelease('missing', () => { return exits.notFound(); })
.catchAndRelease((e) => { return exits.error(e); });

// Throwing in the callback for `.catchAndRelease()` _does_ cause the promise to be rejected.
// But otherwise, the promise is unaffected by what you do in that function -- it would not resolve.

//... which would solve the problem I believe.
// But that begs the question: would that actually be ok?  Or would that cause a memory leak?
// (would need to experiment / look into how `await` is actually implemented a bit more)

console.log('Success!!', result);
return exits.success();
```

**Comment by challenger532** [comment]
some thing like that will be great:

```
function step2() {
  if (someCondition) {
     return Promise.neglect()
  }

}
```

and then neither then nor catch will be called after that...
