### ISSUE TITLE
continuation-local-storage support

### ISSUE THREAD

**Issue by mdarveau** [petkaantonov/bluebird#583]
Hi,

I opened https://github.com/sequelize/sequelize/issues/3509 in the Sequelize project and, long story short, the main issue is that they had to [shim](https://github.com/TimBeyer/cls-bluebird) Bluebird to support [continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage).

Instead of shimming the global Bluebird lib, they shimmed their own instance. This was a design decision as discussed on the thread with @mickhansen and @janmeier.

You might be wondering why on earth I am discussing Sequelize and CLS issue in a Bluebird issue. Well, that discussion made me wonder why CLS support couldn't be backed in bluebird. CLS is so nice for use cases like transaction, log context, HTTP request storage, ...

API could be something like `Bluebird.enableCLSNamespace(ns)` and implementation inspired by https://github.com/TimBeyer/cls-bluebird/blob/master/shim.js but without having to resort to shimming.

It's totally fine with me if your think this is a stupid idea and/or not in the scope of this project. I just want to know if you'd be open to such feature.

**Comment by petkaantonov** [comment]
Why doesn't CLS use domains? They are already enabled in bluebird

**Comment by janmeier** [comment]
CLS is a general mechanism for storing local variables in callback / promise chains (advertised as thread-local storage for callback chains), whereas domains only support error handling as far as I know.

However, I understand the sentiment of not wanting to litter bluebird with implementation details about other libraries, and shimming in sequelize is not too much work :)

**Comment by petkaantonov** [comment]
> CLS is a general mechanism for storing local variables in callback / promise chains (advertised as thread-local storage for callback chains), whereas domains only support error handling as far as I know.

That's not what I mean, domains are also used to implement libraries like CLS:

```js
var d = domain.create();
d.run(function() {
     domain.active.data = {foo: 1};
     setTimeout(function() {
         domain.active.data.foo  // 1;
     }, 10);
});
```

There is nothing generic about CLS, it just monkey patches async methods it knows about hence it's not working with bluebird. Domains work the same way but at least they are in the core.

**Comment by mdarveau** [comment]
I was not aware you could do that with domains. Thank you for your input!
