### ISSUE TITLE
Return a promise from Promise.coroutine() (like co)?

### ISSUE THREAD

**Issue by callumlocke** [petkaantonov/bluebird#585]
I was half expecting `Promise.coroutine` to work like https://github.com/tj/co and return a promise, so I could just chain a `.then()` to get at the final return value of the generator function:

```js
Promise.coroutine(function* () {
  var result = yield Promise.resolve(true);
  return result;
}).then(function (value) {
  console.log(value);
}, function (err) {
  console.error(err.stack);
});
```

But it doesn't work like this. The coroutine call returns `undefined`.

Would you consider adding this functionality? Or maybe as a different method? It's a really useful feature of co.

Or is there some way I could wrap `Promise.coroutine` so I could access the return value? I'm not sure if this is a dumb question..

**Comment by benjamingr** [comment]
`Promise.coroutine` _defines_ a function it doesn't return a promise - it returns a function. It's like a decorator:

```
    var waitTwoSequentially = Promise.coroutine(function(f1, f2){
         yield f1();
         yield f2();
         return "Yay";
    });
    waitTwoSequentially().then(function(){ // note we invoked it (with ())
          //
     });
```

**Comment by callumlocke** [comment]
oh is that how it works, I don't read docs good lol

thanks :)
