### ISSUE TITLE
Optimize reduce pipelining

### ISSUE THREAD

**Issue by dreadjr** [petkaantonov/bluebird#586]
I am trying to write a helper function which calls a pipeline sequentially passing "all" the results from the previous tasks into the next in the sequence. Below is my first attempt. I would love to do this with something like `.props` as well, so the results have more context.
 
```
[func, func2].reduce(function(memo, current) {
  var self = this;
  return memo.then(function(memoValue) {
    return current.apply(self, memoValue).then(function(nextValue) {
      return memoValue.concat(nextValue);
    });
  })
}, bootstrap()).then(function(r) {
  console.log('done', r);
});

function func() {
  return Promise.resolve(1);
}

function func2() {
  return Promise.resolve(2);
}

function bootstrap() {
  return Promise.resolve([0]);
}
```

**Comment by bergus** [comment]
Not sure what you are asking for. Which functionality would you like to have introduced in the Bluebird library? Or if this is a support question, please ask at https://stackoverflow.com/

**Comment by dreadjr** [comment]
Sorry my post got cut off. I was asking for functionality like this.
```
Promise.pipeline([func, func2], initalValue | promise)
  .then(function(results) {
  });
```
Where `func`, would get called with `func(initialValue)`
Where `func2`, would get called with `func([initialValue, funcValue])`
etc

**Comment by benjamingr** [comment]
@dreadjr I'm not sure why you can't do this sort of aggregation already with `.reduce` or with a closure over `each`

**Comment by benjamingr** [comment]
ping @dreadjr

**Comment by dreadjr** [comment]
There are quite a few ways of doing this but I was hoping for a more streamlined version.

**Comment by benjamingr** [comment]
This sounds way too specific for me to be in the library - maybe create a helper as an npm package?

**Comment by petkaantonov** [comment]
There is much better ways to do this kind of thing with `.value()`, .bind or just closed over variables
