### ISSUE TITLE
Promise.invert for turning rejections into fulfilments and vice-versa

### ISSUE THREAD

**Issue by ohjames** [petkaantonov/bluebird#588]
This is really useful during tests to verify a promise fails:

```javascript
it('Test that promise gets rejected', () => {
  return new Promise((_, reject) => reject()).invert()
})
```

I suppose you'd probably want to wrap fulfilment data in an `Error` and leave rejections alone.

Maybe also the static version (which I guess would always reject non-thenables):
```javascript
it('Test that promise gets rejected', () => {
  return Promise.invert(new Promise((_, reject) => reject()))
})
```

Happy to implement it if you can see the case for it.

**Comment by benjamingr** [comment]
`.then(x => throw x, x => x)` - is this really common enough to be in core?

**Comment by ohjames** [comment]
Given I've put it in about 40 tests in the last few weeks, then maybe? If nobody else agrees with me then I'm happy to just provide what the static version does via a library.

**Comment by bergus** [comment]
`invert` sounds pretty meaningless to me. What about `.expectRejection()`?
I guess it would be quite useful, but am not sure whether it needs to be put in core. Monkeypatching `Promise.prototype` with it in a test suite should be pretty trivial.

**Comment by benjamingr** [comment]
Wouldn't it be easier to wrap `it` into an `itDoesnt`?

**Comment by ohjames** [comment]
`itDoesnt` is great when you only have one rejection to test at the end, in other cases you have chains of promises or via `Promise.all` where you only expect certain promises to be rejected.

**Comment by petkaantonov** [comment]
When testing for rejection you must check that the error type and properties are as expected, not simply fulfill on any kind of rejection.

**Comment by felixfbecker** [comment]
Would like this too. This would be **extremly** useful for coroutines. Currently:
```js
it('should throw async if not found', Promise.coroutine(function *() {
  let err
  try {
    yield findOne(9000)
  } catch (e) {
    err = e
  }
  assert(err)
  assert.propertyVal(err, 'status', 404)
})
```
with invert:
```js
it('should throw async if not found', Promise.coroutine(function *() {
  const err = yield findOne(9000).invert()
  assert(err)
  assert.propertyVal(err, 'status', 404)
})
```
If the promise is rejected and the assertions pass, the test passes.
If the promise is resolved the test fails (assertions don't get executed).
