### ISSUE TITLE
Can't find Promise.cast() method in this DOCs

### ISSUE THREAD

**Issue by PutinHuilo** [petkaantonov/bluebird#590]
Something wrong with that method?

**Comment by spion** [comment]
Promise.cast() has been deprecated for a long time now, ever since ES6 decided to drop it. You should switch to `Promise.resolve()` for all your casting needs

**Comment by Laoujin** [comment]
Could I add this to: http://bluebirdjs.com/docs/deprecated-apis.html?

There is still documentation, tutorials etc out there that use `.cast` which makes things complicated for those who do not have this context (like me, 5 minutes ago)

The `Promise.cast` function is still an alias in the latest code base aswell
https://github.com/petkaantonov/bluebird/blob/master/src/promise.js#L191
