### ISSUE TITLE
Use nextTick?

### ISSUE THREAD

**Issue by jesucarr** [petkaantonov/bluebird#591]
I'm using version 2.9.14 for this rate limiter: https://github.com/jesucarr/tokenbucket and if I try to upgrade to the next version 2.9.15, where you added setImmediate instead of nextTick, one of my tests fail.

The issue is [here](https://github.com/jesucarr/tokenbucket/blob/master/test/tokenbucket.spec.coffee#L430), where I use nextTick to trigger the clock tick in the middle of resolution of one promise ([here](https://github.com/jesucarr/tokenbucket/blob/master/src/tokenbucket.coffee#L280)), and this way the test get the code 100% covered. I tried using setImmediate instead of nextTick but I didn't manage to make it work.

Not sure if this is a bug, or I should run that test case in a different way, but it was the only way I found to have 100% code coverage. You can try yourself by running `gulp test`. 

Is this something needing a fix, or any alternatives to run the test?

Thanks

**Comment by benjamingr** [comment]
You can use `Promise.setScheduler`  to re-establish 2.9.14 behavior.

**Comment by jesucarr** [comment]
Thanks! that works.

Not sure if this is expected behaviour, if it is, feel free to close this issue.

**Comment by benjamingr** [comment]
This is expected behaviour, setImmediate makes more sense from a "when things happen" point of view than nextTick, the decision was made after Petka implemented the unhandledRejection hooks in io.js.
