### ISSUE TITLE
`nodeify()` does not always wait for promise fulfilment/rejection

### ISSUE THREAD

**Issue by julien-f** [petkaantonov/bluebird#594]
Maybe it is the correct behaviour, I don't know the promise spec thoroughly enough but it seems weird.

```javascript
var Bluebird = require('bluebird')

function asyncFuncReturningAPromise(cb) {
  process.nextTick(function () {
    cb(null, Bluebird.resolve(42))
  })
}

function forwardResult(result) {
  return result
}

function printResult(error, result) {
  if (error) {
    console.error('Error:', error)
  } else {
    console.log('Result:', result)
  }
}

// The wrapped promise is return directly withouth waiting for fulfilment/rejection.
Bluebird.promisify(asyncFuncReturningAPromise)()
  .nodeify(printResult)
// { _bitField: 268435456,
//   _fulfillmentHandler0: undefined,
//   _rejectionHandler0: undefined,
//   _progressHandler0: undefined,
//   _promise0: undefined,
//   _receiver0: undefined,
//   _settledValue: 42 }

// Adding a `.then()` is enough to get the correct behaviour.
Bluebird.promisify(asyncFuncReturningAPromise)()
  .then(forwardResult)
  .nodeify(printResult)
// 42
```

**Comment by bergus** [comment]
There is no promise spec for `promisify`. It does expect that the callback-accepting functions do `fulfill`, not `resolve` (which would adopt the promise). They must not call callbacks with promises, they must pass values.

If your lib knows about promises, it should return a promise. If it doesn't, it should pass a value to a callback. No mixing.

**Comment by julien-f** [comment]
It still looks pretty weird to me to have a promise which resolves to a promise, I don't think it complies with the spec.

**Comment by bergus** [comment]
The spec does not forbid promises that are fulfilled with a promise, only the usual way to construct one is `resolve` which recursively assimilates thenables. It might look weird to the unaccustomed eye, though from the view of algebraic data types it even makes sense.
Bluebird seems to omit the check for thenables in `promisfy` (performance! performance! performance!), but I don't think there's anything wrong with that. An `asyncFuncCallingBackWithAPromise` as in your example just does not exist anywhere.

**Comment by benjamingr** [comment]
Bergi is right, if your library already knows about promise it should just return promises - there is no point in a promise-using API to be called with promisify. If anything it should raise an error.

**Comment by julien-f** [comment]
@benjamingr raising an error is a bit overkill, I agree it's far from beautiful to return a promise via a callback but it is not an error.

I ran into this issue in [this code](https://github.com/julien-f/js-xen-api/blob/ff435934662b0273abf63d07d0867a2b93bf7faa/src/cli.js#L40-L54) where I patched the Node repl `eval()` function to make the shell waits for promise completion.

I can write as bellow but it feels less clean than a simple `evaluate(...).nodeify(cb)`:

```
const evaluate = repl.eval
repl.eval = (cmd, context, filename, cb) => {
  evaluate(cmd, context, filename, (error, result) => {
    if (error) {
      cb(error)
    } else {
      Bluebird.resolve(result).nodeify(cb)
    }
  })
}
```

Anyway, I don't want to keep bothering all of you but I just find it unnatural to have two different behaviours (even if, I agree, the code in the second case is pretty ugly):

```javascript
// 1. A promise 𝛼 resolved to a promise 𝛽 directly resolve to the value
//    of 𝛽.
new Bluebird(function (resolve) {
  resolve(Bluebird.resolve(42))
})
  .then(console.log)
// 42

// 2. When the promise 𝛼 is created by promisify, its resolved value is
//    the 𝛽 promise and not 𝛽 value!
Bluebird.promisify(function (cb) {
  cb(null, Bluebird.resolve(42))
})()
  .then(console.log)
// { _bitField: 268435456,
//   _fulfillmentHandler0: undefined,
//   _rejectionHandler0: undefined,
//   _progressHandler0: undefined,
//   _promise0: undefined,
//   _receiver0: undefined,
//   _settledValue: 42 }
```

**Comment by bergus** [comment]
Hm, maybe this feels more natural to me because in my own Promise library `fulfill` is the primitive action and I have to `.chain(Promise.resolve)` explicitly when I want assimilation…

I think your code would benefit from making it explicit as well:
```js
const evaluate = Bluebird.promisify(repl.eval);
repl.eval = (cmd, context, filename, cb) => {
  evaluate(cmd, context, filename)
  .then(Bluebird.resolve) // wait for promises
  .nodeify(cb);
};
```
