### ISSUE TITLE
Global override of concurrency

### ISSUE THREAD

**Issue by chung-leong** [petkaantonov/bluebird#595]
I've been using .map() to manage operations that can happen at the same time. The concurrency option is very useful, since it let me force things to occur one at a time with minimal code changes. Debugging becomes easier when there aren't dozens of operations in flight. Breakpoints get triggered in an order that you anticipate.

I was thinking that a way to disable concurrency globally would be a helpful debugging tool.

**Comment by benjamingr** [comment]
There is a _big warning_ about the fact concurrency acts locally, and this sort of thing is why @petkaantonov  didn't want to add the option initially.

It is impossible to do this globally, what if you have other processes running node? What if (for example) your DB driver or HTTP agent itself is limiting concurrency?

That said, if you want it for debugging and _everything_ does .map you can always do:

```js
var mapBound = Promise.prototype.map;
var mapStatic = Promise.map;
Promise.prorotype.map = function(fn, options){
     options = options || {};
     options.concurrency = 1; 
     return mapBound.call(this, fn, options);
};
Promise.map = function(promises, fn, options, _filter){
     options = options || {};
     options.concurrency = 1; 
     return mapStatic(promises, fn, options, _filter);
};
```

**Comment by chung-leong** [comment]
Thanks for you quick response. By globally, I just meant the global scope. What I want to do is ensure that in a situation where I have a breakpoint set at a the place of a where a function is called and another breakpoint set in a callback chained to the function's result, I would hit the second breakpoint immediately after hitting the first.

I had written a lot of code that looks like this:

```js
var results = [];
for(i = 0; i < inputBalues.length; i++) {
    results.push(makePromise(inputValues[i]));
}
promise.all(results).then(function() {
   /* ... */ 
});
```

Such code turned out to be hard to debug. The operations that generate the promises are all in flight. If I set a breakpoint in one of the callbacks used in makePromise(), it could be triggered for every and any of the input values.

Reworking such loops into map() calls make the code more debuggable. And if belatedly I discover that these operations really should run in order, I could just change the call to each().

Anyway, I think you suggestion is just what's needed. I don't know why I didn't think of that before. The solution is better than what I was asking for. Since the replacement function is my own code I could add into extra checks and debug output. Thanks and keep up with the good work!
