### ISSUE TITLE
Concurrent version of each

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/bluebird#597]
Is there a non-sequential version of each?
I guess map works that way, but I do not need the return values.
Why is each sequential anyway?

**Comment by benjamingr** [comment]
You want `.map` or `.all`, `.each` itself was introduced in hindsight especially for sequential execution.

**Comment by tjconcept** [comment]
Okay, that was probably what I feared :(
Thanks.

I just want to react as fast as possible to each promise/value in an array - and hopefully without having to loop it myself, wrap the value in `Promise.resolve` and calling `.then`.

**Comment by tjconcept** [comment]
I ended up with this:

```js
function( obj ){
	var self = this;
	var keys = Object.keys(obj);
	var count = keys.length
	var values = [];

	for (var i = 0;i < count;i++)
		values.push(obj[keys[i]]);

	return Promise
		.map(values, function( value, i ){
			populate(keys[i], value);
		})
		.cancellable()
		.catch(Promise.CancellationError, function( e ){
			for (var i = 0;i < count;i++){
				if (values[i].cancel)
					values[i].cancel();
			}
		});
}
```

I use it for populating a UI with data as it arrives from external requests (which can be cancelled if the UI view is changed).

Please hint if there's a better way.

**Comment by benjamingr** [comment]
@tjconcept any specific reason you're not using `Promise.props`?

**Comment by tjconcept** [comment]
Yeah, I want `popupate` to run each time a new value resolves, and not once for all values.
