### ISSUE TITLE
Strange performance issue when decalre a function inside the executor

### ISSUE THREAD

**Issue by luin** [petkaantonov/bluebird#598]
It seems that declaring a function inside the executor of Promise will decrease the performance significantly. Here's the code: http://jsperf.com/bluebird-declare-function. The case "declare function inside bluebird promise" is much slower than "declare function outside bluebird promise".

The trend is same when using the native Promise, but not as obvious as bluebird.

I've read [Optimization-killers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) but still can't find out the reason.

**Comment by petkaantonov** [comment]
This doesn't seem to be directly related to bluebird so closing.
