### ISSUE TITLE
`Promise.map(promises, callback, { concurrency: 1 })` does not call `callback` with promises in same order they were passed.

### ISSUE THREAD

**Issue by ohjames** [petkaantonov/bluebird#599]
When using this function and an array of 3 promises, you might expect it to call the map function on each promise in order. Instead the mapper is called on the first item, then the last item then the second item (the general pattern seems to be `[0, (n-1), (n -2), ..., 1]`.

In some cases it would be nice if you could rely on the order being the same, e.g. if the queue of promises represents work to do in order, and the concurrency limit can then be used to limit CPU load.

**Comment by benjamingr** [comment]
Right, if you want to do it in order call `.each` instead of `.map`.

**Comment by ohjames** [comment]
Thanks!

**Comment by benjamingr** [comment]
Also aliased as `.mapSeries` in 3.0 btw.

**Comment by ohjames** [comment]
Ah `.each` doesn't use the return value which I need, Promise.map with concurrency of 1 does exactly what I need but processes the values out of order. Guess I can do what I need with Promise.reduce.

**Comment by benjamingr** [comment]
@ohjames  for the record - in 3.0 `.each` returns the results, you can do `.each` in 2.9 and accumulate the results to a closure variable as a workaround (or .reduce that also works).
