### ISSUE TITLE
Function with promises returning before completion using 'then'

### ISSUE THREAD

**Issue by naemono** [petkaantonov/bluebird#601]
Unsure if this is a bug or simply my lack of understanding using promises/bluebird.

https://gist.github.com/naemono/598313a622620da7366c

I'm curious as to why the above code is returning from 'getVpc' function and moving on to the 'testFunction' prior to getVpc finishing?  Here's the output I get:

```
$ node test2.js
About to check credentials
Returning from checkCredentials
Returning from testFunction, vpc: null
Successful response: { Vpcs:
   [ { VpcId: 'vpc-xxxxxx',
       State: 'available',
       CidrBlock: '172.23.0.0/18',
       DhcpOptionsId: 'dopt-xxxxxx',
       Tags: [],
       InstanceTenancy: 'default',
       IsDefault: false } ] }
'''

Shouldn't the 'successful response' come prior to the return from testFunction?

Am I simply missing something vital?

Thanks for any input you can provide.

**Comment by phpnode** [comment]
@naemono stackoverflow is the place for questions like this, but it's happening because in your `.then` handlers you're invoking the next function immediately rather than letting the promise resolution chain invoke them itself. 

```js
checkCredentials().then(getVpc()).then(testFunction())
```
should be more like
```js
checkCredentials().then(getVpc).then(testFunction)
```

**Comment by benjamingr** [comment]
What @phpnode said.

**Comment by naemono** [comment]
Thanks @phpnode .   I'll use stackoverflow for questions moving forward.
