### ISSUE TITLE
align `.catchReturn()`  with `.return()`

### ISSUE THREAD

**Issue by Artazor** [petkaantonov/bluebird#603]
Should it be callable with no args?

```JavaScript
.catchReturn()  <==> .catchReturn(undefined)
```

<sub>Please don't throw slippers to me, I know that it is the terrible catch-all antipattern.</sub>

**Comment by benjamingr** [comment]
Use case?

**Comment by Artazor** [comment]
Just to match with `.return()`
```
myPromise.then(...).return(5)  // ok
myPromise.then(...).catchReturn(5) // ok
myPromise.then(...).return() // ok
myPromise.then(...).catchReturn() // error
```
catchReturn checks arguments.length against 1 to see if there are filters.

**Comment by benjamingr** [comment]
Sounds reasonable to me overall although this should probably warn in debug

**Comment by Janpot** [comment]
In case you're still looking for a use case: It might be used to ignore errors on a promise that didn't return a value in the first place.
