### ISSUE TITLE
Promisified MongoDB Node driver throwing stack_overflow error on multiple document insert

### ISSUE THREAD

**Issue by pcullin-ratio** [petkaantonov/bluebird#605]
When promisifying the mongodb driver module, I can insert multiple documents to a collection successfully. However, I'm also getting a stack_overflow Error hitting the catch block. This happens when executing either `insertAsync` or `insertManyAsync` and passing multiple document objects (using the MongoDB 2.0.0 Driver).

Here is a code sample in which this should reproduce:

```nodejs
var Promise = require('bluebird'),
    mongodb = Promise.promisifyAll(require('mongodb'));

mongodb.connectAsync("mongodb://my_conn_string").then(function(db) {
    return db.collection("my_collection").insertManyAsync([{a: 1}, {b: 2}]);
}).then(function(result) {
    console.log('info', result);
}).catch(function(err) {
    console.log('error', err);
});
```

**Comment by petkaantonov** [comment]
Do something like this at the top:

`Promise.longStackTraces();`

And then paste the stack trace here

**Comment by benjamingr** [comment]
Ping @pcullin-ratio

**Comment by benjamingr** [comment]
Ping @pcullin-ratio one last time?

**Comment by pcullin-ratio** [comment]
Sorry i'm working on this now and will have a more detailed response shortly

**Comment by benjamingr** [comment]
Yes! I knew it was worth one more ping. Thanks.

**Comment by pcullin-ratio** [comment]
I'm not able to reproduce the issue now - seems to be working as expected. Very odd :-/

**Comment by benjamingr** [comment]
@pcullin-ratio hey, thanks for reporting and thanks for following through. Don't hesitate to report issues in the future when you run into suspected bugs.

**Comment by pcullin-ratio** [comment]
Will do, thanks for the replies and tracking this @benjamingr!
