### ISSUE TITLE
Rejections caught with uncaughtException print to stderr

### ISSUE THREAD

**Issue by dpatti** [petkaantonov/bluebird#606]
```js
var Promise = require('bluebird');

process.on('uncaughtException', function(){ });
Promise.reject(Error("err")).done();
```

Gives output:

```
$ node test.js
^--- With additional stack trace: Error: err
    at Error (native)
    at Object.<anonymous> (/home/doug/dev/bluebird/mtest.js:4:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)
    at node.js:866:3
```

I don't quite know what the use-case is for this, but I know that we have some instances in our test utilities of promise chains with `.done()` at the end because we have not been able to promisify our entire application yet. However, mocha registers an `uncaughtException` handler and as the tests are running, this error is printed in between mocha's output. Of course, mocha also notes the error and prints it out at the end as the reasoning for the test failure, which is what we had expected. Is this intended? Bisected to 05987c198768bb.

**Comment by petkaantonov** [comment]
> we have some instances in our test utilities of promise chains with .done() at the end because we have not been able to promisify our entire application yet

This doesn't really make sense, for what purpose are you using `.done()`? It is not necessary in bluebird to use done.

**Comment by dpatti** [comment]
I thought the purpose of `.done()` was to throw any rejections that haven't been handled yet. We use it at the end of any promise chain that is not consumed by something else in some way, such as route handlers.

**Comment by petkaantonov** [comment]
You can just leave it out and throw from unhandledRejection event

**Comment by dpatti** [comment]
That's true, but that also means you _can't_ use `.done()` without seeing these messages in stderr. I like that `.done()` is explicit. We could fix the issue in testing, but it wouldn't prevent the same thing in production where we use domains.

**Comment by petkaantonov** [comment]
When using mocha, you need to return a promise from a test function. If the promise is rejected, then the test fails. There is absolutely no reason to use done.

**Comment by dpatti** [comment]
Sure, I just also believe there is absolutely no reason to be printing to stderr if a thrown promise is caught. That's all.
