### ISSUE TITLE
proposal  .thenCatch()

### ISSUE THREAD

**Issue by Artazor** [petkaantonov/bluebird#612]
### Problem

Let's consider the following snippet:
```JavaScript
myPromise.then(normalFlow).catch(KnownError, recoverLogic)
```

to be more specific: we have the following signatures
```
myPromise: Promise<string>
normalFlow: (result: string) => number
recoverLogic: (reason: KnownError) => number
```

Unfortunately `catch` will catch KnownError in both cases:
- when KnownError was thrown in myPromise
- when KnownError was thrown in normalFlow

However, I don't want that my recoverLogic would be applied to the later case. I'm ready to handle KnownError only from myPromise not from normalFlow.

Reordering of `then` and `catch` doesn't work because

```
myPromise.catch(KnownError, recoverLogic).then(normalFlow) 
```

is irrelevant: normalFlow and recoverLogic should be mutually exclusive, meantime, here we see that if recoverLogic will produce a successful result (number) it will be passed into normalFlow, (which expects string).

### Solution

Of course we can write
```
myPromise.then(normalFlow, function(e) {
    if (e instanceof KnownError) {
        return recoverFlow(e);
    } else {
        throw e;
    }
});
```
Sadly, this solution completely discards all the benefits of the bluebird's error filters/predicates.

### Proposal

introduce the following enhanced form of `then`

```
myPromise.thenCatch(normalFlow, KnownError, recoverFlow)
```
with the following usage:
```
.thenCatch(
   [Function fulfilledHandler] 
   [[, Function ErrorClass|Function predicate...] , Function rejectedHandler ]
) -> Promise
```

It's implementation is straightforward since all parts are already implemented in Bluebird.
The next snippet is a slightly modified copy of the `Promise.prototype.caught`:

```JavaScript
Promise.prototype.thenCatch = function(fulfilled, rejected) {
    var len = arguments.length;
    if (len > 2) {
        var catchInstances = new Array(len - 2),
            j = 0,
            i;
        for (i = 1; i < len - 1; ++i) {
            var item = arguments[i];
            if (util.isObject(item)) {
                catchInstances[j++] = item;
            } else {
                return apiRejection("expecting an object but got " + util.classString(item));
            }
        }
        catchInstances.length = j;
        rejected = arguments[i];
        return this.then(fulfilled, catchFilter(catchInstances, rejected, this));
    }
    return this.then(fulfilled, rejected);
};
```

IMHO, it should be an official form of `then` without any special name like `thenCatch`

**Comment by Artazor** [comment]
Or maybe it's worth to publish a catchFilter functionality via static `Promise.catch` e.g

```JavaScript
myPromise.then(normalFlow, Promise.catch(KnownError, recoverLogic))
```

With the following usage:

```
Promise.catch([Function ErrorClass|Function predicate...] , Function rejectedHandler) -> Function
```

This is tightly related to the standalone `catch` typing problem that we've discussed with @benjamingr in #589

**Comment by benjamingr** [comment]
I actually like the second idea of passing a `Promise.catch` in, and I understand the use case although personally I get around it by always throwing specialized errors so that errors wouldn't be caught by the handler following `normalFlow` (for example a network error) - but I see why this might arise.

@petkaantonov ?

**Comment by petkaantonov** [comment]
Frankly I think this is a ridiculous corner case - so you have specialized error type that could be thrown from multiple places but need to catch it only if it's not thrown from some specific then handler? really?

**Comment by benjamingr** [comment]
```js
function request(url, retries){
     if(retries === 0) throw new NetworkError("Failed to fetch url", url);
     return webRequest(url).catch(NetworkError, request.bind(url, retries -1));
};

// I only want to handle requests for the token API and not request
request(url).then(function(res){
     return request("someApi?token=" + res.token);
}).catch(NetworkError, function(err){
     authService.report("InvalidToken");
     authService.generateNewTokenInBackground().catch(function(){});
     throw new AuthenticationError("Invalid Token");
});

```

**Comment by Artazor** [comment]
@petkaantonov 

Just want to drop a few words about my context.

I'm refactoring a huge legacy project (project age = 2 years) that was built on top of the JQueryPromises (facepalm) before I've joined to the project. I'm responsible for converting as much logic as possible to the Promises/A+. I know all the aspects of the semantics of both JQueryPromises and A+ and it is really a challenge.
During several months, I've performed an exhaustive flow analysis and isolated parts that can't be rewritten. For the rest of the code I've chosen the best existing Promises/A+ implementation namely Bluebird. 

Unfortunately, there are few such corner cases in the *existing projects*. Meanwhile, features requested here are neither completely new nor radical, and in ideal, fully-orthogonal implementation they should be already there.

I can't rewrite the project from the scratch, so I'm trying to find an incremental approach. And this particular feature would be nice to have.

Of course, I'm trying to introduce normal classes for the exceptions. But at this iteration they are too generic yet. Like @benjamingr said: `ServerError`, `UpdateConflictError`, `NotFoundError`, `UnauthorizedError` that are simple wrappers for the underlying http error codes and are descendants from the HttpError. 

Btw, code that @benjamingr has shown almost exactly matches for one of our use-cases.

That is why this proposal has born.

**Comment by benjamingr** [comment]
@Artazor it's worth mentioning that you can extend bluebird from the outside just fine. I wouldn't worry about conflicts, if you can use symbols (which, jQuery implies you probably can't) you can do it through a symbol, otherwise you can just put stuff on the prototype. By the way the cancellation proposal is still open :) (hint hint)

**Comment by Artazor** [comment]
@benjamingr 
> you can extend bluebird from the outside just fine

I already do -)

I've already implemented it as a static `Promise.cath` as you pointed.

> By the way, the cancellation proposal is still open :) (hint hint)

-))) Sorry, my Promise to update the #565 is not cancelled. It's just pending!
I have an enormous amount of work, directly related to promises (arrrgggghhhh). However, it is vital to me to get the best possible cancellation semantics since our project is going to use it.

**Comment by Artazor** [comment]
@petkaantonov 
> Frankly I think this is a ridiculous corner case - so you have specialized error type that could be thrown from multiple places but need to catch it only if it's not thrown from some specific then handler? really?

I know that

```csharp
async Task<ApiResult> apiCall() {
    try {
        var token = await request<string>(authUrl);
        try {
            return await request<ApiResult>("someApi?token=" + token);
        } catch (NetworkError e) {
            throw new ApiError(e);
        }
    } catch (NetworkError e) {
       throw new AuthError(e);
    }
}
```

actually should be refactored into:

```csharp
async Task<string> getAuthToken() {
   try {
      return await request<string>(authUrl);
   } catch (NetwokError e) {
      throw new AuthError(e);
   }
}

async Task<ApiResult> apiCall() {
    var token = await getAuthToken();
    try {
         return await request<ApiResult>("someApi?token=" + token);
    } catch (NetworkError e) {
         throw new ApiError(e);
    }
}
```

However, I think that promises as a technology should be pattern agnostic. It should simply bring a consistent exception handling and composition for asynchronous operations. So every try/catch pattern should be reproducible with promises.

I suspect that we have different priorities. For me 

**Orthogonality** > **Forcing right patterns**

This belief is based on my experience that 

**External Orthogonality** === **Internal Consistency**

and lack of orthogonality is the symptom of having hacks under the hood that may lead to unexpected results in edge cases.

IMHO -)
