### ISSUE TITLE
Disposers

### ISSUE THREAD

**Issue by benjamingr** [petkaantonov/bluebird#616]
Basically, I tried playing with a cancelled disposable promise but I just realized disposers aren't promises anymore.

I'm sure there are (albeit rare) cases when you want a promise that is disposable but you want to manually dispose it. It might be sufficient to expose `._promise` for explicitly using the disposer's promise.

I can't think of non-contrived examples (things like connecting and then cancelling a DB connection don't sound too common) but I wonder if there are more common cases of using disposer+cancellation at conjunction. 

It might also be beneficial to discuss the relation between cancellation and disposal. Some libraries like RxJS don't have two concepts (disposal is cancellation). 

Also, shouldn't disposers of cancelled promises be called? I mean things like:

```js
var p1 = new Promise(function(resolve, reject, onCancel){
		setTimeout(resolve, 20);
		onCancel(function(){});
	})

var p2 = p1.disposer(function(){
		taken=false;
	});

p1.cancel();
Promise.using(p2, function(r){
	console.log("Nothing to log here");
})
setTimeout(function(){
    console.log("Taken", taken); // taken is true here
}, longEnough);
```

Don't feel too strongly about this since I haven't used 3.0 disposers much - but is this the semantic that we want?

**Comment by bergus** [comment]
> Shouldn't disposers of cancelled promises be called?

Are disposers called on rejected promises? Are disposers called on 
resolving promises that are never used (i.e. passed to `Promise.using`)?

> ```js
> var p2 = p1.disposer(function(){
> 	taken=false;
> });
> p1.cancel();
> ```

My first thought when reading that code were the cancellation semantics, 
which leaves us with two possible cases:
* `p2` does depend on `p1`, so `p1.cancel()` is not effective until `p2` 
is cancelled. Of course, that leaves us with the question what should 
happen when `p2.cancel()` (or `Promise.using(p2, …).cancel()`) is called.
* `p2` does not depend on `p1`, and the cancellation is unexpected. The 
same thing should happen as if `p1` was rejected.

> Reply to this email directly or view it on GitHub:
> https://github.com/petkaantonov/bluebird/issues/616

Why does this give a 404? Anyone else having problems?

**Comment by benjamingr** [comment]
@bergus sorry, I had a GH related issue. 

> Are disposers called on rejected promises?

No, not automatically. A rejected promise doesn't mean something should be disposed

> Are disposers called on resolving promises that are never used (i.e. passed to `Promise.using`)?

Doing `.disposer` returns a Disposer in 3.0 and not a promise, see: http://petkaantonov.github.io/bluebird/web/docs/api-reference.html#.disposer

**Comment by petkaantonov** [comment]
There is no change between 2.x and 3.x. [It always returned a disposer](https://github.com/petkaantonov/bluebird/blob/master/API.md#disposerfunction-disposer---disposer) because it's an easy opportunity to prevent wrong usage of the API (passing result of .disposer() to somewhere else than `using`).

I think you have misunderstood `using` in general. Disposers are only called for the resources that succeeded because if you failed to acquire a resource, it is not possible to dispose it because it doesn't exist since you failed to acquire it.

It works exactly the same in 2.x:

```js
var p1 = new Promise(function(resolve, reject){
        setTimeout(resolve, 20);
    }).cancellable();

var p2 = p1.disposer(function(){
        taken=false;
    });

p1.cancel();

Promise.using(p2, function(r){
    console.log("Nothing to log here");
})
setTimeout(function(){
    console.log("Taken", taken); // taken is true here
}, longEnough);
```

**Comment by petkaantonov** [comment]
> My first thought when reading that code were the cancellation semantics,
which leaves us with two possible cases:
* `p2` does depend on `p1`, so `p1.cancel()` is not effective until `p2`
is cancelled. Of course, that leaves us with the question what should
happen when `p2.cancel()` (or `Promise.using(p2, …).cancel()`) is called.
* `p2` does not depend on `p1`, and the cancellation is unexpected. The
same thing should happen as if `p1` was rejected.

`p2` is not even a promise, there is just 1 promise.

**Comment by benjamingr** [comment]
Huh, I guess I never realized in 2.0 it didn't return a promise because I never tried to use it that way.

So there are no cases where promises/disposers and cancellation intertwine? 

Like, if a `using` failed for one disposer or promise - attempt to cancel the rest of the arguments that are promises like you dispose the ones that are disposers?

**Comment by bergus** [comment]
Oops, you're right, I forgot to check back what `.disposer` does and was confused by naming the result `p2`. Ok, so let's change the code a bit:

```js
var p1 = new Promise(function(resolve, reject, onCancel){
    setTimeout(resolve, 20);
    onCancel(function(){});
}),
taken = true,
dis = p1.disposer(function(){
    taken = false;
}),
p2 = Promise.using(dis, function(r){
    console.log("Nothing to log here");
});
```
Now `p2` is a promise again that does depend on `p1`, and `p1` should not be cancellable before `p2`.

What should happen when `p2.cancel()` is called? That is indeed not trivial:

* If the `using` callback has already been executed, cancel the promise returned by it
* for each resource,
  * if it is resolved already, then dispose it
  * if it is still pending, cancel it (and assure that the cancellation disposes everything allocated till now?)

So every promise that loads a resource which needs to be disposed should actually be cancellable. Can we solve the problem when it is not?

**Comment by spion** [comment]
`using(disposable, f)` is basically sugar for `disposable.resource.then(fn).finally(disposable.cleaner)` so it should work normally

**Comment by bergus** [comment]
@spion Yes that's what I though as well initially. However, `using` is a bit more complex, as it can deal with multiple resources and acts like `join` as well.
Also, is that `.finally(disposable.cleaner)` really a good idea? Being triggered on cancellation, there might not yet be anything to dispose, so the `cleaner` needs to take that into account.

And the question still stands: What does `finally(cleaner)` do when the resource promise is not cancellable?

**Comment by petkaantonov** [comment]
Cancelling the promise returned by `using` calls `.cancel()` on the input promises, same as `Promise.all` or `Promise.join`

**Comment by petkaantonov** [comment]
@bergus if you are interested how various scenarios play out, there are plenty in the cancellation+using tests https://github.com/petkaantonov/bluebird/blob/3.0/test/mocha/cancel.js#L2288-L2634

**Comment by bergus** [comment]
@spion And of course I forgot to mention that the cleaner is not called when the resource promise is rejected, so it's not really `.finally`.
@petkaantonov Thanks, those test cases all seem reasonable (basically what I described above). My main question seems to resolve around "Are cancellable and uncancellable promises still distinguished in 3.0?".

```js
var allocate = 0;
var res1 = new Promise(function(res, _) {
    setTimeout(function(){ allocate++; res(); }, 2);
}).uncancellable().dispose(function(){ allocate--; });
var res2 = new Promise(function(res, _, onCancel) {
    var t = setTimeout(function(){ allocate++; res(); }, 2);
    onCancel(function(){ clearTimeout(t); });
}).dispose(function(){ allocate--; });
```
Now consider the test cases
```js
Promise.using(res1, res2, fail).cancel()
```
and 
```js
var all = Promise.using(res1, res2, fail);
setTimeout(function(){ all.cancel(); }, 1);
```
What would the value of `allocate` be after 3 milliseconds? Is the disposer of `res1` called here (as soon as the promise resolves)?
I guess the situation is the same as when `res2` would be rejected after 1ms - what does Bluebird 2.0 do with `res1` currently in this case?

**Comment by petkaantonov** [comment]
@bergus the only methods in 3.x are `.cancel` and `.isCancelled()`. But cancellation is disabled by default and needs to be enabled with configuration
