### ISSUE TITLE
Does not work in SystemJS and nodewebkit from 2.9.15 onwards

### ISSUE THREAD

**Issue by NervosaX** [petkaantonov/bluebird#624]
Since upgrading from 2.9.14 to 2.9.15, bluebird throws an invalid invocation error when performing Promise.all() (possibly others, Promise.resolve() works fine). This is only an error when run through System JS and nwjs (nodewebkit). 2.9.15 seems to be when it adds the browser version of bluebird.

Loading it through nodewebkit with a direct CDN link seemed to work fine. 

See this for reproduction steps: https://github.com/NervosaX/bluebird-nw-bug

The stack trace is:
```
TypeError: Illegal invocation
    at n.2.n._queueTick (https://npm.jspm.io/bluebird@2.9.15/js/browser/bluebird.js:2:2630)
    at n.2.n.invoke (https://npm.jspm.io/bluebird@2.9.15/js/browser/bluebird.js:2:2165)
    at e.23.e.exports.e._then (https://npm.jspm.io/bluebird@2.9.15/js/browser/bluebird.js:4:3618)
    at e.23.e.exports.e.then (https://npm.jspm.io/bluebird@2.9.15/js/browser/bluebird.js:4:1997)
    at file:///home/adam/Programming/js/bluebirdnw/dist/index.html:17:14
    at D (https://jspm.io/es6-module-loader@0.16.5.js:1:7439)
    at I (https://jspm.io/es6-module-loader@0.16.5.js:1:7071)
    at O.7.O.when (https://jspm.io/es6-module-loader@0.16.5.js:1:10745)
    at w.7.w.run (https://jspm.io/es6-module-loader@0.16.5.js:1:9781)
    at e.3.e._drain (https://jspm.io/es6-module-loader@0.16.5.js:1:1740)
    at 3.e.drain (https://jspm.io/es6-module-loader@0.16.5.js:1:1394)
    at process._tickCallback (node.js:375:11)
```

**Comment by benjamingr** [comment]
@NervosaX just to be clear - this fails in 2.9.25 too right?

**Comment by benjamingr** [comment]
Nevermind, verified failure on 2.9.25

**Comment by benjamingr** [comment]
This does not reproduce when doing `<script src="./bluebird.js"></script>` instead of using SystemJS in nw and also works correctly when using SystemJS in the browser http://jsfiddle.net/0voy1u7L/ , the suspect is detecting the scheduler mechanism.

**Comment by NervosaX** [comment]
Wonderful, glad my ticket was thorough enough! Will use your workaround in the meantime.

**Comment by benjamingr** [comment]
@NervosaX thanks for the detailed issue - can you please verify it worked for you?

**Comment by NervosaX** [comment]
@benjamingr 
I seem to be getting the following error now:

```
Uncaught TypeError: undefined is not a functionbluebird.js:3422 31.schedulebluebird.js:248 2.Async._queueTickbluebird.js:186 AsyncSettlePromisesbluebird.js:2486 23.module.exports.Promise._queueSettlePromisesbluebird.js:2499 23.module.exports.Promise._fulfillUncheckedbluebird.js:2422 23.module.exports.Promise._fulfillbluebird.js:2325 23.module.exports.Promise._resolveCallbackbluebird.js:3729 resolveFromThenable
```

Which is here:

```
          var version = process.versions.node.split(".").map(Number);
          schedule = (version[0] === 0 && version[1] > 10) || (version[0] > 0) ? function(fn) {
            global.setImmediate(fn); <-------------
          } : process.nextTick;
```

It is complaining that global.setImmediate does not exist. There is global.setTimeout. I would say this is an incompatability with node webkit now.

**Comment by NervosaX** [comment]
I would say this is related to ticket #525

**Comment by petkaantonov** [comment]
@benjamingr pls fix

**Comment by benjamingr** [comment]
I'll look into it tomorrow, I think we can just explicitly detect node webkit and use `process.nextTick` there.

**Comment by petkaantonov** [comment]
@NervosaX  does it work for you in 2.9.27? I added capability to run tests in nw and they pass. It also changed scheduler to be used in nw to MutationObserver since it's faster than setImmediate and not as buggy as nextTick.

**Comment by NervosaX** [comment]
@petkaantonov Seems to be working as normal in 2.9.27, both in browser and through nw. Thanks heaps for the fix.
