### ISSUE TITLE
Promise.return -> Function

### ISSUE THREAD

**Issue by southpolesteve** [petkaantonov/bluebird#625]
I found myself needing something that I couldn't find in the API. Several github issues and google searches turned up nothing. Consider this simplified example:

``` javascript
var Promise = require('bluebird');
var request = Promise.promisify(require('request'));
var listTweets;

if (config.fakeTweets) {
  listTweets = function(){
    return Promise.resolve(["A tweet", "Another tweet", "A third tweet"]);
  }
} else {
  listTweets = request("http://api.twitter.com/tweets");
}

listTweets().then(filterTweets).then(bigDataAnalyzeTweets);
```

`listTweets` is a function that starts a promise chain. The crux of the issue is this chunk:
``` javascript
  listTweets = function(){
    return Promise.resolve(["A tweet", "Another tweet", "A third tweet"]);
  }
```
I was looking for a bluebird API that returns a function that, when called, returns a value wrapped in a promise. I was looking for something like:

``` javascript
 listTweets = Promise.returns(["A tweet", "Another tweet", "A third tweet"]);
// listTweets is a function that returns a promise
```

It is not apparent to me that this exists in the current API. `Promise.resolve` returns a promise, not a function.  `.returns` is very similar can only be called on an existing promise chain and not used to start a promise chain.  The core API has some nice syntactic sugar for other things, so this seemed like a fit to me. I was honestly surprised when I couldn't find it. Couldn't find any previously closed issues like this either. It is also quite possible this already exists and I just completely missed it. Would be quite happy to hear if that is the case. 

If it makes sense to add to core, I would also be happy to take a crack. Wanted to get feedback here before digging in.

**Comment by goto-bus-stop** [comment]
Non-awesome workaround:

```javascript
// Promise.resolve.bind(null, [ 'A tweet', 'Another tweet', 'A third tweet' ])
Promise.returns = value => Promise.resolve.bind(null, value)

let tweets = Promise.returns([ 'A tweet', 'Another tweet', 'A third tweet' ])
tweets().then(...)
```

**Comment by benjamingr** [comment]
-1 from me, not every utility belongs in core. You're welcome to make a package, it's just `() => Promise.resolve(...)`

**Comment by petkaantonov** [comment]
This doesn't have anything to do with promises, you would probably find it in underscore or lodash, if even there.

```js
function functionOf(value) {
    return function() {return value;}
}
```

**Comment by tyscorp** [comment]
[lodash.constant](https://lodash.com/docs#constant)
