### ISSUE TITLE
Promise keep node process from exit

### ISSUE THREAD

**Issue by vothanhkiet** [petkaantonov/bluebird#626]
I write a tool for migrating data using Bluebird promise, so that user can trigger this tool directly via node command. Example:

> node migrate.js

The problem is, node process will not exist after complete all operation. Here is the content of main migrate.js, the exec() function return a promise.

```js
var migrate = require('../elasticsearch/migrate');
var setting = require('../../config/setting');

var cmd = new migrate(setting.NewConfig.search, true);
cmd.exec()
    .then(function () {
        console.info('Operation completed');
        //process.exit(0);
    })
    .catch(function (err) {
        console.error(err);
        //process.exit(1);
    });
```

At the moment I must trigger process.exit() to kill the process.

**Comment by petkaantonov** [comment]
Promise doesn't keep process alive, it is some other api that you are using.

**Comment by vothanhkiet** [comment]
Thank for you support, after rechecking current open handles via process._getActiveHandles(), the process was kept from exiting because of Knex library.
