### ISSUE TITLE
promise instanceof Promise returns false

### ISSUE THREAD

**Issue by capaj** [petkaantonov/bluebird#628]
ES6 promise returns true when I test if it is an instance of Promise.
Bluebird 2.95 does not.
Could you set a prototype, so that this is true? At least in the environments, where native promises are supported already?

**Comment by benjamingr** [comment]
Well, an `instanceof` check when `Promise` _is_ a bluebird promise works - but that's not how promises assimilate or interoperate between different libraries and between different promises and libraries.

The way a promise library (or native promises) decide something is a promise is by it having a `.then` method. If you want to make sure something is a promise the safest way is to just `Promise.resolve` it which will always return a promise for it.

**Comment by petkaantonov** [comment]
I don't understand what t

**Comment by capaj** [comment]
@benjamingr absolutely. Weird, I would have swore that my code on the line https://github.com/capaj/socket.io-rpc-event-handlers/blob/601ec6bf4a6e1e92d6490b634d296173de4ea774/socket-event-handlers.js#L100 was not going into true branch with Bluebird. Once I removed blubird from the project, that true branch was being executed again.
Ok, probably my mistake.
