### ISSUE TITLE
Promise.join returns an array

### ISSUE THREAD

**Issue by sirsavary** [petkaantonov/bluebird#629]
I'm using Promise.join and expected it to behave like the API docs show but instead it is returning an array:

The section of the docs: https://github.com/petkaantonov/bluebird/blob/master/API.md#promisejoinpromisethenablevalue-promises-function-handler---promise

My code:
```
 Promise.join(
            Tag.find({totalAddons: {'>': 0}}).sort({totalAddons: 'desc'}).limit(3),
            Addon.find({featured: true,  status: 'published'}).limit(4),
            Addon.find({status: 'published'}).sort({createdAt: 'asc'}).limit(10)
        )
        .then(function(array) {
                res.view({title: 'Mod Mountain', activeTab: 'home', popularTags: array[0], featuredAddons: array[1], latestAddons: array[2]});
            });
```

**Comment by bendrucker** [comment]
Read the note below `join` in the API docs. If you don't pass a function as the last argument, calling `Promise.join(p1, p2)` is equivalent to `Promise.all([p1, p2])`. Passing a handler as the final arg is new to 2.x and the above behavior is there for backwards compatibility. 

If Bluebird resolved anything other than an array with your code, it would mean throwing away data.

**Comment by sirsavary** [comment]
Dear god I feel stupid for missing that. Thank you @bendrucker!
