### ISSUE TITLE
`Can't find variable self` when request is failing

### ISSUE THREAD

**Issue by johanneslumpe** [petkaantonov/bluebird#630]
Tried to use bluebird together with react-native. But I'm getting the above error for on line 985 of the browser-build:

```javascript
var method = self[methodName];
```
The error occurs only, if a request is failing - in my case due to a 401 error returned from the server. The code for react-native is executed in JavascriptCore, if that helps. `self` does not seem to be defined in the scope - am I missing something obvious here?

Edit:
The offending part in the repo can be found here: https://github.com/petkaantonov/bluebird/blob/89c27e46ba1f99a56946d30adea0c94ae4e05c7a/src/captured_trace.js#L490

**Comment by petkaantonov** [comment]
`self` is the global object in browsers. The benefit over `window` is that `self` is the global object inside web worker as well, where `window` is undefined.

**Comment by johanneslumpe** [comment]
Ah, didn't know that you could use `self` as well. In JavascriptCore this does not seem to work though. Logging `self` while running a `react-native` app claims that self is not defined and instantly crashes the app. `global` and `window` work though.

**Comment by petkaantonov** [comment]
I think react-native should define `self` as global, if it wants people to use modules developed for browser as is.

**Comment by johanneslumpe** [comment]
Ok, fair enough. A simple `global.self = global` solves the issue. I'll open an issue on react-native instead. Thanks!

**Comment by benjamingr** [comment]
Please cross-link the issue here, thanks.
