### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by fanatid** [petkaantonov/bluebird#635]
Related with #632 

code for tests:
```js
var Promise = require('...')
var promise = Promise.resolve()
console.log('mem usage:', process.memoryUsage())
function noop () {}
for (var i = 0; i < 500000; ++i) { promise.then(noop) }
console.log('mem usage:', process.memoryUsage())
setTimeout(function () {
  global.gc()
  console.log('mem usage:', process.memoryUsage())
}, 100)
```

Table for `heapUsed` (runned on node v0.12.3 with --expose-gc):

| promise  | before loop | after loop | after global.gc() |
|----------|-------------|------------|-------------------|
| naive    | 3939264     | 472758048  | 3727816           |
| bluebird | 5420456     | 52508808   | 20717616          |
| q        | 4605448     | 705704032  | 24285192          |
| lie      | 4854176     | 131715744  | 3866144           |

bluebird looks pretty well with memory consumption after loop... but after global.gc() memory consumption isn't good.
I think it's because internal state of bluebird promise have many undefined values.. you can see it if run Object.keys(promise).length after loop, should return ~655332

**Comment by benjamingr** [comment]
@fanatid with 3.0 coming out every day now - can you try that benchmark in 3.0? 

(Also, it's not a very meaningful benchmark, but before we go into that I have a theory I want to test)

**Comment by fanatid** [comment]
Sorry, I haven't written versions of libraries that I used for tests
```
$ npm ls --depth=0
├── bluebird@2.9.25
├── lie@2.9.1
└── q@1.4.1
```

results for `3.0` branch, commit `06e8c05`
```
mem usage: { rss: 23224320, heapTotal: 11803648, heapUsed: 5713360 }
mem usage: { rss: 162627584, heapTotal: 145355264, heapUsed: 110019824 }
mem usage: { rss: 80601088, heapTotal: 65090560, heapUsed: 20391216 }
```

**Comment by petkaantonov** [comment]
This "use case" is flat out not even supported. In fact if you had tested the code for correctness it would have bugged out because the maximum parallel handlers is only 262k, but it could reasonably be even smaller..

> I think it's because internal state of bluebird promise have many undefined values

In any realistic use case of cached promise there is a event loop turn or more awaited between handler attachment. Those indexes are then reused because the last turn's handlers are not occupied anymore.
