### ISSUE TITLE
IE 10 and IE 11 issues?

### ISSUE THREAD

**Issue by dlong500** [petkaantonov/bluebird#636]
Is there a reason IE 10 and IE 11 are shown in red on the browser support widget from saucelabs?

**Comment by benjamingr** [comment]
Saucelabs are giving us issues, if you click on the banner you'll see for yourself everything works.

For what it's worth last time I checked bluebird ran find on all browsers - even IE5.5 and Netscape 7.

**Comment by petkaantonov** [comment]
The browser widget doesn't represent the state of the releases but is ran when any branch gets updated.

**Comment by dlong500** [comment]
Ok, that makes sense.  Thanks.
