### ISSUE TITLE
IO.js 2.2 build/SSL issue for Travis CI

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#637]
The latest version of Bluebird doesn't build on [Travis CI](http://travis-ci.org) any more, with IO.js 2.2:

```
WARNING: checksums are currently disabled for io.js
Now using io.js v2.2.0
$ node --version
v2.2.0
$ npm --version
2.11.0
$ nvm --version
0.23.3
5.19s$ npm install 
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v2.2.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v2.2.0/bin/npm" "install"
npm ERR! node v2.2.0
npm ERR! npm  v2.11.0
npm ERR! code ESSL
npm ERR! SSL Error: https://registry.npmjs.org/bluebird does not support SSL
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Note this line:
**npm ERR! SSL Error: https://registry.npmjs.org/bluebird does not support SSL**

Any idea why this is happening?

**Comment by petkaantonov** [comment]
This is an issue with npm and/or io.js.

**Comment by vitaly-t** [comment]
I was about to reply that I thought the same :) But lots of people are about to run into the same trouble, with the recent updates :)

**Comment by petkaantonov** [comment]
yes but there is literally nothing that is relevant to bluebird here or nothing that bluebird could do
