### ISSUE TITLE
Add concurrency option for .each?

### ISSUE THREAD

**Issue by lukehorvat** [petkaantonov/bluebird#639]
Is there a reason `.each` doesn't have the `concurrency` option? The way I see it, `.map` is for transformation and `.each` is for side-effects - there's no semantic difference that precludes one from having the `concurrency` option and not the other. 

It's a little annoying not having the option, because it forces you to use `.map` in place of `.each` even when you *don't* want to transform the collection. Example:

```javascript
}).then(() => {
  return getItems();
}).map(item => {
  return processItem(item).then(() => item); // Have to resolve with the item. :(
}, { concurrency: 5 })
.then(items => {
  console.log(items);
});
```

Would be nice if you could do this:

```javascript
}).then(() => {
  return getItems();
}).each(item => {
  return processItem(item); // Don't have to care about the resolved value.
}, { concurrency: 5 })
.then(items => {
  console.log(items);
});
```

I don't see what harm adding the option would bring, since a default value of `1` would provide the exact same behaviour that `.each` currently has (i.e. every item is processed serially).

**Comment by benjamingr** [comment]
> The way I see it, .map is for transformation and .each is for side-effects 

`.map` is for concurrency and `.each` is for in-order execution. In 3.0 `.each` returns the modified sequence too. 

As for `how to resolve with the item` there's `.return`.

**Comment by petkaantonov** [comment]
```js
.map(item => {
  return processItem(item).return(item);
}, { concurrency: 5 })
```
