### ISSUE TITLE
Synchronous inspection doesn't work if `then()` is used?

### ISSUE THREAD

**Issue by dchambers** [petkaantonov/bluebird#640]
When `then()` is used then synchronous-inspection doesn't seem to work by default, but I can get it to work by manually invoking any outstanding scheduled functions. Is there any reason the scheduled functions aren't automatically run when `value()` is invoked?

Here is the code I used to verify this (also available in this [codepen](http://codepen.io/anon/pen/oXZXjY)):

```js
<script src="https://cdn.jsdelivr.net/bluebird/latest/bluebird.js"></script>
<script>
// A
console.log(Promise.resolve(Promise.resolve('A')).value());

// B
console.log(Promise.resolve(new Promise(function(resolve, reject) {
	resolve('B');
})).value());

// C1
installScheduler();
var promise = Promise.resolve('C1').then(function(val) {
	return val;
});
uninstallScheduler();
console.log(promise.value());

// C2
var promise = Promise.resolve('C2').then(function(val) {
	return val;
});
console.log(promise.value());

var scheduledFuncs, origScheduler;
function installScheduler() {
	scheduledFuncs = [];
	origScheduler = Promise.setScheduler(function(fn) {
		scheduledFuncs.push(fn);
	});
}

function uninstallScheduler() {
	for(var fn of scheduledFuncs) {
		fn();
	}
	Promise.setScheduler(origScheduler);
}
</script>
```

**Comment by petkaantonov** [comment]
Promise chained from another promise is not immediately resolved even if the parent was resolved

**Comment by dchambers** [comment]
Hi @petkaantonov, does this mean that resolving these chains within `value()` is a bad thing to do, and more specifically would it break Promises/A+?

**Comment by petkaantonov** [comment]
using .value on promises that are not guaranteed to be fulfilled is bad (and documented so)

**Comment by dchambers** [comment]
But the promise I provided you in my example code is guaranteed to be resolved:

```
console.log(Promise.resolve('C').then(function(val) {
    return val;
}).value());
```

Although the `uninstallScheduler()` function I provided assumes it can call all of the methods immediately, couldn't something similar be done where we only continue invoking scheduled functions while they continue to resolve synchronously?

**Comment by benjamingr** [comment]
@dchambers I saw the issue you opened on that broody-promises lib. That library is _inherently_ not Promises/A+ compliant (Or native promises compliant) because of the way it does scheduling, `then` handlers must always run when only platform code is available. See the promises A+ specification for more details.

**Comment by dchambers** [comment]
Hi @benjamingr, yes, at present that library is failing 70 tests from the Promises/A+ Test Suite. I'm instead asking a question about Bluebird, since it's not clear to me why a promise that can be resolved synchronously isn't, when I specifically ask it to be by invoking `value()`?

**Comment by petkaantonov** [comment]
@dchambers no its not gurantees to be fulfilled because the handler can return a different value or a pending promise or even throw an error in which case it would be rejected

**Comment by dchambers** [comment]
> @dchambers no its not gurantees to be fulfilled because the handler can return a different value or a pending promise or even throw an error in which case it would be rejected

@petkaantonov, are you saying that because you don't know what the handler is going to do beforehand then it's not safe to invoke it?

If so, how is this different from this example which works, albeit that it's a promise where we don't what it's going to do:

```js
console.log(Promise.resolve(new Promise(function(resolve, reject) {
    resolve('B');
})).value());
```

**Comment by petkaantonov** [comment]
the executor is called synchronously but the then handler has not been called by the time you did .value

**Comment by dchambers** [comment]
I realize that the handler has not been invoked at the point `value()` is invoked, I just fail to see why it's okay to use a scheduler call-back to execute these functions rather than performing them within `value()`? My very poor understanding is that doing so wouldn't break Promises/A+ except for code after the `value()` invocation, where it was my choice to resolve early, and so not a problem?

**Comment by benjamingr** [comment]
@dchambers https://promisesaplus.com/

> onFulfilled or onRejected must not be called until the execution context stack contains only platform code. [3.1].

**Comment by petkaantonov** [comment]
The purpose of `setScheduler` is to set an alternative scheduler (function which schedules function to be called asynchronously), in no way is it ok to use it like this.

**Comment by dchambers** [comment]
> onFulfilled or onRejected must not be called until the execution context stack contains only platform code. [3.1].

@benjamingr, okay, but I think there are some provisos that can be made about that statement:

  1. The promises specification doesn't include a `value()` method for enabling _synchronous-inspection_, so it's only talking about regular promise based code.
  2. I assume this stipulation is there to ensure that any code using promises behaves deterministically, regardless of whether a promise could be fulfilled synchronously or asynchronously, whereas I'd like a method of synchronously inspecting a promise, and take responsibility for any code that follows the use of the _synchronous-inspection_ mechanism.

For arguments sake, suppose the `value()` method did work in the way I had expected it to, then it would clearly not break the Promises/A+ Test Suite since that test suite doesn't invoke that method. Additionally, I would assume that invoking such a method at the end of each test in the suite, at the point we know there is no other code reliant on that promise, would not break any of the tests within the suite. **Is this the case?**

If it is the case, then I think having a way of allowing people to do this would be super handy. From re-reading your documentation I can see that you are intending the `value()` method more as a safe convenience for people writing regular promise code, whereas I was attracted by having a compliant promises library that also allows _synchronous-inspection_. The fact that Bluebird is the fastest promises library available only makes that an even more convenient feature.

Assuming the test suite would continue to pass as I'm guessing it would, how about having a scarilly worded method like `forcedValue()`, that comes with a strongly worded disclaimer about breaking determinism for any code that runs after it's been invoked?

**Comment by benjamingr** [comment]
> The promises specification doesn't include a value() method for enabling synchronous-inspection, so it's only talking about regular promise based code.

Right, but you can't synchronously inspect a promise that is _prohibited by the specification_ from being resolved. Synchronous inspection is for promises _you know already resolved_ which is not the case here.

> I assume this stipulation is there to ensure that any code using promises behaves deterministically, regardless of whether a promise could be fulfilled synchronously or asynchronously, whereas I'd like a method of synchronously inspecting a promise, and take responsibility for any code that follows the use of the synchronous-inspection mechanism.

Right, and I'm perfectly cool with synchronous inspection, but what you're talking about is synchronous _resolution_ of promises which is completely different.

> For arguments sake, suppose the value() method did work in the way I had expected it to, then it would clearly not break the Promises/A+ Test Suite since that test suite doesn't invoke that method.

It would break the test suite since it implies

```
Promise.resolve().then(function(){
    console.log(1);
});
console.log(2); // or inspect, or whatever
```

Would log 1 2 and not 2 1 as the spec requires.

> Assuming the test suite would continue to pass as I'm guessing it would, how about having a scarilly worded method like forcedValue(), that comes with a strongly worded disclaimer about breaking determinism for any code that runs after it's been invoked?

You can set the scheduler to do what you made it do - but we offer no guarantees on what happens. There is a Zalgo build (that forfeits asynchronous guarantees) - you can try it out but we do not and we do not intend to support it. If you show me actual code where you need this feature I will gladly help you come up with a better alternative which runs deterministically and without race conditions.

**Comment by dchambers** [comment]
> Right, but you can't synchronously inspect a promise that is prohibited by the specification from being resolved. Synchronous inspection is for promises you know already resolved which is not the case here.

Okay, that's a very useful distinction, thanks.

> It would break the test suite since it implies

> ```js
> Promise.resolve().then(function(){
>     console.log(1);
> });
> console.log(2); // or inspect, or whatever
> ```

> Would log 1 2 and not 2 1 as the spec requires.

Agreed, using `forceValue()` does, for reasons you've described, technically break the promises specification since it will cause promises to resolve ahead of time, and depending on where you chose to invoke `forceValue()` this might be problematic, but I guess I'm saying that it can still be useful and would be in the developers hands.

> You can set the scheduler to do what you made it do - but we offer no guarantees on what happens. There is a Zalgo build (that forfeits asynchronous guarantees) - you can try it out but we do not and we do not intend to support it. If you show me actual code where you need this feature I will gladly help you come up with a better alternative which runs deterministically and without race conditions.

That's very fair. Thanks for taking then time to clearly explain all of this to me, and also making me aware of the possibility of using the Zalgo build.

I do have a genuine [use case for wanting this feature](https://github.com/systemjs/systemjs/issues/469), but given that the author of that project has already described [what I was doing](https://github.com/systemjs/systemjs/issues/469#issuecomment-106307372) as [a hack](https://github.com/systemjs/systemjs/issues/469#issuecomment-106243524), and now I'm here trying to do a hack upon a hack, I can see I'm on a shaky foundation! For what it's worth though, I think the Zalgo build (though clearly there for performance reasons only) is a worse solution in my case since it breaks the promises spec constantly, rather than providing a special rare case method that the developer can not use at all, or use carefully in cases where it's known that no succeeding code will be affected by the early resolution of the preceding promises.
