### ISSUE TITLE
Terrible performance with large sequential requests

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#641]
I've just tested my database library [pg-promise](https://github.com/vitaly-t/pg-promise) for performance versus all popular promise libraries (all latest versions) in a special, sequential test:

* promise
* bluebird
* vow
* q
* when
* rsvp
* lie

All of them in my test showed the same results, give or take 10%, except Bluebird, which takes the remarkable 1,000% to execute the very same test, that's 10 times worse performance than any other promise library that I tested against.

#### The Test

```javascript
var pgpLib = require("pg-promise");

var promise = require('vow');
//var promise = require('promise');
//var promise = require('bluebird');
//var promise = require('q');
//var promise = require('when');
//var promise = require('rsvp');
//var promise = require('lie');

var cn = "postgres://user:password@server:port/database";

var pgp = pgpLib({
    promiseLib: promise // choosing which promise library to use;
});

var db = pgp(cn);

function factory(idx) {
    if (idx < 10000) {
        return this.none('insert into test(name) values($1)', 'name-' + idx)
    }
}

db.tx(function () {
    return promise.all([
        this.none('drop table if exists test'),
        this.none('create table test(id serial, name text)'),
        this.sequence(factory),
        this.one('select count(*) from test')
    ]);
})
    .then(function (data) {
        console.log("COUNT:", data[3].count);
    }, function (reason) {
        console.log("REASON:", reason);
    });
```

They key call here is:
```javascript
this.sequence(factory)
```
which has the following implementation:
```javascript
// Sequentially resolves dynamic promises returned by a factory;
function sequence(t, factory) {

    function loop(idx, result) {
        var obj;
        try {
            obj = factory.call(t, idx, t); // get next promise;
        } catch (e) {
            return $p.reject(e);
        }
        if (!obj) {
            // no more promises left in the sequence;
            return $p.resolve(result);
        }
        if (typeof(obj.then) !== 'function') {
            // the result is not a promise;
            return $p.reject("Promise factory returned invalid result for index " + idx);
        }
        return obj.then(function (data) {
            result.push(data);
            return loop(++idx, result);
        }, function (reason) {
            return $p.reject(reason);
        });
    }

    return loop(0, []);
}
```

How is it possible that this method executes 10 slower with Bluebird than with any other library - I can't understand.

Hopefully somebody else will shed light here. But when it is 1 out of 7 promise libraries tested, something tells me the problem is most likely in Bluebird.

By the way, the original purpose of the test wasn't in testing the promise libraries, it was to test the performance when inserting 1,000 records vs 10,000, vs 100,000, vs 1,000,000. The issue with the promise came out of nowhere, unexpectedly.
And the result was - it takes about 1 min (+/- 10 seconds) to insert 1,000,000 records this way with any promise library, except Bluebird, which takes 10 minutes.

**Comment by spion** [comment]
Whats `$p`?

**Comment by vitaly-t** [comment]
@spion , sorry, I was just about to add it myself...

```javascript
// Simpler promise instantiation;
function $p(func) {
    return new npm.promise(func);
}
```
basically, this is a generic access to the currently used Promise object of the library.

**Comment by spion** [comment]
I'm getting predictably similar performance here:

```js
var when     = require('when').Promise
var bluebird = require('bluebird');


function test(Promise) {

  function sequence(t, factory) {

    function loop(idx, result) {
      var obj;
      try {
        obj = factory.call(t, idx, t);
      } catch (e) {
        return Promise.reject(e);
      }
      if (!obj) {
        // no more promises left in the sequence;
        return Promise.resolve(result);
      }
      if (typeof(obj.then) !== 'function') {
        // the result is not a promise;
        return Promise.reject("Promise factory returned invalid result for index " + idx);
      }
      return obj.then(function (data) {
        result.push(data);
        return loop(++idx, result);
      }, function (reason) {
        return Promise.reject(reason);
      });
    }

    return loop(0, []);
  }

  function testfn(idx) {
    if (idx < 4000000) return new Promise(function(resolve, reject) {
      resolve(idx);
    })
  }
  var t = Date.now();
  return sequence({}, testfn).then(function() {
    return Date.now() - t;
  });

}

var log = console.log.bind(console);

bluebird.resolve(when)
  .then(test)
  .then(log)
  .thenReturn(bluebird)
  .then(test)
  .then(log)
```

when: 2.6s
BB: 3s

**Comment by stefanpenner** [comment]
Might be worth sharing which version of node/v8

**Comment by vitaly-t** [comment]
@stefanpenner , the very latest NodeJS + IO.js, the results are pretty much the same.

@spion, I just simplified my example to to the bare minimum, and the problem is still there:

```javascript
var $p = promise.Promise;

function sequence(factory) {
    function loop(idx, result) {
        var obj;
        try {
            obj = factory(idx); // get next promise;
        } catch (e) {
            return $p.reject(e);
        }
        if (!obj) {
            // no more promises left in the sequence;
            return $p.resolve(result);
        }
        if (typeof(obj.then) !== 'function') {
            // the result is not a promise;
            return $p.reject("Promise factory returned invalid result for index " + idx);
        }
        return obj.then(function (data) {
            result.push(data);
            return loop(++idx, result);
        }, function (reason) {
            return $p.reject(reason);
        });
    }

    return loop(0, []);
}

function factory(idx) {
    if (idx < 10000) {
        return promise.resolve('hi');
    }
}

sequence(factory)
    .then(function () {
        console.log("Finished");

    }, function (reason) {
        console.log("Error:", reason);
    });
```

**Comment by spion** [comment]
I'm getting 15 for bluebird too. Which bluebird version is reported in its package.json ?

**Comment by petkaantonov** [comment]
you probably have long stack traces enabled implicitly through environment variables. For instance is your NODE_ENV set to "development"?

**Comment by stefanpenner** [comment]
> you probably have long stack traces enabled implicitly through environment variables. For instance is your NODE_ENV set to "development"?

good catch, that seems likely.

**Comment by benjamingr** [comment]
Unrelated but... Just pointing out that this is not how you should use bluebird with postgres. The faster way would be to use bluebird's promisification which would likely perform much faster than using the promise constructor.

I can't reproduce this - I think long stack traces are a good suspect for what's happening in your code. The easiest way to verify this would be to throw an error and see if you're getting long or short stack traces.

**Comment by vitaly-t** [comment]
Environment used: Windows 8.1 64-bit, with `NODE_ENV=development`

Changing it to `NODE_ENV=production` resolved the issue. It would appear Bluebird performance drops dramatically in a DEV environment. I did't expect that at all, because no other promise library drops the performance like this.

Closing the issue. Thanks all for the find!

**Comment by benjamingr** [comment]
@vitaly-t no other promise library gives you nearly as much debugging info in development environment. This is intentional behavior :)

**Comment by stefanpenner** [comment]
> Changing it to NODE_ENV=production resolved the issue. It would appear Bluebird performance drops dramatically in a DEV environment. I did't expect that at all, because no other promise library drops the performance like this.

Yes, but it is for debugging sanity of developers. Long stack traces are quite nice.

**Comment by vitaly-t** [comment]
@stefanpenner debugging sanity vs performance insanity, to see which one hits you first :)

**Comment by benjamingr** [comment]
Given you're opting out of good performance anyway by using an adapter
using the promise constructor we're all assuming this is a hypothetical
question anyway :P

**Comment by vitaly-t** [comment]
@benjamingr , very funny.

**Comment by spion** [comment]
Long stack traces are the main reason for the performance drop, and its not nearly as bad on average. Maybe you hit the worst case scenario for LST? (ridiculously long chain of promises).

**Comment by spion** [comment]
This seems to be a regression since 2.7.1 [probably introduced by this fix](https://github.com/petkaantonov/bluebird/commit/a4b757fc649429717548c857a82cf9a29fec3fbb)

**Comment by petkaantonov** [comment]
@spion that was a quick fix for the problem at the time, it doesn't stringify the stack anymore but instead cycles are checked for periodically

**Comment by spion** [comment]
I think the stack is still coerced into a string in 2.x [here](https://github.com/petkaantonov/bluebird/blob/master/src/captured_trace.js#L49) which results with the same perf penalty.

**Comment by petkaantonov** [comment]
Yes but only if the chain is > 32 items long

**Comment by vitaly-t** [comment]
Perhaps in my example it is much longer than that?

**Comment by spion** [comment]
@petkaantonov as far as I can tell string coercion is unavoidable here, otherwise you can't recognize whether there is a duplicate stack to decycle, am I right? :( So its a choise between either this bad perf or way too much memory being used to save all stacks..

**Comment by vitaly-t** [comment]
Using the current Bluebird version in *production* mode I now can execute 10m inserts in just 15 minutes, which is quite impressive on many fronts.

"Oh what a day, what a lovely day!" :+1: 

But every time I forget to switch away from *development* mode, it chokes right away, not even usable on that scale. Heh...

**Comment by stefanpenner** [comment]
Ya it would be great if run times did the stack stitching for us. They can doit it a much more optimal way... Then we wouldn't need to make these user land trade offs :(

**Comment by vitaly-t** [comment]
I've just logged a feature requested related to this: https://github.com/petkaantonov/bluebird/issues/676
