### ISSUE TITLE
.catch() not call

### ISSUE THREAD

**Issue by jeans11** [petkaantonov/bluebird#643]
Hi guys,

I work on an isomorphic project and I meet a small mistake. Let me share you. 
I have this class:

```javascript
import request from "superagent"
import promise from "bluebird"

class Api
{
    constructor(uri) {
        ...
    }

    // Simple GET HTTP Request
    get(...) {
        return new promise((resolve, reject) => {
            var url = this.buildUrl(...);
            this.requestPending = request.get(url);
            this.requestPending.end((err, res) => {
                if (err) {
                    reject(new Error(res.body.error));
                } else {
                    resolve(res.body);
                }
            });
        });
    }
}
```

And I have:

```javascript
var api = new Api(...);

promie.all([
    api.get(...),
    api.get(...),
    api.get(...)
]).then(data => {
   console.log(data);
}).catch(Error, err => {
   console.log("Error");
});
```
In fact, in the browser, I get the following error:
![error2](https://cloud.githubusercontent.com/assets/7700239/8008788/9de0bd1e-0ba4-11e5-83da-51340537a784.png)

Ok ! but the method _.catch()_ is never call. Could you explain this behavior ?

In addition, I tested with **when** and **Q** librairie and I have the same mistake.

**Comment by benjamingr** [comment]
Please ask support questions on StackOverflow - the issue tracker is for tracking bugs in the library and feature requests.
