### ISSUE TITLE
Promise.chunk

### ISSUE THREAD

**Issue by James1x0** [petkaantonov/bluebird#652]
It would be nice to have a alias to some sort of chunking mechanism for cpu-bound tasks that could run async up to a certain limit of ops.

```javascript
var myLargeArray = [];

Promise.reduce(_.chunk(myLargeArray, 10), function ( result, chunk ) {
  return Promise.all(chunk).then(function ( chunkResults ) {
    result.concat(chunkResults);
    return result;
  });
}, []);
```

to be like:

```javascript
Promise.chunk([Array], [ChunkSize]).then(doSomething); 
```

**Comment by benjamingr** [comment]
You mean like the promise map concurrency option?

    Promise.map(myLargeArray, fnToRunOnEachElement, {concurrency: 10})

**Comment by James1x0** [comment]
Holy moly, thank you.

**Comment by benjamingr** [comment]
Glad I could help - note that in your example you weren't actually running any function on the promises. Cheers.

**Comment by James1x0** [comment]
I see that now, probably would have to run a map-like iterator to create the promises so they all didn't run immediately. Promise.map seems to do that. Looks good.
