### ISSUE TITLE
Compatibility with ES6 promises

### ISSUE THREAD

**Issue by NotQuite** [petkaantonov/bluebird#655]
Now that promises are part of ES6, what are the plans for bluebird in the long term?

I still want to use the utility functions that bluebird provides but if possible want to switch over to the native promises. Would something as simple as `Object.assign(Promise, Bluebird)` work?
Or is bluebird too incompatible with native promises as they stand?

**Comment by stefanpenner** [comment]
> I still want to use the utility functions that bluebird provides but if possible want to switch over to the native promises.

Native promises (especially v8) suffer from some bugs still, in addition they do not perform nearly as well as bluebird.

> Would something as simple as Object.assign(Promise, Bluebird) work?

This likely wont work out of the box, Bluebirds helpers are finely tuned to bluebirds internals. This allows extra features, like bind, cancelation and good performance.

**Comment by benjamingr** [comment]
Bluebird is compatible with ES6 promises, you can use them together, the
ES6 spec guarantees it will play nice with bluebird promises and this is by
design and a design goal of the ES6 spec (Promises/A+ compatibility).

Bluebird will also gladly eat ES6 promises as `then`ables.

So you can think of bluebird as a much faster, much easier to debug
implementation with a richer API and goodies that are not native yet (like
cancellation) :)

**Comment by benjamingr** [comment]
Oh yeah definitely like Stef said ` Object.assign(Promise, Bluebird) ` won't work most likely. You can just do `var Promise = Bluebird` though.

**Comment by stefanpenner** [comment]
@benjamingr i believe part of the questions was, can one just harvest bluebirds helper methods, and transplant them to a native Promise.

Answer to that is no, although for people who are uninterested in the performance benefit a subset of the utility functions could be implement in a transplantable way. 

That being said, pollution  of globals (like `self.Promise`) is seen as an anti pattern. Instead of subclass, or entirely user land implementation would be recommended.

As @benjamingr mentioned, promise interopt is strong. You can easily convert back and forth, via `BlueBirdPromise.resolve(Promise.resolve());` or `BlueBirdPromise.resolve().then(function(){ return Promise.resolve(); });`

**Comment by benjamingr** [comment]
I actually wrote an adapter that adds the bluebird API to native promises 3
weeks ago through a subclass but then I figured that if I put it on GH
people would actually use it and just get a weaker, slower version of
bluebird that's harder to debug so now it's just sort of sitting on my
desktop.

![](http://i.imgur.com/ahf5F9x.png)

**Comment by stefanpenner** [comment]
> I actually wrote an adapter that adds the bluebird API to native promises 3
> weeks ago through a subclass but then I figured that if I put it on GH
> people would actually use it and just get a weaker, slower version of
> bluebird that's harder to debug so now it's just sort of sitting on my
> desktop.

burn it with fire :P

**Comment by benjamingr** [comment]
@stefanpenner only if you add the rejection hooks to rsvp already :P

**Comment by stefanpenner** [comment]
> @stefanpenner only if you add the rejection hooks to rsvp already :P

Ya, I should. just a low priority ATM

**Comment by petkaantonov** [comment]
These kind of questions are better asked on [the mailing list](https://groups.google.com/forum/#!forum/bluebird-js).

> Now that promises are part of ES6, what are the plans for bluebird in the long term?

bluebird is not a ES6 promises shim, so it's not affected by that

**Comment by vance** [comment]
hrm. can it at least be easily castable in TypeScript? What is this hangup with purity?
