### ISSUE TITLE
Result of promisified mongoose model save method lacks properties

### ISSUE THREAD

**Issue by skleeschulte** [petkaantonov/bluebird#656]
Here is an example:

    var mongoose = require('mongoose');
    var Promise = require('bluebird');
    
    var testSchema = new mongoose.Schema({
      text: String
    });
    
    var Test = mongoose.model('Test', testSchema);
    Promise.promisifyAll(Test.prototype);
    
    
    mongoose.connection.on('connected', function () {
    
      var saveTest = new Test;
      saveTest.text = 'Hey ho';
      saveTest.save(function(err, test) {
        console.log('saveTest id: ' + test.id); // test.id == [ObjectId from insert]
        console.log('saveTest text: ' + test.text); // test.text == 'Hey ho'
      });
    
      var saveAsyncTest = new Test();
      saveAsyncTest.text = 'I\'m a ghost';
      saveAsyncTest.saveAsync().then(function(test) {
        console.log('saveAsyncTest id: ' + test.id); // test.id == undefined
        console.log('saveAsyncTest text: ' + test.text); // test.text == undefined
      });
      
      var fromNodeTest = new Test();
      fromNodeTest.text = 'Buhuu';
      Promise.fromNode(function(cb) {
        fromNodeTest.save(cb);
      }).then(function(test) {
        console.log('fromNodeTest id: ' + test.id); // test.id == undefined
        console.log('fromNodeTest text: ' + test.text); // test.text == undefined
      });
      
      var promiseWrappingTest = new Test();
      promiseWrappingTest.text = 'Here we go again';
      new Promise(function(resolve, reject) {
        promiseWrappingTest.save(function(err, test) {
          if (err) return reject(err);
          resolve(test);
        }).then(function(test) {
          console.log('promiseWrappingTest id: ' + test.id); // test.id == [ObjectId from insert]
          console.log('promiseWrappingTest text: ' + test.text); // test.text == 'Here we go again'
        });
      });
    
    });
    mongoose.connect('mongodb://localhost/testCollection');

Only the 'normal' callback version and the 'manual wrapping' version have `test.id`and `test.text` set properly. For the promisified versions `test.id` and `test.text` are `undefined`.

**Comment by benjamingr** [comment]
What version of bluebird? Also, did you try just doing `Promise.promisifyAll(require("mongoose"))`?

**Comment by skleeschulte** [comment]
Same result with `var mongoose = Promise.promisifyAll(require("mongoose"));` (replacing `var mongoose = require('mongoose');` and removing `Promise.promisifyAll(Test.prototype);`).
Versions/environment: bluebird@2.9.30, mongoose@4.0.5, node v0.12.4, mongodb 3.0.3, Win7 64-bit

**Comment by petkaantonov** [comment]
Pretty sure save callback has multiple arguments in which case you should use 

```js
saveAsync().spread(function(doc, test, numAffected) {
    // ....
});
```
