### ISSUE TITLE
3.0.0 Milestone?

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#659]
Could somebody, please create a 3.0.0 milestone with the expected release date, plus a list of major changes coming?

Lots of packages will go out-of-date on dependencies, so would be nice knowing in advance when it is time to start testing.

**Comment by tjconcept** [comment]
I think release dates are more harm than good. I guess the 2.x branch will be maintained for some time at least, so there should be plenty of time to upgrade. Also if your application works today, just don't upgrade and it will continue to work the same way.

**Comment by petkaantonov** [comment]
2.x is not an out of date dependency when 3.0.0 is released as they are incompatible.
