### ISSUE TITLE
Feature Request : promise.accumulate

### ISSUE THREAD

**Issue by hgwood** [petkaantonov/bluebird#660]
Accumulating intermediate results of a promise chain is a fairly common need (exhibits: [1](http://stackoverflow.com/questions/28250680/how-do-i-access-previous-promise-results-in-a-then-chain), [2](http://stackoverflow.com/questions/25431912/can-you-accumulate-promise-results-in-a-chain-of-then)).

Popular solutions mention outer-scope variables, which is messy, and returning previous results along with the current result, leveraging `spread` to forward all results to the next handler, as in:

```js
getA()
  .then(function(a) { return [a, getB(a)]; })
  .spread(function(a, b) { return [a, b, getC(a, b)]; })
  .spread(function(a, b, c) { return getD(a, b, c); });
```

This technique is good, though a bit heavy to write and read. However, those issues may be mitigated by the use of a utility function, like this:

```js
getA()
  .then(accumulate(function(a) { return getB(a); }))
  .spread(accumulate(function(a, b) { return getC(a, b); }))
  .spread(function(a, b, c) { return getD(a, b, c); });
```

This looks cleaner, in my opinion. Here's a (naive?) implementation of `accumulate`:

```js
function accumulate(fn) {
  return function() {
    var args = Array.prototype.slice.call(arguments);
    args.push(fn.apply(this, arguments));
    return Promise.all(args);
  };
}
```

I believe `accumulate` to be a utility function along the lines of `spread` and `tap`, that would make a very useful addition to Bluebird. What do you think?

The result could look like this:

```js
getA()
  .accumulate(function(a) { return getB(a); })
  .accumulate(function(a, b) { return getC(a, b); })
  .spread(function(a, b, c) { return getD(a, b, c); });
```

**Comment by benjamingr** [comment]
Personally if not using something that supports coroutines or a transpile target I'd do

```js
var a = getA();
var b = a.then(getB);
var c = join(a, b, getC);
var d = join(a, b, c, getD);
```

That said, I can sympathise with the idea of easily carrying the variable scope around. I'll think about it for a little and wait to see what Petka has to say.

**Comment by spion** [comment]
The unfortunate problem with accumulate is that its only helpful in a very specific case where the previous result is used fairly "near" to the next result in the chain. But if its not near, you'd have to thread it throughout your chain until you get to the place where you actually need it. E.g.

```js
getA().then(a => 
  getB(a).then(b => getC(b))
    .then(c => getD(c))
    .then(d => getF(a,d))
});
```

would turn into

```js
getA().accumulate(a => getB(a))
  .accumulate((a,b) => getC(b))
  .accumulate((a,b,c) => getD(c))
  .accumulate((a,b,c,d) => getF(a,d))
```

In contrast, the variable approach would be

```js
var a = getA();
var b = a.then(getB)
var c = b.then(getC)
var d = c.then(getD)
var f = join(a,d, getF)
```

**Comment by petkaantonov** [comment]
```js
var a = getA();
var b = a.then(function() {
    return getB(a.value());
});
var c = b.then(function() {
    return getC(a.value(), b.value()); 
});
var d = c.then(function() {
    return getD(a.value(), b.value(), c.value());
});

```

**Comment by benjamingr** [comment]
lol petka your `.value` thing is so ugly compared to the `join` version :D

**Comment by petkaantonov** [comment]
the join version doesn't allow arbitrary code and is unrealistic like spion's example

**Comment by benjamingr** [comment]
Ok buddy :D From what I can tell the two versions do exactly the same thing. 

Anyway, I think we all agree this shouldn't be in core - @hgwood you're very welcome to publish this as a package on NPM :)

**Comment by hgwood** [comment]
Great points.

I've used the join technique quite a bit, but I'm a little annoyed by the naming collisions that happen between promises and resolved values. Your comments made me realize those can be eliminated by extracting the callbacks into named functions though, which may be a good idea anyway. So I understand how `accumulate` may not be *that* useful.

I was not aware of @petkaantonov's solution using the synchronous methods. Looks interesting. It might be a little dangerous, because I know I would very tempted to refactor
```js
var d = c.then(function() {
    return getD(a.value(), b.value(), c.value());
});
```
into
```js
var d = c.then_.partial(getD, a.value(), b.value(), c.value());
```

which would be incorrect of course.

Well, thanks for your attention and your reactivity. :)

**Comment by hgwood** [comment]
@petkaantonov Just out of curiosity, what do you mean by "the join version doesn't allow arbitrary code"?

**Comment by bergus** [comment]
I assume you've read that StackOverflow threads you linked? :-)
The proposed approach seems to be the [least popular one](http://stackoverflow.com/a/28250693/1048572). Indeed it has some downsides as shown by @spion and mentioned in that answer; downsides that the [`join` patterns](http://stackoverflow.com/a/28250704/1048572) do not have.

I'd think you should use that `accumulate` decorator function if you plan to use that approach nonetheless, maybe simplified to
```js
let withAccumulate = (fn) =>
    function(...args) {
        return Promise.resolve(fn.apply(this, args)).then((res) => [...args, res]);
    }
```
but supplied in your own library, not by Bluebird.

Your suggestion to make `.accumulate()` a promise method also has the problem that you seem to expect it to be both equivalent to `.then(withAccumulate(…))` and to `.spread(withAccumulate(…))`. One might switch on the [`.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) of the callback, but that's not a good practise and would only lead to very confusing errors.

**Comment by User4martin** [comment]
Just reading up, and had a similar idea recently, so adding it for discussion

```javascript
getA()   // returns promise with (once resolved) value: a
.thenPush(getB(a)) // getB(a) returns b, 
                               // but the promise from thenPush now has [a, b]
.thenPush(getC(a_b)) // getC(a_b) is given the current array value
                               // the promise from thenPush now has [a, b, c]
 thenPush(x)  // pushes x to the result
```

this would allow for other similar methods
```javascript
  .thenUnshift  // add at front of list

  Foo()   // The result of Foo must be an object
  .thenSet(function(ResultFromFoo){}, propertyName)
  // "set" as the opposite to "get"
  // Result.FromFoo.propertyName = resultFromFunction
```

thenSet or just set can be used to store new promises on an object, and then props can be used to wait for their fulfilment

**Comment by benjamingr** [comment]
@User4martin promises are already started activities, in your first example all the actions happen concurrently.

**Comment by User4martin** [comment]
@benjamingr

If the function passed to then (or in my example thenPush) returns a promise  then the promised returned by "then" becomes the promise returned by the function.
If it returns a none promise value then the next "then" runs on that value.

therefore .thenPush(getC(a_b)) should run on the result of .thenPush(getB(a))

**Comment by bergus** [comment]
I'd assume that he meant
```js
getA()
.thenPush(function getB(a){…})
.thenPush(function getC(a, b){…})
.…
```
