### ISSUE TITLE
Separate core and utilities into two different modules

### ISSUE THREAD

**Issue by fresheneesz** [petkaantonov/bluebird#662]
A couple reasons:

1. smaller core
2. easier to understand the library (not only the core)
3. utilities can be written in a way that works with any promise library that has a sufficiently similar API, so people using other promise libraries can take advantage of the utilities written for bluebird

**Comment by spion** [comment]
AFAIK the performance of bluebird is very hard to achieve without all of its helper methods knowing a lot about the implementation internals. @petkaantonov knows best of course, but based on what I've seen, I don't think this will be viable.

**Comment by fresheneesz** [comment]
So you're saying that utility methods use properties of promises that aren't exposed publicly (or documented in the wiki)? If that's the case, the easy solution to that is to simply document those properties and treat them as public. It may not have benefit 3 in that case, but benefits 1 and 2 would still hold.

**Comment by benjamingr** [comment]
Let's take an example - how would you write `promisify` as a separate part and not a part of core?

**Comment by fresheneesz** [comment]
@benjamingr I literally know absolutely nothing about what's under the hood of bluebird. It's pretty simple to promisify various things using your standard promise API. In the code there, I see that `INTERNALS` variable being used pretty sparingly. I don't know what its doing there, but I'll leave it to you experts to tell me whether or not that is critical for promisify's performance.

**Comment by benjamingr** [comment]
@fresheneesz basically promisify _generates and compiles_ a new function dynamically. You can't do this with native promises because it would require a closure which is a real overhead in performance when creating tens of thousands of promises. This is just one example of course.

**Comment by petkaantonov** [comment]
Using only public api it's not possible to implement something efficiently almost by definition.

**Comment by fresheneesz** [comment]
@petkaantonov So there's nothing in this library that only uses the public api of promises? Might it be possible to publicly expose the parts of bluebird that allow you to do such heroic efficiency?

**Comment by phpnode** [comment]
@fresheneesz Bluebird is tuned for performance to a ridiculous and obsessive degree :smile:, what you're asking for doesn't make sense, there's no internal library of functions that are useful to outside code, virtually every single code path is highly specialized and by definition not reusable.

**Comment by fresheneesz** [comment]
Ok then, i guess i'll take your guys' word for that then

**Comment by phpnode** [comment]
@fresheneesz no need to take our word for it, take a look at the source. If you're interested in some of the *patterns* that bluebird uses to go fast, take a look at https://github.com/codemix/fast.js

**Comment by fresheneesz** [comment]
@phpnode fast.js looks pretty cool. Props to you guys for focusing on performance so much. I ran a performance test against the [futures library I wrote](https://github.com/fresheneesz/asyncFuture), and its like 10 times faster - and mine has decently competitive performance compared to a lot of the fast ones out there. So i'll probably be deprecating mine in favor of bluebird at some point (wish I'd found bluebird earlier). 

I did take a look at the code for promisify, and while its complicated and is tied to the `INERNALS` of bluebird, its already a separate module and I still maintain it could easily be separated out into a separate module. Granted, I wouldn't actually recommend separating promisify out, since promisifying things is actually pretty necessary in almost all cases where you're using promises. I'd suggest this more for the collection methods, utility methods, timers, and that kind of thing. Regardless, if those other parts are anything like promisify, then they should be able to be separated out into a different, if tightly coupled, module. This would still gain benefits 1 and 2, tho not 3 as I conceded earlier.

**Comment by benjamingr** [comment]
@fresheneesz by all means, if you think you're able to modularize bluebird go for it :+1:

**Comment by spion** [comment]
Yeah, the collection methods all take advantage of BB's internals to provide better performance

Most of them use an internal method called `_then` that takes 5 arguments; e.g. the last argument passes flags related to features like .bind() and cancellation. 

A lot of the performance work in bluebird is specialized code handling common cases without the overhead of generalized solutions - so there is a lot of specific and hairy code :) Its kind of counter to typical good design / best practice advice *but* - since its a library you'd base your entire platform on, I think its a reasonable tradeoff.

If you're looking for a more balanced approach favoring modularity a bit more over performance (while still fairing quite good at the latter), you might want to also look at [whenjs](https://github.com/cujojs/when).

**Comment by fresheneesz** [comment]
I appreciate the performance, i like bluebird's api much more than when. I was impressed enough by `bind`, but the performance kicks it. I'm sold on bluebird. But in a lot of cases, you only need the basics of promises, and I would guess the various utility methods it would make sense to factor out significantly increase the size of the library. 40kb is getting up there. Being able to pick and choose which utilities you want is important to some people who are very kb focused. I imagine to use any of these tightly coupled modules, you'd do something like:

```
var Promise = require('bluebird')
var PromiseUtils = Promise.hook(require('bluebirdUtils'))
```

Where hook would pass in an internal API to bluebirdUtils that contains stuff like `INTERNALS`. Doing this would also have the benefit of allowing people to create a LOT more utilities of the kind that most people don't need - IE stuff that wouldn't make sense to put into this core module. 

@benjamingr I'm game to help do this, but I would want buy in, so I can be confident my work won't go to waste.

**Comment by fresheneesz** [comment]
Actually, I would imagine that any of the features you can disable in custom builds should be modulizable.

**Comment by benjamingr** [comment]
They're modularizable but they depend on core.
