### ISSUE TITLE
Rejections for non-200 responses with request library

### ISSUE THREAD

**Issue by chainlink** [petkaantonov/bluebird#668]
In the code example listed here https://github.com/petkaantonov/bluebird/blob/master/API.md It implies that the promise will be rejected when a bad request (ie. non 200) occurs, but instead the promise is always fullfilled unless the server times-out.

```
var Promise = require("bluebird");
var request = Promise.promisify(require("request"));

function ClientError(e) {
    return e.code >= 400 && e.code < 500;
}

request("http://www.google.com").then(function(contents) {
    console.log(contents);
}).catch(ClientError, function(e) {
   //A client error like 400 Bad Request happened
});
```

For Example
```
var Promise = require("bluebird");
var request = Promise.promisify(require("request"));

function ClientError(e) {
    return e.code >= 400 && e.code < 500;
}

request("http://www.google.com/404").then(function(contents) {
    console.log(contents);
}).catch(ClientError, function(e) {
  console.log('badness');
   //A client error like 400 Bad Request happened
});
```
Results in the promise being resolved, rather than the catch being triggered.

**Comment by benjamingr** [comment]
Does it not log 'badness' too? In the above code the exception is handled so the resulting promise should be resolved.

**Comment by chainlink** [comment]
The promise is resolved and ```console.log(contents);``` is called, but ```console.log('badness');``` is not

**Comment by spion** [comment]
Yeah, request always returns the response no matter the status code. We might want to avoid mentioning the request library in that example?

**Comment by chainlink** [comment]
ah, okay, so unless the server is down is won't reject the promise

**Comment by chainlink** [comment]
Potentially an idea to update the docs to say this, should I make a PR?

**Comment by benjamingr** [comment]
Sure, go for it

**Comment by benjamingr** [comment]
@chainlink ping, any update? Are you going to make a PR?

**Comment by chainlink** [comment]
Done! https://github.com/petkaantonov/bluebird/pull/679
