### ISSUE TITLE
promisifyAll breaks with mongojs 1.0

### ISSUE THREAD

**Issue by naartjie** [petkaantonov/bluebird#670]
Something changed in mongojs, when we started using version 1.0.1 bluebird's `promisifyAll` no longer works for us.

I haven't had time to dig deeper, but just wanted to put it out there, and see if anyone else has experienced this:

```javascript
const Promise = require('bluebird'), 
  mongojs = Promise.promisifyAll(require('mongojs'));

mongojs('dbName').collection('users').countAsync() // <-- countAsync is undefined
```

**Comment by petkaantonov** [comment]
The module doesn't expose classes in the main export like it used to. You need to require and promisify them individually like in the given example for mysql module:

```js
Promise.promisifyAll(require("mongojs/lib/collection"));
Promise.promisifyAll(require("mongojs/lib/database"));
Promise.promisifyAll(require("mongojs/lib/cursor"));
```

**Comment by naartjie** [comment]
Thank you @petkaantonov 

Can I PR to add those mongojs examples?

**Comment by benjamingr** [comment]
Sure, go ahead and PR them into the API.md

**Comment by naartjie** [comment]
> 
```js
Promise.promisifyAll(require("mongojs/lib/collection"));
Promise.promisifyAll(require("mongojs/lib/database"));
Promise.promisifyAll(require("mongojs/lib/cursor"));
```

I tried to run that (iojs 2.3.2 mongojs 1.0.2 bluebird 2.9.30), and it looks like in all cases the prototypes returned don't have *Async() functions on them.

Not sure if I'm doing something wrong, but it's not working, so I'm going to hold off on the PR.

**Comment by petkaantonov** [comment]
Oops it should be

```js
Promise.promisifyAll([
   require("mongojs/lib/collection"),
   require("mongojs/lib/database"),
   require("mongojs/lib/cursor")
]);
```

**Comment by benjamingr** [comment]
@petkaantonov I didn't even know `promisifyAll` takes an array. AFAIK it's not even documented.

**Comment by petkaantonov** [comment]
It uses the module promisification syntax.. e.g. the array is a "module" with classes on properties "0", "1" and "2"

**Comment by benjamingr** [comment]
Hah, cute.

**Comment by naartjie** [comment]
Cool, that works, thanks guys!! Creating PR for the docs :+1:
