### ISSUE TITLE
Add a tap equivalent for map() and/or spread()

### ISSUE THREAD

**Issue by pimterry** [petkaantonov/bluebird#672]
Currently (as far as I can tell) there's no nice way to .tap a promise who's last callback returned an array of promises. I.e. to tap:

```javascript
var Promise = require('bluebird');
var start = Promise.try(function () {
  return [Promise.resolve(1), Promise.resolve(2)];
});
```

If I don't want to tap(), I can use this in various ways:

```javascript
start.then(function (result) {
  console.log(result); // An array of promises! Not what I want.
});
start.map(function (result) {
  console.log(result); // [1, 2] much more useful
});
start.spread(function (r1, r2) { 
  console.log(r1, r2); // r1 = 1, r2 = 2
});
```

These are very useful. If I do want to tap() though, I can only:

```javascript
start.tap(function (result) {
  console.log(result); // An array of promises, argh!
});
// Best map equivalent I can find:
start.tap(function (promises) {
  return Promise.all(promises).map(function (result) {
    console.log(result); // [1, 2]
  });
});
// Best spread equivalent I can find:
start.tap(function (promises) {
  return Promise.all(promises).spread(function (r1, r2) {
    console.log(r1, r2); // r1 = 1, r2 = 2
  });
});
```

This extra nesting and Promise.all()ing is confusing and messy. It'd be useful instead to add .tapMap() and tapSpread() methods too for this to get rid of that (not sure on exact names yet).

Thoughts? I'm happy to put a PR together for this, as long as it's something that'd be welcomed.

**Comment by benjamingr** [comment]
```js
start.all().tap(function(results){
     console.log(results); /// if you don't want to save the return value, like in your examples.
});
```

**Comment by pimterry** [comment]
Touche.

Yes, I entirely did not know you could use all() like that, and that solves this much neater. Closed, thanks!

**Comment by benjamingr** [comment]
Thanks for the issue, enjoy bluebird.
