### ISSUE TITLE
Explicit switch-off for the DEV mode.

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#676]
Please add an option to explicitly switch off Long Stack Traces and everything debugger-related in the library, i.e. to make it think that `NODE_ENV = production`.

The reason it is needed is because of all promise libraries out there, this one goes an extra mile tracking everything for debugging, and as a result the performance degrades dramatically, x10 times or worse, and tons of extra memory hogged in, which in many cases makes the library unusable in `development` mode.

Having to switch over to `production` every time is way too awkward. For example, I use over 10 packages for a project, all of which do useful stuff for `development` mode, while Bluebird just chokes. I need to keep using `development` mode here, but I can't sit around waiting for Bluebird to do its job because of it, plus it eats so much memory, my NodeJS process dies.

Obviously, I'm dealing with intensive use of promises here, 1m - 10m being executed frequently. But I do believe you guys care about performance a great deal, so it just makes sense to allow use of your library as intended, without having to flip the environment mode all the time.

**Comment by spion** [comment]
Maybe we could just stop doing this for `NODE_ENV=development` in 3.0 and only keep `BLUEBIRD_DEBUG`? That way the flag is orthogonal

**Comment by vitaly-t** [comment]
@spion , that might work. After all, for most people who use this library, they don't care about its debugging features, until something stops working as expected that is.

But on another hand, having an explicit switch-off key adds value to deploying different products onto the same machine. You can have one product for which debugging mode makes no difference, and then another one on the same machine where trying to debug Bluebird breaks the hell loose.

**Comment by benjamingr** [comment]
So, why do you have 10M promises in development?

**Comment by vitaly-t** [comment]
>So, why do you have 10M promises in development?

I'm developing for and testing a data migration product. Moving records across databases.

**Comment by benjamingr** [comment]
@vitaly-t what if it was a part of `Promise.config`? Currently you can opt out of long stack traces with [`Promise.config`](http://bluebirdjs.com/docs/api/promise.config.html) and that should override the environment flag. This is in 3.0

**Comment by vitaly-t** [comment]
@benjamingr that sounds great, as long as it is sufficient to bounce the performance back to production-like.

**Comment by benjamingr** [comment]
Can you try with 3.0?

**Comment by vitaly-t** [comment]
@benjamingr just tried to download it and override my node_modules\bluebird\js\main folder with contents from 3.0.0, folder src\

That didn't do it, getting an error
`
D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:66
if (!__BROWSER__) {
`
Do I need to build it somehow? I'm using Windows 8.1 64-bit here.

**Comment by benjamingr** [comment]
Yes, there are detailed build instructions in the README, basically do `node
tools/build` in the bluebird directory.

**Comment by vitaly-t** [comment]
I've tried that, getting an error...

```
D:\Temp\bluebird-3.0\tools>node build.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Temp\bluebird-3.0\tools\build.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

D:\Temp\bluebird-3.0\tools>
```

**Comment by benjamingr** [comment]
@vitaly-t bluebird is bootstrapped :D `npm install` in the directory. (This is also in the readme)

**Comment by vitaly-t** [comment]
Yeah, I saw it, couldn't get pass `npm install` though, it gives me:

```
D:\Temp\bluebird-3.0>npm install

> bluebird@2.9.12 prepublish D:\Temp\bluebird-3.0
> node tools/build.js --no-debug --release --browser --minify

D:\Temp\bluebird-3.0\tools\build.js:264
    throw new Error("cwd must be se to bluebird project root. Cwd is currently
          ^
Error: cwd must be se to bluebird project root. Cwd is currently

         D:\Temp\bluebird-3.0

    at Object.<anonymous> (D:\Temp\bluebird-3.0\tools\build.js:264:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by benjamingr** [comment]
Can you try renaming it from bluebird-3.0 to bluebird 😅? @vitaly-t

**Comment by petkaantonov** [comment]
There is explicit switch off in 3.0 with `BLUEBIRD_LONG_STACK_TRACES=0` but the long stack traces are generally not much slower but there is an edge case where they will be very slow currently which I believe you are hitting.

**Comment by vitaly-t** [comment]
@benjamingr after I renamed the folder into `bluebird`I was able to get it all up and working.

Did a test with `longStackTraces: false`. Not only it did bring the performance where it was in production mode, but I'm seeing about 5% performance improvement. You guys must have done some optimization on 3.0.0 branch? :) Well done :+1: 

@petkaantonov as mentioned in the second post here, doing it machine-wide isn't a very good idea. You may want to deploy your product to a server where somebody activated that flag for whatever reason and your product may slow down dramatically because of that.

**Comment by benjamingr** [comment]
> You guys must have done some optimization on 3.0.0 branch? :)

"You" is me listening and talking to Petka and Petka doing all the actual coding, just saying :D

**Comment by petkaantonov** [comment]
It's not a dramatic slow down, in fact you should not see any difference for a task like inserting rows to database

**Comment by vitaly-t** [comment]
@petkaantonov not only the performance does drop, but it drops 10-fold, while memory consumption goes right out the window. I have process that moves just 1m records, while keeping memory consumption at 70MB for the entire NodeJS process. Just as I set `development` mode, the NodeJS goes over 1GB and then dies.

**Comment by petkaantonov** [comment]
yes because you are hitting the edge case, don't make chains longer than 32 and long stack traces would have no effect.

**Comment by vitaly-t** [comment]
@petkaantonov I would, if I could, but I have a bit of pseudo-recursive logic here, that's not always possible to get rid of.

**Comment by petkaantonov** [comment]
@vitaly-t can you try implementing it like this:

```js
function sequence(t, factory) {
    var items = [];
    var index = 0;
    return new Promise(function next(resolve, reject) {
        var result = factory.call(t, index, t);
        if (!result) {
            return resolve(items);
        }
        result.then(function(data) {
            items.push(data);
            index++;
            next(resolve, reject);
        }, reject);
    });
}
```

**Comment by vitaly-t** [comment]
What does line `next(resolve, reject);` represent?

**Comment by petkaantonov** [comment]
Actually never mind, this will form a long stack chain as well.

**Comment by vitaly-t** [comment]
@petkaantonov , yes, it seems that any pseudo-recursion results in a long stack chain. And the only way to get rid of it is to remove the recursion, which is not always possible.

**Comment by petkaantonov** [comment]
I just tested and there is only a 0.5x perf difference between long stack traces and no long stack traces:

```js
var Promise = require("bluebird");
var $p = Promise;
Promise.longStackTraces();

function sequence(t, factory) {

    function loop(idx, result) {
        var obj;
        try {
            obj = factory.call(t, idx, t); // get next promise;
        } catch (e) {
            return $p.reject(e);
        }
        if (!obj) {
            // no more promises left in the sequence;
            return $p.resolve(result);
        }
        if (typeof(obj.then) !== 'function') {
            // the result is not a promise;
            return $p.reject("Promise factory returned invalid result for index " + idx);
        }
        return obj.then(function (data) {
            result.push(data);
            return loop(++idx, result);
        }, function (reason) {
            return $p.reject(reason);
        });
    }

    return loop(0, []);
}

function factory(idx) {
    if (idx < 10000) return Promise.delay(1);
}

var now = Date.now();
sequence(null, factory).then(function() {
    console.log("Done: ", Date.now() - now, "ms");
})
```

```
Done:  26150 ms
```

Without long stack traces:

```
Done:  17054 ms
```

**Comment by vitaly-t** [comment]
@petkaantonov , you cannot see the issue at such small numbers, try 1,000,000 ;)

**Comment by petkaantonov** [comment]
Nothing would change with that number in this test, in fact I tested with 1000 and 100 as well and it was exactly the same ratio of 0.5x.

**Comment by petkaantonov** [comment]
Now of course if I use `return Promise.resolve()` instead of `return Promise.delay` there is a huge 371x difference but the 1ms is intended to simulate the database transaction delay. The lower it is the bigger the performance ratio becomes.

**Comment by vitaly-t** [comment]
@petkaantonov , I think the test isn't very accurate, because in my test I do return resolve() all the time, and like you said, it makes all the difference.

**Comment by spion** [comment]
Whats wrong with `BLUEBIRD_DEBUG` being the only flag to control long stack traces? Then you can set NODE_ENV to development and not have to do anything for bluebird (or explicitly say `BLUEBIRD_DEBUG=0`)

**Comment by vitaly-t** [comment]
@spion then what happens when somebody sets that flag on a server where your project is deployed?

It will kill performance without you being able to do anything about it.

**Comment by spion** [comment]
@vitaly-t yes you could. You can do `process.env["BLUEBIRD_DEBUG"] = null;` before loading bluebird or any module that depends on it.

Why would anyone set the environment variable `BLUEBIRD_DEBUG` on a production server over which you have no control? Seems like a very unlikely situation to me.
