### ISSUE TITLE
Promise.resolve for functions

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/bluebird#681]
`Promise.resolve` works great with values when you do not know whether they are promises or not.
I could use something similar for functions. When I create a module that accepts an asynchronous function it would be nice to simply support both callback-taking and promise-returning functions.

I do not know if this would break something, but the simplest thing that came to my mind was to enhance `promisify` to use the returned value if it is a promise.

**Comment by benjamingr** [comment]
How would bluebird find out without invoking the function?

**Comment by tjconcept** [comment]
It would not before invoking it.

**Comment by benjamingr** [comment]
Then how would it know if to pass an additional resolver parameter for the callback function.

**Comment by tjconcept** [comment]
I guess it would not, so you would always pass a callback.

I am playing with something like this in my code:
```js
var asPromise;

var asNode = Promise.fromNode(function( cb ){
	asPromise = maybeNodish(cb);
});

return Promise.resolve(asPromise.then ? asPromise : asNode);
```

**Comment by benjamingr** [comment]
Always passing another argument is problematic if the function for example
takes variable arguments (and callback last if it's a nodeback). I'm afraid
this is not possible without type information.

**Comment by tjconcept** [comment]
Will `promisify` not always append a callback anyway? So taking the return value into account (checking if it is a promise) should not degrade the current behaviour.

**Comment by petkaantonov** [comment]
It wouldn't work too well in practice as the promisified function always has to pass the callback function. Like in your example if `maybeNodish` is a promise returning function that has 1 optional argument, a function you don't even know about is being passed as the optional argument which will inevitably lead to hard to debug bugs.

**Comment by tjconcept** [comment]
Okay, sounds reasonable. Thanks for your thoughts.
