### ISSUE TITLE
bluebird circular promise error while q-promise works

### ISSUE THREAD

**Issue by Ajkcki** [petkaantonov/bluebird#682]
The following  code uses q-library  to wrap PouchDB as a promise

<pre>
var Promise = require("q");
var PouchDB = require("pouchdb");
var PouchdbPromise = (function () {
    function PouchdbPromise(pouchdbName) {
        this._pouchdbP = null;
        this.pouchdbName = pouchdbName;
    }
    PouchdbPromise.prototype.getPouchdb = function () {
        var self = this;
        if (self._pouchdbP !== null)
            return self._pouchdbP;
        var deferred = Promise.defer();
        try {
            var _pouchdb = new PouchDB(self.pouchdbName);
            deferred.resolve(_pouchdb);
        }
        catch (e) {
            deferred.reject("Pouchdb init error:" + e);
        }
        self._pouchdbP = deferred.promise;
        return self._pouchdbP;
    };
    return PouchdbPromise;
})();

var pdbP = new PouchdbPromise("abc");
pdbP.getPouchdb().then(function (abc) {
    abc.get("1");
});
</pre>
It works fine. But switching to bluebird by changing the first line to
<pre>
var Promise = require("bluebird")
</pre>

leads to the following error:

<pre>
Unhandled rejection TypeError: circular promise resolution chain

    See http://goo.gl/LhFpo0

    at process._tickCallback (node.js:415:13)
From previous event:
    at PouchdbPromise.getPouchdb (SOMEDIR/app/scripts/playground/bluebird2.js:20:22)
    at Object.<anonymous> (SOMEDIR/app/scripts/playground/bluebird2.js:31:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
</pre>

the error was thrown at line 20 `deferred.resolve(_pouchdb)`. 

 I know `Promise.defer()` is depreciated, using `new Promise` gets the same error. 

I also tried to run the code in a browser (Chrome 43), bluebird throws the same error and both q and Chrome's native promise work fine. I'm using bluebird version 2.9.30

**Comment by petkaantonov** [comment]
This is because pouchDb resolves with itself which normally leads to infinite loop. In fact doing this in Q leads to infinite loop while bluebird currently gives the circular error immediately:

```js
var o = {
    then: function(f) {
        setTimeout(function() {
            f(o);
        }, 1);
    }
};
```

The reason pouchDB works in Q is that pouchDB actually does something like this:

```js
var o = {
    then: function(f) {
        setTimeout(function() {
            delete o.then;
            f(o);
        }, 1);
    }
};
```

So it won't lead to infinite loop because on second iteration there is no `.then`.

It's still a bug because Promises/A+ clearly requires an implementation to go into an infinite loop into the first scenario instead of rejecting with the circular resolution error.

**Comment by bergus** [comment]
Yeah, looks like a bug in Promises/A+. Would you mind to report it?

**Comment by benjamingr** [comment]
I think before opening an actual bug at A+ it'd be wise to ping @domenic
and ask about it. It's entirely possible this requirement has a perfectly
valid reason. Did you mean to reply on the Q issue I opened or here?

**Comment by bergus** [comment]
I meant to reply where I did :-) I don't think discussing this in a promisesaplus issue would have been wrong, even if the bug is invalid.
