### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by FranzSkuffka** [petkaantonov/bluebird#684]
From my perspective, as Bluebird is approaching v3, it could use some clean visuals. Just gave it a shot:
#683

**Comment by petkaantonov** [comment]
FYI this the website under construction http://bluebirdjs.com/docs/api-reference.html. I wonder how it would fit there? The colors are white orange blue

**Comment by FranzSkuffka** [comment]
The edit link does not seem to work.

**Comment by petkaantonov** [comment]
it is for submitting pull requests for article modifications once the site goes live (is merge to master)
