### ISSUE TITLE
Transaction example and using

### ISSUE THREAD

**Issue by ddcovery** [petkaantonov/bluebird#686]
Transaction commit, sometimes, produces errors (logical errors) because, for example, you are using an optimistic transaction model.

In these cases, the error is not an "internal" error and must be treated as an expected situation (i.e.:  you must return a logical error to the user or retry or ...).

In your examples for Disposing you propose this

```javascript
.disposer(function(client, promise) {
        if (promise.isFulfilled()) {
            return client.queryAsync('COMMIT').then(closeClient);
        } else {
            return client.queryAsync('ROLLBACK').then(closeClient);
        }
        function closeClient() {
            if (close) close(client);
        }
    });
```

Obviously, ROLLBACK must work allways and an error when rollbacking tell us about internall error... 

Problem is COMMIT, because a COMMIT exception must be "logically" treated and the using/disposer pattern causes a crash if disposition fails.... 

A more valid solution (I propose) is taking out disposer the "commit" management and force the caller to perform an explicit commit

```javascript
var pg = require('pg');
var Promise = require('bluebird');
Promise.promisifyAll(pg);

function beginTransaction(connectionString) {
    var close;
    var commited=false;
    return pg.connectAsync(connectionString).spread(function(client, done) {
        close = done;
        return client.queryAsync('BEGIN').then(function () {
            return { 
              client: client, 
              commit: function(result){ 
                   return client.queryAsync("COMMIT").then(function(res){ commited=true; return result;});
              }
            };
        });
    }).disposer(function(trx /*, promise*/) {
        if (commited) {
            closeClient();
        } else {
            return trx.client.queryAsync('ROLLBACK').then(closeClient);
        }
        function closeClient() {
            if (close) close(trx.client);
        }
    });
}

exports.beginTransaction = beginTransaction;
```
that can be used in this way:
```javascript
var beginTransaction = require("pghelpers").beginTransaction;
var using = require("bluebird").using;

using( beginTransaction(connectionString), function(trx){
   return trx.client.queryAsync(query).then(trx.commit);
}).then(function(result){
  // valid commited result
}).catch(function(err){
  // if commit fails... we have an error here and we can treat it adequately.
});

Is similar to the old c# "synchronous" pattern for transactions with "using" statements

using(var trans = beginTransaction()){
  ....
  trans.commit();
}

**Comment by benjamingr** [comment]
Part of the idea is not having to `commit` yourself but instead relying on the `return` value. It's entirely reasonable to attempt to re-commit in the disposer if the commit failed. My actual code in production looks different though :)

**Comment by ddcovery** [comment]
My filosophy is error in commit must be propagated as a promise rejection and disposer doesn't allow... this:  this is the only reason I commit explicitily.

Sometimes, retry is not a solution for commits... because a logical condition can't be satisfied on database (or something changed from original state)  and retry will fail allways.  My experience is  COMMIT error requires to be treated as a "logical" exception, not an "internal" one... and my usual solution is to tell the end user "pls, try it latter"... :-p

**Comment by spion** [comment]
You are right. Ultimately the disposer pattern is not really suitable for transactions In my code I use a slightly different variation of the pattern [(example)](1). The disposer should only get rid of resources.

We should probably remove the transaction example

DB.prototype.transaction = function(fn) {
  return using(pool.acquireConnection(), conn => {
    var tx = conn.begin()
    return Promise.try(fn, tx)
      .then(res => tx.commit().thenReturn(res),
               err => tx.rollback()
                    .catch(e => {/* optionally, add the rollback error to the resulting error */})
                    .thenThrow(err))
  });
}

[1]: https://github.com/doxout/anydb-sql/blob/master/test/index.js#L66-L78

**Comment by ddcovery** [comment]
Nice pattern @spion,
I have to use it.

**Comment by benjamingr** [comment]
@spion feel like improving this in the docs (and also in the 3.0 docs)?

**Comment by ddcovery** [comment]
I think removing transaction example is a good idea (as a using/disposer example)... but it is a really nice example of promises:  This example atracted me to bluebird :-)

**Comment by spion** [comment]
I'll give it a try tomorrow
