### ISSUE TITLE
May we have a Promise.isPromise() static method ?

### ISSUE THREAD

**Issue by doobinay** [petkaantonov/bluebird#693]
I'd love to have a Promise.isPromise() static method.
For now I'm doing this check (using lodash) :

`var isPromise =  _.isObject(p) && _.isFunction(p.then);` 

What do you think ?

**Comment by benjamingr** [comment]
Sorry, but no.

We used to have a `Promise.is` but that was redundant.

If you want to work with something "as-if" it is a Promise, then
`Promise.resolve` it.

If you want to check if something is a trusted bluebird promise, do `p
instanceof Promise`.

**Comment by doobinay** [comment]
Okay, got it. Thank you

**Comment by benjamingr** [comment]
Cheers, thanks for coming up with an idea.
