### ISSUE TITLE
Error in promisifyAll(jsonwebtoken)

### ISSUE THREAD

**Issue by kikar** [petkaantonov/bluebird#694]
When I try to promisifyAll([jsonwebtoken](https://github.com/auth0/node-jsonwebtoken)), the function ```jwt.signAsync(token, secretOrPublicKey)``` doesn't work properly.

**Comment by benjamingr** [comment]
`sign` is a synchronous function, you don't need to - and shouldn't, promisify those.

Promisification is for callback taking functions. Just use the API as synchronous.

    var token = jwt.sign(token, secretOrPublicKey)

**Comment by tsm91** [comment]
@benjamingr @kikar i experiencing the same problem. `jwt.sign` actually has a last optional callback parameter, [see](https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L36).

```js
Promise.promisifyAll(jwt);

....

jwt
  .signAsync(data, config.jwtSecret, { expiresIn: '1h' })
  .then(token => {
    console.log('TOKEN: ', token);
  })
  .catch(err => {
    // for some reason it will run to the catch with err as the token
    console.log('TOKEN: ', err);
  });
```
