### ISSUE TITLE
longStackTraces only includes lines starting with "at"

### ISSUE THREAD

**Issue by aaronyo** [petkaantonov/bluebird#698]
When longStackTraces are enabled, only lines that start with "at" are included in each event's trace, at least on V8.  Here's the regexp from captured_trace.js that does this filtering:

```js
    var v8stackFramePattern = /^\s*at\s*/;
```

I've been doing my own manipulation of stack traces, adding lines starting with "Caused by: ...", to represent nested errors.  Those "Caused by" lines get thrown out.

I'm sure there's some good reason for filtering the lines in some way.  If someone could provide more background, I can try to come up with a fix that makes Promise.longStackTraces() play nicely with other manipulations of error.stack.

**Comment by petkaantonov** [comment]
It's not really possible to know when to retain custom text or even differentiate between custom text and the default text that must be discarded.

When stitching stack traces together individual frames or groups of frames can be discarded and it's not possible to know whether some related 3rd party text should be retained or not.

**Comment by aaronyo** [comment]
Thanks for the quick response.

I can think of a couple solutions.  The first is my preferred, though I'm not sure it is practical yet, and the second seems at least better than what we have today.

1. Instead of using a regexp to choose the line you do want, use patterns to identify the lines you do *not* want.  (I only say this might not be practical because I'm not certain how much stuff there is to screen, and how often it changes.  So far, though, all I've noticed is that some lines that start "Error:" need to be removed)
2. Allow this to be configurable in the call to Promise.longStackTraces()

It is moot, though, if you don't think the use case I stated before is important.  This is a facility of other languages that I have become accustomed to (chaining exception causes from low level to high level).

**Comment by benjamingr** [comment]
@aaronyo well, what I do is instead of relying on the a mutated stack is throw meaningful `Error`s and attach properties to them as I go, that way in the final `catch` I can extract everything I need for them (some of my error types have as much as 4 different stages attaching properties and useful information to them. You can also augment `error.message` IIRC.

```js
Promise.reject(new Error()).
catch(e => {e.foo = 1; throw e; }).
catch(e => {e.bar = 2; throw e; }).
catch(e => {e.baz = "Hi"; throw e; }).
catch(e => {e.causedBy = "Here"; throw e; }).
catch(e => {throw new  SpecifiecException(e)). // innerException like in C#
.catch(e => {
    let {foo, bar, baz, causedBy} = e.inner;
    console.log(foo, bar, baz, causedBy);
})
```

Does that solve your problem?

**Comment by aaronyo** [comment]
@benjamingr

For now, I just attach "at" to the front of my "Caused by:" messages, so I do have a workaround, if terribly hacky.

The issue with just depending on custom vars is that you often don't have control of whatever top level error handler is catching your exception and printing it out.  For example, when running automated tests, the testing harness will typically print err.stack when an error bubbles to the top, and it won't know about your custom vars.
