### ISSUE TITLE
sequence

### ISSUE THREAD

**Issue by tkellen** [petkaantonov/bluebird#70]
would you accept a PR that implements [sequence](https://github.com/cujojs/when/blob/master/docs/api.md#whensequence) like when?

**Comment by JohnGurin** [comment]
You may find this notion about Promises an Seqs interesting:
https://github.com/getify/You-Dont-Know-JS/blob/master/async%20&%20performance/apA.md#sequences-abstraction-design
5th paragraph. Excerpt:

> A sequence is kind of like a Promise chain. However, with Promise chains, there is no "handle" to grab that references the entire chain. Whichever Promise you have a reference to only represents the current step in the chain plus any other steps hanging off it. Essentially, you cannot hold a reference to a Promise chain unless you hold a reference to the first Promise in the chain.

> There are many cases where it turns out to be quite useful to have a handle that references the entire sequence collectively. **The most important of those cases is with sequence abort/cancel. As we covered extensively in Chapter 3, Promises themselves should never be able to be canceled, as this violates a fundamental design imperative: external immutability.**

**Comment by benjamingr** [comment]
Lol, not that again

**Comment by markstos** [comment]
Not what again?

**Comment by benjamingr** [comment]
The comment above mine - I really have no way to say this without maybe offending l Kyle, and I consider Kyle a friendly so I'm going to stick to my unclear grumble :)

**Comment by markstos** [comment]
OK. I can't say that the comment did much to move the conversation forward, since it dismissed the comment without providing any specific objection.

**Comment by bergus** [comment]
Let me be the offender then :-)

That argument seems to be flawed. If we cared for immutability, a sequence (or chain) would not be cancellable as well - aborting a sequence changes its eventual result. So if we want cancellation, we cannot have this external immutability. If we understand the implications of such impurity, and can control them, we can make our chains abortable. There is no need to leave our accustomed framework (promises) and prop a new structure (asynquence) on top of them, if we can just make promises cancellable.
Indeed, we don't really cancel *values*, but the "`then`+callback" control structure. Check out 3.0 cancellation semantics, which maintain as much of the [mentioned](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md#promise-uncancelable) trustability as possible.

**Comment by markstos** [comment]
Thanks for the clear explanation @bergus !

**Comment by vitaly-t** [comment]
Late to the party, with possible alternatives: [batch](https://github.com/vitaly-t/spex/blob/master/docs/code/batch.md) and [sequence](https://github.com/vitaly-t/spex/blob/master/docs/code/sequence.md).

**Comment by markstos** [comment]
Thanks for the suggestion, @vitaly-t . I'll check those out.

**Comment by digital-flowers** [comment]
very late but i should post my version maybe it's good nobody knows :P 
```javascript
const Promise = require("bluebird");

/**
 * a utility to check if a value is a Promise or not
 * @param value
 */
const isPromise = value => value !== null && typeof value === 'object' && typeof value.then === 'function';

/**
 * a utility to resolve an array of promises sequentially
 * @param {Array} array any array of promises, values or a mix
 * @param {Function} func an optional function to create a promises from values if not exists Promise.resolve will be used
 * @return {Promise}
 */
const sequence = (array, func) => array.reduce((a, b) => a.then(() => {
  let value = (typeof func === "function") ? func(b) : b;
  if (typeof value === "function") {
    value = value();
  }
  return isPromise(value) ? value : Promise.resolve(value);
}), Promise.resolve());

module.exports = {sequence, isPromise};
```
