### ISSUE TITLE
Stray html tag in LICENSE file

### ISSUE THREAD

**Issue by myndzi** [petkaantonov/bluebird#700]
I'm playing with some code to identify licenses according to the SPDX matching rules, and noticed that there's a random `</p>` in the LICENSE file for this package. Consider removing? :)

**Comment by benjamingr** [comment]
Yeah whatever.

**Comment by myndzi** [comment]
Haha, thanks. SPDX has plenty of messed up stuff, but I was gonna feel bad hacking it to take care of a case in one of my favorite libraries ;)
