### ISSUE TITLE
Add a concurrency option to .settle()

### ISSUE THREAD

**Issue by yvele** [petkaantonov/bluebird#703]
`.map()` and `.filter()` have both a concurrency option, can `.settle()` also get one?

PS: In section [What's new in 2.0](https://github.com/petkaantonov/bluebird/blob/master/changelog.md#whats-new-in-20) in changelog, this is written:
>  .map(), .each(), .filter(), .reduce() reimagined from simple sugar to powerful concurrency coordination tools

Was `.settle()` forgotten to be part of the restricted powerful concurrency coordination tools? :)

**Comment by petkaantonov** [comment]
This is a misunderstanding of promise fundamentals. You cannot control a promise, it is controlled by the executioner handled to the promise constructor when the promise is initially created. Settle takes an array of promises without any knowledge about where or how they were created.

Also `.settle` is deprecated in favor of `.reflect()` (which can be used with `.map` to achieve what you want anyway)

**Comment by benjamingr** [comment]
Petka is right here, a promise is an already started operation, I'd just like to add that you can :

```js
    Promise.map(values, v => fn(v).reflect()).then(...
```

Which is what Petka meant by using `reflect`

**Comment by yvele** [comment]
Ok thanks @petkaantonov and @benjamingr  ;) that's perfect.

But shouldn't be `.settle` removed from the [doc](https://github.com/petkaantonov/bluebird/blob/master/API.md#settle---promise) and be explicitly deprecated?

**Comment by petkaantonov** [comment]
It will be deprecated in 3.0
