### ISSUE TITLE
Throwing an error from within the map callback doesn't break chain.

### ISSUE THREAD

**Issue by reggi** [petkaantonov/bluebird#705]
I posted this on [stackoverflow](http://stackoverflow.com/questions/31481958/break-promise-map-from-within-function-value) with no response and I'm curious if I'm going crazy, it's a bug with bluebird, or if there's another way to do what I'm trying to get done. 

Here's the reposting from stackoverflow:

In this example code below you can see that I have a chain of functions that are getting mapped, and when and when the error is thrown the chain is exited. The value of the global `x` is set to `bar` from the first function but it's not set to `baz` from the third because it never runs.

```javascript
var x = "foo"

Promise.map([
  function(){
    x = "bar"
    return true
  },
  function(){
    throw new Error()
  },
  function(){
    x = "baz"
    return true
  }
], function(fn){
  return Promise.method(fn)()
})
.catch(function(e){
  console.log(e) // [Error]
})
.then(function(){
  console.log(x) // "bar"
})
```

However when I open up the promise within the map function and interject a conditionally thrown error `x` is changed to `baz`, and the third function does run. 

```javascript
var x = "foo"

Promise.map([
  function(){
    x = "bar"
    return true
  },
  function(){
    return "bad value throw error"
  },
  function(){
    x = "baz"
    return true
  }
], function(fn){
  return Promise.method(fn)().then(function(val){
    if(val == "bad value throw error") throw new Error()
    return val
  })
})
.catch(function(e){
  console.log(e) // [Error]
})
.then(function(){
  console.log(x) // "baz"
})
```

How can I interject an error in the promise map and throw that error breaking the map chain?

Is there another bluebird method that can run an array of promises in parallel?

**Comment by reggi** [comment]
Could really use some help with this, not to rush you, whenever you have a chance @benjamingr @petkaantonov. :rabbit:

**Comment by petkaantonov** [comment]
If you need sequential in-order execution use Promise.each.

> Is there another bluebird method that can run an array of promises in parallel

You cannot run something in parallel but in-ordee, that makes no sense.

**Comment by reggi** [comment]
@petkaantonov thanks, `.each` seemed to work at first, it does fix the issue described above. However `.each` returns a copy of the original array and not the values from the promises, this is really odd. What's the best way to capture those values? Use a global?

**Comment by spion** [comment]
Promise.map has a [second argument for concurrency](https://github.com/petkaantonov/bluebird/blob/master/API.md#option-concurrency), does that help?

**Comment by reggi** [comment]
@spion nope I tried that, doesn't work.

**Comment by reggi** [comment]
@spion Here's a test that shows concurrency does not break the chain when an error is mapped

https://gist.github.com/reggi/fe3c8fba9c536c83f9a6

**Comment by reggi** [comment]
@petkaantonov Sorry for the typo I updated it to `series` instead of `parallel`.

**Comment by spion** [comment]
I see - apparently `Promise.map` doesn't have any order guarantees anymore and the concurrency parameter doesn't add any either. 

I think that 3.0 will have `Promise.each` return the results; until then, I suggest avoiding `map`/`filter` and using `Promise.reduce` for your use case:

```js
Promise.reduce(fns, (acc, fn) => 
  Promise.try(fn)
  .then(val => /* maybe throw error ... */)
  .then(v => acc.push(v)), 
Promise.resolve([]))
```

**Comment by reggi** [comment]
@spion My use case is a little more specific check it out here https://github.com/reggi/node-middleware-run/blob/master/index.js#L21-L38

**Comment by spion** [comment]
My example had a bad `acc.push` line which doesn't do what its supposed to.

`Promise.reduce` isn't all that different from `Promise.each` except you get to return a result. In your case I guess you don't really need to accumulate all the results (you just need the last one), so you could probably just run

```es6
Promise.reduce(middlewares, (last, mw) =>
  Promise.try(mw, [req, res, next])
    .then(val => { /* handle all cases */ }),
Promise.resolve())
```
