### ISSUE TITLE
Feature request handler for both .catch and .then

### ISSUE THREAD

**Issue by reggi** [petkaantonov/bluebird#706]
When running a promise within a test or some other applications it's nice to resolve the value of the promise regardless if it's throws an error or a value. I looked into `reflect`, `finally`, and `done` all with unexpected results. 

Here's a simple use case (also posted on [SO](http://stackoverflow.com/questions/31495313/promise-handle-catch-and-then-at-once)) and here are some [tests](https://gist.github.com/reggi/db97369a07bb4df8d5f5), I was surprised to find that `finally` throws errors instead of catching. Ideally I want `.finallyCatch` or `.thenCatch`.

```javascript
var example = function(throwError){
  return Promise.resolve().then(function(){
    if(throwError) throw new Error("test error")
    return throwError
  })
}

example(true).SOMETHING(function(value){
  console.log(value) // error
})

example(false).SOMETHING(function(value){
  console.log(value) // false
})
```

Shorthand for 

```javascript
promise.catch(function(err){ 
    return err;
})
```

**Comment by reggi** [comment]
Here's a prototype I created.

I do realize that this is dangerous because it takes the error out of the chain, but it works.

    Promise.prototype.thenCatch = function(fn){
      return this
        .catch(function(e){
          return e
        })
        .then(fn)
    }

And to use.

    example(true).thenCatch(function(value){
      expect(value).to.exist
        .and.be.instanceof(Error)
        .and.have.property('message', 'test error')
    }).thenCatch(done)


    example(false).thenCatch(function(value){
      expect(value).to.equal(false)
    }).thenCatch(done)

**Comment by reggi** [comment]
Any ideas thoughts on this? Is it bad practice? Why doesn't it exist already? Better name ideas?

**Comment by benjamingr** [comment]
This is a less compoable version of `reflect`, you can already use `reflect` for this use case.

**Comment by reggi** [comment]
Hey @benjamingr,

I found that this is exactly what I need

````
Promise.prototype.always = function(fn){
  return this.then(fn, fn)
}
````

Then you can do something like this It's clean and simple. 

```
  it("should have test prop foo & catch thrown error", function(done){
    var req  = httpMocks.createRequest({})
    var res = httpMocks.createResponse()
    middlewareRun(req, res, [
      middlewareSetTest("foo"),
      middlewareThrowError,
      middlewareSetTest("bar")
    ]).always(function(value){
      expect(value)
        .and.be.instanceof(Error)
        .and.have.property('message', 'test error thrown')
      expect(req).to.have.property("test", "foo")
    }).always(done)
  })
```

How would you do this with reflect?

**Comment by benjamingr** [comment]
`.catch(/* expects on error */).then(/* expects on req */)` no reflect needed here

**Comment by reggi** [comment]
The the code above becomes this.

```
var handler = function(value){
  expect(value)
    .and.be.instanceof(Error)
    .and.have.property('message', 'test error thrown')
  expect(req).to.have.property("test", "foo")
  return done()
}

it("should have test prop foo & catch thrown error", function(done){
  var req  = httpMocks.createRequest({})
  var res = httpMocks.createResponse()
  middlewareRun(req, res, [
    middlewareSetTest("foo"),
    middlewareThrowError,
    middlewareSetTest("bar")
  ]).catch(handler).then(handler)
})
```

The [documentation has a use case for this with finally where an ajax call is doing the same thing](https://github.com/petkaantonov/bluebird/blob/master/API.md#finallyfunction-handler---promise), except `.finally` it doesn't catch errors. This would be the same kind of convenience function.

**Comment by benjamingr** [comment]
Your code in the last comment makes no sense (what is the `done` doing there?). Don't use `done` with promise tests (mocha has syntax for that), even if it did make sense it wouldn't work nicely in your case. 

```js
it("should have test prop foo & catch thrown error", function(){
  var req  = httpMocks.createRequest({})
  var res = httpMocks.createResponse()
  return middlewareRun(req, res, [
    middlewareSetTest("foo"),
    middlewareThrowError,
    middlewareSetTest("bar")
  ]).catch(function(err){ 
       assert((err instanceof Error) && (err.message === "test error thrown"));
       assert(req.test === "foo");
  });
});
```

**Comment by raine** [comment]
The test above will incorrectly pass if there is no exception, because the catch function is never called.
