### ISSUE TITLE
3.0.0 Beta?

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#707]
Would you, guys, please start publishing 3.x branch as Beta on NPM - 
```
npm publish --tag beta
```
so it can be integrated as a dependency automatically by early adopters?

**Comment by Rush** [comment]
Any news on the 3.0.0 release? :)

**Comment by petkaantonov** [comment]
Fixed in 3.0 release

**Comment by vitaly-t** [comment]
That's not a fix, that's cheating! :) :) :)

**Comment by bergus** [comment]
Yay!

**Comment by Rush** [comment]
Congrats :)
