### ISSUE TITLE
Split a promise's fulfillment to multiple handlers

### ISSUE THREAD

**Issue by skeate** [petkaantonov/bluebird#710]
Something like...

```javascript
fs.readFileAsync(file, 'utf8')
  .split(convert, analyze)
  .spread(function(conversion, analysis) {
    /* ... */
  });
```

Ultimately, just short for 

```javascript
fs.readFileAsync(file, 'utf8')
  .then(function(f) {
    return [convert(f), analyze(f)];
  })
  .spread(function(conversion, analysis) {
    /* ... */
  });
```

but a built in method seems nicer.

**Comment by bergus** [comment]
I think this really shouldn't be a library method. Rather, write a helper function to do this. What you are asking for is exactly the [`Arrow` fanout](http://hackage.haskell.org/package/base-4.8.1.0/docs/Control-Arrow.html#v:-38--38--38-) functionality:
```
function split(fa, fb) {
    return function(x) {
        return [fa(x), fb(x)];
    };
};
….then(split(convert, analyze)).spread…
```
(In terms of [Ramda](http://ramdajs.com/), it should be `split = R.unapply(R.ap)`)

**Comment by benjamingr** [comment]
I don't know, doing it regularly isn't too verbose.

```js
fs.readFileAsync(file, 'utf8')
  .then(x => [convert, analyze].map(f => f(x)));
```


You're welcome to add a method to your own copy and of course publish it by the way.

**Comment by skeate** [comment]
Fair enough
