### ISSUE TITLE
feature: promise that only executes, once a listener (then, catch) is added

### ISSUE THREAD

**Issue by User4martin** [petkaantonov/bluebird#711]
The idea is to be able to use a promise as a function argument, but NOT to start its execution, until the function decides it is needed

```javascript
// alternative Promise.runDeferred(...)
   var slowOptionalStuff = new PromiseRunDeferred(function(resolve, reject) {
       return Foo.promiseLoadData().PromiseDecryptData().promiseCheckData();
   })

   Bar(something, slowOptionalStuff);
   Bar(something, promiseThatIsAlreadySettled);

  function Bar(something, promisedObject) {
   //do stuff
     if (condition) {
        promisedObject.then(bar); // here (and only here and now) the function passed to promisedObject is called, and the slow running chain started.
     }
  }
```

The calling code can create a promise, but decide it should not run, unless its becomes known that its result will be used.
But other calling code can use a normal promise, that may have settle already.

Yet the called function does not need to know the difference. It just takes a promise, to which it attaches.

To do this the promise needs to know when the first handler for onResolve or onRejected is added. At that time the promise will execute its function.

**Comment by benjamingr** [comment]
"Lazy" promises are Promises/A+ exclusive. We can't do that in bluebird, you might be interested in https://github.com/zenparsing/es-observable/issues/34

**Comment by spion** [comment]
@benjamingr do you have any references on how laziness breaks A+?

**Comment by phpnode** [comment]
`slowOptionalStuff`  *isn't* a promise because it's not promising anything, but it can just be a thenable that Bluebird will assimilate, e.g.
```js
slowOptionalStuff = {
  then: (args...) {
    return Foo.promiseLoadData().PromiseDecryptData().promiseCheckData().then(...args);
  }
};
```
