### ISSUE TITLE
Freezing the API surface area / new method proposal criteria

### ISSUE THREAD

**Issue by spion** [petkaantonov/bluebird#712]
Is it a good time to explicitly document that bluebird's API surface is (almost?) frozen to avoid a flood of methods being overwhelming for users?

Alternatively, maybe we could formalize the criteria for a "good API addition proposal" a bit? Maybe request that the proposal includes e.g. at least 2 different examples of the new method combining well with the rest of the existing API to give new previously unavailable functionality with before/after code comparisons?

Related to this, we might also want to make a list of methods that we'd like to deprecate (also with before/after code) - I remember that @petkaantonov saying that there are still few methods that are not that useful that he'd like to get rid of

**Comment by benjamingr** [comment]
@petkaantonov comes and goes in periods (as we all do) based on what else is going on in his life, I suspect that the next thing that'll happen is him coming back, finishing with 3.0 (mostly docs left) and then the API will be mostly frozen (unless unexpected things arise).  

There are methods we're getting rid of (I think `settle` `spawn` and a bunch of others that were superseded). I'd love to find more or maybe modularize things a bit.

**Comment by tjconcept** [comment]
Maybe include a list of proposals that were not accepted (and a reason/workaround if it makes sense).

**Comment by petkaantonov** [comment]
@spion didn't you make a gist about this

**Comment by spion** [comment]
Yep, its here: https://gist.github.com/spion/294bb53db70bd700b0c4

**Comment by petkaantonov** [comment]
@spion Some part of that could be added to the contribute website documentation page with its own header or a separate page even

**Comment by benjamingr** [comment]
Are you interested in adding the relevant parts to the page @spion ?
