### ISSUE TITLE
Allow promisifyAll filter to be an array.

### ISSUE THREAD

**Issue by SimonSchick** [petkaantonov/bluebird#713]
This would by handy is some circumstances where you only want to promisify a limited set of methods rather than all of them, having to write a function that checks for the name feels somewhat dirty.

**Comment by benjamingr** [comment]
Example usage?

**Comment by SimonSchick** [comment]
In my case I worked with hapi and wanted to promisify all the methods provided by the server, however not all methods(inject) are immediacy available upon server creation(only after making it listen on a port), therefore I had use a promisifyAll with a filter to only make it promisify the missing function.

See here: https://github.com/webspeak2/webspeak-backend/blob/master/app/servers/hapi.js#L41

**Comment by SimonSchick** [comment]
In my case the usage would be straight forward:

```
Promise.promisifyAll(server, { filter: ['inject'] });
```

**Comment by benjamingr** [comment]
@SimonSchick `promisifyAll` already ignores 'doubles', that is- it won't promisify an already promisified function so that shouldn't be a performance issue. Any other use cases for an array filter?

A RegExp filter sounds more versatile, but I'm not yet convinced of either (more use cases would go a long way).

**Comment by benjamingr** [comment]
Closed for inactivity, if you come up with a use case we can gladly revisit this.

**Comment by SimonSchick** [comment]
Ah sorry, must have missed the notification about you replying,

Can't come up with another use case for now, sorry.
