### ISSUE TITLE
Set different schedulers for different promises

### ISSUE THREAD

**Issue by ggoodman** [petkaantonov/bluebird#717]
Hello, from what I've been able to find from inspecting promises, there doesn't seem to be a mechanism that allows the user of different schedulers for different promises. Is there something I'm missing?

I thought that I could possibly introspect the promise in the callback function of `Bluebird.setScheduler()` but I wasn't able to find anything relevant.

Any thoughts?

**Comment by bergus** [comment]
You could load two instances of Bluebird, and set different schedulers for them. Then, when you want to use a different scheduler for a part of your promise chain, use `OtherPromise.resolve(…)`.

However I really wonder why you would want to do this? Aren't all your promises living in the same environment, and want to use the fastest possible scheduling available everywhere?

**Comment by benjamingr** [comment]
Please see the section called "for library authors".

Wondering, what's the use case?

**Comment by ggoodman** [comment]
@benjamingr that will definitely do the trick.

The use case is for integration into Angular 1.x. In Angular, there are two versions of their Promise api: 1) `$q` (schedules within the `$digest` loop); and 2) `$$q` (schedules outside the `$digest` loop). The latter is more of an internal api for when `$digest` would be wasteful. In order to `$provide.decorate()` the `$q` and `$$q` services to use the magic of Bluebird under the hood, I need two different schedulers (or at least a mechanism to fire the appropriate scheduler based on the promise _type_).

**Comment by benjamingr** [comment]
Interesting, I wasn't aware of `$$q`. I can't think of a way outside two copies with the current API. There might be one though - what's the decorating code?

**Comment by ggoodman** [comment]
This is what I put together this morning to test out the idea:

```javascript
mod.config(['$provide', function ($provide) {
    $provide.decorator('$q', ['$delegate', '$rootScope', function ($delegate, $rootScope) {
        Bluebird.setScheduler(function (tick) {
            $rootScope.$evalAsync(tick);
        });
    
        var $q = function (resolver) {
            return new Bluebird(resolver);
        };
        
        $q.defer = function () {
            var dfd = Bluebird.defer();
            
            return {
                promise: dfd.promise,
                resolve: dfd.resolve.bind(dfd),
                reject: dfd.reject.bind(dfd),
                notify: dfd.progress.bind(dfd),
            };
        };
        
        $q.all = Bluebird.all;
        $q.reject = Bluebird.reject;
        $q.when = Bluebird.resolve;
        
        return $q;
    }]);
}]);
```
