### ISSUE TITLE
Can't switch off Debug mode

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#719]
Using the latest version, can no longer switch off the long-stack tracing, or the entire debug mode for that matter:

* setting `BLUEBIRD_DEBUG=0` - no effect;
* setting `NODE_ENV=production` - no effect.

Had to go manually comment some code out to make the long-stack tracing go away:

```javascript
var debugging = false/* || (util.isNode &&
                    (!!process.env["BLUEBIRD_DEBUG"] ||
                     process.env["NODE_ENV"] === "development"))*/;
```

what's going on???!!!

**Comment by spion** [comment]
If you want to disable BLUEBIRD_DEBUG you either have to `unset` it or set it to an empty string e.g. `BLUEBIRD_DEBUG=''`

**Comment by vitaly-t** [comment]
I did debugging for this thing, and I found that if I set `BLUEBIRD_DEBUG=0`, then when your code calls `!!process.env["BLUEBIRD_DEBUG"]`, that expression is true, because `!!` applied to a string that contains `"0"` is `true`.

That's a clear bug. Please re-open the issue.

**Comment by spion** [comment]
Reopening because accepting `BLUEBIRD_DEBUG=1` to disable but not accepting `BLUEBIRD_DEBUG=0` to disable is a bad UX. 

There are a few things we might want to consider:

1. If the value is "0", should that override NODE_ENV?
2. If the value is anything other than "1" (e.g. "false" etc) should we handle those cases too?

**Comment by vitaly-t** [comment]
There was a breaking change in one of the recent releases, because I've been using `BLUEBIRD_DEBUG=0` for a while, as was suggested to me here a while ago, and it worked. It stopped recently.

**Comment by spion** [comment]
@vitaly-t if thats the case, then which is the version that accepts `BLUEBIRD_DEBUG=0` ? I checked and the same logic goes at least 6 months back.
