### ISSUE TITLE
Unexpected "Unhandled rejection" with "return" method

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/bluebird#721]
```js
var rj = Promise.reject(new Error());

rj
	.return(Promise.join(rj))
	.spread(console.log)
	.catch(console.error);
```

Gives an "Unhandled rejection Error" with Bluebird 2.9.34.

The example seems freakish, but it is a distilled version of a more complex scenario where the join has more arguments.

My first thought was to swap a simple array for the join, but add another thing to the array, and you're back to square one:

```js
var rja = Promise.reject(new Error());
var rjb = Promise.reject(new Error());

rja
	.return([ rja, rjb ])
	.spread(console.log)
	.catch(console.error);
```

Gives an "Unhandled rejection Error" as well.

**Comment by bergus** [comment]
Hm, the error of `rjb` *is* nowhere handled?

**Comment by tjconcept** [comment]
Yes it is. Try doing this:

```js
var rja = Promise.resolve();
var rjb = Promise.reject(new Error());

rja
	.return([ rja, rjb ])
	.spread(console.log)
	.catch(console.error);
```

Whether using an array or a `Promise.join` it is handled.

**Comment by tjconcept** [comment]
:+1:
I updated Bluebird, ran the tests and poof, all "unhandled" errors were gone :)
