### ISSUE TITLE
spread doesn't seem to work for reject function

### ISSUE THREAD

**Issue by DecSander** [petkaantonov/bluebird#727]
The following doesn't seem to flatten the array passed to the reject function in processAccount. Basically, as far as I can tell, spread doesn't work for rejectedHandlers. However ... I may be wrong
```JavaScript
router.post('/login', function(req, res, next) {
  getAccount(req, res, next).spread(processAccount).spread(loginSuccessful, loginFailed);
});
```

**Comment by petkaantonov** [comment]
Rejection reasons should always be errors (`instanceof Error`)

**Comment by ChezCrawford** [comment]
I was confused by this as well.  The 2.x documentation for `.spread` states:

> Like calling .then, but the fulfillment value or rejection reason must be an array, which is flattened to the formal parameters of the handlers.

The `s` on `handlers` led me to believe that this was true for both the fulfilled and rejected handlers.  @petkaantonov: I can put in a PR with additional clarity in the documentation if you tell me which branch(es) to submit against...

**Comment by petkaantonov** [comment]
Yes the documentation is wrong (in 2.x branch), errors should always be errors
