### ISSUE TITLE
Promise.resolve(*weird promise thing*) crashes the Chrome tab

### ISSUE THREAD

**Issue by SimenB** [petkaantonov/bluebird#728]
The root problem is probably not an issue here, but the handling of it seems wrong.

I use Backbone.LayoutManager which returns a form of jQuery promises from its `render`-function. If I pass that promise into `Promise.resolve`, the whole chrome tab crashes. Any idea what's going on?

JSBin: https://jsbin.com/xaxeta/6/edit?js,console,output
Just remove the comment around `prom`, and the entire tab crashes in Chrome.

Again, this should probably be fixed in LM (and I've created an issue there as well), but no matter what input is given to `Promise.resolve()`, it shouldn't completely crash the Chrome tab, should it?

Issue in other repo: tbranyen/backbone.layoutmanager#483

**Comment by spion** [comment]
The thenable returned resolves to an object which also has a then method, which in turn resolves to an object that has a then method as well, and so on. Since Promises/A+ in its infinite wisdom demands recursive thenable assimilation, this causes Bluebird (and any other Promises/A+ compliant library) to go into an endless loop.

The problem is whichever library it is that produces those endlessly recursive thenables. They're not compatible with Promises/A+ libraries.

**Comment by SimenB** [comment]
Ah, ok. ANything I can do on the consuming end? `delete promise.then().then`?

**Comment by spion** [comment]
To prevent horrible outcomes like this, Bluebird could break Promises/A+ and stop unwrapping after N levels of iteration (after 100 unwrappings would seem to be an obvious bug) or stop unwinding if it detects.

On the consumer end, the only thing you can do is file a bug with the library that acts as a thenable which resolves itself.

**Comment by SimenB** [comment]
Ok, thanks for the quick response! `Promise.pending()` and manually resolving that within works for now. Unnecessarily ugly though...

If you'd be willing to take a quick look: from what I can tell in the source code (https://github.com/tbranyen/backbone.layoutmanager/blob/master/backbone.layoutmanager.js#L54) it's just a `jQuery.Deferred().promise()`, which bluebird handles fine on it's own. Anything obvious popping out?

**Comment by spion** [comment]
The problem is that [the view acts as a thenable which ultimately resolves to itself](https://github.com/tbranyen/backbone.layoutmanager/blob/master/backbone.layoutmanager.js#L265-L268)

**Comment by SimenB** [comment]
Ah. Great, thanks for the awesome help!
