### ISSUE TITLE
Add do-notation

### ISSUE THREAD

**Issue by RedNifre** [petkaantonov/bluebird#730]
For simple cases, a do-notation would be easier than adding ".then" to each line:

```coffeescript
Promise.do -> [
	read(someStuff)
	_.map Stuff.toString
	_.join '\n\n'
	console.log
]
```

You could use this implementation:

```coffeescript
exports.do = (promises) -> Promise.try -> promises().reduce (l,r) -> l.then r
```

Or as JavaScript:

```javascript
exports.do = function(promises) {
  return Promise["try"](function() {
    return promises().reduce(function(l, r) {
      return l.then(r);
    });
  });
};
```

(I did not send this implementation as a pull request because I'm not sure where to put it)

**Comment by bergus** [comment]
I'm having a hard time understanding why you call a parameter that expects a function that evaluates to an array of functions "`promises`" - which usually means an array of promises.

I think what you are actually looking for is function composition, like Ramda offers it with [`composeP`](http://ramdajs.com/0.17/docs/#composeP) and [`pipeP`](http://ramdajs.com/0.17/docs/#pipeP):
```js
R.pipeP(read, _.map(Stuff.toString), _.join('\n\n'), console.log)(someStuff);
```
I don't think we need this in Bluebird.

**Comment by benjamingr** [comment]
```js
Promise.coroutine(function* (){
     yield* [yourTaskList]
});
```

?

**Comment by RedNifre** [comment]
@bergus The reasons why the parameter is a function that returns the list is so that any errors get caught by Promise.try; if the parameter was just a list then the entries in the list would get evaluated too early.

Your ramda code is equivalent to my proposed do-notation. But that's not the point. The point is that of these three options, I find the do-notation easiest to read:

```coffeescript
# regular bluebird
Promise.try ->
  read(someStuff)
  .then _.map Stuff.toString
  .then _.join '\n\n'
  .then console.log

# ramda promise pipe:
R.pipeP(
  read, 
  _.map Stuff.toString,
  _.join '\n\n',
  console.log
)(someStuff);

# do-notation
Promise.do -> [
    read(someStuff)
    _.map Stuff.toString
    _.join '\n\n'
    console.log
]
```

The bluebird version has ".then" at the beginning of each line and the ramda version has a comma at the end of each line except for the last one and it has the thing to read at the end (which is often useful, but sometimes it's easier to start with a promise instead of a function that returns a promise).

I'm not asking for a new feature here, I'm just asking for syntactic sugar.

**Comment by benjamingr** [comment]
Why not use coroutines?

**Comment by RedNifre** [comment]
I'm not sure I understand your argument. Are you saying one of these two?:
1. "We won't include any syntactic sugar for functionality that is already built-in or can be achieved by using other libraries"
2. "We will include syntactic sugar but this 'do' syntax is not good enough."
Which one is it? Or are you arguing for something else?

If you are saying (1) then I would disagree since bluebird itself is syntactic sugar for node's callback apis, so adding a bit more syntactic sugar to it would make it better.
If you are saying (2) then there is nothing more to discuss since I can't improve the syntax any more and I would have to accept your decision against it, since "better" is subjective in this case.

**Comment by bergus** [comment]
More like 1. We're trying to prevent API bloat here, and tend not to include syntactic sugar that only marginally improves established methods, and can trivially be shimmed; or that is not very very common and allows better lower-level optimisations.

You are encouraged to use this method yourself, but we don't think it's super useful to everybody who uses Bluebird.

**Comment by RedNifre** [comment]
Fair enough, in that case I have no further arguments and accept that it won't get included. I think the issue can be closed.

Thank you both for taking the time to discuss it!

P.S.:
If anyone besides me would actually use it: You can find it here now: https://www.npmjs.com/package/fstuff
