### ISSUE TITLE
Race with filter

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [petkaantonov/bluebird#731]
I just ran into an interesting use case. 

I wanted to race a few promises using `Promise.any()`. However I also wanted to filter the promises on a specific fulfilment value.

Without racing it could look like this:

```javascript
const promises = [stuff('foo'), stuff('bar'), stuff('foo')];

return Promise.all(promises).then(function(values) {
    for (const value of values) {
        if (value === 'foo') {
            return value;
        }
    }
    return 'no soup for you';
});
```

Racing would have given me an answer quicker. Something like:

```javascript
const promises = [stuff('foo'), stuff('bar'), stuff('foo')];
const filterFn = function(value) {
    return value === 'foo';
};

// A couple of ideas for the API:

// Introduce a new variant of some():
return Promise.filterSome(promises, 2, filterFn); 
// (resulting array is of length 0, 1 or 2)

// Augment the existing some():
return Promise.some(promises, { count: 1, filter: filterFn });

// Introduce a new variant of any():
return Promise.filterAny(promises, 'no soup for you', filterFn);
// (result is 'foo' or 'no soup for you')
```

**Comment by spion** [comment]
```js
Promise.any(promises.map(p => p.then(val => { 
  if (condition(val)) return val 
  else throw ...  
})))
```

**Comment by Joris-van-der-Wel** [comment]
> 
```javascript
Promise.any(promises.map(p => p.then(val => { 
  if (condition(val)) return val 
  else throw ...  
})))
```

Less results than the `count` is a valid condition in my use case.

```javascript
const mismatch = Symbol();
Promise.any(promises.map(p => p.then(val => { 
  if (condition(val)) return val 
  else throw mismatch
})))
.catch(Promise.AggregateError, errors => {
    errors = errors.filter(e => e !== mismatch)
    if (errors.length) throw errors
    return 'no soup for you' // none of the promises had a "valid" result
}
```

**Comment by petkaantonov** [comment]
Some things to help figure out how useful addition this would be to core:

1. Do you use this often in your projects? Or just a lot in one project? Or just once in many projects?

2. Are there any other people that would be interested in this?

3. Can it be used as a generic build block that you can build on top of instead of being a specialized tool for some specific scenarios?

**Comment by benjamingr** [comment]
Ping @Joris-van-der-Wel

**Comment by Joris-van-der-Wel** [comment]
Whoops

1. I switched jobs so I am currently not using node.js. But I was just using it in one project (although in a module that could be reused for many projects)

I suggested this because while the concept is easy to understand, implementing it can be tricky. My use case is that I wanted an (inclusive) OR on multiple asynchronous return values.

One instance of this use case is that I wanted to check if a user has access to a specific entity; This access could be granted because of multiple reasons. For example: `user.isSuperDuperUser() || entity.isCreatedBy(user) || entity.isCreatedBy(request.impersonatedUser())`.

2. Not sure, but I can certainly imagine such people :p

3. I think that this makes the existing race feature more generic. Instead of only being able to "race" for _any_ value, you can "race" for a _specific_ value or condition

**Comment by stelios313** [comment]
Can confirm that i run into this specific scenario, and looking for a way to run an array of promises that guarantee a fulfillment count along with a conditional on their values. 

Something like: 5 available slots, 10 clients, some clients can fulfill the promise but with an empty value. I 'd like to ping as less as possible in a way that would fully cover my available slots

**Comment by benjamingr** [comment]
Just chain the promises to reject if they don't fulfill the condition, we don't need another helper just for this.

Before:
```
Promise.any(promises)
```
After:
```
Promise.any(promises.map(x => x.then(predicate)))
```

With proposed syntax:

```
Promise.any(promises, predicate)
```

The use case isn't common _enough_ for new syntax IMO.

**Comment by Joris-van-der-Wel** [comment]
That example is not complete, you will have to catch the AggregateError:

```
Promise.any(promises.map(x => x.then(val => predicate(val) ? true : Promise.reject()))).catch(AggregateError, err => false)
```

**Comment by benjamingr** [comment]
I think enough time has passed and we need to decide if this is worthy of a new syntax or it should be a separate library. 

I vote that this belongs separate library - this is useful for that particular case, but the case isn't _that_ common - and no optimizations need to be performed by core to it. @spion @petkaantonov ?
