### ISSUE TITLE
Array version of Bluebird.using

### ISSUE THREAD

**Issue by kjvalencik** [petkaantonov/bluebird#733]
Sometimes it can be useful to use the `using` / `disposer` pattern with an unknown number of resources. It is possible to accomplish this with:

```js
Promise.using.apply(null, resources.concat(function handler(a, b, c, ...) {
}))
```

But, it would be nice if `Promise.using` also accepted an array. E.g.,

```js
Promise.using(resources, function handler() {});
```

My specific use case is in a CI framework that spins up a number of dependent docker containers. The disposer method will remove the containers after the handling function has resolved.

**Comment by spion** [comment]
I assume that the array of resources will be passed to the handler as a single argument?

+1

**Comment by kjvalencik** [comment]
I think that makes the most sense.

**Comment by benjamingr** [comment]
Hmm, the part that bothers me here is the fact that no other language/system with resource management provides this - there is something a little mutually exclusive between deterministic disposing of resources and a dynamic amount - I've never run into it in C# nor Python nor Java nor other languages I've used with resource management of that sort.

The container use case does sound like a very solid one - so I'm in favour of some sugar, fwiw in ES2015 it's:

```js
Promise.using(...resources, (...handlers) => {

});
```
