### ISSUE TITLE
Promise.for

### ISSUE THREAD

**Issue by za-creature** [petkaantonov/bluebird#734]
I'd propose implementing a `Promise.for` method with the following prototype:

`Promise.for(int start, int end, [int step], callback iterate_fn, [Object options])`

That should behave identically with `Promise.map`, but iterate over a range of items. Since javascript does not currently have a `range` function, the current workaround is to use `Promise.each` with either a third party lib (like `_.range`) or a custom `range` implementation. Both cases are unnecessarily memory-intensive for large ranges, and sometimes you can't count on generators (or the iteration protocol) being available.

I can do a PR if the maintainer(s) like the proposal. Just let me know.

-

Why not `Promise.for(start_fn, end_fn, step_fn, iterate_fn)`?

Imo, that's a turing tarpit.

What about `Promise.while(condition_fn, exec_fn)`?

Consistency is nice, and this might be useful when composing promises, but I can't find an actual use case for it so unless someone comes with a useful proposal for this, I'd steer clear of it for now.

**Comment by benjamingr** [comment]
What advantage do we get from putting this into core bluebird rather than a separate package?

I see the use case, but why wouldn't this be something I `npm install` separately?

**Comment by za-creature** [comment]
I agree, this wouldn't bring a whole lot of utility, just solve a little nuisance I sometimes run into while dealing with promises. However, couldn't you make that argument about everything bluebird has on top of Promises/A?

**Comment by benjamingr** [comment]
@za-creature well, everything that is in core is typically in core because it would be impossible to implement in userland on top of bluebird without internal APIs (or it is immensely useful like `.catch`). 

We'll wait for Petka but I doubt this will make the cut. A userland package could solve this in the typical case, heck, I'd probably even use it myself.

**Comment by spion** [comment]
AFAIK 3.0 adds support for iterables, which should be sufficient (and much more flexible than just ranges)

**Comment by za-creature** [comment]
@spion good point about the array of promises, I didn't think of that.

What if I change the proposal to behave like a bastardized version of `Promise.each`, i.e. it will propagate errors but on success will only return `null`? I realize it's a bit of a stretch at this point, but it might still be useful, especially if targeting es5 and below (not really much of an issue server-side)

I like where you're going with promise-streams (side note: for an environment that insists its async, I find node's builtin streams rather underwhelming) but that's really a general purpose solution that does not necessarily supersede this proposal. I stand by my original point that if all these helpers are removed from bluebird, there's not much point in using bluebird instead of spec-compliant promises (with polyfills as needed).

At this point I've heard some good arguments against this, and have half a mind to close the issue myself. I won't because I still think there's some usefulness to it (albeit marginal) and will leave it up to the maintainer to decide.

**Comment by spion** [comment]
@za-creature I'm not saying that all addon methods are a mistake - just the ones that can operate on arrays of non-promises. There is still plenty of value of bluebird over native implementations

1. its still much faster, probably by an order of magnitude at the moment (!)
2. provides resource management facilities
3. long stack traces that span across promises
4. flexible coroutines with custom handlers
5. convenience helpers

I wouldn't necessarily be against bluebird bundling decent streams too (although the bloat would be incredible at that point ;) I just think that array methods are too crude of a tool (which is what you are saying too) and we need something more flexible (like streams)

**Comment by benjamingr** [comment]
I think iterables solve this in 3.0, we can probably close.

**Comment by petkaantonov** [comment]
There are some duplicates for a loop method like this

https://github.com/petkaantonov/bluebird/issues/207
https://github.com/petkaantonov/bluebird/issues/553
