### ISSUE TITLE
Create custom coroutine

### ISSUE THREAD

**Issue by gyson** [petkaantonov/bluebird#735]
`Promise.coroutine` and `Promise.coroutine.addYieldHandler` are really powerful. But in some use case, I want to create custom coroutine without polluting `Promise.coroutine`. For example, babeljs could transfer async function to `Bluebird.coroutine` and I hope my custom setting would not change the behaviour of `Bluebird.coroutine`.

It would be nice if bluebird can provide the API for creating custom coroutine.

The API and functionality would be something like following:
```js
let coroutine2 = Bluebird.createCoroutineFunction(function yieldHandler(value) {
    if (typeof value === 'number') {
        return Bluebird.delay(value);
    }
});

coroutine2(function* () {
    yield 123; // it's ok to yield number
})();

Bluebird.coroutine(function* () {
    yield 123; // get TypeError
})()
```

**Comment by petkaantonov** [comment]
For some reason it's not documented but each coroutine takes a yield handler that only affects that coroutine:

```js
var coroutine2 = function(fn) {
    return Promise.coroutine(fn, {
        yieldHandler: function(value) {
            if (typeof value === 'number') {
                return Bluebird.delay(value);
            }
        }
    });
};
```

**Comment by gyson** [comment]
That's awesome! Thank you.
