### ISSUE TITLE
Document static/instance collection methods more clearly

### ISSUE THREAD

**Issue by bergus** [petkaantonov/bluebird#736]
From [this SO comment](http://stackoverflow.com/questions/32145828/how-do-i-break-a-bluebird-promise-app-on-a-reject#comment52185049_32146184) by jfriend00, regarding the statement in the docs that "*every instance promise method in the API has a static counterpart*":

> I'm just regularly frustrated with the Bluebird doc. They like to put statements like this some place and then assume that everyone reading any other section of the doc is entirely aware of that statement and its relevance to other sections.

Can we have the signatures of both versions in the docs explicitly, please?
I think this is even more important for the 3.0 docs (http://bluebirdjs.com/docs/api-reference.html) where each method has its own web page, and the important comments in the generic "Collections" section are not visible.

**Comment by benjamingr** [comment]
Go for it.

**Comment by petkaantonov** [comment]
yea pr for 2.0 welcome

**Comment by petkaantonov** [comment]
done for 3.0
