### ISSUE TITLE
Inconsistent propagation of promise.bind()

### ISSUE THREAD

**Issue by fenivana** [petkaantonov/bluebird#738]
```js
Promise.resolve().then(function() {
  return new Promise(function(resolve) {
    resolve();
  }).bind({ a: 1 });
}).then(function() {
  console.log(this);
});
```

Outputs `window`.

However appending a then() makes it work:
```js
Promise.resolve().then(function() {
  return new Promise(function(resolve) {
    resolve();
  }).bind({ a: 1 }).then(function() {});
}).then(function() {
  console.log(this);
});
```

**Comment by bergus** [comment]
Interesting, thanks. However I'd argue that the first is correct behaviour and the propagation of the bound value is the bug. `bind` should only influence linear chains. Consider
```js
Promise.bind(a).then(function() {
    return Promise.bind(b);
}).then(function() {
    console.log(this); // a or b?
})
```
Especially when some of your handlers are returning promises that you didn't create yourself, you'll want it to be `a`.

**Comment by benjamingr** [comment]
@bergus it should be `a`. That makes sense for the arguments you've yourself said.

**Comment by bergus** [comment]
@benjamingr Yes, but the case that "works" for the OP is a bug, isn't it?
```
var dummy = { a: 1 };
Promise.resolve().then(function() {
  return Promise.bind(dummy).then(function() {});
}).then(function() {
  console.assert(this !== dummy, "callback should not be bound");
});
```
Especially that it works when `.then(function() {});` is commented out makes this suspicious.

**Comment by spion** [comment]
Reopening because either the first behaviour is a bug, or the second one is :smile:

**Comment by fenivana** [comment]
@bergus Yes, I agree. But propagating `this` to the upper promise chain is useful. Consider the following:

```js
function wrappedApi(args) {
  var _resolve;
  var promise = new Promise(function(resolve) {
    _resolve = resolve;
  });

  return prerequisite().then(function() {
    return ajax(args).then(function(val) {
      _resolve(this);
      return val;
    }, catch(function(e) {
      _resolve(this);
      throw e;
    }));
  }).bind(promise);
}

wrappedApi.then(function(result) {
  console.log(this.responseText);
});
```

If there is a method to propagate `this` to the upper chain,  then life would be easier.
```js
function wrappedApi(args) {
  return prerequisite().then(function() {
    return ajax(args).propagateContext();
  });
}
```

**Comment by petkaantonov** [comment]
The intention has never been so that unknown code could change `this` for you. In your example it would be less confusing if you did `wrappedApi().then(result => console.log(result.responseText))`

**Comment by fenivana** [comment]
@petkaantonov The result is not the XHR object. How to resolve the promise with `JSON.parse(req.responseText)` and bind `this ` to the XHR object ?@petkaantonov The result is not the XHR object. How to resolve the promise with `JSON.parse(req.responseText)` and bind `this ` to the XHR object ?

**Comment by bergus** [comment]
I don't think you should do that at all. If `prerequisite` fails, there is no `XHR` object to bind to… which does not only lead to your confusing `wrappedApi` code, but also makes its usage complicated.
I'd probably either return `[json, XHR]` tuples and use `spread`, or let the user explicitly write out `prerequisite` and the nested `then` calls (which can handle different errors cleanly).

**Comment by fenivana** [comment]
@bergus If prerequisite fails, you can handle it inside `wrappedApi` or in global `unhandledrejection`. In `wrappedApi().catch()`, you should check the error code, not handle prerequisite errors and re-throw it.

Returning `[result, thisObj]` is weird, and `thisObj` will lost in the following chain... We should hide the complexity in the low level. If every remote API needs to check prerequisite, like oAuth2, you should check access token and expires and refresh the token if necessary, your every API call will become `rpc.auth.check().then(function() { rpc.something.get().then(...) })`, and your users will shit on you.
