### ISSUE TITLE
Cannot promisify an API that has normal methods with 'Async'-suffix

### ISSUE THREAD

**Issue by aral** [petkaantonov/bluebird#740]
I get this error when, for example, I have one module that uses promisifyAll() on fs-extra and requires another module that also does this itself.

**Comment by bergus** [comment]
Are you using two instances of Bluebird?

**Comment by aral** [comment]
I was able to narrow it down further: it’s when you do add an Async method yourself.

Simple case to reproduce:

package.json:

	{
	  "name": "promisify",
	  "version": "1.0.0",
	  "description": "Bluebird PromisifyAll bug",
	  "main": "index.coffee",
	  "scripts": {
	    "test": "echo \"Error: no test specified\" && exit 1"
	  },
	  "dependencies": {
	  	"bluebird": "2.9.34",
	  	"fs-extra": "0.23.1"
	  },
	  "author": "Aral Balkan",
	  "license": "MIT"
	}

index.coffee:

	Promise = require 'bluebird'
	# included = require './included' # No problem here.

	fs = require('fs-extra')
	fs = Promise.promisifyAll fs

	fs.existsAsync = (filePath)->
		return new Promise ((fulfill, reject) ->
			exists = fs.existsSync(filePath)
			process.nextTick(->
				fulfill(exists)
			)
		)

	included = require './included' # Error here: TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix

included.coffee:

	Promise = require 'bluebird'
	fs = require('fs-extra')
	fs = Promise.promisifyAll fs

	# Uncomment and it will always fail
	# fs.existsAsync = (filePath)->
	# 	return new Promise ((fulfill, reject) ->
	# 		exists = fs.existsSync(filePath)
	# 		process.nextTick(->
	# 			fulfill(exists)
	# 		)
	# 	)

I’m going to create an ‘fs-extra-as-promised’ file and use that everywhere to workaround the issue. It still seems wrong, however, for what happens in one module to affect another.

**Comment by aral** [comment]
So, basically, just moving the promisification to a separate module works around these issues. Something as simple as:

fs-extra-as-promised:

	Promise = require 'bluebird'
	fs = Promise.promisifyAll require 'fs-extra'

	# Cannot automatically promisify exists()
	fs.existsAsync = (filePath) ->
		return new Promise ((fulfill, reject) ->
			exists = fs.existsSync(filePath)
			process.nextTick(->
				fulfill(exists)
			)
		)

	module.exports = fs

**Comment by petkaantonov** [comment]
Without the error, promisify would have overridden your `existsAsync` with the broken `existsAsync` based on automatic promisification of `exists`
