### ISSUE TITLE
Inner promise chain not being cancelled

### ISSUE THREAD

**Issue by halt-hammerzeit** [petkaantonov/bluebird#742]
(The previous issue got mistakenly closed)

As a follow-up of the previous issue:
https://github.com/petkaantonov/bluebird/issues/737

This code will work correctly and the child promise chain will get cancelled:

```javascript
import Promise from 'bluebird'

const action = (message) => new Promise((resolve) =>
{
    setTimeout(() => resolve(console.log(message)), 1 * 1000)
})

const promise = action(1).cancellable()
.then(result => action(2))
.then(result =>
{
   return action('child 1').cancellable()
   .then(result => action('child 2')) // this line is pending now (when the user calls .cancel())
   .then(result => action('child 3'))
})
.then(result => console.log('Should not be here'))
.then(result => action('end'))

// promise.cancel() // will count to 1
setTimeout(() => promise.cancel(), 2.5 * 1000)
```

This code will not work as intended because the child promise chain won't get cancelled:

```javascript
import Promise from 'bluebird'

const action = (message) => new Promise((resolve) =>
{
    setTimeout(() => resolve(console.log(message)), 1 * 1000)
})

const promise = action(1).cancellable()
.then(result => action(2))
.then(result =>
{
   return action('child 1')
   .then(result => action('child 2')) // this line is pending now (when the user calls .cancel())
   .then(result => action('child 3')).cancellable()
})
.then(result => console.log('Should not be here'))
.then(result => action('end'))

// promise.cancel() // will count to 1
setTimeout(() => promise.cancel(), 2.5 * 1000)
```

In the first case, .cancellable() is being called on the first promise.
In the second case, .cancellable() is being called on the promise being returned.

In the second case it is explicitly marked as .cancellable() so the fact the it isn't working in the second case is a bug and i'm reporting it to the author of the library @petkaantonov

**Comment by spion** [comment]
Only child 3 is cancellable. Child 1 and 2 are not. If you wish for child1 to be cancellable, add `.cancellable()` there. 

Note that this wont cause the console.log operation to be aborted, as the timer has already been scheduled.
