### ISSUE TITLE
API to get long stack trace in a promise

### ISSUE THREAD

**Issue by ziahamza** [petkaantonov/bluebird#750]
Hello. I have a question. 

By any chance, is there a helper function in bluebird to get long error stack trace in case an exception occurs in a promise? We have our own custom logger that logs any exceptions on certain promises. We get error object in catch handler, but anyway to also get long helpful stack trace from bluebird from that promise?

**Comment by spion** [comment]
The regular `error.stack` property should work

**Comment by ziahamza** [comment]
Thanks for the quick reply!


Sent by Outlook for Android





On Thu, Aug 27, 2015 at 6:25 AM -0700, "Gorgi Kosev" <notifications@github.com> wrote:












Closed #750.
