### ISSUE TITLE
Unhandled rejection with .join

### ISSUE THREAD

**Issue by bsiddiqui** [petkaantonov/bluebird#751]
I'm having an issue where a rejection isn't bubbling up (possibly related to #721)

this gets unhandled rejection:
```js
return Promise.join(
  rejectedPromise(), // this promise throws a rejection
  validPromise()
)
.then(reply, reply)
```
this handles unhandled rejection as expected:
```js
return rejectedPromise()
.return(validPromise())
.then(reply, reply)
```

**Comment by benjamingr** [comment]
This is not the correct way to use `join`, `Promise.join` takes a handler function as the last argument, you're passing it only promises.

You probably want `.all`

**Comment by spion** [comment]
Unable to reproduce:

13728 % npm install bluebird@latest
`bluebird@2.9.34 node_modules/bluebird`

13729 % node join-bug.js
`Should be error: [Error: hi]`

13730 % cat join-bug.js
```js
var Promise = require('bluebird')

return Promise.join(
  Promise.reject(new Error("hi")), // this promise throws a rejection
  Promise.resolve()
)
.then(reply, reply)

function reply(a) {
  console.log("Should be error:", a);
}
```

**Comment by bsiddiqui** [comment]
@benjamingr thanks for clarifying that - I misread the documentation and thought that `.join` was like `.all` for a fixed amount of promises but realize the last arg was a handler function

**Comment by bsiddiqui** [comment]
@benjamingr I just re-tested and `.join` is functioning the same as `.all` for me

When I don't add a function handler as the last argument, it returns an array - is that expected/reliable behavior?

**Comment by spion** [comment]
@bsiddiqui yes it is; can you create a minimal example to reproduce the issue? I tried with the above code and was not able to

**Comment by bsiddiqui** [comment]
@spion you're right, not able to reproduce the original issue - I had mistakenly not required Bluebird and was using native Promise. Thanks for the help
