### ISSUE TITLE
express next function doesn't work

### ISSUE THREAD

**Issue by iceNuts** [petkaantonov/bluebird#752]
I use expresses 4.x and have some function like below:

```
var Promise = require('bluebird')
function wrap (genFn) { // 1
    var cr = Promise.coroutine(genFn) // 2
    return function (req, res, next) { // 3
        cr(req, res, next).catch(next) // 4
    }
}

app.param('itemId', util.wrap(function * (req, res, next, id) {
  var item = yield Item.load(options);
  next();
});
```

When I test, the `next` method looks blocking and doesn't work, is there something I miss?

Thanks.

**Comment by benjamingr** [comment]
Please ask support questions in the appropriate channels.

Check out nodeify, the function signature is wrong in your case.

**Comment by iceNuts** [comment]
@benjamingr  Sorry, but looks like you misunderstand my question.
