### ISSUE TITLE
Minor documentation glitch

### ISSUE THREAD

**Issue by StarsoftAnalysis** [petkaantonov/bluebird#753]
In the first example of using map (https://github.com/petkaantonov/bluebird/blob/master/API.md#mapfunction-mapper--object-options---promise), the code fails if a file in the directory is read-only, despite the `.catch()` clause on `readFileAsync`.

I fixed it with `contents: contents || {}`, although that might not be the promisey way.

**Comment by petkaantonov** [comment]
I don't think the catch should even be there
