### ISSUE TITLE
Please include support for a way to .tap only errors

### ISSUE THREAD

**Issue by ddumontatibm** [petkaantonov/bluebird#755]
I would love to have cleanup functions that would not require me to rethrow the error.
```
promise.tapcatch(function(error) {
   // clean up some stuff in scope
});
```
 instead of 
```
promise.catch(function(error) {
   // clean up some stuff in scope
   throw error;
});
```

low priority... would be nice to have.

**Comment by phpnode** [comment]
dupe of #589

**Comment by ddumontatibm** [comment]
Which is a dupe of #517... so I guess this isn't going in, huh?

**Comment by benjamingr** [comment]
As others have pointed out, this is a dupe.
