### ISSUE TITLE
How can I continue to a next then?

### ISSUE THREAD

**Issue by McFarts** [petkaantonov/bluebird#756]
For example:

```

var input = 'Newman';

 
 

Promise.fromNode(function(value) {
			if(input == 'Newman'){
				continue
			} // I need to continue this block and go to the next .then, how?
}).then(function(result) {
    console.log('We checked and that is a valid username! '+result);
})
```

I need to get to the next .then method pro grammatically. Not sure how to activate it upon success :)

**Comment by tflanagan** [comment]
Please use the correct channels for support questions. 

http://stackoverflow.com/questions/tagged/bluebird

--

You are using ```Promise.fromNode()``` wrong. 

https://github.com/petkaantonov/bluebird/blob/master/API.md#promisefromnodefunction-resolver---promise

As you can see, the function you are creating inside fromNode() is passed a callback. 

```javascript
Promise.fromNode(function(callback) {
  // Do Stuff
  var err = null;
  var results = {};

  callback(err, results);
}).then(function(results) {
  console.log(results);
}).catch(function(err){
  console.error(err);
})
```
