### ISSUE TITLE
None of the links for CDN hosted builds seem to work

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/bluebird#757]
E.g. https://cdn.jsdelivr.net/bluebird/latest/bluebird.core.min.js -> `File not found`

**Comment by jimaek** [comment]
It looks like jsDelivr never hosted this file.
http://www.jsdelivr.com/#!bluebird

**Comment by petkaantonov** [comment]
the github release does come with those files so it's a bug with jsdelivr?

**Comment by jimaek** [comment]
Its not a bug. If you need these files then you need to specify them here https://github.com/jsdelivr/jsdelivr/blob/master/files/bluebird/update.json for the bot to pick them up.

**Comment by petkaantonov** [comment]
oh I recalled that I had specified a wildcard for the browser folder.. so a PR is needed there

**Comment by mikeyhew** [comment]
It's been just over 3 months since this was posted, and the links for bluebird.core are still missing from jsdelivr. Just thought I'd bring it up again in case it was forgotten.

**Comment by benjamingr** [comment]
Wait no, that's not it.

**Comment by petkaantonov** [comment]
This is fixed for 3.0.
