### ISSUE TITLE
bluebird promisify not working with node-bcrypt compare (does with hash)

### ISSUE THREAD

**Issue by rkoberg** [petkaantonov/bluebird#760]
I am trying to rewrite some callback hell auth to use promises (which I am relatively new to).
```
import bcrypt, {hash as bcryptHash, compare as bcryptCompare}  from 'bcrypt';
Promise.promisify(bcryptHash);
Promise.promisify(bcryptCompare);
...
  hash(unhashed) {
    const genSaltRounds = 10;
    return bcryptHash(unhashed, genSaltRounds);
  }

  verifyHash(unhashed, hashed) {
    console.log('authServiceUtil bcrypt.compareSync', bcrypt.compareSync(unhashed, hashed));
    return bcryptCompare(unhashed, hashed);
  }
```
Calling the hash function above works as expected, but not verifyHash, which is always returning undefined. The console.log with the compareSync does work (and prints true in this case).
Any ideas why this does not work?

**Comment by phpnode** [comment]
@rkoberg `.promisify` returns a new function, but you're throwing the result of the call away.

**Comment by rkoberg** [comment]
Oh geez, sorry. I had been using promisifyAll and thought they worked the same. (read the api docs about promisifyAll, but not promisify)
