### ISSUE TITLE
Timeout error custom error object?

### ISSUE THREAD

**Issue by leshy** [petkaantonov/bluebird#762]
Hi, I'd like to provide some extra data apart from a string when my promise timeouts,

for example, I might subclass TimeoutError to ConnectionTimeoutError that also has an attribute containing a specific xhr request for futher inspection/custom error messaging

is this something that hasn't been anticipated or am I missing something?

wouldn't it be way nicer if .timeout checked if it received an instance of an Error object and instantiate TimeoutError only if it didn't? (other types apart from String or Error instances can be handled in a few different ways depending on how strict you'd like to be)

Thanks!

**Comment by benjamingr** [comment]
That sounds like a pretty good idea to me. (Allowing `Error` instances)

I've made a PR at https://github.com/petkaantonov/bluebird/pull/763 we'll wait for Petka to see if he likes the idea and for the tests to run. If he does we'll add a test for it.

**Comment by leshy** [comment]
awesome! thanks

**Comment by benjamingr** [comment]
@petkaantonov?

**Comment by petkaantonov** [comment]
i think its already in?

**Comment by benjamingr** [comment]
You forgot to merge https://github.com/petkaantonov/bluebird/pull/763

**Comment by petkaantonov** [comment]
2.10.2
