### ISSUE TITLE
Doc page "What About Generators?"

### ISSUE THREAD

**Issue by rkoberg** [petkaantonov/bluebird#765]
http://bluebirdjs.com/docs/what-about-generators.html

Not sure if there is an error on that page or perhaps someone has maliciously edited it. There is the statement: 
"You might suppose that this is enough to solve all the asynchronous problems, as if you were having your cake and eating it too and now you can forget about callbacks and promises. That is just toy example fallacy at work."

Was this a malicious edit? Does this apply to generators inside a bluebird coroutine?

Can that be expanded upon? In a simple timer test, a promises (then, spread, catch) based chain apparently runs *slightly* faster than the equivalent using bluebird's coroutine. Using the generator and yields is obviously clearer code, see below. (and I am new to this, so perhaps I could be doing things more efficiently)

Why is the generator (actually two, I **need** to use a callback for the req.login) version "bad"?
```
login: (routeOptions) => Promise.coroutine(function* _login(req, res, next) {
  const startTime = new Date();

  //Promise.longStackTraces();
  const loginDetails = authServiceUtil.validateFields(req, loginFieldsConfig);
  const user = yield getUser(loginDetails);

  if (user && (user.active || !user.blocked)) {

    const isVerified = yield authServiceUtil
                        .verifyHash(loginDetails.password, user.hashedPassword);

    if (isVerified) {

      req.logIn(user, Promise.coroutine(function* loginCallback(err) {
        if (err) {

          logger.error('Error in login loginCallback for', req.body.email, err);
          req.flash('errors', err.name + ': ' + err.message);
          next(err);

        } else {
          //yield authService.updateUserOnLogin(req.user);
          authService.updateUserOnLogin(req.user);
          console.log('login final then time: ', (((new Date()) - startTime) / 1000));
          next();
        }
      }));

    } else {
      req.flash('errors', 'Not able to log in based on the supplied credentials.');
      next();
    }

  } else {
    handleLogInErrors(req, user);
    next();
  }
}),

loginBAK: (routeOptions) => (req, res, next) => {
  const startTime = new Date();

  //Promise.longStackTraces();
  authServiceUtil
    .validateFields(req, loginFieldsConfig)
    .then(getUser)
    .spread((loginDetails, user) => {
      if (user && (user.active || !user.blocked)) {

        return authServiceUtil.verifyHash(loginDetails.password, user.hashedPassword)
          .then((isVerified) => {
            if (isVerified) {
              return Promise.resolve(req.logIn(user , function loginCallback(err) {
                if (err) {
                  logger.error('Error in login loginCallback for', req.body.email, err);
                  req.flash('errors', err.name + ': ' + err.message);
                  return Promise.reject(err);
                } else {
                  return authService.updateUserOnLogin(req.user);
                }
              }))
            } else {
              req.flash('errors', 'Not able to log in based on the supplied credentials.');
              return Promise.resolve([]);
            }
          })
          .catch((err) => {
            next(err)
          });

      } else {
        return Promise.resolve(handleLogInErrors(req, user));
      }
    })

    .then(() => {
      console.log('login final then time: ', (((new Date()) - startTime) / 1000));
      next()
    })
    .catch((err) => {
      next(err)
    });
},

```

**Comment by benjamingr** [comment]
Well a few things: 

First, the 3.0 docs are WiP, contributions are welcome.

Second, I think what Petka is saying is that people are tempted to forget about concurrency and do this:

```js
coroutine(function*(){
    var r1 = yield api1();
    var r2 = yield api2();
    var r3 = yield api3();
    // code using r1, r2 and r3
});
```
'Forgetting' about the underlying abstraction where they would get faster results if they understood APIs are not just something you `yield` and that promises/callbacks themselves are what coroutines are based on - in the above example, you'd probably want to do:

```js
coroutine(function*(){
    var [r1, r2, r3] = yield Promise.all([api1(), api2(), api3()]);
    // code using them, but they were obtained concurrently here
});
```

So effectively, you still have to be aware of the abstraction going on. **It's definitely not about speed**, specially since generators will actually usually outperform the way people usually write callbacks.

**Comment by rkoberg** [comment]
Thank you. But wouldn't that be the case for promises too? That is, chaining promises when they could/should be using join?

What are the thoughts on not yielding a function that returns a promise? For example,
coroutine(function*(){
    api1();
    api2();
    api3();
    // just needs to kick off the above
    next(); // go on without needing the result of the above
});
The promise eventually resolves. Super fast, other than losing any kind of error handling in a server side response :).

**Comment by benjamingr** [comment]
> Thank you. But wouldn't that be the case for promises too? That is, chaining promises when they could/should be using join?

Right, the point is that just using generators for everything async without understanding how things work is not enough.

> What are the thoughts on not yielding a function that returns a promise? For example,

Yes, that could also work, you probably meant:

```
coroutine(function*(){
    var r1p = api1();
    var r2p = api2();
    var r3p = api3();
    var r1 = yield r1p;
    var r2 = yield r2p;
    var r3 = yield r3p;
    // code using r1, r2 and r3
});
```

Which would also be concurrent, in any case it's not enough to just use generators blindly without understanding how the underlying abstraction works. Anyway, the page is not done :)

**Comment by bergus** [comment]
It would be concurrent, but leave some unhandled rejections hanging around if `r2p` fails before `r1p` fulfills.

**Comment by bergus** [comment]
It would be concurrent, but leave some unhandled rejections hanging around (e.g. if `r2p` fails before `r1p` fulfills). Don't do this either :-)

Btw, I missed the obligatory link to http://stackoverflow.com/q/24193595/1048572

**Comment by rkoberg** [comment]
My thinking in https://github.com/petkaantonov/bluebird/issues/765#issuecomment-140082331 was that the promises get kicked off and the code continues on without worrying about errors. Perhaps the client does not need any data returned from the promises and they don't rely on each other. Perhaps if an error occurred, it gets handled by alerting the dev team or sending it through a socket after the initial response returned. Just a thought
