### ISSUE TITLE
Expose subError to make it easy to create new Error types

### ISSUE THREAD

**Issue by kevinsimper** [petkaantonov/bluebird#766]
I am new to Promises, and I often use Promise.OperationalError, so I can catch that type easier, instead of in the catch function.

I searched with google, but have not found any information where they use a flow with multiple error types, but often in my promise chains, there can happen errors, that are non-recoverable, but needs different answers.

For example a http route in express, could have three response, 500, 404, or 401 unauthorize.

Would it be a idea to expose `subError` to make it possible to create new error types and then be able to use it later `.error(NotFound, func)`?

**Comment by benjamingr** [comment]
Bluebird 3.0 allows object property matching against errors and Petka created https://github.com/petkaantonov/core-error-predicates

Subclassing errors isn't hard as it is

**Comment by petkaantonov** [comment]
There's also npm module for creating sub errors e.g. https://github.com/dasilvacontin/subclass-error
