### ISSUE TITLE
Editing wiki without PR?

### ISSUE THREAD

**Issue by erykpiast** [petkaantonov/bluebird#770]
Should it be possible here? I've just want to ask a question (by PR, you cannot comment wiki pages, so I thought it's the easiest way) and I've added some comment to code, clicked "Save" button and... that's it, new version was published. Everybody can do it. Should it be like that? Just asking.

**Comment by spion** [comment]
Probably not, but until the [3.0 docs are out](http://bluebirdjs.com/docs/api-reference.html) we don't really have a better solution.

**Comment by benjamingr** [comment]
No, the documentation is mostly in the API.md file, later in 3.0 it'll be on bluebirdjs.com, so far the wiki hasn't been abused so there was no need to restrict it.
