### ISSUE TITLE
Possible to add .then after loops?

### ISSUE THREAD

**Issue by McFarts** [petkaantonov/bluebird#771]
for example:
```
redis.get('GAMECOUNT').then(function(obj){
				var total_games = obj;
				var GAMES = {};
				for(var i = 0; i < total_games; i++){
					
					redis.hgetall('GAMES:'+i).then(function (obj) {
						GAMES[i] = obj;
					}); 
				}
				
				console.log(GAMES);
				
}).then(function(){
			console.log(GAMES);
	
}).catch(function(e){
	 gamelog(e, user)
});
```

I'm grabbing data from redis, and both console logs do **NOT** get filled because redis is async.

But, if I were to add a `.then` after the `for` loop, I could grab the data. 

Any idea?

**Comment by spion** [comment]
Promises are values. You can push them in an array. Then you can await the all.

```js
redis.get('GAMECOUNT').then(total_games => {
  var GAMES = [];
  for (...) {
    games.push(redis.hgetAll('GAMES:'+i))
  }
  return Promise.all(GAMES)
}).then(GAMES => console.log(GAMES))
```

**Comment by McFarts** [comment]
Wow, okay.  Didn't know you could put them on a new line as well, oh boy does that make the code looks so much clearn,t hank you!
