### ISSUE TITLE
Home page broken

### ISSUE THREAD

**Issue by mpermar** [petkaantonov/bluebird#774]
Just a note letting you know that the home page http://bluebirdjs.com/ returns a big 404.

Cheers!

**Comment by benjamingr** [comment]
Yes, that's intentional, we don't actually want people to get there until 3.0, it contains the 3.0 docs which are irrelevant to the current version. When 3.0 is released it'll be released too.

**Comment by benjamingr** [comment]
Thanks for the heads up though!

**Comment by mpermar** [comment]
Oh I see. Fair enough! I would suggest to redirect that page to this github project though. There is no link so I ended up having to google search for finding my way here.
