### ISSUE TITLE
Connections are available, but new connect operation hangs

### ISSUE THREAD

**Issue by nmandyam** [petkaantonov/bluebird#776]
When my app has been running for 12 hours or more, it seems to "leak" connections. pgAdmin tells me  there are 15 connections open (I set the pool-size to 10), but new requests hang on the connect operation even though there's nothing else using the connections. This may be due to my not closing a connection in some situations, so I'm trying figure out where. I am also trying to figure out ways where I can be notified when, say, 13 connections have already been used, so I can figure out why (this is not an app that's being used very heavily - yet). Hence these questions:
-  Is there a way to get the current number of open connections? I could set some kind of event send me an email, if so, when it hits a specific number.
-  Is there a way to know which of those connections are being used? Maybe even a timestamp when ti was last used? I could figure out which ones are not being used, do some recovery stuff.
-  Are there better ways of trying to figure out WHERE connections are "leaking" other than logging exits? I ask because node-inspector won't help - my troubles occur only every few hours.

Thanks for all the help!

**Comment by spion** [comment]
Are you sure this is the right place to post this issue, not https://github.com/brianc/node-postgres ?

Or are you refering to the [resource management APIs of bluebird?](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiseusingpromisedisposer-promise-promisedisposer-promise--function-handler---promise)

**Comment by nmandyam** [comment]
Dumb of me to have not checked the API - that will help, thanks!
I did worry about whether this should be on the node-postgres issue list, but I finally (and I see now, correctly!) posted here.
