### ISSUE TITLE
Promise.join: Possibly unhandled Error

### ISSUE THREAD

**Issue by MichielDeMey** [petkaantonov/bluebird#781]
The `.join` method seems to trigger a `Possibly unhandled Error`.

I'm using it in the following way:
```js
Promise.join(
    promise1(),
    promise2(),

    function() {
      // Do some mapping in the callback function
      return {
        prop1: arguments[0],
        prop2: arguments[1]
      };
    }
)
.then(res.json.bind(res))
.catch(function(error) {
    return res.status(500).end(error.toString());
});
```

Inside one of these promises I throw an Error
```js
throw new Error('My error message');
```

This will result in
```js
Possibly unhandled Error: My error message
```

Even though I have a `catch` function defined at the end.
I'm assuming this is a bug?

**Comment by benjamingr** [comment]
What's `res.join.bind(res)`?

**Comment by MichielDeMey** [comment]
Oh, sorry. That's part of the [Express](https://github.com/strongloop/express) framework.
It's a shortcut for

```js
.then(function(data) {
  res.json(data);
})
```

The shortcut shouldn't be an issue, I also tested the above snippet to make sure the bindings are still correct.

**Comment by petkaantonov** [comment]
can you make a stand alone repro?

**Comment by benjamingr** [comment]
@MichielDeMey sorry for bugging you, any chance to get a repro?

**Comment by MichielDeMey** [comment]
Hey guys

Sorry for the slow response.
I've been doing some debugging and I've found the culprit.

Somewhere in `promise1()` I had another promise on which I used a `.then()` without a `catch()`.
So it looks like I needed to add a `catch()` throughout the entire stack of promises instead of at the end.

This is most likely intended behaviour?
Is there currently a way to pass caught errors into another promise?

Maybe I should switch to using `Promise.map()`?

Addendum:
```
promise1: function() {
  return new somePromise().then(function(data) {
    // Some mapping going on here
    return data;
  });
}
```

All I needed was to add a `catch()` after the `.then()`.

**Comment by benjamingr** [comment]
> So it looks like I needed to add a catch() throughout the entire stack of promises instead of at the end.

Yes, this was intended behavior. Bluebird had your back here :)

**Comment by bergus** [comment]
> Somewhere in `promise1()` I had another promise on which I used a `.then()` without a `catch()`.

This sounds like the [`Promise` constructor antipattern](http://stackoverflow.com/q/23803743/1048572)?
You should not need to add `.catch()` everywhere, you just need to compose promises appropriately (using lib functions) so that rejections get automatically propagated.

**Comment by MichielDeMey** [comment]
I an using lib functions and returning actual promises, rather than creating new deferred objects and manually resolving/rejecting them (see addendum).

The thing is that I need to do some mapping after the data is returned by the lib functions, so I decided to do this in the `then()` function. I'll see if it's better to use a `map()` function for this purpose.
