### ISSUE TITLE
Possibilty to accept Generator function instead of static Arrays

### ISSUE THREAD

**Issue by vanthome** [petkaantonov/bluebird#782]
es6-promise-pool [1] is similar to Bluebird's  `map()` function but it is much more
powerful in that the array must not be static.
If can be a generator function which may theoretically spit out an infinite number of promises.
As far as I can see, this cannot be realized with Bluebird currently or am I overlooking something.

[1] https://github.com/timdp/es6-promise-pool#generator

**Comment by benjamingr** [comment]
Accepting ES2015 iterables is in Bluebird 3.0

Thanks for the suggestion.
