### ISSUE TITLE
Catching errors based on Error.name

### ISSUE THREAD

**Issue by perrin4869** [petkaantonov/bluebird#785]
I was thinking that in many cases, it might be more convenient to use a String to catch errors rather than constructors, and the reason is that when it comes to modules, you actually need to export modules, making it much more cumbersome to type. Compare the following:

```javascript
Promise.resolve(foo)
.then(() => { ... })
.catch(MyModule.errors.MyFirstError, err => { ... })
.catch(MyModule.errors.MySecondError, err => { ... })
...
```

vs:

```javascript
Promise.resolve(foo)
.then(() => { ... })
.catch("MyFirstError", err => { ... })
.catch("MySecondError", err => { ... })
...
```

Where in the first catch `err.name === "MyFirstError"` and in the second catch `err.name === "MySecondError"`.

**Comment by benjamingr** [comment]
Bluebird 3.0 supports something similar. Assuming you don't want to alias and import the errors directly anyway:

      promise.catch({name: "MyFirstError"}, err => { ... }); // valid Bluebird 3

Thanks for the suggestion. https://github.com/petkaantonov/bluebird/issues/499

**Comment by perrin4869** [comment]
I see, that's very useful! Still, different modules might expose error constructors differently or not at all, and then using the whole `{name: "MyFirstError"}` syntax would be rather verbose when you could just use `"MyFirstError"` as a string, would it not? It would only be a matter of converting `"MyFirstError" -> {name: "MyFirstError"}` internally when passed a string parameter, would it not?

**Comment by benjamingr** [comment]
```js
let {MyFirstError, MySecondError} = MyModule.errors;

Promise.resolve(foo)
.then(() => { ... })
.catch(MyFirstError, err => { ... })
.catch(MySecondError, err => { ... })
```

Seems to work just fine. Would it not?

**Comment by perrin4869** [comment]
Interesting, I didn't know that ES6 construct, I actually like it :)
Yeah, that would work in most cases I presume, but you still need to explicitly alias the constuctors each time, maybe in many files with many different modules which expose their error constructors in different manners (maybe across different objects...). I mean, in a language like Java it would really make sense to do all that explicitly, but I'm not sure aliasing the constructors is true to the spirit of Javascript...
The other question would be, what are the objections to being able to pass a string as a parameter to catch?

**Comment by spion** [comment]
@perrin4869 there are many benefits

1. With ES6 imports can be statically checked for correctness / typos. Strings cannot
2. With JSHint error names that refer to variables can be checked for typos. Strings cannot.
3. If you add TypeScript or Flowtype later, errors can be refactored (renamed or moved) and leftover renames and moves can be pointed out by the typechecker. Strings cannot.

**Comment by perrin4869** [comment]
Oh, I never argued to choose one over the other, I just think it would be great if we had all three of them available since it'd be so trivial to do and it would make sense to use it in many cases. I mean, is there any reason to have clients who want to match errors based on their names all implement the predicate function above, `let errName = name => err => err.name === name` and then pass `errName("MyError")`, when you could handle string arguments to behave just that way?

**Comment by spion** [comment]
The first 4 reasons refer to the pitfalls of using strings when refactoring. 

And... I know this feature is just one little thing. Its true, by itself its not a big deal at all - its quite trivial to implement, really. But there've been hundreds of feature requests like this, and they really add up after a while. They contribute to library bloat and API documentation bloat, and sometimes make it harder to reason about all the potential interactions. So they aren't really free.

P.S. If it were really up to me, I would also remove the object matching functionality. Most of the people I recommend Bluebird to don't find the lack of features a problem (save for a few fundamental ones like cancellation). Their objection is more like "oh its too huge, the API is too complex, I need something simpler" - but they normally don't open issues here and look elsewhere instead :(

I guess the two choices to deal with this this are:

1. 
a. start removing some features, and
b. be selective when adding new ones, and
c. look into splitting off more specialised functionality into separate related libraries

2. embrace the bloat

What we're doing now is just 1.b. and that probably doesn't make sense by itself...

**Comment by perrin4869** [comment]
Well no I totally agree with 1a and 1b and each single feature has to be judged on its own merit on a case by case basis, and if my suggestion doesn't cut for you guys then that is that... But you know, the more I learned about bluebird and read the documentation, the more interesting and useful features I kept finding! I'm sure I used most of the features available in bluebird in my current project... and there were times where I was wishing for features like being able to simulate something like `async.series` with promises by passing functions that return promises or something... And I never opened an issue because I felt that it really is not justified to have that in, just as a personal opinion even though it might save me a few lines of reduce code here and there and might slightly increase readability...

So going back to the error matching problem, now that I think about it, if you are giving people the option to use predicate functions then the object matching functionality does seem somewhat redundant after all although it could improve readability in some cases... Still, error names are such a defacto standard in Javascript that I maintain that matching them in catch clauses would not really be a bloat

**Comment by spion** [comment]
@perrin4869  Are you sure its so common for everyone, or is it a particular problem you have with libraries that don't export their errors, or the way you have those libraries arranged in the modules? I've personally had no trouble importing error types (and predicates) and using them, so I find it hard to see any benefit at all. I know its just a difference in perspective...

regarding the rest of my comment it was off topic so I moved it to https://gist.github.com/spion/294bb53db70bd700b0c4 . (Unfortunately the solution I came up with doesn't apply to this issue as its impossible to move such a feature into a separate lib)

**Comment by perrin4869** [comment]
Well, the only problem I have with ES6 exports is that unfortunately, they do not yet work natively in node.js, even the newest 4.1.x versions, so they are not a viable solution yet.

OK, my very last pitch to supporting strings in catch clauses will be that there are times when constructors are just not available at all. For example, take socket.io. If, say, the client gives a callback to their emit to the server, and the server throws and error and wants to hand it to the client, the error gets serialized and sent back as json to the client... This is what I mean:

```js
client.emitAsync('login', credentials)
.catch(err => err.name === 'RetryLoginError', err => { ... })
```

Of course this means that the client can't have a constructor because the error they got is not an instance of `Error`, and it could never be. At that point, the only way to write multiple catch clauses is to use predicate functions, which work perfectly, but are more verbose than I would like.
