### ISSUE TITLE
Mandatory .then()

### ISSUE THREAD

**Issue by adriano-di-giovanni** [petkaantonov/bluebird#786]
What if I invoke an asynchronous function returning a Bluebird promise and omit to invoke `.then()`. Does the asynchronous operation get executed?

I have an asynchronous function like this

```javascript
var promise = saveToMySQL(data);
```

Data gets saved to MySQL only if I invoke `.then()` like this

```javascript
saveToMySQL(data).then(function (response) {});
```

Does it make sense?

**Comment by benjamingr** [comment]
A promise is a proxy to the asynchronous operation's result. If you have a promise then the operation has already started.

Please ask support questions in the appropriate support channels like SO and IRC in the future
