### ISSUE TITLE
Combine map() + each()

### ISSUE THREAD

**Issue by paulxtiseo** [petkaantonov/bluebird#788]
Is there a way, that I have missed, to get the guaranteed sequential processing of each() and the return of a modified array of map()?

**Comment by benjamingr** [comment]
This is how each behaves in 3.0

**Comment by phpnode** [comment]
in 2.0 you can implement `map` using `reduce`.

```js
Bluebird.reduce(promiseArray, (items, item) => {
  items.push(doSomething(item));
  return items;
}, []);
```



> [insert boilerplate scolding for asking questions in an issue rather than on stackoverflow or gitter here]

**Comment by benjamingr** [comment]
@phpnodd feature requests are fine on the issue tracker :)

**Comment by paulxtiseo** [comment]
@phpnode I meant as 95% feature request, 5% self-doubt-maybe-there's-a-trick-I'm-missing. :) Thanks for the alternate method.

**Comment by jagged3dge** [comment]
@phpnode Thank you for providing this workaround :) I've been trying to use this, but I couldn't figure out how to use this if the `doSomething(item)` function call returns a promise? As it is, I'm receiving the resulting `items` array as an array of promises.

I tried the following, that aren't helping:

```js
// 1: Try to resolve the promise while pushing it to the 'items' array
Bluebird.reduce(promiseArray, function (items, item) {
  items.push(doSomething(item).then(function (i) { return i })) // Still results in array of promises
  return items
}, [])

// 2: Try returning the resulting array, then use '.all(array)' to resolve the resulting array of promises
function resolveInSequence = function (promiseArray) {
  return Bluebird.reduce(promiseArray, function (items, item) {
    items.push(doSomething(item))
    return items
  }, [])
}

Promise.all(resolveInSequence(promiseArray))
  .then(function (results) {
    console.log(results) // Displays the array. But the sequence is gone awry again
  }
```

I double-checked the input `promiseArray` and it's providing the correct sequence of numbers to process. However, the processing done by the `doSomething` function seems to takes a little longer in a couple instances, causing the sequence to go awry. Is there any way around this?
