### ISSUE TITLE
Documentation is inconsistent on Promise.all

### ISSUE THREAD

**Issue by tomaskulich** [petkaantonov/bluebird#789]
Documentation is inconsistent in whether promise.all accept iterable of Promises (or only array is allowed). Current version (2.10.1) seems to support only Arrays, which is unnecessarily restricting and contradicts the first documentation cited.

According to 

http://bluebirdjs.com/docs/api/promise.all.html

Promise.all(Iterable<any>|Promise<Iterable<any>> input) -> Promise

whereas according to 

https://github.com/petkaantonov/bluebird/blob/master/API.md

.all() -> Promise

Given an array, or a promise of an array, which contains promises (or a mix of promises and values) return a promise that is fulfilled when all the items in the array are fulfilled. The promise's fulfillment value is an array with fulfillment values at respective positions to the original array. If any promise in the array rejects, the returned promise is rejected with the rejection reason.

**Comment by benjamingr** [comment]
bluebirdjs.com is the 3.0 docs, 3.0 is not released yet. You can check it out and build it and play with it if you'd like.

**Comment by tomaskulich** [comment]
It's great that you changed this behavior in 3.0 version!

However, if this documentation is in build-in-progress / not-yet-released state, shouldn't there be some warning displayed? Or at least the version number could be displayed somewhere (am I just blind?) The page ranks quite high on Google which may cause some confusion among Bluebird users.

**Comment by benjamingr** [comment]
There are no links to the site
