### ISSUE TITLE
each() docs incorrect?

### ISSUE THREAD

**Issue by stevenvachon** [petkaantonov/bluebird#790]
`(item, index, value)` can't be right. `value` should be renamed to `length`.
https://github.com/petkaantonov/bluebird/blob/master/src/reduce.js#L126-L130

With that, should the length even be provided? Maybe have `array` instead like `Array.prototype.forEach`.

**Comment by petkaantonov** [comment]
Yes it's supposed to be length, PR welcome

**Comment by stevenvachon** [comment]
Should `item` be renamed to `value`, then?
```js
(value, index, length)
```
