### ISSUE TITLE
Bind upper context inside Promise then()

### ISSUE THREAD

**Issue by f1nnix** [petkaantonov/bluebird#791]
I'm trying to call super method save() from child instance:

```
module.exports = class ImageKeeper extends FileKeeper {
    constructor(keeperPath, options) {
        super(`/${keeperPath}`, options)
        this.keeperPath = keeperPath;
    }

    save(filePath) {
        return new Promise((resolve, reject) => {
            this
                .resolvePath(filePath)
                .then(fileData => { // <== NOTE THIS
                    var filePath = fileData[0],
                        mime = fileData[1];

                    super.save(filePath, mime);
                })
                .catch(function(err) {
                    reject(err)
                })
        })
    }
}
```

Calling `super.save(filePath, mime);` raises:

```
Unhandled rejection SyntaxError: 'super' keyword unexpected here
```

which means upper context is not bound to `then()`.

**If we use native v4.x Promise, everything works.**

Demo repository: https://github.com/f1nnix/_super-test

SO question: https://stackoverflow.com/questions/32932699/calling-super-method-inside-promise-super-keyword-unexpected-here/32932725

Any help will be highly appreciated.

**Comment by benjamingr** [comment]
@petkaantonov

**Comment by benjamingr** [comment]
This is not a bug, native promises behave the same way. Remove the `require("bluebird")` calls and add a unhandled rejection tracking handler to verify yourself:

```
process.on("unhandledRejection", function(reason, p){
	console.log(reason, p);
});
```

Native promises give me: 

> > $ node test.js
> [SyntaxError: 'super' keyword unexpected here] Promise { <rejected> [SyntaxError: 'super' keyword > unexpected here] }

**Comment by petkaantonov** [comment]
[`super` is only valid inside method definitions.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super), not lambdas or regular functions.

> The super.prop and super[expr] expressions are valid in any method definition in both classes and object literals.

**Comment by PavelPolyakov** [comment]
Hi guys,

Having in mind that `super` could not be called inside the coroutine.
Is there any pretty solution to make it happen?

Currently I went up to this:
```javascript
class A {
    process({ a, b, c }) {
        // in order to be able to call super method inside the coroutine
        const _process = super.process;

        return Promise.coroutine(function *() {

            yield _process.bind(this)({ a, b, c });

            // some actual work

            return true;
        }).bind(this)();
    }
}
```

However, it could be that there are better solutions. Probably not only me have met this issue.

Regards,
