### ISSUE TITLE
Mongoose Map/Reduce simple example

### ISSUE THREAD

**Issue by nottinhill** [petkaantonov/bluebird#793]
I want to fire a request to MongoDB with Mongoose, get hundrets of thousands of data back and then iterate through each, do stuff to it and write back to DB.

```
MyModel.myPromisifiedMethod parameter, (err,res) ->
.then((res) ->
  Promise.map res, ((eachItem) ->
    parameter = eachItem.parameter
    AnotherModel.get parameter, (err,res) ->
      return someObjects
  )
.then((finalResult) ->
  res.status(202).send
    result:finalResult
)
```

So again the most important steps of what I want to do:

- Query the DB and get a torrent of data
- Iterate through the Data (with map?) and perform a another Query to each of data item.
- When finished it would be very nice to only fire ONE single express res.status(202).send

I cant get this to work.

What I tried:

http://stackoverflow.com/questions/32928325/map-join-with-bluebird-and-mongoose/32950809#32950809

**Comment by markthethomas** [comment]
What about using something like `Promise.all()`?

**Comment by nottinhill** [comment]
I switched to async, it worked pretty much instantly with their `.waterfall` method. I also do recommend to take a look at Highland and read on here: http://blog.vullum.io/javascript-flow-callback-hell-vs-async-vs-highland/

**Comment by spion** [comment]
FWIW this should work and accumulate a sum of the many queries' `someField` field

```coffeescript
MyModel.myPromisifiedMethod(parameter).then (items) ->
  Promise.reduce items, (runningTotal, item) -> 
    parameter = item.parameter
    AnotherModel.get(parameter).then (res) -> 
      runningTotal + res.someField
.then (total) ->
  res.status(202).send 
    result: total
```

**Comment by markthethomas** [comment]
@nottinhill Async and Highland definitely give you tons of great tools for control flow w/ callbacks and streams, respectively. And `.waterfall` *is* great, but FWIW I've found that when you start to get into longer algorithms (e.g., in my case one example was processing a payment that required 10s of `callback`s), you can make everything much easier to understand and reason about w/ Promises (not to mention the speed-gains). 

Kyle Simpson (@getify) has a [great book](https://github.com/getify/You-Dont-Know-JS/tree/master/async%20%26%20performance) on async and performance and 
@spion, pertinently, also has a [great overview](https://spion.github.io/posts/why-i-am-switching-to-promises.html) of promises and touches on Promised-based correlates to some popular `async` methods. Worth thinking about, at least. :+1:
