### ISSUE TITLE
Implicit Promise.all behaviour

### ISSUE THREAD

**Issue by palamccc** [petkaantonov/bluebird#794]
Is Implicit Promise.all officially supported, or is it removed recently, the behavior is inconsistent now.
(node 4.1.1, bluebird 2.10.2)

    P.resolve()
      .then( () => [P.resolve(1), P.resolve(2)] )
      .then( (x) => console.log("implicit followed by then >> ", x) )
      .then( () => [P.resolve(1), P.resolve(2)] )
      .spread( (x, y) => console.log("implicit followed by spread >> ", x, y) )
      .then( () => Promise.all([P.resolve(1), P.resolve(2)]) )
      .then( (x) => console.log("Promise.all followed by then >> ", x) )
      .then( () => Promise.all([P.resolve(1), P.resolve(2)]) )
      .spread( (x, y) => console.log("Promise.all followed by spread >> ", x, y) );

   output:

    implicit followed by then >>  [ Promise {
        _bitField: 268435456,
        _fulfillmentHandler0: undefined,
        _rejectionHandler0: undefined,
        _progressHandler0: undefined,
        _promise0: undefined,
        _receiver0: undefined,
        _settledValue: 1 },
      Promise {
        _bitField: 268435456,
        _fulfillmentHandler0: undefined,
        _rejectionHandler0: undefined,
        _progressHandler0: undefined,
        _promise0: undefined,
        _receiver0: undefined,
        _settledValue: 2 } ]
    implicit followed by spread >>  1 2
    Promise.all followed by then >>  [ 1, 2 ]
    Promise.all followed by spread >>  1 2

**Comment by spion** [comment]
Its always been this way, afaik. `spread` implies `all`; `then` doesn't (and is not allowed to per Promises/A+).

**Comment by benjamingr** [comment]
Yes, this is exactly as @spion  said, `spread` has to implicitly `.all` in order to get the array.

**Comment by palamccc** [comment]
Thanks for the reply, Can you please add implict .all behavior to documentation. I could not find it. If its already there, ignore this request. Thanks.
