### ISSUE TITLE
bluebird breaks on node 4.0

### ISSUE THREAD

**Issue by cultofmetatron** [petkaantonov/bluebird#795]
Because of node 4 reserving the Promise keyword. I can't load up bluebird or any library that depends on it.

```
var Promise = require("bluebird");
TypeError: Identifier 'Promise' has already been declared
```

are there any current workarounds? bluebird, knex and bookshelf simply do not work on node 4!

**Comment by ivan** [comment]
Where are you running that?  Why would a `var` prohibit re-declaration?  It works for me:

```
# node --version
v4.1.1
# node 
> var Promise = require('bluebird');
undefined
```

**Comment by cultofmetatron** [comment]
Looks like its only a problem on 4.0. I switched to 4.1 and that resolved the issue or me.
