### ISSUE TITLE
cancel() with force parameter!

### ISSUE THREAD

**Issue by edvinv** [petkaantonov/bluebird#796]
Hi,
I have a project with very complex promise structure that should be in some situation canceled from root promise. The problem is that it is very easy to forget marking a promise as cancellable but very difficult to find such a bug. So IMHO it will be very good to have additional force parameter in cancel method.  Without it or when it is false it will work the same way as it is working now, but if you set it to true it will not only cancel promises that are marked as cancellable but also those that are not marked at all, but stop at promises marked as uncancellable. So you will  now have an option not to mark promises as cancellable, but forcing cancellation with force parameter and only mark those points where you want to stop cancellation. This way there will be considerably less work in cases where all promises chain should be cancelled, because you will only have to call cancel() with true parameter and more importantly you will not have to worry that you forgot to call cancellable few months later when you add some additional promises to the chain.

thanks

**Comment by benjamingr** [comment]
Thanks for the feedback.

Promise cancellation is being overhauled for bluebird 3.0 to behave like the proposed ES standard cancellation and to be simpler and more robust.

see https://github.com/petkaantonov/bluebird/issues/415 , let us know if you have any issues with it.
