### ISSUE TITLE
Catch should catch all types

### ISSUE THREAD

**Issue by abelnation** [petkaantonov/bluebird#798]
There are some cases where it is not possible to subclass the base Error type.  Being able to throw any type and have it be caught by bluebird catch statements would be very helpful.  

Thanks! Love the lib

**Comment by benjamingr** [comment]
`catch` catches all types already.

**Comment by abelnation** [comment]
This test fails for me.  I'm using es6 syntax, and transpiling via Babel:
```
describe('bluebird', () => {
    it('catches errors of any type', (done) => {
        class Foo {}

        bluebird.resolve(true).then(result => {
            throw new Foo()
        }).then(result => {
            done(new Error('should not have made it to the next then'))
        }).catch(Foo, err => {
            done()
        }).catch(err => {
            done(new Error('should not have fallen through to catch all'))
        })

    })
})
```

**Comment by petkaantonov** [comment]
The argument should be an error type, Neither Foo or Bar is an error type. What do you mean it's not possible to subclass erorr?
