### ISSUE TITLE
Cancelling promises

### ISSUE THREAD

**Issue by hpwdetica** [petkaantonov/bluebird#800]
I am using Bluebird 2.9.25 and am trying out the cancellation feature of promises, but they are not behaving as I would expect.

I've tried what I'd consider to be a base case of cancelling a pending Promise:

```javascript
var def = Promise.pending();
var prom = def.promise.cancellable();
var promChained = prom
		.then(function() {
				console.log('then added before cancel');
		})
		.catch(function(e) {
				console.log('catch e: %o', e);
		});

prom.cancel();

promChained.then(function() {
		console.log('then added after cancel');
})
def.resolve();
```

I would expect the above to print: 

```javascript
catch e: CancellationError
```

or something similar, as if a pending promise is cancelled I'd expect the rest of the chain to no longer execute. Instead it prints:

```javascript
then added before cancel
then added after cancel
```

Any pointers on where I'm going wrong would be appreciated!

Cheers

**Comment by mbroadst** [comment]
possible duplicate: https://github.com/petkaantonov/bluebird/issues/537

**Comment by hpwdetica** [comment]
I would expect that behaviour, but here my catch is never hit.

I see in #537 there is a comment:

```
cancellation in 2.x is horribly broken by design and wontfix and cannot be made to work with all bluebird features consistently. Cancellation has been redone for 3.0
```

Do you know the extent of how broken it is?

@petkaatonov If you could shed any light on this it would be appreciated.

**Comment by petkaantonov** [comment]
It's very broken, use 3.x

**Comment by hpwdetica** [comment]
Ok, cheers.
