### ISSUE TITLE
spurious CancellationError

### ISSUE THREAD

**Issue by mbroadst** [petkaantonov/bluebird#801]
I've got a piece of code that looks similar to this:

```
self._waitingForRefresh[something] =
  Promise.delay(self._policy.waitForRefreshTimeout)
    .cancellable()
    .then(function() {
      return self._refreshManually(something);
    })
    .catch(Promise.CancellationError, _.noop);
```

which I then cancel later if a similarly triggered action occurs with the following:

```
  if (_.has(this._waitingForRefresh, otherThing)) {
    this._waitingForRefresh[otherThing].cancel();
    delete this._waitingForRefresh[otherThing];
  }
```

This generally works quick nicely in my integration tests, as well most of the time in production. However, occasionally I will get a `CancellationError` emitted from the `.cancel()` call above, and I'm having trouble tracking down how that's possible. I would have thought that since the original promise noops the CancellationError it wouldn't be otherwise thrown, but that's not the case all the time.

Unfortunately I haven't yet been able to pinpoint a failing test case, but thought I'd document this here first before digging deeper there.

**Comment by mbroadst** [comment]
Anyone know why this might happen? Definitely still happening for me but I can't seem to isolate the behavior - it seems almost random, but definitely throwing the cancellation error at the call site with:

```
CancellationError: cancellation error
```

**Comment by benjamingr** [comment]
Did you try 3.0?

**Comment by mbroadst** [comment]
@benjamingr I haven't yet, considering it came out yesterday I'll need about a week to find time to update and verify - I'll let you know.

**Comment by janpieterz** [comment]
@benjamingr possibly related, if not please excuse me. I used to get a CancellarionError every time I cancelled, but since upgrading to 3.0 I don't get them anymore. It cancels fine, request shows cancelled. Is this expected? I couldn't find anything in the docs, for example on the  3.0 What's New page or the Cancellation page.

Perhaps something was wrong with my previous implementation, but I'd like to be sure before I'm rewriting the code that handled those Errors like that.

**Comment by mbroadst** [comment]
@benjamingr I'm trying with 3.0.5 right now, but I'm having trouble reworking the code. Previously `cancel`ing a promise would still resolve it, so I could return a `Promise.all(promises);` from one method, and if certain promises in that were cancelled it would complete. For example:

```
'use strict';
var Promise = require('bluebird');
Promise.config({ cancellation: true });

function somePromiseMethod() {
  return new Promise(function(resolve, reject) {
    // do long process
    setTimeout(function() { resolve(); }, 1000000);
  });
}

var promises = [];
for (var i = 0; i < 10; ++i) promises.push(somePromiseMethod());
setTimeout(function() {
  promises.forEach(function(promise) { promise.cancel(); });
}, 1000);

return Promise.all(promises)
  .then(function() { console.log('DONE!'); });
```

Now that just hangs until each of the `somePromiseMethod`s eventually resolve. Is there a way to emulate the old behavior?

**Comment by mbroadst** [comment]
Ah, it seems I can use `Promise.reflect()` to get the same type of resolution notification!

**Comment by mbroadst** [comment]
It looks like the behavior I want can be obtained using `Promise.reflect()`, considering the latest version doesn't even spawn CancellationErrors anymore (outside of multiple consumers?) I think it's safe to close this.

**Comment by benjamingr** [comment]
Thanks @mbroadst for the report. 

@janpieterz 2.x cancellation had broken semantics. 3.0 cancellation is more sound. Check out the tutorial on the website if you have any more questions :)

**Comment by mbroadst** [comment]
@benjamingr might be worth mentioning on the Cancellation page that you can achieve the same notification by use of `Promise.reflect` - I think it's a far better approach semantically, but its non obvious initially (given the old behavior)

**Comment by benjamingr** [comment]
A pull request would be entertained
