### ISSUE TITLE
Merging custom stack into a bluebird error

### ISSUE THREAD

**Issue by Rush** [petkaantonov/bluebird#802]
I have two bluebird-powered applications connected over the network, when an error occurs on one end of the network, the error is serialized over the wire. I would like merge the serialized stacktrace into bluebird's own long stacktrace, is it doable?

`Bluebird.longStackTraces()` is enabled on both ends.

**Comment by benjamingr** [comment]
+1, as far as I know it's not possible at the moment, it would require hooks into bluebird's internal stack traces - bluebird isn't aware of what operation it's wrapping.

If it was doable to let bluebird know "this operation happened during waiting for that promise to resolve, please put it in the stack trace" - how would the API look?

**Comment by Rush** [comment]
It seems I got it working ... not sure if it works in every case but it looks easier than I originally planned and requires no talking to bluebird internals, as bluebird does the parsing on its own.

Receiving end that parses the messages from JSON and throws if they have `error` key
```js
.catch(function(err) { // err is a js object, JSON parsed from the wire
    if(! (err instanceof Error) && err.message && err.stack) {
      var errInstance = new Error(err.message);
      errInstance.stack = err.stack; 
      throw errInstance; // bluebird should parse the stack here and join new events to it
    } else {
      throw err;
    }
  })
```

Sending party:
```js
if(error && error instanceof Error) {
  error = {
    message: error.message,
    stack: error.stack,
    name: error.name
  };
}
self.send({
  error: error,
  type: obj.type,
  response: obj.uuid,
  data: responseData
});
```
