### ISSUE TITLE
Can’t use promisifyAll on AWS Lambda

### ISSUE THREAD

**Issue by whittle** [petkaantonov/bluebird#805]
The [official JavaScript SDK for the API exposed by AWS Lambda](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html) exposes both an [invoke](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) method and an [invokeAsync](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invokeAsync-property) method. When using promisifyAll, Bluebird detects this and bails out. It should be noted, however, that the invokeAsync method is officially deprecated. 

I don’t know that it’s appropriate for Bluebird to do something in this special case, but this seemed like a common enough library that [the request to open an issue](https://github.com/petkaantonov/bluebird/wiki/Error:-Cannot-promisify-an-API-that-has-normal-methods) applied.

**Comment by rkoberg** [comment]
You can do:
```
Bluebird.promisifyAll(object, {suffix: 'Bsync'});
```

**Comment by whittle** [comment]
Excellent point, @rkoberg. That seems like a sufficient solution.

**Comment by zommerfelds** [comment]
Or, if you want:
```
Promise.promisifyAll(
    new AWS.Lambda(),
    {filter: (name, func, target, passesDefaultFilter) =>
        passesDefaultFilter && name !== 'invokeAsync'});
```
