### ISSUE TITLE
Mutation of rejected argument in onPossiblyUnhandledRejection

### ISSUE THREAD

**Issue by cdaringe** [petkaantonov/bluebird#806]
Hi all,

Thanks for the great lib.  I've been reading through the docs, but cannot figure out why this occurs.  Take a peek at the rejected err arg.  It's ok in the first catch, but in the unhandled handler, it's mutated.

Thanks,

```js
var Promise = require('bluebird');

var p = Promise.resolve().then(function() {
    return Promise.reject({ my: 'errz' });
}).catch(function(err) {
    throw err; // err => { my: 'errz' }
});

Promise.onPossiblyUnhandledRejection(function(err) {
    /*
    err => { handle: 6,
      type: 'error',
      className: 'Error',
      constructorFunction: { ref: 11 },
      protoObject: { ref: 12 },
      prototypeObject: { ref: 2 },
      properties:
       [ { name: 'stack', attributes: 2, propertyType: 3, ref: 2 },
         { name: 'message', attributes: 2, propertyType: 1, ref: 13 } ],
      text: 'Error: [object Object]' }    
     */
});
```

**Comment by tyscorp** [comment]
[`{ my: 'errz' }` is not an Error object](http://www.devthought.com/2011/12/22/a-string-is-not-an-error/). You should consider always throwing/rejecting Error objects when handling exceptions.

**Comment by cdaringe** [comment]
@tyscorp, indeed.  however, I'm dealing with vendor code

**Comment by cdaringe** [comment]
I do want to add that even when I do a `Promise.reject(realErrorInstance)` without a `.catch`, I still do not get access to the `realErrorInstance` in the `onPossiblyUnhandledRejection` handler*

**Comment by cdaringe** [comment]
I suppose the content _is_ in there, but it's tucked away in a different format.  I can still access the attrs.  looks like they may be proxied to `err.properties`?  curious about the design here.  can someone share the intent, as to how and why the error obj was mutated?

**Comment by petkaantonov** [comment]
Not sure where all those properties are coming from but the first argument is forced an error object so that `err.stack` works. 

You can get the original object by doing:

```js
Promise.onPossiblyUnhandledRejection(function(err, promise) {
    console.log(promise.reason());
    // { hello: 'world' }
});
Promise.reject({hello: "world"});
```
