### ISSUE TITLE
Unhandled rejection using coroutines

### ISSUE THREAD

**Issue by wryun** [petkaantonov/bluebird#808]
Have this code:

```
var bluebird = require("bluebird");

var doError = bluebird.coroutine(function* () {
  asdasd;
});

bluebird.coroutine(function* () {
  try {
    yield new Promise(function (resolve) {
      return setTimeout(resolve, 100);
    });
    yield Promise.all([doError()]);
  } catch (e) {
    console.log(e);
  }
})();
```

Looks reasonable, but it triggers an unhandled rejection message. Is this expected behaviour?

**Comment by benjamingr** [comment]
Looks like a bug to me, @petkaantonov ?

**Comment by petkaantonov** [comment]
It should be

```js
bluebird.coroutine(function* () {
  try {
    yield new bluebird(function (resolve) {
      return setTimeout(resolve, 100);
    });
    yield bluebird.all([doError()]);
  } catch (e) {
    console.log(e);
  }
})();
```

`Promise` is not bluebird in your case.

**Comment by bergus** [comment]
Still, shouldn't this work with the native `Promise.all` just as well?

**Comment by wryun** [comment]
The reason I ran across this is that we're not using bluebird directly, but via babel's implementation of ES7 async.

**Comment by wryun** [comment]
Agree with @bergus - shouldn't this be interoperable with standard Promises?

**Comment by petkaantonov** [comment]
The unhandled rejection reporting waits until end of turn to see if there is an error handler, but when mixing with other implementations like this, the error handler might not be attached soon enough because the async schedulers are not aware of each other.

I tested this extensively and indeed it turned out that the native Promise.all is calling the `.then` on the immediately rejected promise too late, after the error has already been reported.

**Comment by petkaantonov** [comment]
You can see native promise calls the then too late by doing this:

```js
var c = false;
bluebird.resolve({
    then: function(_) {
        c = true;
        _(3);

    }
})
// true
console.log(c);

var c = false;
Promise.resolve({
    then: function(_) {
        c = true;
        _(3);

    }
})

// false.
console.log(c);
```

**Comment by bergus** [comment]
I didn't think Promises/A+ mandates whether thenable resolution is asynchronous or not? Afaik even implementations that defer it until a handler is added are still conformant.

**Comment by petkaantonov** [comment]
Steps are executed synchronously unless there is explicit mention of "run these steps in next turn" or similar.
