### ISSUE TITLE
Can an array of promises be modified while iterating?

### ISSUE THREAD

**Issue by matthew-dean** [petkaantonov/bluebird#810]
My use case:

I have an array of promises, which is reading the directories of a directory. If I run ```Promise.all()``` on that array, it's likely there will be more directories inside those directories, in which case I need to add all of those as promises, and so on, until the tree has been traversed. In other words, I can't get a complete "list" of promises in order to call ```Promise.all()``` on that list, because "getting a list" is exactly what the async function ```readdir``` is doing, recursively.

Is ```Promise.all()``` even the correct way to go about this?

**Comment by matthew-dean** [comment]
And I apologize if the question itself is due to a noobish understanding of promises.

**Comment by phpnode** [comment]
@matthew-dean it does sound like you need to experiment with promises a bit more to fully grok them. This isn't really the right place for support, stackoverflow or gitter are better, but perhaps you'll find this helpful:

```js
var Bluebird = require('bluebird');
var fs = require("fs");
var path = require("path");
Bluebird.promisifyAll(fs);

function processDir (dirname) {
  return fs.readdirAsync(dirname).then(items => {
    return Bluebird.map(items, item => {
       const fullPath = path.join(dirname, item);
       return fs.statAsync(fullPath).then(stat => {
          if (stat.isDirectory()) {
            return processDir(fullPath);
          }
          else {
             return processFile(fullPath);
           }
       });
    })
    .reduce((items, item) => items.concat(item), []);
  });
}

function processFile (filename) {
  return {filename: filename, somethingElse: true};
}


processDir(__dirname).then(console.log);
```

**Comment by benjamingr** [comment]
Please ask support questions on StackOverflow. There is a detailed exmaple of iterating a directory in the examples section here.
