### ISSUE TITLE
Access original value from promisified method.

### ISSUE THREAD

**Issue by ajcrites** [petkaantonov/bluebird#811]
Specifically I am working with the aws sns library.

    var sns = new AWS.SNS();
    sns = Promise.promisifyAll(sns);

    var request = sns.publishAsync(opts);

Now I can chain `.then` and `.catch` to `request` as expected and it all works great.

Only problem is that getting the requestId of a failed request takes a bit more work since it's not included in the error.  Typically you would do something like this:

    var request = sns.publish(opts);
    request.on("complete", info => console.log(info));

However when I try to do this after `publishAsync` I just get `request.on is not a function`.

I need a way to access the original / non-promise value from the returned promise object so that I can call methods on it.

**Comment by phpnode** [comment]
@ajcrites this is not the right place for support questions, it's better to ask on stackoverflow or github. Your question makes me think that you need to experiment with promises a bit more, because it doesn't sound like you've fully understood them quite yet.

**Comment by ajcrites** [comment]
@phpnode this is not a question, I am just asking for new functionality here. I need to get the value from the asynchronized function and there does not appear to be a way to do that. Take this example:

    let Promise = require("bluebird");
    let assert = require("assert");

    function someFn(cb) {
        process.nextTick(() => cb(null, "some value"));

        return "some other value";
    }

    let someFnAsync = Promise.promisify(someFn);

    let someOtherValue = someFnAsync().then(value => assert.equal("some value", value));
    assert.equal("some other value", someOtherValue.originalValueProperty);

I need `originalValueProperty` to exist or some other way to get it. This applies specifically to the AWS.Request object returned by `sns.publish` above but it also applies in a more general sense.

**Comment by petkaantonov** [comment]
Use a custom promisifier http://bluebirdjs.com/docs/api/promise.promisifyall.html#option-promisifier

**Comment by petkaantonov** [comment]
```js
var sns = new AWS.SNS();
sns = Promise.promisifyAll(sns, {
    promisifier: function(method) {
        return function() {
            var request = method.apply(this, arguments);
            return {
                promise: new Promise(function(resolve, reject) {
                    request.on("complete", resolve);
                    request.on("error", reject);
                }),
                request: request
            }
        };
    }
});

var requestAndPromise = sns.publishAsync(opts);
requestAndPromise.promise.then(...)
```
