### ISSUE TITLE
lazy promises

### ISSUE THREAD

**Issue by tcurdt** [petkaantonov/bluebird#812]
I would love promises to be lazy and not get executed on creation - but instead on `then`.
I know this is not part of the spec - but I still find it very useful.

Seems like there are others interested in this, too. There is a work-around on [SO](http://stackoverflow.com/questions/21957187/can-i-do-a-lazy-promise-with-bluebird-js) and someone else created [a lib for it](https://github.com/then/lazy-promise).

Would love to hear some thoughts on this.

**Comment by tflanagan** [comment]
Don't interrupt this as +/-[1|0], but having the ```.then()``` be the executioner of the promise seems misleading.

I think a better keyword would be ```.exec()```.

---

I'm pretty confused as to the purpose/concept of this. You would declare a new Promise (which is essentially a function execution), but not execute it?

Why not create a function, then execute it like normal when you need it?

Can you provide general use cases where this feature would be required?

**Comment by tcurdt** [comment]
Indeed - an `exec` would be much clearer. Would also be a fine option in my opinion.

As a use case: I have list of objects. These objects have very expensive function.

    {
      load: function() { console.log('loaded') }
    }

The function will not necessarily be called on every object. When the function gets called the result should be cached. Given there is other async code that uses Promises, it would be great if one could just call `object.load.then(...)`. It would be straightforward to stick a Promise in there as a possible future.

    {
      load: new Promise(function(){ console.log('loaded') })
    }

This would work very seamlessly with the other code. The only problem: Creating a Promise executes a Promise.

Thing is: That's not the spec and I wouldn't know how to add it API wise. I only know that the immediate execution (be it the most common use case) suddenly feels quite awkward. Working around it even more so.

**Comment by phpnode** [comment]
https://gitter.im/petkaantonov/bluebird would be a better venue for this discussion.

Lazy `.then()`  is particularly nice for database query builders when combined with `async`/`await`:

```js
const roles = await db.select().from("roles");
console.log(roles);

const users = await db.select().from("users").where({active: true});
console.log(users);
```

**Comment by tflanagan** [comment]
When things feel wrong, it's usually because it is.

Why wouldn't you have a function declaration:

```
function loadPromise(){
  return new Promise(...);
}

Object.load = function(){
  return loadPromise();
};
```

That's essentially what you want, right?

**Comment by tcurdt** [comment]
@tflanagan that creates a new Promise on every `load` call and does not make use of value caching. I sure can add caching myself - but that's not the point.

In my use case it's also not the same `load` function for every object (and adding to `Object` also feels wrong anyway).

Didn't know about the gitter room. Sure can join there.

**Comment by spion** [comment]
Normally I cache the promise:

```
{
  load() { if (!this._cached) this._cached = getPromise(); return this._cached; }
}
```

You can write a wrapping function that does that

```js
function cached(field, fn) {
  return function() {
    if (!this[field]) this[field] = fn.call(this)
    return this[field]
  }
}

{
  load: cached('myValue', function() { return getPromise(); })
}
```

**Comment by tflanagan** [comment]
Sorry, I used ```Object```, should've used ``foobar```.

I see what you're getting at, and I see the value in it, but not in adding it to core. I'm -0.

There is already a userland package that does this, it doesn't get many downloads, so the need for this seems minimal.

The wrapper functions themselves aren't too difficult and I can see them being case specific for every user. Caching techniques, execution techniques, etc...

**Comment by tcurdt** [comment]
Yeah - I didn't think it was for the core. Just thought I bring it up as a discussion as in my very case it seems quite useful.

But I've come up with a wrapper that works OK for me.

    function LazyPromise(fn) {

      var promise = null;
      var fn = fn;
  
      this.then = function() {
        promise = promise || new Promise(fn);
        return promise.then.apply(promise, arguments);
      }

      this.isFulfilled = function() {
        return promise != null;
      }
    }

    module.exports = LazyPromise;

What user land package or you referring to? The one I linked?

**Comment by winterland1989** [comment]
Please check out [my library](https://github.com/winterland1989/Action.js) , it's provide lazy, cancellable and retriable Actions with Promise style api, and from [benchmark](https://github.com/winterland1989/Action.js/wiki/Benchmark), it's the only library on earth faster than bluebird.

**Comment by winterland1989** [comment]
Promise is not about the action it will run, it's a proxy to the value produced in future, so a lazy Promise basically is just a function return Promise, which may not be what you want.

**Comment by vitaly-t** [comment]
@tcurdt, @tflanagan, @phpnode, @spion 

To give this idea a body, I came up with the following example, as an illustration:

```javascript
function LazyPromise(cb) {
    this.cb = cb;
    this.exec = function () {
        return new Promise(this.cb);
    };
    this.then = function (func) {
        return this.exec().then(func);
    };
}

var test = new LazyPromise(function (resolve, reject) {
    resolve("test");
});

// initiate lazy promise:
test.then(function (data) {
    console.log(data);
});
```
Let me know, please, if illustrates the idea well.

**Comment by winterland1989** [comment]
So every time you call `then`, you're creating a new promise using `exec`, which is exactly what OP want to avoid : )

When you want a promise to be lazy, you're asking promise to remember the underline action and wait your command, but  that's not what a promise is intended to abstract, basically what a promise does are:

+ schedule the action to be fired.
+ if the action are running, save any callback who want the value .
+ when the action finishes, memorize the value it produced, feed the value to previous saved callbacks.
+ if any future callbacks want to use this value, just use the memorized value.

So after all the process, the underline action will be forgotten and be garbage collected eventually, the value produced in future is the core of promise abstraction. 

Generally speaking, a promise doesn't even care when the underline action are scheduled as long as it will be fired some point in future, and that's part of the reason why a lot of promise libraries have different performance characteristic. if you want an action to be saved and waiting for your command, you're not going to use promise because it's simple not designed to do this job.

**Comment by winterland1989** [comment]
Note that what described above is what a promise does internally and can't be changed by building any wrapper on it, that's what Promise A+ designed it to be, so please consider add some method on prototype which have the access to internal state if you really want to add manual scheduling control.

**Comment by tjconcept** [comment]
I don't think this would belong anywhere in Bluebird - it's not really a promise-thing anymore than a general async challenge.

I wrote a package for **lazy-execution of an async job** (and reuse of it's promise so that it will **never run twice**): https://www.npmjs.com/package/smoop#using-promises

Internally it is using Bluebird, but it works with callbacks as well. The async job can be either callback taking or promise returning as well.

Example:

```js
var smoop = require('smoop');

var myQuery = smoop(function(){
    return queryTheDatabase();
});

// return now and queryTheDatabase is never called

myQuery().then(function( result ){
    console.log(result);
});

// queryTheDatabase is called
```

It is pretty simple (63 SLOC) and has options for expiring the result or continuously refreshing it.

**Comment by petkaantonov** [comment]
Instead of passing a lazy promise, you can try passing a function that returns an eager promise which has the same effect.

**Comment by nomi-ramzan** [comment]
Hi
What do you think about this way ? **Just for feedback/better way.**

```
Promise.PromiseLazy = function(func, args, opts){opts=opts||{};
	var PromiseLazy = function(){
		return func.apply(opts.cxt, args)
	}
	PromiseLazy.then = function (resolve, reject) {
		return PromiseLazy().then(resolve, reject);
	}
	PromiseLazy.catch = function (reject) {
		return PromiseLazy().catch(reject);
	}
	return PromiseLazy;
}
```
Then we use it like this

```
Primise.PromiseLazy(getPromise, [123])
// Also working
.then(console.log).catch(console.log)
// OR
.then(console.log, function (err) { console.log('Got Error', err); })

// OR
Primise.all([
	Primise.PromiseLazy(getPromise, [123])
	,Primise.PromiseLazy(getPromise, [123])
])
.then(console.log)
.catch(function (err) { console.log('Got Error', err); })
```

**Comment by tcurdt** [comment]
@petkaantonov 

> Instead of passing a lazy promise, you can try passing a function that returns an eager promise which has the same effect.

Not sure I can follow. What's an "eager promise"? And won't that also be yet another fresh promise instance on calling it twice?
