### ISSUE TITLE
Invalid anti-pattern premise

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#814]
In the following anti-pattern chapter you are going way off on a limb, only to confuse people:

[The .then(success, fail) anti-pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-thensuccess-fail-anti-pattern)

The word anti-pattern in programming refers to code redundancy or compromised algorithmic efficiency.

What you refer to is simply a coding style, which got nothing to do with anti-patterns.

**Comment by benjamingr** [comment]
It's code redundancy

**Comment by bergus** [comment]
Related: https://stackoverflow.com/questions/24662289/when-is-thensuccess-fail-considered-an-antipattern-for-promises

Maybe we should relax the language a bit. It's antipattern only in certain siturations.

**Comment by vitaly-t** [comment]
Yes, and saying:

>there is almost never a reason to use .then(success, fail) in application code

`almost` doesn't quite cut it here, because those situation are all over the place.

**Comment by petkaantonov** [comment]
There is edit button on the top right corner

**Comment by vitaly-t** [comment]
I have updated my previous post with an example.

**Comment by petkaantonov** [comment]
How would you write it in synchronous code then?

**Comment by vitaly-t** [comment]
Not sure, haven't tried yet, it was written with promises from the beginning.

**Comment by bergus** [comment]
Those global variables are horrible and seem unnecessary to me. Regardless, code like the following is perfectly reasonable:
```js
obj.none('begin')
.then(callback)
.then(function (data) {
    return obj.none('commit') // COMMIT;
    .then(function() {
        update(false, true, data); // client notification;
        return data;
     });
}, function (reason) {
     return obj.none('rollback') // ROLLBACK;
     .then(function() {
        update(false, false, reason); // client notification;
        throw reason;
    });
}); // TODO: handle commit/rollback fail
```

There is no JavaScript syntax for synchronous branching on fails. Regardless, with a pythonic `try` we could write
```js
try {
    obj.none('begin');
    callback();
} catch(reaseon) {
    obj.none('rollback'); // ROLLBACK;
    update(false, false, reason); // client notification;
    throw reason;
} else {
    obj.none('commit'); // COMMIT;
    update(false, true, data); // client notification;
    return data;
}
// TODO: handle commit/rollback fail
```

**Comment by vitaly-t** [comment]
Can't really do that, your code merges errors from `begin` and `callback` into one, can't tell one error from the other.

**Comment by bergus** [comment]
@vitaly-t Ah, right, that was the catch, you'll need nesting here indeed. See the edit to my comment (it doesn't really change the point).
And don't get me wrong, I support your case: there is indeed no reason to use `.catch` here, and your usage of `then` with both callbacks is not an antipattern.
It's only an antipattern for people who expect it to work like `try catch` in one method, which it doesn't.

**Comment by phpnode** [comment]
@vitaly-t your example code is not really ideal for other reasons, as @bergus mentioned - it relies on out of band signalling. Here's how I'd write your example:

```js
obj.none('begin')
.then(callback)
.catch(function (err) {
  return obj.none('rollback').then(function () {
    update(false, false, data); // client notification
    throw err;
  });
})
.then(function (data) {
  return obj.none('commit').return(data);
})
.then(function (data) {  
  update(false, true, data); // client notification
  return data;
});
```

**Comment by vitaly-t** [comment]
@phpnode not quite, it shows the same  problem as what bergus had: within the `.catch` section you cannot tell the error related to `begin` execution from an error from the `callback` execution.

**Comment by phpnode** [comment]
@vitaly-t that's true, this does seem like a scenario where the second argument might be an appropriate option. However I still think that *most* of the time it really is an anti pattern. I recently started work on a codebase where this is used a lot and it's causing them a lot of pain because it doesn't catch errors that they expect.

**Comment by vitaly-t** [comment]
We all have different experience in using promises, depending on the exact tasks at hand. My experience suggests that my example isn't that rare at all.

This is why I suggested to reconsider advocating the `.then(success, error)` syntax as anti-pattern, 'cos it ain't. It solves its specific logic patterns where `.catch` isn't even usable.

**Comment by benjamingr** [comment]
Do Petka's exercise of writing the code as if all operations were synchronous and the correct way will reveal itself.

**Comment by vitaly-t** [comment]
@benjamingr I wouldn't even know how to approach this, given that it is built on top of an asynchronous callback-based protocol. For the same reason I'm not sure how practical an exercise this would make.

**Comment by stefanpenner** [comment]
`catch(CB).then(CB)` is likely the pattern most actually intend to use. It mimics the syntactic try/catch nicely, conveys an unambiguous intent, and transposes gracefully to ES7 async/await's syntactic try/catch.

Although the `then(CB,CB)` induced Stockholm syndrome appears normal to some, it is unfortunate.

**Comment by benjamingr** [comment]
@vitaly-t assume the callback base protocol returns values instead or taking callbacks and that all methods return synchronous.

**Comment by vitaly-t** [comment]
@benjamingr I have tried to think it that way, nothing came up yet. If promises are to stand for simplicity, and streamlined logic, in my example it is isn't there, or perhaps doesn't exist to begin with :)

@stefanpenner you first stated the obvious, and then ended with plain trolling. that's not helping.

**Comment by benjamingr** [comment]
What's wrong with this @vitaly-t ?
```js
function transact(fn){
    return obj.none("begin").then(fn).then(x => obj.none("commit").return(x), 
                                           e => obj.none("rollback").throw(SqlError(e));
}
transact(callback).tap((data) => {
    update(false, true, data);
}).catch(SqlError, e => {
    update(false, false, cbReason);
    throw e;
}); // .catch(CommitError, e => /* handle error in commit */)
```

**Comment by stefanpenner** [comment]
@vitaly-t I'm glad you agree, if what I said was obvious that re-affirms the anti-pattern claim.

The Stockholm syndrome comment isn't trolling, it's unfortunately true.

**Comment by vitaly-t** [comment]
@benjamingr 
In the following example:
```javascript
return obj.none("begin").then(fn).then(x => obj.none("commit").return(x), 
                                           e => obj.none("rollback").throw(SqlError(e));
```
as I stated twice above, your `error` section can't tell whether the error was caused by `begin` or by `the callback` function.

@stefanpenner you are not really trying to follow the discussion, best not to post then.

**Comment by benjamingr** [comment]
@vitaly-t Oh, I didn't realize none could throw, that's super easy to fix (I thought you were talking about commit erroring vs callback).

```js
function transact(fn){
    return obj.none("begin").catch(e => { throw TransactionStartError(e) }) 
                   .then(fn).then(x => obj.none("commit").return(x), 
                                         e => isNotBeginError(e) ? reject(e) : obj.none("rollback").throw(SqlError(e));
}
transact(callback).tap(data => {
    update(false, true, data);
}).catch(BeginTransactionError, e => {

}).catch(SqlError, e => {
    update(false, false, cbReason);
    throw e;
}); // .catch(CommitError, e => /* handle error in commit */)
``` 

Of course we can use a coroutine here and get clearer and more verbose syntax:

```js
const transact =  coroutine(function*(fn){
    try { 
        var begin = yield obj.none("begin");
    } catch (e) { throw new TransactionStartError(e); }
    try {
        yield fn(); // the transaction not being passed around is weird btw
     } catch(e) { return obj.none("rollback").throw(SqlError(e)); }
     yield obj.none("commit"); 
}
```

**Comment by vitaly-t** [comment]
Well, if we take this code from your example:
```javascript
.then(fn).then(x => obj.none("commit").return(x), 
                                         e => isNotBeginError(e) ? reject(e) : obj.none("rollback").throw(SqlError(e));
```
that's in fact the very same `.then(success, error)` syntax - the proclaimed anti-pattern, which is argued against here in favour of the `.catch` syntax, which makes the whole point of the conversation - changing my original example to such a form as to make no use of the `.then(success, error)` syntax.

**Comment by benjamingr** [comment]
How is that even remotely close to the code that is wrapped in a promise constructor? Note the `reject` here is `Promise.reject` and not a parameter of the promise constructor - which there is none.

I think what you were missing is that you can _conditionally_ catch things and that in JavaScript you can rethrow errors safely.

**Comment by vitaly-t** [comment]
From what I'm reading, this code:
```javascript
.then(x => obj.none("commit").return(x), 
                                         e => isNotBeginError(e) ? reject(e) : obj.none("rollback")
```
translates into something like:
```javascript
then(function (x) {
    return obj.none("commit").return(x);
}, function (e) {
    return isNotBeginError(e) ? reject(e) : obj.none("rollback");
});
```
except I don't even know what `isNotBeginError` this is...

**Comment by benjamingr** [comment]
Maybe an `instanceof` check, maybe another assertion on the error type. Whatever floats your goat.

The key here is merely that you'd rethrow the exception to signal it wasn't handled - preferably you'd wrap it in a more concrete type to signal what sort of exception it is and how someone should handle it. Half the point of exceptions (vs. using return values for errors) is the fact you can write this sort of code and propagation happens rather than writing the code you wrote above in your original example.

**Comment by vitaly-t** [comment]
>Whatever floats your goat.

I don't have a goat. LOL :)

My code was in fact written to work within the Promises/A+ standard, without any specific promise library in mind, so I'm not being picky here ;)

It this point I probably will just leave a perfectly functioning code as is, because I believe that if I need to write extra code, like re-throwing exceptions, then my original code is way better, as it is simpler. And as far as the anti-patterns go, it is still very unconvincing.

**Comment by benjamingr** [comment]
> My code was in fact written to work within the Promises/A+ standard, without any specific promise library in mind, so I'm not being picky here ;)

Bluebird contains a lot of sugar that makes developer lives easier - but nothing too specific in this regard - everything above can be written just fine without bluebird. 

It is considerably less code, and you have a lot less room for mistakes because you don't have to manually handle cases and promises don't stay pending forever or silence errors (because control flows automatically rather than manually).

The code still ends up being clearer, less redundant and shorter, but I guess clearer is subjective. I think the `update` callback is pretty weird anyway :D

**Comment by benjamingr** [comment]
I'd also like to note that the pattern is there for _very obvious_ cases of abuse, bluebird has a philosophy of doing things that cater for 95% of developers or 95% of use cases. There are always pathological examples where an anti pattern might be appropriate (also for explicit construction).

That document was written for things like:

    function foo(successCb, failCb){
         somePromise.then(successCb, failCb);
    }

    foo(function(success) { ... }, function(failure) { ... }

Where the fact "things" happen with the callback if it throws is implicit, and it would have been a lot better to just return a promise and chain off that. This is _extremely_ common - for example in Angular when working against `$http` or in jQuery working against `$.ajax`.

I think your (initial) attempt at the code contains (what I consider) smell, but it is a _lot_ more debatable than the code people usually write with `then(success, fail)`

**Comment by vitaly-t** [comment]
Just to return on your very first post here:

>It's code redundancy

Redundancy in code is defined as a repeated block of code whilst performing the exact same operation.

Using `.catch` versus `.then(success, error)` isn't repeating the same code, as the resulting logic differs. So even strictly within the terminology, there is a flaw right there in trying to label `.then(success, error)` as anti-pattern.

**Comment by bergus** [comment]
@stefanpenner 
> `catch(CB).then(CB)` is likely the pattern most actually intend to use.

That only works the same as `.then(CB, CB)` when the error handler rethrows. Which was the case in Vitaly's example, though I really don't like that style.

> transposes gracefully to ES7 async/await's syntactic try/catch.

Actually `try catch` in `async` functions is superior, because you can control what parts of your code the `try` wraps. With `.catch`, it just always catches *all* rejections from the complete chain, unless you start nesting. Both Benjamin and me fell for that above :-)

However `try catch` also lacks the ability to handle normal and exception cases distinctively. @benjamingr worked around this quite well:
> ```js
async function transact(fn) {
    try { 
        var begin = await obj.none("begin");
    } catch (e) {
        throw new TransactionStartError(e);
    }
    try {
        await fn(); // the transaction not being passed around is weird btw
    } catch(e) {
        return obj.none("rollback").throw(SqlError(e));
//      ^^^^^^
    }
    await obj.none("commit"); 
}
```

…by `return`ing (or `throw`ing) from within the `catch`. Now that is hard-to-understand control flow!

Just using `.then(x => … obj.none("commit")…, e => … obj.none("rollback")…)` is so much more sane imo :-)
