### ISSUE TITLE
.spread with redirect?

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#817]
As much as I like using method `.spread`, when it comes to databases it runs short on the mapping logic.

Here's a simple example of a nested transaction:

```javascript
db.tx(function () {
    return promise.all([
        this.none("update users set active=$1 where id=$2", [true, 123]),
        this.none("insert into audit(status, id) values($1, $2)", ['active', 123]),
        this.tx(function () {
            return promise.all([
                this.one("insert into users(name) values($1) returning id", "John"),
                this.one("insert into events(code) values($1) returning id", 123)
            ]);
        })
    ]);
})
    .then(function (data) {
        console.log(data[2][0].id); // print new user id;
        console.log(data[2][1].id); // print new event id;
    })
    .catch(function (error) {
        // error;    
    });
```
We would really like to be able to replace the last `then` section with the `spread`, but the problem is we cannot use the `data` directly, we need to use `data[2]` in our example.

Is there any possibility to extend method `spread` to pass it the data to be mapped, to override the default data resolved?

Something that would have an effect of:

```javascript
.spread(data[2], function (user, event) {
    console.log(user.id); // print new user id;
    console.log(event.id); // print new event id;
});
```

Or else, what would be the recommended approach in such cases?

**Comment by spion** [comment]
.get(2).spread(function(user, event) { ... })

**Comment by vitaly-t** [comment]
@spion that is brilliant! :+1: 

Do you want to post it here also? - http://stackoverflow.com/questions/33360184/spread-with-data-redirect

Cheers!!!
