### ISSUE TITLE
Add `Bluebird.on()` for promisifying an event emitter

### ISSUE THREAD

**Issue by phpnode** [petkaantonov/bluebird#820]
It's incredibly common to need to promisify event emitters of various types, particularly streams. I've written something like this a million times (approximately):

```js
function promisifyEmitter (emitter, success = "data", error = "error") {
  return new Promise((resolve, reject) => {
    emitter.on(success, resolve).on(error, reject);
  });
}
```

It would be really nice to have this as part of bluebird, perhaps in the form of `Bluebird.on()`:

```js
Bluebird.on = function (emitter, success, error) {
  if (success === undefined) success = "data";
  if (error === undefined) error = "error";
  return new Promise(function (resolve, reject) {
    if (Array.isArray(success)) {
      for (var i = 0; i < success.length; i++) {
        emitter.once(success[i], resolve);
      }
    }
    else {
      emitter.once(success, resolve);
    }
    if (Array.isArray(error)) {
      for (var i = 0; i < error.length; i++) {
        emitter.once(error[i], reject);
      }
    }
    else {
      emitter.once(error, reject);
    }
  });
};
```

**Comment by spion** [comment]
Can you give a couple of realistic example usages?

Also, have you tried [promise-streams](https://github.com/spion/promise-streams)? I'm trying to figure out all the things wrong with node streams and then implement something that can take care of the problems: https://gist.github.com/spion/ecdc92bc5de5b381da30 so if you have any insights I definitely welcome them.

**Comment by phpnode** [comment]
@spion I'd only glanced at `promise-streams`, I'll have another look, thanks. Right now I'm dealing with a legacy-ish UI which emits various events when transitioning between screens. For example, if I open a dialog, that dialog component will emit an `error` event when there's a problem and a `close` event when the user closes it. I need to be able to await those events:
```js
function askTheUserSomething() {
  var dialog = createSomeDialog();
  return Bluebird.on(dialog, "close");
}
```
The other example which immediately springs to mind is reading a small number of bytes from a certain location in a file in node, which can only be done with a read stream:
```js
function readInt (offset) {
  var stream = fs.createReadStream({start: offset});
  return Bluebird.on(stream, "data").then(function (buffer) {
    return buffer.readInt32LE(0);
  });
}
```

**Comment by spion** [comment]
For the second example, you might run into troubles: e.g. what happens if there is a stream error after you read the data? What if there is more than one error? What if you attach to a network stream to read a packet, but then you're not resuming/pausing/cancelling that stream in any way?

I think this is the kind of thing that needs to be done in a separate companion library.

**Comment by petkaantonov** [comment]
When you think about all the different event emitter apis (`addListener`, `addEventListener`, `on` etc) and all the different success events (`"success"`, `"load"`, `"complete"`, `"data"`) that are not always even success events it's just way too specific and ad hoc to be a core feature. So I agree with spion that this probably belongs to separate utility library.

**Comment by phpnode** [comment]
ok, I think on reflection I agree

**Comment by kirly-af** [comment]
Sorry to dig out this old ticket, but I did not understand @petkaantonov's last comment.

It is the developer choice to properly choose what event he wants to await on. Especially nowadays, since we have async/await available. For example, being able to await on the "end" event of a stream is quite useful. If one needs to wait for another event, she can just use Promise.all.

```js
try {
    await Promise.all([
        Promise.on('end', readbleStream),
        Promise.on('finish', writableStream),
        Promise.on('someEvent', writableStream)
    ]);
} catch (err) {
    // convenient error handling
}
```

**Comment by benjamingr** [comment]
@kirly-af you're answering a question about a different API from the one that was suggested. The suggestion here is to infer the event names.

**Comment by kirly-af** [comment]
@benjamingr Thanks for your answer. Indeed, I got it wrong. The way I see it there are "only" 3 APIs to support. That sounds quite reasonable to me.

There would be 3 possibilities to support them:
* use 3 different functions: .fromEventTarget(), .fromEventEmitter(), .fromInternetExplorerEvent() (terrible name, we all agree)
* infer type with duck typing (like does [event-to-promise](https://www.npmjs.com/package/event-to-promise))
* infer type with instanceof (probably won't work in IE)

**Comment by benjamingr** [comment]
@kirly-af instead,  async iteration support was added support for the to Node.js, you can now use `for...await` in async functions on Node.js streams. That is a more "long term" solution to making event emitter like constructs work with promises.

**Comment by kirly-af** [comment]
The actual issue is more about EventEmitters than streams. With the streams semantics (.pipe() or standard async iteration) we deal with data consumption.

However, here I just want to be able to await on an event I subscribed on (let's say the stream "end" event), and that's not something async iteration is meant for.

Sooner or later we might have a standard EventEmitter-like API (as the Observable proposal) but nowadays we're stuck with the existing APIs.

**Comment by benjamingr** [comment]
@kirly-af node has a standard event emitter API (provided in the events module) which we ship. Do you believe that Node.js should provide a `once` method on event emitters that returns a promise?

**Comment by kirly-af** [comment]
@benjamingr By standard I meant "available in most environment" (ie. browsers + node). But yes, that would effectively solve the problem (only in Node obviously). 
That would probably require another name though as '.once()' already returns an EventEmitter. Should I open an issue in the Node.js repo instead?

**Comment by benjamingr** [comment]
@kirly-af sure, you're also welcome to open one in https://github.com/nodejs/promise-use-cases/issues if you prefer - either are fine.

**Comment by kirly-af** [comment]
@benjamingr I just created https://github.com/nodejs/node/issues/20893
