### ISSUE TITLE
Remove check for getters in promisifyAll

### ISSUE THREAD

**Issue by felixfbecker** [petkaantonov/bluebird#828]
`node-mysql` sets getters on the `exports` object to lazy-load their internal modules to reduce memory usage. In bluebird util.js in `inheritedDataKeys()` (line 133) the enumerable properties of the target object are checked for being a getter or setter and if yes excluded from promisification.
I wanted to submit a PR to them to export Pool and Connection so bluebird can pick them up for promisification, but it doesn't work because bluebird excludes getters. Is there a reason for that?

**Comment by petkaantonov** [comment]
Calling getters breaks promisification of mongoose.

**Comment by petkaantonov** [comment]
Also you can just load all the classes to promisify yourself: `Promise.promisifyAll([Connection, Pool])`

**Comment by felixfbecker** [comment]
I didn't know you could pass an array to promisifyAll. That would save a few lines.
