### ISSUE TITLE
.then() not called on some object type?

### ISSUE THREAD

**Issue by sainttail** [petkaantonov/bluebird#833]
I have this code which use kurento-client library and I have the below code.

However, the `.then()` is not called at all if I `resolve` using `_kurentoClient` object but this have no problem at all with other objects. 

```
getKurentoClient()
        .then(function (kurentoClient) {
            console.log('connect to kurento');
            // setup conference io
            conference(kurentoClient, socketio);
            presenter(kurentoClient, socketio);
        })
        .catch(function (error) {
            console.log(error);
        });

function getKurentoClient() {
    return new Promise(function (resolve, reject) {
        kurento(argv.ws_uri, function (error, _kurentoClient) {
            if (error) {
                var message = 'Coult not find media server at address ' + argv.ws_uri;
                reject(message + ". Exiting with error " + error);
            }

            // kurentoClient = _kurentoClient;
            resolve(_kurentoClient);
        });
    });
}
```

Here is the screenshot for properties on `_kurentoClient`

![screen shot 2015-10-29 at 3 04 40 pm](https://cloud.githubusercontent.com/assets/3015139/10813059/977253bc-7e4e-11e5-83c9-ded340671c8c.png)

**Comment by benjamingr** [comment]
It would be awesome of you if you could upload a reproducing sample to GitHub and help isolate the issue further. The object looks like it tried to implement the promise API (it has a `then`) but it does so poorly - so bluebird waits for its then to resolve.

Can you try doing `delete _kurentoClient.then`  and see if it starts working because of that?

**Comment by sainttail** [comment]
yeah after `delete _kurentoClient.then` it is start working.

**Comment by benjamingr** [comment]
@sainttail this is not a bluebird specific issue then, when promises resolve other promises or things with `then` (aka `then`ables, like `_kurentoClient` in this case) - they have to wait for it to call `then` itself.

This is called assimilation. Basically, your `then` would be called _after_ `_kurentoClient` has itself resolved. If you want to resolve with something that's a promise but don't want to resole it (usually, you do) you should wrap it in an object, for example `resolve({_kurentoClient})` and then `.then(({_kurentoClient})  => {...`. Or in ES5 notation `resolve({_kurentoClient:_kurentoClient})` and similarly in the handler.

Thanks for the report.

**Comment by Llorx** [comment]
To add a note, I guess that [this commit](https://github.com/Kurento/kurento-client-js/commit/b06ef2c42d42047caabb49668535263aa7d7b440#diff-ea3e1858c081563f64dbece2fb93f1b8R951) fixes this problem, right?
