### ISSUE TITLE
Promise.promisify(functionReturningAPromise) returns a function which will not resolve

### ISSUE THREAD

**Issue by boneskull** [petkaantonov/bluebird#835]
Test case:

```js
'use strict';

const Promise = require('bluebird');

const func = Promise.method(function() {
});

describe('Promise.promisify()', () => {
  it('should return a function which eventually resolves', () => {
    return Promise.promisify(func)();
  });
});
```

Output:

```shell
$ mocha bluebird-test.js


  Promise.promisify()
    1) should return a function which eventually resolves


  0 passing (2s)
  1 failing

  1) Promise.promisify() should return a function which eventually resolves:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/Volumes/alien/projects/boneskull/mocha/lib/runnable.js:189:19)
```

The behavior if `Promise.promisify()` is misused in this manner seems to be undefined.  Anecdotally, `Promise.promisify(function() {})` also results in a non-resolving function.

~~I'm not sure of how the internals work here, but perhaps something like this could save users from themselves:~~

- ~~When the promisified function (the result of `Promise.promisify()`) is called, **note** the final argument.~~
- ~~**If** the final argument **is not** a function: ~~
    - ~~after returning from the wrapped function, but *before* returning from the promisified function, **if** the return value **is not** a `Promise`:~~
      - ~~**throw** some appropriate exception, explaining to the user how they called a function expecting a callback without a callback (or otherwise directing them to appropriate documentation).~~
    - ~~**else**:~~
      - ~~cast the `Promise` to a bluebird `Promise` and return it.~~
- ~~**else**:~~ 
  - ~~no change in behavior.~~

**EDIT**: I didn't think this through, so I'm not sure how to solve this.  Again; not a big issue.

Not a big deal, but might be more user-friendly.  I may be missing something in the solution that would make this sort of check impossible; if so, I apologize.

**Comment by boneskull** [comment]
ugh, I realize this doesn't make sense, hold on.

**Comment by boneskull** [comment]
yeah, so, promisify passes the function itself, and it has no idea what the wrapped function does with it, or when it will be called, so I imagine this is not solvable.

**Comment by boneskull** [comment]
I suppose, however, if the function actually returned a promise, one *may* be able to safely return it, but maybe not.

**Comment by petkaantonov** [comment]
From the first paragraph in the docs:

> Returns a function that will wrap the given nodeFunction. Instead of taking a callback, the returned function will return a promise whose fate is decided by the callback behavior of the given node function. The node function should conform to node.js convention of accepting a callback as last argument and calling that callback with error as the first argument and success value on the second argument.

Neither `function(){}` nor `Promise.method(function(){})` are "node functions"

**Comment by boneskull** [comment]
@petkaantonov I understand how the function is intended to be used, what I was hoping for was a safeguard.

**Comment by petkaantonov** [comment]
Yes if there was a way to detect misuse it would be implemented in a heartbeat :)
