### ISSUE TITLE
A documentation in chinese version?

### ISSUE THREAD

**Issue by starkwang** [petkaantonov/bluebird#836]
May I translate bluebird 2.x documentation into chinese?
I have translated a part of it:
https://github.com/starkwang/bluebird/blob/master/API-CH.md

**Comment by benjamingr** [comment]
By all means go for it. It's an open source project and as long as you don't charge money for it (and probably even if you do) - it's totally cool.

**Comment by petkaantonov** [comment]
Yea I don't see why not
