### ISSUE TITLE
Documentation issue: onPossiblyUnhandledRejection

### ISSUE THREAD

**Issue by oliversalzburg** [petkaantonov/bluebird#843]
`Promise.onPossiblyUnhandledRejection` is not listed on http://bluebirdjs.com/docs/api-reference.html, but it *is* available at http://bluebirdjs.com/docs/api/promise.onpossiblyunhandledrejection.html

Additionally, the documentation points to *global rejection events*, which just links back to the same page.

**Comment by petkaantonov** [comment]
Yea the local hooks should be added to the reference menu
