### ISSUE TITLE
Documentation issue: longStackTraces

### ISSUE THREAD

**Issue by oliversalzburg** [petkaantonov/bluebird#844]
`Promise.longStackTraces` is not listed on http://bluebirdjs.com/docs/api-reference.html, but is available at http://bluebirdjs.com/docs/api/promise.longstacktraces.html

**Comment by benjamingr** [comment]
Hmm, I think this is intentional, you're supposed to enable long stack traces via `Promise.config` now.

**Comment by oliversalzburg** [comment]
Well, the function exists, works and is documented. If you're not supposed to use it any longer, it should be noted somewhere in the docs, shouldn't it? At the very least, in the **New in bluebird 3.0** article.

**Comment by petkaantonov** [comment]
It's left overs from the documentation auto converter, it is not supposed to be documented or used

**Comment by oliversalzburg** [comment]
If it's not supposed to be used, but it was the way to use it in 2.0 *and* it still works, why not put it into the deprecated APIs article?
