### ISSUE TITLE
Documentation issue: Progression migration

### ISSUE THREAD

**Issue by oliversalzburg** [petkaantonov/bluebird#845]
On http://bluebirdjs.com/docs/api/progression-migration.html, the link in this paragraph leads to a 404 error page:

> For old code that still uses it, see [the progression docs in the deprecated API documentation](http://bluebirdjs.com/bluebird/web/docs/deprecated_apis.html#progression).

**Comment by benjamingr** [comment]
Thanks, will be fixed on next rebuild of the docs.

**Comment by oliversalzburg** [comment]
Awesome :) :+1:
