### ISSUE TITLE
.map with concurrency: 1 does not respect element order

### ISSUE THREAD

**Issue by Alexsey** [petkaantonov/bluebird#847]
```
'use strict'

let Promise = require('bluebird')

function g (n, i) {
	return new Promise(resolve =>
		setTimeout(() => {
			console.log(n, i)
			resolve()
		}, 1000)
	)
}

new Promise.resolve([1, 2, 3]).map(g, {concurrency: 1})
```
will output
```
1 0
3 2
2 1
```
But if we remove ```concurrency``` parameter, or set it to ```> 1``` it will output
```
1 0
2 1
3 2
```
as it sould

**Comment by dmethvin** [comment]
The [docs](http://bluebirdjs.com/docs/api/promise.map.html) address this specifically, although there are some typos in it:

> The order map calls the mapper function on the array elements is not specified, there is no guarantee on the order in which it'll execute the maper on the elements. This makes sense because the order of the even with the {concurrency: 1}.

I think it meant this:

> The order map calls the mapper function on the array elements is not specified; there is no guarantee on the order in which it'll execute the mapper on the elements, even with `{concurrency: 1}`.

**Comment by petkaantonov** [comment]
Use mapSeries if you need ordering

**Comment by Alexsey** [comment]
Sorry, I'll be more attentive next time
