### ISSUE TITLE
Update deoptimization tests

### ISSUE THREAD

**Issue by KenanSulayman** [petkaantonov/bluebird#848]
Hi,

please update all tests for deoptimized / not-optimized functions.

As of recently, many functions that were deemed not-optimizable, including functions with *with statements*, *const* and *let* declarations, et al., became optimizable by TurboFan and other changes on V8.

Here's an updated script for it:

---

```
//Function that contains the pattern to be inspected (using with statement)
function containsWith() {
    return 3;

    with({}) {}
}

function printStatus(fn) {
	var optimizationStatus = %GetOptimizationStatus(fn);

    switch(optimizationStatus) {
        case 1: console.log("Function is optimized"); break;
        case 2: console.log("Function is not optimized"); break;
        case 3: console.log("Function is always optimized"); break;
        case 4: console.log("Function is never optimized"); break;
        case 6: console.log("Function is maybe deoptimized"); break;
        case 7: console.log("Function is TurboFan optimized."); break;

        default: console.log("Unknown optimization status: %s", optimizationStatus)
    }
}

//Fill type-info
containsWith();
// 2 calls are needed to go from uninitialized -> pre-monomorphic -> monomorphic
containsWith();

%OptimizeFunctionOnNextCall(containsWith);
//The next call
containsWith();

//Check
printStatus(containsWith);
```

---

```
node --trace_opt --trace_deopt --allow-natives-syntax test.js
```

---

Also, please educate the users for the better - because I've met a lot of engineers recently that cited the previous results and tried to not use these language features at all, while most are now TurboFan optimized.

Thanks

**Comment by benjamingr** [comment]
The optimizations killers page is a wiki and it's open to edits. Please by all means feel free to update it.

**Comment by petkaantonov** [comment]
Unless turbofan is enabled by default I don't think it's relevant yet

**Comment by KenanSulayman** [comment]
It is enabled by default. At least in Node 5.

**Comment by petkaantonov** [comment]
Yea but according to https://arewefastyet.com/ "optimized by turbofan" isn't really saying anything

**Comment by petkaantonov** [comment]
So yea as Benjamin said it's just a wiki page that anyone can edit. However, for eval, with and for..of it should be noted that turbofan optimization isn't currently even close to crankshaft (according to arewefastyet) and those patterns that are only optimized by turbofan should still be avoided.
