### ISSUE TITLE
Promise._async._normalQueue seems full of undefined entries

### ISSUE THREAD

**Issue by mbroadst** [petkaantonov/bluebird#851]
Hi,
I'm running some benchmarks on an amqp module (https://github.com/noodlefrenzy/node-amqp10), where we use promises pretty generously and in this particular case one promise is created per message send. I'm sending 100k messages in this test, and when the corresponding messages have been received I call for a `global.gc()`, make a quick heapdump, and exit the process.

When I enter the dump into chrome's devtools the top entry is consistently in `Promise._async._normalQueue`, which I can confirm has 100003 entries in it (3 extra for the initial connect, setup of sender and receiver links, and disconnect), each with a value of `undefined`.

Am I doing something horribly wrong here? Is this a bug, or just my lack of understanding of what should be happening (perhaps I'm not waiting long enough for a drain to occur?). 

Thanks

**Comment by mbroadst** [comment]
just a little followup, I looked into the draining and thought perhaps I could add a timeout before exiting to ensure it was empty (as well as trying an explicit call to `_drainQueues`) - but that didn't seem to do anything.

**Comment by benjamingr** [comment]
Bluebird's queue is not a regular array (that'd be inefficient). It resizes as it needs to grow and otherwise avoids allocation and deallocation as much as it can (by placing `undefined` instead of actually resizing again).

The assumption is that if you need 100K items once you'll likely need 100K items again - so it doesn't "shrink". If you want you can explicitly resize it - but I wouldn't. 

See the implementation here: https://github.com/petkaantonov/bluebird/blob/master/src/queue.js

**Comment by petkaantonov** [comment]
Even if you shrink array I'm pretty sure the backing storage is not shrinked anyway

**Comment by mbroadst** [comment]
@benjamingr Okay cool, so this is indeed a false positive for a leak, that answers my immediate question thank you.

I had assumed after <some time> it would reduce though? I mean imagine this as a service coordinating e.g. 200k nodes on the network somewhere. I send out 100k messages in a short period of time due to a storm of requests, and bluebird creates 100k entries in its queue, and there is no more communication for the rest of the day - do I continue to pay the memory penalty all day? (this admittedly is incredibly small, but just for the sake of discussion).

**Comment by benjamingr** [comment]
> do I continue to pay the memory penalty all day? 

Yes, and like you said - it is indeed incredibly small compared to the other overheads you pay for in that scenario anyway.

Cheers.
