### ISSUE TITLE
nested rejects

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#856]
This is just a question about something I'm trying to understand:

**Why nested rejects work differently from nested resolve operations?**

If we execute a nested resolve operation like this:

```javascript
promise.resolve(promise.resolve("nested"))
    .then(function (data) {
        console.log(data);
    });
```
we get the expected output:
```
nested
```
But if we execute a nested reject operation:

```javascript
promise.reject(promise.reject("nested"))
    .catch(function (error) {
        console.log(error);
    });
```
then the output is:
```
{ _bitField : 18087936, _fulfillmentHandler0 : 'nested', _rejectionHandler0 : undefined, _promise0 : undefined, _receiver0 : undefined }
```

I have looked through the [promise specification](https://promisesaplus.com/), and couldn't find any contradiction to this, hence the question.

**Comment by benjamingr** [comment]
I'm not sure why you're asking support questions here again, let alone ones that have nothing to do with bluebird and apply equally as much to any other spec-conforming promise libraries.

Anyway, `Promise.resolve` and `Promise.reject` are not a part of Promises/A+ (they're a part of a different spec), let's look at the ES2015 spec: [`Promise.reject`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise.reject) and [`Promise.resolve`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise.resolve) both delegate to the semantics of the resolve/reject semantics of the promise constructor (though promiseCapability).

Promise Reject just [calls RejectPromise](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise-reject-functions) which just sets the rejection value of the result.

Promise Resolve on the other hand [does a lot more](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise-resolve-functions), namely it checks if the return value has a `then` method and performs `Perform EnqueueJob ("PromiseJobs", PromiseResolveThenableJob, «‍promise, resolution, thenAction»)` which means "recursively assimilate the promise passed in".

In the future, please prefer asking questions in the appropriate support channels. This is not the first time I've asked you to do this - time spent answering them is time not spent on bugs. Sorry for the tone.
