### ISSUE TITLE
New warnings should indicate origin

### ISSUE THREAD

**Issue by florian-rossiaud** [petkaantonov/bluebird#861]
The new warnings introduces by bluebird 3 are quite handy to avoid bugs, but the error they refer to can be quite hard to pinpoint in large codebases:

    Warning: a promise was created in a  handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:367:17)

In my case this was due to the use of old-style callbacks that didn't return anything, but maybe Bluebird could somewhat use the longStackTrace mechanism to indicate the origin of the error to facilitate debugging.

**Comment by petkaantonov** [comment]
There should be a long stack trace as this warning is not even enabled if long stack traces are not enabled

**Comment by florian-rossiaud** [comment]
Long stack traces are enable but I go the error above. 

My bluebird configuration:

```js
Promise.config({
    warnings: true,
    longStackTraces: true,
})
```

**Comment by florian-rossiaud** [comment]
This code can reproduce the error:

```js
var Promise = require('bluebird');

Promise.config({
    warnings: true,
    longStackTraces: true,
});

Promise.resolve()
    .then(function () {
        Promise.resolve();
    })
;
```

This warning show up:

```
Warning: a promise was created in a  handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:367:17)

```

**Comment by petkaantonov** [comment]
Thanks, I'll look into it

**Comment by petkaantonov** [comment]
This was actually bug with Promise.resolve rather than the warning system
