### ISSUE TITLE
Global variable name

### ISSUE THREAD

**Issue by perrin4869** [petkaantonov/bluebird#864]
I was just wondering, is it acceptable to use
```
var Promise = require('bluebird');
```
since `Promise` is a global variable in ES6 and linters like jshint complain about it (as discussed here: https://github.com/jshint/jshint/issues/1747)
I know you can make jshint shut up about it, but maybe there is a better solution? Are there any plans to set a new standard in the documents, samples, etc?

**Comment by petkaantonov** [comment]
If it's a local variable, the linters are wrong to complain about it. Builtins or standard globals don't have magical powers to overwrite your local variables. I would not e.g. try to think another name for an `Event` object just because there is also a standard global called `Event`.
