### ISSUE TITLE
Question about turning on cancellation

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [petkaantonov/bluebird#865]
If I include a module that wants to turn on cancellation after I have already made promises without enabling cancellation, Bluebird throws an error telling me that I should have turned on cancellation before I made any promises and that it can't be done anymore. I am therefore forced to turn on cancellation in my own code before I do anything else even though I believe I shouldn't care about it. The module itself may never need to be included.

Without going into the specifics of what code I have written, what is the proper behavior for a module that needs cancellation (or for the app requiring it)? Should I always require all of the modules I may need later? Should the module require a fresh new copy of Bluebird by manipulating Node's cache? Can I check in some way if cancellation can be enabled and manage without it if it can't?

Thanks in advance and sorry if n00bish.

**Comment by petkaantonov** [comment]
The module should use their own bluebird instance http://bluebirdjs.com/docs/features.html#scoped-prototypes

**Comment by MySidesTheyAreGone** [comment]
Thanks!
