### ISSUE TITLE
Load bluebird library on docs site

### ISSUE THREAD

**Issue by cspotcode** [petkaantonov/bluebird#866]
I like opening up my browser DevTools and playing around with a library while I'm reading the docs.  [bluebirdjs.com](http://bluebirdjs.com) doesn't have a `<script src="bluebird.js"></script>`, however, so I can't do that.

**Comment by nickclaw** [comment]
Whoa, I coincidentally thought the same thing half an hour ago #868. Great minds think alike?

**Comment by cspotcode** [comment]
Wow, good timing.  I'll close this issue since your PR is better.
