### ISSUE TITLE
Documentation issue: Promise.using

### ISSUE THREAD

**Issue by oliversalzburg** [petkaantonov/bluebird#874]
The [second paragraph](http://bluebirdjs.com/docs/api/promise.using.html) looks incomplete:

> Here is a simple example ` [has been defined] to return a proper undefined))

I would have sent a PR, but I don't know what the line is supposed to say. It's not a formatting issue.

**Comment by petkaantonov** [comment]
It's probably a bug in the documentation migration script that I used to migrate the page from 2.0 documentation.

It's probably supposed to say that the `getConnection()` has been defined to return a proper `Disposer` object

**Comment by Arnavion** [comment]
Also on http://bluebirdjs.com/docs/api/resource-management.html - "We can do better, retaining concurrency and not leaking resources, by using undefined".

https://web.archive.org/web/20150811102329/https://github.com/petkaantonov/bluebird/blob/master/API.md said "by using using()"

**Comment by Coaxial** [comment]
The page at http://bluebirdjs.com/docs/api/resource-management.html still reads `We can do better, retaining concurrency and not leaking resources, by using undefined:`
