### ISSUE TITLE
Interfaces for `.promisify` and `.fromCallback` don't match

### ISSUE THREAD

**Issue by kevinburkeshyp** [petkaantonov/bluebird#878]
Both promisify and fromCallback take a function with a callback as an argument, and return you a Promise. However, the interfaces are different. In particular `fromCallback` requires you to define an anonymous function, and (possibly) call `.bind` or `.call` to apply the callback with the given arguments.

We were using `.promisify` everywhere (didn't realize it was meant for creating repeatable function definitions), we are trying to switch over but the interface for `.fromCallback` makes it easier to make a mistake, and our team has a lot of people who aren't very experienced with Javascript.

Here's the shim we use to call `.fromCallback` with the same signature as `.promisify`:

```javascript
/*
 * Returns a function that will wrap the given `fn` and return a Promise whose
 * behavior is governed by the callback behavior of the original `fn`.
 *
 * `fn` should always place the callback as the last available argument. The
 * first argument to the callback should always be an `Error` object or `null`
 * if there was no error.
 *
 * `target` is the `this` context for the callback function.
 *
 * If the callback has a single success value - e.g. `cb err, pickup` - the
 * returned Promise will resolve it as a single value. If the callback has
 * multiple return values - e.g. `cb err, pickup, driver` - the returned Promise
 * will resolve it as an array of values. Examples:
 *
 *   promisifyCb(pickup.getUser, pickup)().then(function(user) {
 *     # do something with the user...
 *   });
 *
 *   promisifyCb(DriverAssignment.assign, DriverAssignment)(pickup, driver).then(function(results) {
 *     pickup = results[0]
 *     driver = results[1]
 *   }
 *
 * Rejects with an error if the `fn` is not a function.
 */
module.exports = function(fn, target) {
  if (target === null || typeof target === "undefined") {
    target = {};
  }
  if (typeof fn !== 'function') {
    var err = new Error('promisifyCb: Please provide a function as the first argument');
    return function() {
      return Promise.reject(err);
    };
  }
  return function() {
    var argsWithoutCb = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
    return Promise.fromCallback(function(cb) {
      var args = Array.prototype.slice.call(argsWithoutCb).concat([cb]);
      return fn.apply(target, args);
    });
  };
};
```

We like it because there's no need for callers to mess around with `this` scopes or `.bind` or `.call` or `.apply` this way. Was wondering if you thought this was useful... maybe for a `.promisifyOnce` function ?

**Comment by kevinburkeshyp** [comment]
(I have tests for this as well!)

**Comment by benjamingr** [comment]
> We were using .promisify everywhere (didn't realize it was meant for creating repeatable function definitions), we are trying to switch over but the interface for .fromCallback makes it easier to make a mistake, and our team has a lot of people who aren't very experienced with Javascript.

Well, as a start the good solution is _probably_ to do promisifyAll once - it promisifies the prototype - that should normally be enough.

**Comment by kevinburkeshyp** [comment]
Oh! We were using it for stuff like 

driver = new Driver(); Promise.promisify(driver.assign, driver)(pickup)

I'm not sure that calling promisify on the prototype is feasible since we use the callback in some places and the promisified version in some places. But it sounds like this feature isn't a good fit

-kevin

**Comment by phpnode** [comment]
@kevinburkeshyp try this:
```js
Bluebird.promisifyAll(Driver.prototype);

let driver = new Driver();

driver.assignAsync().then(console.log);
```


`promisifyAll()` does not overwrite any existing methods, it adds additional methods with an `Async` suffix

**Comment by benjamingr** [comment]
Yes, you can still use the original functions like phpnode suggested. That'd be the good solution.

Promisify once and then stop worrying about it :) Bluebird's working assumption is that using promises should be hassle free and introduce as little overhead as possible
