### ISSUE TITLE
spurious Unhandled rejection warning?

### ISSUE THREAD

**Issue by dmansfield** [petkaantonov/bluebird#880]
This code
```
var Promise = require('bluebird');

function slowPromiseFactory() {
    return new Promise(function(resolve) {
        setTimeout(resolve, 1000);
    });
}

// return a new function that when called returns a rejected Promise
function rejectingPromiseReturningFunctionFactory() {
    var p = Promise.reject('reject');
    return function() {
        return p;
    };
}

var x = { doit: rejectingPromiseReturningFunctionFactory() };

slowPromiseFactory().then(function() {
    return x.doit();
})
.then(function() {
    console.log('wont get here');
})
.catch(function(err) {
    console.log('got the error: '+err);
});

console.log('sync portion complete');
```

The rejected promise is created but never attached to anything until the async portion of the script resumes after the timeout.  Obviously this is a contrived case, but is there specifically a no-no being committed here?  This could obviously be changed to create the promise when the function created by the factory is called instead of when the factory method is called, but that's the point.

**Comment by petkaantonov** [comment]
If a promise is rejected before a catch handler is added then error will be reported because there is no way to know if in future someone will add a catch handler or not.

If you know you are going to add a catch handler later like in this code, you can simply use [.suppressUnhandledRejections()](http://bluebirdjs.com/docs/api/suppressunhandledrejections.html)

```js
function rejectingPromiseReturningFunctionFactory() {
    var p = Promise.reject('reject');
    p.suppressUnhandledRejections()
    return function() {
        return p;
    };
}
```

**Comment by petkaantonov** [comment]
Also if someone will later chain the promise and forgot a catch handler, they will still get unhanded rejection report correctly despite the suppression as the suppression is only for this immediate promise.
