### ISSUE TITLE
Travis Fix

### ISSUE THREAD

**Issue by vitaly-t** [petkaantonov/bluebird#886]
@petkaantonov All of the PR-s submitted keep failing, because your Travis integration is obsolete.

I have submitted [the update for your Travis integration](https://github.com/petkaantonov/bluebird/pull/883), which is the only one successful now. If you accept it, all the new PR-s should build successfully, and your project's build status will show as success also.

It will make things a lot easier when evaluating new PR-s.

**Comment by vitaly-t** [comment]
The PR has been merged.

**Comment by benjamingr** [comment]
Thanks a lot :)

**Comment by vitaly-t** [comment]
@benjamingr You are welcome. And as was suggested to Petka, the owner account can re-run tests on all the PR-s that previously failed, to re-validate them ;)
