### ISSUE TITLE
Promise.longStackTraces missing from documentation index

### ISSUE THREAD

**Issue by joepie91** [petkaantonov/bluebird#888]
The page about the [longStackTraces feature](http://bluebirdjs.com/docs/api/promise.longstacktraces.html) appears to be missing from the API index.

As I'm not sure where it's supposed to go, I'm filing this as an issue rather than a PR :)

**Comment by tyscorp** [comment]
[Promise.config](http://bluebirdjs.com/docs/api/promise.config.html)
