### ISSUE TITLE
Feature Request : waitFor

### ISSUE THREAD

**Issue by SimonSchick** [petkaantonov/bluebird#890]
I recently needed to write a piece of code that would wait for a condition to to become true and then resolve a value, I couldn't find a function in bluebird that covers this particular case so I wrote this.
```javascript
function waitFor(condition, value = condition, interval = 20) {
	return new Promise(resolve => {
		var int = setInterval(() => {
			var isDone = condition();
			if(isDone) {
				if(condition === value) {
					resolve(isDone);
				} else {
					resolve(value(isDone));
				}
				return clearInterval(int);
			}
		}, interval);
	});
}
```

This kind of functionality is useful for polling so I thought it might make a good addition to bluebird.

If there already is a way to do this in a similarily compact manner, please tell me.

**Comment by spion** [comment]
```js
function waitFor(condition, interval = 20) {
  return Promise.delay(interval).then(condition)
    .then(result => result === true || waitFor(condition, interval))
}

waitFor(_ => fn() === value).then(_ => {
 // code here
});
```

Not sure if its general enough to become a part of the core API though...

**Comment by spion** [comment]
Perhaps `whilst` would help?

```js
function waitFor(condition, delay = 10) {
  return Promise.whilst(() => condition() != value, () => Promise.delay(delay))
}
```

**Comment by SimonSchick** [comment]
I cannot find any documentation for whilst, can you link me to that?

Also one important aspects of my function is that the the resolved value does not have to be the resolved value and it doesn't create huge promise chains.

**Comment by spion** [comment]
We don't have `whilist` at the moment, however its slightly more general than `waitFor` so I think it may be better to include instead

In the above example even though the chain is nested, bluebird doesn't leak memory - the old promise references aren't being kept

**Comment by SimonSchick** [comment]
Sorry I wasn't implying memory leaks but general performance.

whilst would be an interesting addition tho.

**Comment by petkaantonov** [comment]
```js
function waitFor(condition, interval = 20) {
  return Promise.delay(interval).
    then(condition).
    then(result => result === true || waitFor(condition, interval))
}
```

Does not cause a huge promise chain in bluebird since 2.7 or so. There is an issue with promise spec that bluebird is "violating" in order to handle this scenario without creating huge chain or memory leak.
