### ISSUE TITLE
promise.timeout() doesn't cancel the original promise after the timeout

### ISSUE THREAD

**Issue by spion** [petkaantonov/bluebird#891]
With bluebird 2.x cancellable promises were being cancelled by `timeout()` however in 3.x that doen't happen even if cancellation is (globally) enabled. Is this intentional?

**Comment by benjamingr** [comment]
I hope not.

**Comment by spion** [comment]
To reproduce:

var Promise = require('bluebird')

bb2/cancel-bug.js
```js
var Promise = require('bluebird')
var assert = require('assert')

function assertAfter(t, str) {
  return Promise.delay(t)
    .cancellable()
    .then(_ => console.error(str))
}

var p1 = assertAfter(1000, "Not cancelled");
var p2 = p1.timeout(500).catch(_ => _)
```

vs

bb3/bug.js
```js
var Promise = require('bluebird')
var assert = require('assert')

Promise.config({cancellation: true})

function assertAfter(t, str) {
  return Promise.delay(t)
    .then(_ => console.error(str))
}

var p1 = assertAfter(1000, "Not cancelled");
var p2 = p1.timeout(500).catch(_ => _)
```


`node bb2/cancel-bug` has no output, while `node bb3/cancel-bug` prints: 

    Not cancelled

**Comment by petkaantonov** [comment]
Cancellation is not rejection anymore, so how would it even work?

**Comment by bergus** [comment]
@petkaantonov: cancelling `p1` should prevent the `_ => console.error(…)` callback from occurring and cancel the `Promise.delay` promise, shouldn't it?

**Comment by petkaantonov** [comment]
what does that have to do with timeout whose purpose is to reject with a cancellationerror?

**Comment by spion** [comment]
@petkaantonov What I meant is that .timeout() used to not only reject things, but called `.cancel()` on the promise, resulting with rejections propagating upstream. Not sure if the current `.timeout()` does that anymore, but I'll look into it and maybe send a PR of what I expect the behaviour to be.

**Comment by spion** [comment]
This is the PR above. Don't know if it makes sense to do it now as it may be considered a breaking change. Alternatively it may be considered a bugfix :grinning:

**Comment by spion** [comment]
Example use case (assumes cancellation enabled)

```js
function whilist(condition, body, value = undefined) {
  if (condition()) body().then(val => whilist(condition, body, val))
  else return Promise.resolve();
}

var waitButton = whilist(_ => !$('.button').length, _ => Promise.delay(100))
waitButton.timeout(10000, "Page failed to load"); // should end `whilist` loop
```

**Comment by bergus** [comment]
> Is this in conflict with the new cancellation semantics?

No, I'd say it's totally in line with the new cancellation semantics. One might even consider cancelling with the `TimeoutError` instead of a `CancellationError`.

The only thing I'm not so sure about is whether `parent.cancel()` (in the PR) is enough. Conceptionally, you'd have to unsubscribe the handlers on `parent` (which were supposed to resolve the timeout promise that is now rejected) to make the cancellation work.

**Comment by petkaantonov** [comment]
> No, I'd say it's totally in line with the new cancellation semantics. One might even consider cancelling with the TimeoutError instead of a CancellationError.

You cannot cancel *with* anything, cancellation is not rejection anymore.

**Comment by spion** [comment]
@petkaantonov you can reject the derived promise but also cancel the parent one. If cancelling the parent is not a good idea due to other promises being potentially derived from it, e.g.

This should not cancel p2 and p3 or prevent the logging (multiple derived promises):
```js
var Promise = require('bluebird');
Promise.config({
  cancellation: true
});

var p1 = Promise.delay(100)
  .then(_ => console.log("p1"))

var p2 = p1.delay(200).then(_ => console.log("p2"))
var p3 = p1.delay(300).then(_ => console.log("p3"))

p1.timeout(50) 
```

This should cancel the console.log and reject both p2 and p3
```js
var Promise = require('bluebird');
Promise.config({
  cancellation: true
});

var p1 = Promise.delay(100)
  .then(_ => console.log("p1")).timeout(50)

var p2 = p1.delay(200).then(_ => console.log("p2"))
var p3 = p1.delay(300).then(_ => console.log("p3"))
```

then creating a parent/child pair within timeout then cancelling the parent but returning the child should fix that

**Comment by bergus** [comment]
@petkaantonov 
> You cannot cancel with anything, cancellation is not rejection anymore.

Well, it is to those callbacks that still observe cancellation, isn't it? I mean things like `onCancel` handlers, `finally`, and late subscribers. And I would think it's ok if those see a `TimeoutError` instead of a `CancellationError`.

@spion 
>  If cancelling the parent is not a good idea due to other promises being potentially derived from it

That's fine, `cancel()` should automatically handle that.

**Comment by spion** [comment]
@bergus it doesn't because the original promise gets cancelled, and therefore so will the other derived promises. Which is why I suggested creating a parent and a child (or rather, a child and a grand-child), cancelling the child and rejecting the grandchild.

**Comment by spion** [comment]
Updated PR to address last point.

**Comment by bergus** [comment]
Ah, I see, that's what `parent = this.then()` is good for.
