### ISSUE TITLE
Managing arguments need explanation on arguments use in es2015

### ISSUE THREAD

**Issue by onemen** [petkaantonov/bluebird#894]
Regarding re-assign:
```
function reAssignParam(a, b_) {
    var b = b_;
    //unlike b_, b can safely be reassigned
    if (arguments.length < 2) b = 5;
}
```
We can avoid using arguments:
```
function reAssignParam_es6(a, ...args) {
    var b = args[0];
    if (!args.length) b = 5;
}
```
Regarding leaks:
```
function leaksArguments2() {
    var args = [].slice.call(arguments);
}
```
is it safe to use:
```
var args = Array.from(arguments);
```

**Comment by benjamingr** [comment]
What?

**Comment by onemen** [comment]
In https://github.com/petkaantonov/bluebird/wiki/Optimization-killers
Managing arguments section

Do you think it needs some explanation regarding managing arguments with es6 examples

**Comment by benjamingr** [comment]
As far as I know, v8 doesn't support it in the stable branch yet anyway. 

When we get a stable version - then the page can be updated. 

It's a wiki anyway.
