### ISSUE TITLE
react native rejections handling

### ISSUE THREAD

**Issue by steida** [petkaantonov/bluebird#896]
http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events

I tried all examples, no success.

**Comment by grabbou** [comment]
The following works normally in my apps:
'''
if (__DEV__) {
  Promise.longStackTraces();
  Promise.onPossiblyUnhandledRejection(error => {
    console.log('Unhandled rejection');
    console.log(error);
  });
}
'''

**Comment by benjamingr** [comment]
@grabbou Please prefer `.config` to `longStackTraces` in bluebird 3. 

I don't have a RN environment handy - I'll look into it soon.

**Comment by grabbou** [comment]
Okey, thanks!

**Comment by benjamingr** [comment]
@grabbou can you please see if this happens with the global `unhandledrejection` event?

**Comment by steida** [comment]
Which syntax do you mean?
Btw, this code:

```js
const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        reject(new Error('fok'))
      }, 1000);
    });
    p.then((value) => {
      console.log(value);
    });
```

Now produces this beautiful yellow warning:

![screen shot 2016-01-10 at 01 08 53](https://cloud.githubusercontent.com/assets/66249/12219154/bd47e09a-b736-11e5-8fc3-5c76730d0662.png)

**Comment by steida** [comment]
So I think it fine right now. Btw, Promise polyfilled by React Native doesn't do that, but bluebird does. How you managed it?
