### ISSUE TITLE
Bluebird 3.x performance in webpack

### ISSUE THREAD

**Issue by suprememoocow** [petkaantonov/bluebird#897]
This issue seems totally bizarre to me. I'm not sure whether to file it under webpack or Bluebird, but since it may be affecting other bluebird users I'll file it here.

I've been finding that Bluebird's performance in the browser has been pretty shoddy since I upgraded to bluebird 3. 

In an effort to diagnose the problem, I started conducting some tests here: https://github.com/suprememoocow/bluebird-webpack-perf

The results are strange to say the least, but here's some of what I'm seeing:

* A simple `Promise.reduce`  with an array of 100 values takes 2ms when run in Chrome 64bit on OSX. The exact same code, when processed through webpack takes 500ms. 

* You can compare the implementations here:
https://github.com/suprememoocow/bluebird-webpack-perf/blob/master/bluebird-no-webpack.html
and
https://github.com/suprememoocow/bluebird-webpack-perf/blob/master/bluebird-with-webpack.js

* In an effort to isolate the problem, I've minimized the processing that webpack does with the following settings:

```js
      module: {
        noParse: [
          /bluebird\/js\/browser\/bluebird\.js/
        ]
      },
      node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: false,
        __dirname: false,
        setImmediate: false
      },
```

* Changing these settings hasn't helped.

* Downgrading to Bluebird 2.x.x fixes the problem.

I'll conduct some further tests and see if I can get to the bottom of the problem

**Comment by suprememoocow** [comment]
More strange results:

The problem **does not** occur in Firefox 42.0 or Safari 9.0.1 on OSX. It is occurring in Chrome 47.0.2526.73 beta (64-bit) and Chrome Canary Version 49.0.2578.0 canary (64-bit)

**Comment by suprememoocow** [comment]
Doing some profiling I noticed that bluebird is capturing long stack traces even though I have 
```js
Promise.config({
    warnings: false,
    longStackTraces: false, // <-- Turn off long stack traces
    cancellation: true
  });
```
This would explain why Chrome is getting the performance hit, but not Firefox or Safari.

Upon further investigation, it looks like the `__DEBUG__` constant is being set to `true` for the build of `js/browser/bluebird.js` if you compare:

```
js/browser/bluebird.js:658:var debugging =!!(true || util.env("BLUEBIRD_DEBUG") ||
```

to the original source, here: https://github.com/petkaantonov/bluebird/blob/master/src/debuggability.js#L18

**Comment by benjamingr** [comment]
I'm sorry - but what scenario do you have in client side code when you'd rather have performance over long stack traces?

**Comment by suprememoocow** [comment]
@benjamingr when running in production.

The minified version of the browser build has `__DEBUG__` set to false and that's why it doesn't suffer from the same performance problem. When you're using Webpack or Browserify with npm however, you use the non-minified version, so `__DEBUG__` is set to true. 

Obviously, I can still set `longStackTraces` to true using `Promise.config`, but that's my prerogative as an Bluebird user and I'll enable it when running in development mode. As things stand, `Promise.config({ longStackTraces: false })` has no effect when using Bluebird via Webpack - it's always `true` whether you want it to be or not.

The reason I started investigating this bug is that I'm writing a bluebird based Bayeux client for Gitter.im. I noticed that compared to the old Bayeux client, it was noticeably and quite obviously slower (for example, when switching rooms on Gitter). On investigation, this seems to be the problem.

As a practical example of how this affects performance, I was previously using `Promise.reduce` to pass incoming and outgoing messages through a set of extensions. For a small number of extensions, this was adding more than 500ms to the time it took for a message to pass through the client onto the transport. I worked around this issue by [removing `Promise.reduce`](https://github.com/gitterHQ/halley/commit/65a682b3c7e83e64ae08bcba1f5d788ec1794392#diff-e16533e9c28a315f726b8b2933ba193aR29) but this hack wouldn't be required if bluebird was running at full-speed.

In the example repo above, having this turned on slows things down by about ~250 times in Chrome.

Bluebird is all about performance and it's crazy fast, so why not let application developers choose when to hobble it with long stack traces?

a

**Comment by petkaantonov** [comment]
with browserify and webpack youre supposed to use the npm module

the downloaded file is for script tag users

**Comment by suprememoocow** [comment]
@petkaantonov, I am using the npm module, which references `js/browser/browser.js`, which is currently built with `__DEBUG__` set to `true`. #898 is my attempt at changing this.

References:
[`require('bluebird')`](https://github.com/suprememoocow/bluebird-webpack-perf/blob/master/bluebird-with-webpack.js#L1)
[`package.json`](https://github.com/suprememoocow/bluebird-webpack-perf/blob/master/package.json#L5)
