### ISSUE TITLE
eval after return in toFastProperties

### ISSUE THREAD

**Issue by nazrhyn** [petkaantonov/bluebird#899]
I just noticed Firefox throwing this error in the console on [your site](http://bluebirdjs.com/docs/api-reference.html) where I was testing `coroutine`:

> unreachable code after return statement

I don't usually use Bluebird in the browser, so I wouldn't normally have seen this; not sure if it matters! Thanks for such a great library; your new documentation site is _awesome_.

([source](https://github.com/petkaantonov/bluebird/blob/7a39370ba1b98da0aaef1fa9d85b2fd5daaba4ee/src/util.js#L196))
```js
function toFastProperties(obj) {
    /*jshint -W027,-W055,-W031*/
    function FakeConstructor() {}
    FakeConstructor.prototype = obj;
    var l = 8;
    while (l--) new FakeConstructor();
    ASSERT("%HasFastProperties", true, obj);
    return obj;
    eval(obj);
}
```

**Comment by benjamingr** [comment]
http://stackoverflow.com/q/24987896/1348195

Thanks for the report.

**Comment by nazrhyn** [comment]
Ah, cool; that's quite an interesting optimization. Perhaps it should be in the documentation, or a link to that SO question in a comment in the source? Might help avoid future reports.

Thanks!

**Comment by benjamingr** [comment]
Someone started working on a PR a week ago at https://github.com/petkaantonov/bluebird/pull/884 but Petka hasn't responded yet with his opinion about the matter and it's not a high priority issue.
