### ISSUE TITLE
docs: possible missing anti-pattern?

### ISSUE THREAD

**Issue by clayzermk1** [petkaantonov/bluebird#908]
http://bluebirdjs.com/docs/api/new-promise.html has a note near the top that says: "Note: See explicit construction anti-pattern before creating promises yourself".

The linked page, http://bluebirdjs.com/docs/anti-patterns.html, does not have such an anti-pattern.

I'd guess that either the note is out of date or there is a missing anti pattern. The wiki page history doesn't look like it's had it for the last couple years so maybe the latter?

Thanks for all your time and such a great library!

**Comment by bergus** [comment]
The [explicit promise construction antipattern](http://stackoverflow.com/q/23803743/1048572) is basically a hyperonym for the deferred antipattern and the `Promise` constructor antipattern - which are two sides of the same coin. Yeah, looks like this needs an update.

**Comment by petkaantonov** [comment]
You can submit a patch by clicking the "edit on github"  button on the top right corner

**Comment by benjamingr** [comment]
Fixed in #2637906 , needs a rebuild of the docs.
