### ISSUE TITLE
Allow to report progress without using deferreds

### ISSUE THREAD

**Issue by gaearon** [petkaantonov/bluebird#91]
Bluebird encourages to ditch `defer` in favor of `Promise` constructor but this is impossible in our case because we want to report progress which is _only_ available from deferreds.

This would be solved by making `Promise` constructor's `resolver` accept a third argument, `progress: Function`.

**Comment by samal84** [comment]
@benjamingr I assume this is the place in the API guide you are referencing: http://bluebirdjs.com/docs/api/progression-migration.html
