### ISSUE TITLE
Wiki: updated error message for Error: expecting an array...

### ISSUE THREAD

**Issue by timeimp** [petkaantonov/bluebird#910]
I have made some edits on my own fork of the Error: expecting an array, a promise or a tenable wiki page. The wiki can be edited by anyone, but I wanted to check the edit is OK: https://github.com/timeimp/bluebird/wiki/Error:-expecting-an-array,-a-promise-or-a-thenable-(v1.1)

**Comment by benjamingr** [comment]
That looks good to me, it's not promise specific but it sounds common enough people will find it useful - feel free to make the relevant edits in the wiki. Thanks.

**Comment by benjamingr** [comment]
Also, make the edits here: http://bluebirdjs.com/docs/error-explanations.html

**Comment by benjamingr** [comment]
ping @timeimp

**Comment by timeimp** [comment]
pong @benjamingr

**Comment by benjamingr** [comment]
@timeimp still interested in following through with a PR?

**Comment by timeimp** [comment]
Yep - I'll have one written up this weekend ready for review.

**Comment by benjamingr** [comment]
Ping @timeimp

**Comment by timeimp** [comment]
@benjamingr I was summoned?

**Comment by benjamingr** [comment]
@timeimp 

> Yep - I'll have one written up this weekend ready for review.

:point_up_2:

**Comment by timeimp** [comment]
@benjamingr :O I had a PR written up and everything about 5 days after I posted this.... let me investigate.

**Comment by timeimp** [comment]
@benjamingr found it: https://github.com/petkaantonov/bluebird/pull/953

**Comment by benjamingr** [comment]
Oh cool, looks like it was already merged. Thanks!
