### ISSUE TITLE
expecting an array or an iterable object but got [object Null] with Mongoose 4.3.1

### ISSUE THREAD

**Issue by ndjordjevic** [petkaantonov/bluebird#911]
Hi,

I'm using mongoose with bluebird and upgrading to v3 causes this exception, even with multiArgs set to true:

```var mongoose = require('bluebird').promisifyAll(require('mongoose'), {multiArgs: true});```
... in some mocha:
```return user.saveAsync()
        .spread(function(u) {
          return u.authenticate('password');
        }).should.eventually.be.true;```

**Comment by grantila** [comment]
What are you spreading? That's your bug.

**Comment by ndjordjevic** [comment]
Hmm, it could be. I'm not JS expert. The code came from angular fullstack generator and was working fine with bluebird 2.10.2

**Comment by petkaantonov** [comment]
mongoose has possibly been already promisified, which means this promisify call will not do anything. Note that promisification adds methods to the classes, there is no need to assign the result.

**Comment by ndjordjevic** [comment]
yeah, mongoose async methods already returns a promise:
http://mongoosejs.com/docs/promises.html
however you can tell mongoose to use bluebird as you wish.
