### ISSUE TITLE
setTimeout is used as scheduler in latest Chrome

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird#915]
Latest Chrome ~~does not have window.navigator.standalone defined (see https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js#L26)~~ always has function chrome.loadTimes, because of this hasDevTools always returns true in Chrome. It looks like undesired behavior.

**Comment by benjamingr** [comment]
That part is inside a `!`..

**Comment by benjamingr** [comment]
You're right http://jsfiddle.net/10o58rup/ - it seems to be using setTimeout.

**Comment by benjamingr** [comment]
Hmm, `((typeof MutationObserver !== "undefined") &&
          !(typeof window !== "undefined" &&
            window.navigator &&
            window.navigator.standalone))` evaluates to `true` in latest chrome. Odd...

**Comment by lextiz** [comment]
Maybe it not the case when bluebird is loaded?

**Comment by benjamingr** [comment]
Unlikely - http://jsfiddle.net/ufpLxvqn/

I think this is not a bug, bluebird resets the scheduler to setTimeout if you have the devtools open so async stack traces correctly work.

**Comment by lextiz** [comment]
Yes. Will update when finished.

**Comment by lextiz** [comment]
I have reproduced this with debugger closed: closed all debugger instances, closed all chrome processes, opened jsfiddle link, I see setTimeout there. Do you see MutationObserver implementation instead?

**Comment by lextiz** [comment]
I see that (typeof chrome !== "undefined" && chrome && typeof chrome.loadTimes === "function") evaluates to true when debugger tools are closed

**Comment by lextiz** [comment]
Tried even to reboot, it still evaluates to true. What is your Chrome version? I have 47.0.2526.80 m.

**Comment by petkaantonov** [comment]
Devtools doesn't matter, it will still use normal scheduler. Just without trampoline.

**Comment by benjamingr** [comment]
Petka step through the code, it uses the regular scheduled and then overrides it with setTimeout

**Comment by petkaantonov** [comment]
Can you link to line?

**Comment by lextiz** [comment]
This is overriding: https://github.com/petkaantonov/bluebird/blob/aefda6abbda2e7f146b51c18daaa45dc0f17d89b/src/async.js#L91
It happens when hasDevTools returns true. In current version of Chrome it always returns true, because chrome.loadTimes is a function.

**Comment by petkaantonov** [comment]
Ah yes static scheduler like mutation observer cannot be used without trampoline

**Comment by petkaantonov** [comment]
This is because async stack traces work only when trampoline is not used, the detection only detects if it's chrome, not if DevTools are open or if async stack traces are enabled

**Comment by petkaantonov** [comment]
This can be fixed by using 2 mutationobservers to get: working devtools async stack traces,fast performing trampoline and latency not affected by tab inactivity. :+1: demo: https://jsfiddle.net/yu7tx5em/4/

**Comment by lextiz** [comment]
Thanks!
