### ISSUE TITLE
Feature request: add automatic test for performance regression to CI

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird#916]

**Comment by benjamingr** [comment]
@vitaly-t if you're interested in this - I recall you have CI experience

**Comment by vitaly-t** [comment]
@benjamingr All projects I did have both Travis CI and Coveralls integration. But all performance tests that I did were to run locally only.

This feature request implies that there is a way to integrate performance output into the Travis. It souns reasonable, but I have never done that.

**Comment by benjamingr** [comment]
@vitaly-t well, if you want this issue is up to grabs.

**Comment by petkaantonov** [comment]
I have planned readding browsers to CI when I get good chunk of free time again
