### ISSUE TITLE
Feature request: add configurable option to workaround promises slowdown in inactive tab

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird#917]
Asynchronous code executions are artificially slowed down in inactive tab of modern browsers (http://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs), in Q for example slow down does not happen because it uses the MessageChannel based scheduler (http://www.nonblocking.io/2011/06/windownexttick.html). This kind of scheduler does not look good for some reasons, but it solves the slowdown issue. While the slow down in inactive tabs exists by design there are some use cases, that suffer from this.

Proposal for configurable feature (relevant for browsers only):
1) Register to "onblur" and "onfocus" events
2) On blur: set scheduler to MessageChannel based scheduler (https://github.com/kriskowal/q/blob/v1/q.js#L211)
3) After next drainQueues after "onfocus" event finished (and queues are empty) set scheduler back to default one

Use case (replace commented lines to compare):
```html
<html>
<head>
<!--script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/q.js/1.4.1/q.js"></script-->
<script language="javascript" src="https://cdn.jsdelivr.net/bluebird/latest/bluebird.js"></script>
<script language="javascript">
window.test = function () {
  window.open("about:blank");
  var start = Date.now();
  //var prom = Q("");
  var prom = Promise.resolve("");
  for (var i = 0; i < 10; i++) {
    prom = prom.then(function() {console.log(Math.random());});
  }
  prom.then(function() {
    console.log(Date.now()-start);
  });
}
</script>
</head>
<body>
<button onclick="window.test()">Click me</button>
</body>
</html>
```

**Comment by lextiz** [comment]
https://github.com/petkaantonov/bluebird/issues/913

**Comment by benjamingr** [comment]
@petkaantonov what about using asap as the default scheduler?

**Comment by petkaantonov** [comment]
This is exactly what  setScheduler does

**Comment by lextiz** [comment]
As far as I understand MessageChannel based scheduler is not good: it is not recognized by Chrome debugger as async operation and encourages writing error prone code, because it executes promises in order of their appearance in code, so it hides broken promises chains and more bugs. @petkaantonov Is this possible to add _onAfterQueuesDrained hook, so this feature could be safely implemented by library consumer?

**Comment by lextiz** [comment]
What is the reason you do not want this feature?

**Comment by petkaantonov** [comment]
Why cant you use setScheduler for this?

**Comment by petkaantonov** [comment]
The bug with using setTimeout is going to be fixed, any additional configuration can be done with setScheduler

**Comment by lextiz** [comment]
Ok, now I see that MutationObserver does not have the background tab limitation. Great.
