### ISSUE TITLE
What is Promise.pending()?

### ISSUE THREAD

**Issue by ibc** [petkaantonov/bluebird#919]
No idea what the following example extracted from the doc means:

```js
function applicationFunction(arg1) {
    var deferred = Promise.pending(); //Or Q.defer() in Q
    libraryFunction(arg1, function (err, value) {
        if (err) {
            deferred.reject(err);
        } else {
            deferred.fulfill(value);
        }
    });
    return deferred.promise;
}
```

* What is `Promise.pending()`? what does it return? It seems it returns:

```js
{ promise:
   Promise {
     _bitField: 0,
     _fulfillmentHandler0: undefined,
     _rejectionHandler0: undefined,
     _promise0: undefined,
     _receiver0: undefined },
  resolve: [Function: deferResolve],
  reject: [Function: deferReject] }
```

but that is not documented.

**Comment by ibc** [comment]
Also, there is no `fulfill()` function in the returned object.

**Comment by petkaantonov** [comment]
This looks like very old documentation(from v0 and v1 era) , if this is in up-to-date docs then that needs to be fixed.

**Comment by ibc** [comment]
It is: http://bluebirdjs.com/docs/anti-patterns.html#explicit-construction-anti-pattern

**Comment by benjamingr** [comment]
Fixing.

**Comment by ibc** [comment]
Nice, but... how am I supposed to check the new syntax in the [doc](http://bluebirdjs.com/docs/anti-patterns.html#the-deferred-anti-pattern)? :)

**Comment by vicfriedman** [comment]
hey @benjamingr - current docs still include `Promise.pending()` discussing when to use deferred:

```
//setTimeout that returns a promise
function delay(ms) {
    var deferred = Promise.pending();
    setTimeout(function(){
        deferred.fulfill();
    }, ms);
    return deferred.promise;
}
```

Running this code gives me `TypeError: undefined is not a function`. 

I'm new to promises and Bluebird, just wanted some clarification! Thanks!

**Comment by benjamingr** [comment]
Hi @vicfriedman apologies - can you send me a link to the documentation showing this so it can be corrected?

The correct use would be to use `Promise.delay()` for timeouts and if we wanted to promisify a method not returning a `Promise` to use the promise constructor:

```js
function delay(ms) {
    return new Promise(function(resolve, reject) {
         setTimeout(function() { resolve(); }, ms);
    });
}
```

Or more compactly with modern syntax:

```js
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
```

**Comment by vicfriedman** [comment]
@benjamingr - no worries! 

Here's the [doc](http://bluebirdjs.com/docs/anti-patterns.html#explicit-construction-anti-pattern)

Thanks for the clarification!

**Comment by benjamingr** [comment]
Thanks, fixed there - @petkaantonov can you run a docs build?

**Comment by vicfriedman** [comment]
thanks for the quick response @benjamingr ! :)

**Comment by petkaantonov** [comment]
pushed

**Comment by cchamberlain** [comment]
Looks like wiki has dupe information that needs updating - https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns
