### ISSUE TITLE
Feature request: add optional pending promises number limitation

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird#923]
Helpful to identify misuse of promises: too many pending promises have chance of slowing down the UI.

**Comment by benjamingr** [comment]
You can literally create tens of thousands of promises on a modern machine before noticing a slow down. 

What's the use case?

**Comment by petkaantonov** [comment]
Also, isn't this possible from the monitor feature?

**Comment by bergus** [comment]
> What's the use case?

Probably the same as #918. Not that I would want either, but I guess the number of pending promises might be a more useful metric than the length of a chain.

**Comment by benjamingr** [comment]
I just want to point out I really appreciate @lextiz 's recent contributions to bluebird and I'm interested in getting more ideas for things that'd make debugging easier.

**Comment by lextiz** [comment]
It is not the same as 918: this one refers number of pending promises all over the system and 918 refers number of promises in single chain. Not implemented in monitor. I will answer regarding the use case later.

**Comment by lextiz** [comment]
Regarding the use case: promises themselves will not stuck the UI probably, but code inside the callbacks might do it. Number of pending promises could give you a good metric to issue a warning about  run time complexity of code.

**Comment by petkaantonov** [comment]
The monitor has "getPendingPromises" method, how cannot that be used to determine the amount of pending promises?

**Comment by lextiz** [comment]
The limit has to be checked for every new promise and getPendingPromises has O(n) runtime, so performance suffer. It is not supposed to be called frequently, just for debugging purposes.

**Comment by lextiz** [comment]
Also this capability could be enabled separately from monitoring with very little performance overhead.

**Comment by lextiz** [comment]
@benjamingr Thanks

**Comment by petkaantonov** [comment]
in that case monitoring api shouldn't be so inflexible, it could just fire events and the user can build whatever they want on top of that

**Comment by lextiz** [comment]
Should I add "Promise.monitor.onPromiseCreated" property to be assigned a handler to monitoring impl? Or, you mean firing DOM events?

**Comment by petkaantonov** [comment]
it should be the same as the rsvp monitoring api

**Comment by lextiz** [comment]
Do you mean on and off methods, to use it like Promise.on("_promiseCreated",handlerFunction)? I did not find here (http://inch-ci.org/github/tildeio/rsvp.js) any other API that could possibly be used for signing to "promise created" and "promise settled" events

**Comment by lextiz** [comment]
I think "promise life cycle event subscriptions" feature is not very much related to monitoring (only thing the have in common hook utility functions). I have submitted initial implementation to monitoring branch, for example, but I would like to take it to a new PR.

**Comment by petkaantonov** [comment]
It doesn't make sense to expose a very inflexible and minimal use api, when we can easily export the general api of events on top of which you can trivially implement getPendingPromises *and* pending promises number limitation. In your monitor implementation you are already firing events anyway.

**Comment by lextiz** [comment]
I have added the life cycle events implementation.
In case only the general APIs (on, off) are exposed library users would have to write all the monitoring and promises number limitation code themselves (exposing themselves to unnecessary debugging problems). Wouldn't you like to make this monitoring/debugging functionality already available for them in optional (off by default) build package?
