### ISSUE TITLE
.join and chained promises

### ISSUE THREAD

**Issue by kesteinbakk** [petkaantonov/bluebird#925]
I don't know if this is an issue or just me misunderstanding (probably the last one)

I have some custome promise functions:
```javascript
func1 = Promise.method(function(input) {
  // I do something
  return user.fetchAsync().then(function(data){
    // Do something with returned data
    return data
  });
});

func2 = Promise.method(function(input) {
  // Similar as func1 with returning some async operation chained with .then
});
```
Now, this seems to work just fine:
```javascript
    SomeAsync.then(func1).then(func2).then(function(returnData){
      //handle return data from func2
    })
```
If I instead wanted to run those two functions in parallel, I had expected that this would work:
```javascript
    SomeAsync.then(Promise.join(func1, func2, function(resFunc1, resFunc2){
      if (resFunc1 && resFunc2)
         return true
      }
    })
```
But it fails with "Then only acepts functions but was passed [object Object]"

Then I tried this:
```javascript
    SomeAsync.then(function(){
      return Promise.join(func1, func2, function(resFunc1, resFunc2){
      if (resFunc1 && resFunc2)
         return true;
      }
    })
```
But it also fails, not running func1 nor func2

So, how can I get Bluebird.method functions (returning chained promises) to execute in parallel?

**Comment by petkaantonov** [comment]
The syntax to run a function (function call) is `functionName(argument1, argument2, argument3...)`  or just `functionName()` in case of no arguments:

```js
    SomeAsync.then(function(){
      return Promise.join(func1(), func2(), function(resFunc1, resFunc2){
      if (resFunc1 && resFunc2)
         return true;
      }
    })
```

**Comment by bergus** [comment]
Just saying, if your functions always return promises and you don't expect them to throw, there's no point in wrapping them in `Promise.method`. They're just normal, promise-returning functions.

**Comment by kesteinbakk** [comment]
They don't always return promises and I throw errors in them (tried to simplify my semi-code to illustrate my problem). I still don't understand how I can run func1 and func2 in parallel, instead of .then(func1).then(func2)

Thanks anyway.

Sendt fra min iPhone
