### ISSUE TITLE
Not loading via Webpack but CDN works fine

### ISSUE THREAD

**Issue by simkessy** [petkaantonov/bluebird#930]
I'm having this strange issue where if I load Bluebird using the CDN link in my index file, my application works fine, but when remove the CDN and bundle bluebird using webpack, I get an error saying the `settle` function doesn't exist

>TypeError: Promise.settle is not a function

From what I can see, the library isn't making the necessary changes to the native Promise object. Not sure why it works on way (CDN through index.html) but not through Webpack

**Comment by simkessy** [comment]
I was able to get it working by changing 

```
require('bluebird')
```

to 

```
require('expose?Promise!bluebird');
```

**Comment by psulek** [comment]
Or you can left `require('bluebird')` and setup webpack as this:
`new webpack.ProvidePlugin({
                'Promise': 'bluebird'
});`
