### ISSUE TITLE
Going from .settle() to .reflect

### ISSUE THREAD

**Issue by simkessy** [petkaantonov/bluebird#931]
I updated my version of bluebird and noticed that `.settle()` is being deprecated. I use this twice in my application and I'm not sure how to get `.reflect()` to work. 

```
        //WHEN ALL WEBCALLS COMPLETED
        Promise.settle(self.itemsPromise)
        .then(function(data) {
          d.resolve(self.itemsPromise);
        });

      return Promise.settle(self.listsPromise).then(self.FindLibraries);
```
I've tried going `self.itemsPromise.reflect()` or `Promise.resolve(selt.itemsPromise).reflect` but neither work.

**Comment by bergus** [comment]
Wait, what is `d.resolve()`? This code is weird even without noting that `settle` is deprecated.

**Comment by benjamingr** [comment]
`Promise.settle(promises)` is the same thing as `Promise.all(promises.map(x => x.reflect()))`. 

Please ask support question in the appropriate support channels as listed in contributing.md, the site and the home page next time.
