### ISSUE TITLE
Promise.promisifyAll(require('fs')) node 4.2.3 not working

### ISSUE THREAD

**Issue by marcofranssen** [petkaantonov/bluebird#932]
I figured that the `Promise.promisifyAll(require('fs'))` does not work for the node file system library. I guess it is because they are not using the Async method postfix. For this module all methods are async by default. In node 4.2.3 they do have the sync variants in place by postfixing the method with Sync.

As a workarround I just used the promisify method for a single method. Although I can use it like that it is not really convenient as I have to do it for many methods.

Can the promisifyAll be made compatible again with this filesystem module?

**Not working**
```javascript 
let fs = Promise.promisifyAll(require('fs'));

fs.readFile('somefile').then(function (stream) { console.log(stream); });
```

**Working**
```javascript 
let fs = require('fs'),
    readFile = Promise.promisify(fs.readFile);

readFile('somefile').then(function (stream) { console.log(stream); });
```

**Comment by benjamingr** [comment]
Bluebird adds the `Async` suffix to the methods promisified via `promisifyAll` (that's configurable, as shown in the docs):

```
let fs = Promise.promisifyAll(require('fs'));
fs.readFileAsync('somefile').then(console.log);
```

This did not change in any version of Node over the past two years.
