### ISSUE TITLE
Minor optimisation, discussion of on arguments section in "Optimization killers"

### ISSUE THREAD

**Issue by cefn** [petkaantonov/bluebird#939]
Thanks hugely for your page on v8 optimisation (https://github.com/petkaantonov/bluebird/wiki/Optimization-killers)

Given your inline-slice function is aiming to be as super-efficient as possible, thought it would be worth mentioning this optimisation to avoid a variable declaration...

    var $_len = arguments.length;var args = new Array($_len); for(; $_len-->0;) {args[$_len] = arguments[$_len];}

...instead of the original...

    var $_len = arguments.length;var args = new Array($_len); for(var $_i = 0; $_i < $_len; ++$_i) {args[$_i] = arguments[$_i];}

...although this speedup may be eliminated by v8 optimisation of for loops anyway, perhaps.

Although your inlining strategy is best for performance, those who don't have a 'build step' allowing macros may benefit from the speedup by handing off to another function which itself can be optimised, combining the optimisation of apply, length access and access by index

```javascript
function argsToArray(){
    var $_len = arguments.length;
    var args = new Array($_len);
    for(; $_len-->0;) {args[$_len] = arguments[$_len];}
    return args;
}
```

...which can be called as follows, avoiding optimisation penalties for both caller and callee...

```javascript
    argsToArray.apply(null, arguments);
```

Does this sound reasonable? Is it worth adding this note? Also perhaps there's no penalty for a function not being optimised if the only single thing it does is pass off the arguments array? For example, this existed in our production code...

```javascript
return tree.addTopicGlobListener(type, topicGlob, function(id, value){
                emitter.emit.call(null, Array.prototype.slice.apply(arguments)) 
}, catchupEvents, catchupTopics)
```

...and I wonder whether this should actually be...

```
return tree.addTopicGlobListener(type, topicGlob, function(id, value){
                emitter.emit.call(null, argsToArray.apply(null, arguments)) 
}, catchupEvents, catchupTopics)
```

...or whether it would make no difference at all since there's no code apart from the arguments handoff.

Out of interest I found that the following didn't conflict with optimisation either, but the raw performance of this call being better than explicit assignment would rely on array creation and concatenation being optimised by the JS engine, and I'm suspicious of concat generally.

```javascript
var arr = Array.prototype.concat.apply([], arguments);
```

P.S. For reference the above production example (TopicGlobListener) is an EventStream adapter, so the translation to Array and use of emitter.call (not apply) is deliberate to pass in the arguments from a listener as a single array argument to the stream handler, hence need for the arguments munging.

**Comment by petkaantonov** [comment]
`.apply` is too unreliable, if you add any property to a function it will stop working

**Comment by cefn** [comment]
Do you mean that if I do something like argsToArray.hello = "world" to my argsToArray function then the argsToArray.apply trick I described will no longer avoid deoptimisation?

**Comment by petkaantonov** [comment]
Yes, perhaps that caveat could be documented along with the alternative method

**Comment by phpnode** [comment]
I believe (but could be wrong) that the alternative you suggested here will cause V8 to create a sparse array because you assign the elements in reverse index order:

```js
var $_len = arguments.length;var args = new Array($_len); for(; $_len-->0;) {args[$_len] = arguments[$_len];}
```
