### ISSUE TITLE
Phantomjs 2.0 Errror.stack is not writable causing "Promise was rejected with a non-error"

### ISSUE THREAD

**Issue by unional** [petkaantonov/bluebird#942]
```js
describe('map', function() {
    it.only('should...', function() {
        var array = ['a'];

        return Promise.map(array, function(i) {
          throw new Error('xyz');
        });
    });
});
```

result:
```
WARN: 'Warning: a promise was rejected with a non-error: [object Error]' 
PhantomJS 2.0.0 (Windows 8 0.0.0) map should... FAILED
        xyz
```

Nested one more layer:
```js
describe('map', function() {
    it.only('should...', function() {
        var array = ['a'];

        return Promise.map(array, function(i) {
          return Promise.resolve().then(function() {
            throw new Error('xyz');
          });
        });
    });
});
```

result:
```
WARN: 'Warning: a promise was rejected with a non-error: [object Error]' 
WARN: 'Warning: a promise was rejected with a non-error: [object Error]' 
PhantomJS 2.0.0 (Windows 8 0.0.0) map should... FAILED
        xyz
```

**Comment by benjamingr** [comment]
Guess - Phantom uses two sets of errors (for client and server),
Proposed solution - check if it's an `Error` or the constructor name contains the string `Error`.

**Comment by benjamingr** [comment]
Ok, looking at the code that's not it - it appears like it doesn't have a stack.

We should probably include a `|| ('constructor' in reason && reason.constructor.name.indexOf("Error") > -1)`

Or something like that.

**Comment by unional** [comment]
By the way, should this be a phantomjs bug also? We can put a patch in bluebird to handle this issue while waiting for phantomjs to fix.

**Comment by petkaantonov** [comment]
What do you propose for a fix? We cannot use `.toString.call() === "[object Error]"` because user errors are `[object Object]`

**Comment by benjamingr** [comment]
rejections are rare, walk the prototype chain and check any constructor name for "Error"

**Comment by unional** [comment]
When detecting whether if it is an Error or not, why do we have to rely on `canAttachTrace()`? if `obj instanceof Error` is true while stack is not writable, isn't it still a valid `Error`?

**Comment by petkaantonov** [comment]
If trace cannot be attached then it might as well not be an error anyway

**Comment by unional** [comment]
According to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
stack is non-standard.

**Comment by petkaantonov** [comment]
A non standard property will be writable if not supported at all

**Comment by unional** [comment]
So that's why it should be a bug on `phantomjs`?

**Comment by petkaantonov** [comment]
huh? The problem with phantomjs is they have different Error identity so that `instanceof Error` is returning false. This has nothing to do with .stack not being writable, which it always is, unless the user for some reason has made it unwritable by using ES5 reflection APi.

**Comment by unional** [comment]
Well, then why in `phantomjs` `instanceof Error` returning false?  I was doing `throw new Error(...)`, so it should have work correctly. :rose:

**Comment by unional** [comment]
Just tested:
`new Error('abc') instanceof Error` is true

**Comment by petkaantonov** [comment]
Because there are multiple error identities. It is similar when you get an array from iframe it will not match `instanceof Array` and instead you must use `{}.toString.call === "[object Array]"`.

**Comment by unional** [comment]
Ok. My finding is that
It does have stack, it is just not writable.
`es5.isPropertyWritable(new Error(), 'stack')` is false.

**Comment by petkaantonov** [comment]
I see. I wonder why would phantom make it non writable

**Comment by unional** [comment]
It means this code:
```
            var trace = util.ensureErrorObject(reason);
            var hasStack = trace === reason;
            if (!hasStack && !ignoreNonErrorWarnings && debug.warnings()) {
              var message = "a promise was rejected with a non-error: " + util.classString(reason);
              this._warn(message, true);
            }
```
is just not right. At best the message is `a promise was rejected with an Error that I can attach trace to`.

**Comment by unional** [comment]
When I do `console.log((new Error()).stack)`, it does print out stack trace.

**Comment by petkaantonov** [comment]
Yes but bluebird needs to modify the stack to show you the full stack trace, not just where the error was immediately created. The intention of the warning is to discourage practices which would prevent this, because then you will see no stack traces or very limited stack traces.

**Comment by unional** [comment]
Ok. Let me submit a PR on this.

**Comment by unional** [comment]
Proposal:

Since it rejects the error back to user, I can't use any fake errors (in. `errors.js`) as a vehicle to carry the stack around.

At best I can give a better warning, skip `attachExtraTrace`, and get the existing error back to the user.

What do you think?

**Comment by unional** [comment]
Should I file an issue on `phantomjs` about this so they **might** consider to make `stack` writable?

**Comment by unional** [comment]
https://github.com/kriskowal/q/issues/579

**Comment by unional** [comment]
Found it issue on phantomjs, although don't know how to fix it:
https://github.com/Vitallium/qtwebkit/blob/phantomjs/Source/JavaScriptCore/interpreter/Interpreter.cpp#L694

**Comment by benjamingr** [comment]
Remove the `ReadOnly |` bit? :D
