### ISSUE TITLE
disposer() doc doesn't show how to use it

### ISSUE THREAD

**Issue by ralt** [petkaantonov/bluebird#943]
http://bluebirdjs.com/docs/api/disposer.html

This is showing examples of how to *implement* the disposer, but nothing about its usage.

Should it be there? Or at least a link to `Promise.using` page?

**Comment by benjamingr** [comment]
Yes, feel free to make a docs PR :)

**Comment by spion** [comment]
Is this update good enough? https://github.com/petkaantonov/bluebird/pull/944
