### ISSUE TITLE
mapSeries documents

### ISSUE THREAD

**Issue by pevers** [petkaantonov/bluebird#945]
From the example from the documents http://bluebirdjs.com/docs/api/promise.mapseries.html it looks like mapSeries is chainable with then. Is this right? Because I can't find the example on https://jakearchibald.com/2014/es7-async-functions/ and it doesn't seem to be implemented (any more?).

```js
    .then(function(story) {
      addHtmlToPage(story.heading);
      return story.chapterURLs.map(getJSON);
    })
    .mapSeries(function(chapter) { addHtmlToPage(chapter.html); }) // HERE
```

**Comment by benjamingr** [comment]
@pevers mapSeries is a bluebird function. That article is not about bluebird promises.

**Comment by pevers** [comment]
I see but the article is linked in the code example. What I'm trying to say is that the bluebird mapSeries API documentation contains example code that makes no sense, right?

**Comment by spion** [comment]
The source is where the example task comes from, and the page contains a reimplementation in Bluebird. Is that confusing?

**Comment by pevers** [comment]
@spion, ah ok I get it. I thought the example was about bluebird mapSeries. My bad.
