### ISSUE TITLE
Question: Cancellation integration with any/all etc.

### ISSUE THREAD

**Issue by SimonSchick** [petkaantonov/bluebird#946]
I started playing around with cancellation today, and one of the first things that came to my mind is aborting parallel operations when a single one fails.

On example would be this:

```javascript
const Promise = require("bluebird");

Promise.config({
	cancellation: true
})

Promise.any([
	new Promise((res, rej, can) => {
		setTimeout(res, 1000);
		can(() => console.log("woo"));
	}),
	new Promise((res, rej, can) => {
		setTimeout(res, 2000);
		can(() => console.log("boo"));
	})
])
.then(() => console.log("done"));
```
With cancellation enabled I kind of expected the slow promise to be cancelled, but it wasn't.

On the other hand, with Promise.all/.all, how would I automatically cancel all other concurrently running promises?

As this:
```javascript
const Promise = require("bluebird");

Promise.config({
	cancellation: true
})

Promise.all([
	new Promise((res, rej, can) => {
		setTimeout(rej, 1000);
		can(() => console.log("woo"));
	}),
	new Promise((res, rej, can) => {
		setTimeout(res, 2000);
		can(() => console.log("boo"));
	})
])
.then(what => console.log("done"), err => console.error(err));
```
Also doesn't invoke any rejection handlers.

Assuming this is intended behavior, what would be the "proper" way to do this?

**Comment by benjamingr** [comment]
Where are you cancelling anything? You didn't cancel the `.all`

@petkaantonov  - I think any cancelling would probably be a good/nice idea (also for `race`) as it fits with the disinterest semantics. Opinion?

**Comment by spion** [comment]
As far as I know, cancellation does propagate through `Promise.all`. But I'm pretty sure current semantics of that are kinda buggy:

```js
Promise.config({ cancellation: true })

var p1 = Promise.delay(1000).then(_ => console.log("1")).finally(_ => console.log("1f"))
var p2 = Promise.delay(2000).then(_ => console.log("2")).finally(_ => console.log("2f"))

var p121 = Promise.all([p1, p2]).then(_ => console.log("OK1"))

var p122 = Promise.all([p1, p2]).then(_ => console.log("OK2"))

Promise.delay(500).then(_ => p121.cancel())
```

Last line will cancel everything, not just p12: https://jsfiddle.net/hkuv9fzq/

**Comment by petkaantonov** [comment]
@spion promise all isn't incrementing reference counts when simulating .then() calls on the input promises, that will be painfully to implement since it's hard to know when an internal should increment reference count and when not.

**Comment by petkaantonov** [comment]
as for the main issue, like @benjamingr said, you aren't cancelling the promise anywhere. It works just fine when I do call cancel: https://jsfiddle.net/kzoqg66z/2/

**Comment by SimonSchick** [comment]
I think I failed to get my point across, sorry.

As for `any` I was wondering if there was a way to *automatically* cancel all other promises after the first one resolved, and for `all/map/etc.` to cancel all the others once a promise rejected.

**Comment by petkaantonov** [comment]
yes but not from the library since it would clutter the API

```js
function all(promises) {
      return Promise.all(promises).catch(function(e) {promises.forEach(p => p.cancel());});
}
```

**Comment by benjamingr** [comment]
@petkaantonov yes, but it does make sense for `.any` to try and cancel the other promises on its own if cancellation is enabled. Same for `.some` and `.race`

**Comment by petkaantonov** [comment]
on it's own without specifying it would be too magical

**Comment by dmethvin** [comment]
Agreed, not by default. Maybe `.raceNorthKoreanStyle` where the first to finish is returned and the others are terminated for the failure and shame they have brought.

**Comment by benjamingr** [comment]
Why? Cancellation has disinterest semantics.

**Comment by petkaantonov** [comment]
But any/all/some don't. Those calling cancellation implicitly would effectively give them disinterest semantics which they don't have necessarily.

```js
Promise.all([a, b]).then(...)

// Imagine after 150ms a rejects

setTimeout(function() {
    b.then(function() {
        console.log("hello")
    })
}, 250);
```

If Promise.all automagically cancelled promises when one rejected, this code would behave differently

**Comment by benjamingr** [comment]
You're completely right. It would be interesting to entertain the typical case but not the default for sure.

**Comment by SimonSchick** [comment]
Would anything like:

```javascript
Promise.any([...], { autoCancel: true})
```
 be feasible?

**Comment by spion** [comment]
@petkaantonov why is it hard to know? Is it because the derived promise would have to keep a reference to the original list of promises?

To me its obvious that the right (not sure about performant) way to go is for every derived promise to increment the count and for every cancellation of that derived promise to decrement it (if it hits 0, propagate cancellation)

**Comment by petkaantonov** [comment]
e.g. bind does up to 3 internal thens but it should count as one reference

**Comment by benjamingr** [comment]
I don't remember why I reopened this. Anyway, if interested a feature request should be a separate issue.
