### ISSUE TITLE
wForgottenReturn can't be set with environment

### ISSUE THREAD

**Issue by ufo22940268** [petkaantonov/bluebird#948]
[It](http://bluebirdjs.com/docs/api/promise.config.html) says the `wForgottenReturn` can be set alone.

But i tried the following ways, still got the `Warning: a promise was created in a  handler but was not returned from it` warning.

        BLUEBIRD_WARNINGS=1 BLUEBIRD_W_FORGOTTEN_RETURN=0 node app.js

        BLUEBIRD_W_FORGOTTEN_RETURN=0 node app.js

**Comment by petkaantonov** [comment]
You are probably getting the warning from a version of bluebird that doesn't recognize the flag. Make sure all bluebird instances used in the app (by other libraries) also are using the version that recognized the flag.
