### ISSUE TITLE
Feature request: Execute bluebird tests in browsers as part of CI

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird#950]
Travis CI allows integration with sauce labs:
https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by benjamingr** [comment]
We used to have this, but this didn't work often.

**Comment by lextiz** [comment]
What were the reasons? On Travis side or sauce labs?

**Comment by petkaantonov** [comment]
sauce labs timing out often

**Comment by lextiz** [comment]
https://github.com/travis-ci/travis-ci/issues/2718, people report similar issue to be fixed, maybe this worth another try?

**Comment by petkaantonov** [comment]
I have planned readding browsers to CI when I get good chunk of free time again
