### ISSUE TITLE
Example usage of static Promise.bind

### ISSUE THREAD

**Issue by DeX3** [petkaantonov/bluebird#951]
Hello there,

I'm struggling to figure out how to use the static form of `Promise.bind`. The docs state no example and I can't decipher what the docs say regarding its static use:

    Promise.bind(
        any|Promise<any> thisArg,
        [any|Promise<any> value=undefined]
    ) -> BoundPromise
    
    Create a promise that follows this promise or in the static method is
    resolved with the given value, but is bound to the given thisArg value.

wat?

I often use `.bind` to avoid closures like this:

    somethingAsync()
    .bind( {} )
    .then( function( resultNeededLater ) {
      this.result = resultNeededLater;

      return moreAsyncStuff();
    } )
    .then( function() {

      // use this.result here
    } );

However, sometimes I want to kickstart a promise chain with a bound context, which currently I do like the following:

    Promise.resolve()
    .bind( {} )
    .then( function() {
      // ...
    } );

I'm guessing I can use the static `bind` to avoid the the (kind of weird) call to `Promise.resolve()`, but I can't find out how...

**Comment by spion** [comment]
`Promise.bind({}).then(...)` should work fine. 

The second argument is only useful if you have an external thenable that may not have `bind`:  `Promise.bind({}, thenable)`

**Comment by DeX3** [comment]
Aaaand I missed the most obvious use case. Thanks for the quick help :thumbsup:
