### ISSUE TITLE
Promise.props does not fail if one promise fail on 3.1.1

### ISSUE THREAD

**Issue by oliveti** [petkaantonov/bluebird#956]
Hi,

I'm currently using bluebird with props : 

            Promise.props(promises).then(function (response) {
               //do something
            }).catch (function ( response ) {
                console.log("error");
            }).finally (function () {
                console.log("finaly");
            });

The issue is, if a promise fail, neither the catch or the finally block of code are reached.

Does anyone has the same issue ?

Thank you for you help.

**Comment by oliveti** [comment]
One of the request was in error but the promise was not properly rejected, now it's working.

**Comment by phpnode** [comment]
@oliveti if there's not a problem with the library it's a good idea to close the issue.
