### ISSUE TITLE
Manual promisification anti-pattern doc needs more details

### ISSUE THREAD

**Issue by nathanmarks** [petkaantonov/bluebird#957]
In the documentation, using `new Promise.....` to wrap a traditional callback is presented as an anti-pattern and called "re-inventing the square peg".

However, it does not explain the significance of using bluebird's promisification at runtime which can result in some extremely high CPU usage -- manual promisification in this situation offers much better performance.

I understand the best practice is to promisify on init, but I've seen some situations where this has not been possible and the methods have been promisified after a factory is called during runtime.

**Comment by petkaantonov** [comment]
There's also `Promise.fromCallback`
