### ISSUE TITLE
Looks like Promise.mapSeries will iterate all items before return

### ISSUE THREAD

**Issue by xiaogaozi** [petkaantonov/bluebird#960]
According to the [documentation](http://bluebirdjs.com/docs/api/promise.mapseries.html):

> The iterator won't be called for an item until its previous item, and the promise returned by the iterator for that item are fulfilled.

But in my test, the given `Iteratable` will be called unconditional even there's promise be rejected. This's my test script (Bluebird v3.1.1):

```javascript
var bluebird = require('bluebird');

var myIterable = {};
myIterable[Symbol.iterator] = function* () {
  console.log('Yield first item');
  yield bluebird.reject(new Error('first item rejected'));
  console.log('Yield second item');
  yield bluebird.resolve('some value');
};

bluebird.mapSeries(myIterable, i => i)
  .then(items => {
    console.log('Items:', items);
  })
  .catch(err => {
    console.log('Some error: %s', err.message);
  });
```

Expect output:

```
Yield first item
Some error: first item rejected
```

Actual output:

```
Yield first item
Yield second item
Some error: first item rejected
```

Point out me if I have any misunderstanding, thanks.

**Comment by xiaogaozi** [comment]
After looking the source code, maybe the [`asArray()`](https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L286-L307) function is the problem?

**Comment by benjamingr** [comment]
I wonder - what do native promises do here?

**Comment by petkaantonov** [comment]
Iterator is treated as an alternative to array, there is no magic with regards to asynchronous iterators.

**Comment by petkaantonov** [comment]
Btw, "iterator" in that documentation refers to your `iterator` callback function, not to ES6 iterators. That is probably confusing.

**Comment by benjamingr** [comment]
Petka, wouldn't it make sense to iterate the iterator lazily? It sounds like a nice and easy optimization. Native promises question was misguided - I forgot all the methods (race/all) have to run the iterator anyway.

**Comment by petkaantonov** [comment]
Rewriting all collection methods is far from easy and doesnt make any sense for this case which shoukd just use Promise.coroutine.

**Comment by xiaogaozi** [comment]
@petkaantonov Hi Petka, could you show me the `Promise.coroutine` version code?

**Comment by petkaantonov** [comment]
```js
var bluebird = require('bluebird');

var iterator = bluebird.coroutine(function* () {
  console.log('Yield first item');
  var a = yield bluebird.reject(new Error('first item rejected'));
  console.log('Yield second item');
  var b = yield bluebird.resolve('some value');
});

iterator().then(function(items) {
    
});
```

**Comment by xiaogaozi** [comment]
Very thankful for this example!
