### ISSUE TITLE
promise.bind(this, args) ignores args

### ISSUE THREAD

**Issue by yamsellem** [petkaantonov/bluebird#967]
The [bind docs](http://bluebirdjs.com/docs/api/promise.bind.html) says:

```javascript
Promise.bind(
    any|Promise<any> thisArg,
    [any|Promise<any> value=undefined]
)
```

This implies,`bind` method works as the native `function().bind(this, [..])`.
But arguments provided alongside `this` are ignored.

Maybe, I missing something here, but the following test should work, right?

```javascript
"use strict"

var Promise = require('bluebird'),
    assert = require('assert');

describe('Promise', function() {
    it('should bind arguments alongside this', function(done) {
        var Clazz = function() {
            this.value = 'fine';

            new Promise(function(resolve, reject) {
                resolve('worked');
            })
            .bind(this, 15)
            .then(function(number, value) {
                assert(this.value === 'fine');
                assert(number === 15); // fail here, 'cause number 15 is not transmitted
                assert(value === 'worked');

                done();
            });
        }

        new Clazz();
    });
});
```

_ps. Bluebird release 3.1.1_

**Comment by spion** [comment]
AFAIK, Promise.bind(this, value) is the equivalent of Promise.resolve(value).bind(this)

**Comment by petkaantonov** [comment]
`Promise.bind` is a static method and not the same as the instance method `.bind`

**Comment by yamsellem** [comment]
It sounds weird to me.
Is this a A+ standard?

A `bind` that is not a `bind`, is awkward, don't you think?

**Comment by phpnode** [comment]
@yamsellem `.bind()` isn't in promises A+ spec at all, A+ spec only deals with `.then()`

**Comment by petkaantonov** [comment]
The purpose of bind is to ensure a `this` value. The standard is who got it horribly wrong by also making it alternatively a `_.partial`.

**Comment by yamsellem** [comment]
@petkaantonov you may ask JS to change about that, but `Promise.resolve(value).bind(this)` or `_.partial` for the `bind` method is a matter of taste IMO. Doing something against the langage standard logic may be misleading for the rest of us.

At least, clearly state it in the docs ^^.

**Comment by petkaantonov** [comment]
The supported arguments and what they do are very clearly documented
