### ISSUE TITLE
When using .timeout(), I get a warning that says "cancellation is disabled"

### ISSUE THREAD

**Issue by JoshuaWise** [petkaantonov/bluebird#970]
In my code, I'm not using `.cancel()` at all.

From my understanding, `.timeout()` **rejects** a promise, not cancels it. But the whenever my timeout fires, I get a warning that says "cancellation is disabled". It appears that the timeout promise was rejected as expected.

Is there any difference with using `.timeout()` with cancellation disabled vs enabled? Why am I getting this warning?

**Comment by reidrankin** [comment]
See issue #891; it is indeed supposed to cancel the promise, if cancellation is enabled. The docs do omit this point, though.

**Comment by JoshuaWise** [comment]
I see, thanks for the info.
And thanks for the quick fix, petkaantonov..
