### ISSUE TITLE
Suggestion: a new warning about Promise created in fromCallback() or promisify()

### ISSUE THREAD

**Issue by ben-page** [petkaantonov/bluebird#972]
The new warnings are fantastic. They've revealed many design flaws that certainly would lead to very hard to track down bugs.

I think I've identified another situation that benefit from a warning: Creating a Promise inside of fromCallback or promisify by definition creates a runaway Promise. 

### Case 1 - A Promise created in the resolver function of fromCallback()
```javascript
function somethingAsync() {
    return Promise.resolve();
}

function fn(cb) {
    setTimeout(cb.bind(null, null, 'result'), 0);
}

Promise.fromNode(function (callback) {
    somethingAsync(); //runaway promise, no warning
    fn(callback);
});
```
There is good reason to do this. It could be refactored to call somethingAsyc in the outer Promise chain.
```javascript
function somethingAsync() {
    return Promise.resolve();
}

function fn(cb) {
    setTimeout(cb.bind(null, null, 'result'), 0);
}

somethingAsync()
    .then(function() {
        return Promise.fromNode(function (callback) {
            fn(callback);
        });
    });
```

### Case 2 - A Promise created in up the call stack the resolver function of fromCallback()
```javascript
function somethingAsync() {
    return Promise.resolve();
}

function fn(cb) {
    somethingAsync(); //runaway promise, no warning
    setTimeout(cb.bind(null, null, 'result'), 0);
}

Promise.fromNode(function (callback) {
    fn(callback);
});
```
This could refactored so that fn returns a Promise. If fn() is aware of Promises internally, there is no reason for it to use an callback.
```javascript
function somethingAsync() {
    return Promise.resolve();
}

function fn(cb) {
    return somethingAsync()
        .then(function() {
            return Promise.resolve(true);
        });
}

fn();
```

I think there should be a warning anytime a Promise is created inside fromCallback() or promisify. Doing so will always be problematic and should be avoided.

Rather than the existing runaway Promise warning, I think a new warning is a good idea. Although the issue is still (in essence) about runaway Promises, there is no mechanism for attaching these Promises to the outer promise chain. So the solution has to be different than other runaway Promises. ie. Most runaway Promises can just be returned or attached to the Promise chain. These cases must be refactored.

Thoughts?

**Comment by ben-page** [comment]
I suppose the same rules should apply to a Promise create in the Promise constructor that is not passed to the resolve or reject functions.

```javascript
new Promise(function(resolve, reject) {
    Promise.resolve(); //trigger new warning
    resolve(Promise.resolve()); //no warning
});
```

**Comment by benjamingr** [comment]
@ben-page can you come up with a case where your last example is not an anti pattern? (Passing promise to `resolve` in the constructor).

**Comment by ben-page** [comment]
No, but at least the promise is attached to the chain. I think the issue is out of the scope of this warning.

But you make a good point. It could be helpful to create a warning about passing a Promise to resolve() or reject().

**Comment by petkaantonov** [comment]
Please use fromNode/promisify to do API translation only, don't put additional logic in there.

**Comment by ben-page** [comment]
@petkaantonov, I agree. I'm suggesting a warning to let users know not to do do that.

**Comment by petkaantonov** [comment]
I don't think that's common enough to warrant a warning. 

Passing promise to `resolve` is an intended feature (even in constructor) while passing promise to reject will already warn.
