### ISSUE TITLE
Promisification of functions not following error-first convention

### ISSUE THREAD

**Issue by felixfbecker** [petkaantonov/bluebird#974]
Node's very own modules include functions that callback with the result directly, like [readline question](https://nodejs.org/dist/latest-v5.x/docs/api/readline.html#readline_rl_question_query_callback). How can this be promisified?

When you have to ask the user multiple questions you get into pyramid of doom very quick.

There should be an option to promisify like `{errorFirst: false}` to allow to promisify these functions aswell.

**Comment by petkaantonov** [comment]
With custom promisifier:

```js
Promise.promisifyAll(readline, {
    promisifer: function(fn) {
        return function(...args) {
            return new Promise(resolve => {
                args.push(resolve);
                fn.apply(this, args);
            });
        }
    }
});
```

**Comment by felixfbecker** [comment]
@petkaantonov That is a lot of code for such a simple thing... Cant we have a simple option for that?

**Comment by felixfbecker** [comment]
It actually makes the code harder to understand in my case as if I just used callback API.

**Comment by benjamingr** [comment]
@felixfbecker that code is written _once and then used everywhere. Although to be honest, we're not interested in supporting non-standard API signatures.

If something uses the standard `(err, data)` convention that's cool - if it invents its own convention then we're not interested in catering for anything else. You are of course welcome to use whatever tools you want. 

`readline` only looks this way for historical reasons. It (and `.exists`) are historical mistakes - not the norm.
