### ISSUE TITLE
Docs mention "core build", but the link gives a "File not found"

### ISSUE THREAD

**Issue by JoshuaWise** [petkaantonov/bluebird#976]
In the [docs](http://bluebirdjs.com/docs/getting-started.html), it mentions a `core build`, which I'm guessing is smaller than the `full build`. Unfortunately, the `core build` link goes nowhere, and I can't find any documentation about the differences between the two builds.

**Comment by benjamingr** [comment]
This is a known issue, @petkaantonov is working on it today. See also https://github.com/petkaantonov/bluebird/issues/757

**Comment by JoshuaWise** [comment]
Oh, great, thanks.

**Comment by petkaantonov** [comment]
lol I am not working on that?

**Comment by benjamingr** [comment]
@petkaantonov then what did you mean by "the build should produce the files now" 0_o?

**Comment by petkaantonov** [comment]
Well they still didn't end up on npm and on top of that, we also need to publish those files on the cdnjs configuration

**Comment by benjamingr** [comment]
Fixed by Petka - links now lead to the file.

**Comment by JoshuaWise** [comment]
There's still no documentation about the different between the full build and the core build. What does the core build include/exclude?

**Comment by petkaantonov** [comment]
It used to be documented but I guess it was lost in 2 -> 3 docs migration. For now you could infer from the file header what features are missing from core.
