### ISSUE TITLE
[Question] Are async operations completed before calling the next then?

### ISSUE THREAD

**Issue by McFarts** [petkaantonov/bluebird#977]
Lord have mercy on my pitiful code...but please cut me some slack. Still learning bluebird.

```
if (user) {
					redis.del('username:' + user.RPG.username.toLowerCase());
					if (user.RPG.channel) {
						redis.get('channels:' + user.RPG.channel)
							.then(function(data) { // Remove user from their channel on Redis
								if (data) {
									data.splice(data.indexOf(user.RPG.username.toLowerCase()), 1);
									redis.set('channels:' + user.RPG.channel, data).then(function(a, b) {
										//Notify everyone else in this Redis channel that this user has left.
										data.forEach(function(value) {
											redis.hgetall('username:' + value, function(error, data) {

												publish(data.server, {
													user_id: data.user_id,
													message: 'OQ ' + user.RPG.user_id
												});

											})


										})



										delete users[socket.user_id];

									});

								}
							}).then(function() {
								console.log('LERRRROY JENKINGS');

							});
					} else {
						delete users[socket.user_id];
					}
				}
```

See the Lerrory Jenkings log at the bottom inside that then function? Notice how I have code above that that is async? ForEach, `redis.hgetall`, and `publish` which is a function referencing back to use `redis.publish`.

Anyways, my question is will the text lerrror jenkings only be called **AFTER** ALL those operations in the previous `then` have completed? Even if they have a ton of async operations in them already?

**Comment by benjamingr** [comment]
Questions belong on StackOverflow or IRC or the DISQUS comments in the API docs and not in the issue tracker. 

The issue tracker is for feature requests and bug reports as well as discussing the future of the library. Not for support questions.

This is all written in the contributing.md file and in the readme as well as on the website.

**Comment by benjamingr** [comment]
Some reading:  http://stackoverflow.com/questions/22539815/arent-promises-just-callbacks promises aren't magical, they work by using `return` value of functions.
