### ISSUE TITLE
Exception on Bluebird 3.1.2 and node 0.12.2

### ISSUE THREAD

**Issue by asafyish** [petkaantonov/bluebird#978]
Hi,

I am getting this exception after upgrading to Bluebird 3.1.2:
TypeError: Cannot redefine property: length
at defineProperty (native)
at Function.Promise.coroutine (/home/ubuntu/services/sender/source/node_modules/bluebird/js/release/generators.js:188:5)

Looks like something that was added in https://github.com/petkaantonov/bluebird/commit/6bd757e8595c9d58191d0d22d66100f1dee3b234

Notice that I am using node 0.12.2, maybe length cannot be overridden there ?

**Comment by petkaantonov** [comment]
Sigh. I had a feeling it was too good to be true that there was a solution to modify .length

**Comment by benjamingr** [comment]
Node 0.12 has generators? I didn't even remember that, is that with a flag or without it? 

Anyway, this concerns me since having programs behave differently in two different versions of node is probably a bad idea.

**Comment by asafyish** [comment]
with --harmony

**Comment by benjamingr** [comment]
@petkaantonov to be fair, it's supposed to be configurable http://www.ecma-international.org/ecma-262/6.0/index.html#sec-functioninitialize so 0.12 is just using an old buggy version of v8 here - we can put a caveat for Node users with `--harmony`.

**Comment by asafyish** [comment]
I am fine with just adding a warning. 0.12 is indeed really old.

**Comment by petkaantonov** [comment]
@benjamingr still breaking code is not worth it here at all, it's just a pointless "nice to have" thing.

**Comment by renegare** [comment]
Thanks for the notice.
