### ISSUE TITLE
Installing version 3.1.4 with bower does not include the js/browser directory anymore

### ISSUE THREAD

**Issue by daedalus28** [petkaantonov/bluebird#979]
This caused breaking changes on our production application - was this intended to be removed, or is it a bug? I couldn't find any mention of it in the changelog.

**Comment by benjamingr** [comment]
I assume it was intended as I don't think the `js/browser` directory was ever meant to be a part of the distribution (rather, you can build it with the build tool).

That said, if it broke your code then it was certainly not intended for a bug fix release.

**Comment by petkaantonov** [comment]
I don't have bower and never will, but the release was made properly with the browser files:

```bash
$ rm -rf js/browser
$ git checkout v3.1.4
$ ls -l js/browser/
total 408
-rw-rw-r-- 1 petka petka 111743 tammi 25 19:07 bluebird.core.js
-rw-rw-r-- 1 petka petka  52357 tammi 25 19:07 bluebird.core.min.js
-rw-rw-r-- 1 petka petka 169153 tammi 25 19:07 bluebird.js
-rw-rw-r-- 1 petka petka  75312 tammi 25 19:07 bluebird.min.js

```

**Comment by daedalus28** [comment]
It's partially our bad for depending with a ~ version instead of a fixed number, but the js/browser directory is definitely not there with a fresh bower install of bluebird as of 3.1.4 and is in 3.1.1 (didn't test 3.1.2 or 3.1.3).

Happy to update if js/browser is not intended to be included in bower. For browser use which file should we be referencing from bower?

**Comment by petkaantonov** [comment]
As far as I understand, bower works by fetching the git tag. Which I just showed you has the browser files. It should work just fine, can you try in a completely separate and clean environment?

**Comment by daedalus28** [comment]
It seems to work now - very weird. Before I close this issue, is js/browser/bluebird.min.js the correct file to depend on moving forward?

**Comment by petkaantonov** [comment]
bluebird.js has all the features so it's most convenient yea

**Comment by ruimarinho** [comment]
@petkaantonov just an aside on bower - the version does not need to be tracked anymore on the bower manifest on each release as its use has been deprecated. One less file to update.

https://github.com/bower/spec/blob/master/json.md#version

**Comment by petkaantonov** [comment]
The field is automatically updated by a script, it would be more work to remove it :)
