### ISSUE TITLE
warning hook

### ISSUE THREAD

**Issue by Janpot** [petkaantonov/bluebird#980]
I'd like to add my own logging logic when it comes to displaying warnings. Would it be possible to add a hook to intercept these warnings so I can handle them myself?

```
process.on('bluebirdWarning', function (warn) {
  // ...
});
```

**Comment by benjamingr** [comment]
Related: https://github.com/nodejs/node/pull/4782

**Comment by benjamingr** [comment]
We should hold off until there's a node consensus and then decide if we want to reuse their hook if it's appropriate. In theory this sounds like a good idea if it's not too much work.

**Comment by petkaantonov** [comment]
Added as `'warning'` in 3.3. `'warn' alias will probably be added if node adds it as well since the api is the same (.name, .message, .stack). Still undocumented.
