### ISSUE TITLE
Checking if a Promise is Bluebird or not

### ISSUE THREAD

**Issue by jhyland87** [petkaantonov/bluebird#982]
Im writing some Mongoose model methods, and they require the Promise to be used. I found that can easily be done [like so](http://eddywashere.com/blog/switching-out-callbacks-with-promises-in-mongoose/):
```javascript
import Promise from 'bluebird'
import Mongoose from 'mongoose'
Mongoose.Promise = Promise
```
The Mongoose object is handed down to the Models, so that means that  Mongoose.Promise should be the Bluebird promise library.

How can I check if it is or isnt? Heres an example of what I mean:
```javascript
import Promise from 'bluebird' // Wont really need this, since it should be handed over via Mongoose.Promise 

module.exports = Mongoose => {
    // Mongoose.Promise.prototype.isPrototypeOf(Promise.prototype) // false
    // Mongoose.Promise.prototype.isPrototypeOf(Promise) // false
    // Mongoose.Promise instanceof Promise // false

    /* Basically, im trying to have my model error out if Mongoose.Promise is NOT Bluebird  */
}
```

**Comment by petkaantonov** [comment]
This issue tracker is for bug reports and feature requests. You can probably check for methods like promisifyAll and .bind to see if Promise is bluebird.
