### ISSUE TITLE
Errors being swallowed when binded to 'this'

### ISSUE THREAD

**Issue by luujam1** [petkaantonov/bluebird#983]
Taking the following example:

    window.addEventListener('unhandledrejection', function(e) {
       console.error(e);
    });

    var p = new Promise(function(resolve, reject) {
       console.log('start');
       resolve();
    });

    p.bind(this).then(function() {
       console.log('then');
       //this.callfunction here
       throw new Error('err');
    });

I expect the error to be caught in the unhandledrejection event listener and the error is outputted to console. This works fine when .bind(this) is not in the code but the error seems to be swallowed when used. Any explanation as to why this is the case would be much appreciated. Thanks.

**Comment by petkaantonov** [comment]
Which version are you using?

**Comment by luujam1** [comment]
3.0.5

**Comment by luujam1** [comment]
I can see it was fixed in version 3.1.0 in the changelog. Thanks
