### ISSUE TITLE
Benchmark setup seems to be biased against async callback style libraries

### ISSUE THREAD

**Issue by peterluhub** [petkaantonov/bluebird#985]
I cloned bluebird to my machine and ran the benchmark tests to find how out my async callback style library(under development) stands up against the known async libraries.  At first, the results were not surprising.  Bluebird came out on top in parallel with the current bluebird setup.  By changing the setup for callback style libraries(the way it should be, I think), the results were dramatically different.  The extra scope lookups and memory allocations make a whole lot of difference.

**The benchmark results from the original bluebird benchmark setup:**
-p 25
results for 10000 parallel executions, 1 ms per I/O op

|file|                                                      time(ms) | memory(MB)
|---|---|---|
|callbacks-baseline.js |                         261  |     63.12
|promises-bluebird.js |                          421  |    106.31
|callbacks-peterlu-asyncFlowF-parallel.js    |     469  |     93.04
|callbacks-suguru03-neo-async-parallel.js   |    516   |    96.25
|callbacks-caolan-async-parallel.js       |      842    |  157.09

**The results from the new benchmark setup:**
-p 25
results for 10000 parallel executions, 1 ms per I/O op

|file|                                                      time(ms) | memory(MB)
|---|---|---|
|callbacks-baseline.js          |                255    |   62.99
|callbacks-peterlu-asyncFlowF-parallel.js    |     285  |     73.48
|callbacks-suguru03-neo-async-parallel.js  |     303   |    75.03
|promises-bluebird.js                       |    423  |    106.30
|callbacks-caolan-async-parallel.js    |         611    |  139.36

Platform info:
Linux 3.10.0-229.20.1.el7.x86_64 x64
Node.JS 5.0.0
V8 4.6.85.28
Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz × 1

The changes I made to the setup:

New:
```javascript
function fileInsertFor(i, tx) {
    var ins = FileVersion.insert({index: i})
    return function(callback) {
            ins.execWithin(tx, callback);
    };
}
```
Original:
```javascript
function fileInsertFor(i, tx) {
    return function(callback) {
        FileVersion.insert({index: i}).execWithin(tx, callback);
    };
}
```

**Comment by petkaantonov** [comment]
As far as I can tell, all other implementations are calling FileVersion.insert like in the Original, not just callback version

**Comment by peterluhub** [comment]
Yes, they do, but the big difference is that the promise version does not carry FileVersion.insert around like the callback style does.  FileVersion.insert returns nothing but an object that has a few function pointers.  The promise version executes FileVersion.insert before the queries array gets passed to Promise.all.  So, the promise test run carries much less weight than the callback style version. And that is key of the issue.  The callback style test run does not need to execute FileVersion.insert later.  It can execute FileVersion.insert just like the promise version.  The same amount code is executed.  The difference is where is that piece of code is executed.

**The change I made doe not execute less amount of code.  It just changes how and where the code is executed.  Therefore, it is still fair comparing to the promise version.  The way you have it is definitely unfair to callback style test run.**

**Comment by petkaantonov** [comment]
*FileVersion.insert* starts a transaction and looking at async.js, your change would cause this code to start the transactions *outside* `async.parallel` which is not the desired behavior and not what all the other implementations are doing. Then If you changed `.parallel` to `parallelLimit` or whatever, the parallelLimit would not actually be able to control the concurrency.

**Comment by petkaantonov** [comment]
Promise.all is not comparable to `async.parallel` because `Promise.all` doesn't execute any code it simply listens to completion of *already* started promises.

**Comment by peterluhub** [comment]
As far as I can tell this line starts a transaction:
var tx = db.begin();

It runs before fileInsertFor.  So, my change is still within the transaction.  

Agree?

Also as the code stands now, FileVersion.insert does not nothing but return the function pointer to invoke execWithin.  If you make queryisht global, you dont need FileVersion.insert.  In fact, I tried that. 
For promise, the queries line inside the for loop becomes:

Old: queries[i] = FileVersion.insert({index: i}).execWithin(tx);
New: queries[i] = queryisht().execWithin(tx);

For callback style, the change is in fileInsertFor function:

Old: FileVersion.insert({index: i}).execWithin(tx, callback);

New: queryisht().execWithin(tx, callback);

 the results from a test after the change are compatible with the change I first suggested.

**Comment by petkaantonov** [comment]
I mean it starts/registers/whatever an insert operation. I think you are misunderstanding the purpose of the benchmark which is to actually try to be something like real code, not to take artificial shortcuts that wouldn't be possible when actually writing real code. FileVersion.insert is used in the original production code so it will not be removed or changed.

**Comment by spion** [comment]
In the original code, `FileVersion.insert({...})` creates a new instance of a `Query` object that contains the SQL and the parameters necessary to execute the query, as well as inherited methods such as `execWithin` that will send the query to the transaction object. It doesn't start any operation.

The bigger question here is, why is the same amount of work taking less time. Is it because the peak memory allocation is different?

**Comment by peterluhub** [comment]
Given the fact that my change is bonafide, can you change the status of this issue to open?

**Comment by petkaantonov** [comment]
Since it's your issue you should be able to open it as well

**Comment by benjamingr** [comment]
@spion in fact it's even stranger since there is a closure used after the change.

**Comment by benjamingr** [comment]
I see no change in performance in Node v6.5.0 between the benchmarks with the change and without it. Maybe it was a temporary issue with v8.

That said, it does look like neo async performs a lot better on v6.5 (like in the chart OP posted) and we should update the benchmarks page to reflect that.
