### ISSUE TITLE
How to implement `Unhandle reject` warning in bluebird?

### ISSUE THREAD

**Issue by XGHeaven** [petkaantonov/bluebird#986]
As we know, if `reject()` without `catch`, it show `unhandle reject undefined` warning.
```javascript
const Promise = require('bluebird')
Promise.reject() // show warning
Promise.reject().catch(() => {}) // not show

new Promise((resolve, reject) => {
    reject();
}) // show warning
new Promise((resolve, reject) => {
    reject();
}).catch(() => {}) // not show
```

How to implement this?

I guess call `process.nextTick` for register a check function to check `promise` if `catch`ed in next event loop, when create a new `Promise`.
Right? About I guess?

**Comment by benjamingr** [comment]
`.suppressUnhandledRejection`. Please don't use the issue tracker for support questions - see contributing.md or the README on where it is appropriate.

Also,  http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events http://bluebirdjs.com/docs/api/promise.onpossiblyunhandledrejection.html

**Comment by benjamingr** [comment]
OH, you're asking how bluebird implements this? It's kind of clever in bluebird but here's how I implemented it in Q : https://github.com/kriskowal/q/pull/643 

Also, see https://gist.github.com/benjamingr/0237932cee84712951a2
