### ISSUE TITLE
"illegal access" in debuggability.js

### ISSUE THREAD

**Issue by samuelneff** [petkaantonov/bluebird#987]
I'm upgrading from Node 0.12.9 to Node 4.2.3 and ran into an `illegal access` error in `debuggability.js`. I also tested with Node 5.5.0 and see the same error.

The error is this:

```
C:\app\2016-01-lib-upgrades\src\node_modules\bluebird\js\release\debuggability.js:535
    var firstStackLines = firstLineError.stack.split("\n");
                                        ^
 illegal access

C:\app\2016-01-lib-upgrades\src>
```

context:

```
function setBounds(firstLineError, lastLineError) {
    if (!longStackTracesIsSupported()) return;
    var firstStackLines = firstLineError.stack.split("\n");
    var lastStackLines = lastLineError.stack.split("\n");
    var firstIndex = -1;
    var lastIndex = -1;
```

I'm not actually using bluebird myself.. I'm using the Stripe API which uses bluebird. It was referencing bluebird 2.9.6 and I upgraded it to point to the latest 3.1.5. The error is the same in both versions, only the location is different (2.9.6 has it in capture_traces.js).

If I revert back to Node 0.12.9 I do not get the error.

Any suggestions?

Thanks,

Sam

**Comment by petkaantonov** [comment]
There is something else that is really screwing up your environment

**Comment by samuelneff** [comment]
I spun up an AWS EC2 Linux instance with Node 4.2.3 (latest supported on Elastic Beanstalk) and get the same error there.

Any suggestions on where to look would be helpful. Searches online turned up nothing relevant.

**Comment by petkaantonov** [comment]
I mean you are using some highly weird module or config which is affecting the stack property of all errors. You could egrep for "\bstack\b" in your node_modules for instance.

**Comment by samuelneff** [comment]
Thank for the tip, I'll look through the node_modules.

**Comment by benjamingr** [comment]
Cannot reproduce with the same settings AWS EC2 Linux Node 4.2.3 with clean build and bluebird. Ran test suite and everything passes.

Thanks for the report. Like Petka said - it's a weird module affecting the stack.

**Comment by alex-shamshurin** [comment]
Is this one https://github.com/petkaantonov/bluebird/issues/1252 related to the issue?
