### ISSUE TITLE
@3.2.0 npm browser build, global object reference error 

### ISSUE THREAD

**Issue by Okahyphen** [petkaantonov/bluebird#988]
Yo. I'm working on a project for browsers that is using bluebird via jspm/npm. Was working like a charm on `npm:bluebird@3.1.5`, but as soon as I bumped up to `npm:bluebird@3.2.0` `js/browser/bluebird.js` threw a ReferenceError in my face.

    Uncaught ReferenceError: global is not defined @ bluebird.js:816

The portion in question (`js/browser/bluebird.js@3.2.0`):

```javascript
var fireGlobalEvent = (function() {
    if (util.isNode) {
        return function() {
            return process.emit.apply(process, arguments);
        };
    } else {
        if (!global) { // Right here, line 816.
            return function() {
                return false;
            };
        }
        return function(name) {
            var methodName = "on" + name.toLowerCase();
            var method = global[methodName];
            if (!method) return false;
            method.apply(global, [].slice.call(arguments, 1));
            return true;
        };
    }
})();
```

Whereas `@3.1.5` seems to recheck the global object inside `fireGlobalEvent`.

```javascript
        var globalObject = typeof self !== "undefined" ? self :
                     typeof window !== "undefined" ? window :
                     typeof global !== "undefined" ? global :
                     this !== undefined ? this : null;

        if (!globalObject) {
            return function() {
                return false;
            };
        }
```

Issue with #929 ?

**Comment by Okahyphen** [comment]
Digging around, it looks like references to `global` were intended to be references to `util.global`.

**Comment by benjamingr** [comment]
Interesting, did you turn monitoring on in your setup?

**Comment by Okahyphen** [comment]
I did not turn on monitoring. Was just running out of the box. \o/

**Comment by petkaantonov** [comment]
@benjamingr did you verify your patch works? Otherwise I'm gonna have to revert the monitoring stuff, I don't have time to really get into this.

**Comment by petkaantonov** [comment]
@Okahyphen does 3.2.1 work for you?

**Comment by Okahyphen** [comment]
@petkaantonov Yep, looks great. Nice work. Will close this issue.
