### ISSUE TITLE
Feature request:  Allow caller of `asCallback` to cause callback to propagate to chained Promises

### ISSUE THREAD

**Issue by matthewadams** [petkaantonov/bluebird#995]
Currently, it appears that `.asCallback` must be called on each Promise that should use the callback.

I have a scenario whereby I'd like the callback passed to `asCallback` to propagate down the Promise chain if nothing is thrown, similar in behavior to many of the `async` methods (like `waterfall`, `each`, etc) that call the callback with a truey error as soon as there is one or that call the callback only once with a falsey error and the final return value.  If there is another way, please point me to it (http://bluebirdjs.com/docs/api/collections.html ?), since I may not be familiar enough with bluebird to know.

One suggestion I thought of was to allow the `asCallback` method to accept a second argument called `options`, that would take an object only one key of which would currently be used:  `chain`.  That way, a caller could instruct the Promise to pass along the callback if there's no error, else call the callback upon error.  The choice of an `options` object is simply to allow for future expansion; I'd be equally ok with another method like `asChainedCallback` or something similar.

While experimenting with how `asCallback` works right now, I created some test cases.  Then, I created some test cases for how the proposed behavior should work, basically to serve as behavioral specifications:
```
'use strict';
var Promise = require('bluebird');
var assert = require('assert');

describe('asCallback chaining enhancement', function () {

  it('should call unchained callback each time with happiness', function (done) {
    var c = 0;
    var f = 0;

    var callback = function callback(err, value) {
      assert.ifError(err);
      if (++c === 3) return done();
    };

    var fn = function (i) {
      assert.equal(i, f);
      return ++f;
    };

    var p = Promise.method(fn);

    p(0).asCallback(callback)
      .then(fn).asCallback(callback)
      .then(fn).asCallback(callback);
  });

  it('should call unchained callback with happiness then saddiness', function (done) {
    var c = 0;
    var f = 0;

    var callback = function callback(err, value) {
      if (err) {
        assert.equal(c, 2);
        assert.equal(f, 2);
        done();
      }
      c++;
    };

    var fn = function (i) {
      assert.equal(i, f);
      return ++f;
    };

    var p = Promise.method(fn);

    p(0).asCallback(callback)
      .then(fn).asCallback(callback)
      .then(function () {
        throw -1;
      }).asCallback(callback);
  });

  it('should call chained callback only once with happiness', function (done) {
    var f = 0;
    var finished = false;

    var callback = function callback(err, value) {
      assert.ifError(err);
      assert.equal(value, 3);
      assert(finished);
      done();
    };

    var fn = function (i) {
      assert.equal(i, f);
      return ++f;
    };

    var p = Promise.method(fn);
    p(0).asCallback(callback, {chain: true}) // pass down to chained promises
      .then(fn)
      .then(function (i) {
        finished = true;
        return fn(i);
      });
  });

  it('should call chained callback with midstream saddiness', function (done) {
    var f = 0;
    var finished = false;

    var callback = function callback(err, value) {
      assert(err);
      assert(finished);
      done();
    };

    var fn = function (i) {
      assert.equal(i, f);
      return ++f;
    };

    var p = Promise.method(fn);

    p(0).asCallback(callback, {chain: true}) // pass down to chained promises
      .then(function (i) {
        finished = true;
        throw -1;
      })
      .then(fn);
  });

  it('should call chained callback with final saddiness', function (done) {
    var f = 0;
    var finished = false;

    var callback = function callback(err, value) {
      assert(err);
      assert(finished);
      done();
    };

    var fn = function (i) {
      assert.equal(i, f);
      return ++f;
    };

    var p = Promise.method(fn);
    p(0).asCallback(callback, {chain: true}) // pass down to chained promises
      .then(fn)
      .then(function (i) {
        finished = true;
        throw -1;
      });
  });
});
```

**Comment by petkaantonov** [comment]
Please see http://bluebirdjs.com/docs/coming-from-other-libraries.html#coming-from-async-module

**Comment by matthewadams** [comment]
After reading the doc you referred me to, @petkaantonov, there was nothing about `asCallback`, but, for whatever reason, it made me try simply moving `asCallback` until after the last `then` and that made the difference; all tests passed.  I don't know why it didn't occur to me to try that before.  Perhaps adding a sample of this usage to http://bluebirdjs.com/docs/api/ascallback.html would've helped.  Thanks!
