### ISSUE TITLE
Question: warnings when creating Promises in Jasmine tests

### ISSUE THREAD

**Issue by alexlukelevy** [petkaantonov/bluebird#998]
I've read about the new warnings regarding [Promises not returning from handlers](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it) and had a related question...

In some of my unit tests, I stub out the functionality of certain dependencies to return promises using Jasmine's `spyOn` function. So with this new change, I am seeing quite a few warnings when my tests run. I can of course disable the warnings, but I wondered if there was an improved approach I could use that would naturally get rid of such errors?

Example:

```
    beforeEach(function (done) {
            
      var formatter = new Formatter();
      var promise = Promise.resolve(['1,000', '2.45']);
      
      spyOn(formatter, 'format').and.returnValue(promise);
      
      // internally calls formatter.format()
      doStuff(formatter, [1000, 2.4567]).then(done);

     // promise is not returned
    });

   // test cases
```

Can add a full working plunker if that would be of use?

**Comment by benjamingr** [comment]
Please ask support questions in the appropriate support channels as listed in the README and on the website. The issue tracker is exclusively for bug reports and feature requests.

**Comment by alexlukelevy** [comment]
Thanks @benjamingr. I have posted on [SO](http://stackoverflow.com/questions/35287107/warnings-from-bluebird-promises-in-jasmine-tests), but got no help so far...
