### ISSUE TITLE
Support for safari 5.x?

### ISSUE THREAD

**Issue by Dindaleon** [petkaantonov/bluebird#999]
Hello,

I am testing my app on safari `5.1.7` on my windows machine and I am getting the error: `"Can't find variable: Promise"` I read that safari does not support promises. So, Is there any way I can offer promise support on my app for safari users?

I am using babel 6.

**Comment by petkaantonov** [comment]
Please use stackoverflow or the mailing list to ask support questions. This tracker is for bugs/feature requests.
